### ISSUE TITLE
Ecto.Changeset.validate_change/3 should check field

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1107]
It's an issue I see often repeated - someone adding a validation on a field, but forgetting to add it to required or optional fields in cast.

I propose that we raise in `validate_change/3` if the field is not in the changes map, and is neither in `required` nor `optional` fields.

**Comment by josevalim** [comment]
Yes, that's one way to do it. Another option is to warn if a field is given to cast parameters but never used. If we warn with Logger.debug, we should be fine.

**Comment by tony612** [comment]
Yeah, this is a problem indeed. And I prefer warning in log.

**Comment by josevalim** [comment]
This will be for 2.1 or 2.2 because I would like to be able to disable the log and the API for such in 2.0 would be confusing.

**Comment by aphillipo** [comment]
I too had this problem.

Could it be even better to simply not have an optional fields key and just calculate them somehow, maybe with a macro?

**Comment by michalmuskala** [comment]
@josevalim I was looking into this, and I'm not sure what you meant by a field "not being used". Could you clarify that?

I still thing it would be totally ok, to raise if you give a field that does not exist in the schema to `validate_change/3`.

**Comment by josevalim** [comment]
> I still thing it would be totally ok, to raise if you give a field that does not exist in the schema to validate_change/3.

But that's not the issue here right? The field exists in the schema... but it was not cast as a change. And that's OK... specially if you have validations being shared by two different cast/2 calls. The best we can do is log, I would't raise.

**Comment by michalmuskala** [comment]
The initial issue I reported is validation used on a field that was never casted - it doesn't matter if it exists in the schema. So the problematic thing is:

```elixir
schema
|> cast(params, [:foo])
|> validate_change(:bar, &validate_bar/2)
```

The validation function will never run, thus it's safe to raise - the call is either useless and can be removed, or erroneous and should be corrected.

**Comment by josevalim** [comment]
> The validation function will never run, thus it's safe to raise - the call is either useless and can be removed, or erroneous and should be corrected.

I disagree. The current code allows two changeset functions to share a validation path even if they don't share all of validations. Maybe we want to do this change anyway, I am just pointing out there is a scenario where the current code is valid and that's why we should start with at least a warning.

**Comment by michalmuskala** [comment]
I see your point. So maybe we should limit ourselves to situations when the field is not in changes and not in the schema?
