### ISSUE TITLE
Support DBConnection

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1215]
Hi @elixir-lang/ecto-adapters!

Ecto 2.0 should arrive in a month or two. One of the big features in Ecto 2.0 for SQL databases is integration with [DBConnection](https://github.com/fishcakez/db_connection) that provides pooling, transactions, faster encoding/decode, query prepare and much more. From Ecto 2.0, the drivers for all SQL adapters must migrate to DBConnection.

Postgrex has already migrated and this is the initial pull request: https://github.com/ericmj/postgrex/pull/128

The good news is that you don't need to wait until Ecto 2.0 to leverage DBConnection. In fact, I would recommend drivers and adapters to migrate to DBConnection with Ecto 1.1. Only after the driver moves to DBConnection and all adapter test pass with Ecto 1.1.3 (you will need the latest), you should consider moving to Ecto 2.0.

* [x] PostgreSQL
* [x] MySQL
* [ ] MSSQL
* [ ] SQLite3
* [ ] MongoDB

PS1:  If you cannot implement DBConnection, you can still implement the Ecto adapter from scratch. You just won't be able to leverage the features in Ecto.Adapters.SQL, like the concurrent test sandbox coming in 2.0.

PS2: MongoDB is not a SQL adapter but I am including them in the discussion. They need to figure out if they want to move to DBConnection or not.

PS3: I will open up an issue that includes migration to Ecto 2.0 later on.

**Comment by fishcakez** [comment]
@mobileoverlord @jazzyb DBConnection should be stable now if you wish to start upgrading to Ecto 2.0.

**Comment by mobileoverlord** [comment]
I am actually working on this starting monday. I'll ping you if I have any questions. I'm currently churning through the PR for postgrex.

**Comment by christhekeele** [comment]
Does the DBConnection abstraction (and the stability of a 2.0 release) mean that a mnesia adapter might be in scope for in the 2.x lifecycle?

**Comment by ericmj** [comment]
@christhekeele Ecto will continue to only ship with mysql and postgres adapters. It's up to the community to create additional adapters.

**Comment by christhekeele** [comment]
@ericmj Cool, thanks! Just saw #239 and wondered.

**Comment by josevalim** [comment]
I am closing this as it is up to adapters to migrate to Ecto 2.0. If I can be of any help to adapters, please ping me. :)
