### ISSUE TITLE
Inline embeds

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1375]
Many changes introduced in Ecto 2.0 move it away from being just a database library and bring it closer to being a general data mapping solution.

We'd like to propose an enhancement to schemas and changesets that targets easy processing of external data, and makes Ecto more robust when it comes to data mapping. The aim of this proposal is to make Ecto schemas easier to use as a first line of your application, processing external data and getting it into structured format, that can be easily processed by other layers.

For a long time Ecto had a perfect solution for mapping such data - embeds. With the recent [removal of the `__meta__` field from embeds](https://github.com/elixir-lang/ecto/commit/e4eb4695a46e88c697511e3e981c223c3d2b1e6b) and removal of callbacks, embeds are even closer to being regular elixir structs with additional type information than to full-blown Ecto schemas. They make it easy to declare typed structs with custom validation logic that can be completely separate from the database. Using embedded schemas as pure data structure gives you the power of changesets and Ecto types for modeling your data. Those could be a part of your applications architecture in a role similar to form objects or commands known from various OO solutions. The biggest issue is that they become rather verbose when dealing with nested data, what is a common situation in many APIs - each level of nesting requires defining separate modules with schema declaration.

## Usage

We'd like to propose ability to define embedded schemas inline in the parent schema. 

```elixir
defmodule NewOrderCommand do
  use Ecto.Schema
  
  embedded_schema do
    field :user_id, Ecto.UUID
    
    embeds_one :address, Address do
      field :street, :string
      field :country, :string
      field :location, Geo.Point
    end
    
    embeds_many :items, Item do
      field :item_id, Ecto.UUID
      field :quantity, :integer
    end
  end
end
```
This would define two additional embedded schemas `NewOrderCommand.Address` and `NewOrderCommand.Item`. It's not yet clear if we'll go with the `embeds_one/many` accepting a block route or introduce separate `inline_embeds_one/many` macros.

The new schemas could be later used similarly to separately defined embeds with the exception that it woudn't be possible to define changeset functions that `cast_embed` expects. This shouldn't be an issue though, because we can use `with` option for passing arbitrary changeset function.

```elixir
def changeset(struct, params) do
  struct
  |> cast(params, [:user_id])
  |> cast_embed(:address, with: &address_changeset/2)
  |> cast_embed(:items, with: &item_changeset/2)
  |> validate_required([:user_id, :address, :items])
end

defp address_changeset(struct, params) do
  struct
  |> cast(params, [:street, :city])
  |> validate_required([:street, :city])
  |> validate_existing_city
  |> find_location
end

defp item_changeset(struct, params) do
  struct
  |> cast(params, [:item_id, :quantity])
  |> validate_required([:item_id, :quantity])
  |> validate_number(:quantity, min: 0)
end
```

After validations, building the changeset `Ecto.Changeset.apply_changes/1` allows us to extract the final struct for further processing - the final result is plain data we can safely pass into code that is completely unaware of ecto. With a simple function (such as `changeset_to_tuple/1` shown below) we can format the changeset for easy processing in pipelines or `with` macros.

```elixir
def changeset_to_tuple(%Ecto.Changeset{valid?: true) = changeset) do
  {:ok, Ecto.Changeset.apply_changes(changeset)}
end

def changeset_to_tuple(%Ecto.Changeset{errors: errors} do
  {:error, Ecto.Changeset.traverse_errors(changeset, &format_error/1)}
end
```

**Comment by josevalim** [comment]
:+1:

**Comment by imranismail** [comment]
This is so freaking awesome, this makes it super useful when the requirements are fluid 👍

**Comment by andys** [comment]
This would also be really useful for creating an Elasticsearch adapter
