### ISSUE TITLE
MySQL test failures

### ISSUE THREAD

**Issue by nathanl** [elixir-ecto/ecto#1387]
### Environment

* Elixir: 1.2.4, Erlang/OTP 18
* Database: "mysql  Ver 14.14 Distrib 5.7.12, for osx10.11 (x86_64) using  EditLine wrapper". This is a fresh install on a new machine; all I've done related with mysql is `brew install mysql` and `mysql.server start`.
* Ecto version: master, commit 89881a9229e66b1ba96c8097bf258bc1bbcff3c4, April 21, 2016
* Database adapter and version: mariaex 0.7.1
* Operating system: OS X El Capitan (10.11.2)

### Current behavior

`MIX_ENV=mysql mix test` has two test failures:

```
  1) test many_to_many assoc selector (Ecto.Integration.JoinsTest)
     integration_test/cases/joins.exs:198
     Assertion with == failed
     code: p2.users() == [u2]
     lhs:  []
     rhs:  [%Ecto.Integration.User{__meta__: #Ecto.Schema.Metadata<:loaded>,
             comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
             custom: #Ecto.Association.NotLoaded<association :custom is not loaded>, custom_id: nil, id: 10,
             inserted_at: #Ecto.DateTime<2016-04-21 12:39:30>, name: "2",
             permalink: #Ecto.Association.NotLoaded<association :permalink is not loaded>,
             posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
             schema_posts: #Ecto.Association.NotLoaded<association :schema_posts is not loaded>,
             updated_at: #Ecto.DateTime<2016-04-21 12:39:30>}]
     stacktrace:
       integration_test/cases/joins.exs:221

  2) test has_many through assoc selector (Ecto.Integration.JoinsTest)
     integration_test/cases/joins.exs:225
     Assertion with == failed
     code: p2.comments_authors() == [u2]
     lhs:  []
     rhs:  [%Ecto.Integration.User{__meta__: #Ecto.Schema.Metadata<:loaded>,
             comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
             custom: #Ecto.Association.NotLoaded<association :custom is not loaded>, custom_id: nil, id: 12,
             inserted_at: #Ecto.DateTime<2016-04-21 12:39:30>, name: "2",
             permalink: #Ecto.Association.NotLoaded<association :permalink is not loaded>,
             posts: #Ecto.Association.NotLoaded<association :posts is not loaded>,
             schema_posts: #Ecto.Association.NotLoaded<association :schema_posts is not loaded>,
             updated_at: #Ecto.DateTime<2016-04-21 12:39:30>}]
     stacktrace:
       integration_test/cases/joins.exs:249
```

### Expected behavior

`mix test.all` should have 0 failures.

**Comment by nathanl** [comment]
There appears to be some issue with state bleeding from another test - `MIX_ENV=mysql mix test integration_test/cases/joins.exs` has the two failures, but if I comment out all tests in that file except `  test "has_many through assoc selector"`, it passes.

**Comment by nathanl** [comment]
There seems to be a race condition - if I comment out all but the two tests that failed above, and run repeatedly, `test many_to_many assoc selector` fails every time, but `test has_many through assoc selector` sometimes passes.

**Comment by nathanl** [comment]
Question: http://stackoverflow.com/questions/36770956/how-can-i-see-the-raw-sql-generated-for-an-ecto-query

**Comment by josevalim** [comment]
If you go to ingration_test/mysql/test_helper.exs and comment the first
line, the queries will also be logged. :)

Then use: MIX_ENV=mysql mix test integration_test/cases/preload.exs:SOMELINE

To run some particular test.

**Comment by nathanl** [comment]
Update: Right now I'm specifically debugging `test "many_to_many assoc selector"`. The failure happens with the version of the query that uses `on:`; after `TestRepo.all` runs, the first post has the expected user asocition, but the second post is given an empty user association.

I logged the queries it runs (and used `Logger.flush` to see the log output in the expected places) and tried running simplified versions of those queries myself (just selecting fewer columns):

```
    #mysql version - run with MIX_ENV=mysql
    Ecto.Adapters.SQL.query(TestRepo, "SELECT p0.`id`, p0.`title`, u1.`id`, u1.`name`, u1.`custom_id`, u1.`inserted_at`, u1.`updated_at` FROM `posts` AS p0 LEFT OUTER JOIN `posts_users` AS p2 ON p2.`post_id` = p0.`id` LEFT OUTER JOIN `users` AS u1 ON (p2.`user_id` = u1.`id`) AND (p0.`title` = u1.`name`) ORDER BY p0.`id`", []) |> IO.inspect

    # postgres version - run with MIX_ENV=pg 
    Ecto.Adapters.SQL.query(TestRepo, "SELECT p0.\"id\", p0.\"title\", u1.\"id\", u1.\"name\", u1.\"custom_id\", u1.\"inserted_at\", u1.\"updated_at\" FROM \"posts\" AS p0 LEFT OUTER JOIN \"posts_users\" AS p2 ON p2.\"post_id\" = p0.\"id\" LEFT OUTER JOIN \"users\" AS u1 ON (p2.\"user_id\" = u1.\"id\") AND (p0.\"title\" = u1.\"name\") ORDER BY p0.\"id\"", []) |> IO.inspect
```

Both Postgres (which passes) and Mysql (which fails) get correct-looking data back:

```
{:ok,
 %Postgrex.Result{columns: ["id", "title", "id", "name", "custom_id",
   "inserted_at", "updated_at"], command: :select, connection_id: 50134,
  num_rows: 4,
  rows: [
     [1, "1", 1, "1", nil, {{2016, 4, 21}, {17, 13, 17, 0}}, {{2016, 4, 21}, {17, 13, 17, 0}}],
     [1, "1", nil, nil, nil, nil, nil],
     [2, "2", 2, "2", nil, {{2016, 4, 21}, {17, 13, 17, 0}}, {{2016, 4, 21}, {17, 13, 17, 0}}],
     [3, "3", nil, nil, nil, nil, nil]
   ]}}

{:ok,
 %Mariaex.Result{columns: ["id", "title", "id", "name", "custom_id",
   "inserted_at", "updated_at"], command: :select, connection_id: nil,
  last_insert_id: nil, num_rows: 4,
  rows: [
    [1, "1", 1, "1", nil, {{2016, 4, 21}, {17, 13, 48, 0}}, {{2016, 4, 21}, {17, 13, 48, 0}}], 
    [1, "1", nil, nil, nil, nil, nil],
    [2, "2", 2, "2", nil, {{2016, 4, 21}, {17, 13, 48, 0}}, {{2016, 4, 21}, {17, 13, 48, 0}}],
    [3, "3", nil, nil, nil, nil, nil]
  ]}}
```

So it appears that the problem is not what the database returns, but something in how the associations are built from there.

Still digging...

**Comment by josevalim** [comment]
@nathanl great progress so far! Thanks for following up.

**Comment by nathanl** [comment]
😅

**Comment by nathanl** [comment]
I still don't get it. :( What I've found is that [this line](https://github.com/elixir-lang/ecto/blob/89881a9229e66b1ba96c8097bf258bc1bbcff3c4/lib/ecto/adapters/sql.ex#L360) has different return values for `MIX_ENV=mysql mix test integration_test/cases/joins.exs:198` than with `MIX_ENV=pg`. Specifically, with PostgreSQL, it returns the posts and 2 users, and with MySQL, the posts and just one user. I'm not sure why, since the queries look identical except for MySQL/PostgreSQL syntax and when I run them myself (as shown above) I get the same data back in both cases.

The params to that function look identical to me in both cases, and I'm not sure how any differences between the two db adapters would come into play further down, but maybe I'm missing something.

**Comment by josevalim** [comment]
All signs point to a be a weird bug in MySQL, specially given it does not happen on other MySQL versions like 5.5.

**Comment by nathanl** [comment]
I'm out of steam on this one. Hopefully this will be a useful thread if somebody else wants to take a crack at it.

**Comment by josevalim** [comment]
No worries @nathanl. I was able to reproduce it locally by changing versions and I also have no idea why it fails. I looked at MySQL server logs and there are no hints in there as well. :(

**Comment by nathanl** [comment]
@josevalim That's too bad, but thanks for telling me - now I don't feel so bad. :smile:

**Comment by starbelly** [comment]
I have replicated this on my macbook via `brew install mysql`. The second failing test can be remedied with a where clause, but does not really solve the problem. That is adding `where ca.name != NULL` My blind and uneducated guess is that it has to do with the rows in the result where user id or name is null. 

But for now, I must eat. Will try to peck away at this some more later this evening.

**Comment by starbelly** [comment]
No solution yet, but interesting find. If you run only one of the test units in question, it passes:

    MIX_ENV=mysql mix test integration_test/cases/joins.exs:198

**Comment by starbelly** [comment]
Further down the rabbit hole we go : ) 
 
 Once again, have no solution yet, but modified the test as so:

    query = from(p in Post, left_join: u in assoc(p, :users), on: p.title == u.name, order_by: p.id)
    res   = TestRepo.all(query)
    posts = Enum.map res, fn x ->
     x |> TestRepo.preload(:users)
    end
    p1 = Enum.at(posts,0)
    p2 = Enum.at(posts,1)
    p3 = Enum.at(posts,2)
    p4 = Enum.at(posts,3)
    assert p1.users == [u1, u2] # This is post 1
    assert p2.users == [u1, u2] # This is post  1
    assert p3.users == [u2] # This is post 2
    assert p4.users == [] # This is post 3

That of course, passes. 

@josevalim Plan on digging into the preload code later on, any advice or direction is very much welcome.

**Comment by nathanl** [comment]
Given that the SQL produced by Ecto looks correct, and that this only fails on specific versions of MySQL, and that it fails intermittently, it seems most likely that (as José said) it's a bug in MySQL. If we could reproduce the error more simply - eg a script that just executes SQL strings - that would get us closer to pinpointing the situation that causes it.

I don't really understand whether or how these tests are run concurrently. We'd probably want to reproduce that, though.

**Comment by starbelly** [comment]
@nathanl Yeah, probably expending too much energy on this. Though, I felt it was a great opportunity to learn the guts of ecto, and thus far that has proven true. I'm pretty stubborn as well :) It's obviously not something in Ecto if it works with 5.5 and 5.6, which I tested and work fine. Moving along for now : )

**Comment by josevalim** [comment]
Thank you @starbelly! I think at this point we have all arrived to the same conclusion this is not an Ecto issue. Should we close this?

**Comment by starbelly** [comment]
Absolutely.

**Comment by starbelly** [comment]
@josevalim Absolutely
