### ISSUE TITLE
Preload not working on join fragment

### ISSUE THREAD

**Issue by ashleyw** [elixir-ecto/ecto#1438]
Is it not possible to preload on a join fragment?

```
query = Post
  |> join(:inner, [p], c in fragment("SELECT * FROM \"comments\" AS c"), p.id == c.post_id)
  |> preload([p, c], [comments: c])
```

```
** (CaseClauseError) no case clause matching: {:fragment, [], [raw: "SELECT * FROM \"comments\" AS c"]}
stacktrace:
  (ecto) lib/ecto/repo/queryable.ex:119: Ecto.Repo.Queryable.execute/5
  (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
  integration_test/cases/assoc.exs:55
```

Using `assoc` works for this use-case, but this is related to implementing LATERAL joins (#1425)

**Comment by josevalim** [comment]
If you check the postgres_test file, you will see we have tests called "join with fragments" that test exactly this. Do you have a failing test case you could add to the suite?

**Comment by ashleyw** [comment]
Sure: https://github.com/ashleyw/ecto/commit/4f3dfab86f4f1c69a22f943436512e7702a6c88f

**Comment by ashleyw** [comment]
What would it take to get preloads with fragments working? It would be very helpful when combined with LATERAL joins. Currently I'm using raw SQL and building the Ecto structs manually.

Thanks!

**Comment by josevalim** [comment]
@ashleyw right now it isn't straight-forward because preload requires structs and we can't return struct from fragments because we don't have enough metadata about them.
