### ISSUE TITLE
Make it convenient to prepare both a dev and test database

### ISSUE THREAD

**Issue by drewolson** [elixir-ecto/ecto#144]
When I'm developing Ecto applications I generally have two databases. Something like `app_dev` and `app_test`. It would be nice if there was a task that would prepare both of these databases for me. Right now, I'm doing something like:

``` elixir
defmodule App.Repo do
  use Ecto.Repo, adapter: Ecto.Adapters.Postgres

  def url do
    "ecto://user@localhost/app_#{Mix.env}"
  end
end
```

I run the following to prepare my databases.

``` bash
mix ecto.migrate
MIX_ENV=test mix ecto.migrate
```

I don't have a specific solution but I think it is worth starting a discussion.

**Comment by HappMacDonald** [comment]
Hmm, I am getting an error when I try some manual tests:

```
jesse@mc01:~/dev/dishwasher2-elixir$ MIX_ENV=dev mix run dw_project_null.exs @ q init < /dev/null

17:01:11.719 [debug] QUERY OK source="wisp_dw_projects" db=3.4ms decode=2.5ms
SELECT w0.`project_id`, w0.`project_name` FROM `wisp_dw_projects` AS w0 WHERE (w0.`project_name` = ?) ["q"]

17:01:11.726 [debug] QUERY OK source="wisp_dw_lists" db=3.4ms
SELECT w0.`list_id`, w0.`list_name` FROM `wisp_dw_lists` AS w0 WHERE (w0.`list_name` = ?) ["init"]

17:01:11.727 [debug] QUERY OK source="wisp_dw_lists" db=0.4ms
SELECT w0.`list_id`, w0.`list_name` FROM `wisp_dw_lists` AS w0 WHERE (w0.`list_name` = ?) ["exception"]
** (MatchError) no match of right hand side value: nil
    (dishwasher2) lib/dishwasher2.ex:138: anonymous fn/4 in Dishwasher2.output/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (dishwasher2) lib/dishwasher2.ex:137: Dishwasher2.output/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

When I give it some data to chew on it gets no error. But then when I try to read back the data:

```
jesse@mc01:~/dev/dishwasher2-elixir$ MIX_ENV=dev mix run dw_project_null.exs init q  < /dev/null
** (RuntimeError) cannot reduce stream outside of transaction
    (ecto) lib/ecto/adapters/sql.ex:520: Ecto.Adapters.SQL.reduce/7
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:857: Stream.do_transform/5
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:2979: Enum.reduce/3
    (dishwasher) lib/dishwasher.ex:19: Dishwasher.run/2
    (dishwasher2) lib/dishwasher2.ex:27: Dishwasher2.run/2
```

**Comment by norpan** [comment]
If it's any help, I have the following in my `mix.exs`, which sets up a fresh test database each time:
```
defp aliases do
    [
      test: ["ecto.drop", "ecto.create", "ecto.migrate", "test"]
    ]
end
```

**Comment by srogers** [comment]
In a long-running project, there may be hundreds of migrations, so it doesn't seem like relying on the migrations to recreate the current DB state is ideal in the long run. Rails gets around that with a schema file that holds the current state. This has its own associated issues, but it does solve some problems. I don't see an easy way to replicate that without re-thinking many aspects of the way things work.

**Comment by josevalim** [comment]
Ecto has included ecto.dump and ecto.load for a while. So you can update your  `mix ecto.setup` alias in your mix.exs or in your test_helper.exs to use those instead.

**Comment by srogers** [comment]
That works - if there's a standard place to keep it, and to use it in tests. It's the difference between there being a way to do it, vs. there being a well-known "normal" way to do it.
