### ISSUE TITLE
Use sbroker as the default pool

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1453]
@fishcakez I believe sbroker seems to be a better default, provide better concurrency and performance, regardless if we are using shrinking or not.

**Comment by fishcakez** [comment]
I am a bit uncomfortable with the idea of switching from a ~400 line of code default to a 6.5k lines of code (estimate for sbroker 1.0) default. That is a lot of code for pooling, not everyone needs the features provided*. I would choose sbroker every time myself but if someone made that switch on me I would not be thrilled. Whereas defaulting to the simpler poolboy means people can opt-in to more advanced features.

* Its approximately 1.5k lines to do dispatch, 1.5k lines to do pool resizing and then maybe 7 features around 500 lines each to reduce upper percentile latency in certain situations. We can probably make all of these features available but I'm unsure how many will be used by 80% of people.

**Comment by fishcakez** [comment]
Performance of poolboy pool is now almost inline with sbroker.

**Comment by fishcakez** [comment]
We have defaults that seem ok in postgrex so lets go for this. There is A LOT of configuration available that is documented in DBConnection, we will need to point there otherwise it is too much duplication.

**Comment by josevalim** [comment]
We have decided to continue with poolboy because sbroker also brings sasl as a dependency, which brings extra logging behaviour. Moving to sbroker would also break the user code since they need to depend on both sbroker deps and application.
