### ISSUE TITLE
Support Elixir v1.3 calendar types 

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1466]
`:time` will be Time, `:date` will be `Date` and `:datetime` will be `NaiveDateTime`.

**Comment by lau** [comment]
How about it being possible to define a datetime field in the schema as a UTC DateTime? An example of this could be the `inserted_at` and `updated_at` timestamps. We know already that they are always in UTC. It would be nice if you could pass an `inserted_at` to `DateTime.to_unix/2`.

This kind of feature is available in [Calecto](https://github.com/lau/calecto) with `Calecto.DateTimeUTC`.

So if you have a `datetime` field you could either define it as a NaiveDateTime or DateTimeUTC field in your schema. If it is a DateTimeUTC field you cannot cast non-UTC `DateTime` structs into it e.g. one where the time_zone is "Europe/Paris". Only "Etc/UTC". And you always get UTC DateTimes back.

This should work fine with just a normal datetime field in the database. But here is a further development of the idea: Taking it to the next step for postgres it would be even nicer if a postgres "timestamp with timezone" were always DateTimeUTC. The idea is that if in the database a field is defined as being in UTC in the database we should treat it as such in Ecto and not just as a naive datetime.

**Comment by josevalim** [comment]
@lau I have plans for such but I haven't listed it due to implementation factors. Typically the native types are supported by the adapters themselves, so I am not sure if we should push the UTC concerns to the adapters or if we should handle those in Ecto (which means then we need a custom type).

**Comment by lau** [comment]
How about adding a new type to Ecto? Not sure if this is what you meant by custom type. Just like we have `:datetime`, `:time`, and `:date`. We could add `:datetime_utc` which would map to `TIMESTAMP` in MySQL, `timestamp with timezone` in Postgres.

For the other databases:
- Sqlite seems to use INTEGER for unix time, which can be used as UTC datetime too.
- Mongodb's "date" is actually a utc datetime which it seems is supposed to be used for everything including date, time, datetime.
- mssql doesn't seem to have a UTC-only datetime/timestamp.

**Comment by nimrev** [comment]
I just read up on the different timestamp implementations in the various databases and found this in the MySQL documentation:
_"MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval."_
So storing the DateTimeUTC value directly in MySQL would cause some weird issues when the system in not in the UTC timezone mode or when the DateTime's timezone is not the same as the systems timezone. 
I checked the code but I couldn't figure out how this is currently solved, if it even is?

**Comment by nimrev** [comment]
Seems this internal calculation doesn't take place when inserting with the value with FROM_UNIXTIME.

However the value received when querying is still converted back to the system timezone, doesn't remain a UTC value.

**Comment by lau** [comment]
@nimrev It might be a good idea for Ecto or its adapter to verify that the mysql time zone is set to UTC. And/or set it to UTC when the connection begins.

http://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

Running `SET time_zone = '+00:00';` should do it when starting the connection.

**Comment by fishcakez** [comment]
Elixir 1.3 Calendar types are in postgrex master. We can release `postgrex 0.12.0` at any time if someone wants to work on this.

**Comment by isaacsanders** [comment]
Lack of generic support of datetimes/timestamps with time zones is a critical issue with Ecto. Adding such support would go a long way to lessen the list of issues we have with this library on my team.

**Comment by lau** [comment]
@isaacsanders have you seen [Calecto](https://github.com/lau/calecto)? It supports all the native Elixir 1.3 calendar types including `DateTime`s with timezones. You could use that until such features become built into Ecto.

**Comment by isaacsanders** [comment]
That would work for me, except that `Ecto.Adapters.SQL.query` transforms my timestamps with time zones into Ecto/erlang DateTime tuples without a timezone.

**Comment by isaacsanders** [comment]
There also doesn't appear to be a way around the transformation/corruption of my data by ecto.

**Comment by lau** [comment]
@isaacsanders which database do you use? I don't know any databases that natively support real time zones e.g. "America/New_York". For instance Postgres supports "naive datetimes" or UTC datetimes, but does not have a built in type for a datetime with a specific timezone. What Calecto does is use a composite type, which includes a sub-field with a timezone and a sub-field that is a datetime without a timezone.

So when you say you don't want the timestamps to be translated to something without a timezone in queries, what would you want instead in the query? The databases don't really know timezones outside of "is this UTC or not?".

**Comment by isaacsanders** [comment]
Postgres: https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-TIMEZONES

**Comment by isaacsanders** [comment]
There is also a type that exists in a "blessed" extension called timestamptz.

**Comment by lau** [comment]
@isaacsanders Yes, postgres does not save the timezone information in the database with those types. It can do some timezone conversion in queries, but the timezone information is not saved.

**Comment by josevalim** [comment]
If you have someone on your team willing to work on this issue or on
your list of issues, please let us know. We will be happy to give a hand or
provide guidance when required.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
This is in master. We have introduced four types: date, time, naive_datetime and utc_datetime. They map respectively to Date, Time, NaiveDateTime and DateTime with time_zone set to "Etc/UTC".

For the DateTime one, although we don't currently store the timezone as "Etc/UTC" in the database, we **enforce** the timezone to be UTC when writing the data to the database. The user then is only responsible to guarantee the database will return UTC datetimes when loading the data. We can improve this in the future in two ways: 1. we can work with adapters to support enforcing the timezone to UTC more transparently (reducing the burden on users) 2. We can always send the timezone to the adapter which chooses to write it down or not depending on the database column type.

Feedback is welcome!

**Comment by danielberkompas** [comment]
I'm having an issue with `datetime_add/3`. Here are the relevant portions of my schema:

```elixir
defmodule MyApp.Contest do
  use Ecto.Schema

  schema "contests" do
    field :end_at, Ecto.DateTime
  end
end
```

My query:

```elixir
from c in MyApp.Contest,
  where: c.end_at > datetime_add(^Ecto.DateTime.utc, -30, "second")
```

The error I get:

```
** (Ecto.Query.CastError) iex:12: value `#Ecto.DateTime<2016-11-18 23:33:10.482082>` in `where` cannot be cast to type :naive_datetime in query:

from c in CrossConnect.Contest,
  where: c.end_at > datetime_add(^#Ecto.DateTime<2016-11-18 23:33:10.482082>, -30, "second"),
  select: c
```

Does `datetime_add/3` need to be updated? I don't understand why this cast error is happening.

**Comment by josevalim** [comment]
It is a bug on Ecto 2.1. We are still supposed to be backwards compatible, so the example above should not error.

**Comment by michalmuskala** [comment]
@josevalim what would be the appropriate fix here? Allow `Ecto.DateTime` when casting the `naive_datetime` type? Should we allow the ecto types when casting the new types in general?

**Comment by josevalim** [comment]
@michalmuskala I am thinking we should support it specially in the naive_datetime function.
