### ISSUE TITLE
Support where exists(subquery) as well as where left in subquery

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1479]

**Comment by josevalim** [comment]
Unfortunately implementing this is way trickier than expected if we want to allow the bindings in the parent query to be accessed from the subquery. For now, the best solution for this will be to use fragments still.

**Comment by AndrewDryga** [comment]
I guess we can support it by allowing interpolation of Ecto.Query in `fragment/1`? Right now it throws exception, but as I understand it's should not be possible when developer is building another query.

```
to prevent sql injection, only a keyword list may be interpolated as the first argument to `fragment/1` with the `^` operator, got `#Ecto.Query<from s in Ecto.Paging.Schema, where: s.id == ^7700, select: s.id>`
```

**Comment by AndrewDryga** [comment]
Example:
```
    sub_query = %Ecto.Query{from: query.from}
    |> select([c], :id)
    |> where([c], :id == ^starting_after)

    query
    |> where([c], :inserted_at > fragment(^sub_query))
```

**Comment by aaronjensen** [comment]
We just hit this as well. It'd be great if we could at least build queries to use in fragments rather than having to use strings.

**Comment by bcardarella** [comment]
@AndrewDryga @josevalim was there ever movement on query interpolation within `fragment` ?

**Comment by kenips** [comment]
@josevalim is it possible to revisit this? Back then it was too much to implement but as Ecto matures this should be reconsidered? Forcing join only subquery or writing fragment is not the best solution in some cases (performance / maintainability) and it would be great if Ecto can support this.

**Comment by fuelen** [comment]
@josevalim it seems like with introducing parent_as https://github.com/elixir-ecto/ecto/commit/7633ac0acb0b65f55d57c51ddea6c741b98e0439 this issue can be reopened, right?

**Comment by josevalim** [comment]
Yup, good call! and we can even look at the “in query” support as an example of how to implement this. PRs are welcome!

**Comment by fuelen** [comment]
Could you update labels and milestone?

**Comment by GabrielAlacchi** [comment]
I believe this can be closed. @josevalim is there anything missing that's covered in this issue?
