### ISSUE TITLE
Support fragments in update

### ISSUE THREAD

**Issue by mspanc** [elixir-ecto/ecto#1481]
### Environment

* Elixir version (elixir -v): 1.2.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.4.5
* Ecto version (mix deps): 1.1.8
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: ubuntu 14.04

### Current behavior

There's no way to do the use more sophisticated DB features because there's no way to do the following

```elixir
from(f in File, where: f.id == ^record.id)
  |> MyApp.Repo.update_all(set: [search_vector: fragment("to_tsvector('simple', coalesce(unaccent(?), ''))", keywords)])
```

### Expected behavior

There's a way to pass fragment to the update.

**Comment by josevalim** [comment]
Which error do you get?

**Comment by mspanc** [comment]
AFAIR undefined function `fragment`

**Comment by omidbachari** [comment]
I can handle this issue, if y'all give the go ahead. :-)

**Comment by josevalim** [comment]
Please go ahead :D

**Comment by omidbachari** [comment]
Ready for review, friends!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
