### ISSUE TITLE
Support varargs in fragment macro

### ISSUE THREAD

**Issue by mspanc** [elixir-ecto/ecto#1485]
### Environment

* Elixir version (elixir -v): 1.2.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.4.5
* Ecto version (mix deps): 1.1.8
* Database adapter and version (mix deps): postgrex 0.11.1
* Operating system: ubuntu 14.04

### Current behavior

I need to build a query where I dynamically build a fragment.

Something like this:

```elixir
from file in query,
  where: fragment("? @@ to_tsquery('simple', unaccent(?))", file.search_vector, ^term)
```

but if there are many keywords I need to replicate to_tsquery part for each keyword and then merge these tsqueries using postgres-specific operator, so amount of arguments to the macro will defined in the runtime as each replicated part will have its placeholder for a value.

If I pass list as argument to the macro, it will replace first placeholder in the fragment with SQL ARRAY

### Expected behavior

If I pass list as argument to the macro, its items will be mapped to the subsequent placeholders.

**Comment by josevalim** [comment]
Sorry, this request is not clear. What are the keywords in your case? Which code are you writing today (please give more details), which one do you expect to write and what is the SQL you expect to be generated? Thank you.

**Comment by mspanc** [comment]
My fault, I have pasted invalid code snippet.

The right one is 

```elixir
from f in MyApp.File,
  update: [set: [search_vector: fragment("to_tsvector('simple', unaccent(?))", ^keyword)]]
|> MyApp.Repo.update_all([])
```

I want to utilize full-text search from posgtresql. I need to convert list of keywords into `tsvector`.

So if I have one keyword, the code would have been looking like:

```elixir
from f in MyApp.File,
  update: [set: [search_vector: fragment("to_tsvector('simple', unaccent(?))", ^keyword)]]
|> MyApp.Repo.update_all([])
```

But if I have two keywords, the code would have been looking like:

```elixir
from f in MyApp.File,
  update: [set: [search_vector: fragment("to_tsvector('simple', unaccent(?)) || to_tsvector('simple', unaccent(?))", ^keyword1, ^keyword2)]]
|> MyApp.Repo.update_all([])
```

And so on. Because amount of keywords is unknown at the compilation time, I need a way to build a fragment with unknown amount of placeholders. 

So I imagine that it would have worked like this



```elixir
keywords = [keyword1, keyword2]
fragment_sql = Enum.map(keywords, fn(_) -> "to_tsvector('simple', unaccent(?))") |> Enum.join(" || ")

from f in MyApp.File,
  update: [set: [search_vector: fragment(^fragment_sql), ^keywords)]]
|> MyApp.Repo.update_all([])
```

**Comment by josevalim** [comment]
It doesn't seem varargs would be enough to solve this issue because you also need a way to tell us how to concatenate each fragment. It is more like you need "fragment_join" or another operator of sorts.

In any case, why don't you concatenate the keywords in Elixir land and send a single value to the database? Reading Postgres docs says the result is the same except the position of the tokens is shuffled by one in the presence of stop words on the left side, which does not seem to affect the result if you are simply matching against a tsquery: https://www.postgresql.org/docs/9.1/static/textsearch-features.html#TEXTSEARCH-MANIPULATE-TSVECTOR

**Comment by mspanc** [comment]
Hm I already concatenate fragments (see Enum.join in the line 2).

Indeed I will do as you suggest for now, but generally speaking, in my career I've had at least dozen cases when I had to dynamically build part of a query, so support for such thing would be awesome.

**Comment by josevalim** [comment]
Yes, this is similar to the problem with concatenating multiple ORs. We definitely need a solution around this.

**Comment by josevalim** [comment]
@mspanc i am closing this for now since we have solved your problem and I am hoping the addition of `or` to the query will allow us to handle the majority of the cases. If someone still needs this feature, please let us know.

**Comment by jablan** [comment]
We need this feature too http://stackoverflow.com/questions/41301959/ecto-query-and-custom-mysql-function-with-variable-arity Should I open new issue?

**Comment by josevalim** [comment]
The biggest problem is come up with an API for this. If there are proposals, we are glad to discuss them.

**Comment by jablan** [comment]
As all of the logical combinations with `fragment` (such as `fragment("?, ?, ?", [1, 2, 3])` and `fragment(["?, ?, ?", 1, 2, 3])` are already used for other things, I guess there would have to be another function, such as `fragment_list("?, ?, ?", [1, 2, 3])` or so. :/

**Comment by michalmuskala** [comment]
I'm afraid this will cause issues with the query cache. Since now for the same query struct we'd need to generate different SQL depending on the params we receive.

**Comment by josevalim** [comment]
@michalmuskala every time varargs are required, we cannot use the query cache. The same is true for `x in ^list` in MySQL. So we already have a mechanism for not using the query cache in Ecto for certain constructs.

**Comment by jablan** [comment]
@michalmuskala voiced good concern [here](https://jira.xing.hh/browse/REG-5342?focusedCommentId=633002&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-633002) about having to have fragment string in compile time, which does not work with dynamic arity. In this case, perhaps something like `custom_function(function_name, [1, 2, 3])`could work, second parameter passed as an argument list to `function_name`?

**Comment by cheerfulstoic** [comment]
For anybody else running into the `FIELD()` conundrum, it turns out that (at least in MySQL) there is a `FIND_IN_SET` function which takes a comma-separated list of values as a single second argument.  Works great and doesn't require variable arguments!
