### ISSUE TITLE
Handle new sbroker and db_connection failures

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1491]
@fishcakez,

After moving to db_connection 1.0.0-rc.0 we have some failures.

1. We are getting reports on mariaex checkout: https://travis-ci.org/elixir-lang/ecto/jobs/138017895#L598. Notice the previous db_connection version we depended on did not emit those: https://github.com/fishcakez/db_connection/commit/940a20ab1a34da13f778636aa2dc8baeba64c0f9

2. sbroker tests are complaining sregulator is not available. To run them: `ECTO_POOL=sojourn_broker mix test.adapters`. Here is the report:

```
** (EXIT from #PID<0.46.0>) shutdown: failed to start child: DBConnection.Ownership.Manager
    ** (EXIT) shutdown

10:48:17.674 [error] ** :sbroker_meter :sregulator_underload_meter failed to install.
** Was installing in {DBConnection.Sojourn.Regulator, #PID<0.201.0>}
** When arguments == {500, 5000, {:underload, #PID<0.199.0>}}
** Reason == {:badarg,
 [{:gen_event, :send, 2, [file: 'gen_event.erl', line: 232]},
  {:sregulator_underload_meter, :init, 2,
   [file: '/Users/jose/OSS/ecto/deps/sbroker/src/sregulator_underload_meter.erl',
    line: 68]},
  {:sbroker_handlers, :meters_init, 5,
   [file: '/Users/jose/OSS/ecto/deps/sbroker/src/sbroker_handlers.erl',
    line: 252]},
  {:sbroker_handlers, :meters_init, 4,
   [file: '/Users/jose/OSS/ecto/deps/sbroker/src/sbroker_handlers.erl',
    line: 242]},
  {:sregulator, :do_init, 6,
   [file: '/Users/jose/OSS/ecto/deps/sbroker/src/sregulator.erl', line: 643]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
```

**Comment by fishcakez** [comment]
1. is a bug in mariaex, its just become more apparent because all pools are now passive by default and `:idle_timeout` was reduced. Previously only `:sojourn` was passive and the idle timeout was longer that it wouldn't get caught in a test.

2. The call that's failing is to `:alarm_handler`, which means `sbroker`  haven't been started. `:sbroker` requires `:sasl` to be started, and `:alarm_handler` is in the sasl application.

**Comment by josevalim** [comment]
Waiting on a new mariaex release and we should be golden.
