### ISSUE TITLE
Fragment in join does not have access to outside aliases

### ISSUE THREAD

**Issue by madshargreave** [elixir-ecto/ecto#1493]
### Environment

Elixir: 1.2.1
PostgreSQL 9.4
Ecto: 2.0.0-rc.6
OS: OSX

### Current behavior
In cases where a fragmented join clauses refers a previously defined table alias, it raises the error

`* (Postgrex.Error) ERROR (undefined_table): invalid reference to FROM-clause entry for table "u3"`

Below is an example. We reference `u.id` that has previously been declared, but it throws the error.

```
Repo.one(
      from v in Visitor,
      join: c in assoc(v, :conversation),
      join: a in assoc(c, :app),
      join: u in assoc(a, :users),
      inner_join: g in fragment("SELECT * FROM groups g WHERE g.default = true OR g.user_id = ?", u.id), ...
```

Here's the generated SQL:

```
[debug] SELECT v0."id", v0."app_id", c1."id", v0."first_seen", v0."last_seen", v0."last_heard_from", v0."last_contacted", v0."last_page_viewed", v0."sessions", v0."seen_welcome_message", v0."email", v0."data", v0."name", v0."type", v0."avatar", array_remove(array_agg(f4."name"), NULL) FROM "visitors" AS v0 INNER JOIN "conversations" AS c1 ON c1."visitor_id" = v0."id" INNER JOIN "apps" AS a2 ON a2."id" = c1."app_id" INNER JOIN "app_users" AS a5 ON a5."app_id" = a2."id" INNER JOIN "users" AS u3 ON a5."user_id" = u3."id" INNER JOIN (SELECT * FROM groups g WHERE g.default = true OR g.user_id = u3."id") AS f4 ON TRUE WHERE (c1."id" = $1) AND (u3."id" = $2) GROUP BY v0."id", c1."id" ["cov4pj0u90001sjcty1s0i1xk", "clt8ojxvk0000dp2fyvwq126"] ERROR query=5.5ms queue=1.3ms

```
Any ideas?

**Comment by josevalim** [comment]
Reading about this error online seems to point this to be rather a query issue rather than an Ecto one: http://stackoverflow.com/questions/6347897/mixing-explicit-and-implicit-joins-fails-with-there-is-an-entry-for-table-b

What if you remove the `where` and use `join` on instead? Something like:

```elixir
join: c in assoc(v, :conversation), on: c.id == ^param1,
join: a in assoc(c, :app),
join: u in assoc(a, :users),on: u.id == ^param2,
```

**Comment by madshargreave** [comment]
I got it working, thanks for the help

**Comment by josevalim** [comment]
Are we good to close then? :D


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by madshargreave** [comment]
Sure :)
