### ISSUE TITLE
Selecting foreign key returns \n

### ISSUE THREAD

**Issue by mikelat** [elixir-ecto/ecto#1499]
### Environment

* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 14.14
* Ecto version (mix deps):  2.0.0-rc.6
* Database adapter and version (mix deps):  mariaex 0.7.7
* Operating system: Debain

### Current behavior

  schema "read_votes" do
    ...
    belongs_to :link, Link
  end
...
    ids = Repo.all(from rv in ReadVote, select: rv.link_id)
    IO.inspect ids

this outputs something along the lines of '\n\n\n\n\n\n\n\n\n'

### Expected behavior
A list of ids like [1, 2, 3]

**Comment by josevalim** [comment]
That's a list of number 10:

    iex> [10, 10, 10]
    '\n\n\n'

Type the following in your terminal to learn more:

    iex> i '\n\n\n'
