### ISSUE TITLE
Ecto.Repo no longer works with `timeout: :infinity`

### ISSUE THREAD

**Issue by alco** [elixir-ecto/ecto#1503]
Contrary to what the docs say for Ecto v2.0.1 [here](https://github.com/elixir-ecto/ecto/blob/v2.0.1/lib/ecto/repo.ex#L71-L72), the `:timeout` value no longer works with Postgrex, it ends up in Postgrex's code [here](https://github.com/elixir-ecto/postgrex/blob/v0.11.2/lib/postgrex/protocol.ex#L359-L360) and causes `{:error, :badarg}`.

Here's a test repo https://github.com/alco/ectest. All you have to do to reproduce the issue is run `iex -S mix` there.

**Comment by fishcakez** [comment]
This is a bug in postgrex, rather than a documentation bug in Ecto

**Comment by josevalim** [comment]
Fixed in Postgrex.
