### ISSUE TITLE
Allow any term for Ecto.Multi operations

### ISSUE THREAD

**Issue by asonge** [elixir-ecto/ecto#1505]
Ecto.Multi operation names have to be unique, but I am adding dynamic numbers of operations to an Ecto.Multi (I need to perform multiple operations to achieve an "insert", so I cannot use associations so easily).

Being able to name the operation `{:object_name, n}` would be more convenient/less problematic than munging `:"object_name_#{n}"`

**Comment by alexauritt** [comment]
me me me! lemme lemme do it!
https://myadventuresinadulthood.files.wordpress.com/2012/10/kid-with-hand-raised.jpg

**Comment by IamfromSpace** [comment]
I feel like automatic indexing solves 99% of use cases.  Does it make sense to add an automatic index if name is `nil`?

```
multi = Ecto.Multi.new
  |> Ecto.Multi.update(nil, user_changeset)
  |> Ecto.Multi.insert(nil, log_changeset)
```

In this case the names automatically become 0 and 1.  Then we're not dynamically creating atoms.

**Comment by josevalim** [comment]
I don't think it makes sense as you would be unable to access the results
later on.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
