### ISSUE TITLE
can't rollback migration after adding custom timestamp with just "def change do"

### ISSUE THREAD

**Issue by baron** [elixir-ecto/ecto#1511]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
postgres (PostgreSQL) 9.5.3
* Ecto version (mix deps):
* ecto 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ecto) cf97a4d3
  ok
* Database adapter and version (mix deps):
* postgrex 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (postgrex) 139755c1
  ok
* Operating system:
OSX

### Current behavior

```
  def change do
    alter table(:some_table) do
      add :processed_at, :datetime
    end
  end
```

This migration works going forward but when I try to rollback I get the following error.

Include code samples, errors and stacktraces if appropriate.
> ** (FunctionClauseError) no function clause matching in Enum."-reduce/3-lists^foldl/2-0-"/3
>     (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"(#Function<37.55738230/2 in Enum.map_join/3>, "DROP COLUMN \"processed_at\"", nil)
>     (elixir) lib/enum.ex:1213: Enum.map_join/3
>     (ecto) lib/ecto/adapters/postgres/connection.ex:561: Ecto.Adapters.Postgres.Connection.execute_ddl/1
>     (ecto) lib/ecto/adapters/postgres.ex:69: Ecto.Adapters.Postgres.execute_ddl/3
>     (ecto) lib/ecto/migration/runner.ex:101: anonymous fn/2 in Ecto.Migration.Runner.flush/0
>     (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/migration/runner.ex:99: Ecto.Migration.Runner.flush/0
>     (stdlib) timer.erl:181: :timer.tc/2

### Expected behavior
I expect it to migrate/rollback without issue.

When I modify the migration as follows, I am able to migrate/rollback without difficulty but it seems a bit strange and feels like a gotcha.

```
  def down do
    alter table(:some_table) do
      remove :processed_at
    end
  end

  def change do
    alter table(:some_table) do
      add :processed_at, :datetime
    end
  end
```

**Comment by baron** [comment]
Here's some additional information that might help. In the `schema "table_name" do` block, I need to declare custom timestamps like so:


```
    field :processed_at, Ecto.DateTime
    timestamps
```

When declared like this:

```
    # field :processed_at, Ecto.DateTime
    timestamps([:updated_at, :inserted_at, :processed_at])
```

Results in errors like, 

> iex(38)> some_model.processed_at          
> ** (KeyError) key :processed_at not found in: 

This works fine:

> iex(38)> some_model.updated_at  
> #Ecto.DateTime<2016-06-17 03:59:43>


in the table (I added "processed_at" later and I don't want a "not null" constraint:

>  inserted_at       | timestamp without time zone | not null
>  updated_at        | timestamp without time zone | not null
>  processed_at      | timestamp without time zone | 

Strangely enough, even when I do the following:

```
    # field :processed_at, Ecto.DateTime
    timestamps([:processed_at])
    # timestamps([:updated_at, :inserted_at, :processed_at])
```

I'm still able to access "updated_at" and "inserted_at" just fine. Only "processed_at" gives me an error.

Only when I go to the extreme of commenting out all timestamp declarations do I get an error. I'm not sure if that's intended behavior (that updated_at and inserted_at even when excluded from a list) but it might be related.

Btw, thank you for all the hard work, I'm just leaving notes up here not to rush you (it's a quirky bug but easy to work around) but to put to write it down before I forget.

**Comment by baron** [comment]
Apparently I misunderstood Ecto timestamps as noted in my examples above (I thought I could add whatever custom stamps by passing additional atoms). I think the original report of the "change" block failing for user-defined timestamps still stands so I'll leave it there. Please disregard my additional comment/info (perhaps a feature idea?).

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error? Unfortunately I was not able to reproduce the bug with the information provided, thank you!

**Comment by josevalim** [comment]
PS: I will reopen the issue once we can reproduce it. :)
