### ISSUE TITLE
Export Ecto.Adapters.SQL.query/query! directly in SQL repositories

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1515]

**Comment by michalmuskala** [comment]
Should this be a general additional callback for adapters?

I would also consider adding something like `Repo.query("...", load_into: MyStruct)`. Today executing the query is not that hard, what is hard is processing the result.

**Comment by tracehelms** [comment]
Hey @josevalim, I've got some extra time at work to help out with OS. Any pointers for getting started on this?

**Comment by imranismail** [comment]
So instead of calling

`Ecto.Adapters.SQL.query(repo, sql, params, opts \\ [])`

The `use Ecto.Repo, otp_app: :my_app` macro will add the `query` function directly to the repo module?

**Comment by imranismail** [comment]
I think I can work on this

**Comment by josevalim** [comment]
Yes, please!
