### ISSUE TITLE
There are still Tagged structs reaching adapters

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1517]
Even though we worked hard on eliminating those, there are still couple places where they reach the adapters directly instead of going through the dumpers/loaders mechanism.

One example of such query is: `from f in Foo, where: f.bar == <<0, ?a, ?b, ?c>>`

**Comment by josevalim** [comment]
I think the goal was to eliminate them from the runtime. At compile time,
there isn't much we can do as we need to indicate that it is a binary and
not a string. So or we use a tagged struct or a special AST instruction
which is the same at the end, no?

On Sunday, June 26, 2016, Michał Muskała <notifications@github.com> wrote:

> Even though we worked hard on eliminating those, there are still couple
> places where they reach the adapters directly instead of going through the
> dumpers/loaders mechanism.
>
> One example of such query is: from f in Foo, where: f.bar == <<0, ?a, ?b,
> ?c>>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-ecto/ecto/issues/1517>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbmAnuMjcEaI86eFrd5ibOryVL9ydks5qPjemgaJpZM4I-gsS>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michalmuskala** [comment]
I thought in case like this the planner (which has access to adapter) would run dumpers on fields like this, so once they reach the adapter they are already converted to what the adapter wants to have. 
But I'm not sure how this would work for params.

**Comment by josevalim** [comment]
That's how it works for params. For regular queries, adapters need to know
if it is explicitly a string or a binary and encode accordingly, hence the
tag.

On Sunday, June 26, 2016, Michał Muskała <notifications@github.com> wrote:

> I thought in case like this the planner (which has access to adapter)
> would run dumpers on fields like this, so once they reach the adapter they
> are already converted to what the adapter wants to have.
> But I'm not sure how this would work for params.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-ecto/ecto/issues/1517#issuecomment-228596122>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbshG724qfIPh_faR8yXIgAQqX2ngks5qPl7RgaJpZM4I-gsS>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
