### ISSUE TITLE
`Ecto.Repo.Assoc.merge/3` failure

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-ecto/ecto#1525]
### Precheck

Quick google revealed nothing.  Following post is slightly sanitized for job reasons but is accurate.

### Environment

* Elixir version:  Elixir 1.3.1, Erlang/OTP 18
* Database and version:  PostgreSQL 9.5
* Ecto version:  ecto 2.0.1
* Database adapter and version (mix deps):  postgrex 0.11.2
* Operating system:  Windows 10 and Debian both

### Current behavior

Built a SQL query of the form:
```elixir
    now = Ecto.Date.utc
    from s in Student,
      join: ssems in assoc(s, :student_sems),
      join: sreqs in assoc(s, :student_reqs),
      where: ssems.uid == s.uid
        and ssems.start <= ^now
        and ssems.end >= ^now,
      preload: [:student_sems, student_reqs: sreqs],
      select: s
```
Yes the :student_sems not being linked to ssems is on purpose, the issue happens without it as well.

A reduced test is:
```elixir
    from s in Student,
      join: sreqs in assoc(s, :student_reqs),
      preload: [student_reqs: sreqs]
```
The Student schema is:
```elixir
  @primary_key {:uid, :integer, autogenerate: false}
  schema "students" do
    field :preferred_name, :string
    field :personal_email, :string
    field :comment, :string

    has_many :student_reqs, Student.Requirement, foreign_key: :uid
    has_many :student_sems, Student.Semester, foreign_key: :uid

    # Why the heck do these not want to link, plus still need access to the intermediate table regardless and it seems these do not supply that...
    # many_to_many :requirements, Requirement,
    #   join_through: Student.Requirement,
    #   join_keys: [uid: :uid, requirement_id: :id]
    #
    # many_to_many :semesters, Semester,
    #   join_through: Student.Semester,
    #   join_keys: [uid: :uid, semester_id: :id]

    timestamps
  end
```
And the Student.Requirement schema is:
```elixir
  @primary_key false
  schema "students_requirements" do
    belongs_to :student, Student, foreign_key: :uid, references: :uid, primary_key: true
    belongs_to :requirement, Requirement, primary_key: true
    field :date, Ecto.Date, primary_key: true
    field :location, :string
    field :method, :string
    field :comment, :string

    timestamps
  end
```

Trying to run the above (reduced testcase) query (just via Repo.all) returns this:
```elixir
[debug] QUERY OK db=16.0ms
SELECT n0."uid", n0."preferred_name", n0."personal_email", n0."comment", n0."inserted_at", n0."updated_at", n2."uid", n2."requirement_id", n2."date", n2."location", n2."method", n2."comment", n2."inserted_at", n2."updated_at" FROM "students" AS n0 INNER JOIN "students_semesters" AS n1 ON n1."uid" = n0."uid" INNER JOIN "students_requirements" AS n2 ON n2."uid" = n0."uid" WHERE (((n1."uid" = n0."uid") AND (n1."start" <= $1)) AND (n1."end" >= $2)) [{2016, 6, 29}, {2016, 6, 29}]
** (MatchError) no match of right hand side value: [uid: 12345678901234567890, requirement_id: 1, date: #Ecto.Date<2016-06-26>]
      (ecto) lib/ecto/repo/assoc.ex:40: Ecto.Repo.Assoc.merge/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/repo/assoc.ex:48: Ecto.Repo.Assoc.merge/3
      (ecto) lib/ecto/repo/assoc.ex:28: anonymous fn/2 in Ecto.Repo.Assoc.query/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/repo/assoc.ex:27: Ecto.Repo.Assoc.query/3
      (ecto) lib/ecto/repo/queryable.ex:132: Ecto.Repo.Queryable.execute/5
      (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
```
So following the top of the stack points me to the lib/ecto/repo/assoc.ex file, and looking at these lines of:  https://github.com/elixir-ecto/ecto/blob/v2.0.2/lib/ecto/repo/assoc.ex#L38-42
We see this:
```elixir
    child_key =
      if struct do
        [{_, key}] = Ecto.primary_key!(struct) # Marked line
        key || raise Ecto.NoPrimaryKeyValueError, struct: struct
      end
```
Where it crashes at the marked line, which is immediately suspect because it seems to be matching out a single primary key when schemas could easily have more, but lets give it the benefit of the doubt and follow `Ecto.primary_key!/1` to: https://github.com/elixir-ecto/ecto/blob/v2.0.2/lib/ecto.ex#L403-422
What we see here is:
```elixir
  def primary_key(%{__struct__: schema} = struct) do
    Enum.map schema.__schema__(:primary_key), fn(field) ->
      {field, Map.fetch!(struct, field)}
    end
  end
# snip
  def primary_key!(%{__struct__: schema} = struct) do
    case primary_key(struct) do
      [] -> raise Ecto.NoPrimaryKeyFieldError, schema: schema
      pk -> pk
    end
  end
```
So, running this:
```elixir
iex(server@snip.local)109> Student.Requirements.__schema__(:primary_key)
[:uid, :requirement_id, :date]
iex(server@snip.local)110> Ecto.primary_key!(%Student.Requirements{})
[uid: nil, requirement_id: nil, date: nil]
```
So looking back to where assoc.ex is matching:
```elixir
[{_, key}] = Ecto.primary_key!(struct)
```
`[{_, key}]` is not matching to `[{:uid, nil}, {:requirement_id, nil}, {:date, nil}]`

So it seems that the private `Ecto.Repo.Assoc.merge/3` is failing by assuming there is only a single primary key, which is interesting considering it is even given all of the primary keys, values, and all, so it should have no trouble with it, except it was explicitly coded to ignore/die any more than one.

### Expected behavior

Expected the association to be preloaded and filled out in one transaction without needing to match and specify the SQL select for all of it manually, which will not fill out the associations and thus break the View

How do I get this working in my side of the code?

**Comment by OvermindDL1** [comment]
And for note, the same thing happens if joining with the Student.Semester table as it has two primary keys:
```elixir
  @primary_key false
  schema "students_semesters" do
    belongs_to :student, Student, foreign_key: :uid, references: :uid, primary_key: true
    belongs_to :semester, Semester, primary_key: true
    field :start, Ecto.Date
    field :end, Ecto.Date
    field :end_type, :string
    field :comment, :string

    timestamps()
  end
```

**Comment by josevalim** [comment]
Yes, we should improve the code so it handles composite primary keys.

**Comment by OvermindDL1** [comment]
Is there any other way to do a fairly simple many_to_many relation with needing the intermediary table as it contains some needed metadata of the association?  Perhaps a many_to_many taking an :intermediary option to specify the local 'key' name of intermediary tables in addition to the far associated table?
