### ISSUE TITLE
Don't generate Repo.transaction when not supported

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1530]
Today ecto always generates the `transaction/2`, `in_transaction?/0` and `rollback/1` functions on repo, even when the adapter does not support them and does not implement the `Ecto.Adapter.Transaction` behaviour.

This has a very unfortunate effect when combined with the new xref warnings from 1.3, because it tells the user that the appropriate adapter functions are not defined, which is correct and expected.

We have two options:
- don't generate those functions at all (might be problematic because of `Ecto.Repo` behaviour
- generate functions that raise an error when the adapter does not support those.

When fixed, I would ask to backport this to the 1.0 branch, since this affects mostly MongoDB users (and that's the last version supported).

**Comment by josevalim** [comment]
> generate functions that raise an error when the adapter does not support those.

I think the adapter should define them such as they only raise.

**Comment by michalmuskala** [comment]
Then this completely defeats the purpose of separating various adapter bits in different behaviours if adapter has to define all of them anyway.

**Comment by josevalim** [comment]
That's a good point. So maybe we should merge these definitions?

On Thursday, June 30, 2016, Michał Muskała <notifications@github.com> wrote:

> Then this completely defeats the purpose of separating various adapter
> bits in different behaviours if adapter has to define all of them anyway.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-ecto/ecto/issues/1530#issuecomment-229772638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbgUrZrAUfn3-iI6U6f8YFYfzAzMOks5qRCGMgaJpZM4JChS2>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Yeah, I think that would make sense.

**Comment by josevalim** [comment]
@michalmuskala it should be mostly fine since removing a behaviour doesn't really affect compilation (only a warning).

**Comment by josevalim** [comment]
Closed by accident, sorry.

**Comment by michalmuskala** [comment]
Wouldn't it break the adapters that implement only some of the behaviour? Or should we say that they were broken anyway, because ecto expected them to implement all the functions.

**Comment by ericmj** [comment]
Maybe add a `use Ecto.Adapter` that brings in all the behaviours and adds default implementations for the optional functions. `db_connection` does this for all its behaviour functions because different DB drivers needs different functions.

**Comment by eniolopes** [comment]
I can take this one if nobody is going to do it.

Just to clarify things. We are going to define `transaction/2`, `in_transaction?/0` and `rollback/1` and by default they are going to raise? They would be injected when `use Ecto.Adapter` is called?

**Comment by josevalim** [comment]
@eniolopes right now the plan is to merge the Ecto.Adapter.Transaction definitions into Ecto.Adapter. Do you agree @michalmuskala?

**Comment by michalmuskala** [comment]
Yes. If the additional behaviour is not optional I see no point in keeping it separate.

**Comment by josevalim** [comment]
@eniolopes so if you would like to, a PR is appreciated :D

**Comment by michalmuskala** [comment]
The commit that solved this was reverted. I'm working on a different solution.
