### ISSUE TITLE
Can't rollback text column to string column with "change" method

### ISSUE THREAD

**Issue by baron** [elixir-ecto/ecto#1535]
This was previously reported mistakenly in #1511. The gist of this error is that you can't do a "mix ecto.rollback" when you change a string column to a text column in your migrations.

I've reproduced the bug in a bare bones repository:
https://github.com/baron/ecto_text_string_rollback_issue

My apologies for wasting your time with the previous issue report. I hope this issue is reproducible through my repo.

### Environment

* Elixir version (elixir -v): 1.3
* Database and version ((PostgreSQL) 9.5.3:
* Ecto version (mix deps): ecto 2.0.2 (Hex package) (mix)
* Database adapter and version (mix deps): postgrex 0.11.2 (
* Operating system: osx

### Current behavior

```
11:55:15.908 [info]  == Running EctoDatestampIssue.Repo.Migrations.ModifyButAddDownMethod.change/0 backward
** (Ecto.MigrationError) cannot reverse migration command: alter table users. You will need to explicitly define up/1 and down/1 in your migration
    (ecto) lib/ecto/migration/runner.ex:174: Ecto.Migration.Runner.execute_in_direction/4
    (ecto) lib/ecto/migration/runner.ex:101: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1622: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:99: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:121: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:101: anonymous fn/4 in Ecto.Migrator.do_down/4

```

### Expected behavior
Shouldn't have to define down migration.

**Comment by michalmuskala** [comment]
This is fully expected. `modify` does not specify the source type, so there's no way of knowing what should be the type when rolling back.

It might be a good idea to improve documentation around this.

**Comment by baron** [comment]
Thanks for clarifying that!
