### ISSUE TITLE
Default foreign key types

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-ecto/ecto#1544]
### Precheck

Was talking about this on the forum at:  https://elixirforum.com/t/phoenix-gen-model-question-probably-ecto-question/1018

Was advised to report this here.  The above post is:
The help for `phoenix.gen.model` states:
```
The generator also supports `belongs_to` associations
via references:

    mix phoenix.gen.model Post posts title user_id:references:users

This will result in a migration with an `:integer` column
of `:user_id` and create an index. It will also generate
the appropriate `belongs_to` entry in the schema.
```
However this is not strictly true, it looks like it actually uses the `serial` datatype, which creates an auto-incrementing serializer in the database itself, and considering this is a foreign column then this seems to be entirely wasteful.  Why does it not default to `integer`, or better yet default to the type of the primary key of the associated table if detectable otherwise `integer` instead of the useless `serial`?  Is there a case for having a foreign key be `serial` over `integer` that I have never yet ran across in years?

### Environment

* Elixir version (elixir -v):  Elixir 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): ecto 2.0.1
* Database adapter and version (mix deps): postgrex 0.11.2
* Operating system:  Debian/Win10

### Current behavior

Foreign keys by default use the :serial datatype, which has additional and unneeded overhead compared to the :integer datatype and should not be used for foreign links as it creates a sequence in the database when a sequence should not exist for this purpose.

### Expected behavior

Should use the :integer datatype by default.

**Comment by OvermindDL1** [comment]
It also looks like the PostgreSQL adapter overrides `:serial` to `:integer` on references explicitly, but other databases do not necessarily do the same.  As `:serial` would generically never be useful on a reference it is still odd that that is the default instead of `:integer`, a far more reasonable default, so reasonable in fact that the PostgreSQL adapter overrides `:serial` (which would really suck if that was really wanted for some reason (??!?)...

https://github.com/elixir-ecto/ecto/blob/968eafecb48c809ba6b7dcb170c41272c8bc0e2f/lib/ecto/adapters/postgres/connection.ex#L766

**Comment by josevalim** [comment]
Yes, please send a PR changing the default. :)

**Comment by michalmuskala** [comment]
I'm not really sure where did you got those `serial` columns from, but ecto does not generate them.

I just tried a following migration:

```elixir
    create table(:test) do
      add :foo, :integer
    end

    create table(:bar) do
      add :test_id, references(:test)
    end
```

and got following in `psql`:

```
                         Table "public.test"
 Column |  Type   |                     Modifiers
--------+---------+---------------------------------------------------
 id     | integer | not null default nextval('test_id_seq'::regclass)
 foo    | integer |
Indexes:
    "test_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "bar" CONSTRAINT "bar_test_id_fkey" FOREIGN KEY (test_id) REFERENCES test(id)

                          Table "public.bar"
 Column  |  Type   |                    Modifiers
---------+---------+--------------------------------------------------
 id      | integer | not null default nextval('bar_id_seq'::regclass)
 test_id | integer |
Indexes:
    "bar_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "bar_test_id_fkey" FOREIGN KEY (test_id) REFERENCES test(id)
```

**Comment by josevalim** [comment]
It seems both adapters seem to convert the serial type into something else:

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/mysql/connection.ex#L679
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L766

So it seems it is behaving as expected in the sense we are using the serial flag as a way for the adapter to know exactly to what it should map to. :)

I believe we can close this?

**Comment by michalmuskala** [comment]
I think we should change the `serial` type to `id`, though. It seems like the `serial` type is a legacy thing from before we had `id`.

**Comment by josevalim** [comment]
@michalmuskala sounds good to me!

**Comment by michalmuskala** [comment]
I followed up on this, and it seems we use the `serial` type also as the default type for the autogenerated `id` field in the `create` statement in migrations. Changing to `id` breaks some things, especially in MySQL, since it's translated to `integer`, while the `serial` type was translated to `BIGINT UNSIGNED`.

I'm not sure how to go about solving it.

**Comment by josevalim** [comment]
It seems we have good reasons to keep this as is then. Closing it for now...
