### ISSUE TITLE
Repo.insert returns a changeset with missing fields

### ISSUE THREAD

**Issue by alex-shapiro** [elixir-ecto/ecto#1561]
### Environment

* Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace] Elixir 1.3.1
* PostgreSQL 9.5.3
* Ecto v2.0.2
* OSX 10.11.5

### Current behavior

The changeset returned by `Repo.insert` does not include db-generated fields that are not a table's primary key. Given the following schema:

**Postgres schema:**
```
    Column    |  Type  |                            Modifiers                             
--------------+--------+------------------------------------------------------------------
 uuid         | uuid   | not null
 order_number | bigint | not null default nextval('airplanes_order_number_seq'::regclass)
Indexes:
    "airplanes_pkey" PRIMARY KEY, btree (uuid)
```

**Elixir module:**
```elixir
@primary_key {:uuid, :binary_id, autogenerate: false}

defmodule Airplane do
  use Ecto.Schema

  schema "airplanes" do
    field :order_number, :integer
  end
end
```

The changeset returned by `Repo.insert` has a nil `order_number` field:

```elixir
plane = 
  %Airplane{uuid: Ecto.UUID.generate}
  |> MyApp.Repo.insert!()

# returns %Airplane{__meta__: #Ecto.Schema.Metadata<:loaded, "airplanes">, order_number: nil, uuid: "0889b587-da06-4982-b2af-0b818a5a9706"}
```

However, if you perform a query, it's clear that the database is saving the Airplane with an order number:

```elixir
MyApp.Repo.one(Airplane, uuid: "5f6e853d-e831-4430-817e-8c474ce0ce5b")

# returns %Airplane{__meta__: #Ecto.Schema.Metadata<:loaded, "airplanes">, order_number: 1, uuid: "0889b587-da06-4982-b2af-0b818a5a9706"}
```

### Expected behavior

The changeset returned by an Ecto insert should include db-generated fields:

```elixir
plane = 
  %Airplane{uuid: Ecto.UUID.generate}
  |> MyApp.Repo.insert!()

# returns %Airplane{__meta__: #Ecto.Schema.Metadata<:loaded, "airplanes">, order_number: 1, uuid: "0889b587-da06-4982-b2af-0b818a5a9706"}
```

**Comment by josevalim** [comment]
You need to tell Ecto to reload such fields by either using them as IDs or
setting the :read_after_writes options in your schema.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by alex-shapiro** [comment]
Oops, I should have read the options list more carefully. Thanks for the quick response.

Is there a reason why :read_after_write isn't the default for all fields? It's a little confusing that db-generated primary key fields are returned by default but other fields aren't.

**Comment by josevalim** [comment]
Because it is not supported for all databases and because that would cause
us to read data when we don't really need to. Also, Ecto doesn't know if a
certain field is a primary key if you don't tell Ecto about it.

On Monday, July 11, 2016, Alex Shapiro <notifications@github.com> wrote:

> Oops, I should have read the options list more carefully. Thanks for the
> quick response.
>
> Is there a reason why :read_after_write isn't the default for all fields?
> It's a little confusing that db-generated primary key fields are returned
> by default but other fields aren't.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-ecto/ecto/issues/1561#issuecomment-231633352>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbrRJiYY1W0afVK-HeQUJ61cfmuDzks5qUbR3gaJpZM4JI7r0>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
