### ISSUE TITLE
Improve SQL Sandbox lock limitation documentation to mention non-deadlock blocking

### ISSUE THREAD

**Issue by ericmj** [elixir-ecto/ecto#1570]
### Environment

* Elixir version (elixir -v): 1.4.0-dev
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 2.0.2
* Database adapter and version (mix deps):  postgrex 0.11.2, db_connection 1.0.0-rc.3

### Current behavior

See: https://gist.github.com/ericmj/99d201dbf4798e0e6497e807b3886391

### Expected behavior

This may be an application bug, but it's being hidden by timeouts and crashes from ecto. If you look at the gist we get a lot of timeouts from the sandbox pool, maybe those should be increased to be longer than the test timeout?

**Comment by fishcakez** [comment]
If the ownership timeouts are too long all other tests may fail because of pool (checkout) timeouts. Of course this is happening in the gist but more tests would fail to checkout. Which behaviour is least desirable?

**Comment by ericmj** [comment]
I bumped `ownership_timeout: 61_000` to make it higher than the test timeout. But I am still getting spammed with ecto errors.

The actual issue was an infinite loop inside of my app which I found from a test timeout. But that test timeout was hidden among 900 lines of ecto timeouts. Ideally I would only see the test timeouts.

**Comment by ericmj** [comment]
This branch reproduces https://github.com/hexpm/hex_web/commits/emj-ecto-issue. Use the "WIP" commit, the last commit fixes the issue.

**Comment by fishcakez** [comment]
The ownership errors are occurring because insert queries are blocking waiting for a lock to insert the user "eric". This can be resolved by following the `deadlock` advise in the `Ecto.Adaptes.SQL.Sandbox` documentation. However we should extend that section to point out the issue can also occur without deadlock if everything first attempts to gain the same lock.

**Comment by josevalim** [comment]
This is currently documented in the sandbox.

**Comment by fishcakez** [comment]
Only deadlocking is mentioned.
