### ISSUE TITLE
Repo.preload should force by default

### ISSUE THREAD

**Issue by ericmj** [elixir-ecto/ecto#1571]
Ecto has always had the policy to don't do any magic. The default should be to always make the database query, it's surprising to call `Repo` and ecto won't perform any queries.

**Comment by josevalim** [comment]
The problem is that it reduces composition. I would like to have the benefit of calling multiple functions that may want to preload data without paying the cost of preloading it every time. So I think not forcing by default is the less surprising behaviour.

**Comment by michalmuskala** [comment]
I've seen multiple times something like:
```elixir
result
|> Repo.preload(:foo)
|> Repo.preload(foo: :bar)
```

Yes, it's bad, but if we introduce this change, code like this would suddenly start issuing multiple queries.

Both ways are not ideal, but I agree with @josevalim on this one.

**Comment by ericmj** [comment]
@michalmuskala To me it seems very bad that we are not doing the second preload in your example. Even worse than:

```elixir
result
|> Repo.preload(:foo)
|> Repo.preload(:foo)
```

This is actually hurting composability, so I am not sure I am sold on that argument.
