### ISSUE TITLE
Add source metadata to log entries

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1579]
When looking at the logs, usually the part you're most interested in is the table, against which you're running the query. Unfortunately, today it's relatively hard to get it, since it's hidden in the `FROM` clause behind all the explicit selects.

I propose to add an additional `source` field to `Ecto.LogEntry` that would be filled on a best-effort basis (it's hard to extract it for subqueries, for example). If present the field would be displayed on the first line of the log, for example:
```
[debug] QUERY OK source=events db=3.2ms queue=0.1ms
SELECT e0."id", e0."name", e0."description", e0."inserted_at", e0."updated_at" FROM "events" AS e0 []
```

**Comment by Troush** [comment]
I tried to handle this.
But got stuck with question:
How to get proper table name?

Regex query statement is a bad idea, I think. Or not?

**Comment by josevalim** [comment]
@Troush when building the log entry struct, we typically have the query or the source already separated, so we should pass such information as well.

**Comment by Troush** [comment]
@josevalim I was inspecting https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/sql.ex#L512
And I can't find any `source` or `table` info there.  Just plain `statement` and other info.

**Comment by michalmuskala** [comment]
Closed by https://github.com/elixir-ecto/ecto/commit/0ea701ca6df04026a84c8a4f9a91b42bd2b97196
