### ISSUE TITLE
Repo.insert replaces embedded Changeset with Struct

### ISSUE THREAD

**Issue by seangeo** [elixir-ecto/ecto#1584]
Hi there,

We've found a problem with Changesets being replaced for embedded objects when a Repo.insert fails. It seems to happen when inserted into a table that has both an association and an embedded record and the associated record has a association of it's own.

I've created a minimal, failing example of this in a Phoenix app at https://github.com/sendle/ecto_embed_insert_bug

To describe the schema, it looks something like this:

[Parent](https://github.com/sendle/ecto_embed_insert_bug/blob/master/web/models/parent.ex)

```elixir
defmodule Parent do
  schema "parents" do
    timestamps
  end
end
```

[Child](https://github.com/sendle/ecto_embed_insert_bug/blob/master/web/models/child.ex)
```elixir
defmodule Child do
  schema "children" do      
    belongs_to :parent, EctoEmbedInsertBug.Parent
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:parent_id])
    |> assoc_constraint(:parent)
  end
end
```

[GrandChild](https://github.com/sendle/ecto_embed_insert_bug/blob/master/web/models/grand_child.ex)
```elixir
defmodule Grandchild do
  defmodule Embed do
    use EctoEmbedInsertBug.Web, :model

    embedded_schema do
      field :something, :string
    end

    def changeset(data, params) do
      data
      |> cast(params, [:something])    end
  end

  schema "grand_children" do
    belongs_to :child, Child
    embeds_one :embed, GrandChild.Embed

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:child_id])
    |> cast_embed(:embed, required: true)
    |> cast_assoc(:child)
    |> assoc_constraint(:child)
  end
end
```

If you attempt to create changeset for a `GrandChild`, along with a `Child` but referencing a Parent that doesn't exist, like so:

```elixir
changeset = GrandChild.changeset(%GrandChild{}, 
   %{embed: %{something: "test"}, child: %{parent_id: 123}})
```

You correctly get a changeset with a nested changeset at `changeset.changes.embed`.

If you then try to insert that changeset, using `Repo.insert(changeset)`, you correctly get an error back that contains a changeset for the child with the error about the missing parent, but the embed changeset at `changeset.changes.embed` has been converted into a `GrandChild.Embed` struct, which means passing the changeset to `traverse_errors/2` fails.

There is a failing test for this at https://github.com/sendle/ecto_embed_insert_bug/blob/master/test/models/grand_child_test.exs

I'd be happy to look at fixing this too, if someone can give me some pointers on how to replicate this structure in the Ecto test suite.

Thanks

**Comment by josevalim** [comment]
@seangeo thank you for the report and a mechanism to reproduce the issue. I don't have any particular tip on how to reproduce the error in our test suite besides giving the existing structures in `integration_test` a try. Have you tried that already? Are there more specific instructions on how we could help? :)

**Comment by seangeo** [comment]
Thanks @josevalim. I've had a look at the structures in `integration_test` and can't find the structure that I need to reproduce the issue. Is it ok to create some new tables and schema to get a failing test in place? Is `integration_test/support/migration.exs` and `integration_test/support/schema.exs` the right place to do that?

**Comment by josevalim** [comment]
@seangeo it is generally not recommended to do that, because it would get harder to maintain with time. However, it is fine to add fields to the existing structures. Would that be enough? Maybe we can add something to order? https://github.com/elixir-ecto/ecto/blob/master/integration_test/support/schemas.exs#L218

**Comment by seangeo** [comment]
That could work. I'll give it a shot. Thanks.
