### ISSUE TITLE
Provide Ecto.Schema.load/3

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1590]
It's currently relatively hard to run raw SQL queries and properly load them into structs with loading all parameters into proper types.

We should provide `Ecto.Schema.load/3` function to do that:
```elixir
@spec load(schema :: module, columns :: [atom], rows :: [term]) :: struct
```

We could also consider a schemaless version:
```elixir
@spec load(%{atom => Ecto.Type.t}, columns :: [atom], rows :: [term]) :: map
```

**Comment by josevalim** [comment]
@michalmuskala I am worried about adding a `Ecto.Schema.load/3` because that will be added to the user schema. Maybe we should define `__load__/2` in every schema instead?

**Comment by josevalim** [comment]
We probably need `load(schema, map)` as well.

**Comment by ericmj** [comment]
`Ecto.load(schema, map | keyword)` seems better. It solves the import problem and is a parallel to `Kernel.struct/2`.

**Comment by josevalim** [comment]
@ericmj Sounds good to me!
