### ISSUE TITLE
@schema_prefix issues

### ISSUE THREAD

**Issue by foeken** [elixir-ecto/ecto#1591]
* Elixir version (elixir -v): 1.2.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6.27
* Ecto version (mix deps): 2.0.2
* Database adapter and version (mix deps): ?
* Operating system: OSX Sierra

## Nested :prefix usage
It is undocumented if the :prefix option is supported to change within a query. If I want to preload an association from a different prefix I could do `preload(mode: ^custom_query_with_different_prefix)`, but it doesn't work. Is this a bug or intended behavior? Either way, it should be clearly specified what the limits of the feature are.

**Comment by josevalim** [comment]
Which Ecto version are you using? When opening an issue, there is a template. Please fill it up otherwise I will end-up just re-asking the questions here.

**Comment by foeken** [comment]
Argh. Sorry about that. I was looking at the `phoenix_ecto` version instead of the Ecto version which happened to be exactly the same (2.0.2) but I was running an older Ecto. So that was why the schema_prefix stuff did not work :(

So that just leaves the question about nested :prefix options in the docs. It seems to be unsupported as the `schema_prefix` that was hard coded in the model is also overridden if the query prefix is set for another model.

```elixir
r = Right 
|> Ecto.Queryable.to_query 
|> Map.put(:prefix, "schema_b") 
​
e = Elevation 
|> Ecto.Queryable.to_query 
|> Map.put(:prefix, "schema_a")
|> preload(right: ^r)
|> Shield.Repo.all  
```

**Comment by josevalim** [comment]
@foeken do you mean the "schema_b" is not being taken into account?

**Comment by foeken** [comment]
Yes, exactly.

**Comment by josevalim** [comment]
Ah, this is tricky. :(

I can see both situations where you want the parent prefix to be used and when you don't want that to happen.

One option is to preload it later and pass the prefix option:

```elixir
e = Elevation 
|> Ecto.Queryable.to_query 
|> Map.put(:prefix, "schema_a")
|> Shield.Repo.all  
|> Shield.Repo.preload([right: ^r], prefix: "schema_b")
```

**Comment by josevalim** [comment]
The fix is to change this line:

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L154

So it does:

    | prefix: query.prefix || prefix}

But this means that the query prefix will never be used if it is set in the schema, not even the option approach sent above.

**Comment by foeken** [comment]
I've been playing with your suggestions. I agree that there are use-cases for both behaviors that would seem equally plausible. Supporting both would be a challenge. (I tried your code change and indeed that works for my situation)

Your first solution also works, but when the queries (and preloads) get more complex this syntax is quite confusing. 

In addition, I was wondering if there is a way to supply the prefix for joins too?

**Comment by josevalim** [comment]
> In addition, I was wondering if there is a way to supply the prefix for joins too?

No, it is per query. The main goal behind prefixes is to support tenancy. If you need to talk between difference prefixes then the best approach for now is to issue separate queries.

**Comment by foeken** [comment]
Okay, that's clear. I will close this issue :) Thank you for clarifying! Ans once again sorry for the mixup in Ecto versions.
