### ISSUE TITLE
Creating an empty table in mysql

### ISSUE THREAD

**Issue by xcambar** [elixir-ecto/ecto#1595]
### Current behavior

While working on #1594, I noticed that creating a table without any column (unusual, isn't it? 😉 ),
the generated SQL query for MySQL is invalid:

```
  defmodule DuntMigration do
    use Ecto.Migration

    def change, do
      create table(:dummy)
    end
  end

=> CREATE TABLE "dummy" () ENGINE = INNODB;
```

### Expected behavior

It should generate `CREATE TABLE "dummy" ENGINE = INNODB;`.

I'll gladly do it, feel free to assign me.

**Comment by josevalim** [comment]
@xcambar i can't  assign you to it but a PR is welcome :D
