### ISSUE TITLE
Broken link to Getting Started guide in Docs

### ISSUE THREAD

**Issue by andyw8** [elixir-ecto/ecto#1607]
https://hexdocs.pm/ecto/Ecto.html links to https://hexdocs.pm/getting-started.html which returns a 404.

Strangely, https://github.com/elixir-ecto/ecto/blob/v2.0.3/lib/ecto.ex#L27 points to a [different URL](https://github.com/elixir-ecto/ecto/tree/master/examples/simple), but that also returns a 404.

**Comment by josevalim** [comment]
Fixed, thank you!
