### ISSUE TITLE
CI is failing likely to an overload protection system

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1608]
Details: https://travis-ci.org/elixir-ecto/ecto/jobs/149202101

/cc @fishcakez

**Comment by fishcakez** [comment]
This is still happening and appears to only occur when mysql tests take approximate twice the normal time. Likely in that scenario the pool queue time is very slow and so overload protection would naturally kick in. Are we just getting unlucky with travis containers or should we investiagte mariaex? Shall we disable overload protection for mysql tests? All tests? Always?

**Comment by josevalim** [comment]
@fishcakez should we include timeout values? If we increase timeout values and they continue happening, then I think we should investigate.

**Comment by fishcakez** [comment]
Seems like suddenly queue time goes almost immediate to slow. Can see client drop probability rise near slow (above target) queue (search for `drop`) https://api.travis-ci.org/jobs/158505351/log.txt?deansi=true. A persistent queue time of 645ms (as in the log) should result in drops but only once allowance has been used up. Needs further investigation to see if allowance has been used up or if there is a bug in the implementation.

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-ecto/ecto/commit/00f132830cff970df576b9c91875c3fc3bcd50cf.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
