### ISSUE TITLE
Should custom primary keys uniqueness be validated?

### ISSUE THREAD

**Issue by pareeohnos** [elixir-ecto/ecto#1611]
I'm not sure whether this is by design, but I think it's something that should be handled by Ecto. For a standard setup, the primary key is an integer ID which is fine. In an app I'm working on, this isn't applicable in a number of models, so as per the instructions, I have changed the primary key:

    @primary_key { :id, :string, [] }
    @foreign_key_type :string

This works, however due to the primary key not being auto-generated, I am having to set the value manually, so my changeset function now looks like this:

    def create_changeset(params \\ %{}) do
      %__MODULE__{}
      |> cast(params, [:id, :name])
      ...
    end

This works well, however in writing some tests, I noticed that Ecto doesn't perform any validation on ensuring that the primary key is unique. I understand this makes sense when it is auto-generated for an integer as the database is responsible for producing the next ID, however in a custom String primary key such as this, that is not the case.

If I run the following

    MyModel.create_changeset(%{ id: "ID1",  name: "Name1" }) |> Repo.insert
    MyModel.create_changeset(%{ id: "ID1",  name: "Name2" }) |> Repo.insert

I obviously expect it to fail due to a duplicate ID, however I feel that Ecto should automatically be checking for this error on custom primary keys given that for it to be a primary key, it has to be unique.

Currently, the only remedy for this is to add the following to my changeset function:

    ...
    |> unique_constraint(:id, name: :my_models_pkey)

Without this, I receive the following error:

    ** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: my_models_pkey

    If you would like to convert this constraint into an error, please
    call unique_constraint/3 in your changeset and define the proper
    constraint name. The changeset defined the following constraints:

    * unique: my_models_name_index

             (ecto) lib/ecto/repo/schema.ex:417: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
           (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
             (ecto) lib/ecto/repo/schema.ex:403: Ecto.Repo.Schema.constraints_to_errors/3
             (ecto) lib/ecto/repo/schema.ex:195: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
             (ecto) lib/ecto/repo/schema.ex:608: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
             (ecto) lib/ecto/adapters/sql.ex:480: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1063: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:987: DBConnection.run_begin/3

As well as automatically handling the uniqueness of the primary key, does it not also make sense for `cast/3` to not also automatically allow for the custom primary key to be set if it is not set to `autogenerate`?

### My setup

- Elixir 1.2.4
- Postgres 9.4.1.0
- Ecto 2.0.3
- Postgrex 0.11.2
- OS X 10.11.5

**Comment by josevalim** [comment]
The goal of unique_constraint is for you to map errors that should be reported back to users. That's why you should explicitly opt-in for using unique_constraint because sometimes those are actual bugs in your application that you don't want to report to users and actually let your request fail. So I don't think it should be done automatically.
