### ISSUE TITLE
Subqueries with two same named columns from different tables

### ISSUE THREAD

**Issue by isaacsanders** [elixir-ecto/ecto#1616]
### Environment

* Elixir version (elixir -v): 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.5.2
* Ecto version (mix deps): 2.0.3
* Database adapter and version (mix deps): Postgrex 0.11.2
* Operating system: OS X "El Capitan"

### Current behavior

This appears to be a known phenomenon, according to https://github.com/elixir-ecto/ecto/blob/fb397116e25733d27b64e75df9ccef1e603121e0/lib/ecto/query/planner.ex#L194.

When I try to make a query like

```elixir
query = from a in "foo",
join: b in "bar", on: a.b_id == b.id,
select: %{
  b_id: b.id,
  foo_alpha: a.alpha,
  bar_alpha: b.alpha
}

from z in subquery(query),
group_by: [z.b_id],
select: %{
  b_id: z.b_id,
  foo_alpha: max(a.alpha),
  bar_alpha: sum(b.alpha)
}
```

The error in the `Ecto.Query.Planner` occurs.

### Expected behavior

I would expect to be able to have the aliases that I declare for the subquery to propagate upwards and allow me to reference the columns in the query.

**Comment by josevalim** [comment]
Yes, it is a known limitation. I am keeping this open because we do want to support map based names in subqueries.

**Comment by josevalim** [comment]
@isaacsanders the biggest trouble is in the adapter. SQL is going to complain if you have two fields with the same name in the subquery so you need to use AS. So we would need to include support for naming fields in Ecto.Query's select, make the adapters respect it, then we can change the planner.

**Comment by isaacsanders** [comment]
So the %{ alias: table.actual } doesn't convert to `AS`es at the end of the day?

**Comment by josevalim** [comment]
@isaacsanders currently no. We only use the field names.
