### ISSUE TITLE
Unexpected syntax error in preload expression (nested queries)

### ISSUE THREAD

**Issue by foeken** [elixir-ecto/ecto#1618]
### Environment

* Elixir version (elixir -v): 1.3.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6
* Ecto version (mix deps): 2.0.3 (master: 8f649b7)
* Operating system: OSX Sierra

### Current behavior

```elixir
elevations_query = from elevation in Shield.Elevation

from user in Shield.User,
preload: [elevations: {^elevations_query, :right}]
```

Raises:

```
** (Ecto.Query.CompileError) `{^elevations_query, :right}` is not a valid preload expression. preload expects an atom, a (nested) list of atoms or a (nested) keyword list with a binding, atoms or lists as values. Use ^ if you want to interpolate a value
```

But:

```elixir
elevations_query = from elevation in Shield.Elevation

from user in Shield.User,
preload: [elevations: ^{elevations_query, :right}]
```

Works as expected :)

### Expected behavior

The syntax checker is probably confused since this is possible. I expect the first syntax to work.

**Comment by josevalim** [comment]
Bug confirmed. Thank you.

**Comment by Troush** [comment]
I will take this :+1: If no rejections

**Comment by josevalim** [comment]
Please go ahead!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
@Troush ping.

**Comment by josevalim** [comment]
Given that supporting this will add a lot of code complexity for little gain, I have improved the error message to make clear that `^` must be added to the outermost preload. Thank you!

**Comment by Troush** [comment]
@josevalim Sorry, totally forget about me taking this issue. My bad :(
