### ISSUE TITLE
Reference on_delete: :delete_all not reflected in database

### ISSUE THREAD

**Issue by RomarioLopezC** [elixir-ecto/ecto#1620]
I have this migration 

```
defmodule MyApp.Repo.Migrations.CreateDog do
  use Ecto.Migration

  def change do
    create table(:dogs) do
      add :user_id, references(:users, on_delete: :delete_all)

      timestamps()
    end
    create index(:dogs, [:user_id])

  end
end
```
I already did `mix ecto.rollback`
`mix ecto.migrate`
`mix ecto.reset`

But is not getting reflected in my db, the foreign_key is created but with the option on_delete: restrict

**Comment by josevalim** [comment]
Can you please answer the questions asked when creating an issue?

```
* Elixir version (elixir -v):
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps):
* Database adapter and version (mix deps):
* Operating system:
```

**Comment by RomarioLopezC** [comment]
I already solve it, it was a mistake that i made @josevalim thanks!, do you know if ecto is going to support something like this that we had in rails? `belongs_to :user, dependent: :destroy`

**Comment by josevalim** [comment]
We already support "dependent", check `:on_delete` option. Although the database way is preferred. Also please close the issue next time if you have solved it. :)
