### ISSUE TITLE
Support on_replace: :update for has_one/belongs_to

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1627]
Since those are one-to-one relationships it makes sense to allow editing them without passing the original id, they can be always uniquely identified. Currently ecto will not like that and will require to always pass the association id.

When `on_replace` is set to `:edit`, the associated record will be always edited with new params, regardless if they contain the id or what is the value of the id field.

**Comment by josevalim** [comment]
@michalmuskala :+1:. Shall we call it `:update` though?

**Comment by michalmuskala** [comment]
Yes, upgrade is better.

**Comment by eniolopes** [comment]
Can I work on this one?

**Comment by josevalim** [comment]
Yes, please!

**Comment by eniolopes** [comment]
👍
