### ISSUE TITLE
Add total_time to the LogEntry struct

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1632]
We should have an additional measurement in the query struct that includes as much of what ecto is doing as it's possible - translation of query struct into SQL, encoding of params, queuing, decoding, etc. The timer should start as soon as a `Repo` function is called and be stopped when it returns (ideally, in practice it can't be that, but we should be able to get close).

\cc @fishcakez

**Comment by deadtrickster** [comment]
Is it possible to also add LogEntry field for module that initiated query? I think it can be set when query macros expand.

**Comment by josevalim** [comment]
This is actually quite tricky to do because it would require changing the adapter to receive the total time, since we want to consider what is happening at the repo level. It is also more work for us to do and the current instrumentation already tackles the hot paths.
