### ISSUE TITLE
ecto 2.0.4: cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by bill-mybiz** [elixir-ecto/ecto#1633]
### Environment

* Elixir version (elixir -v): 1.3.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 9.5.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
* Ecto version (mix deps): 
  * ecto 2.0.4 (Hex package) (mix)  
    locked at 2.0.4 (ecto) 03fd3b9a  
    ok

* Database adapter and version (mix deps):
  * postgrex 0.11.2 (Hex package) (mix)  
    locked at 0.11.2 (postgrex) 139755c1  
    ok  
* Operating system: Ubuntu 16.04

### Current behavior

`mix ecto.drop` (ok)
`mix ecto.create` (ok)
`mix ecto.migrate` gives error:
```
19:27:44.890 [info]  create table ibgibs
** (Postgrex.Error) ERROR (syntax_error): cannot insert multiple commands into a prepared statement
    (ecto) lib/ecto/adapters/sql.ex:180: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:69: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:101: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:99: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:121: Ecto.Migrator.attempt/6

```

### Expected behavior
It works when I downgrade Ecto back to v2.0.2:

```
19:26:17.784 [info]  == Running IbGib.Data.Repo.Migrations.CreateIbgibs.change/0 forward

19:26:17.784 [info]  create table ibgibs

19:26:17.816 [info]  create index ibgibs_ib_index

19:26:17.832 [info]  create index ibgibs_gib_index

19:26:17.850 [info]  create index ibgibs_ib_gib_index

19:26:17.862 [info]  == Migrated in 0.0s

```

Migration file:
```
defmodule IbGib.Data.Repo.Migrations.CreateIbgibs do
  use Ecto.Migration

  def change do
    create table(:ibgibs, comment: "Primary table for ibGib data.") do
      add :ib, :string
      add :gib, :string
      add :data, :map
      add :rel8ns, :map

      timestamps
    end

    create index(:ibgibs, [:ib], name: :ibgibs_ib_index)
    create index(:ibgibs, [:gib], name: :ibgibs_gib_index)
    create unique_index(:ibgibs, [:ib, :gib], name: :ibgibs_ib_gib_index)
  end
end
```

Model: 
```
defmodule IbGib.Data.Schemas.IbGibModel do
  @moduledoc """
  This is the primary model that simply persists IbGib in the db.
  """
  use IbGib.Constants, :error_msgs

  use Ecto.Schema
  import Ecto.Changeset
  alias IbGib.Data.Schemas.ValidateHelper

  schema "ibgibs" do
    field :ib, :string
    field :gib, :string
    field :data, :map
    field :rel8ns, :map

    timestamps
  end

  @required_fields ~w(ib gib rel8ns)
  @optional_fields ~w(data)
  @min 1
  @max 64

  def changeset(content, params \\ :empty) do
    content
    |> cast(params, @required_fields, @optional_fields)
    |> validate_required([:ib, :gib, :rel8ns])
    |> validate_length(:ib, min: @min, max: @max)
    |> validate_length(:gib, min: @min, max: @max)
    |> validate_change(:rel8ns, &ValidateHelper.do_validate_change(&1,&2))
    |> validate_change(:data, &ValidateHelper.do_validate_change(&1,&2))
    |> unique_constraint(:ib, name: :ibgibs_ib_gib_index)
    # |> unique_constraint(:gib, name: :ibgibs_ib_gib_index)
  end
end
```

Full project at: https://github.com/ibgib/ibgib, with this particular app being [ib_gib](https://github.com/ibgib/ibgib/tree/master/ib_gib_umb/apps/ib_gib).

**Comment by josevalim** [comment]
@bill-mybiz so the problem seems to be related to the comment. if you drop the comment, you should be good to go!

**Comment by josevalim** [comment]
@bill-mybiz I am currently revert the comments feature until we figure out how to make it work with prepared statements. So I would recommend you to drop `:comment` for now and rock on Ecto 2.0.4. :)

**Comment by eniolopes** [comment]
@josevalim can I help with this? This seems to be related to https://www.postgresql.org/docs/9.2/static/sql-prepare.html, I don't remember seeing it on our source code, `execute_ddl` uses prepared statements? A possible solution would be to have a query run subsequently for adding the comments to the table.

**Comment by josevalim** [comment]
@eniolopes i was just pinging you in the other issue. :) I am not sure what is the best way to solve this... maybe wrapping in being/end would help? for example, we do it for some of the migrations. Adding an integration test (basically adding comments to one of the migrations in integration_test) would help us catch those as well. :)

**Comment by eniolopes** [comment]
@josevalim Sounds good, will take a look at that, this weekend will be working on this an the other issues, expect PRs :)

**Comment by bill-mybiz** [comment]
@josevalim Awesome! Removing the comment got the migration up and going. Thanks for the quick diagnosticatin'!

**Comment by eniolopes** [comment]
@josevalim I'm looking into getting this to work with prepared statements, and as far as I understood, every query is being prepared and so if there is more than one statement per query, which is the case for adding comments, it will fail. 

Question is, do we need to use prepared statements for migration queries? It might not make sense to use them for migrations, if this is the case we just need to run migration queries without preparing them. 

Answering your question about using `begin/end` this will not avoid the problem with prepared statements because we would still be sending multiple statements in one query, unless we change the way we are doing this which means we have to move the logic that adds comments to a different layer.

**Comment by fishcakez** [comment]
@eniolopes postgrex only supports prepared queries

**Comment by eniolopes** [comment]
@fishcakez thanks for clarifying that.

If we want to support this, we will need to override [this](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/sql.ex#L128-L132) on the postgres adapter to support execution of multiple queries.

Basically allow `execute_ddl/1` to return a list of queries to be executed.

**Comment by josevalim** [comment]
@eniolopes we can certainly do the execute_ddl change. :) As a matter of fact, it is how it worked before, but we removed it because none of the adapters used it. See this commit: d4a9f50812153c2ecbc67e6dcf996440343a9969

**Comment by josevalim** [comment]
@eniolopes so I am guessing we can revert the commit above. Revert the revert commit (where we reverted the comment feature), change it to use lists, and add an integration test. Wdyt?

**Comment by fishcakez** [comment]
@fire does the suggested fix help with your snappydata issue (sorry I forget the details)?

**Comment by fire** [comment]
Will take a look later today.

**Comment by eniolopes** [comment]
@josevalim sounds good, will do it!
