### ISSUE TITLE
Support `@primary_key false` in embedded schemas

### ISSUE THREAD

**Issue by chrismccord** [elixir-ecto/ecto#1638]
As discussed with @michalmuskala, we should remove the primary key requirement on embedded schemas. I think having it as the default can remain and would allow this to be a forwards compatible change. The issue with the current behavior is for drivers like postgres, having an auto generated primary key on the embedded schema is mostly like pointless data for the majority of users, so it would be nice to add `@primary_key false` and skip the `id` key generated on embedded schemas when desired. I would be happy to help with this change, but I'm tapped out until after ElixirConf and Phoenix 1.3 ships. Thoughts?

**Comment by josevalim** [comment]
I am fine with removing the requirement but keep it in mind we needs IDs if you want to track changes using put_assoc/put_embed in changesets. Otherwise it is hard for us to know how the data in the DB maps to the one sent by the user.

**Comment by chrismccord** [comment]
😻 😻 😻
