### ISSUE TITLE
Update documentation to include port

### ISSUE THREAD

**Issue by wm** [elixir-ecto/ecto#1645]
I spent a long time debugging a simple environment issue on my end. Basically postgres was running on a non-standard port (15432). I might have figured out why my db connections were failing sooner if it was not for the fact that `mix ecto.create` worked.

Because `create` works I did not think that my db config was at fault.

I am opening the issue here to suggest adding `host: "localhost",` and `port: "5432"` to the config settings in the README which may ring bells for folks like me. I can add that via a pull if you like.

I am also opening this to ask why `ecto.create` works at all postgres running on a non standard port?

### Environment

* Elixir 1.3.2
* PostgreSQL 9.4
* Ecto 2.0.4
* Postgrex 0.11.2
* Operating system OSX
* Boxen which has postgres running on port 15432

### Current behavior

`mix ecto.create` succeeds

### Expected behavior

`mix ecto.create` fails?

__Note__ 
I had opened this as a [question on StackOverflow](https://stackoverflow.com/questions/39091408/why-does-phoenix-ecto-postgresx-fail-to-connect-in-dev/39113622#39113622) too - which I answered. So people will find it there at least.

Also: Ecto is amazing!

**Comment by josevalim** [comment]
@wm agreed! Can you please send a PR to the getting started guide and the README? Thank you!

**Comment by wm** [comment]
ok, done: https://github.com/elixir-ecto/ecto/pull/1656
