### ISSUE TITLE
Ecto is not supporting local languages while inserting into Mysql

### ISSUE THREAD

**Issue by ok-madan** [elixir-ecto/ecto#1647]
### Precheck

I am trying to insert one indian language string into mysql database using Repo.insert, but in database that value of that column showing like ???????????????

while creating database in mysql i am using ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; for unicode support, and inside elixir model i am using column type as string( field :displayname, :string )

I am not sure Ecto supports other than english language while insert into DB, need support from anybody how to do that.

### Environment

* Elixir version (Elixir 1.3.2):
* Database and version (MySQL 5.6.27 ):
* Ecto version (1.1.9):
* Database adapter and version (mariaex 0.7.7 ):
* Operating system: Ubuntu 14.04.3 LTS

### Current behavior

String : ಆಗ್ತಾಇಲ್ಲ
After insert into mysql db using Repo.insert, in DB it is showing like ???????

### Expected behavior
String : ಆಗ್ತಾಇಲ್ಲ
After insert into mysql db using Repo.insert, in DB it should show ಆಗ್ತಾಇಲ್ಲ

**Comment by ericmj** [comment]
This seems like an issue with mysql or the elixir driver mariaex. Ecto just passes the utf8 strings along to the driver.

**Comment by josevalim** [comment]
@ok-madan yes, please file an issue on https://github.com/xerions/mariaex. Please include the mariaex version (it can be found in `mix deps`) and some sample commands in your report.

**Comment by ok-madan** [comment]
@ericmj , @josevalim  Thanks for quick response and clarified my issue, i will create issue at mariaex repo.

**Comment by samueltthomas** [comment]
I had the same issue and it was resolved after I set the value of the locale environment variable LC_ALL. Please check https://samueltthomas.com/setting-locale-for-fixing-unicode-issue-for-elixir for more info

**Comment by mackstar** [comment]
For anyone else struggling with this, just add 
```
binary_as: :field_type_blob
```
to your connection and it solves this issue.
