### ISSUE TITLE
Fields that default to empty string have unexpected behavior

### ISSUE THREAD

**Issue by bgeihsgt** [elixir-ecto/ecto#1648]
### Environment

* Elixir version (elixir -v): 1.3.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 2.04
* Database adapter and version (mix deps):
* Operating system: OS X

### Current behavior

The commit for `empty_values` (https://github.com/elixir-ecto/ecto/commit/af26b32854dce236cffc7e36ad0b9acad89969b7) has caused some unexpected behavior for fields that you want to default to empty string.

I have a `notes` field defined like this:

```
field :notes, :string, default: ""
```

When I create a changeset without a `notes` key, the column gets correctly set to `""` in the DB.

When I create a changeset with `notes` set to `""`, the field gets sent to the DB as NULL. This breaks a not-null constract I have on that column.

### Expected behavior
A few things here:

- I'm not sure converting to `nil` is the right answer here. I understand the reasoning to do this (HTML forms don't send nil/null), but is that really in Ecto's scope to handle? Empty string and `nil` are semantically different and to treat them the same by default feels like over-reach and coupling Ecto too tightly to the web (Ecto 2.0 was designed to be a move away from over-reach, right?). Perhaps `empty_values` should be opt-in instead of set to `[""]` by default?
- I've set a default on this field. If the default is set and I've set it to an empty value (`nil` or `""` in this case), I'd expect it to use the default value.
- `empty_values` as a setting on the entire changeset feels too coarse. I'd like to say "Hey just for notes, don't use "" as an empty value" instead of setting empty_values to `[]` for the entire changeset.

Thanks for this great library!

**Comment by josevalim** [comment]
Good catch, this is a bug. We will fix it and release a new version. :)

**Comment by bgeihsgt** [comment]
Thanks José!

**Comment by facto** [comment]
@josevalim just making sure... was that commit supposed to close #1649 instead? This doesn't seem related at first glance.

**Comment by michalmuskala** [comment]
Yeah, this looks like an error, I'm going to open this back.

**Comment by josevalim** [comment]
Yup, my bad!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by rranelli** [comment]
I've had to fix some validations when updating to ecto 2.0 because of this issue. Not a big deal, but I was surprised by the new behaviour.

**Comment by josevalim** [comment]
@bgeihsgt can you please try master out and let me know if it works as expected? Thank you!

**Comment by bgeihsgt** [comment]
Worked like a charm, thanks @josevalim!

**Comment by denispeplin** [comment]
What is the way to actually change a value from nil to ""?
I have a real use case: answer to a question can be empty, and I won't ask it again. But I can't update a field via changeset:
```elixir
params = %{"name" => ""}
struct = %Guest{name: nil}
changeset = Ecto.Changeset.cast(struct, params, ~w(name)a)
changeset.changes
%{}
```

**Comment by josevalim** [comment]
@denispeplin we don't provide an official API for it yet because we are deprecating the existing arguments. However, you can achieve it by doing this:

```elixir
changeset = Ecto.Changeset.change(struct, %{})
changeset = %{changeset | empty_values: []}
Ecto.Changeset.cast(struct, params, ~w(name)a)
```

We will provide a better API in future versions.

**Comment by atomkirk** [comment]
Wait, @josevalim, how does that work?
```
changeset = Ecto.Changeset.change(struct, %{})
changeset = %{changeset | empty_values: []}
Ecto.Changeset.cast(struct, params, ~w(name)a)
```
you're not using the changeset you created in the cast.
I need to use cast AND turn off the empty values
