### ISSUE TITLE
`validate_required` validations seem to be run only once per changeset pipeline

### ISSUE THREAD

**Issue by miskolc** [elixir-ecto/ecto#1651]
### Environment

* Elixir version 1.3.2
* PostgreSQL 9.4
* Ecto version 2.0.3
* Database adapter and version (mix deps):
postgrex 0.11.2
phoenix_ecto 3.0.1 
* Operating system:
Ubuntu

### Current behavior
I'm creating a `slug` based on the record's `name` field
```
   |> validate_required([:name])
   |> put_slug
   |> validate_required([ :category, :link, :slug, :interest])
```

The `put_slug` method assumes that if it was reached the validation of the name column succeded therefore I can use the `name` to generate the `slug` column.

When I try to test it with no attributes

```
test "changeset with no attributes" do
    changeset = Shop.changeset(%Shop{}, @no_attrs)
    refute changeset.valid?
  end
```

It doesn't break at the validation of the missing `name` attribute but at this line of code in the `put_slug` method

`name = get_change(changeset, :name)`

and I get this error

```
** (FunctionClauseError) no function clause matching in String.Casing.downcase/2
     stacktrace:
       (elixir) unicode/unicode.ex:313: String.Casing.downcase(nil, "")
```

However if replace that line with this:
`name = get_change(changeset, :name) || ""
`
the test passes however that is not what I was expecting. I expected the validation of the name colomn to fire first and in my opinion that would have been more elegant. It would have been clear from the pipeline of actions done on the changeset that I want to have the name if I would create a slug. If I treat this case inside the put_slug method I wouldn't be that obvious.

I suspect that all `validate_required` validations are run at the same time regardless of their position in the pipeline. Right?

### Expected behavior

Be able to use `validate_required` multiple times for one single changeset pipeline and to have them executed in the order they appear in the pipeline.

**Comment by michalmuskala** [comment]
`validate_required` will add an error to the changeset on errors - it won't stop the pipeline. You can check in your `put_slug` function if the changeset is valid at this point, or handle the empty case like you showed.
