### ISSUE TITLE
Ecto.Changeset.traverse_errors fails without types key

### ISSUE THREAD

**Issue by Gazler** [elixir-ecto/ecto#1673]
### Environment

* Ecto version (mix deps): 2.0.2

### Current behavior

When manually generating a changeset with an error, the errors can't be traversed.

```
iex(1)> %Ecto.Changeset{} |> Ecto.Changeset.add_error("foo", "bar") |> Ecto.Changeset.traverse_errors(&(&1))
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
```

This can be fixed by setting the types on the changeset:

```
iex(1)> %Ecto.Changeset{} |> Ecto.Changeset.add_error("foo", "bar") |> Map.put(:types, %{}) |> Ecto.Changeset.traverse_errors(&(&1))
%{"foo" => [{"bar", []}]}
```

An example use case is converting an error such as `{:error, :not_found}` to a format that is expected by the view.

cc @michalmuskala

**Comment by josevalim** [comment]
Dear @gazler, you are not supposed to create a changeset by hand. :) You need to call `Ecto.Changeset.change({data, types})` or `Ecto.Changeset.change(struct)` before.

**Comment by Gazler** [comment]
@josevalim This is true, I can do:

```
Ecto.Changeset.change({%{}, %{}}) |> Ecto.Changeset.add_error("foo", "bar") |> Ecto.Changeset.traverse_errors(&(&1))
%{"foo" => [{"bar", []}]}
```

I forgot to mention that @michalmuskala and I discussed making the error better. Perhaps we should also update the Changeset moduledoc to advise against manually creating a changeset.

If possible, the error should also advise against creating a changeset by hand.
