### ISSUE TITLE
Support {:system, ENV_NAME, default} tuples

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#1679]
I think this will remove duplication in config.exs/prod.exs by letting set environment variables and safely fallback to defaults on development environment.

**Comment by josevalim** [comment]
@AndrewDryga we have no plans in adding more features related to this part of the codebase. The tuple is already a hack related to releases and we plan to work towards removing it rather than adding more. :)

**Comment by AndrewDryga** [comment]
What is your current plans on fixing this? Maybe I would know about new best practice :)

**Comment by josevalim** [comment]
No solid plans for now besides eventually including releases in Elixir. Maybe @bitwalker has something in mind in distillery right now.

**Comment by bitwalker** [comment]
Other than the `{:system, "VAR"}` tuple, you can use `REPLACE_OS_VARS=true` in conjunction with `some_setting: "$VAR_NAME"` in your `prod.exs` when running releases built with distillery, and `$VAR_NAME` will be replaced with the value of that variable in the environment.  The behaviour of `REPLACE_OS_VARS=true` could be automated when the presence of `System.get_env/1` calls are found in `config.exs` as well, but that is currently not the case, and I don't think it solves the problem of runtime configuration well enough. 

Configuration has some fairly strict rules when it comes to releases, and regardless to what degree releases are introduced into Elixir proper, there are some limits imposed by both the Erlang runtime and release handling in OTP itself. It's something I'm trying to solve, but I don't have any clear ideas on the best path yet.

**Comment by AndrewDryga** [comment]
Actually I already use `REPLACE_OS_VARS`. It's me, that guy that asks many questions about environment variables in distillery repo :).

**Comment by AndrewDryga** [comment]
I just think that it's ugly to mix different declarations in a single config file, we have `{:system, ..}` tuples and `"${ENV_NAME}"` strings that gets replaced only for ECTO.
