### ISSUE TITLE
Support databases written in Erlang

### ISSUE THREAD

**Issue by KeeperB5** [elixir-ecto/ecto#1685]
It would be nice if Ecto had support for databases written in Erlang.

- [CouchDB](http://couchdb.apache.org/) (CouchDB is not dead, 2.0 will be released any day now.)
- [CouchBase](http://www.couchbase.com/)
- [Mnesia](http://erlang.org/doc/man/mnesia.html)
- [Riak](http://basho.com/products/)

All of these promote reliability and scalability. Exactly what all other Erlang-based solutions, including Elixir and Phoenix do as well.

**Comment by josevalim** [comment]
Yes please! Anyone is free to implement adapters to any database they want to. :)

**Comment by AndrewDryga** [comment]
@josevalim should we PR Mnesia adapter to Ecto or publish as separate ecto_mnesia package?

**Comment by josevalim** [comment]
@AndrewDryga as a separate package for now but I would love to review it.

**Comment by AndrewDryga** [comment]
@josevalim some really dirty (we will clean it up) stuff is happening here: https://github.com/Nebo15/ecto_mnesia
