### ISSUE TITLE
Ecto.Adapters.SQL.Sandbox.Connection.connect violates DBConnection.connection/2 callback spec

### ISSUE THREAD

**Issue by KronicDeth** [elixir-ecto/ecto#1697]
### Environment

* Elixir version (elixir -v): 1.3.2
* Erlang version: 18.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 6beeda443b8204d8c38113866a8e656d9fa546ed
* Database adapter and version (mix deps): N/A
* Operating system: OSX

### Current behavior

I have a branch where I'm trying to get Ecto to pass `mix dialyze` on my path to get Erlang 19 working with `mix dialyze`.   I decided to test Erlang 18.3 first because `mix dialyze` works for my projects that use Ecto, so I thought Erlang 18.3 would be a good control.  There are many dialyze warnings for Ecto with Erlang 18.3, but one that requires a design decision from you the maintainers is this:

```
lib/ecto/adapters/sql/sandbox.ex:295: The inferred type for the 1st argument of connect/1 ({atom() | tuple(),_}) is not a supertype of [{atom(),_}], which is expected type for this argument in the callback of the 'Elixir.DBConnection' behaviour
```

`Ecto.Adapters.SQL.Sandbox.Connection` says it follows the `DBConnection` behaviour:

```
  defmodule Connection do
    @moduledoc false
    @behaviour DBConnection

    def connect({conn_mod, state}) do
      case conn_mod.init(state) do
        {:ok, state} -> {:ok, {conn_mod, state, false}}
        {:error, _} = err -> err
      end
    end
```

But, the `@callback` for `connect/2` expects a `Keyword.t`:

```
  @callback connect(opts :: Keyword.t) ::
    {:ok, state :: any} | {:error, Exception.t}
```

### Expected behavior

`Ecto.Adapters.SQL.Sandbox.Connection.connection/2` needs to be changed to take a Keyword list to match the behaviour, but since Sandboxes work now, this means that the caller of `Ecto.Adapters.SQL.Sandbox.Connection.connection` needs to be updated to pass a `Keyword.t`.

Since I haven't figured out where that caller is, I'm opening this bug.

**Comment by fishcakez** [comment]
There isn't a caller, the function is never called.

**Comment by KronicDeth** [comment]
@fishcakez if it's never called, why does it have a body and a pattern?  Or do you mean I won't be able to find the caller in the Ecto source + deps and I'd need to find the caller in tests using the Sandbox?

**Comment by fishcakez** [comment]
@KronicDeth the code used to be called but isn't anymore. Likely a few other callbacks are no longer used too. I think only `handle_*` callbacks (except `handle_info`) would be called but this is an implementation detail of the `DBConnection.Ownership` pool. I think we can just change `connect/1` to raise like the `Sandbox.Pool` functions.

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-ecto/ecto/commit/2d41c5b5c0597def6cee0ade6eb39f922d5663fe
