### ISSUE TITLE
create table posts_customs is using the wrong FK reference

### ISSUE THREAD

**Issue by fire** [elixir-ecto/ecto#1699]
### Environment

* Elixir version (elixir -v): Elixir 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): SnappyData 1.6-snapshot
* Ecto version (mix deps): Problem exists in master.
* Database adapter and version (mix deps): custom build
* Operating system: centos 7

### Current behavior

Errors on statement because database doesn't support FK on non PK columns.

```sql
CREATE TABLE APP.POSTS (
	"id" BIGINT NOT NULL,
	"uuid" VARCHAR(36),
	PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX POSTS_UUID_INDEX ON APP.POSTS ("uuid");

CREATE TABLE APP.POSTS_CUSTOMS(
			"post_id" VARCHAR(36) CONSTRAINT "POSTS_CUSTOMS_post_id_fkey" REFERENCES APP.posts("uuid")
)

-- SQL Error [X0Y44]: SQLSTATE=X0Y44,SEVERITY=-1: (Server=snappydata.192.168.55.4.nip.io[1528],Thread[DRDAConnThread_32,5,gemfirexd.daemons]) Constraint 'POSTS_CUSTOMS_post_id_fkey' is invalid: there is no unique or primary key constraint on table '"APP"."POSTS"' that matches the number and types of the columns in the foreign key.
```

### Expected behavior

https://github.com/elixir-ecto/ecto/blob/599d4a666ccbb7af48988349611938b6ff1606ab/integration_test/support/migration.exs#L65

```elixir
create table(:posts_customs, primary_key: false) do
  add :post_id, references(:posts, column: :uuid, type: :uuid)
  add :custom_id, references(:customs, column: :bid, type: :binary_id)
end
```

becomes

```elixir
create table(:posts_customs, primary_key: false) do
  add :post_id, references(:posts, column: :id, type: :id)
  add :custom_id, references(:customs, column: :bid, type: :binary_id)
end
```

UUID is not the PK of the posts table, ID is.

```elixir
create table(:posts) do
      add :title, :string, size: 100
      add :counter, :integer
      add :text, :binary
      add :bid, :binary_id
      add :uuid, :uuid
      add :meta, :map
      add :links, {:map, :string}
      add :public, :boolean
      add :cost, :decimal, precision: 2, scale: 1
      add :visits, :integer
      add :intensity, :float
      add :author_id, :integer
      add :posted, :date
      timestamps null: true
    end
```

**Comment by josevalim** [comment]
Thank you, however I am thinking I am missing something. A foreign doesn't
need to point to the primary key, it can point to any column. Which
database are you using? I am afraid we are using UUID on purpose but I
would need to double check.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fire** [comment]
I've been trying to write an adapter for [SnappyData](https://github.com/SnappyDataInc/snappydata) for the last few months.

This database has a limitation that its Foreign Keys must match the Primary Key in the other table as it's   is scalable across multiple machines. I believe other databases allow you to match the FK on the candidate key. 

In this case I think the test has a logic error. post_id is referring to entire row in posts.  post_customs looks like some sort of many to many relationship. UUID is just an attribute and does not uniquely identify the row.

I'm on irc in #elixir-lang as iFire if you want to chat.

**Comment by josevalim** [comment]
@fire ok, thank you! I will apply your changes tomorrow, I just need to investigate if we need to port some test over because of the change. :)
