### ISSUE TITLE
ecto 2 and gettext 0.10

### ISSUE THREAD

**Issue by building39** [elixir-ecto/ecto#1703]
Elixir 1.4.0 with OTP 19
Ecto 2.0.5

Looks like there's an issue with gettext >= 0.10.0. When I run my tests, a couple of them fail:

warning: function test_coverage/1 is unused
  mix.exs:30

....

  1) test does not create resource and renders errors when data is invalid (Leadspoc.LeadControllerTest)
     test/controllers/lead_controller_test.exs:44
     ** (FunctionClauseError) no function clause matching in Gettext.dngettext/6
     stacktrace:
       (gettext) lib/gettext.ex:524: Gettext.dngettext(Leadspoc.Gettext, "errors", "can't be blank", "can't be blank", nil, %{})
       (ecto) lib/ecto/changeset.ex:1938: anonymous fn/3 in Ecto.Changeset.merge_error_keys/2
       (elixir) lib/enum.ex:1674: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/changeset.ex:1932: Ecto.Changeset.traverse_errors/2
       (leadspoc) web/views/changeset_view.ex:17: Leadspoc.ChangesetView.render/2
       (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
       (leadspoc) web/controllers/lead_controller.ex:1: Leadspoc.LeadController.action/2
       (leadspoc) web/controllers/lead_controller.ex:1: Leadspoc.LeadController.phoenix_controller_pipeline/2
       (leadspoc) lib/leadspoc/endpoint.ex:1: Leadspoc.Endpoint.instrument/4
       (leadspoc) lib/phoenix/router.ex:261: Leadspoc.Router.dispatch/2
       (leadspoc) web/router.ex:1: Leadspoc.Router.do_call/2
       (leadspoc) lib/plug/error_handler.ex:64: Leadspoc.Router.call/2
       (leadspoc) lib/leadspoc/endpoint.ex:1: Leadspoc.Endpoint.phoenix_pipeline/1
       (leadspoc) lib/leadspoc/endpoint.ex:1: Leadspoc.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/lead_controller_test.exs:45: (test)

...

These tests pass when gettext is 0.9.0

**Comment by josevalim** [comment]
Can you please paste the code in your web/views/changeset_view and in your errors_helpers? I believe they are out of date. In particular, if you look at the first line in the stackrace:

    Gettext.dngettext(Leadspoc.Gettext, "errors", "can't be blank", "can't be blank", nil, %{})

You can see the `nil` argument and we expect a number to be given there. It should be something like this: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/web/views/error_helpers.ex#L20-L38

**Comment by building39** [comment]
Yep. My bad. I should have regenerated the application. Closing.
