### ISSUE TITLE
Introduce Ecto.Repo.cast or Ecto.Repo.cast_query

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1705]
The goal of this function is to explicit cast its parameters before running a query. This would help solve #1704 and it is a feature asked by @chrismccord. The issue however is that it would only work with queries and therefore wouldn't work for functions such as `get/3` or `get_by/3`.

**Comment by chrismccord** [comment]
@josevalim but it would allow this, right?:

```elixir
with {:ok, %{id: id} <- Repo.cast(Post, post_params),
     {:ok, post} <- Repo.get(Post, id) do
...
end
```

**Comment by josevalim** [comment]
@chrismccord no because we have no idea how parameters are used in that example. I guess we may allow it but it definitely looks suspicious.

**Comment by chrismccord** [comment]
Can you show a couple example of how these new functions would be used?

**Comment by josevalim** [comment]
```elixir
query = from p in Post, where: [id: ^id]
case Repo.cast(query) do
  {:ok, _} ->
  {:error, _} ->
end
```

so it expects a query with parameters.

**Comment by chrismccord** [comment]
Ah I see. It makes sense that we couldn't know how to cast params outside the context of a query. It would be nice to come up with a more succinct api for get/get_by, but It sounds like this is as good as it can get, so 👍 from me.

**Comment by michalmuskala** [comment]
I never was a fan of `get_by`, especially now that we have the simplified form of `where` with a keyword. This means we could replace `Repo.get_by(Post, fields)` by `Post |> where(^fields) |> Repo.cast`

**Comment by josevalim** [comment]
Right, so maybe that's the course of action for those wanting to rely on cast? Because both get and get_by are still very convenient to express many queries. It is much more readable than the alternative you posted, no?

**Comment by eniolopes** [comment]
What is the value returned by `cast` used for? According #1704 seems like the use case is to check if the params provided to the query are "castable". If this is the case, I'd rather call the function something like `Repo.can_cast_query?` or maybe move it to the query module? `Query.can_cast?` or `Query.castable?`.

I'd love to work on this when things are sorted out.

**Comment by chrismccord** [comment]
The goal, for me in a web context, is to be able to write something like this:

```elixir
def get_post(id) do
  with {:ok, query} <- cast(from p in Post, where: [id: ^id])
       %Post{} = post <- Repo.one(query) do

    post
  else
    {:error, :badcast, fields} -> {:error, :badcast, fields}
    nil -> {:error, :not_found}
  end
end
```

My app would the have a layer that knows how to translate common domain types to responses, so `{:error, :not_found}` will 404, and `{:error, :badcast, fields}` will 400, with a relevant error message. This is why I am 👎 on `can_cast?` because I may want access to what failed to cast.

**Comment by eniolopes** [comment]
makes sense, then `cast_query` seems like the best name option here.

**Comment by noma4i** [comment]
Purpose of Ecto is to help other then to add hassle but with variety of functions.

Cast implementation in my opinion  should not add another helper we already have. My point is to incorporate casting in Ecto to skip tons of boilerplate. Common use is to pass for example not valid input and have errors as pattern matchable response, not an error raised. 

I see such feature as a part of Ecto to return `{:error, :badcast, fields}` by default with no code written. No hidden magic. Just expected things to happen. User supplied wrong input - return it to use in `case/cond`. It should happen internally as people not writing anything in addition to have `{:ok, record}` to return from query.

Expected code after Ecto will be able to offer internal cast handling.

```
query = from p in Post, where: [id: ^id]
case Repo.one(query) do
  {:ok, record} -> ....
  {:error, :badcast, fields} -> ... fields could be another tuple for patternmatching happiness
  nil -> ...
end
```
 
Im validating input before passing it to query builder as workaround and can't see any outcome from moving to `cast_query` as another solution while I will need to write another block of `with` ladder to handle that.

**Comment by michalmuskala** [comment]
That would be ideal - the problem is that such implementation of `Repo.one/1` is not backwards compatible and will introduce a lot of issues with migration. A less invasive approach is required. One such approach is adding the `cast/1` or `cast_query/1` function - you're free to define some more complex, boilerplate removing functions in your repo that would use it. Repo is just a module - you are free to define functions on it. For example:

```elixir
def fetch_one(query) do
  case cast(query) do
    {:ok, query} ->
      case one(query) do
        nil    -> {:error, :not_found}
        record -> {:ok, record}
      end
    {:error, fields} ->
      {:error, {:badcast, fields}}
  end
end
```
You could define `fetch_all/1` in a similar fashion.

In any way, adding the `cast` function is a first step.

**Comment by noma4i** [comment]
Bump this issue! Cast was done https://github.com/elixir-ecto/ecto/pull/1719

**Comment by josevalim** [comment]
We are closing this as we do not plan to add those features to Ecto for now.

**Comment by josevalim** [comment]
If you need to validate the incoming data. Use (schemaless) changesets.
