### ISSUE TITLE
Chaining: Repo.preload should accept nil

### ISSUE THREAD

**Issue by jfrolich** [elixir-ecto/ecto#1709]
### Current behavior
Chaining `Repo.get` to `Repo.preload` allows us to easily preload fields from our Repo.get, for instance
```elixir
iex> Repo.get(User, 1)
...> |> Repo.preload(:organization)
%User{...}
```
However when we `get` an unexisting user it blows up:
```elixir
iex> Repo.get(User, 100)
...> |> Repo.preload(:organization)
** (FunctionClauseError) no function clause matching in Ecto.Repo.Preloader.preload/4
    (ecto) lib/ecto/repo/preloader.ex:36: Ecto.Repo.Preloader.preload(nil, Cogo.Repo, :organization, [])
```

### Expected behavior
Of course it makes sense that it blows up, the input for preload is `nil`. However, this requires an extra case statement when we use `Repo.get` with preloads. This in turn makes our code less readable. I think it makes sense to just return `nil` when the first argument to Repo.preload is `nil`.

The result of this would be:
```elixir
iex> Repo.get(User, 100)
...> |> Repo.preload(:organization)
nil
```

I know there is an alternative `from` syntax where we can include the preloads as part of the query. However there are reasons preload after the fact.

**Comment by jfrolich** [comment]
#1710

**Comment by josevalim** [comment]
Closing in favor of the PR then. :)
