### ISSUE TITLE
Allow embedded_schema with :id, autogenerated: false primary_key

### ISSUE THREAD

**Issue by pma** [elixir-ecto/ecto#1712]
Currently it's possible to set `@primary_key {:id, :id, autogenerate: false}` before `embedded_schema` to have non-autogenerated integer keys in nested structs.

However, when saving the struct, we get an error raised due to not having the embedded_schema primary key be a binary_id with autogenerate: true (https://github.com/elixir-ecto/ecto/blob/fb397116e25733d27b64e75df9ccef1e603121e0/lib/ecto/embedded.ex#L131).

As long as we set autogenerate: false, we shouldn't be restrictedto using `:binary_id` for the primary key.

This commit (https://github.com/pma/ecto/commit/9e8ae8c69082b93c28a52355f91c2b06237d21c0) attempts to implement the suggested behaviour.

We may also change this further to allow using a custom ecto type for the primary key as long as it  implements `autogenerate/0`; and use the adapter generate_id implementation only for the primitive type `binary_id`.  

Edit: Issue created based on the discussion here: https://groups.google.com/forum/#!topic/elixir-ecto/3YqQ2KHkiW4

**Comment by jclem** [comment]
I'm not sure if it makes a difference, but my original case in the discussion was actually around autogenerated primary keys using a custom field type, e.g.

```elixir
@primary_key {:id, Base62UUIDField, autogenerate: true}
```

**Comment by josevalim** [comment]
@pma @jclem but your cases should be fixed and tested in master, please let me know how it goes! :heart:
