### ISSUE TITLE
Allow embedded schemas to use custom field types for primary key

### ISSUE THREAD

**Issue by jclem** [elixir-ecto/ecto#1713]
From [this discussion thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-ecto/3YqQ2KHkiW4/x5KxbD9BBwAJ): Currently, Ecto complains when using a custom field type as a primary key for an embedded schema:

```elixir
@primary_key {:id, Base62UUIDField, autogenerate: true}
```

When doing this, Ecto complains [here](https://github.com/elixir-ecto/ecto/blob/fb397116e25733d27b64e75df9ccef1e603121e0/lib/ecto/embedded.ex#L133). cc @michalmuskala 

https://github.com/elixir-ecto/ecto/issues/1712 is similar, I think, and also sprang from the above discussion.

**Comment by josevalim** [comment]
Yup, same as #1712, so that one is enough for now. Thank you! :D
