### ISSUE TITLE
Rows is dropped when preload is declared explicitly on source.

### ISSUE THREAD

**Issue by Crashtown** [elixir-ecto/ecto#1734]
### Environment

* Elixir version: 1.3.2
* Database and version: Postgres 9.5.0
* Ecto version (mix deps): 2.1.0-rc.1 and 2.0.5
* Database adapter and version (mix deps): postgrex 0.12.0
* Operating system: macOS 10.12

### Current behavior

When I perform queries A -(join)-> B -(left join)-> C I expect that database will return rows in format of (A,B,C) some of (A,B) will be the same, but (C) will be different, for example:
(A1,B1,C1)
(A1,B1,C2)
(A1,B1,C3)

If I want to select A with preloaded B and select C I expect to get (A,B,[C]) or at least row per every unique C. if I specify this preload through atom, then everything is ok, ecto returns unique row per every C with added (A,B). But if I specify preload in form of keyword list like `preload: [cs: с]` in this situation some of C will be lost, ecto will try to merge rows returned from database in module `Ecto.Repo.Assoc` and during computations some of C's will be lost.

This is test which illustrates problem:

```Elixir
  test "explicit preload statements" do
    user = TestRepo.insert!(%User{name: "1"})
    post = TestRepo.insert!(%Post{title: "1", author: user})
    user2 = TestRepo.insert!(%User{name: "2"})
    post2 = TestRepo.insert!(%Post{title: "2", author: user2})
    post3 = TestRepo.insert!(%Post{title: "3", author: user2})
    comment = TestRepo.insert!(%Comment{post: post, author: user2})
    q1 =
      from u in User, where: u.id == ^user.id,
      join: p in assoc(u, :posts),
      left_join: c in Comment, on: c.post_id == p.id,
      join: u1 in User, where: u1.id == c.author_id,
      left_join: p1 in Post, on: u1.id == p1.author_id,
      preload: [:posts],  # preload set as atom
      select: {u, p1}
    assert length(TestRepo.all(q1)) == 2 # will pass
    q2 =
      from u in User, where: u.id == ^user.id,
      join: p in assoc(u, :posts),
      left_join: c in Comment, on: c.post_id == p.id,
      join: u1 in User, where: u1.id == c.author_id,
      left_join: p1 in Post, on: u1.id == p1.author_id,
      preload: [posts: p],  # preload set as keyword list
      select: {u, p1}
    assert length(TestRepo.all(q2)) == 2 # will fail
  end
```

### Expected behavior

Expected behavior would be merge of posts to the list, or at least return it in plain format like in q1.

**Comment by shhavel** [comment]
Here is one more example of two similar queries from provided data:

```elixir
q1 =
  from u in User, where: u.id == ^user2.id,
  left_join: p in assoc(u, :posts)

q2 =
  from u in User, where: u.id == ^user2.id,
  left_join: p in assoc(u, :posts),
  preload: [posts: p]
```

Which produce the following SQL (correspondingly)


```SQL
SELECT u0."id", u0."name"
FROM "users" AS u0
LEFT OUTER JOIN "posts" AS p1 ON p1."author_id" = u0."id"
WHERE u0."id" = 2;


SELECT u0."id", u0."name", p1."id", p1."title", p1."text", p1."author_id"
FROM "users" AS u0
LEFT OUTER JOIN "posts" AS p1 ON p1."author_id" = u0."id"
WHERE u0."id" = 2;
```

SQL conditions are identical.

But results return different amount of records.

```elixir
Repo.all(q1) # 2 rows for the same user

Repo.all(q2) # 1 row of one user with 2 posts
```


When preload works in the same query with original query it ads additional JOIN (if it doesn't already exist).
Then it assumes that this JOIN produces additional results when SQL query is executed
which should be combined and while associations data should be extracted from them.

Sometimes additional rows are exists regardless from adding additional JOIN for preloaded associated data.

And it is very unclear how to distinguish whether or not some rows should be combined.

So I think this is probably almost impossible to fix.



@Crashtown

A little bit out of topic.
There is a typo in building SQL which leads to:

```SQL
SELECT u0."id", u0."name", p4."id", p4."title", p4."author_id"
FROM "users" AS u0
INNER JOIN "posts" AS p1 ON p1."author_id" = u0."id"
LEFT OUTER JOIN "comments" AS c2 ON c2."post_id" = p1."id"
INNER JOIN "users" AS u3 ON TRUE
LEFT OUTER JOIN "posts" AS p4 ON u3."id" = p4."author_id"
WHERE (u0."id" = 1) AND (u3."id" = c2."author_id");
```

NOTE: `INNER JOIN "users" AS u3 ON TRUE`

In code should be `join: u1 in User, on: u1.id == c.author_id` 
instead of `join: u1 in User, where: u1.id == c.author_id`

**Comment by Crashtown** [comment]
Thank you for guidance, @shhavel. You are right, this is typo :) I've spent some time analyzing sources responsible for output formatting but not understood how to solve this problem. At first sight bug sit in the `Ecto.Repo.Assoc`, it just not treats well left joined stuff, looks like accumulator structure is not deep enough to correctly merge data from rows. But before I'll try to fix it I need advice from maintaining team on subject of is my assumptions correct. :)

**Comment by josevalim** [comment]
Yes, @shhavel is correct. One way to look at it is that `[preload: [posts: p]]` is doing a group by. So it is going to group all users with that shared post. If you have different entries because of `p`, you will only see the first one.

Thank you @shhavel !

**Comment by Crashtown** [comment]
@josevalim, I understand that distinguish which records should be combined is can be difficult, but right now data is just lost after combinations, maybe correct strategy there would be not guess and return raw data? It was very confusing when I faced with this problem. Both queries semantically the same (for me) and return same output from database, but results is different. If it goes this way by design, then maybe I can help with documenting this behavour? :)

**Comment by josevalim** [comment]
@Crashtown documenting the behaviour would be welcome. :)

My point though is that they are *not* semantically equivalent. Sure, they emit the same SQL, but the point of preload is exactly to merge the data together. If you don't want the data to be merged, then don't use preload but instead `select: {u, p, p1}`.

**Comment by Crashtown** [comment]
@josevalim okay, thank you very much for explanation, I'll work on improving docs for `preload` function, hope it will prevent another folks struggles :)

**Comment by eshubin** [comment]
Is there any change related to that issue? That is super error-prone.
