### ISSUE TITLE
assoc doesn't respect @schema_prefix on through-associations

### ISSUE THREAD

**Issue by thorsten-de** [elixir-ecto/ecto#1746]
While **preloading** "through-associations" on a prefixed schema works fine, requesting them with **assoc** doesn't respect the @schema_prefix.

### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MariaDB 
* Ecto version (mix deps): 2.0.5
* Database adapter and version (mix deps): mariaex 0.7.8
* Operating system: arch linux

### Current behavior
```elixir
defmodule Hotel do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_hotels" do
    has_many :room_categories, Hotel.RoomCategory
    has_many :rooms, through: [:room_categories, :rooms]
  end
end

defmodule Hotel.RoomCategory do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_room_categories" do
    belongs_to :hotel, Hotel
    has_many :rooms, Hotel.Room
  end
end

defmodule Hotel.Room do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_rooms" do
    belongs_to :room_category, Hotel.RoomCategory
    has_one :hotel, through: [:room_category, :hotel]
  end
end

h = Repo.get Hotel, 1
Repo.preload(h, :rooms) # works fine, respects @schema_prefix
# [debug] QUERY OK source="hotel_room_categories" db=0.5ms SELECT h0.`id`, h0.`hotel_id`, h0.`hotel_id` FROM `br_dev`.`hotel_room_categories` AS h0 WHERE (h0.`hotel_id` = ?) ORDER BY h0.`hotel_id` [1]
# [debug] QUERY OK source="hotel_rooms" db=0.5ms decode=0.1ms SELECT h0.`id`, h0.`room_category_id`, h0.`room_category_id` FROM `br_dev`.`hotel_rooms` AS h0 WHERE (h0.`room_category_id` IN (?,?,?,?,?,?,?,?)) ORDER BY h0.`room_category_id` [4, 5, 6, 163, 164, 165, 166, 167]

Repo.all Ecto.assoc(h, :rooms) # fails for ignoring @schema_prefix on through-association
# [debug] QUERY ERROR source="hotel_rooms" db=0.1ms SELECT DISTINCT h0.`id`, h0.`room_category_id` FROM `hotel_rooms` AS h0 INNER JOIN `hotel_room_categories` AS h1 ON h1.`hotel_id` = ? WHERE (h0.`room_category_id` = h1.`id`) [1]
# ** (Mariaex.Error) (1146): Table 'br.hotel_rooms' doesn't exist

Repo.all Ecto.assoc(h, :room_categories) # but direct associations work fine with @schema_prefix
# [debug] QUERY OK source="hotel_room_categories" db=0.5ms SELECT h0.`id`, h0.`hotel_id` FROM `br_dev`.`hotel_room_categories` AS h0 WHERE (h0.`hotel_id` = ?) [1]

```
### Expected behavior
`Repo.all Ecto.assoc(h, :rooms)` should respect the "br_dev" schema_prefix.

**Comment by josevalim** [comment]
That's a known limitation. Schema prefixes are not propagated through queries. So if you have a join or an assoc that is on a different prefix, they will still always run on the query prefix itself. I will improve the docs to make sure this limitation is clear, thank you.

**Comment by thorsten-de** [comment]
Thx for your immediate reply.

> So if you have a join or an assoc that is on _a different prefix_, they will still always run on the query prefix itself. 

In the stated example, all schemas have the _same_ prefix. So I don't understand why the query prefix is not used at all.

**Comment by josevalim** [comment]
Good point. Can you try this for now:

    Repo.all Ecto.assoc(Ecto.put_meta(h, prefix: "br_dev"), :rooms)

I am wondering if it is respecting the record prefix or if it is just a bug. Also, can you please check if the bug exists or not on master?

Thank you!

**Comment by josevalim** [comment]
Actually, nevermind. I have checked and it won't work on master. This is definitely a bug.

**Comment by thorsten-de** [comment]
I'll use preloading anyway, but I was a bit surprised to see preloding working fine but assoc not.

Taking a closer look at the queries, they are quite different. `assoc` builds inner joins, just as I do when writing the query manually - I really like that. Preloading doesn't use a join, but issues individual querys to build all the data while walking "through" the association, I guess. 

So perhaps it's fine when preloading associacions shows a different behavior than assoc, because I'd use assoc to build very explicit queries under special circumstances.
