### ISSUE TITLE
Additional options for all Ecto.Changeset validation errors

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#1751]
Hi guys,

[We](https://github.com/Nebo15/) love to provide our users very descriptive validation errors on Front-End of our projects, so our error structure [is complex](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors):
```
{
  "error": {
    "type": "validation_failed",
    "invalid": [
      {
        "entry_type": "json_data_proprty",
        "entry": "#/product_type",
        "rules": [
          {
            "rule": "string",
            "params": []
          },
          {
            "rule": "min:2",
            "params": [{"min": 2}]
          }
        ]
      }
    ],
    "message": "Validation failed. Return human-readable error message. You find all possible validation rules at https://docs.qbill.ly/#request-validators."
  }
}
```

And `Ecto.Changeset` doesn't provide sufficient data for such response structure, and setting `[message:..]` option for each changeset in each project is will mess everything (for example, you can forget to set it, and it's hard to refactor messages across all projects).

Our core idea is to provide PR that will add additional data to options (validation function and all validation options), that will be accessible in `traverse_errors/1` function and it should not break backwards compatibility.

Is it ok to work on this PR (would you like to see it?) or we should look for another way to solve our issue?

**Comment by josevalim** [comment]
@AndrewDryga the messages in Ecto already are stored in the format `{"message", []}`. So if you are calling add_error manually on your own validations, they already support passing [options](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset.ex#L1191), which are passed to [traverse_errors](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset.ex#L2073). So it seems what you want is already supported?

**Comment by AndrewDryga** [comment]
Nope, message itself is looks not descriptive enough in **native** validators (we almost don't write our own).

But I noticed `changeset.validations` list, I will take a look into it and come back later :).

**Comment by josevalim** [comment]
Oh, if you want to provide information about all validations and not only the errors, then the validations list will keep information about all validations and which parameters you have passed to them.

**Comment by AndrewDryga** [comment]
I need this information only for failed validations, I'm not sure yet is it possible to match errors and validations. Because errors return text (and it's a little bit strange to me, because look like they they intersect for different validators).

**Comment by josevalim** [comment]
@AndrewDryga your example seems to say otherwise? There are at least two validations (rules) being shown there: that the type is a string and that it has a minimum of 2 chars?

**Comment by AndrewDryga** [comment]
That oversimplified example, I'm trying to make sure all possible validations can be turned in struct like that one. I guest I can we can create our own implementation or `traverse_errors` and collect all necessary information from `changeset.required` and  `changeset.validations`. Ill try and report  with code samples if it's not feasible.

**Comment by AndrewDryga** [comment]
Ok, it looks like I have a solution, but it's ugly:
1. Collect all possible messages (eg. `has invalid format`, `can't be blank`) and match them to atoms (eg. `:format`)
2. For each error in changeset get `changeset.validations`, find rules by this atom (eg.: `{:format, ~r/@/}]`).
3. Construct error message.

But It would be so much easier if It would be possible to get same structure as `changeset.validations` has only for failed rules. Maybe you can suggest something?

**Comment by josevalim** [comment]
@AndrewDryga the only suggestion I have in mind is to store a key in the error messages that say which validation triggered it, for example, `type: :format`.

**Comment by AndrewDryga** [comment]
@josevalim maybe I can create a PR where all validators is adding their name to opts?
```
def validate_required(%{required: required, errors: errors} = changeset, fields, opts \\ []) do
    message = message(opts ++ [rule: :required], "can't be blank")
    fields  = List.wrap(fields)

    new_errors =
      for field <- fields,
          ensure_field_exists!(changeset, field),
          missing?(changeset, field),
          is_nil(errors[field]),
          do: {field, {message, []}}

    case new_errors do
      [] -> %{changeset | required: fields ++ required}
      _  -> %{changeset | required: fields ++ required, errors: new_errors ++ errors, valid?: false}
    end
  end
```
(change in 2nd line: `opts ++ [rule: :required]`)

So everybody would have a way to construct error responses by constant keys, instead of matching/replacing text?

**Comment by josevalim** [comment]
@AndrewDryga sounds good to me. It should look like this though:

    message = message([validation: :required] ++ opts, "can't be blank")

We should prepend, as it is faster, and use `:validation`. We will also need to change the traverse_errors example to not attempt to interpolate the `:validation` key. We should [delete it before traversing](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset.ex#L2073).

**Comment by AndrewDryga** [comment]
Ok, Ill work on it. Thanks :)

**Comment by AndrewDryga** [comment]
@josevalim BTW, why you want to delete it before interpolation? 

I guest it won't conflict with existing implementations, because `String.replace` won't throw any errors if you will try to replace variable that does not exist in pattern, and we can be pretty sure that nobody uses `"%{validation}"` in their `traverse_errors/1` because there was no such key for interpolation.

**Comment by josevalim** [comment]
Oh, it is just an atom, so it is fine. No need to delete it. Sorry about that.
