### ISSUE TITLE
Bug? Date comparison seems to fail

### ISSUE THREAD

**Issue by StephanMeijer** [elixir-ecto/ecto#1754]
```
iex(37)> Ecto.Date.cast!("2015-06-11") <= Ecto.Date.cast!("2016-06-12")
true
iex(38)> Ecto.Date.cast!("2015-06-11") <= Ecto.Date.cast!("2016-06-10")
false
```

`11 <= 10` is false
`12 <= 11` is true

```
iex(40)> Ecto.Date.cast!("2015-06-11") <= Ecto.Date.cast!("2016-06-11")
true
```

`2015 <= 2016` is true

Comparison of date seems to be bugged.

Versions:

```
bash $ iex --version
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

IEx 1.3.2
```

```
bash $ elixir --version
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.3.2
```

Dependencies:
- `ecto 2.0.2`
- `phoenix_ecto 3.0.1`

**Comment by sevenseacat** [comment]
What are the return values of the casts?

**Comment by StephanMeijer** [comment]
```
iex(2)> Ecto.Date.cast!("2015-06-11")
#Ecto.Date<2015-06-11>
iex(3)> Ecto.Date.cast!("2016-06-12")
#Ecto.Date<2016-06-12>
iex(4)> Ecto.Date.cast!("2016-06-10")
#Ecto.Date<2016-06-10>
iex(6)> Ecto.Date.cast!("2016-06-11")
#Ecto.Date<2016-06-11>
```

`Ecto.Date.compare/2` seems to behave properly.

**Comment by shhavel** [comment]
`Ecto.Date.cast!/1` returns Ecto.Date struct.  
Structs can also be compared with `<=`.
 which return the same results for provided examples.

```elicir
iex> %{year: 2015, month: 6, day: 11} <= %{year: 2016, month: 6, day: 10}
false
```
 
There is no feature to compare `Ecto.Date` with `<=`  same as `Ecto.Date.compare/2`.
So I think this is not a bug.

**Comment by josevalim** [comment]
@shhavel correct, <= and > and friends perfect structural comparison, not semantical one. So the `compare/2` function is the way to go.
