### ISSUE TITLE
Option read_after_writes is not supported by belongs_to

### ISSUE THREAD

**Issue by denispeplin** [elixir-ecto/ecto#1762]
### Environment

* Elixir version (elixir -v): 1.3.2
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): 2.0.5
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: Ubuntu 13.10

### Current behavior

```elixir
  schema "messages" do
    field :path, :string, null: false, read_after_writes: true
    belongs_to :guest, App.Guest, read_after_writes: true

    timestamps()
  end
```

```
$ mix test
Compiling 2 files (.ex)

== Compilation error on file lib/app/message.ex ==
** (ArgumentError) invalid option :read_after_writes for belongs_to/3
    lib/ecto/schema.ex:1461: Ecto.Schema.check_options!/3
    lib/ecto/schema.ex:1272: Ecto.Schema.__belongs_to__/4
    lib/app/message.ex:11: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```
### Expected behavior

I found in [documentation[(https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3), that `read_after_writes` should be supported by `belongs_to`: "All other options are forwarded to the underlying foreign key definition and therefore accept the same options as field/3."

I would prefer to have this option supported, but in a worst case the documentation should be corrected if the option is not supported.

**Comment by josevalim** [comment]
That's by design because we would only reload the field and not its association. If you really want to, you can define the field explicitly, `field :foo_id, :integer, read_after_writes: true` and then pass `define_field: false` to the belongs to.

**Comment by denispeplin** [comment]
Thank you, I tried to define separate field before, but I didn't get that I should use `define_field: false`, so this didn't work. Now it works!

But I still think that documentation is incorrect, because it says that "**All** other options are forwarded ... therefore **accept the same options** as field/3", and it is definitely is not true.

**Comment by michalmuskala** [comment]
A PR updating the docs to inform about this limitation and the solution of using a separate field is definitely welcome!
