### ISSUE TITLE
`cast_embed` uses schema types, not a changeset types

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#1763]
Hello,

There are method [`Ecto.Relation.do_cast/4`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset/relation.ex#L92) that uses `__schema__` metadata, but I think it would be a good idea to extract type data from `changeset.types`. 

Thus we will make it possible to hack type system and, if developer want, replace type in `changeset/2` functions. It it suitable when there are many different embeds in a same schema structure. (It would require many copy-paste schemas.)

I have real world example: 
1. Different peer-to-peer transfer peers is defined as custom type: https://github.com/Nebo15/tokenizer.api/blob/master/lib/repo/schemas/peer.ex#L13
2. Type itself can resolve what kind of data in it and cast/dump it to map: https://github.com/Nebo15/tokenizer.api/blob/master/lib/repo/types/peer_credential.ex#L10
3. Custom cast for this types: https://github.com/Nebo15/tokenizer.api/blob/master/lib/repo/changeset/dynamic_embed.ex#L42

Right now only issue left is that when saving to DB this data doesn't get dumped from Changeset struct to map (`changeset.changes.credential` stores changeset that is ignored by Ecto, because its defined as embed type only in changeset.)

```
"encode map"
%{credential: #Ecto.Changeset<action: nil,
   changes: %{number: "5473959513413611"}, errors: [],
   data: #Tokenizer.DB.Models.CardNumber<>, valid?: true>,
  email: "ivan@example.com", phone: "+380631112233"}
23:17:02.283 [error] #PID<0.466.0> running Tokenizer.HTTP.Endpoint terminated
Server: localhost:4001 (http)
Request: POST /payments
** (exit) an exception was raised:
    ** (Poison.EncodeError) unable to encode value: {:number, :credit_card}
...
```

**Comment by josevalim** [comment]
Yes, we should always use the types information if one is available. A PR is welcome.

**Comment by AndrewDryga** [comment]
Ok, I'll look into it in few days :).

*For people that found this issue in Google*: There are easy way how to deal with this issue, you simply need to call `Ecto.Changeset.apply_changes/1` before saving data to database, and all castings will be done with extraction of this data from `changeset.types`.

**Comment by josevalim** [comment]
Ping? :)

**Comment by AndrewDryga** [comment]
Pong :).

Right now I'm working on adapter, will try to allocate some time on this issue on next week (but I did not forgot about it).

**Comment by AndrewDryga** [comment]
@josevalim I need your help.

I've investigated code structure and it looks like that are places that don't have access to changeset, eg: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/changeset/relation.ex#L299.

I may add changeset as 6-th optional argument and use `changeset.types` when they are present, but It will add side effects to `Ecto.Relaction.cast` behaviour, since schema structure will extracted from two different places.

Maybe thats not the best idea to implement it in v2.1.

**Comment by josevalim** [comment]
Sure. Let's postpone it and wait until 2.1 is out.

**Comment by narrowtux** [comment]
I can't see the examples you posted but if I understand this correctly, you want to be able to dynamically decide the type of an association?

I am half-way of hacking this into my project, using `cast_embed`'s `:with` option which basically lets me pass a custom changeset function. This alone is wonderful for validating an opts field which depends on a different type field with multiple `embedded_schema` definitions.

However, this won't allow me to define the schema that would be used when loading the struct from the database. It would be great if `embeds_one` and `embeds_many` could also offer a `:with` option to pass a function that decides which schema to use depending on other fields in the struct.

**Comment by narrowtux** [comment]
As a workaround, I will use a schema that has all the possible fields from the other schemata so it can load the options correctly, it's not ideal though.

**Comment by auxbuss** [comment]
@AndrewDryga, could you update the links in your original post, please.

**Comment by AndrewDryga** [comment]
@auxbuss done, thanks for noticing it.
