### ISSUE TITLE
Crashing Ecto/Postgrex

### ISSUE THREAD

**Issue by walkr** [elixir-ecto/ecto#1768]
I'm working on an Elixir application and I've managed to create a scenario that causes Ecto to crash.

It seems like this causes Ecto to crash with three different types of errors. 

I've created a similarish app to reproduce the scenario. See [`ecto-crash`](https://github.com/walkr/ecto-crash)

To reproduce please run the following commands:

```shell
$ git clone https://github.com/walkr/ecto-crash
$ cd ecto-crash
$ mix deps.get
$ make crash  # See Makefile for details
```

**NOTE**: Run `make crash` repeatedly and you will get different errors. See bellow under **Current Behavior**

Here's my database config:

```elixir
config :ecto_crash, EctoCrash.Repo,
  adapter: Ecto.Adapters.Postgres,
  extensions: [],
  username: "postgres",
  password: "postgres",
  database: "ecto_crash",
  hostname: "localhost",
  pool_size: 16,
  pool_timeout: 10_000,
  timeout: 10_000

config :ecto_crash, ecto_repos: [EctoCrash.Repo]
```

### Environment

* Elixir version (elixir -v):

    Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false [dtrace]

    Elixir 1.3.4

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
    
    postgres (PostgreSQL) 9.5.4

* Ecto version (mix deps):

    * connection 1.0.4 (Hex package) (mix)
    * poolboy 1.5.1 (Hex package) (rebar)
    * decimal 1.2.0 (Hex package) (mix)
    * db_connection 1.0.0 (Hex package) (mix)
    * postgrex 0.12.1 (Hex package) (mix)
    * ecto 2.0.5 (Hex package) (mix)

* Operating system:

    ProductName:	Mac OS X
    ProductVersion:	10.11.6
    BuildVersion:	15G1108

### Current behavior

The following errors are generated:

#### ERROR 1

```shell

  1) test insertion (EctoCrashTest)
     test/ecto_crash_test.exs:12
     ** (DBConnection.ConnectionError) tcp recv: closed
     stacktrace:
       lib/ecto/adapters/postgres/connection.ex:97: Ecto.Adapters.Postgres.Connection.execute/4
       lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
       lib/ecto/adapters/sql.ex:454: Ecto.Adapters.SQL.struct/6
       lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       (ecto_crash) lib/ecto_crash.ex:28: EctoCrash.create_user/1
       test/ecto_crash_test.exs:14: anonymous fn/2 in EctoCrashTest.test insertion/1
       (elixir) lib/enum.ex:1628: anonymous fn/3 in Enum.reduce/3
       (elixir) lib/range.ex:92: Enumerable.Range.reduce/5
       (elixir) lib/enum.ex:1627: Enum.reduce/3
       test/ecto_crash_test.exs:13: (test)
```

#### ERROR 2

```shell

  1) test insertion (EctoCrashTest)
     test/ecto_crash_test.exs:12
     ** (DBConnection.ConnectionError) tcp recv: invalid argument - :einval
     stacktrace:
       lib/ecto/adapters/postgres/connection.ex:97: Ecto.Adapters.Postgres.Connection.execute/4
       lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
       lib/ecto/adapters/sql.ex:454: Ecto.Adapters.SQL.struct/6
       lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       (ecto_crash) lib/ecto_crash.ex:28: EctoCrash.create_user/1
       test/ecto_crash_test.exs:14: anonymous fn/2 in EctoCrashTest.test insertion/1
       (elixir) lib/enum.ex:1628: anonymous fn/3 in Enum.reduce/3
       (elixir) lib/range.ex:92: Enumerable.Range.reduce/5
       (elixir) lib/enum.ex:1627: Enum.reduce/3
       test/ecto_crash_test.exs:13: (test)

```

#### ERROR 3

```shell
  1) test insertion (EctoCrashTest)
     test/ecto_crash_test.exs:12
     ** (exit) exited in: :gen_server.call(EctoCrash.Repo.Pool, {:checkout, #Reference<0.0.1.100>, true}, 10000)
         ** (EXIT) shutdown
     stacktrace:
       :erlang.send(EctoCrash.Repo.Pool, {:"$gen_cast", {:cancel_waiting, #Reference<0.0.1.100>}}, [:noconnect])
       (stdlib) gen_server.erl:402: :gen_server.do_send/2
       (stdlib) gen_server.erl:232: :gen_server.do_cast/2
       src/poolboy.erl:58: :poolboy.checkout/3
       (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
       (db_connection) lib/db_connection.ex:712: DBConnection.checkout/2
       (db_connection) lib/db_connection.ex:619: DBConnection.run/3
       (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
       lib/ecto/adapters/postgres/connection.ex:91: Ecto.Adapters.Postgres.Connection.execute/4
       lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
       lib/ecto/adapters/sql.ex:454: Ecto.Adapters.SQL.struct/6
       lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       lib/ecto/repo/schema.ex:124: Ecto.Repo.Schema.insert!/4
       (ecto_crash) lib/ecto_crash.ex:28: EctoCrash.create_user/1
       test/ecto_crash_test.exs:14: anonymous fn/2 in EctoCrashTest.test insertion/1
       (elixir) lib/enum.ex:1628: anonymous fn/3 in Enum.reduce/3
       (elixir) lib/range.ex:92: Enumerable.Range.reduce/5
       (elixir) lib/enum.ex:1627: Enum.reduce/3
       test/ecto_crash_test.exs:13: (test)
```

### Expected behavior

It should not crash!

Any advice? Thank you in advance!

**Comment by fishcakez** [comment]
Hi @walkr. For Error 1 and Error 2 it looks like the socket is closed (`tcp recv: einval` probably occurs due to a race condition when the socket is closed at approximately the same time that a `:gen_tcp` function is called, if the call is made earlier or later it is `:closed`). Assuming there isn't an issue with TCP there should be another log because a transaction/standalone query checkout from pool or sandbox ownership has exceeded the `:timeout` or `:ownership_timeout`. Assuming this is correct you may want to investigate why the time outs are occurring, or if you need to increase the relevant timeout.

For Error 3 the Repo's pool is being shutdown by its parent process, the Repo. The stacktrace is misleading/incorrect because of a bug in poolboy (incorrect use of `:erlang.raise/3`). Not sure why the Repo is shutting down without seeing log messages.

So I think you will need to read the logger output here to investigate further. If there isn't anything logged it may not be possible to offer any advise without seeing the code.

**Comment by josevalim** [comment]
@walkr the bug is probably here:

https://github.com/walkr/ecto-crash/blob/master/lib/ecto_crash/server.ex#L40

That should be `{:noreply, state}`. Otherwise it is causing your worker to crash, which then causes the supervision tree to eventually restart or shutdown completely, which brings the postgrex connections down.

**Comment by ericmj** [comment]
@josevalim When I am running the code that error never shows up in the logs.

**Comment by walkr** [comment]
Yes, that is indeed causing the error. I can't believe I've missed that. Thank you @josevalim!

However, crashing (2) below should not crash (1). Shouldn't their failures be handled independently, since I've specified the `:one_for_one` restart strategy?

**Supervision tree**

```
EctoCrash.Supervisor 
    ├── EctoCrash.Repo   (1) ├── EctoCrash.Repo.Pool ├── ...
    └── EctoCrash.Server (2)
```

**Code in question**

```elixir
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    # Define workers and child supervisors to be supervised
    children = [
      supervisor(EctoCrash.Repo, []),
      worker(EctoCrash.Server, [:ok, []]),
    ]
    opts = [strategy: :one_for_one, name: EctoCrash.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

And thank you for your reply as well @fishcakez

**Comment by walkr** [comment]
UPDATE: I've looked into it. It looks like the children do get restarted independently. It's only when running tests that the application shutdown is triggered. My mistake!

Thank you guys!

**Comment by fishcakez** [comment]
@walkr I was too lazy to notice there was linked code :blush:. You are correct that children get restarted independently but once `max_restarts` occur in `max_seconds` the supervisor reaches its max restart intensity and shuts down. The supervisor is the top supervisor in the application so the application stops.

@ericmj the timeout value isn't checked by `:gen_server` and a `receive` will be attempted without a try. This leads to the `:gen_server` code raising a `:timeout_value` error that isn't caught - so no `GenServer` log message. However a (sasl) `:crash_report` should be logged by `:proc_lib`, and ofc the supervisor reports.
