### ISSUE TITLE
Add a ping repository operation

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1789]
We need a way to check if the database is alive and that won't crash if the database isn't. It probably requires adapter support. @fishcakez thoughts?

**Comment by josevalim** [comment]
We are closing this because the ping implementation on the connection is not a considerably improvement compared to running something like a "SELECT 1".

**Comment by schaary** [comment]
To send a ping to a server, you don't have to be authenticated or authorized - for `select 1` you have to be. Additionally you need select grants.
