### ISSUE TITLE
Changeset.Relation raises runtime error rather than InvalidChangesetError

### ISSUE THREAD

**Issue by adamboas** [elixir-ecto/ecto#1790]
### Environment

* Elixir version: 1.3.2:
* Database and version: PostgreSQL 9.5.4
* Ecto version (mix deps):2.0.2
* Database adapter and version (mix deps): postgrex 0.11.2
* Operating system: OS X Sierra

### Current behavior

If you provide invalid joins in your Changeset for a many_to_many relation it raises a RuntimeError

### Expected behavior

I would expect it to raise an Ecto.InvalidChangesetError like any other invalid Changeset. Perhaps I am missing something? Unfortunately this requires me to catch any runtime error in my processing stream rather than being able to deal with invalid data specifically.

**Comment by josevalim** [comment]
Can you please include the full error, stacktrace and an example of the
changeset fields being set?



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by adamboas** [comment]
The stacktrace is below. Unfortunately it doesn't dump the Changeset as it is just a RuntimeError.

The Question schema looks like this:
```
 schema "questions" do
    field :uuid, :string
    field :name, :string

    belongs_to :survey, WaffleEventImporter.Survey
    has_many :answers, Answer
    many_to_many :factors, WaffleEventImporter.Factor, join_through: "factors_questions"

    timestamps
  end
```

I took a look at the Changeset.Relation#on_replace where the below error message originates and it appears that this is intended behaviour.  I might be missing something but it seems like failing to save because of an invalid changeset should consistently raise Ecto.InvalidChangesetError and dump the changeset to assist with debugging.

```
 ** (RuntimeError) you are attempting to change relation :factors of
 WaffleEventImporter.Question, but there is missing data.
 
 If you are attempting to update an existing entry, please make sure
 you include the entry primary key (ID) alongside the data.
 
 If you have a relationship with many children, at least the same N
 children must be given on update. By default it is not possible to
 orphan embed nor associated records, attempting to do so results in
 this error message.
 
 It is possible to change this behaviour by setting `:on_replace` when
 defining the relation. See `Ecto.Changeset`'s section on related data
 for more info.
 
     (ecto) lib/ecto/changeset/relation.ex:193: Ecto.Changeset.Relation.on_replace/2
     (ecto) lib/ecto/changeset/relation.ex:302: Ecto.Changeset.Relation.reduce_delete_changesets/5
     (ecto) lib/ecto/changeset.ex:891: Ecto.Changeset.put_relation/5
     (waffle_event_importer) lib/waffle_event_importer/import_event/question.ex:41: WaffleEventImporter.ImportEvent.Question.update_question!/3
     (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
     (elixir) lib/enum.ex:651: Enum.each/2
     (waffle_event_importer) lib/waffle_event_importer/import_event/question.ex:24: WaffleEventImporter.ImportEvent.Question.update!/2
     (ecto) lib/ecto/adapters/sql.ex:472: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
```

**Comment by josevalim** [comment]
Thank you! If you check the `:on_replace` option mentioned in the error message, there is an optio to mark as invalid. I believe that's what you want:

      many_to_many :factors, WaffleEventImporter.Factor, join_through: "factors_questions", on_replace: :mark_as_invalid

**Comment by adamboas** [comment]
Ah yes, that is the behaviour I was after. Thanks so much @josevalim .
