### ISSUE TITLE
Postgres syntax error when renaming table with prefix

### ISSUE THREAD

**Issue by kelvinst** [elixir-ecto/ecto#1807]
First: I don't know if is this an ecto or a postgrex problem, I opened here, maybe you guys can tell me, and I would be happy to move this issue to the right repo, if needed.

### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.4
* Ecto version (mix deps): 2.0.5
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: MacOS Sierra - 10.12.1 Beta

### Current behavior

With the following migration:

```elixir
# ...

def change do
  rename table(:prospects), to: table(:companies)
end

# ...
```

I get the following error when executing it like this:

```bash
$ mix ecto.migrate --prefix juca
...
09:05:58.144 [info]  rename table juca.prospects to juca.companies
** (Postgrex.Error) ERROR (syntax_error): syntax error at or near "."
...
```
### Expected behavior

To run the migration normally. 😆

I searched the Postgres documentation and realized that the command `rename table juca.prospects to juca.companies`, the correct would be `rename table juca.prospects to companies`.

Just registering the bug here. Will probably opening a PR today. Thank you!

**Comment by kelvinst** [comment]
FIY, I "workaround" it with `execute "ALTER TABLE #{prefix}.prospects RENAME TO companies"`, but this is far away from the ideal. 😬

**Comment by kelvinst** [comment]
One more thing: just found out the code https://github.com/elixir-ecto/ecto/blob/v2.0.5/lib/ecto/migration.ex#L597 which puts the prefix in the second parameter too. 

My question now is: how to implement it so the rename command still working for the other adapters?

**Comment by michalmuskala** [comment]
I believe it should be enough to modify this function to skip emitting prefix for the second table, if the prefix is the same: 
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L665

**Comment by kelvinst** [comment]
Ow yeah! Than you so much. Opening PR ;)

**Comment by Zeeker** [comment]
It would be great of ecto could print a warning that the second prefix is being dropped due to postgres constraints. Took me an hour to narrow it down why my rename didn't work. 😕
