### ISSUE TITLE
Delegate storage behavior to other module (not adapter)

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#1820]
While creating new Ecto adapter I noticed that to support migrations Ecto requires a single adapter to implement three behaviors, but It makes adapter code really large and messy.

Maybe we can add helper method `adapter.__storage__` and `adapter.__structure__` that will be able to delegate all required methods to other modules?

**Comment by josevalim** [comment]
Make your adapter have only small functions that delegate to something else doing the work. :)
