### ISSUE TITLE
association removed when casting

### ISSUE THREAD

**Issue by ehtb** [elixir-ecto/ecto#1824]
This very much looks like a problem on my end, but since I have exhausted all my options and gathered all infos, the issue remains. I have also asked it on [Stackoverflow](http://stackoverflow.com/questions/40781811/how-to-build-an-association-using-ecto-and-guardian).

### Environment

* Elixir version (elixir -v): Elixir 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.5.5
* Ecto version (mix deps): 2.0.5
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: MacOs

### Current behavior

Given:
```
# MeetingController#create
changeset = case Guardian.Plug.authenticated?(conn) do
    true ->
        Guardian.Plug.current_resource(conn) # == existing user
        |> build_assoc(:meetings) # successfully builds a meeting with user_id
        |> Meeting.changeset_with_user(meeting_params) # removes user_id
     _ ->
        Meeting.changeset(%Meeting{}, meeting_params)
end

# Meeting:
....
schema "meetings" do
    field :title, :string
    field :description, :string

    belongs_to :user, User
end

def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:title, :description])
end

def changeset_with_user(model, params \\ %{}) do
    model
    |> changeset(params)
    |> assoc_constraint(:user)
end
...

# User
...
schema "users" do
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    has_many :meetings, Meeting

    timestamps
end
...
```

Calling build_assoc correctly sets the user_id, but calling changeset removes the association again.

calling `build_assoc` returns: `Meeting{meta: #Ecto.Schema.Metadata<:built, "meetings">, description: nil, id: nil, inserted_at: nil, title: nil, updated_at: nil, user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 107}`

calling `changeset_with_user` return: `#Ecto.Changeset<action: nil, changes: %{description: "test meeting description", title: "create meeting title"}, errors: [], data: #Api.Meeting<>, valid?: true>`

### Expected behavior

To insert the record, including the association.

**Comment by josevalim** [comment]
The `user_id` field is not in the changeset, because you have not explicitly given it as a change, but it is still inside `changeset.data.user_id`. If you insert the changeset, I believe everything should still work as we will lift the other fields from `changeset.data`, including the `user_id`. Can you please confirm that?

**Comment by ehtb** [comment]
Thanks, you're right. I was only checking the changeset, without considering the changeset.data properties.
