### ISSUE TITLE
[elixir-ecto] Do preload with join instead run several queries (and whithout duplicates)

### ISSUE THREAD

**Issue by Moussenger** [elixir-ecto/ecto#1826]
Using this issue: https://github.com/elixir-ecto/ecto/issues/1478

It would be good an option to force preload to run join instead two queries and merge the results like it's doing now.

Maybe include a merge option on query:

`from users in User,
  left_join: subscriptions in assoc(users, :subscriptions),
  preload: [subscriptions: subscriptions],
  merge: [subscriptions]`

So, we can choose if we want run all query on join or execute several queries to fetch data.

**Comment by josevalim** [comment]
Unless I misunderstood your request, that's exactly how it works today.

1. This performs one query:

    from users in User, left_join: subscriptions in assoc(users, :subscriptions), preload: [subscriptions: subscriptions]

2. This performs two queries:

    from users in User, preload: [:subscriptions]

**Comment by Moussenger** [comment]
Oh! Excuse me. I have a little problem with some tests. That works fine!
