### ISSUE TITLE
It should show error message

### ISSUE THREAD

**Issue by kostonstyle** [elixir-ecto/ecto#1829]
Hi all  

When I create the new table:

```
    create table(:companies_classes_languages) do

      add :company_class,   references(:companies_classes, column: :code, type: :integer), primary_key: true
      add :language_iso,    references(:languages_codes, column: :iso, type: :string), primary_key: true
      add :description,     :string

      timestamps

    end 
```

As you can see, I've forgot to set `primary_key: false`, what happened after migrate statement is, that the `id` column will be created. In my opinion, the compiler should complain.

It is a bug?

Thanks

**Comment by josevalim** [comment]
I believe it is OK as is, what you are doing is that you have a composite primary key with three entries, including the ID.

**Comment by kostonstyle** [comment]
Ok, thanks jose.
