### ISSUE TITLE
Embeded schema docs

### ISSUE THREAD

**Issue by vasspilka** [elixir-ecto/ecto#1831]
Some info on Ecto documentation about embeds are outdated, specifically the docs tell us to use `put_change` but it raises the following error
```
** (RuntimeError) changing embeds with change/2 or put_change/3 is not supported, please use put_embed/4 instead
         (ecto) lib/ecto/changeset.ex:875: Ecto.Changeset.put_change/7
         (ecto) lib/ecto/changeset.ex:868: Ecto.Changeset.put_change/3
```
I suppose its from the major changes to Ecto 2.x
Should I look into it and make a PR with updated docs? Is it already being worked on or needs more time?

**Comment by josevalim** [comment]
Can you please point to where in the docs the advice is given? Thank you!

**Comment by vasspilka** [comment]
In [embed_one](https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_one/3) there is this code example
```
order = Repo.get!(Order, 42)

# Generate a changeset
changeset = Ecto.Changeset.change(order)

# Change, put a new one or remove an item
changeset = Ecto.Changeset.put_change(changeset, :item, nil)

# Update the order
changeset = Repo.update!(changeset)
```

and same in `embeds_many`.

**Comment by josevalim** [comment]
Yes, great catch. A PR would be very appreciated. :)

**Comment by vasspilka** [comment]
ok :)

**Comment by vasspilka** [comment]
Hmm looked into it, and I'll make a small PR that will change `put_change` to `put_embeded`, however the documentation problem is a bitsy bigger, let me explain below.

Embeds are given an `id` field that contains values similar to this `"df73de5d-c218-44b5-9f3b-4b9425cfb87f"`, these id values have to be included in the attributes if you want to update an embedded structure, all this I did not find documentation for. I solved the problem with code like this 
```
  def update!(%Tour{} = tour, attrs) do
    ## Get info map and create new map that includes `id` field
    info = attrs.info
    |> Map.merge(%{id: tour.info.id})

    ## "replace" info in attrs with one that contains id
    attrs = update_in(attrs.info, fn(_) -> info end)
    ## update database with new attrs (including embedded info)
    tour
    |> Tour.changeset(attrs)
    |> Repo.update!
  end
```
furthermore `embeds_many` complicates things, here is an example code of what did I have to do to add a new embedded struct to a `embeds_many` without overriding old entries.
```
    # creates a list of Price structs including one new and all the old ones
    prices = [
      %Price{
        attendee_id:     attendee.id,
        attendee_number: attendee.number
      } | Contracts.get(contract.id).prices]

    ## updates contract to have all prices, old and new
    contract
    |> Ecto.Changeset.change()
    |> Ecto.Changeset.put_embed(:prices, prices)
    |> Repo.update!
```

all this is fine (unless I am actually doing it wrong), the problem is that these stuff are not well documented and I had a hard time figuring how stuff should work, so maybe do this small PR and then open another one documenting embeds and their use further?

**Comment by josevalim** [comment]
All of your comments and conclusions are correct. :) So multiple PRs to improve this are welcome!

It is likely some of those aspects are documented elsewhere, maybe in the changeset module or in has_one/has_many, but including more examples won't hurt.

**Comment by vasspilka** [comment]
made first PR, leaving this open to remind me to check out more of the docs and update something if I deem it useful.
