### ISSUE TITLE
Allow enabling extenstions using migrations

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#1832]
It would be nice to have `Ecto.Migration.extension` method which would allow us to run:

```elixir
defmodule MyApp.Migrations.EnableExtensions do
  use Ecto.Migration

  def change do
    create_if_not_exist extension("uuid-ossp")
  end
end
```

Or similar code. Similar to #1805

**Comment by michalmuskala** [comment]
Extensions are very postgresql specific. I would personally rather see them in a separate package, something like `PostgresEcto` that could also include other postgresql specific extensions - macros wrapping fragments for some common functions, etc.

**Comment by hauleth** [comment]
I can try to produce something like that.

**Comment by josevalim** [comment]
Unfortunately it is not possible to implement something like the above in a third party project. In any case, I don't mind having Postgres specific behaviour in Ecto most times, specially this one which is a very minor feature.

**Comment by hauleth** [comment]
@josevalim I can accept that challenge.

**Comment by michalmuskala** [comment]
Maybe we should look into ways of making it possible for extensions to provide such behaviour?

**Comment by josevalim** [comment]
@michalmuskala I would love to and tried a couple times in the past. The best solution I had in mind is to define one protocol per adapter and I am not confident it is the best way to go.
