### ISSUE TITLE
timeout value increase in ecto.

### ISSUE THREAD

**Issue by i-m-v-j** [elixir-ecto/ecto#1838]
hello, iam writing some complex queries and some times it takes more that 5 seconds to run. now the problem is, 8some times i time out from request.

i am using Ecto.Adapters.SQL.query() method to run queries. i want to know , i should i increase timeout values. without it , it is just timing out and can't do any processing.

**Comment by josevalim** [comment]
You can either `Ecto.Adapters.SQL.query(Repo, query, params, timeout: 30_000)` or by setting the `timeout: 30_000` in your Repo configuration in your `config/*` files.
