### ISSUE TITLE
Adapter.transaction is required and optional at the same time

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1839]
We recently removed the `Ecto.Adapter.Transaction` behaviour and merged the functions with the main `Ecto.Adapter`. This makes it required for all adapters to implement the transactions in some way (most probably raising if not supported). Relevant commit: https://github.com/elixir-ecto/ecto/commit/e4e8fe8d16b596d0f72764e2b84d91b35706c943.

At the same time, in the `Ecto.Repo.Schema` module, we preserved the old behaviour of checking if the transaction function is exported, to decide if transactions are supported by the adapter. Relevant line: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L672

This leads to a difficult situation for adapters that don't support transactions - they either need to skip the function, emitting warnings at compile-time or implement some form of emulating transactions, which is something we're trying to avoid.

**Comment by michalmuskala** [comment]
The initial issue that was solved by the problematic change: https://github.com/elixir-ecto/ecto/issues/1530

**Comment by josevalim** [comment]
Reverted in master.
