### ISSUE TITLE
on_conflict: :nothing with cast_assoc

### ISSUE THREAD

**Issue by maxsalven** [elixir-ecto/ecto#1850]
### Environment

* Elixir version (elixir -v): 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.6.1
* Ecto version (mix dips): 2.1.0-rc.4
* Database adapter and version (mix dips): postgrex 1.0.0-rc.1
* Operating system: OS X 10.11.6

### Possible Feature
Any plans to bring `on_conflict: :nothing` to `cast_assoc`?

A very contrived example:
if a `user` `belongs_to` a `category`, and my params are:
```elixir
%{
  name: "Max",
  category: %{
    name: "Staff"
  }
}
```
It would be great for `|> cast_assoc(:category)` to automatically deal with the case when a category with name "Staff" already exists in the DB and to automatically set `category_id` on the new user to the appropriate value.

**Comment by josevalim** [comment]
We will add this to Ecto 2.2. I want to support `:on_conflict` not only on cast_assoc but also on the regular `cast` and `change` functions.

**Comment by josevalim** [comment]
@maxsalven if you would like to move ahead with this, we are ready. :) The idea is that we will introduce an `opts` field in the changeset and be able to store options such as `:on_conflict` in there. We can start with supporting options on `cast` and `change` and then support it on `cast_assoc` and `cast_embed` as we see fit.

**Comment by josevalim** [comment]
For now we have added a `:repo_opts` field that you can set manually when building the changesets. For example: `%{changeset | repo_opts: [on_conflict: :ignore]}`.
