### ISSUE TITLE
Support referencing excluded table in Repo.insert_all/3 on_conflict update

### ISSUE THREAD

**Issue by nobrick** [elixir-ecto/ecto#1853]
### Environment
* Database and version: PostgreSQL 9.5
* Ecto version: 2.1.0-rc.5
* Database adapter and version: postgrex 0.12.1

### Description

In PostgreSQL `INSERT ON CONFLICT DO UPDATE` clause, we can use the special `EXCLUDED` table to reference values originally proposed for insertion according to the [docs](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT):

```SQL
INSERT INTO distributors (did, dname)
    VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc')
        ON CONFLICT (did) DO UPDATE SET dname = EXCLUDED.dname;
```

This is particularly useful for bulk-insert cases. It would be great to support this in `Ecto.Repo.insert_all/3`.

**Comment by michalmuskala** [comment]
This is in some ways related to https://github.com/elixir-ecto/ecto/pull/1846

**Comment by josevalim** [comment]
@nobrick you can today by using query and fragments:

    query = from p in Post, update: [set: [title: fragment("EXCLUDED.title")]
    Repo.insert_all Post, entries, on_conflict: query

A bit verbose but should do the job for now. :) Plus #1846 will handle the most common cases.

Thank you!

**Comment by lukerollans** [comment]
Hello from the future! I just came across this myself as I'm upserting with Ecto for the first time. I see that #1846 is merged and this matter consider closed, but I'm wondering if there's plans to allow upserting with `insert_all/3` _without_ specifying existing ID's?

I'd love the ability to give `insert_all/3` a list of maps (no ID's) and have Ecto upsert over conflicting records while keeping primary keys intact. For now, I'm using the fragment method as suggested above (I didn't know about the `EXCLUDED` table.. the more you know!).

I've had a dig around to see if there's a conversation in play but no luck. If you think it might be worthwhile, I'm keen to start a discussion on the mailing list or whatever is approriate.

Thank you!!
