### ISSUE TITLE
json types not compiling

### ISSUE THREAD

**Issue by TBK145** [elixir-ecto/ecto#1858]
* Elixir version (elixir -v): 1.4.0-rc.1
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): 2.1.0-rc.5
* Database adapter and version (mix deps): 0.13.0-rc.0
* Operating system: Ubuntu 16.04

Poison version 2.2.0

### Current behavior

With the change to the new postgrex/ecto combination we had to change the way our types are defined (I found this not very well documented tbh, eg: where to define what), so now we define our `Core.Ecto.Repo` as follows:
```
defmodule Core.Ecto.Repo do
  @moduledoc false
  use Ecto.Repo, otp_app: :core
  use Ecto.Migration, otp_app: :core

  @application_name :core

  Postgrex.Types.define(Core.PostgresTypes,
    [Core.Ecto.Extension.XML, Core.Ecto.Extension.PrefixRange, Core.Ecto.Extension.Name]
      ++ Ecto.Adapters.Postgres.extensions(),
    json: Poison)

  def conf do
    Application.get_env(@application_name, __MODULE__)
  end
end
```
our `config.exs`:
```
config :core, Core.Ecto.Repo,
  adapter: Ecto.Adapters.Postgres,
  types: Core.PostgresTypes,
  {...}
```
However, when defining a schema that has a :json field, it gives a compile error.
```
  schema "accounts" do
    field :name, :string
    # schema-less, user-defined data
    field :data, :json
    timestamps()
  end
```
```
== Compilation error on file lib/models/account.ex ==
** (ArgumentError) invalid or unknown type :json for field :data
    lib/ecto/schema.ex:1722: Ecto.Schema.check_type!/3
    lib/ecto/schema.ex:1426: Ecto.Schema.__field__/4
    lib/models/account.ex:13: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

I already tried cleaning everything and recompiling, but the error stays.

**Comment by wojtekmach** [comment]
I think the type on the **schema** should be `:map` (or `{:map, :string} etc` if you want fine-grained type checking), not `:json`.

**Comment by TBK145** [comment]
But in [this](https://github.com/elixir-ecto/ecto/blob/7de8c4ac15fa9e8678f08a2e2d57e17b6cac63ad/lib/ecto/migration.ex#L591-L594) example it says `:json`.

**Comment by wojtekmach** [comment]
that's a migration, not your schema definition. You want to store your data as `:json`/`:jsonb` in the DB, and represent it as e.g `:map` in Ecto

**Comment by josevalim** [comment]
@TBK145 the migration example could use map as well, I will improve it.

Regarding the new Postgrex types, I have recently added how to upgrade to the CHANGELOG and to the docs.

**Comment by TBK145** [comment]
So I changed it to `:map`, but right now it still gives an error:
```
iex(1)>Core.Ecto.Repo.insert %Core.Model.Account{name: "foo", data: %{}}
14:55:05.785 [debug] pid=<0.1178.0> module=Ecto.LogEntry function=log/1 line=41 QUERY OK db=1.9ms
begin []
14:55:05.789 [debug] pid=<0.1178.0> module=Ecto.LogEntry function=log/1 line=41 QUERY ERROR db=3.0ms
INSERT INTO "accounts" ("data","name","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5) [%{}, "foo", <<79, 242, 29, 62, 220, 62, 73, 27, 188, 116, 233, 48, 106, 111, 194, 44>>, {{2016, 12, 16}, {13, 55, 5, 786132}}, {{2016, 12, 16}, {13, 55, 5, 786166}}]
** (Postgrex.Error) ERROR 08P01 (protocol_violation): insufficient data left in message
14:55:05.790 [debug] pid=<0.1178.0> module=Ecto.LogEntry function=log/1 line=41 QUERY OK db=0.3ms
rollback []
             (ecto) lib/ecto/adapters/sql.ex:570: Ecto.Adapters.SQL.struct/7
             (ecto) lib/ecto/repo/schema.ex:457: Ecto.Repo.Schema.apply/4
             (ecto) lib/ecto/repo/schema.ex:198: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
             (ecto) lib/ecto/repo/schema.ex:674: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
             (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
```

**Comment by josevalim** [comment]
Are you using any of the new custom types in the query above?

**Comment by josevalim** [comment]
Also, can you please paste your migration?

**Comment by TBK145** [comment]
Only a map which has to be converted to JSON by Poison.
```
      create table(:accounts, primary_key: false) do
        add :id, :uuid, primary_key: true
        add :name, :string
        add :data, :json
        timestamps()
      end
```

**Comment by josevalim** [comment]
I am not sure if this is the cause of your issue, I would have to investigate, but prefer to use `add :data, :map` in your migration (or `add :data, :jsonb`) as jsonb would be more efficient.

**Comment by TBK145** [comment]
Turns out the name field in the database still had type prefixrange (a custom type like you suggested). When I migrated and the field was changed to a string it worked fine. So now I will have to debug that extension for the protocol error. Thanks anyway for helping!
