### ISSUE TITLE
Repo.insert may return schema without {:ok, _} tuple

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#1861]
I will describe full path to make it clear why this can happen (at least it happens with Mnesia adapter, but somehow I can't reproduce this issue inside adapters tests):

1. Whenever you use `Repo.insert/2` it will call [following code](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L189) that delegates work to [`Repo.Schema.insert/4`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L160).

2. All workload for `Repo.Schema.insert/4` is done inside `Repo.Schema.do_insert/4` function that wraps results in transaction via `wrap_in_transaction/6` function. `Repo.Schema.insert/4` will exit [on this line](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L202) returning `{:ok, schema}` tuple, as expected.

3. But transaction wrapper `wrap_in_transaction/6` will match all `{:ok, schema}` tuples and [return `schema`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L677). Thus Repo.insert will return `schema` instead of expected `{:ok, schema}` tuple.

Any ideas when this was added to code? Am I missing something?

**Comment by josevalim** [comment]
Could it be an issue with your transaction implementation? The transaction implementation should return the result of the block wrapper in `{:ok, value_from_block}`.

**Comment by michalmuskala** [comment]
That looks completely correct. The contract of the `Ecto.Adapter.transaction/3` callback is to wrap the return value (in case of a successful transaction) in an `{:ok, _}` tuple, so the [final block](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L675-L680) should always return correct value.

I suspect that the adapter you're using does not adhere to the interface and does not wrap the return value in the tuple.

**Comment by AndrewDryga** [comment]
Yes, it could be issues in my transaction. Ill check and be back shortly.

Maybe it's a good idea to rename `schema` in `wrap_in_transaction/6` to `query_results` or something less ambiguous? Just pick a name and i'll PR it.

**Comment by josevalim** [comment]
In that case it is a `struct` and it will always be. So I believe it is correctly named?

**Comment by AndrewDryga** [comment]
You are right, miss read it as `schema`.
