### ISSUE TITLE
Float in embedded schema incorrectly written to db

### ISSUE THREAD

**Issue by strokovnjaka** [elixir-ecto/ecto#1866]
When an embedded schema contains a field of type float it is in some cases incorrectly written to db. Embedded schema is an `embeds_one :options, Test.Options, on_replace: :delete`, of type `jsonb` in postgres db, and it contains
```elixir
  embedded_schema do
    field :float_two, :float
  end
```
1. In case changeset contains value of e.g. 1,  `changes: %{float_two: 1.0}`, then `Repo.update` results in a correct state, e.g.
```
 id |     name     |  options
----+--------------+----------------------
  1 | testname     |  {"float_two": 1.0}
```
Reading the embedded schema is ok.

2. In case changeset contains value of e.g. 3000, `changes: %{float_two: 3.0e3}`, then `Repo.update` results in e.g.
```
 id |     name     |  options
----+--------------+----------------------
  1 | testname     |  {"float_two": 3000}
```
Reading the embedded schema in this case raises e.g.
```
Exception: ** (ArgumentError) cannot load `3000` as type :float for :float_two in schema Test.Options
    (ecto) lib/ecto/schema.ex:1394: Ecto.Schema.load!/5
    (ecto) lib/ecto/schema.ex:1362: anonymous fn/5 in Ecto.Schema.__load__/4
    (stdlib) lists.erl:1262: :lists.foldl/3
    (ecto) lib/ecto/schema.ex:1347: Ecto.Schema.__load__/6
    (ecto) lib/ecto/type.ex:440: Ecto.Type.load_embed/3
    ...
```

### Environment

* Elixir version (elixir -v): Elixir 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.1
* Ecto version (mix deps): ecto 2.1.0-rc.4
* Database adapter and version (mix deps): ecto 2.1.0-rc.4
* Operating system: macosx 10.11.6
* Poison: poison 2.2.0

**Comment by michalmuskala** [comment]
What version of Poison (or other json serializer, if you changed the default) are you using?

**Comment by strokovnjaka** [comment]
@michalmuskala poison is version 2.2.0, updated above

**Comment by ericmj** [comment]
I don't think this is a Poison bug. Poison encodes integers as `1` and floats as `1.0`, which is valid according to the json spec.

The question is why ecto doesn't cast the value `3000` to `3000.0`. It would be interesting to see how you build the changeset, there is a chance no casting is happening.

**Comment by strokovnjaka** [comment]
Changeset is built as below. It seems that if inspecting changeset shows the changed value in E notation (e.g. 3.0e3) the value is written as integer. 
If I put "1" or "10" or "3000.1" in params below, the thing works correctly, while "100" shows 1.0e2 in changeset and an integer appears in db.

```elixir
defmodule Test.Options do
  embedded_schema do
    field :float_two, :float
  end
  def changeset(arguments, params \\ :empty) do
    arguments
    |> cast(params, [:float_two])
    |> validate_required([:float_two])
  end
end

defmodule Test do
  schema "tests" do
    field :name, :string
    embeds_one :options, Test.Options, on_replace: :delete
  end
  def changeset(arguments, params \\ :empty) do
    arguments
    |> Ecto.Changeset.cast(params, [:name])
    |> Ecto.Changeset.cast_embed(:options, required: true)
  end
end

id = 1
params = %{name: "testname", options: %{float_two: "3000"}}
Repo.get!(Test, id)
|> Test.changeset(params)
|> Repo.update
```

**Comment by strokovnjaka** [comment]
The problem seems to be related to both poison and postgres. The query produced is
```sql
UPDATE "tests" SET "options" = $1 WHERE "id" = $2 [%{float_two: 3.0e3}, 1]
```
Postgres then writes `3000` to db, same as if in psql
```sql
update tests set options = jsonb_set(options, '{float_two}', '3.0e3') where id=1;
select options->'float_two' from tests where id=1;
 ?column? 
----------
 3000
(1 row)
```
Putting in `'3000.0'` produces 
```
 ?column? 
----------
 3000.0
(1 row)
```

**Comment by strokovnjaka** [comment]
As per [postgres docs](https://www.postgresql.org/docs/current/static/datatype-json.html) it seems to me I've been barking up the wrong tree. 

The problem is not writing the numeric type but reading it. I think ecto should always take into account the underlying type of embedded field: translating it to postgres jsonb types and back is not unambiguous.

So loading a `jsonb` field of type `numeric` with value `3000` into a field of type `float` or `integer` should both succeed, whereas loading the same with value `3000.0` into a field of type `float` should succeed, but to type `integer` it should not.

**Comment by strokovnjaka** [comment]
I found the problem was with loading the thing from a map. It works ok when loading from db.
