### ISSUE TITLE
Repo.insert_all("table_name", changeset) does not work when running release. It hangs.

### ISSUE THREAD

**Issue by jakkra** [elixir-ecto/ecto#1867]
* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps):  2.1.0
* Database adapter and version (mix deps): 
* Operating system: Windows 10

It works well when running mix phoenix.server both in dev and prod.
However when I make a release using {:exrm, "~> 1.0"} it doesn't work.

`
      Repo.insert_all("table_name_which_exist_for_this_model", chunk)
`
This line hangs, I added so that Ecto logs all queries, but doing this line, no output is given. No error or anything. It just hangs there. No code after that line is executed.

It works well with just `Repo.insert_all(Model, chunk)` but I need to specify exactly which table.

**Comment by josevalim** [comment]
Can you let us know what is the `chunk`? Can you perform other queries? Also, can you reproduce it locally? Without a way to reproduce this it may be quite hard to fix it.

**Comment by jakkra** [comment]
@josevalim I can perform other queries. chunk is an array with maximum allowed number of changesets (`Float.floor(65_535 / 4) |> round`). The changesets are nothing special, just 4 rows with integer data. I can reproduce it locally when I make a release build and start this from the terminal. 

I'll see if I can make an example project where I can reproduce it for you.

Do you know if there are any other good way for me to come around using insert_all here. It's a lot of data I insert.

**Comment by josevalim** [comment]
@jakkra I have no idea. And it is so weird this manifests only with releases but not in `MIX_ENV=prod mix phoenix.server`. Paging @fishcakez in case he has any idea about what is happening.

**Comment by josevalim** [comment]
@jakkra btw, you are using a release candidate for Ecto, you probably want to migrate to Ecto 2.0 or to the latest Ecto 2.1. Maybe this bug has been fixed already. :)

**Comment by jakkra** [comment]
@josevalim Tested with latest `ecto 3.2.1` and latest `phoenix_ecto 3.2.1` still same problem.

**Comment by josevalim** [comment]
@jakkra thank you. So I think we really need a way to reproduce this so we can further investigate and pinpoint the bug.

**Comment by jakkra** [comment]
@josevalim I managed to reproduce it easily. I created a repo for you here https://github.com/jakkra/ecto_insert_all_issue_reproduce.

It works quick in both dev and prod, but when you run the release it's insanely slow.

**Comment by fishcakez** [comment]
Thank you for the report and especially the example project @jakkra, I will look at this tomorrow.

**Comment by jakkra** [comment]
@fishcakez Awesome thank you!

**Comment by josevalim** [comment]
@jakkra I have tried it locally and both versions take 2s. I am afraid this may be something related to Windows.

Can you please try the following in the release console: `Protocol.consolidated?(String.Chars)`?

**Comment by jakkra** [comment]
@josevalim Running `Protocol.consolidated?(String.Chars)` gives me `false`.

**Comment by josevalim** [comment]
> @josevalim Running Protocol.consolidated?(String.Chars) gives me false.

That's the culprit. When releases are built, protocols are consolidated and they replace the default protocol definition. For some reason that's not happening on Windows with Exrm. But it seems to be happening successfully with Window and just Mix.

I would try to either: 1. open up an issue on exrm and see if they have a solution or 2. try the distillery project [which obsoletes exrm](https://github.com/bitwalker/distillery) and may have fixed the issue.

**Comment by jakkra** [comment]
@josevalim Okey great, thanks alot! Now I know the problem! I will try Distillery first and see if that helps :)
