### ISSUE TITLE
Multiple nested cast_assoc don't work as expected

### ISSUE THREAD

**Issue by behrendtio** [elixir-ecto/ecto#1873]
### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PG 9.6.1
* Ecto version (mix deps): 2.0.6
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: MacOS 10.12.2

### Current behavior

Given the following simplified schemas:

```elixir
defmodule App.One do
  schema "ones" do
    many_to_many :twos, App.Two, join_through: App.Three
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [])
    |> cast_assoc(:twos, required: true)
  end
emd
```

```elixir
defmodule App.Two do
  schema "twos" do
    many_to_many :ones, App.One, join_through: App.Three
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [])
    |> cast_assoc(:threes)
  end
end
```

```elixir
defmodule App.Three do
  schema "three" do
    field :amount, :integer
    belongs_to :one, App.One
    belongs_to :two, App.Two
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:amount])
    |> validate_required([:amount])
  end
end
```

the following code:

```elixir
One.changeset(%One{}, %{
  twos: [%{
    threes: [%{amount: 100}]
  }]
})
|> Repo.insert!
```

Will correctly insert the entries for `One` and `Two`, but will not correctly associate all three schemas with the `amount` value.

This is the simplified SQL output in the console:

```sql
INSERT INTO "ones" ("inserted_at","updated_at") VALUES ($1,$2) RETURNING "id" [{{2016, 12, 24}, {11, 51, 18, 0}}, {{2016, 12, 24}, {11, 51, 18, 0}}]
INSERT INTO "twos" ("inserted_at","updated_at") VALUES ($1,$2) RETURNING "id" [{{2016, 12, 24}, {11, 51, 18, 0}}, {{2016, 12, 24}, {11, 51, 18, 0}}]
INSERT INTO "threes" ("amount","two_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" [100, 29, {{2016, 12, 24}, {11, 51, 18, 0}}, {{2016, 12, 24}, {11, 51, 18, 0}}]
INSERT INTO "threes" ("two_id","one_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" [29, 29, {{2016, 12, 24}, {11, 51, 18, 0}}, {{2016, 12, 24}, {11, 51, 18, 0}}]
```

The third query associates the schemas `Two` and `Three`, including the `amount` value, but not with the `One` schema. Then Ecto issues another query, associating all three schemas, but without the `amount` value.

### Expected behavior

Not sure if this is a bug or an error on my side, but given how Ecto works with one nested `cast_assoc`, I'd assume it works the same for multiple nested ones.

Therefore, expected would be to have only one query targeting the `threes` table, including the values for `one_id`, `two_id` AND `amount`.

**Comment by josevalim** [comment]
You need to keep them unidirectional. If you have duplicate entries, in this case in the "threes" table which is happening 1. via join table and 2. via the explicit amount, then Elixir will consider those separate entries and it will introduce two distinct values.

A simpler way to say it: Elixir has no idea those "threes" are the same value and will attempt to introduce them twice. One solution is to introduce the Three entry:

```elixir
Repo.insert!(%Three{
  one: %{...},
  two: %{...},
  amount: ...
}
```

**Comment by behrendtio** [comment]
Ah I see. Unexpected from a users point of view, coming from `accepts_nested_attributes_for`, but understandable.

For people coming here from Google, the whole functionality using changesets would be:

```elixir
Three.changeset(%Three{}, %{
  amount: 100,
  two: %{...),
  one: %{...}
})
```

when the Three model has the following `changeset` function:

```elixir
def changeset(struct, params \\ %{}) do
  struct
  |> cast(params, [:amount])
  |> validate_required([:amount])
  |> cast_assoc(:ingredient)
  |> cast_assoc(:recipe)
end
```
