### ISSUE TITLE
update_change behavior on required field

### ISSUE THREAD

**Issue by almassapargali** [elixir-ecto/ecto#1874]
Hello

### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4.5
* Ecto version (mix deps): 2.1.0-rc.1
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: macOS

Currently, docs for `update_change` stats:

```
The given `function` is invoked with the change value only if there
  is a change for the given `key`. Note that the value of the change
  can still be `nil` (unless the field was marked as required on `cast/3`).
```

1. We are not passing required through `cast` functions anymore.
2. Even with `validate_required` before `update_change` I'm getting nil value in update function.

I think we either should update docs that it can be `nil` even for required fields, or make function passed to `update_change` run only when value is not nil. Let me know what should we do, and I'll make a PR with changes.

**Comment by josevalim** [comment]
I think we should change `validate_required` and `validate_change` to remove the field from `changes` if it does not pass validation. It may solve many of the problems with checking for `valid?: true` in changeset. @michalmuskala, @wojtekmach, what do you think?

**Comment by wojtekmach** [comment]
+1 for removing field from `changes` when it doesn't pass validation. The incorrect (blank) field value will be still in `params` so it won't break e.g. forms. The only other change I can think of is to update wording for https://github.com/elixir-ecto/ecto/blob/v2.1.1/lib/ecto/changeset.ex#L199: to be something along the lines of:

```markdown
* `changes`      -  The `changes` from parameters that were approved in casting and passed validations
```

**Comment by michalmuskala** [comment]
I'm :-1: for removing from `changes` on validation failures. This would make it impossible to catch multiple validation errors on a single field - it's not inconceivable that could happen.

`validate_required` is a different case, I think it might make sense to remove `nil` values from changes there, provided the value in `data` is `nil` too.

**Comment by josevalim** [comment]
Good call. Restricting it to validate_required sounds good then.
