### ISSUE TITLE
Default primary keys to BIGINT

### ISSUE THREAD

**Issue by bradleybeddoes** [elixir-ecto/ecto#1879]
### Current behavior

Ecto defaults new tables to have a primary key of `integer`.

```
xyz_dev=# \d some_table
                                      Table "public.some_table"
   Column    |            Type             |                      Modifiers
-------------+-----------------------------+-----------------------------------------------------
 id          | integer                     | not null default nextval('some_table_id_seq'::regclass)
...
```

### Proposed behaviour

Change Ecto to default to `BigInt` for all `id` fields. 

A change which is similar in nature to this request has recently been accepted into Rails master per https://github.com/rails/rails/pull/26266

Alternatively allow opts provided to `table/2` (https://hexdocs.pm/ecto/Ecto.Migration.html#table/2) to specify the datatype the field should utilise.

Foreign Key behaviour will need to be considered if this proposal gets carried forward.

**Comment by josevalim** [comment]
We should change them all to `:bigserial` (today we use `:serial`) and make sure we also translate `:bigserial` in the MySQL adapter to `BIGINT UNSIGNED`.

**Comment by michalmuskala** [comment]
It seems we're already using `BIGINT UNSIGNED` for primary keys in MySQL https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/mysql/connection.ex#L689

I'm :+1: for this change.

**Comment by bradleybeddoes** [comment]
I'm happy to have a poke around at the changes necessary and propose a PR if that would be of help. It'll give me a good excuse to look inside Ecto more than I have to date.

**Comment by josevalim** [comment]
That would definitely be welcome!
