### ISSUE TITLE
Repo.update raises Ecto.StaleEntryError

### ISSUE THREAD

**Issue by wmnnd** [elixir-ecto/ecto#1891]
Hi there,

it seems that Ecto.Repo.update raises an exception when the filter applied by optimistic_lock is not met. Instead, I would expect Repo.update to return an error tuple and only Repo.update! to raise the exception.

* Elixir version: 1.3.3
* Database and version: MariaDB 10.0.28
* Ecto version: ecto 2.2.0-dev
* Database adapter and version: mariaex 0.8.0
* Operating system: Ubuntu 16.10

### Current behavior
```elixir
changeset
|> Ecto.Changeset.optimistic_lock(:lock_field),
|> Repo.update(changeset)
```

```
** (Ecto.StaleEntryError) attempted to update a stale struct:

%MyStruct{[…]}

             (ecto) lib/ecto/repo/schema.ex:459: Ecto.Repo.Schema.apply/4
             (ecto) lib/ecto/repo/schema.ex:263: anonymous fn/13 in Ecto.Repo.Schema.do_update/4
[…]
             (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
```

### Expected behavior
I would expect an error tuple as with other validation or constraint errors.

**Comment by josevalim** [comment]
I believe this has been "reported" in the past. The issue is that we are unable to know if the record does not exist or if there was a filter violation so we cannot quite make it an error. For such reasons, I believe the exception is the best way to signal something unexpected may have gone happened.
