### ISSUE TITLE
Allow schema :field to have an alias

### ISSUE THREAD

**Issue by Bharat311** [elixir-ecto/ecto#1892]
Hi,

I am fairly new to elixir and am currently working on developing a service application on phoenix.

It uses MongoDB as a backend and i am using `mongo-ecto` as the adapter to connect to the database.

The issue i am facing is that the fields in the MongoDB (as per normal practise) use short names. So, `first_name` is stored as `fn`, etc. Now, I want to access the field using proper names (read: `first_name`) throughout the code. 

One approach that i could think of makes use of `virtual` fields like below:

```
defmodule User do
  use Blog.Web, :model

  schema “users” do
    field :fn, :string
    field :first_name, :string, virtual: true
  end

  def copy_from_alias(%{})
    # we copy values from alias
  end
	
  def copy_to_alias(%{})
    # we set value to aliases 
  end
end
```

We can also have the above code autogenerated via a macro like `aliased_field`.

However, with this i’ll need to explicitly call these methods whenever casting data to/from database. 
Is there any way to avoid doing that ?

Also, i am not sure how to get it working with queries. For eg:

`Repo.get_by(User, %{first_name: “Bharat”})`

should check for `fn` when forming query and not `first_name`.

Is there any other approach that solves this problem ? I am willing to raise a PR for the same as i believe this to be a fairly regular use case (MongoDB, legacy databases, etc.) if i can get some pointers.

Any help is appreciated.

**Comment by johnnyshields** [comment]
Two thoughts:

```
  schema “users” do
    field :fn, :string, alias: :first_name
  end
```

or


```
  schema "users" do
    field :first_name, :string
  end

  mongo_adapter "users" do
     map_field :first_name, to: :fn
  end
```

**Comment by johnnyshields** [comment]
@josevalim would be great to get your direction on how this could be implemented, we're happy to give it a try if there's an agreed upon spec.

**Comment by johnnyshields** [comment]
@josevalim any comment here? This is an important issue for our team to migrate from Ruby/Mongoid to Elixir.

**Comment by sevenseacat** [comment]
Out of curiosity, why is it 'normal practise' to use cryptic and meaningless field names in MongoDB?

**Comment by johnnyshields** [comment]
@sevenseacat unlike other DBs which use position-dependent columns, MongoDB is a document database and the column names are sorted within the row. So you can significantly reduce the size of objects by using aliases:

```
{ my_long_field_name: "my value", my_other_field: "other value" }
```

becomes

```
{ f1: "my value", f2: "other value" }
```

**Comment by johnnyshields** [comment]
A secondary reason for both schema and schema-less DBs is from time-to-time you may want to migrate or rename columns, and using aliases make it much easier to move things around without renaming the variable throughout your entire app.

**Comment by sevenseacat** [comment]
Cheers for that. Now I have another reason to avoid Mongo apps...

**Comment by josevalim** [comment]
@johnnyshields I believe this has been discussed in the past. Did you find any relevant information in previous discussions?

**Comment by johnnyshields** [comment]
@josevalim I'm not aware of where these discussions were held. I've searched this repo for issues containing "alias" and I don't see it.

**Comment by josevalim** [comment]
@johnnyshields let's give the `:alias` option a try then. This is a somewhat complex issue because it does not only touch insert/update/delete operations but also all queries.

**Comment by johnnyshields** [comment]
@josevalim great, thanks. We'll start work on this soon.

**Comment by Qqwy** [comment]
Just wanted to make sure that you are aware of [the discussion about aliases](https://elixirforum.com/t/how-to-approach-converting-camelcase-to-snake-case-field-names/4375/3) that is going on on the Elixir forum. I think this is mostly relevant because the Original Poster describes an alternative situation in which field aliases would be helpful, namely one in which Elixir+Ecto needs to use an already-existing database that uses CamelCase field names.

**Comment by hbobenicio** [comment]
+1 on this.
In my case, my database has "ugly" column name conventions that I wouldn't like to inherit in my phoenix/ecto project. I got some columns like "some_random_prefix_convention_foo" that would be great if used only as "foo" on my model.

**Comment by johnnyshields** [comment]
@hbobenicio there is a PR branch here https://github.com/elixir-ecto/ecto/pull/1998 ready to merge which we are using in our apps, please help push to get it merged.

**Comment by josevalim** [comment]
In master! Please give it a try and test it further!

**Comment by scf4** [comment]
Is there a way to convert names between camel/snake case, without "source" on every field?

**Comment by michalmuskala** [comment]
You could create a custom `field` macro that would compute the correct source and call the original `field`.

**Comment by josevalim** [comment]
The macro works but we can possibly make it easier. What if we have a
source_mapper option that is given to schema/2 and it I invoked for every
field?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by scf4** [comment]
Thanks @michalmuskala I'll give it a try

@josevalim a source_mapper option would be perfect!
