### ISSUE TITLE
Problem with convert date after upgrade to 2.1

### ISSUE THREAD

**Issue by es1o** [elixir-ecto/ecto#1899]
Hello, I've recently upgraded ecto from 2.0 to 2.1 and I have this error during convert DateTime to iso format:
`
** (FunctionClauseError) no function clause matching in Ecto.DateTime.to_iso8601/1
     stacktrace:
       (ecto) lib/ecto/date_time.ex:584: Ecto.DateTime.to_iso8601(~N[2017-01-09 17:11:31.208162])
       test/unit_tests/esioci_router_test.exs:91: (test)
`

`~N[2017-01-09 17:11:31.208162]` comes from insert! function.

With 2.0 version everything was fine.
### Environment

* Elixir version (elixir -v): elixir 1.3.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.2-1.pgdg80+1 
* Ecto version (mix deps): 2.1.2
* Database adapter and version (mix deps): postgrex 0.13.0
* Operating system: Ubuntu 16.10 x86_64

**Comment by NilsLattek** [comment]
Ecto 2.1 uses NaiveDateTime, so please try ```NaiveDateTime.to_iso8601/1``` which was introduced in elixir 1.3 or 1.4 (you might need to upgrade).

**Comment by michalmuskala** [comment]
Did you change the schema types? `Ecto.DateTime` struct corresponds to the custom ecto schema type `Ecto.DateTime`, `NaiveDateTime` struct, that you have there corresponds to the schema type `:naive_datetime`. In 2.0 only the former existed, 2.1 introduced the new types to take advantage of the built-in calendar structs introduced in Elixir 1.3.

**Comment by josevalim** [comment]
Ecto 2.1 defaults to :naive_datetime, so you can easily fix by adding `timestamps type: Ecto.DateTime` to the relevant schema. This way Ecto will emit the old types and everything should work as before. We do recommend eventually migrating to the new types though. Such has been noted in the changelog.

**Comment by es1o** [comment]
Thanks for response, I've changed Ecto.DateTime to NaiveDateTime and works on Elixir 1.3.3.
