### ISSUE TITLE
documentation over `opts` arguments is incomplete for certain methods. 

### ISSUE THREAD

**Issue by seivan** [elixir-ecto/ecto#1900]
### Environment
* Ecto version (mix deps): 2.1.2

You only find out by stepping through the [source](https://github.com/elixir-ecto/ecto/blob/v2.1.2/lib/ecto/migrator.ex#L73) that the `opts ` argument in `Ecto.Migrator.run` can contain `:prefix` once you reach [the end](https://github.com/elixir-ecto/ecto/blob/v2.1.2/lib/ecto/migrator.ex#L73).

Not sure what the best solution is as it could easily fill a whole page for certain methods, but maybe a link to the 'main' method that continue with the same `opts` or something.

**Comment by josevalim** [comment]
We should just duplicate the options in the documentation options section. Being complete is more important than being concise here.

**Comment by seivan** [comment]
I leave that up to you.
