### ISSUE TITLE
Nested fragments complaining about wrong types

### ISSUE THREAD

**Issue by TBK145** [elixir-ecto/ecto#1905]
* Elixir version (elixir -v): 1.4.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgresql 9.4.5
* Ecto version (mix deps): 2.1.2
* Database adapter and version (mix deps): postgrex 0.13.0
* Operating system: Ubuntu 16.04

### Current behavior

I currently use two macros with fragment functions:
```elixir
    defmacro coalesce(left, right) do
      quote do
        fragment("COALESCE(?, ?)", unquote(left), unquote(right))
      end
    end
    defmacro between(field, left, right) do
      quote do
        fragment("? BETWEEN ? AND ?", unquote(field), unquote(left), unquote(right))
      end
    end
```
But when I call them like this:
```elixir
|> where([p1, p2, p3], between(p3.start_time, coalesce(^Ecto.Time.cast!("12:00:00"), ^Ecto.Time.cast!(timestamp)), coalesce(p2.stop_time, ^Ecto.Time.cast!("24:00:00"))))
```
I get this error:
```
** (Postgrex.Error) ERROR 42883 (undefined_function): operator does not exist: time without time zone >= text
12:25:36.054 [debug] pid=<0.1147.0> module=Ecto.LogEntry function=log/1 line=41 QUERY ERROR db=1.3ms
[...] AND (r2."start_time" BETWEEN COALESCE($7, $8) AND COALESCE(r1."stop_time", $9)) [[...] {12, 0, 0, 0}, {12, 25, 34, 492907}, {23, 59, 0, 0}]
    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
```
It's quite a long query, so I replaced two parts with [...], but I'm 100% positive that that works.

### Expected behavior
I would expect Ecto not to use constraints like type checking on fragments, because the COALESCE function will return a time without time zone instead of a text.

On a side note, why do I have to explicitly cast `timestamp` (A DateTime) with `^Ecto.Time.cast!(timestamp)`? Can't that be done automatically?

**Comment by michalmuskala** [comment]
The error is complaining about the `>=` operator, but in the fragment of the query you posted it is not used. It is my understand that this part of the query is not the problem.

**Comment by TBK145** [comment]
Yes, that's my issue too, I don't use the `>=` operator, so I assumed it would have something to do with the between statement.

**Comment by TBK145** [comment]
I see I copied the wrong "where"-statement, I updated it now.

**Comment by josevalim** [comment]
What are the column types of start_time and stop_time in the database? Ecto is not doing anything special here, so I am assuming BETWEEN compiles down to >= which is leading the database to think it is comparing a text to time. The question is: from where text is coming from? I can think about some options:

  1. The database column is text
  2. The interpolated value is a text
  3. The text is coming as a default type from coalesce

Although all three operations above are unlikely, I would check them to be sure. The second option does not seem to be the case given the logs above. One option is to use explicit type annotations:

```elixir
defmacro between_time(field, left, right) do
  quote do
    fragment("? :: timestamp BETWEEN ? :: timestamp AND ? :: timestamp", unquote(field), unquote(left), unquote(right))
  end
end
```

Or the equivalent Postgres query.

**Comment by TBK145** [comment]
\d on the database table returns `time without timezone`, as expected.

I changed the macro to the following:
```elixir
    defmacro between(field, left, right) do
      quote do
        fragment("? :: time BETWEEN ? :: time AND ? :: time", unquote(field), unquote(left), unquote(right))
      end
    end
```
And it returned this error:
```
** (ArgumentError) Postgrex expected a binary, got {12, 0, 0, 0}. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
13:13:02.105 [debug] pid=<0.1147.0> module=Ecto.LogEntry function=log/1 line=41 QUERY ERROR db=5.4ms
[...] WHERE (r2."start_time" :: time BETWEEN COALESCE($5, $6) :: time AND COALESCE(r1."stop_time", $7) :: time) [[...] {12, 0, 0, 0}, {13, 13, 0, 490949}, {23, 59, 0, 0}]
    (voiceover_core) /home/thijs/Documents/voiceover_umbrella/deps/postgrex/lib/postgrex/type_module.ex:716: Voiceover.Core.PostgresTypes.encode_params/3
          (postgrex) lib/postgrex/query.ex:45: DBConnection.Query.Postgrex.Query.encode/3
     (db_connection) lib/db_connection.ex:1070: DBConnection.describe_run/5
     (db_connection) lib/db_connection.ex:1141: anonymous fn/4 in DBConnection.run_meter/5
     (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
     (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
              (ecto) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.prepare_execute/5
              (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
              (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
              (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
              (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
```

So it looks like the `^Ecto.Time.cast!("12:00:00")` isn't interpolated correctly for the fragment?

**Comment by josevalim** [comment]
Can you please try `COALESCE($5 :: time, $6 :: time)` and so on just to be sure?

**Comment by TBK145** [comment]
```
** (Postgrex.Error) ERROR 42846 (cannot_coerce): cannot cast type integer to time without time zone
[...] WHERE (r2."start_time" :: time BETWEEN COALESCE($5 :: time, $6 :: time) :: time AND COALESCE(r1."stop_time" :: time, $7 :: time) :: time)
[...] {12, 0, 0, 0}, {14, 40, 0, 804169}, {23, 59, 0, 0}]
    (ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
```

**Comment by josevalim** [comment]
I may be barking at the wrong tree but to me it is still looking that postgres is expecting something else besides a time in coalesce. Here would be my last try. Replace the coalesce implementation by this:

```elixir
    defmacro coalesce(left, right) do
      quote do
        fragment("CASE WHEN ? IS NULL THEN  ? ELSE ? END", unquote(left), unquote(right), unquote(left))
      end
    end
```

Btw, the reason why using `\d` works is because it is not using prepared statements. So it allows Postgres to look at the whole query with parameters. Ecto, on the other hand, uses prepared statements so the query is prepared without the parameters and I believe in such cases Postgres needs to decide the types for the interpolated parameters upfront. So I am assuming it is expecting an integer or a text and when you pass `:: time` or something of sorts, it doesn't work as expected.

Another option you can try is to do the casting on postgres instead of Ecto. So you could have:

```elixir
defmacro cast_as_time(string) do
  quote do
    fragment("? :: time", string)
  end
end
```

and then `cast_as_time(^"12:00:00")` instead of `Ecto.Time.cast!`.

**Comment by TBK145** [comment]
Turns out I was calling coalesce somewhere else as well, which caused the last error...
Explicitly casting coalesce's arguments as `time` did the trick, the castings in the between macro were not even necessary.

So I think that `^Ecto.Time.cast!("12:00:00")` is not being seen as a `time`, but rather a `text` in postgres?

**Comment by josevalim** [comment]
> So I think that ^Ecto.Time.cast!("12:00:00") is not being seen as a time, but rather a text in postgres?

It is the opposite. Postgres is guessing it to be a text and then it gets surprised when we send a time. That's because in prepared queries we first prepare the query, without the parameters, so Postgres has to guess. That's why the explicit castings help.

I don't think there is anything we can do on Ecto side, unfortunately. So I will go ahead and close this issue. Let me know though if you have ideas about how this could be improved.
