### ISSUE TITLE
Specifying a unique index for upsert's conflict_target

### ISSUE THREAD

**Issue by madshargreave** [elixir-ecto/ecto#1907]
Hi

I have the following partial unique index

`execute "CREATE UNIQUE INDEX user_email_idx ON visitors(email) WHERE type = 'user';"`

But I have not been able to find a way to specify this when performing the upsert. I want to do something akin to

`opts = [on_conflict: on_conflict, conflict_target: "user_email_idx"]`

**Comment by josevalim** [comment]
Can you please use the mailing list for questions? Here is an example from the documentation:

```elixir
MyRepo.insert(%Post{title: "this is unique"}, on_conflict: on_conflict, conflict_target: :title)
```

**Comment by josevalim** [comment]
@madshargreave I am not sure it matters. All Postgres expects is a name. If you are getting an error, please let us know which one is it, but that is likely a Postgres limitation rather than Ecto.

**Comment by madshargreave** [comment]
It complains that the the 'column' doesnt exists, ie. it interprets the conflict_target value as a column name, and not as the name of the index

**Comment by josevalim** [comment]
Can you please paste the full error? Also can you try to write the query using Postgres directly in the Postgres terminal and let us know if there is a variant that works?

**Comment by asgoel** [comment]
Here's an example @josevalim:

Let's say I have a table with primary key email and constraint: `"email_preference_email_unique_index" UNIQUE, btree (lower(email::text))`

If I specify the conflict target as `:email` I get:
```
** (Postgrex.Error) ERROR 23505 (unique_violation): duplicate key value violates unique constraint "email_preference_email_unique_index"

    table: email_preference
    constraint: email_preference_email_unique_index

Key (lower(email::text))=(email@email.com) already exists.
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.insert_all/7
    (ecto) lib/ecto/repo/schema.ex:55: Ecto.Repo.Schema.do_insert_all/7
```

Here's a postgres query that works:
```
INSERT INTO email_preference (email, should_receive_emails) VALUES ('EMAIL@EMAIL.COM', 'f') ON CONFLICT (lower(email)) DO UPDATE SET should_receive_emails='f';
```

If i try setting `conflict_target: "lower(email)"` in my `insert_all` call, I get the following error:
```
** (Postgrex.Error) ERROR 42703 (undefined_column): column "lower(email)" does not exist
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.insert_all/7
    (ecto) lib/ecto/repo/schema.ex:55: Ecto.Repo.Schema.do_insert_all/7
```

Not sure why it wouldn't work to be honest

**Comment by asgoel** [comment]
Dug deeper and I think its because we intersperse the quote names here: https://github.com/elixir-ecto/ecto/blob/v2.1.4/lib/ecto/adapters/postgres/connection.ex#L197. The resulting binary looks something like `(\"lower(email)\")` which I think might be tripping up postgres since it thinks thats a column

**Comment by adenisonafifi** [comment]
I'm not sure if this issue has been resolved already, but I am also trying to use `Repo.insert` with a unique_index `:conflict_target`. I tried `Repo.insert(on_conflict: :replace_all, conflict_target: :unique_index_name)` and found that it was being checked as a table name as well.

Per @josevalim I tried writing the query using Postgres directly and found the same error:
```
dev=# INSERT INTO "future_event_people" ("checked_in") VALUES (true) ON CONFLICT ("unique_future_person") DO UPDATE SET "checked_in" = true RETURNING "id";
ERROR:  column "unique_future_person" does not exist
LINE 1: ..._people" ("checked_in") VALUES (true) ON CONFLICT ("unique_f...
```

Here is the index listed:
```
Indexes:
    "unique_future_person" UNIQUE, btree (person_id, future_event_id)
```

Found this [postgres post](https://www.postgresql.org/message-id/CAN9Kr4C6An92CpWg%3DyLOjat9pcFM0AMF1e%2By5TszpRyx4cH2ew%40mail.gmail.com) and tried out the proposed solution:  

`INSERT INTO "future_event_people" ("checked_in") VALUES (true) ON CONFLICT (person_id, future_event_id) DO UPDATE SET "checked_in" = true RETURNING "id";`

This does execute for me, but I don't know if it is checking the correct unique index.

**Comment by adenisonafifi** [comment]
Just hit this issue as well when trying to use `conflict_target: "(person_id, event_id)"`. The query debug statement prints out this: `ON CONFLICT ("person_id, future_event_id")`

**Comment by josevalim** [comment]
@adenisonafifi have you tried passing a list to conflict_target? `conflict_target: [:person_id, :event_id]`?

**Comment by josevalim** [comment]
And yes, if we solve #2081 this would then be possible too. Good catch.

**Comment by adenisonafifi** [comment]
`conflict_target: [:person_id, :event_id]` properly resolved to `ON CONFLICT ("person_id","event_id")`. Thank you, I should have tried that.
