### ISSUE TITLE
Proposal: Ecto.Repo insert_all/3: on_conflict with fragment or similar 

### ISSUE THREAD

**Issue by emerleite** [elixir-ecto/ecto#1908]
Trying to use **GREATEST** on *on_conflict*, I ended with a code like this:

```elixir
    struct
    |> changeset
    |> Repo.insert(on_conflict: from(v in MyModel, update: [set: [field: fragment("GREATEST(field, ?)", ^struct.value)]]))
```

But I expected something like this should work:

```elixir
    struct
    |> changeset
    |> Repo.insert(on_conflict: [set: [field: fragment("GREATEST(field, ?)", struct.some_value)]]))
```

Or maybe something like this (I prefer the previous version, but this could be a try):

```elixir
    struct
    |> changeset
    |> Repo.insert(on_conflict: [set: "FIELD = GREATEST(field, #{struct.some_value})"]]))
```

I'm not sure if we need an extra parameter or Ecto could be smart enough to deal with this.

**Comment by josevalim** [comment]
It is not going to work because Repo.insert is a regular function. fragments require macros, that's why the second example does not work, and the third example would be vulnerable to sql injection attacks. The way to go is to write on_conflict: as a query and then pass the query as argument.

**Comment by emerleite** [comment]
Thanks for the explanation, @josevalim ;)
