### ISSUE TITLE
Error with :on_conflict and put_assoc

### ISSUE THREAD

**Issue by maxsalven** [elixir-ecto/ecto#1912]
### Environment

* Elixir version (elixir -v): 1.3.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.5.3
* Ecto version (mix dips): 2.1.2
* Database adapter and version (mix dips): postgrex 0.13.0
* Operating system: OS X 10.11.6

### Current behavior

This works fine:
````
car = Repo.get(Car, 1)

User.changeset(%User{}, params)
|> put_assoc(:cars, [car])
|> Repo.insert()
````

This does not work:
````
car = Repo.get(Car, 1)

User.changeset(%User{}, params)
|> put_assoc(:cars, [car])
|> Repo.insert(on_conflict: [set: [name: params["name"]]], conflict_target: :name)

** (Postgrex.Error) ERROR 42703 (undefined_column): column "name" does not exist
````

Please let me know if you are unable to reproduce, I've simplified a complicated real world example. I think Ecto is trying to call Repo.insert on the Car struct rather than the User struct.

**Comment by josevalim** [comment]
You should see in the log the queries being attempted. Can you please
report them here? We may be trying to use the on_conflict conditions on
both queries.

**Comment by maxsalven** [comment]
You are correct, it is using the on_conflict condition on both queries.

```
INSERT INTO "users" AS u0 ("name","created_at","updated_at")
VALUES ($1,$2,$3)
ON CONFLICT ("name")
DO UPDATE SET "name" = $4 RETURNING "id" [...]

INSERT INTO "cars_users" AS c0 ("user_id","car_id")
VALUES ($1,$2)
ON CONFLICT ("name")
DO UPDATE SET "name" = $3 [...]
```
