### ISSUE TITLE
DateTime.from_erl/1 and Time.from_erl/1 should accept microseconds

### ISSUE THREAD

**Issue by CaptChrisD** [elixir-ecto/ecto#1913]
`Time.load/1` accepts microseconds but `Time.from_erl/1` does not, see:
https://github.com/elixir-ecto/ecto/blob/v2.1.2/lib/ecto/date_time.ex#L381

Same for `DateTime`
https://github.com/elixir-ecto/ecto/blob/v2.1.2/lib/ecto/date_time.ex#L615

This is important when the schema specifies `usec: true` and fragments are used in the selects.

When using a fragment on a select the Erlang tuple format is returned instead of being cast to an `Ecto.DateTime`. This is probably not the only place where this is important... but I couldn't get `type/2` to work and bumped into this issue

Example run
```
iex(6)> Ecto.Time.from_erl {16,15,42}
#Ecto.Time<16:15:42>
iex(7)> Ecto.Time.from_erl {16,15,42,100}
** (FunctionClauseError) no function clause matching in Ecto.Time.from_erl/1
    (ecto) lib/ecto/date_time.ex:381: Ecto.Time.from_erl({16, 15, 42, 100})
iex(7)> Ecto.Time.load {16,15,42,100}
{:ok, #Ecto.Time<16:15:42.000100>}
```

```
iex(8)> Ecto.DateTime.load {{2017, 1, 16}, {16, 15, 42, 591114}}
{:ok, #Ecto.DateTime<2017-01-16 16:15:42.591114>}
iex(9)> Ecto.DateTime.from_erl {{2017, 1, 16}, {16, 15, 42, 591114}}
** (FunctionClauseError) no function clause matching in Ecto.DateTime.from_erl/1
    (ecto) lib/ecto/date_time.ex:615: Ecto.DateTime.from_erl({{2017, 1, 16}, {16, 15, 42, 591114}})
```

This is on the latest codebase

**Comment by josevalim** [comment]
Hi @CaptChrisD. Since those types are soft-deprecated in Ecto 2.1, I would recommend migrating to Elixir's calendar types and let us know if you run into any issues or if you have any questions.

**Comment by josevalim** [comment]
I will close this for now. If you still believe it is worth improving the old and deprecated types, please send a PR or a drop a comment here.
