### ISSUE TITLE
[RFC] Ecto.Query.API.map/2 support for maps

### ISSUE THREAD

**Issue by 0xAX** [elixir-ecto/ecto#1916]
Hello everyone,

The `Ecto.Query.API` provides `map/2` for select:

```elixir
select: map(city, [:country_id, :name])
```

would be good to add support for maps as second parameter:

```elixir
select: map(city, %{id: :country_id, name: :name})
```

where the keys represent actual fields names and values represent columns names in a response. What do you think? Why hasn't it been implemented before? If there are no objects, I'd implement this

**Comment by wojtekmach** [comment]
You can do this today:

```elixir
select: %{id: city.country_id, name: city.name}
```

**Comment by 0xAX** [comment]
@wojtekmach yes, but if i don't know exact list of fields which I want to select, how can I generate them? 

I mean for example each time I get list with fields names which should be selected: `[:name]` in the first case, `[:id, :name]` in the second case, `[:country_id, :whatever]` and etc...

**Comment by wojtekmach** [comment]
oh, I see what you mean, interesting. In that case I'd probably grab the result of the query (map from your 1st example) and create a new map replacing the keys with custom ones.

Perhaps there's a simpler way; per issue template you should ask for support in other mediums like elixirforum etc, and if you want to propose a new feature the mailing list is the appropriate place (Ecto Core: sorry if I'm stepping on your toes!)

**Comment by umatomba** [comment]
@wojtekmach, 

> In that case I'd probably grab the result of the query (map from your 1st example) and create a new map replacing the keys with custom ones.

it's not effective if you think about performance

**Comment by josevalim** [comment]
Right now you will have to do another pass on the data. The query API is already complex and I don't want to add support for uncommon scenarios unless we really have to. It is more code to maintain, more complexity and possibly a source of confusion.
