### ISSUE TITLE
ecto.rollback should also rollback test database

### ISSUE THREAD

**Issue by Valentin-Seehausen** [elixir-ecto/ecto#1924]
When changing a migration file (yes, some people have to do that), mix ecto.rollback doesn't effect the test database, which can be irritating. A short discussion of this: https://elixirforum.com/t/rollback-test-database/1158/4

You can set MIX_ENV=test, but first you have to know about this issue.

So ecto.rollback and ecto.reset should per default effect the test database, too.

**Comment by josevalim** [comment]
We currently don't plan to special case the test environment. So if you change your migrations, please be mindful you have to rollback it too.

**Comment by Valentin-Seehausen** [comment]
It is kind of irritating.

Ecto.migrate does effect the test environment.
Ecot.rollback does NOT effect the test environment.

2017-01-24 23:57 GMT+13:00 José Valim <notifications@github.com>:

**Comment by josevalim** [comment]
That's not true. ecto.migrate does not affect the test environment. You probably have a task in your mix.exs doing it for you.

**Comment by Valentin-Seehausen** [comment]
Ah ok (good to know :) ).

"test": ["ecto.create --quiet", "ecto.migrate", "test"]

Maybe it would make sense ecto.reset there. I will open a issue.

Thank you ;)

2017-01-25 12:26 GMT+13:00 José Valim <notifications@github.com>:
