### ISSUE TITLE
Multiple concurrent migrations don't work due to "template1" database being used

### ISSUE THREAD

**Issue by mmainz** [elixir-ecto/ecto#1925]
### Environment

* Elixir version (elixir -v): 1.4.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.1
* Ecto version (mix deps): 2.1.3
* Database adapter and version (mix deps): postgrex 0.13.0
* Operating system: OS X 10.12.2

### Current behavior

When doing `mix ecto.create`, a connection is opened to the `template1` database. However, if there is already another connection to `template1`, the database creation will fail:

```
** (Mix) The database for Envoy.Repo couldn't be created: ERROR 55006 (object_in_use): source database "template1" is being accessed by other users

There is 1 other session using the database.
```

To reproduce this, just do `psql -d template1` and leave that prompt open while doing `mix ecto.create` in another terminal window.

### Expected behavior

Creating the database should succeed no matter how many connections there are to `template1`. This is especially true for running multiple `mix ecto.create` tasks concurrently.

### Additional info

This is documented PostgreSQL behavior, as you can read here: https://www.postgresql.org/docs/current/static/manage-ag-templatedbs.html

The problem with this is, if you have multiple applications that have their database on the same database server, creating the databases will fail if you happen to do that concurrently. I have never seen this happen in production, but in theory it could.

We also have a Docker environment for running our microservices landscape on our local development machines. There, we execute migrations and database creation on startup. In that environment, we can see this behavior rather often, which is not ideal.

**Comment by josevalim** [comment]
Do you have any suggestions on how to solve this problem?

**Comment by mmainz** [comment]
Well, I'm not an expert when it comes to PostgreSQL. Probably connecting to a different database for `mix ecto.create` would be sufficient. But I'm not sure what the best practice is.

I found this very old PR where people discussed whether to connect to `template1` or `postgres`: https://github.com/elixir-ecto/ecto/pull/260

So maybe using `postgres` is the better alternative after all? I could try reproducing the issue with the `postgres` database and report my findings. Other than that, I can only search Google for best practices on this.

**Comment by josevalim** [comment]
@mmainz if you can do the research, that would help us a ton. We can also see what other frameworks are doing. The fix itself is likely straight-forward. Finding the right fix is the tricky part. :)

**Comment by mmainz** [comment]
@josevalim sure, I already tried to find out what ActiveRecord does, but that source code is a little tricky to read :)

I'll give it another shot. Then I'll see if I can find something in the PostgreSQL documentation. When I made up my mind, I'll check if the problem is eliminated if I make the appropriate change. I'll come back to you then :)

**Comment by mmainz** [comment]
Postgres documentation states that you should use the `postgres` database for stuff like creating new databases. That is also the database used by CLI tools like `createdb`. After some digging, it seems Rails does also use the `postgres` database for that. You can find the relevant documentation page here: https://www.postgresql.org/docs/current/static/manage-ag-createdb.html

**Comment by yoonghm** [comment]
Initdb CLI is used to create a postgresql database cluster, which, by
default, should contain template0, template1 and postgres databases.

Standard and third party applications assume the existance of postgres
database in a postgresql database cluster (abbreviated as cluster)

template1 is used only during creation of new database within the cluster.

Database administrator can create additional database within the cluster.

I am new to Elixir and Ecto. If ecto.create is used to create new database
within the cluster, the described behaviour (not able to connect to
template1 if it is connected by more than 1 connection) is correct.
