### ISSUE TITLE
Default parameters are not returned by Repo.insert/2

### ISSUE THREAD

**Issue by arashm** [elixir-ecto/ecto#1927]
### Environment
key | value
--------- | ------
Elixir version (elixir -v) | 1.4.0
Database and version | PostgreSQL 9.6.1
Ecto version (mix deps) | 2.1.3
Database adapter and version (mix deps) | postgrex 0.13.0
Operating system | Archlinux

### Current behavior

I have model created like this (with a default value for `city_id`):

```elixir
defmodule Sample.Repo.Migrations.CreateUser do
  use Ecto.Migration

  def change do
    create table(:users) do
      add :first_name, :string
      add :last_name, :string
      add :city_id, :integer, default: 5
      timestamps()
    end
  end
end
```

The `Repo.insert/2` does not return the default value `5` for city_id:

```elixir
iex> Sample.Repo.insert(%Sample.User{first_name: "Test"})
{:ok,
 %Sample.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, city_id: nil,
  first_name: "Test", last_name: nil, id: 1, inserted_at: ~N[2017-01-26 20:43:32.748233],
  updated_at: ~N[2017-01-26 20:43:32.752669]}}
```

This only happens with the `index/2` and getting the same record after being inserted, does have the default value:

```elixir
iex> Sample.Repo.get(Sample.User, 1)
 %Sample.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, city_id: 5,
  first_name: "Test", last_name: nil, id: 1, inserted_at: ~N[2017-01-26 20:43:32.748233],
  updated_at: ~N[2017-01-26 20:43:32.752669]}}
```

### Expected behavior

`insert/2` returned result should have the default values already assigned.

**Comment by michalmuskala** [comment]
By default Elixir will not query the database to return field values after insert. You can turn this behaviour on by passing the `read_after_writes` option to the `field` macro or using the schema-level default.
