### ISSUE TITLE
map not supported in macro

### ISSUE THREAD

**Issue by blset** [elixir-ecto/ecto#1936]
### Environment

* Elixir version (elixir -v): Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.1

* Database and version (PostgreSQL 9.5.5:
* Ecto version (mix deps): 2.1.3
* Database adapter and version (mix deps): postgreex 0.13
* Operating system: osx el capitan 10.11.6

here is the macro definitions 

```
defmodule Testmac do

defmacro binary(key) do

    quote do
        [
           fragment("case when (?->>?) in ('oui','1') then 1  else 0 end", u.response, unquote(key)),
           fragment("case when (?->>?) in ('non','2') then 1  else 0 end", u.response, unquote(key)),
          ]
    end
  end

  defmacro mapbin(key) do

    quote do
        %{
          "1" =>  fragment("case when (?->>?) in ('oui','1') then 1  else 0 end", u.response, unquote(key)),
          "2" =>  fragment("case when (?->>?) in ('non','2') then 1  else 0 end", u.response, unquote(key)),
         }
    end
  end
end
```

--------------------------

here is a call which does compile

`from u in resp, select: [binary(^key)]
`

--------------------------
here is a call which also compiles 

```
from u in resp, select: [
        %{
          "1" =>  fragment("case when (?->>?) in ('oui','1') then 1  else 0 end", u.response, ^key),
          "2" =>  fragment("case when (?->>?) in ('non','2') then 1  else 0 end", u.response, ^key),
         }
]

```
--------------------------

here is the call which does not compile, when wrapped in a macro

`from u in resp, select: [mapbin(^key)]
`

## here is the compilation error

** (Ecto.Query.CompileError) `%{"1" => fragment("case when (?->>?) in ('oui','1') then 1  else 0 end", u.response(), ^key), "2" => fragment("case when (?->>?) in ('non','2') then 1  else 0 end", u.response(), ^key)}` is not a valid query expression.

**Comment by josevalim** [comment]
Oh, just now I noticed what can be the cause of error. You cannot have a map inside a list. We will fix that. :)

**Comment by blset** [comment]
Are you sure ? this compiles ok though

from u in resp, select: [

        %{

          "1" =>  fragment("case when (?->>?) in ('oui','1') then 1  else 0 end", u.response, ^key),

          "2" =>  fragment("case when (?->>?) in ('non','2') then 1  else 0 end", u.response, ^key),

         }

]


I routinely use maps inside a list at least for the select clause of the from macro

**Comment by josevalim** [comment]
Hrm, you are right. I am jumping into the code right now and investigating then. :)

**Comment by blset** [comment]
thanks

how do I use it ?

can I use master git on production ?

**Comment by josevalim** [comment]
I will update the CHANGELOG so you can take an informed decision if you can use master in production or not. You should be OK most of the time.
