### ISSUE TITLE
order_by not working with distinct

### ISSUE THREAD

**Issue by nhu313** [elixir-ecto/ecto#1937]
When I try to use order_by and distinct at the same time, order_by doesn't work.

### Environment
* Database: Postgres
* Ecto version: 2.0.4

### Current behavior

Here is the test I wrote for `postgres_test.exs`
```elixir
  test "distinct first then order by" do
    query = Schema |> distinct([r], r.x) |> order_by([r], desc: r.x) |> select([r], r.x) |> normalize
    assert SQL.all(query) == ~s{SELECT DISTINCT ON (s0."x") s0."x" FROM "schema" AS s0 ORDER BY s0."x" DESC}
  end
````

This is the result I get back:

```elixir
code: SQL.all(query) == ~s"SELECT DISTINCT ON (s0.\"x\") s0.\"x\" FROM \"schema\" AS s0 ORDER BY s0.\"x\" DESC"
     lhs:  "SELECT DISTINCT ON (s0.\"x\") s0.\"x\" FROM \"schema\" AS s0 ORDER BY s0.\"x\", s0.\"x\" DESC"
     rhs:  "SELECT DISTINCT ON (s0.\"x\") s0.\"x\" FROM \"schema\" AS s0 ORDER BY s0.\"x\" DESC"
```
-----------------
### Extra details

Looking at the code in `lib/ecto/adapters/postgres/connection.ex` line 371, I was thinking of putting order_bys first. So this:

```elixir
      [" ORDER BY " |
       intersperse_map(distinct ++ order_bys, ", ", &order_by_expr(&1, sources, query))]
```

becomes this:

```elixir
      [" ORDER BY " |
       intersperse_map(order_bys ++ distinct, ", ", &order_by_expr(&1, sources, query))]
```

It works, but it doesn't generate the SQL statement I expect. In `postgres_test.exs` these tests look inconsistent to me:

`distinct` test line 99

```elixir
    query = Schema |> distinct([r], r.x) |> select([r], {r.x, r.y}) |> normalize
    assert SQL.all(query) == ~s{SELECT DISTINCT ON (s0."x") s0."x", s0."y" FROM "schema" AS s0}

    query = Schema |> distinct([r], desc: r.x) |> select([r], {r.x, r.y}) |> normalize
    assert SQL.all(query) == ~s{SELECT DISTINCT ON (s0."x") s0."x", s0."y" FROM "schema" AS s0}
```

`distinct([r], desc: r.x)` ignores the ordering and generates the same statement as `distinct([r], r.x)`. However the test below takes the ordering into account. 

```elixir
  test "distinct with order by" do
    query = Schema |> order_by([r], [r.y]) |> distinct([r], desc: r.x) |> select([r], r.x) |> normalize
    assert SQL.all(query) == ~s{SELECT DISTINCT ON (s0."x") s0."x" FROM "schema" AS s0 ORDER BY s0."x" DESC, s0."y"}
  end
```

**Comment by josevalim** [comment]
Order by and distinct seems to work correctly. Postgres requires that, when distinct and order by are used, all of the columns in distinct on need to appear first on the order_by.

What am I missing?

**Comment by nhu313** [comment]
I'm confused. When I write this query, I expect it to be order_by `x`. Isn't that right?

```elixir
Schema 
|> distinct([r], r.x) 
|> order_by([r], desc: r.x) 
|> select([r], r.x) 
|> normalize
```
However, this is the query it generates. 

```elixir
"SELECT DISTINCT ON (s0.\"x\") s0.\"x\" FROM \"schema\" AS s0 ORDER BY s0.\"x\", s0.\"x\" DESC"
```

This query doesn't order by `x` because the statement says order by s0.x in ascending order, then s0.x in descending order. If that is the expected behavior, then my question is, how can I write the statement with distict and order_by. For example, this is the query I write:

```elixir
Movie |> distinct([m], m.name) |> order_by([m], desc: m.year) |> select([m], m.year) |> normalize
```

I want to order it by Movie year in descending order. But right now, it is ordering it by name in ascending order, then year in descending order.

**Comment by josevalim** [comment]
The query you want to write is not possible in postgres AFAIK. If you use `distinct on` and `order_by`, the columns you specify in distinct on need to come first.

**Comment by nhu313** [comment]
Sorry, I'm still confused. I want to write this SQL statement, which I know works. Is that possible with Ecto?
 
```
"SELECT DISTINCT ON (s0.\"year\") s0.\"year\" FROM \"movies\" AS s0 ORDER BY s0.\"year\" DESC"
```

**Comment by josevalim** [comment]
Oh, I see. Can you try this:

```elixir
Movie 
|> distinct([m], desc: m.year) 
|> order_by([m], true) 
|> select([m], m.year)
```

**Comment by nhu313** [comment]
That didn't seem to work. But I switched the order_by and distinct args and that gives me the result I want. I didn't really need to do an `DISTINCT ON`.

```elixir
Movie 
|> distinct([m], true) 
|> order_by([m], desc: m.year) 
|> select([m], m.year)
```

This query also gives me the query result I want. 

```elixir
Movie
|> distinct([m], desc: m.year)
|> order_by([m], desc: m.year)
|> select([m], m.year)
```

It generates this query. 
```
SELECT DISTINCT ON (s0.\"year\") s0.\"year\" FROM \"movies\" AS s0 ORDER BY s0.\"year\" DESC, s0.\"year\" DESC
```

Sorry, I should I have tried the different combinations. So I guess it is working as intended like the doc said.

**Comment by josevalim** [comment]
Glad it works. I will clause this for now. I believe it could be better, especially given that we duplicate the order_by, but it is very likely the database will optimize it away anyway, so we should be fine until we come up with a cleaner API to force order bys.
