### ISSUE TITLE
Querying dynamic virtual table

### ISSUE THREAD

**Issue by andreapavoni** [elixir-ecto/ecto#1940]
Hello there,

not sure if this is the right place instead of StackOverflow, however I think that this could be an useful discussion here. Here's some context.

I have a simple table to track existing appointments:

```
  field :user_id, :integer
  field :duration, Ecto.Postgres.Tsrange # this one is a custom type that handles PG's tsrange
```

I want to get the available slots based on duration, user and date, so I wrote this raw SQL query:

```
    WITH slots AS (
      SELECT UPPER (duration) AS start_at,
        LEAD ( LOWER (duration), 1, UPPER (duration) )
        OVER (ORDER BY duration) - UPPER (duration) AS available_time,
        user_id AS user_id
      FROM (
        SELECT user_id, duration
        FROM appointments
        WHERE user_id = #{user_id}
        UNION ALL
        VALUES
          (#{user_id}, '[#{opens.beginning_of_day}, #{opens.open_at})'::tsrange),
          (#{user_id}, '[#{opens.close_at}, #{opens.end_of_day})'::tsrange)
      ) AS _
    )
  
    SELECT * FROM slots
    WHERE available_time >= '#{duration} minutes'::INTERVAL
    ORDER BY start_at ASC
```

It works as expected, however I have to run it through `Ecto.Adapters.SQL.query` and then wrap/parse raw results into a proper struct (or a list of it).

So my question: is there a way to use Ecto.Query.API to avoid wrapping/parsing of raw results?

Thanks in advance :-)

**Comment by michalmuskala** [comment]
The `Repo.load/2` function was created exactly for loading raw results into structs with proper type casting.

An example [from the docs](https://hexdocs.pm/ecto/Ecto.Repo.html#c:load/2)
```elixir
iex> result = Ecto.Adapters.SQL.query!(MyRepo, "SELECT * FROM users", [])
iex> Enum.map(result.rows, &MyRepo.load(User, {result.columns, &1}))
[%User{...}, ...]
```

**Comment by andreapavoni** [comment]
Thanks for the reply, that's what I've already did :-P I was wondering if there was another way ;-)

Thanks again!
