### ISSUE TITLE
Problems with belongs_to + custom primary keys + insert_all combination

### ISSUE THREAD

**Issue by Custodia** [elixir-ecto/ecto#1941]
I have two schemas with custom primary keys and a belongs_to relation:

```
defmodule BudgetingElixir.Schemas.Account do
  use Ecto.Schema
  alias BudgetingElixir.Repo
  alias BudgetingElixir.Schemas.Account
  alias BudgetingElixir.Schemas.AccountType

  @primary_key {:name, :string, autogenerate: false}

  schema "accounts" do
    field :description, :string
    field :on_budget, :boolean
    field :closed, :boolean
    belongs_to :type, AccountType, references: :name, type: :string
  end
end
```

```
defmodule BudgetingElixir.Schemas.AccountType do
  use Ecto.Schema
  alias BudgetingElixir.Repo
  alias BudgetingElixir.Schemas.AccountType

  @primary_key {:name, :string, autogenerate: false}

  schema "account_types" do
    field :default_on_budget, :boolean
  end

end
```

Repo.insert works fine but when I try to Repo.insert_all the data gets inserted and then I get this error:

```
** (UndefinedFunctionError) function :assoc.type/1 is undefined (module :assoc is not available)
    :assoc.type({:assoc, %Ecto.Association.BelongsTo{cardinality: :one, defaults: [], field: :type, on_cast: nil, on_replace: :raise, owner: BudgetingElixir.Schemas.Account, owner_key: :type_id, queryable: BudgetingElixir.Schemas.AccountType, related: BudgetingElixir.Schemas.AccountType, related_key: :name, relationship: :parent, unique: true}})
    (ecto) lib/ecto/type.ex:655: Ecto.Type.adapter_dump/3
    (ecto) lib/ecto/repo/schema.ex:695: Ecto.Repo.Schema.dump_field!/6
    (ecto) lib/ecto/repo/schema.ex:109: anonymous fn/5 in Ecto.Repo.Schema.init_mapper/2
    (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map_reduce/3
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1772: Enum.map_reduce/3
    (ecto) lib/ecto/repo/schema.ex:86: anonymous fn/5 in Ecto.Repo.Schema.extract_header_and_fields/4
```

Sounds like a bug to me since insert works fine and insert_all actually does what it's supposed to before throwing.

Here's a commit that this can be tested on:

https://github.com/Custodia/BudgetingElixir/commit/f8afcb18985d6393eb7eab2eb8243dca37fd47f4

**Comment by Custodia** [comment]
I immediately noticed I'm a bit mistaken. I can insert and insert_all AccountTypes.

I can also insert Accounts but I can't get them with all and if I try insert_all I get the error above. What I would expect is that if there is something wrong with Account schema insert would also throw.

**Comment by Custodia** [comment]
I was a bit mistaken, AccountTypes works as expected. Accounts however does not error on `insert` but on `insert_all` throws that weird error.

**Comment by Custodia** [comment]
Doesn't seem to be what I thought it was, I'll go ask in google groups

**Comment by josevalim** [comment]
Reopening this because in one way or the other the error message above is unacceptable. :) If you can provide a simple app that reproduces the issue, it will make my life much much easier. Thank you!

**Comment by Custodia** [comment]
Yeah so the custom primary keys had nothing to do with this :D I had chosen :type as the belongs_to column name which made it look like a bug with macros. The differences between insert and insert_all seem very unintuitive to me and they aren't really explained in the docs.

Here's a commit that this can be tested on:

https://github.com/Custodia/BudgetingElixir/tree/use_integer_id

From db app run `run mix ./priv/repo/seeds.ex`

**Comment by josevalim** [comment]
@Custodia we mention [the differences here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L501-L509) but at the moment it does not include differences regarding association handling. We will update that when we improve the error message.

**Comment by Custodia** [comment]
It doesn't mention for example that update_all will not take structs. It does say it takes a map in the params but structs are also maps so it's an easy mistake to make.
