### ISSUE TITLE
Ensure pool configuration can be set dynamically in init/2

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1953]
@fishcakez I will ping you to figure out how to move from `__pool__` to ets or app environment configuration.

**Comment by michalmuskala** [comment]
We should look into making the adapter the only compile-time config. All the other things, should be configurable at runtime.

If we achieve this, I think we should move the adapter setting to repo, to make it more obvious that this is bound at compile-time:

```elixir
defmodule MyAppRepo do
  use Ecto.Repo, otp_app: :my_app, adapter: Ecto.Adapters.Postgres
end
```

**Comment by josevalim** [comment]
@michalmuskala that's the plan and I think the `__pool__` is the last configuration left.

**Comment by josevalim** [comment]
The registry is a perfect solution for this.

**Comment by michalmuskala** [comment]
I'm not sure I see, how that would look like. Could you elaborate?

**Comment by josevalim** [comment]
@michalmuskala when the repo supervisor starts, it registers its pool configuration under the registry. If that process crashes by any chance, the registry will automatically clean it up.
