### ISSUE TITLE
has_one association error on delete

### ISSUE THREAD

**Issue by renanoronfle** [elixir-ecto/ecto#1954]
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.0
postgres (PostgreSQL) 9.6.1
ecto 2.1.3
postgrex 0.13.0
MacOS Sierra

Hello, I have a phoenix project with ecto1, Im trying to update to ecto2.

Everything worked fine except one feature, when I try to delete my has_one association I got an error:
no case clause matching: :raise

I followed this blog post:
http://blog.plataformatec.com.br/2015/08/working-with-ecto-associations-and-embeds/

This error happens only with has_one association, when I change to has_many (like describbed in blog post) it works.

I think it happens because in has_one association the method on_repo_change is called and there raises the error.

**Comment by josevalim** [comment]
Can you lease post the full error message with stacktrace?

**Comment by renanoronfle** [comment]
`rollback []
[info] Sent 500 in 3507ms
[error] #PID<0.491.0> running TestAssoc.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /posts/4
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: :raise
        (ecto) lib/ecto/association.ex:515: Ecto.Association.Has.on_repo_change/4
        (ecto) lib/ecto/association.ex:372: Ecto.Association.maybe_replace_one!/5
        (ecto) lib/ecto/association.ex:315: Ecto.Association.on_repo_change/6
        (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/association.ex:293: Ecto.Association.on_repo_change/3
        (ecto) lib/ecto/repo/schema.ex:617: Ecto.Repo.Schema.process_children/4
        (ecto) lib/ecto/repo/schema.ex:684: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
        (test_assoc) web/controllers/post_controller.ex:45: TestAssoc.PostController.update/2
        (test_assoc) web/controllers/post_controller.ex:1: TestAssoc.PostController.action/2
        (test_assoc) web/controllers/post_controller.ex:1: TestAssoc.PostController.phoenix_controller_pipeline/2
        (test_assoc) lib/test_assoc/endpoint.ex:1: TestAssoc.Endpoint.instrument/4
        (test_assoc) lib/phoenix/router.ex:261: TestAssoc.Router.dispatch/2
        (test_assoc) web/router.ex:1: TestAssoc.Router.do_call/2
        (test_assoc) lib/test_assoc/endpoint.ex:1: TestAssoc.Endpoint.phoenix_pipeline/1
        (test_assoc) lib/plug/debugger.ex:123: TestAssoc.Endpoint."call (overridable 3)"/2
        (test_assoc) lib/test_assoc/endpoint.ex:1: TestAssoc.Endpoint.call/2`

**Comment by renanoronfle** [comment]
I create one project if you want to seed: 
https://github.com/renanoronfle/test_assoc

Run seed and enter in url: /posts, edit and try delete a comment

**Comment by josevalim** [comment]
Fixed on master and v2.1. Thank you so much for a mechanism to reproduce this!
