### ISSUE TITLE
Typo in documentation of lib/ecto/changeset.ex

### ISSUE THREAD

**Issue by WernerBuchert** [elixir-ecto/ecto#1955]
Typo in documentation of lib/ecto/changeset.ex:

Line 366:

      iex> changeset = cast(post, %{title: "Hello"}, [:title])
      iex> new_changeset = cast(changeset, %{title: "Foo", body: "Bar"}, [:body])
      iex> new_changeset.params
      %{"title" => "Foo", "body" => "Bar"}

Shouldn't it be this?
%{"title" => "Hello", body: "Bar"}

**Comment by josevalim** [comment]
The parameters are always merged over, you may choose to accept those parameters as a change or not. In other words, the third argument only affects the `:changes` and not `:params`.

**Comment by WernerBuchert** [comment]
Sorry, it's new_changeset.params not new_changeset.changes, I'm really stupid.
