### ISSUE TITLE
Consider adding an example on how to select an additional field

### ISSUE THREAD

**Issue by kuon** [elixir-ecto/ecto#1957]
I think we should add an example to `Ecto.Query.select` for selecting an additional field, like so:

`from d in Document, select: %{d | somefield: 42}`

Where `somefield` is declared as virtual in the schema.

It might seem obvious, but it took me a really long time to find out and I think it's a common enough use case.

**Comment by josevalim** [comment]
@kuon can you please send a pull request? Where did you try looking for it? We should probably add it as part of `Ecto.Query.select`?

**Comment by kuon** [comment]
I'll do a PR.

**Comment by kuon** [comment]
Actually, I just noticed that 9ad38bdf1ea6605311a472930530de22eacacefc added an example that I didn't notice at first. I think it's enough to get it.
