### ISSUE TITLE
Ecto.Adapters.SQL.query! a Postgres function returns function's name as column

### ISSUE THREAD

**Issue by sntran** [elixir-ecto/ecto#1976]
### Environment

* Elixir version (elixir -v): 1.4.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): (PostgreSQL) 9.5.3
* Ecto version (mix deps): ecto 2.1.3 (Hex package)
* Database adapter and version (mix deps): postgrex 0.13.1 (Hex package)
* Operating system: Mac OS X 10.12.2

### Current behavior

With the following function:

```sql
CREATE OR REPLACE FUNCTION search_people(q text)
RETURNS SETOF person
AS $$
  SELECT person.*
  FROM person as person
  WHERE (
    to_tsvector('simple', unaccent(person.given_name)) ||
    to_tsvector('simple', unaccent(COALESCE(person.additional_name, ''))) ||
    to_tsvector('simple', unaccent(COALESCE(person.family_name, ''))) ||
    to_tsvector(person.language::regconfig, unaccent(COALESCE(person.about, '')))
  ) @@ to_tsquery(q);
$$ LANGUAGE sql STABLE;
```

When trying to run:

```elixir
Ecto.Adapters.SQL.query!(Repo, "SELECT search_people($1)", [query])
```

The return is:

```elixir
%Postgrex.Result{columns: ["search_people"], command: :select,
 connection_id: 10492, num_rows: 2, rows: [...]}
```

### Expected behavior

The Postgres function `all_people/1` returns a set of `person` rows.

As a database user, I expect the `columns` will contain all column of `person` table. Otherwise, I can't really use `Repo.load/2` to map to my struct, unless I use a query like this: `SELECT p.* FROM search_people($1) as p`

However, I am not sure whether Ecto can or should handle that. Thought?

**Comment by josevalim** [comment]
That's what the database is returning us, so I don't believe there is anything Ecto (or Postgrex) could do here.
