### ISSUE TITLE
Defunct module reference in SQL adapter documentation

### ISSUE THREAD

**Issue by christhekeele** [elixir-ecto/ecto#1979]
I'm just getting around to playing with Ecto internals, so I'm not yet sure how this should be corrected, but the `Ecto.Adapters.SQL` docs [reference a non-existent `Ecto.Adapters.SQL.Query` module](https://github.com/elixir-ecto/ecto/blob/637858fc02bd0e9dc1fc5f640fafa045b78eecf2/lib/ecto/adapters/sql.ex#L10).

**Comment by josevalim** [comment]
Done, thank you! https://github.com/elixir-ecto/ecto/commit/d8371fd7071c98235abbcce6bac401505c1abd23
