### ISSUE TITLE
Allowing subquery not only for :all

### ISSUE THREAD

**Issue by vstavskyi** [elixir-ecto/ecto#1983]
Example

ccc = 1
subquery = from a in "aaa", select: a.bbb, where: a.bbb = ^ccc
Repo.delete_all(from b in subquery(subquery))
{:query, 'DELETE FROM (SELECT e0.bbb bbb FROM aaa e0 WHERE (e0.bbb = :1)) s0', 1}

**Comment by michalmuskala** [comment]
I'm not sure I understand. In general databases require that `DELETE FROM` is followed by a table name, and not by an expression. For postgres: https://www.postgresql.org/docs/9.1/static/sql-delete.html

>```
>[ WITH [ RECURSIVE ] with_query [, ...] ]
>DELETE FROM [ ONLY ] table [ * ] [ [ AS ] alias ]
>    [ USING using_list ]
>    [ WHERE condition | WHERE CURRENT OF cursor_name ]
>    [ RETURNING * | output_expression [ [ AS ] output_name ] [, ...] ]
>```
>[...]
>**table**
>The name (optionally schema-qualified) of the table to delete rows from. If ONLY is specified before the table name, matching rows are deleted from the named table only. If ONLY is not specified, matching rows are also deleted from any tables inheriting from the named table. Optionally, * can be specified after the table name to explicitly indicate that descendant tables are included.

Also - please use the issue template.

**Comment by vstavskyi** [comment]
Oracle supports numerous features that extend beyond standard SQL. If you are concerned with the portability of your super ecto to other implementations of SQL, then you may want to take off some restrictions.

**Comment by josevalim** [comment]
@vstavskyi we are OK with supporting such features as long as there is a use case and someone interested on working on that. Is there are current adapter for Oracle?

**Comment by vstavskyi** [comment]
I hope first version will be next week https://github.com/erlangbureau/jamdb_oracle

**Comment by josevalim** [comment]
@vstavskyi oh, that context would have been helpful. :) Are you running our integration test suite as well?

**Comment by vstavskyi** [comment]
Not yet. I'm a beginner in ecto.

**Comment by josevalim** [comment]
@vstavskyi got it :)
