### ISSUE TITLE
Fix HexDocs for Ecto.Migration "drop constraint()"

### ISSUE THREAD

**Issue by erickipnis** [elixir-ecto/ecto#1987]
For: https://hexdocs.pm/ecto/Ecto.Migration.html#drop/1

### Current behavior
Currently the docs include the following example:

drop constraint(:products, name: "price_must_be_positive")

This throws an error when running a rollback on a migration:

** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[name: "price_must_be_positive"]

### Expected behavior

Removing the "name:" property fixes the issue. Perhaps we can change the docs to show:

drop constraint(:products, "price_must_be_positive") or at least indicate the "name:" property isn't needed in the actual function call.

**Comment by josevalim** [comment]
Thank you. It is fixed in master.
