### ISSUE TITLE
postgres adapter: cannot load `<<1::size(1)>>` as type :boolean

### ISSUE THREAD

**Issue by SxDx** [elixir-ecto/ecto#1994]
### Environment

* Elixir version: **1.4.2**
* Database and version: **PostgreSQL 9.6**
* Ecto version: **2.1.4**
* Database adapter and version: **postgrex 0.13.2**
* Operating system: **macOS 10.12.3, CentOS 7**

### Current behavior
When trying to use an postgres `bit(1)` field as `boolean` the following exception is raised:

```
* (ArgumentError) cannot load `<<1::size(1)>>` as type :boolean for :published in schema Hydra.Housing.Hotel
        (ecto) lib/ecto/schema.ex:1418: Ecto.Schema.load!/5
        (ecto) lib/ecto/schema.ex:1399: Ecto.Schema.__load__/5
        (ecto) lib/ecto/schema.ex:1371: Ecto.Schema.__load__/6
        (ecto) lib/ecto/adapters/sql.ex:582: anonymous fn/4 in Ecto.Adapters.SQL.process_row/4
        (elixir) lib/enum.ex:1325: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/adapters/sql.ex:579: Ecto.Adapters.SQL.process_row/4
        (postgrex) lib/postgrex/query.ex:77: DBConnection.Query.Postgrex.Query.decode_map/3
        (postgrex) lib/postgrex/query.ex:64: DBConnection.Query.Postgrex.Query.decode/3
        (db_connection) lib/db_connection.ex:1010: DBConnection.decode/6
        (ecto) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.prepare_execute/5
        (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
        (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:76: Ecto.Repo.Queryable.one!/4
        (hydra) lib/hydra/web/controllers/hotel_controller.ex:14: Hydra.Web.HotelController.show/2
        (hydra) lib/hydra/web/controllers/hotel_controller.ex:1: Hydra.Web.HotelController.action/2
        (hydra) lib/hydra/web/controllers/hotel_controller.ex:1: Hydra.Web.HotelController.phoenix_controller_pipeline/2
        (hydra) lib/hydra/web/endpoint.ex:1: Hydra.Web.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
```

### Expected behavior

The Postgres adaper should convert `bit(1)`to `boolean`as the mysql adapter already does (implemented in #1366 #1367 #1368 #1369 ) 
Postgrex represents `bit(1)` as `<<1::size(1)>>` and `<<0::size(1)>>`

Would a similar implementation to the mysql adapter work for postgres? 
If so I can send a pull request.

**Comment by ericmj** [comment]
Why are you using bit(1) for booleans in your database instead of the actual boolean type. The postgres driver is correct here because it's handling the types as the database is intending.

If you want to override this behaviour postgrex supports custom extensions where you can implement your own encoding/decoding https://hexdocs.pm/postgrex/Postgrex.Extension.html#content.

**Comment by josevalim** [comment]
Since you are using Ecto, you can also implement a custom Ecto type instead of a Postgrex extension. You can call it BitBoolean or something. The reason Mariaex uses bit is because afaik it does not have an actual boolean type. Or it is a tinyint or a bit.

**Comment by SxDx** [comment]
@ericmj Didn't think it would be relevant for the question but I access a legacy mysql database through Postgres using a Foreign Data Wrapper. Obviously would not use bit(1) for boolean otherwise. 

@josevalim Thanks for the hint.
