### ISSUE TITLE
Fix document on has_many's on_replace option

### ISSUE THREAD

**Issue by xfumihiro** [elixir-ecto/ecto#1995]
[https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3](https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3)
> May be :raise (default), :mark_as_invalid, :nilify, :update, or :delete

should be

> May be :raise (default), :mark_as_invalid, :nilify or :delete

according to
[https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3)

btw, why is the update option not supported?

**Comment by josevalim** [comment]
Update option is only supported on `has_one`, since we don't need an ID to know what we are updating. I will fix it on master, thank you.

**Comment by josevalim** [comment]
Fixed on master.

**Comment by KalvinHom** [comment]
Hi @josevalim, is there a reason why `has_many` can't support `:update` if the related records have their ID included?  

Noticed this as an issue because it makes auditing the children records harder since they get deleted/recreated every time.

**Comment by josevalim** [comment]
@KalvinHom the on_replace option only applies when the ID is not included. If the ID is included, then we are always updating, never replacing.
