### ISSUE TITLE
UUID.cast should treat upper- and mixed-case UUIDs as invalid

### ISSUE THREAD

**Issue by Dremora** [elixir-ecto/ecto#1999]
### Environment

* Elixir version (elixir -v): 1.4.2
* Ecto version (mix deps): ecto 2.1.4
* Operating system: macOS 10.12.3

### Current behavior

```
UUID.cast("20d935d2-1630-487B-9b5d-38dDd3c5d88A")
```
returns
```
{:ok, "20d935d2-1630-487B-9b5d-38dDd3c5d88A"}
```

### Expected behavior

According to [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), only lowercase characters are allowed in the canonical format. I would expect the code above to return `:error`.
Perhaps normalization (automatically converting to lowercase) is the way to go? But then should the dashes be also automatically added if missing?

**Comment by josevalim** [comment]
You are right. PR please?

**Comment by Dremora** [comment]
Onto it!
