### ISSUE TITLE
Suggestion: Add Support For Drop Foreign Key

### ISSUE THREAD

**Issue by ardhitama** [elixir-ecto/ecto#2004]
### Environment

* Elixir version (elixir -v): 
  Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
  Elixir 1.4.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
   mysqld  Ver 5.7.17-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))
* Ecto version (mix deps):
   ecto 2.1.4
* Database adapter and version (mix deps):
   mariaex 0.8.1
* Operating system:
   Ubuntu 16.04.2 LTS

### Current behavior

Dropping foreign key constraint using `execute/1`

### Expected behavior

Dropping foreign key constraint using  `drop foreign_key(...)`

**Comment by josevalim** [comment]
We have decided to not have to support all constructs in the migration syntax but rather make execute more flexible. See #1993.
