### ISSUE TITLE
Do not save empty embeds

### ISSUE THREAD

**Issue by zimt28** [elixir-ecto/ecto#2009]
### Current behavior

When using `embeds_one :thing, Thing` with Phoenix.HTML's `inputs_for`, a `%Thing{id: "UUID", foo: "", bar: ""}` will be saved with no values, when there's no actual input, even though `foo` or `bar` have validation rules that wouldn't allow empty strings.

### Expected behavior

When the params for the resource aren't given, `null` should be saved instead, alternatively an option to make sure Ecto doesn't save empty resources.

**Comment by josevalim** [comment]
This is what we want to support as part of #1857. Allow you to say the changeset should be ignored. So I will close this as a dup, thank you!

**Comment by zimt28** [comment]
@josevalim Thanks, didn't see that. Is there a good workaround? I've tried the following, it works fine but also makes `inputs_for` not show the field anymore when the action fails:

```elixir
defp remove_if_empty(changeset, field) do
  case get_field(changeset, field) do
    %{field: nil} ->
      put_embed(changeset, field, nil)
    _ ->
      changeset
  end
end
```

**Comment by josevalim** [comment]
Currently the only option is to do another pass on the changeset, after you
call cast_embed, getting all entries in changeset.changes, removing the
invalid ones, and calling put_embed with the remaining ones.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
