### ISSUE TITLE
`usec` timestamps option is not honoured on MySQL migration

### ISSUE THREAD

**Issue by bernardd** [elixir-ecto/ecto#2012]
When a column is specified as `utc_datetime` or `native_datetime` in a migration, having `usec: true` does not cause the creation of a `datetime(6)` type column, but rather a plain `datetime`. In mysql 5.7 (which supports sub-second resolution) the latter truncates sub-second values (while the former preserves the sub-second information).

Now this may be intentional - there's a note about usecs in the mysql adapter, but it just notes differences between versions and advises that we consult the documentation :) I can't see any "right" way to get the appropriate type set on the column beyond hardcoding some raw SQL into the migration.

### Environment

* Elixir version: 1.4.1
* Database and version: MySQL 5.7
* Ecto version: 2.1.4
* Database adapter and version: mariaex 0.8.1
* Operating system: Ubuntu 16.04

**Comment by josevalim** [comment]
Yes, the best is to update the usec notes about MySQL and say they can
explicitly pass "datetime(6)" type in migrations.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by bernardd** [comment]
Is there a way to specify that as part of a "normal" Ecto type declaration? In particular I want to use it for the `timestamps()` shortcut to add `created_at` and `updated_at`, but I can't just set:

`@timestamps_opts [type: "datetime(6)"]`

**Comment by josevalim** [comment]
You do not define it as part of your schema but rather as part of migrations. There you can do:

    add :created_at, :datetime, size: 6

I am not sure if `timestamps(size: 6)` in migrations is supported. If not, we should.

**Comment by bernardd** [comment]
> I am not sure if timestamps(size: 6) in migrations is supported. If not, we should.

A quick test suggests it's not supported. I might take a stab at getting that working. Thanks very much for the pointers.

**Comment by bernardd** [comment]
A more correct test suggests it is in fact supported, just not as part of the @timestamps_opts attribute :) So I've just updated the docs to explain it. The PR is #2013. Thanks very much for your help :)

**Comment by josevalim** [comment]
I will keep this open though because I think we can do a better job here.

**Comment by josevalim** [comment]
Closing it in favor of #2018.
