### ISSUE TITLE
Insert nil values on upsert

### ISSUE THREAD

**Issue by alex88** [elixir-ecto/ecto#2017]
### Environment

* Elixir version (elixir -v): 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 2.2.0-dev a1746d5
* Database adapter and version (mix deps): postgrex 0.13.1
* Operating system: OSX 10.12.3

### Current behavior

Upserting a model with a `nil` value doesn't set that field to `nil`:

```
insert_category = Map.merge(%App.Category{parent_id: parent_id}, category) |> IO.inspect
App.Repo.insert!(insert_category, on_conflict: :replace_all, conflict_target: :identifier)
```

this shows:

```
%App.Category{__meta__: #Ecto.Schema.Metadata<:built, "categories">,
 ... other values ...
 parent: #Ecto.Association.NotLoaded<association :parent is not loaded>,
 parent_id: nil}

20:02:38.734 [debug] QUERY OK db=0.2ms
INSERT INTO "categories" ("disabled","filters","identifier","name","order_by") VALUES ($1,$2,$3,$4,$5) ON CONFLICT ("identifier") DO UPDATE SET "disabled" = EXCLUDED."disabled","filters" = EXCLUDED."filters","identifier" = EXCLUDED."identifier","name" = EXCLUDED."name","order_by" = EXCLUDED."order_by" [false, [%{id: "damaged", label: "Damaged", type: "boolean", values: [true, false]}, %{id: "refurbished", label: "Refurbished", type: "boolean", values: [true, false]}], "cell-phones-accessories", "Cell phones & Accessories", []]
```

as `parent_id` is `nil`, it's not being inserted to the database, this could be ok for the default inserting behavior as a nil value would be whatever the db default is, but while upserting, we want to be sure that value is `nil`, otherwise if the db has a value already, there is no way to set it to nil except using `on_conflict: [set: [fields...]]`

### Expected behavior

The upsert query specifies also the `nil` values to null the values on the db

**Comment by josevalim** [comment]
Does it work if you use a changeset? Without a changeset we will always
have to guess the changes, I don't think we can fix this.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by alex88** [comment]
Sorry for the delay, I think it would work if I update, but with insert it doesn't (even with a changeset), maybe `:replace_all` should include nil values when set?

**Comment by josevalim** [comment]
@alex88 can you please show the code you are trying with changeset?

**Comment by josevalim** [comment]
I could not reproduce this locally. Please let us know if you have more information. Thank you.

**Comment by nietaki** [comment]
For future archeologists: This issue is being worked on here: https://github.com/elixir-ecto/ecto/issues/2474

**Comment by edgurgel** [comment]
@nietaki, thanks for posting the connected issue 👍
