### ISSUE TITLE
Introduce usec types

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2018]
Since we migrated to Elixir built-in types, issues are starting to surface on how Ecto handles microseconds.

Those issues comes from the fact that database adapters do not cover the difference in precision that exists in Elixir. Leading to issues described in #1935.

Furthermore, databases may require different types for usec and non-usec, such as MySQL in #2012.

One solution to this problem is to introduce `:naive_datetime_usec` and `:utc_datetime_usec`. Those types can be used in migrations, explicitly tackling MySQL issues, and will guarantee on casting/dumping/loading that the microseconds precision is always 6, mirroring the database behaviour. The current `:naive_datetime` and `:utc_datetime` will discard the microsecond values, both on cast, dumping and loading.

The downside of this solution is the multiplicity of times but, given the difference in behaviour, it seems more explicit then passing `usec: true` everywhere (which even though is not enough to solving all issues above).

Thoughts?

/cc @michalmuskala @wojtekmach @lau

**Comment by lau** [comment]
I like the idea. Isn't `usec: true` default now for :utc_datetime? How about instead of changing that, adding `:utc_datetime_no_subsecond` (just an example name) for datetimes with no sub second precision? Ie. instead of renaming the current type and adding a new one without subseconds, we add a new type with subseconds. I'm not 100% set on what I think would be best of the two, but want to hear opinions on it.

**Comment by lau** [comment]
The shorter name (`utc_datetime`) is the default and will possibly seen as the default vs a new option with a longer name.

If you want to throw away as little data as possible by default, that would suggest having the default option saving the microseconds.

**Comment by josevalim** [comment]
`usec: true` is not the default. Plus it also won't work in many databases.

**Comment by lau** [comment]
I must have been reading the docs about the `timestamps_opts` where `usec: true` is the default. Was this a change of defaults? How is the  `timestamps_opts` with `usec: true` default working with MySQL? Does it work with MySQL 5.7?

For people using Postgres I think not throwing away the microseconds is the best default. But of course Ecto has to work with MySQL too. Could MySQL users using an old version of MySQL use a `:utc_datetime_no_subsecond` type after upgrading to a new minor release?

**Comment by josevalim** [comment]
@lau you are correct, we changed the default to usec: true. It works with MySQL because the current types all have arbitrary precision, like the Elixir types. If we introduce two new types, then I would like them to always have precision of 6 or 0, and then using 6 will be incorrect for MySQL and using 0 may lead to truncation for PostgreSQL.

The good news though is that it is easy to change the defaults for your app because of @timestamp_opts.

**Comment by lau** [comment]
👍 I think :naive_datetime_usec and :utc_datetime_usec (vs. changing :utc_datetime and :naive_datetime to have usec) makes sense given factors such as the preference for compatability with MySQL and other databases.

It would be nice if it was made obvious in the documentation that if you use Postgres then the -`_usec` types make sense. Also in Phoenix where the default is postgres maybe it makes sense in generators to use the usec version. And document that you can change it to the non-usec version if you use MySQL.

**Comment by josevalim** [comment]
Unfortunately we cannot do any of the changes above in a backwards incompatible fashion. So they will be scheduled to 3.0 which will give us the opportunity to finally get rid of the old types and also make sure databases return the new types exclusively.

**Comment by josevalim** [comment]
I have removed the old datetime types from Ecto master and I have removed the usec precision from `:time`, `:naive_datetime` and `:utc_datetime`.

The work that is left to do is to introduce the types `:time_usec`, `:naive_datetime_usec` and `:utc_datetime_usec` and make sure they are respected in migrations. We should also check if `datetime_add` works with the usec ones (see integration_test/cases/interval.exs) or if we need to introduce a specific `datetime_usec_add`.

**Comment by wojtekmach** [comment]
Per:

> One solution to this problem is to introduce :naive_datetime_usec and :utc_datetime_usec. Those types can be used in migrations, explicitly tackling MySQL issues, and will guarantee on casting/dumping/loading that the microseconds precision is always 6, mirroring the database behaviour.

@josevalim I tried this on Elixir master:

```elixir
iex> changeset = Ecto.Changeset.cast({%{}, %{x: :naive_datetime_usec}}, %{x: "2018-01-01 09:00:00.00"}, [:x])
iex> changeset.changes.x
~N[2018-01-01 09:00:00.00]
```

and I think it should be casted to: `~N[2018-01-01 09:00:00.000000]`, can you verify? I can work on a fix.

**Comment by josevalim** [comment]
I think the usec means maximum precision. So I think the behavior is
correct?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
@josevalim I wrote following integration test on pg:

```elixir
    created = TestRepo.insert!(%Article{published_at: ~N[2018-01-01 09:00:00.000]})
    assert created.published_at == ~N[2018-01-01 09:00:00.000]
    loaded = TestRepo.get!(Article, created.id)
    assert loaded.published_at == ~N[2018-01-01 09:00:00.000
```

and it fails which I expected:

```
  1) test decimal type (Ecto.Integration.TypeTest)
     integration_test/cases/type.exs:253
     Assertion with == failed
     code:  assert loaded.published_at() == ~N"2018-01-01 09:00:00.000"
     left:  ~N[2018-01-01 09:00:00.000000]
     right: ~N[2018-01-01 09:00:00.000]
     stacktrace:
       integration_test/cases/type.exs:276: (test)
```

it fails on mysql differently which is probably a bug:

```
  1) test decimal type (Ecto.Integration.TypeTest)
     integration_test/cases/type.exs:253
     Assertion with == failed
     code:  assert loaded.published_at() == ~N"2018-01-01 09:00:00.000"
     left:  ~N[2018-01-01 09:00:00]
     right: ~N[2018-01-01 09:00:00.000]
     stacktrace:
       integration_test/cases/type.exs:276: (test)
```

---

I was thinking about casting `09:00:00.000` to `09:00:00.000000` to have a contract like whatever we casted and inserted we get back from DB as exactly the same - or we are not making such guarantees and instead folks should explicitly do `read_after_write` in certain scenarios.
```

**Comment by josevalim** [comment]
If the database adds the precision then I agree we should add any missing
precision on cast.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by clouds56** [comment]
Is there any way to configure usec type globally not? like what [CHANGELOG](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#calendar-types) saying.
I tried `migration_timestamps` and without luck.

**Comment by josevalim** [comment]
@clouds56 migration_timestamps should work. if not, please open up an issue report following the issue template, include versions and steps to reproduce. Thanks!
