### ISSUE TITLE
Support for infinity in postgres dates

### ISSUE THREAD

**Issue by makkrnic** [elixir-ecto/ecto#2019]
### Current behavior

In current implementation, when postgres returns infinity, it is transformed - positive infinity "works" because its number of days is supported by erlang's `:calendar.gregorian_days_to_date/1`, but negative infinity breaks things because `:calendar.gregorian_days_to_date/1` doesn't accept negative dates.

### Expected behavior

Return either fixed number, tuple or something else consistent.

A (very) naive approach can be seen at papagenocms/ecto@d4a8e9a

src: lib/ecto/adapters/postgres/datetime.ex:49

**Comment by josevalim** [comment]
We recommend you to build your own Postgrex extension then because even if we change it in the adapter level, building a DateTime or NaiveDateTime later on will also fail, as they don't support such dates. Documentation for custom extensions can be found in Ecto.Adapters.Postgres.

**Comment by makkrnic** [comment]
Thank you for such prompt response and a suggestion. I will try that.
