### ISSUE TITLE
Autogenerated binary id with upsert on_conflict: :nothing

### ISSUE THREAD

**Issue by camcaine** [elixir-ecto/ecto#2025]
### Environment

* Elixir version: 1.4.1
* Database: PostgreSQL 9.5.3
* Ecto version: 2.1.4
* Database adapter: postgrex 0.13.2
* Operating system: OSX 10.11.6

### Current behavior

A new binary id is generated when using `on_conflict: :nothing` for upserts, making it harder to check the `:id` for `nil` when `on_conflict: :nothing` comes into play (as per the docs).

###### Example:

`Participation` schema with unique index on `[:game_id, :user_id]`

```
@primary_key {:id, :binary_id, autogenerate: true}
@foreign_key_type :binary_id

schema "participations" do

  belongs_to :game, Game
  belongs_to :user, User

  timestamps()
end
```

Callsite:

```
def add_participant(%Game{} = game, %User{} = user) do
  %Participation{game: game, user: user}
  |> Repo.insert(on_conflict: :nothing)
end
```

Failed test:

```
test "upserts the participant", %{game: game, user: user} do
  # Insert participation once
  {:ok, _} = Game.add_participant(game, user)

  # Upsert (would raise normally)
  assert {:ok, ignored} = Game.add_participant(game, user)
  assert ignored.id == nil
end
```

```
Assertion with == failed
     code:  ignored.id() == nil
     left:  "98e27c28-ba1e-46c4-a4f8-c8d66e84471a"
     right: nil
```

### Expected behavior

As per the docs for `Repo.insert/2`:

```
# Keep in mind that, although this returns :ok, the returned
# struct does not reflect the data in the database. For instance,
# in case of "on_conflict: :nothing", the returned post has no ID.
 {:ok, ignored} = MyRepo.insert(%Post{title: "this is unique"}, on_conflict: :nothing)
 assert ignored.id == nil
```

I'm guessing this is related to  `@primary_key {:id, :binary_id, autogenerate: true}` generating the uuid. 

But should this behaviour be inline with non-binary ids being `nil`?

**Comment by josevalim** [comment]
@camcaine unfortunately there is nothing we can do for auto generated values as databases do not give enough information on the upsert operation results. Your best option is to move the generation to the database and use `read_after_writes: true` to read the value of the field back after every operation.
