### ISSUE TITLE
@derive through Poison.Encoder not possible with :id, when :id is of type :binary_id

### ISSUE THREAD

**Issue by mrusme** [elixir-ecto/ecto#2026]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace] 
Elixir 1.4.2
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Cassandra 3.10 (via @vintikzzz's https://github.com/vintikzzz/cassandra_ecto)
* Ecto version (mix deps): `ecto 2.1.4`
* Database adapter and version (mix deps): `cassandra_ecto 0.4.1`
* Operating system: macOS 10.12.4

### Current behavior

Repo:
```
defmodule Myapp.Repo.Organization do
    use Ecto.Schema

    import Ecto.Query

    alias Myapp.Repo, as: Repo
    alias Myapp.Repo.Organization, as: Organization

    @primary_key {:id, :binary_id, autogenerate: true}
    @derive {Poison.Encoder, only: [:id, :name, :country_code]}
    schema "organizations" do
        field :name,    :string
        field :country_code,     :string
        timestamps()
    end

    def show(id) do
        Repo.get!(Organization, id)
    end
end
```

Controller:
```
                org = Organization.show(params[:id])

                conn
                |> put_status(200)
                |> json(org)
```

With this code, the Controller fails to return proper data back to the requesting client. The reason for that is the `:binary_id` (`:id`) which is a `BitString` and cannot be converted by `Poison.Encoder`. However, adding `IO.inspect Ecto.UUID.load(org)` before the `conn`-pipeline shows me, that it is a correct UUID string.

### Expected behavior

I would expect the entity to be derived into proper JSON. Ecto should provide a way for Poison.Encode to convert the `:binary_id` through Ecto.UUID or convert it to a string-type upfront.

### Workaround

The only workaround I found so far was to implement my own `Poison.Encode` functions which check for the key name (`id`) and perform an `Ecto.UUID.load()` before proceeding.

**Comment by josevalim** [comment]
Why do you have a bitstring in your struct? The struct should always keep
the loaded UUID. I would investigate from where the bitstring is coming
from.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by mrusme** [comment]
@josevalim thank you for the super-quick reply! Actually I don't know. As mentioned, I'm using the https://github.com/vintikzzz/cassandra_ecto adapter. The data is being pulled from Cassandra through that extension.

So, you're saying that Ecto (and its adapters) should always provide a string instead of a bitstring, even though it's defined as `:binary_id`?

**Comment by josevalim** [comment]
@mrusme I believe you are right since the adapter can keep it as a raw binary if it wants to. Maybe `{:id, Ecto.UUID, autogenerate: true}` would do the trick?

**Comment by mrusme** [comment]
@josevalim you're a genius, thanks! Indeed, setting `Ecto.UUID` instead of `:binary_id` did the trick. I will close this issue here and open a new one on https://github.com/vintikzzz/cassandra_ecto, to request a documentation change.

Thanks again!

**Comment by michalmuskala** [comment]
I would say this is a bug in the `binary_id` implementation of the adapter. 

The implementation seems to be missing the dumpers and loaders for `binary_id` type:
Compare the postgres/mysql implementation https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/sql.ex#L47-L54 with the adapter: https://github.com/vintikzzz/cassandra_ecto/blob/master/lib/cassandra_ecto/adapter.ex#L250-L261

**Comment by josevalim** [comment]
@michalmuskala good catch!
