### ISSUE TITLE
Unsigned INT Auto Increment Primary Key

### ISSUE THREAD

**Issue by ricking06** [elixir-ecto/ecto#2032]
Ecto do not has a INT which is unsigned and Auto increment at same time.

Im using `:serial` but then i cannot use "int unsigned".
And i want int unsigned auto increment

**Comment by michalmuskala** [comment]
Unsigned integer types are not SQL standard. Moreover, postgresql does not have unsigned integers at all.

If using MySQL, in migrations you can pass any type supported by the database as an atom - 
```elixir
crate :foo, primary_key: false do
  add :id, :"BIGINT UNSIGNED", prmary_key: true
end
```
---
Please use the elixir forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you.
