### ISSUE TITLE
Prefix option in `Repo.aggregate`?

### ISSUE THREAD

**Issue by brandonparsons** [elixir-ecto/ecto#2036]
Hi there,

It appears that there is no `prefix` option that can be passed to `Repo.aggregate`. Is this by design?

Is there a way to work around this, if I'm trying to use `Repo.aggregate` to realize the results of a query that requires searching within a given prefix?

**EDIT**

As a follow-up, it also seems I can't add a prefix in `Ecto.Query.subquery`, which is the first thing I tried to do to work around this :)

**Comment by michalmuskala** [comment]
This can definitely be supported. PR will be welcome :)

**Comment by brandonparsons** [comment]
Thanks. I was hoping to make sure I wasn't missing something completely obvious :)

I will have a look at the source to see if it's something I could take a crack at. If it involves actually hitting the SQL queries it will be outside of my ability. If it's munging & passing around options might be something I could do :)

**Comment by brandonparsons** [comment]
Turns out there was a better way to do this (in my case), so I'm going to close. Assuming nobody else is asking for this at the time being.
