### ISSUE TITLE
Migration error message when using composite type without specifying subtype

### ISSUE THREAD

**Issue by almielczarek** [elixir-ecto/ecto#2040]
### Environment

* Elixir version (elixir -v):
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): 0.13.2
* Operating system: Arch linux

### Current behavior

Given the following code:

```
defmodule EctoTest.Repo.Migrations.CreateTodoList do
  use Ecto.Migration

  def change do
    create table(:todo_list) do
      add :name, :string
      add :items, :array
    end
  end
end
```

Users are faced with this error:

```
18:18:18.790 [info]  == Running EctoTest.Repo.Migrations.CreateTodoList.change/0 forward

18:18:18.790 [info]  create table todo_list
** (Postgrex.Error) ERROR 42601 (syntax_error): syntax error at or near "array"
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

### Expected behavior

Perhaps the ecto adapters could do a validation and give an error message to users explaining how to fix their code such as: "When using a composite type (ie array), the database expects a subtype. For example: `add :items, {:array, :string}`

**Comment by ericmj** [comment]
It was mentioned in the other issue that the adapter can raise but I don't believe so because `array` is a valid type name: `CREATE TYPE "array";`

**Comment by josevalim** [comment]
@ericmj is right.

@almielczarek thanks for moving the issue here but I think there isn't anything we can do here. At least the decision is now properly documented. Thank you!
