### ISSUE TITLE
UUID.cast to allow binaries

### ISSUE THREAD

**Issue by rockwood** [elixir-ecto/ecto#2045]
### Environment

* Elixir version: 1.4.2
* Database and version: Postgres 9.6.1
* Ecto version: 2.1.4
* Database adapter and version: Postgrex 0.13.0
* Operating system: OSX 10.12.4

### Current behavior

I have a use case for manually generating binary UUIDs. Currently Ecto.UUID doesn't accept raw binaries even if they're valid 16 bytes. Is there any reason it shouldn't?

```elixir
defmodule File do
  use Ecto.Schema

  schema "files" do
    field :hash, Ecto.UUID, autogenerate: false
  end
end
```

```
> Repo.insert(%File{hash: :erlang.md5("file content")})
> ** (Ecto.ChangeError) value `<<209, 11, 76, 63, 241, 35, 178, 109, 192, 104, 212, 58, 139, 239, 45, 35>>` for `File.hash` in `insert` does not match type Ecto.UUID
      (ecto) lib/ecto/repo/schema.ex:699: Ecto.Repo.Schema.dump_field!/6
      (ecto) lib/ecto/repo/schema.ex:708: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
      (stdlib) lists.erl:1263: :lists.foldl/3
      (ecto) lib/ecto/repo/schema.ex:706: Ecto.Repo.Schema.dump_fields!/5
      (ecto) lib/ecto/repo/schema.ex:655: Ecto.Repo.Schema.dump_changes!/6
      (ecto) lib/ecto/repo/schema.ex:200: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
```

Digging into the UUID generate functions also yields some unexpected results:

```
> Ecto.UUID.generate() |> Ecto.UUID.cast()
{:ok, "ff7f95df-c6df-4743-a630-74069d82ac63"}
> Ecto.UUID.bingenerate() |> Ecto.UUID.cast()
:error
```

### Expected behavior

I'd expect Ecto.UUID to accept any valid 16 byte binary.

**Comment by josevalim** [comment]
Yes, please send a PR, but we should validate the UUID as well.

**Comment by rockwood** [comment]
@josevalim On it. Thanks!

**Comment by shulhi** [comment]
@rockwood you can actually do 
```
iex(1)> Ecto.UUID.bingenerate |> Ecto.UUID.load
{:ok, "867976c9-6d36-4f00-a6e5-2ecbbf38efda"}
```

**Comment by rockwood** [comment]
@shulhi Is there a reason why cast shouldn't accept a binary?
