### ISSUE TITLE
Deprecate Ecto.Date, Ecto.DateTime, Ecto.Time

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2058]
Since Ecto 2.1 we support the native elixir calendar types. Supporting both ecto types and elixir types is extremely confusing - it's not clear which ones are preferred and why it's duplicated. The new types provide superior usability and integrate seamlessly with the rest of elixir ecosystem through libraries such as calendar or timex.

I propose we deprecate the old types in 2.2 so that they emit a warning when used.

**Comment by josevalim** [comment]
Yes, that's the plan all along. I am actually surprised it was not deprecated yet. So good reminder!

**Comment by seanhandley** [comment]
@michalmuskala @josevalim I'd like to take a look at this as a way of starting out contributing. Would you mind writing a few lines of client code that demonstrate how Ecto currently works with both types and how it *should* work?

**Comment by seanhandley** [comment]
Also, what's the preferred method of deprecation warnings? I like the idea of a decorator:

```elixir
defmodule DeprecationDecorator do
  use Decorator.Define, deprecated: 0

  def deprecated(body, context) do
    IO.warn "Function #{context.module}.#{context.name}/#{context.arity} is deprecated."
    body
  end
end

defmodule Ecto.DateTime do
  use DeprecationDecorator

  @decorate deprecated
  def old_function_do_not_use() do
    # ...
  end
end
```

(Based on https://elixirforum.com/t/raise-warnings-during-compile-time/240/4).

**Comment by josevalim** [comment]
Sorry @seanhandley but I am almost done with those changes locally. Thanks for pinging though! :heart:

**Comment by seanhandley** [comment]
D'oh. Thanks anyway for the quick reply.

I'll look for another place to start...

**Comment by josevalim** [comment]
In master!
