### ISSUE TITLE
embeds_one does not work with read_after_writes

### ISSUE THREAD

**Issue by maxsalven** [elixir-ecto/ecto#2061]
### Environment

* Elixir version (elixir -v): 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.6.1
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): postgres 0.13.2
* Operating system: 10.12.4

### Current behavior

`embeds_one` does not work with `read_after_writes`. I have database level defaults for my JSONB field, and `Repo.insert()` returns `nil` for my `privacy` field.

`invalid option :read_after_writes for embeds_one/3`

```
embeds_one :privacy, Privacy, read_after_writes: true, primary_key: false, on_replace: :update do
  field :posts, :string
  field :profile, :string
end
```

**Comment by josevalim** [comment]
As the error says, we currently do not allow this option. If you are interested on this, I would recommend trying to send a pull request, as this feature is low priority for us. If you have any questions, please let us know!
