### ISSUE TITLE
Bad docs for Ecto.Repo.insert_or_update and Ecto.Repo.insert_or_update!

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#2063]
For both methods first parameter name is bad:
```elixir
insert_or_update(struct_or_changeset, opts)
insert_or_update(struct_or_changeset :: Ecto.Schema.t | Ecto.Changeset.t, opts :: Keyword.t) ::
  {:ok, Ecto.Schema.t} |
  {:error, Ecto.Changeset.t}
# and:
insert_or_update!(struct_or_changeset, opts)
insert_or_update!(struct_or_changeset :: Ecto.Schema.t | Ecto.Changeset.t, opts :: Keyword.t) ::
  Ecto.Schema.t |
  no_return
```
in description:
> Inserts or updates a **changeset** depending on whether the struct is persisted or not.

So we can pass only **changeset**.

This found forum user `Crowdhailer`, see [his topic](https://elixirforum.com/t/using-repo-insert-or-update-without-a-changeset/5099?u=eiji).
After looking deeper I also found:

Another fault in docs is result of example code:
> Please note that for this to work, you will have to load existing structs from the database. So even if the struct exists, this won’t work:
```elixir
struct = %Post{id: 'existing_id', ...}
MyRepo.insert_or_update changeset
# => {:error, "id already exists"}
```
`&MyRepo.insert_or_update/2` should return `{:error, changeset}` instead of `{:error, "description"}`.

**Comment by wojtekmach** [comment]
there's a test that ensures this behaviour so looks like indeed the arg names (and typespecs) need to be updated: https://github.com/elixir-ecto/ecto/blob/v2.1.4/test/ecto/repo_test.exs#L285:L289
