### ISSUE TITLE
Support map update syntax in subquery select statements

### ISSUE THREAD

**Issue by zachdaniel** [elixir-ecto/ecto#2064]
I'm looking into setting this up as we speak. 

It looks to me like its just the code that determines if something is a valid subquery select field that needs to be updated.

### Current behavior

When selecting in a subquery using map update syntax there is a pattern match failure somewhere.

The select statement ends up looking like this:
```
[{:|, [],
  [{:&, [], [0]},
   [average_accuracy: {{:., [], [{:&, [], [1]}, :average_accuracy]}, [], []}]]}]
```
The error we get is:
```
** (exit) an exception was raised:
    ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Query.Planner.subquery_fields/2
```

### Expected behavior

This functions as a valid select statement

**Comment by zachdaniel** [comment]
I'm starting to get other errors I wasn't expecting, so this issue might be premature.

**Comment by josevalim** [comment]
@zachdaniel can you please provide a full example of the query you want to compile?

**Comment by zachdaniel** [comment]
@josevalim, sure!  I should have included it in my earlier post but I was just being lazy.  Here is a trimmed down example that we have.

This looks a little silly once I've pared it down, but we want to start selecting calculated values early on in the pipeline so that we can easily sort/filter on those values later.  The simplest way I've found to do it in a way that doesn't mess with the rest of the system is to use map update syntax to override a key with the value in question.  This works because our resources are backed by views, so we just add a null column to the view, that(based on parameters) can be filled in in this early step or not.  The main reason we subquery this though has to do with our paginator that happens near the end of the pipeline.

```
  @spec query() :: Ecto.Queryable.t
  def query() do
    query = from assignment in MyApp.Assignment,
      left_join: stats in subquery(stats()),
      on: stats.id == assignment.id,
      select: %{assignment | average_accuracy: stats.average_accuracy}

    from query in subquery(query)
  end

  @spec stats() :: Ecto.Queryable.t
  defp stats() do
    from assignment in MyApp.Assignment,
      left_join: attempt in assoc(assignment, :attempts)
      group_by: assignment.id,
      select: %{
        id: assignment.id,
        total_accuracy: fragment("COUNT(?) FILTER (WHERE ? IS TRUE)", attempt.id, attempt.correct) / fragment("NULLIF(COUNT(?), 0)", attempt.id)
      }
  end

```

**Comment by zachdaniel** [comment]
I also just realized that most of that example is unnecessary. the only part that matters is where we `subquery/1`

**Comment by zachdaniel** [comment]
So I found a pretty hacky way of getting the behaviour we want. I can't imagine that it would be done this way if it was implemented in ecto, but since we have more guarantees about the shape of the query, I think this will work for us.

In the subquery we only select the value we care about, which puts it into a shape that the subquery expects. From what I can tell its basically an expression AST. Then this adds all of the original fields back into the query. I was a little surprised when this worked, but it did.

```
   @spec query() :: Ecto.Queryable.t
   def query() do
     query = from assignment in MyApp.Assignment,
       left_join: stats in subquery(stats()),
       on: stats.id == assignment.id,
       select: %{accuracy: stats.total_accuracy}

     with_all_schema_fields = add_all_schema_fields(query, MyApp.Assignment)

     from query in subquery(with_all_schema_fields)
   end

  @spec add_all_schema_fields(%Ecto.Query{}, module) :: %Ecto.Query{}
  def add_all_schema_fields(query = %{select: %{expr: current_select_expression}}, schema) do
    :fields
    |> schema.__schema__()
    |> add_all_fields(current_select_expression)
    |> update_select_expression(current_select_expression)
    |> update_query(query)
  end

  @spec update_select_expression(any, {any, any, any}) :: {any, any, any}
  def update_select_expression(new_fields, {current_select_expr_1, current_select_expr_2, _}), do: {current_select_expr_1, current_select_expr_2, new_fields}

  @spec update_query(any, %Ecto.Query{}) :: %Ecto.Query{}
  def update_query(new_select_expression, query = %{select: select_statement}), do: %{query | select: %{select_statement | expr: new_select_expression}}

  @spec add_all_fields([atom], {any, any, any}) :: any
  def add_all_fields(fields, {_, _, current_select_fields}) do
    Enum.reduce(fields, current_select_fields, fn field, select_expression ->
      Keyword.put(select_expression, field, {{:., [], [{:&, [], [0]}, field]}, [], []})
    end)
  end
```

**Comment by josevalim** [comment]
> but since we have more guarantees about the shape of the query, I think this will work for us

Actually you have no guarantees. :) The Ecto.Query struct is completely private. We may change how data is stored at any time and it may break your code in unexpected ways.

**Comment by zachdaniel** [comment]
Sorry, what I meant is that we knew that we only wanted to select the fields on the first binding, and didn't need to come up with a generic solution that works for all forms of queries. We are very heavily tested, so if we upgrade and something under the hood changes this behavior we will almost certainly know right away. Plus, after making a change like this we know we have to be hyper aware of the changes happening in Ecto.  Honestly, Ecto is such a critical part of our application architecture that it would be silly to think that we could just upgrade it without a comprehensive understanding of the changes.

**Comment by josevalim** [comment]
@zachdaniel well, Ecto is not supposed to break your code when you migrate from 2.0 -> 2.1 and then 2.1 -> 2.2 and so on. If it does, it is a bug. But when you reach for the internals like that, then we have no guarantees. But that is your choice. :)

**Comment by zachdaniel** [comment]
I totally understand and agree. Unfortunately, I haven't been able to come up with another solution that fits our needs, and we do need to have something working soon. With that said, my plan is to perhaps see if I can resolve this issue by contributing to Ecto, and then get rid of the hacky method. I took a stab at it, and made some good progress. 

From what I saw, it doesn't seem like anything should conceptually limit this from working, just that the patterns for verifying the select statement and loading the query haven't been set.

**Comment by zachdaniel** [comment]
@josevalim Thanks so much!

**Comment by zachdaniel** [comment]
@josevalim 

Let me know if this should be a separate issue.

I'm noticing that type information is not maintained when selecting using map update syntax.

```
correct_types = from a in Mandark.V2.Assignment, select: %{a | template: true}, limit: 1
incorrect_types = from sub in subquery(correct_types)

correct_types
|> Repo.one
|> Map.get(:id)
# "48d4b32b-8833-4423-a1c0-4f43c9471356"

incorrect_types
|> Repo.one
|> Map.get(:id)
# <<72, 212, 179, 43, 136, 51, 68, 35, 161, 192, 79, 67, 201, 71, 19,
     86>>
```

This seems to be consistent across all of our custom types as well.

**Comment by zachdaniel** [comment]
Opening this as a separate issue just in case.
