### ISSUE TITLE
Clarification in Docs for Ecto.Changeset.put_assoc

### ISSUE THREAD

**Issue by lauraannwilliams** [elixir-ecto/ecto#2076]
I'm looking at the docs here: https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4  and I feel there's an inconsistency

In the third paragraph, it states:

> The given value may either be the association struct, a changeset for the given association **or a map or keyword list of changes** to be applied to the current association. If a map or keyword list are given and there is no association, one will be created.

But the fourth paragraph states:

> If the given value is not an association struct or changeset, it will raise.

From my testing with Ecto v2.1.4 and a has_many association, the fourth paragraph matches the actual behaviour - if I try to use a list of maps with put_assoc, I get a (slightly confusing) error raised:
 ``` ** (RuntimeError) changing assocs with change/2 or put_change/3 is not supported, please use put_assoc/4 instead```

Given the inconsistency, I'm not sure if this is a bug in the code or the docs. Could someone clarify for me?

If it's a bug in the docs, I'm happy to put a PR in to remove the reference to using maps & keyword lists. If it's a bug in the code, I'm happy to set up a test case with the error in addition to a doc pr. :)

**Comment by josevalim** [comment]
Thanks for the report @lauraannwilliams! There is definitely an error in the doc in the fourth paragraph, as we should rather say something like "If none of the values above are given, it will raise."

However, I believe a list of maps should be supported, and I have added more tests to make sure this is the case here: 4fbbfd8cb41735802de970260824f85f0c863fe8

Since the tests pass, I assume there is something else going on causing this bug to happen. Can you please provide a mechanism that reproduces the error or a new test to our suite?

Thank you!

**Comment by lauraannwilliams** [comment]
I think it may be due to my composite primary key + has_many. I'm not using many-to-many because my real cases has an additional field set on the join table. 

The following test reproduces the error for me when run as a postgres integration test

```elixir
Code.require_file "../support/types.exs", __DIR__

defmodule Ecto.Integration.PutAssocTest do
  use Ecto.Integration.Case, async: Application.get_env(:ecto, :async_integration_tests, true)

  alias Ecto.Integration.TestRepo
  alias Ecto.Changeset

  alias __MODULE__.User
  alias __MODULE__.Post
  alias __MODULE__.PostUserCompositePk

  defmodule Post do

    use Ecto.Integration.Schema

    schema "posts" do
      field :title, :string
      has_many :post_users, PostUserCompositePk
      timestamps()
    end
  end

  defmodule User do
    use Ecto.Integration.Schema

    schema "users" do
      field :name, :string
      has_many :user_posts, PostUserCompositePk
      timestamps()
    end
  end

  defmodule PostUserCompositePk do
    use Ecto.Integration.Schema

    @primary_key false
    schema "posts_users_composite_pk" do
      belongs_to :user, Ecto.Integration.User, primary_key: true
      belongs_to :post, Ecto.Integration.Post, primary_key: true
      timestamps()
    end
  end

  @tag :composite_pk
  test "put assoc with composite pk" do

    user = TestRepo.insert!(%User{})
    post = TestRepo.insert!(%Post{title: "post title"})

    post = post |> TestRepo.preload(:post_users) |> Changeset.change()

    post_users = [%{post: post, user: user}]

    Changeset.put_assoc(post, :post_users, post_users)
  end

end
```

Result:
```
 MIX_ENV=pg mix test integration_test/cases/put_assoc.exs
Excluding tags: [:without_conflict_target]

  1) test put assoc with composite pk (Ecto.Integration.PutAssocTest)
     integration_test/cases/put_assoc.exs:45
     ** (RuntimeError) changing assocs with change/2 or put_change/3 is not supported, please use put_assoc/4 instead
     stacktrace:
       (ecto) lib/ecto/changeset.ex:1030: Ecto.Changeset.put_change/7
       (stdlib) lists.erl:1263: :lists.foldl/3
       (ecto) lib/ecto/changeset.ex:346: Ecto.Changeset.change/2
       (ecto) lib/ecto/changeset/relation.ex:152: Ecto.Changeset.Relation.do_change/4
       (ecto) lib/ecto/changeset/relation.ex:259: Ecto.Changeset.Relation.map_changes/8
       (ecto) lib/ecto/changeset.ex:1109: Ecto.Changeset.put_relation/5
       integration_test/cases/put_assoc.exs:54: (test)



Finished in 0.1 seconds
1 test, 1 failure

Randomized with seed 696985
```

### Environment

* Elixir version (elixir -v):
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
PostgreSQL 9.6
* Ecto version (mix deps):
HEAD (cloned repo)
* Operating system:
OSX Sierra 10.12.4

**Comment by lauraannwilliams** [comment]
@josevalim  Just wanted to ping on this - should I extract this to a fresh ticket for this, or am I doing something weird?

**Comment by josevalim** [comment]
@lauraannwilliams I actually plan to investigate it this week. I will let you know if we need more info, thanks for asking!

**Comment by josevalim** [comment]
@lauraannwilliams this was a case of poor error messages.

The error was coming from the `:post` and `:user` associations INSIDE the `:post_users` association. That's because Ecto calls `change` recursively when changing associations.

However, instead of improving the error message, I have decided to add the feature altogether, which allows `change/2` and `put_change/3` to work with associations altogether.

**Comment by lauraannwilliams** [comment]
I appreciate the update. :) Thank you
