### ISSUE TITLE
Separation of compile- and run-time configuration

### ISSUE THREAD

**Issue by rhetzler** [elixir-ecto/ecto#2077]
The Ecto configuration takes on the following form:
```
config :my_app, MyApp.MyRepo,
  adapter: Some.Adapter,
  database: "my_app_prod",
  pool_size: 10,
  other_opts....
```
This is a mix of configurations that are accessed at different stages of code lifecycle:
 * compile-time configuration ("adapter")
 * run- (or release)- time configuration (connectivity & tuning)

From the perspective of release management, you always want to keep these things separate, and isolate/minimize the set of configs which will vary from one environment to the next (especially multiple production environments)

We can increase the level of code maturity in ecto and elixir apps in general by promoting this separation of concerns.

Consider the following:
```
defmodule MyApp.MyRepo do
  use Ecto.Repo, otp_app: :my_app, adapter: Some.Adapter
end
```

By moving the adapter specification to the definition of the module it affects, we have attained the following:
* compile time dependency visibly in proximity with the code it affects at compile time
* eliminates a "configuration" that is unlikely to ever require runtime revision
* improved the ability to perform a compilation of your database code without importing your production credentials into your build environment or having to provide fake values (ie, improved code quality)
* reduce risk in updating configuration at run or launchtime with connectivity parameters and secrets. (such code should not require knowledge of an "adapter" key)

# Backwards Compatibility:
Given the implementation of Ecto.Repo \_\_using\_\_, rolling this out as an optional override is trivial. Deprecate the config, and move on.

# Alternative:
If there is a desire to ensure that the adapter remains specified inside the config.exs, it can be retained and still have clean separation with the following (or something similar):
```
config :my_app, {MyApp.MyRepo, :adapter}, Some.Adapter
config :my_app, {MyApp.MyRepo, :connectivity}, database: ...
config :my_app, {MyApp.MyRepo, :tuning}, pool_size: ...
```
I think this alternative is unnecessary, but I present it here for completion only to cover two cases for backwards-compatibility:
* Running a different database in dev vs prod (recognized as an antipattern)
* Provide the ability to hotswap database implementation (switch from postgres to mysql to mongodb at runtime? - If you have sufficient acuity to perform this kind of change, then code reloading from ```  use Ecto.Repo, otp_app: :my_app, adapter: Mysql ``` to   ```use Ecto.Repo, otp_app: :my_app, adapter: Postgrex``` should present no problem. )

Thank you for your consideration

**Comment by josevalim** [comment]
We can allow options to be given to `use` and then users can choose if they want to separate those concerns or not. Also worth mentioning that we allow runtime options to be set on init.

**Comment by josevalim** [comment]
Actually, we already allow in master the adapter to be given as you propose, so I believe what you propose is already achievable. I just made sure we accept `:loggers` too. We don't plan to deprecate the current mechanisms though, thank you!
