### ISSUE TITLE
utc_datetime Error 

### ISSUE THREAD

**Issue by i-m-v-j** [elixir-ecto/ecto#2078]
```
 %Inspect.Error{message: "got UndefinedFunctionError with message \"function Inspect.DateTime.inspect/2 is undefined (module Inspect.DateTime is not available)\" while inspecting %{__struct__: DateTime, calendar: Calendar.ISO, day: 27, hour: 4, microsecond: {152960, 6}, minute: 50, month: 5, second: 36, std_offset: 0, time_zone: \"Etc/UTC\", utc_offset: 0, year: 2017, zone_abbr: \"UTC\"}"
```
when i use dev environment i am getting date with utc_datetime perfectly, but when i am generating release and running , i am getting above error while getting utc_datetime in ecto .

**Comment by michalmuskala** [comment]
Use of `utc_datetime` requires Elixir 1.3. What's the version you use in the release?

Please fill in the issue template. It saves us both time going back and forth on basic questions like this.

**Comment by josevalim** [comment]
Yes, please open up a new issue where the issue template is correctly filled. Thank you.
