### ISSUE TITLE
GitLab-CI docker executor make :ets.match(110633, {"INSERT INTO `schema_migrations` (`version`,`inserted_at`) VALUES (?,?)", :_, :"$1", :"$2", :"$3"})`

### ISSUE THREAD

**Issue by taverngoal** [elixir-ecto/ecto#2083]
### Environment

* Elixir version (elixir -v):   `docker image elixir:slim,  1.4.4`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `docker image mysql:5.6, 5.6.36`
* Ecto version (mix deps):     `2.1.4`
* Database adapter and version (mix deps):     `mariaex 0.8.2`
* Operating system:    `Docker 17.03.1-ce-mac12  On macOS 10.12.5`
* GITLAB version: `8.16.4`
* gitlab-runner version: `1.11.4`
* gitlab-runner config：

```toml
concurrent = 1
check_interval = 0

[[runners]]
  name = "XXX"
  url = "XXX"
  token = "XXX"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ruby:2.3"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
  [runners.cache]

[[runners]]
  name = "XXX"
  url = "XXX"
  token = "XXX"
  executor = "shell"
  [runners.cache]
```

### Current behavior

I use gitlab-ci run test.  the executor is docker.  this is my `.gitlab-ci.yml`:

```yml
image: elixir:latest
services:
  - mysql:5.6
  - docker:dind
variables:
  MYSQL_DATABASE:  XXX
  MYSQL_ROOT_PASSWORD:  XXX

stages:
  - build

before_script:
  - mix local.rebar --force && \
  - mix local.hex --force && \
  - mix deps.get

test:
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install mysql-client -y
    - export MYSQL_USERNAME=XXX MYSQL_PASSWORD=XXX MYSQL_DATABASE=XXX MYSQL_HOST=mysql MIX_ENV=test
    - mix ecto.create
    - mix ecto.migrate
    - mix run priv/repo/seeds.exs
    - mix test
```

the below information is from gitlab-ci console log.

```elixir
$ mix ecto.create
The database for SuServicesSms.Repo has been created
$ mix ecto.migrate

02:58:39.851 [error] Mariaex.Protocol (#PID<0.208.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.73.0> timed out because it owned the connection for longer than 15000ms

02:58:40.391 [error] Could not update schema migrations. This error typically happens when the "schema_migrations" table, which Ecto uses for storing migrationinformation, is already used by another library or for other purposes.

You can fix this by running `mix ecto.drop` in the appropriate `MIX_ENV` to drop the existing database and let Ecto start a new one with a proper definition of "schema_migrations" or by configuring the repository to use another source:

    config :su_services_sms, SuServicesSms.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error is shown below.

** (ArgumentError) argument error
    (stdlib) :ets.match(110633, {"INSERT INTO `schema_migrations` (`version`,`inserted_at`) VALUES (?,?)", :_, :"$1", :"$2", :"$3"})
    (mariaex) lib/mariaex/lru_cache.ex:20: Mariaex.LruCache.lookup/2
    (mariaex) lib/mariaex/protocol.ex:344: Mariaex.Protocol.prepare_lookup/2
    (mariaex) lib/mariaex/protocol.ex:325: Mariaex.Protocol.handle_prepare/3
    (db_connection) lib/db_connection.ex:958: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:1059: anonymous fn/4 in DBConnection.run_prepare_execute/4
    (db_connection) lib/db_connection.ex:1125: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4

ERROR: Job failed: exit code 1
```

the main error in `GITLAB-RUNNER` is 
`(stdlib) :ets.match(110633, {"INSERT INTO `schema_migrations` (`version`,`inserted_at`) VALUES (?,?)", :_, :"$1", :"$2", :"$3"})`

but, my local PC goes well, the command `gitlab-runner exec docker test --docker-privileged`:
```
............

Finished in 0.7 seconds
12 tests, 0 failures

```

### Expected behavior

```
............

Finished in 0.7 seconds
12 tests, 0 failures

```

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error? For errors that happen only on certain environments, we need a sample application, otherwise we risk spending a lot of time in simply trying to reproduce the error (which is not always possible). Thank you.

**Comment by taverngoal** [comment]
It's my pleasure, and I'm sorry for my neglect.  

BUT, I make a [demo](https://git.cn-su.net/tavern/gitlab-ci-ecto/builds/718#down-build-trace),  It just contains ecto and mariaex, It goes well. and never show the error. 
 I can't reproduce.

I'm trying to let the error show again,  I'll add phonenix  on the demo, and try again and again. I'll back. ^_^

sorry for my pool english.

**Comment by josevalim** [comment]
@taverngoal your english is fine. :)

I will close this issue for now. If you can reproduce it, please let us know!
