### ISSUE TITLE
Ecto.Migration.index/3

### ISSUE THREAD

**Issue by tomciopp** [elixir-ecto/ecto#2086]
### Environment

* Elixir version (elixir -v): 1.4.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.3
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: macOS Sierra 10.12.5

### Current behavior

I'm attempting to add postgres' full text search to a column and am running into an error when trying to create the index. 

    for prefix <- prefixes() do
      create index(:notes, [:name], [
        name: "note_search_index",
        prefix: prefix,
        using: "GIN (to_tsvector('english', name))"
      ])

      flush()
    end

This is based off of the documentation for Postgres which recommends creating a GIN index:
https://www.postgresql.org/docs/current/static/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX

Based on the docs here: 
https://hexdocs.pm/ecto/Ecto.Migration.html#index/3-index-types

This string should be passed to the USING clause as is.

However when I attempt to run the migration I get the following error:

    ERROR 42601 (syntax_error): syntax error at or near "("
    (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0

I've attempted several difference escape sequences, but nothing seems to work. It's quite possible that I'm doing something wrong but I can't seem to grasp what syntax error I'm making. 

### Expected behavior

This code should create a GIN index for the name field on this table.

**Comment by josevalim** [comment]
@tomciopp here you go:

```elixir
create index(:notes, ["to_tsvector('english', name)"], [
    name: "note_search_index",
    prefix: prefix,
    using: "GIN"
  ])
```

I will improve the docs.

**Comment by josevalim** [comment]
Added an example to master too. Thank you! Btw, on Ecto 2.2 you will be able to use --log-sql, so at least you will know which command went wrong on migration. :)

**Comment by tomciopp** [comment]
Awesome! I knew I must have had the signature wrong in some way. Thanks for everything!
