### ISSUE TITLE
Incorrect documentation for Ecto.Changeset.cast/3

### ISSUE THREAD

**Issue by shankardevy** [elixir-ecto/ecto#2091]
The documentation for `Ecto.Changeset.cast/3` says

> The given data may be either a changeset, a struct or a {data, types} tuple. The second argument is a map of params that are cast according to the type information from data. params is a map with string keys or a map with atom keys containing potentially unsafe data.

However, the function doesn't accept _struct_ as input.  It should be _schema_ instead. 

```elixir

iex> defmodule Post do        
...    defstruct [:title, :body]  
...  end
iex> Ecto.Changeset.cast %Post{}, %{title: "hello", body: ""}, [:title]
** (UndefinedFunctionError) function Post.__changeset__/0 is undefined or private
           Post.__changeset__()
    (ecto) lib/ecto/changeset.ex:422: Ecto.Changeset.do_cast/4
```
The offending code is https://github.com/elixir-ecto/ecto/blob/v2.1.4/lib/ecto/changeset.ex#L422

When a struct is given, the function expects the struct's module to implement a `__changeset__` function which is defined when using `Ecto.Schema`. 

Can I submit a PR for the docs?

**Comment by michalmuskala** [comment]
Yes, I think the corrected text should read "a struct of an ecto schema" instead of "a struct"

**Comment by shankardevy** [comment]
It looks this is more complicated than a simple text change here. I noticed in several places that Ecto documentation is using the term _struct_ when it is actually a module that uses `schema` macro.  Technically having _struct_ in the docs is incorrect and is misleading. For eg., `Repo.insert/2` says 

> Inserts a struct or a changeset.

It cannot insert a struct. Struct has no information about the table name to store data.

However, having to replace _struct_ everywhere with  _struct created by schema macro_  is too verbose and repetitive. Other option is to use `schema` but again it's technically incorrect, though it is short. It can be `ecto schema module`, though. Any thoughts?

**Comment by josevalim** [comment]
I would say `struct` is fine because in the context it makes sense to be a struct backed by a schema. But being clearer is always welcome, so we can also say `schema struct`. I would agree that calling it `schema` is confusing.

**Comment by josevalim** [comment]
PR please? :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
