### ISSUE TITLE
Writing an adapter for fun, test suite ?

### ISSUE THREAD

**Issue by niahoo** [elixir-ecto/ecto#2094]
Hi, 

I would like to implement a small database engine, just for fun, and I would like to be able to work with Ecto on it, so I could be able to migrate everything to postgresql when I can.

I know that callbacks are defined [here](https://hexdocs.pm/ecto/Ecto.Adapter.html#content), but I would like to know if out of the box I can run the ecto test suite with my adapter.

That would be very useful to implement it.

Thank you

**Comment by josevalim** [comment]
Please See how other adapters, such as mongodb_ecto does it: https://github.com/michalmuskala/mongodb_ecto

**Comment by niahoo** [comment]
Thank you, I'll try to.
