### ISSUE TITLE
encode decimal into float and not-loaded association empty collection

### ISSUE THREAD

**Issue by kenuyx** [elixir-ecto/ecto#2099]
I wonder if it is better that `lib/ecto/poison.ex` looks kind of below

```elixir
if Code.ensure_loaded?(Poison) do
  defimpl Poison.Encoder, for: Decimal do
    def encode(decimal, _opts) do
      decimal |> Decimal.to_float |> :io_lib_format.fwrite_g
    end
  end

  defimpl Poison.Encoder, for: Ecto.Association.NotLoaded do
    def encode(struct, _options) do
      case struct.__cardinality__ do
        :many -> "[]"
        _ -> "{}"
      end
    end
  end
end
```

**Comment by michalmuskala** [comment]
Encoding into float loses precision. Encoding decimals in JSON as strings is the only possible lossless encoding.

Not loaded association does not mean, there are no elements associated. It means we don't know, if they are or not. Encoding as empty collection/object would be simply incorrect.

**Comment by donileo** [comment]
> Encoding decimals as floats loses precision. Encoding decimals in JSON as strings is the only possible lossless encoding.
> 
> Not loaded association does not mean there are no elements associated. It means we don't know, if they are or not. Encoding as empty collection/object would be simply incorrect.

Is there a way to go ahead with lossy conversion and encode decimal types as floats in the json response?

**Comment by OvermindDL1** [comment]
Transform your structure to perform the lossy conversion explicitly first.  :-)

**Comment by donileo** [comment]
> Transform your structure to perform the lossy conversion explicitly first. :-)

Yea I figured this was one way. Thanks.
