### ISSUE TITLE
outdated documentation on hexdocs.pm

### ISSUE THREAD

**Issue by kandros** [elixir-ecto/ecto#2102]
The documentation found at https://hexdocs.pm/ecto/getting-started.html is out of date, while the documentation in the repo is up-to-date.

I had a really hard time figuring out what I was doing wrong considering the guide on hexdocs does not have this snippet (taken from current repo guide)
```
The final piece of configuration is to setup the Friends.Repo as a supervisor within the application's supervision tree, which we can do in lib/friends/application.ex (or lib/friends.ex for elixir versions < 1.4.0), inside the start/2 function:
```

Please consider backport the docs updates.

**Comment by josevalim** [comment]
Thanks @kandros. as you said, it is fixed in master, so as soon as we release a new version, the docs will be updated.
