### ISSUE TITLE
update getting started guide for elixir 1.4

### ISSUE THREAD

**Issue by nhooyr** [elixir-ecto/ecto#2103]
https://hexdocs.pm/ecto/getting-started.html says that one has to first add echo and postgrex to dept in mix.exs and then also add them to the application list but now with elixir 1.4,  you just have to add them as deps and mix will automatically build your application list based on your dependencies

**Comment by josevalim** [comment]
Thank you! It is fixed in master so it will be updated as soon as there is a new release!
