### ISSUE TITLE
`Ecto.Migration.execute/1` options not documented

### ISSUE THREAD

**Issue by toraritte** [elixir-ecto/ecto#2105]
Ecto version (mix deps): **`master`**

- `:capped`
    No description found at the sources below. Has it been deprecated?
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/migration.ex#L574
https://github.com/elixir-ecto/ecto/blob/master/integration_test/sql/migration.exs#L240
https://github.com/elixir-ecto/ecto/blob/master/test/ecto/migration_test.exs#L107
https://github.com/elixir-ecto/ecto/blob/master/test/ecto/migration_test.exs#L109

- `:size`
   Not sure what this means in the context of `execute/1`. The same option is used for `add/3` and `modify/3` in `Ecto.Migration` but `:size` is still referenced individually at each.

Thank you!

**Comment by josevalim** [comment]
Those options are database specific. It can literally be anything, as an `execute` can be any string with any semantics as long as it is accepted by the database you are talking to.

**Comment by michalmuskala** [comment]
To clarify - those particular tests are to support style used in the mongodb adapter for explicitly creating things like capped collections, etc. They are documented in the adapter.
