### ISSUE TITLE
Spec for Ecto.Adapters.SQL.query incorrect for postgrex

### ISSUE THREAD

**Issue by dantswain** [elixir-ecto/ecto#2117]
### Environment

* Elixir version (elixir -v):  1.4.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 9.6.1
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): postgrex 0.13.2
* Operating system: mac OS

### Current behavior

The spec is:

```
query(Ecto.Repo.t, String.t, [term], Keyword.t) ::
  {:ok, %{rows: nil | [tuple], num_rows: non_neg_integer}} |
  {:error, Exception.t}
```

However, postgrex queries return a `Postgrex.Result` struct, e.g.,

```
{:ok,
 %Postgrex.Result{columns: ["max"], command: :select, connection_id: 72712,
  num_rows: 1, rows: [["20170516150906"]]}}
```

Notably, the `rows` value is a list of lists rather than a list of tuples.  This causes dialyzer to fail any match on the returned rows.

### Expected behavior

Without digging, I'm not sure if just the spec needs to be relaxed (`rows: nil | [term]` would work, I think) or if the code needs to be modified to convert the result to a list of tuples.   If the former, I would be glad to submit a PR.

I have the postgrex version overridden to 0.13.2 b/c I need features in the newer version.  The ecto mix.exs wants 0.13.0.  I checked the docs for 0.13.0, 0.13.2, and 0.13.3, and they all say that they return a list for `rows`.

**Comment by josevalim** [comment]
It should be a list of lists. The contract changed for 2.0 or 2.1 (i can't recall). PR please?

**Comment by dantswain** [comment]
Sure thing, I'll do it ASAP.

**Comment by sntran** [comment]
What about the error? When there is an error in database (i.e., invalid constraint, undefined function, etc...), it returns a `%Postgrex.Error{}` and not an `Exception`.

**Comment by michalmuskala** [comment]
`Exception.t` is any struct representing an exception that can be `raised` - https://hexdocs.pm/elixir/Exception.html#t:t/0
