### ISSUE TITLE
`update_all`/`delete_all` with `assoc` on has_many through

### ISSUE THREAD

**Issue by matthewlehner** [elixir-ecto/ecto#2126]
### Environment

* Elixir version (elixir -v): 1.4.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.6.3
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): postgrex 0.13

### Current behavior

When using the `update_all` or `delete_all` from `Ecto.Repo` or `Ecto.Multi` with the `assoc` function a query error is raised.

With the following schemas:

```elixir
defmodule PostContent do
  schema "post_contents" do
    has_many :templates, PostTemplate
    has_many :queued_posts, through: [:templates, :queued_posts]
  end
end

defmodule QueuedPost do
  schema "queued_posts" do
    belongs_to :template, PostTemplate
    has_one :post_content, through: [:template, :post_content]
  end
end

content = Repo.get(PostContent, 1)
Repo.update_all(assoc(content, :queued_post), set: [post_template_id: nil])
```

Raises
```
** (Ecto.QueryError) `update_all` allows only `where` and `join` expressions in query:

     from q in QueuedPost,
       join: p in PostTemplate,
       on: p.post_content_id == ^1050,
       where: q.post_template_id == p.id,
       distinct: true,
       update: [set: [post_template_id: ^nil]]
```

It's easily remedied by writing the query without `distinct: true`, but would be really nice if there was an option to remove it from the query returned by `assoc`.

Even more preferably, the `update_all` and `delete_all` functions could strip the `distinct: true` expression from the query (though, I acknowledge that I'm not aware of the implications of this kind of change from anything other than my current perspective).

**Comment by josevalim** [comment]
You can call `except(:distinct)` and it should remove distinct from the query.

**Comment by josevalim** [comment]
@michalmuskala I am not sure how to proceed here. Simply discarding information can be misleading if people are expecting distinct to somehow work on update/delete. Although I can see how this hurts composition. We have two options:

  1. Automatically discard distinct
  2. Mention the `except` functionality in the error message

Preferences?

**Comment by michalmuskala** [comment]
Yeah, I don't think we should be dropping things by default, on the other hand `distinct: true` never makes sense with `update_all` or `delete_all`. 

I think it's a bit unfortunate we add the `distinct: true` by default, but that ship has sailed.

**Comment by matthewlehner** [comment]
To put in my two cents, if the error message had some text pointing in the direction of `exclude`, that would be a good stop gap measure. At that point, for me, it was an API discoverability issue and was easily solved.

In this specific case, your guidance pointed me in the right direction and I ended up with the following code (which isn't much more verbose).

```elixir
content |> assoc(:queued_posts) |> exclude(:distinct)
```

Something like an additional message like this will help while you decide on the underlying API fix.

```
** (Ecto.QueryError) `update_all` allows only `where` and `join` expressions in query:

     from q in QueuedPost,
       join: p in PostTemplate,
       on: p.post_content_id == ^1050,
       where: q.post_template_id == p.id,
       distinct: true,
       update: [set: [post_template_id: ^nil]]

     If this is unexpected, you can exclude unwanted expressions from a generated
     query using `Ecto.Query.exclude/2`
```

Thanks for the help, and all the work on Ecto and Elixir! ☺️

**Comment by josevalim** [comment]
I went with the error message for now since we don't discard fields in most cases. If this proves to be an issue, we can automatically discard `distinct`, but deciding where to draw the line is a bit though. For example, should we discard order_by? What about limit? Maybe some people would expect limit to actually work and discarding it can be confusing, etc, etc.
