### ISSUE TITLE
Incorrect parameter numbering on self join with fragment

### ISSUE THREAD

**Issue by bernardd** [elixir-ecto/ecto#2128]
* Elixir version (elixir -v): 1.4.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL
* Ecto version (mix deps): master
* Database adapter and version (mix deps): postgrex 0.13.2

The SQL generated when a self-JOIN uses a `fragment` in the subquery has incorrect numbering on the parameters, which causes Postgrex to throw the following error:

`(Postgrex.Error) ERROR 42P18 (indeterminate_datatype): could not determine data type of parameter $2`

(where $2 is the missing parameter).
The following tests, when placed in `postgres_test.exs` demonstrate the problem:

```elixir
  test "self join on subquery" do
    subquery = Schema |> select([r], %{x: r.x, y: r.y})
    query = subquery |> join(:inner, [c], p in subquery(subquery), true) |> normalize
    assert SQL.all(query) ==
           ~s{SELECT s0."x", s0."y" FROM "schema" AS s0 INNER JOIN } <>
           ~s{(SELECT s0."x" AS "x", s0."y" AS "y" FROM "schema" AS s0) } <>
           ~s{AS s1 ON TRUE}
  end

  test "self join on subquery with fragment" do
    subquery = Schema |> select([r], %{string: fragment("downcase(?)", ^"string")})
    query = subquery |> join(:inner, [c], p in subquery(subquery), true) |> normalize
    assert SQL.all(query) ==
           ~s{SELECT downcase($1) FROM "schema" AS s0 INNER JOIN } <>
           ~s{(SELECT downcase($2) AS "string" FROM "schema" AS s0) } <>
           ~s{AS s1 ON TRUE}
  end
```

The first test passes, however the second test ends up with `downcase($1)` twice and no `downcase($2)`.

**Comment by bernardd** [comment]
Actually, on further inspection, you don't need `fragment` to hit this error - it looks like any expression that pulls in an external value using `^` hits the same problem:
```elixir
    subquery = Schema |> select([r], %{x: ^999})
    query = subquery |> join(:inner, [c], p in subquery(subquery), true) |> normalize
```
gives:
`SELECT $1 FROM "schema" AS s0 INNER JOIN (SELECT $1 AS "x" FROM "schema" AS s0) AS s1 ON TRUE`

**Comment by josevalim** [comment]
Thanks, it seems we are not counting the entries in the select inside the subquery.

**Comment by josevalim** [comment]
Fixed in master!
