### ISSUE TITLE
"no case clause matching" in Ecto.Adapters.SQL.struct/7

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#2132]
We was able to get this error in our project:
```
Request: DELETE /apis/35d6d358-d33a-423a-9e96-88a2b235d3f5/plugins/cors
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:ok, %Postgrex.Result{columns: nil, command: :delete, connection_id: 29732, num_rows: 12, rows: nil}}
        (ecto) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.struct/7
        (ecto) lib/ecto/repo/schema.ex:467: Ecto.Repo.Schema.apply/4
        (ecto) lib/ecto/repo/schema.ex:359: anonymous fn/9 in Ecto.Repo.Schema.do_delete/4
        (ecto) lib/ecto/repo/schema.ex:684: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3"}}
```

This error occurred by calling following code:
1. https://github.com/Nebo15/annon.api/blob/master/lib/annon_api/management_api/controllers/api_plugin.ex#L57
2. https://github.com/Nebo15/annon.api/blob/master/lib/annon_api/configuration/plugin.ex#L130

**Comment by josevalim** [comment]
@AndrewDryga that looks like a modelling issue in your application. Is the primary key really a primary key? It seems it is deleting 12 rows instead of a single one.

**Comment by AndrewDryga** [comment]
I guess it can happen, we are using composite PK. I'll check and come back a little bit later.

How about to add a meaningful exception to the `Ecto.Adapters.SQL.struct/7`? Eg.:
```
Your delete statement affected 14 rows instead of one,
please check your primary key.
```

**Comment by josevalim** [comment]
Yup, we definitely need a better error. I just wanted to give you a heads up that something may be wrong on your side. :)

**Comment by AndrewDryga** [comment]
I'll send a PR with error message within 24 hours :). Thanks a lot.

**Comment by josevalim** [comment]
Closing in favor of the PR.
