### ISSUE TITLE
Default to using bigserial/bigint for primary keys

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2135]
This is a backwards-incompatible change, so it will need to wait a little bit.

The downsides of using bigserial/bigint for primary key are very small - primarily data size. But if your dataset is small that doesn't really matter and if your dataset is big, you'd want to use bigserial/bigint anyway. It seems like a much saner default.

**Comment by josevalim** [comment]
Apparently it is bigserial since Ecto 2.0. :)
