### ISSUE TITLE
** (MatchError) no match of right hand side value: {:error, {:postgrex, {'no such file or directory', 'postgrex.app'}}} even when using mysql

### ISSUE THREAD

**Issue by dsslimshaddy** [elixir-ecto/ecto#2136]
Im not using postgresql but mysql i added mariaex in config still the error. 

```
config :auth, Auth.Repo,
  adapter: Ecto.Adapters.MySQL,
  ...

config :auth,
  ecto_repos: [Auth.Repo]

```

```
  defp deps do
    [{:ecto, "~> 2.1"},
      {:mariaex, "~> 0.8.2"}]
  end

```
im using umbrella app

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error? Try searching for "postgrex" in your whole project and see if there is anything left.

**Comment by dsslimshaddy** [comment]
I had postgrex installed(default by phoenix) in one of apps_web i was calling auth from.

After i removed it and did a clean compile (deps.clean deps.compile) it worked nicely.

**Comment by julian3ap** [comment]
can you tell me where did you removed the postgrex installer ? im getting the same error

**Comment by OvermindDL1** [comment]
It's generally best to ask this on the forums, but in general check all of your configs to see what database type is being used.

**Comment by julian3ap** [comment]
thanks, repo.ex had "adapter: Ecto.Adapters.Postgres" by default, that was the error

**Comment by kenny-evitt** [comment]
`mix clean && mix compile` (not the `mix deps.*` versions) seemed to resolve this for me just now.

**Comment by giantthinker** [comment]
> thanks, repo.ex had "adapter: Ecto.Adapters.Postgres" by default, that was the error

Thank you @julian3ap
