### ISSUE TITLE
2.1.5

### ISSUE THREAD

**Issue by brandonparsons** [elixir-ecto/ecto#2143]
Howdy!  I was wondering if you could cut a `2.1.5` release?

I've been waiting for a few months for the e2c42617de50166d85ccc587273a9e363540a868 backport to be in a released version of Ecto. Would be great if it could be in the next week or two :)

**Comment by michalmuskala** [comment]
Yes, I started the work on backporting some fixes for 2.1.5 in the beginning of the week but hit some issues that slowed me down. This is definitely a plan to make this release.

**Comment by michalmuskala** [comment]
2.1.5 was published

**Comment by brandonparsons** [comment]
🎉 

Thanks!!
