### ISSUE TITLE
Consider prompting for confirmation on ecto.load mix task

### ISSUE THREAD

**Issue by brucepom** [elixir-ecto/ecto#2144]
Just something for discussion. The `ecto.dump` mix task [prompts the user for confirmation](https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.drop.ex#L39) under specific circumstances. Presumably as a safeguard against inadvertently dropping the production database. The `ecto.load` mix task is potentially equally destructive. By default the `structure.sql` generated by `ecto.dump` contains instructions to delete then create each table, effectively deleting all data if accidentally run against a populated database. Should `ecto.load` also prompt the user for confirmation?

I'm using `ecto.dump` and `ecto.load` on a project as a way to setup a legacy database in dev and test environments. I'm hesitant to commit `structure.sql` though for fear of it being executed in production. I guess another approach would be to edit `structure.sql` making it non-destructive and having it skip tables that already exist. I'd have to remember to make the edits again if I ever run `ecto.dump` again though.

Really appreciate any thoughts or suggestions.

**Comment by michalmuskala** [comment]
This is a valid concern. Contributions welcome!

**Comment by josevalim** [comment]
@brucepom :+1: can you please send a PR that does the same as ecto.drop? Thank you!

**Comment by brucepom** [comment]
Thanks guys, I will send a PR for this...
