### ISSUE TITLE
Comment is not supported in mysql?

### ISSUE THREAD

**Issue by neroishero** [elixir-ecto/ecto#2148]
mysql adopter
### Current behavior

 create table(:fa_servers, primary_key: false) do
          add :server_id, :integer, null: false, comment: "server's real id"
          add :server_name, :varchar, size: 100 , null: false
          add :ip,  :string, size: 50 , null: false
      end
after run" mix ecto.migrate  " successfully, i can NOT see the comment "server's real id" of the field "server_id" in the datebase(mysql), why?
### Expected behavior
comment "server's real id" in database

**Comment by michalmuskala** [comment]
Yes, comments are not supported in MySQL at the moment. PRs welcome!

**Comment by neroishero** [comment]
ahu, u guys reply so fast ! thanks.  I am new to Elixir, so i just paste my changes here, see if it is correct 
# ---------------------- codes change --------------------------------------------------
   defp column_options(opts) do
      default = Keyword.fetch(opts, :default)
      null    = Keyword.get(opts, :null)
      comment = Keyword.get(opts, :comment)
      [default_expr(default), null_expr(null), comments(comment)]
    end

    defp comments(c) when is_binary(c), do: " COMMENT '" <> escape_string(c) <> "'"
    defp comments(_), do: ""
# --------------------- codes change end ------------------------------------------------

**Comment by neroishero** [comment]
i tested, ofcourse. it worked.

**Comment by josevalim** [comment]
Hi @neroishero! Please try sending a pull request and including some tests. You will most likely need to add comments supports to more than one place. Here is the postgres implementation you can use as guidance, especially when it comes to tests: 4604b0a3caf5ce823d7e75241add9930300e5218

Thank you!

**Comment by josevalim** [comment]
I will close this for now. If someone is interested on this feature, please do send a PR!
