### ISSUE TITLE
Support for preloading subqueries

### ISSUE THREAD

**Issue by zachdaniel** [elixir-ecto/ecto#2152]
Elixir Version: 1.4.5
Database Version: PostgreSQL 9.5
Ecto Version: ecto 2.2.0-dev (https://github.com/elixir-ecto/ecto.git) (mix)
Database Adapter: postgrex 0.13.3 (Hex package) (mix
Operating system: OSX

### Current behavior
When put a query into a keyword list preload statement, I get:
```
** (FunctionClauseError) no function clause matching in Ecto.Repo.Preloader.query!/1
```

The offending code is clearly:
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L315

### Expected behavior
Subqueries can be passed into the preloader, or a better error message expressing that it is not possible.

Was that pattern match intended to restrict things like subqueries? If so, lets add a nicer error message. If not, how do we get subqueries to work in preloads?

**Comment by zachdaniel** [comment]
I was able to resolve this issue on my end by wrapping the subquery in `Ecto.Queryable.to_query/1` to make sure its not a subquery.

**Comment by josevalim** [comment]
Right now we don't plan to support this feature so I will go ahead and close this. If someone wants to contribute though, please go ahead!
