### ISSUE TITLE
Float converts to integer in map field, when saving in PostgreSQL

### ISSUE THREAD

**Issue by Apelsinka223** [elixir-ecto/ecto#2154]
Value in map field converts from float to int when it`s bigger then 1000

### Environment

* Elixir version (elixir -v): Elixir 1.4.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.2
* Ecto version (mix deps): ecto 2.1.4
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: macOS 16

### Current behavior

Schema

```
schema "test" do
   field :data, :map

   timestamps()
end
```

When > 1000
```
iex(1)> MyApp.Repo.insert(MyApp.Test.changeset(%MyApp.Test{}, %{data: %{"float" => 50000.0}}))

{:ok,
 %MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
  data: %{"float" => 5.0e4}, id: "8b72d633-6c69-418a-bf4c-b4f90654a506",
  inserted_at: ~N[2017-08-04 18:43:22.012468],
  updated_at: ~N[2017-08-04 18:43:22.012513]}}

iex(2)> MyApp.Repo.get(MyApp.Test, "8b72d633-6c69-418a-bf4c-b4f90654a506")

%MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
 data: %{"float" => 50000}, id: "8b72d633-6c69-418a-bf4c-b4f90654a506",
 inserted_at: ~N[2017-08-04 18:43:22.012468],
 updated_at: ~N[2017-08-04 18:43:22.012513]}
```

When < 1000

```
iex(3)> MyApp.Repo.insert(MyApp.Test.changeset(%MyApp.Test{}, %{data: %{"float" => 50.0}}))

{:ok,
 %MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
  data: %{"float" => 50.0}, id: "60c95e45-4f6c-43b6-985a-8706b67ee459",
  inserted_at: ~N[2017-08-04 18:58:32.034022],
  updated_at: ~N[2017-08-04 18:58:32.034036]}}

iex(4)> MyApp.Repo.get(MyApp.Test, "60c95e45-4f6c-43b6-985a-8706b67ee459")

%MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
 data: %{"float" => 50.0}, id: "60c95e45-4f6c-43b6-985a-8706b67ee459",
 inserted_at: ~N[2017-08-04 18:58:32.034022],
 updated_at: ~N[2017-08-04 18:58:32.034036]}
```
### Expected behavior

```
iex(1)> MyApp.Repo.insert(MyApp.Test.changeset(%MyApp.Test{}, %{data: %{"float" => 50000.0}}))

{:ok,
 %MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
  data: %{"float" => 5.0e4}, id: "8b72d633-6c69-418a-bf4c-b4f90654a506",
  inserted_at: ~N[2017-08-04 18:43:22.012468],
  updated_at: ~N[2017-08-04 18:43:22.012513]}}

iex(2)> MyApp.Repo.get(MyApp.Test, "8b72d633-6c69-418a-bf4c-b4f90654a506")

%MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
 data: %{"float" => 50000.0}, id: "8b72d633-6c69-418a-bf4c-b4f90654a506",
 inserted_at: ~N[2017-08-04 18:43:22.012468],
 updated_at: ~N[2017-08-04 18:43:22.012513]}

iex(3)> MyApp.Repo.insert(MyApp.Test.changeset(%MyApp.Test{}, %{data: %{"float" => 50.0}}))

{:ok,
 %MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
  data: %{"float" => 50.0}, id: "60c95e45-4f6c-43b6-985a-8706b67ee459",
  inserted_at: ~N[2017-08-04 18:58:32.034022],
  updated_at: ~N[2017-08-04 18:58:32.034036]}}

iex(4)> MyApp.Repo.get(MyApp.Test, "60c95e45-4f6c-43b6-985a-8706b67ee459")

%MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
 data: %{"float" => 50.0}, id: "60c95e45-4f6c-43b6-985a-8706b67ee459",
 inserted_at: ~N[2017-08-04 18:58:32.034022],
 updated_at: ~N[2017-08-04 18:58:32.034036]}
```

**Comment by josevalim** [comment]
I cannot reproduce this in our test suite. Can you please try adding a test case to `integration_test/cases/type.exs` that reproduces the issue?
 
Also please try checking how the data is being written to the database. It is important to know if the issue is happening when writing or reading. You can also see the query sent to the database in your logs.

**Comment by Apelsinka223** [comment]
Added case in tests https://github.com/Apelsinka223/ecto/commit/b121db56fa366338ae4b2b1351a2eb3c002bfff3
. An error throws only when used `===` comparison

With query
```
iex(1)> MyApp.Repo.insert(MyApp.Test.changeset(%MyApp.Test{}, %{data: %{"float" => 50000.0}}))

[debug] QUERY OK db=13.3ms queue=0.1ms
INSERT INTO "test" ("data","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4) [%{"float" => 5.0e4}, {{2017, 8, 7}, {13, 14, 35, 899710}}, {{2017, 8, 7}, {13, 14, 35, 911179}}, <<119, 186, 6, 117, 187, 199, 72, 147, 171, 178, 96, 89, 97, 161, 131, 53>>]

{:ok,
 %MyApp.Test{__meta__: #Ecto.Schema.Metadata<:loaded, "test">,
  data: %{"float" => 5.0e4}, id: "77ba0675-bbc7-4893-abb2-605961a18335",
  inserted_at: ~N[2017-08-07 13:14:35.899710],
  updated_at: ~N[2017-08-07 13:14:35.911179]}}
```

In database
```
-[ RECORD 1 ]-------------------------------------
id          | 77ba0675-bbc7-4893-abb2-605961a18335
data        | {"float": 50000}
inserted_at | 2017-08-07 13:14:35.89971
updated_at  | 2017-08-07 13:14:35.911179
```

**Comment by josevalim** [comment]
So I have verified this is a postgres behaviour:

```
ecto_test=# SELECT '{"foo": 5.0e3}'::jsonb;
     jsonb
---------------
 {"foo": 5000}
(1 row)
```

The reason I used "5.0e3" is because that's the value used by Poison for 5000.0 and above.

However, I am not sure we can call it either a Postgres bug or a Poison bug (the library we used to encode numbers) because JSON does not have the concept of integers and floats, it just calls the "numbers" and it provides no guidance on this topic.

The only solution I could find for now is to make the field a `:json` field instead of `:jsonb`, if possible. Note `:json` takes more storage though and gives less flexibility. But it seems to keep the original value:

```
ecto_test=# SELECT '{"foo": 5.0e3}'::json;
      json
----------------
 {"foo": 5.0e3}
(1 row)
```


I am not sure if there is something we can do here. JSON doesn't specify integers or floats so you may have to work with the possibility that any JSON field may be an integer or a float.

**Comment by josevalim** [comment]
Another alternative is for you to define an `embedded_schema` for your map and use that instead. If you mark the field as float in the embedded_schema, then that will be guaranteed.

**Comment by OvermindDL1** [comment]
As I recall, jsonb encodes 'numbers' as a 'double' (64-bit) floating point to follow the same spec as modern browsers do, so you should always assume that all numbers stuffed into a JSON object will come back as a double.  If you want to encode it unambiguously then you can always hexify the float or binary/string encode the integer and just store it as a string (though that loses some flexibility, but not really at the large performance and size of using json over jsonb datatype in PostgreSQL).

**Comment by Apelsinka223** [comment]
Thank you for the answer
