### ISSUE TITLE
Undocumented breaking change in 2.2

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-ecto/ecto#2160]
Returning tuples from subqueries is no longer supported and results in:
`** (EXIT from #PID<0.3800.0>) an exception was raised:
         ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.
     
         ** (Ecto.QueryError) subquery must select a source (t), a field (t.field) or a map, got: `{&0.my_property()}` in query: ...`

The fix in this case is trivial:
replace
`select: {x.my_property} `
with
`select: %{my_property: x.my_property} `

However, a migration guide should be added.

**Comment by josevalim** [comment]
Hrm, it seems the validation logic had a bug in 2.1 since returning a tuple from `select` can't really be used upstream. I will update the CHANGELOG, thank you.

**Comment by Yoshyn** [comment]
@lucasmazza : So much thanks. The fix is trivial but as the error is unexpected it's not so trivial to debug.
