### ISSUE TITLE
Strict checks introduced in 828cfbc result in hard to debug errors

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-ecto/ecto#2161]
### Environment
* Ecto version (mix deps): 2.2-rc.0

### Current behavior
```
     ** (KeyError) key :id not found
     code: clone(original_id)
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:642: Ecto.Repo.Schema.load_each/4
       (ecto) lib/ecto/repo/schema.ex:626: Ecto.Repo.Schema.load_changes/7
       (ecto) lib/ecto/repo/schema.ex:214: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:768: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
```
### Expected behavior
Better error message, e.g `Struct MyStruct is missing :id key in action :insert
`

**Comment by josevalim** [comment]
Can you please provide a code snippet that reproduces the error?

**Comment by josevalim** [comment]
Basically, I want to know if it is an Ecto bug or if it is really just a case of a poor message. It is really suspicious that you are getting a missing :id key for a *struct*.

**Comment by lukaszsamson** [comment]
It's not a bug. I was getting it in a hacky code that used to work with 2.1
```
orig = Repo.get!(MyStruct, original_id)
... 
orig
|> Map.delete(:id)
|> Ecto.Changeset.change(:version, orig.version + 1)
|> Repo.insert!
```
I ended up changing `|> Map.delete(:id)` to `|> Map.merge(%{id: nil})`
A better message here definitely would save a few cycles.

**Comment by josevalim** [comment]
Thanks, I will push some improvements to master!
