### ISSUE TITLE
With a large number of inserts application killed by memmory limit

### ISSUE THREAD

**Issue by Slavenin** [elixir-ecto/ecto#2164]
### Environment

* Elixir version (elixir -v):

> Erlang/OTP 19 [erts-8.2] [source] [64-bit] [async-threads:10] [kernel-poll:false]
> Elixir 1.4.0

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
```
MongoDB shell version v3.4.2
git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

* Ecto version (mix deps):

> "ecto": {:git, "https://github.com/elixir-ecto/ecto.git", "eaf8f4a6ba173732391b8e33049a664649738a67", [ref: "v2.0"]},

* Database adapter and version (mix deps):

> {:mongodb_ecto, git: "https://github.com/michalmuskala/mongodb_ecto", branch: "ecto-2"},

* Operating system:

> Ubuntu 16.10 (GNU/Linux 4.8.0-49-generic x86_64)

### Current behavior

My app inserts millions records. Every second size ets data table increases on several mb.
In deps/ecto/lib/ecto/query/planner.ex I find cache_insert function that inserts data to ets. 

My function for insert:
```elixir
defp to_cache(links) do
    recs =
    Enum.uniq(links)
    |> Enum.filter(fn (link) -> (link != nil and link != "") end)
    |> Enum.map(fn link -> %{link: link}  end)
    |> Enum.each(fn link ->
         %Crawler.MongoLinks{}
            |> Crawler.MongoLinks.changeset(link)
            |> Crawler.MongoRepo.insert()
     end)
end
```
`link` is struct like `%Crawler.Links{link: "http://example.com/page.html"}`

**Comment by josevalim** [comment]
Are you sure the table in the planner is the one running out of memory?
Ecto does not cache insert queries. So it is either a bug elsewhere or
there is another part of your application performing queries.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Slavenin** [comment]
@josevalim, you right. This other app from deps.
