### ISSUE TITLE
Support :mapper or :source_mapper for field mapping on schema/2

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2166]
@michalmuskala any preferences on the option name?

**Comment by michalmuskala** [comment]
`mapper` sounds way too generic for me. I could see us using even `source_field_mapper`.

How does `source` work on embeds? Should this also work there?

**Comment by josevalim** [comment]
Yup, it works on embeds. Maybe it should be a module attribute though to
mirror everything else? @ecto_field_mapper?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
With module attribute, we can't use a fun, though. Should we accept a `{m, f, args}` tuple instead?

**Comment by josevalim** [comment]
We can use a fun as long as we don't inject it in any function.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
