### ISSUE TITLE
Associations guide missing from https://hexdocs.pm/ecto

### ISSUE THREAD

**Issue by berlintam** [elixir-ecto/ecto#2167]
If you go to https://hexdocs.pm/ecto and navigate to the pages section, the 'Associations' manual should also be listed. Currently only the 'Getting Started' doc is shown. 

![screenshot from 2017-08-12 09-53-29](https://user-images.githubusercontent.com/4237285/29239057-325d0726-7f44-11e7-9d87-6cddc1fa895d.png)

The [Associations.md](https://github.com/elixir-ecto/ecto/blob/master/guides/Associations.md) is included in the [mix.ex](https://github.com/elixir-ecto/ecto/blob/3d25cc46b7ea7049daa2cfd890c897b3046171d1/mix.exs#L33) but I can't spot what's causing this incorrect behaviour. 

If someone can point me in the right direction I'd be happy to submit a PR. Thanks!!

**Comment by michalmuskala** [comment]
The associations guide is part of the 2.2 release. It's not present in the 2.1 documentation.

https://hexdocs.pm/ecto/2.2.0-rc.0/associations.html#content
