### ISSUE TITLE
Ecto load map cannot load `"{}"`

### ISSUE THREAD

**Issue by steffenix** [elixir-ecto/ecto#2168]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.5
* Ecto version (mix deps): 2.1.6
* Database adapter and version (mix deps): 0.13.0

### Current behavior
 ```
defmodule Insta.Profile do
  use Ecto.Schema
  schema "profiles" do
    field :name
    field :infos, :map
  end
end
```

```
defmodule Insta.Repo.Migrations.CreateProfiles do
  use Ecto.Migration

  def change do
    execute "CREATE EXTENSION IF NOT EXISTS postgis"
    create table(:profiles) do
      add :name, :string
      add :education, :map
      add :location, :geography
    end
  end
end

```

Error:

```
** (ArgumentError) cannot load `"{}"` as type :map for :infos in schema Insta.Profile
```

### Expected behavior

It's should be possible to load an empty json.

**Comment by josevalim** [comment]
The JSON is coming as a strings. Something was supposed to have converted
it to a map already. Can you please provide more information to reproduce
the issue?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
