### ISSUE TITLE
ecto.create should not report the database already exists for Postgres on invalid credentials

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2169]
See https://github.com/phoenixframework/phoenix/issues/2442.

**Comment by pbudzik** [comment]
LOL. The issue was cause by existence of a system property DATABASE_URL. How come? Do you use it? If you do, it should not conflict. I remove it and now it throws a proper error :)

**Comment by josevalim** [comment]
We shouldn't pick it up automatically. I will investigate when I am back
the computer.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Ok, i got the proper error too, it was a different error. But we don't pick DATABASE_URL by default so maybe there is another file causing it? but it seems Ecto is behaving as specified.

**Comment by mkreyman** [comment]
A "new" project seems to use configuration for an "old" project and ignores its own config/dev.exs. I have the following in my ~/.bash_profile for an "old" phoenix project:
```
export DB_USER=$USER
export DB_PASSWORD=''
export DB_NAME='old_project_dev'
export DB_HOST='localhost'
export DATABASE_URL="ecto://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME"
```
...and here's config/dev.exs for it:
```
config :old_project, OldProject.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD"),
  database: System.get_env("DB_NAME"),
  hostname: System.get_env("DB_HOST"),
  pool_size: 10
```

Here's the "new" project's config/dev.exs:
```
config :new_project, NewProject.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "new_project_dev",
  hostname: "localhost",
  pool_size: 10
```

Now, when I drop, create and run migrations in the "new" project's directory, those actions are getting executed on the "old" database!

Renaming the env variables for the "old" project resolved the issue.
