### ISSUE TITLE
Creating sorted indices fail

### ISSUE THREAD

**Issue by asabil** [elixir-ecto/ecto#2170]
### Environment

* Elixir version: Elixir 1.5.0 Erlang/OTP 20 [erts-9.0]
* Database and version: PostgreSQL 9.6.3
* Ecto version:  2.1.6
* Database adapter and version: postgrex 0.13.3
* Operating system: macOS 10.12.6

### Current behavior

The Ecto PostgreSQL migration support started adding parentheses around indices in order to properly support index expressions in https://github.com/elixir-ecto/ecto/commit/e35e36b4e03ccbd9a810148ee3da23c8857dc580

This however breaks the creation of sorted indices. The following call:

`create index(:foo, ["created_at DESC"])`

fails with this error in the PostgreSQL logs:

```
ERROR:  syntax error at or near "DESC" at character 83
STATEMENT:  CREATE INDEX "foo_created_at_DESC_index" ON "myschema"."foo" ((created_at DESC))
```

**Comment by michalmuskala** [comment]
\cc @ericmj you introduced the problematic change. Could you explain a bit more what issues was it fixing?

**Comment by ericmj** [comment]
@michalmuskala Expressions always require parenthesis around them. We should probably add proper fragments and add support for DESC/ASC/NULLS without dropping down to SQL syntax.

**Comment by michalmuskala** [comment]
It seems the problem is the double wrapping in parens. I guess it would work if we only wrapped the second time if we have more than one expression for the index, right? 

It still breaks something that was working before, if we can't make both things work, I guess it's better to have the thing that worked before continue working and provide a new mechanism for the thing that was never working.

**Comment by ericmj** [comment]
> It seems the problem is the double wrapping in parens. I guess it would work if we only wrapped the second time if we have more than one expression for the index, right?

You are supposed to double wrap when using expressions. The problem is that we put DESC as part of the expression which is incorrect.

> It still breaks something that was working before, if we can't make both things work, I guess it's better to have the thing that worked before continue working and provide a new mechanism for the thing that was never working.

Yes, we probably need to roll this change back and find a backwards compatible way to improve index creation.

**Comment by asabil** [comment]
> > It still breaks something that was working before, if we can't make both things work, I guess it's better to have the thing that worked before continue working and provide a new mechanism for the thing that was never working.
> 
> Yes, we probably need to roll this change back and find a backwards compatible way to improve index creation.

I think what was working before, was really working by accident. `index` should probably have the following signature:

```
index(table, [column]) where
    column :: atom | expression | {atom | expression, [modifier]}
    expression :: String.t
    modifier :: binary | :asc | :desc | :nulls_first | :nulls_last | {:collate, binary}
```

**Comment by ericmj** [comment]
Yeah, it's really unclear how this was supposed to work. Before my change the expression example was broken in the docs were broken: https://hexdocs.pm/ecto/Ecto.Migration.html#index/3.

The docs only use atoms for fields and uses strings for expressions.

The docs also say "Expects the table name as first argument and the index fields as second. The field can be an atom, representing a column, or a string representing an expression that is sent as is to the database." Which is exactly what we are following now but didn't before my patch. It was also not documented that modifiers were supposed to work.

I think @asabil's suggestion makes sense.

**Comment by josevalim** [comment]
I have reverted the PR for now in master. Thank you!

**Comment by ericmj** [comment]
@josevalim I think this is the wrong decision. By reverting we fix undocumented behaviour and we break documented behaviour.

We have no documentation that says "column" or "column DESC" is supposed to work, the docs clearly say you should use atoms for columns and use strings for expressions.

These examples are now broken again: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/migration.ex#L535 and https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/migration.ex#L541-L542

**Comment by asabil** [comment]
I completely agree with @ericmj I think his fix is the correct one. We just need to augment it supporting index column/expression modifiers.

**Comment by josevalim** [comment]
@ericmj this behaviour is a breaking change we are introducing on 2.2. People using expression on 2.1 already wrapped them in parens, people using DESC etc has it working today. So we do need to revert the behaviour and THEN we come up with the new API.

**Comment by ericmj** [comment]
The reason I don't agree is because we are only breaking something that has never been documented to work. The documentation is pretty clear that strings are for expressions and DESC is not an expression. We are not breaking people who already wrap expressions in parenthesis, we only break DESC.

**Comment by josevalim** [comment]
@ericmj it is still a breaking change where a fix buys us very little. Given the benefits, the breaking change is really not worth it.

**Comment by ericmj** [comment]
Fair enough. I see you also updated the docs, thank you!
