### ISSUE TITLE
Ecto 2.1.4 - Schema from pg_dump fails to execute: "cannot insert multiple commands into a prepared statement"

### ISSUE THREAD

**Issue by sergiotapia** [elixir-ecto/ecto#2171]
### Environment

* Elixir version (elixir -v): 1.4.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PG 9.6.1
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): ecto 
* Operating system: OSX

### Current behavior

I extracted the schema from an existing PG database using pgAdmin 4 and setting schema only export. Running the `.sql` file with `execute` in a migration file causes error:

`execute File.read!("my-sql-file.sql)`

> ** (Postgrex.Error) ERROR 42601 (syntax_error): cannot insert multiple commands into a prepared statement
> (ecto) lib/ecto/adapters/sql.ex:195: Ecto.Adapters.SQL.query!/5
> (ecto) lib/ecto/adapters/postgres.ex:86: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
> (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
> (ecto) lib/ecto/adapters/postgres.ex:86: Ecto.Adapters.Postgres.execute_ddl/3
> (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
> (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
> (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
> (stdlib) timer.erl:181: :timer.tc/2

### Expected behavior

It executes the script normally and creates the database tables/fields (no data).

**Comment by josevalim** [comment]
Yes, `execute` is about a single command, you can't load the whole sql file.

**Comment by sergiotapia** [comment]
Hi @josevalim - that makes sense. For my purpose I just needed to create one table so I removed all commands except the single `create table`. That's why it worked.

I was wondering for the time when I do need to create an entire database from an exported schema, how do I accomplish this? Any suggestions? This was for setting up codeship's postgres database for my mix tests to run.

**Comment by michalmuskala** [comment]
There's the `mix ecto.load` task that can load from a pg_dump dumped database. Maybe that could be useful.
