### ISSUE TITLE
Use UTC time to timestamp migration files

### ISSUE THREAD

**Issue by svarlet** [elixir-ecto/ecto#2172]
Hi,

I was wondering if the timestamps which prefix the migration files uses the local machine time or the UTC time. The documentation doesn't seem to mention it so I asked in Slack and @michalmuskala suggested to open an issue here.

Since the timestamp is used to ensure the migrations are performed in the right order, I believe that using the local time (of the machine which generated the migration file) will cause troubles to geographically distributed teams.

**Comment by michalmuskala** [comment]
We should either change globally or at least support a configuration option for this.

**Comment by michalmuskala** [comment]
Ok, I just checked and it seems both `ecto.gen.migration` and `phx.gen.schema` tasks use `:calendar.universaltime` as the base for producing the timestamp, so we're fine.

@svarlet I'm not sure where in the docs we could mention it. Any suggestions?

**Comment by josevalim** [comment]
We should list it in the docs of both generators.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by svarlet** [comment]
Good news!
I was expecting to find a mention here https://hexdocs.pm/phoenix/mix_tasks.html#ecto-specific-mix-tasks
