### ISSUE TITLE
bulk upsert increments existing primary key IDs

### ISSUE THREAD

**Issue by timCF** [elixir-ecto/ecto#2181]
### Environment

* Elixir version 1.4.5
* Database and version (PostgreSQL 9.6.3)
* Ecto version ~> 2.1
* Database adapter and version postgrex ~> 0.13.0
* Operating system Mac

### Current behavior

```elixir
App.Model
|> App.Repo.insert_all([
    %{name: "name1", data: "data1"},
    %{name: "name2", data: "data2"},
], [
    on_conflict: :replace_all, 
    conflict_target: [:name], 
    returning: [:id]
])
```

```
SELECT id, name FROM models;
 id |      name
----+----------------
  1 | name1
  2 | name2
```

```elixir
App.Model
|> App.Repo.insert_all([
    %{name: "name1", data: "data1"},
    %{name: "name2", data: "data2"},
], [
    on_conflict: :replace_all, 
    conflict_target: [:name], 
    returning: [:id]
])
```

```
SELECT id, name FROM models;
 id |      name
----+----------------
  3 | name1
  4 | name2
```

### Expected behavior

Upsert will not change ID primary key of already existing rows, just update other fields.

**Comment by josevalim** [comment]
Can you please check the query we are sending to the database? And can you can then try to run this query directly against the database and see how it behaves? I believe there is nothing we can do here, it is all the DB behaviour.

**Comment by timCF** [comment]
In logs I see something like this ( one row in request for example )
```
INSERT INTO "models" 
    ("name","id","data") 
VALUES 
    ($1,DEFAULT,$2) 
ON CONFLICT ("name") DO UPDATE 
SET 
    "name" = EXCLUDED."name",
    "id" = EXCLUDED."id",
    "data" = EXCLUDED."data" 
RETURNING 
    "id" 
[1, "Test 4"]
```
It seems `"id" = EXCLUDED."id"` is the cause of this behaviour described above

**Comment by josevalim** [comment]
Yes, I think this is a bug. We should replace all except the primary key. Thank you.

**Comment by timCF** [comment]
Thx for fast feedback!

**Comment by josevalim** [comment]
I am wondering why it is setting "id" to DEFAULT. Do you also have some entries that include the ID in the list given to insert_all?

**Comment by timCF** [comment]
In this example ID is not present in data to upsert, just uniq_key `name`

**Comment by timCF** [comment]
It seems behaviour is fixed when `"id" = EXCLUDED."id"` is removed from request

**Comment by josevalim** [comment]
@timCF Thanks for checking.

I am worried about changing `:replace_all` because we can only remove primary keys if a schema is available - it may also be a breaking change if someone is relying on this behaviour. So I will push a new option, `:replace_all_except_primary_key` that should fit your use case. We may want to make it more generic in the future, `{:replace_all, except: [...]}`, but I think this case is common enough to warrant its own option, especially given that it should likely be preferred over `:replace_all`.

**Comment by timCF** [comment]
Thx! `{:replace_all, except: [...]}` sounds very good, and `replace_all_except_primary_key` is also ok for my current task :)

**Comment by seymores** [comment]
I am curious as to the use case where the PK is expected to change by default in the context of an upsert operation.

**Comment by kcurtin** [comment]
is the `{:replace_all, except: [...]}` being tracked anywhere? I'd like to subscribe to it so I know when it gets merged. My use case is doing bulk upserts based on a unique `external_id`. I need to preserve the PK (for associations) and match the new data based on the `external_id`. Something like this:
```
App.Model
|> App.Repo.insert_all([
    %{external_id: "id1", data: "data1"},
    %{external_id: "id2", data: "data2"},
], [
    on_conflict: {:replace_all, except: [:id, :external_id]}, 
    conflict_target: :external_id, 
    returning: true
])
```

**Comment by safwank** [comment]
@josevalim Is the fix only gonna be included in v3.0?

**Comment by josevalim** [comment]
@kcurtin there are no plans for it right now so it isn't tracked anywhere. You can do `App.Model.__schema__(:fields)` or similar to get all fields and remove the ones you want.

@safwank yes because it augments the adapter APIs and for this reason it can't be included in a point release.

**Comment by safwank** [comment]
@josevalim Are you suggesting a temporary workaround would be to do something along these lines?

```elixir
App.Model.__schema__(:fields)
|> List.delete(:id)
|> App.Repo.insert_all(...)
```

**Comment by josevalim** [comment]
@safwank not exactly like that but something like that, yes, correct.

**Comment by safwank** [comment]
Hah, just realized it wouldn't actually work, but point taken 👍
