### ISSUE TITLE
has_one issues sql query when preloading nil value

### ISSUE THREAD

**Issue by khamilowicz** [elixir-ecto/ecto#2190]
### Environment

* Elixir version: 1.5.1
* Database and version: PostgreSQL 9.6.1
* Ecto version: 2.1.6
* Database adapter and version: postgrex 0.13.3
* Operating system: macOS 10.13

### Current behavior

Preloading multiple times has_one association keeps sending queries to database, even though relation is loaded as `nil`.

    defmodule Defa.Accounts.User do
      use Ecto.Schema
      import Ecto.Changeset
      alias Defa.{
        Accounts.User,
        Accounts,
      }

      schema "users" do
        has_one :profile, Accounts.Profile
        field :date_of_birth, :date
        field :name, :string

        timestamps()
      end

    end

    defmodule Defa.Accounts.Profile do
      use Ecto.Schema
      import Ecto.Changeset
      alias Defa.Accounts.Profile
      alias Defa.Accounts.User

     schema "profiles" do
      field :name, :string
      field :user_id, :id

      belongs_to :user, Accounts.User

      timestamps()
    end

    {:ok, user} = Defa.Repo.insert(%User{profile: nil})
    INSERT INTO "users" ("inserted_at","updated_at") VALUES ($1,$2) RETURNING "id" [{{2017, 8, 27}, {20, 22, 0, 18857}}, {{2017, 8, 27}, {20, 22, 0, 25895}}]
    user = Defa.Repo.preload(user, :profile)
    SELECT p0."id", p0."name", p0."user_id", p0."inserted_at", p0."updated_at", p0."user_id" FROM "profiles" AS p0 WHERE (p0."user_id" = $1) [3]
    user = Defa.Repo.preload(user, :profile)
    SELECT p0."id", p0."name", p0."user_id", p0."inserted_at", p0."updated_at", p0."user_id" FROM    "profiles" AS p0 WHERE (p0."user_id" = $1) [3]

Setting assoc key to any value does not send query.

### Expected behavior

Repo.preload should treat `nil` assoc value as loaded association.

**Comment by josevalim** [comment]
Fixed in 483fa649dd2adc7afb49a44e0084ed2df794619a.
