### ISSUE TITLE
Ecto.Migration.timestamps/1 inconsistent with Ecto.Schema.timestamps/1

### ISSUE THREAD

**Issue by vraravam** [elixir-ecto/ecto#2208]
### Environment

* Elixir version (elixir -v): Elixir 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.6.3
* Ecto version (mix deps): ecto 2.1.6
* Phoenix version: phoenix 1.3.0
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: Mac OSX Sierra (10.12.6)

### Current behavior
I went through some documentation and blogs since I wanted to customize the `inserted_at` and `updated_at` columns in the schemas as well as the migrations (since I am creating a phx app that has to deal with an existing DB). So, I put this wherever I found `use Ecto.Schema` (ie in the models):
```elixir
@timestamps_opts inserted_at: :created_at, updated_at: :modified_at
```
While this does generate the db correctly for the `dev` environment, it actually doesn't seem to affect the `test` environment. When I was debugging, I also found another inconsistency: the autogenerated `id` primary key column seems to have different datatypes when comparing the dev and the test databases.

### Expected behavior
1. The column names for the timestamp columns should be as I have specified in the migration file. Of course, I am using the migration files/mechanism only for local testing, since the production database already exists from the previous tech stack.
2) The `id` column data types should be consistent - either `integer` or `big_int`.

### Screenshot of the 2 databases
![dev-vs-test-table-descriptions](https://user-images.githubusercontent.com/69629/30096115-e67089ae-92d6-11e7-9b42-02e198c97338.png)

**Comment by josevalim** [comment]
Setting those in the schema is not going to change your migrations. You need to specify how you want the timestamp to look like in both the schema and the migrations. Is that the case? If so, can you provide how you have also configured the migrations?

**Comment by vraravam** [comment]
@josevalim : Yes, I deduced that part - and had the similar options in each of the migrations as well (individually, as opposed to having a global setting). The migration line looks like this:
```elixir
timestamps(inserted_at: :created_at, updated_at: :modified_at)
```

**Comment by josevalim** [comment]
So I have no idea why this would happen. Can you please provide a sample application that reproduces the error so we can give it a try? Thank you!

**Comment by vraravam** [comment]
@josevalim - Not sure what was happening. I tried to create a bare repo, and this time it worked fine ie both the issues are not reproducible. I suspect that previously, I was trying to do `ecto.reset` - which brought in schemas from some cached location? Anyways, this can be closed. Thanks for your response.
