### ISSUE TITLE
warning about "not an Ecto schema" due to compilation order of nested modules

### ISSUE THREAD

**Issue by danj3** [elixir-ecto/ecto#2209]
### Environment

* Elixir version (elixir -v):
> Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
>
> Elixir 1.4.2

* Ecto version (mix deps): 2.2.1

### Current behavior

The code below will cause the following warning to be emitted during compilation:

> warning: invalid association 'outer' in schema Embed.Inner: associated module Embed is not an Ecto schema
>  lib/misc/embed_ecto.ex:8: Embed.Inner (module)

```
defmodule Embed do
  use Ecto.Schema

  schema "outer" do
    field :name, :string
  end

  defmodule Inner do
    use Ecto.Schema

    schema "inner" do
      belongs_to :outer, Embed
    end
  end

end
```

During the @after_compile hook run when `Embed.Inner` has completed compilation, the code in `Ecto.Association.BelongsTo.after_compile_validation` cannot detect that `Embed` is a module containing a schema because it is not compiled yet. The other associations have nearly identical code and would likely produce the same warning.

To clarify the use case: this is a simplification of a macro called within Embed that produces the Inner module and adds functions to Embed for interacting with it. It is undesirable to split the macro resulting in making multiple calls in different places to produce the same result. 

### Expected behavior

No warning.

Possible approaches:
1. Detect the compilation of an embedded module and to defer the running of the after compile hook (unaware if this is possible or worth the speculative complexity)

2. add an association option that suppresses this kind of warning, i.e. "I know what I'm doing"

**Comment by josevalim** [comment]
Good call. We can detect the parent module and abort the checks based on that. But then it would mean that nothing is checked but that is likely better than a false warning?

**Comment by danj3** [comment]
I think no check/no warn is probably better. The only refinement might be if it is possible to determine the module nesting and not warn if the association is not compiled and is a parent of the module of the current running @after_compile. This would make it possible for associations outside the nesting to be checked as usual... if it is possible.

**Comment by danj3** [comment]
That's exactly it, nicely done. My thanks.
