### ISSUE TITLE
many to many association with length validation not consistent on create and update.

### ISSUE THREAD

**Issue by bartekupartek** [elixir-ecto/ecto#2211]
### Environment

* Elixir version (elixir -v): Elixir 1.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.6.3
* Ecto version (mix deps): 2.2.1 and current master
* Database adapter and version (mix deps): 0.13.3
* Operating system: macOS Sierra

### Current behavior

Room model with `many_to_many :tags, App.Web.Tag, join_through: "rooms_tags", on_delete: :delete_all, on_replace: :delete` association. On creation `validate_length` works as expected, but on update action when I try to put empty `tag_ids` list `validate_length` ignores that I want to insert empty associations.

    %App.Web.Room{name: "test"} 
    |> Ecto.Changeset.change() 
    |> Ecto.Changeset.put_assoc(:tags, []) 
    |> Ecto.Changeset.validate_length(:tags, min: 1, max: 5) 
    |> App.Repo.insert
    {:error,
     #Ecto.Changeset<action: :insert, changes: %{tags: []},
      errors: [tags: {"should have at least %{count} item(s)",
        [count: 1, validation: :length, min: 1]}], data: #App.Web.Room<>,
      valid?: false>}

    tag = %App.Web.Tag{name: %{"en" => "bike"}} |> App.Repo.insert!
    {:ok, room} = %App.Web.Room{name: "test", tags: [tag]} |> App.Repo.insert
  
    %App.Web.Room{__meta__: #Ecto.Schema.Metadata<:loaded, "rooms">, id: 4, name: "test",
     tags: [%App.Web.Tag{__meta__: #Ecto.Schema.Metadata<:loaded, "tags">,
       id: 31, name: %{"en" => "bike"},
       rooms: #Ecto.Association.NotLoaded<association :rooms is not loaded>}]}

    cs = 
      room 
      |> Ecto.Changeset.change() 
      |> Ecto.Changeset.put_assoc(:tags, []) 
      |> Ecto.Changeset.validate_length(:tags, min: 1, max: 5)
    #Ecto.Changeset<action: nil,
     changes: %{tags: [#Ecto.Changeset<action: :replace, changes: %{}, errors: [],
         data: #App.Web.Tag<>, valid?: true>]}, errors: [],
     data: #App.Web.Room<>, valid?: true>

    cs |> Repo.update
    {:ok,
     %App.Web.Room{__meta__: #Ecto.Schema.Metadata<:loaded, "rooms">,
      id: 4, name: "test", tags: []}

It saved empty tags.

I've tried ecto 2.2.1 and current master

### Expected behavior

Shouldn't it act in both actions the same way? I think that tags with replace action should be considered empty.

**Comment by bartekupartek** [comment]
I figured out that validation for minimum length more than 1 is working but for equal 1 it won't add errors, there is a test: [commit](https://github.com/bartekupartek/ecto/commit/69c84c644657febcb7e1367e49f70c0e36edecb8)

**Comment by bartekupartek** [comment]
hmm, maybe add new function `validate_assoc_length` :smiley:

**Comment by josevalim** [comment]
Yeah, the issue here is that length is doing a regular count and you have mixed entries in there. We probably need something specific for associations.

**Comment by bartekupartek** [comment]
There was possible to fetch type of field with list and filter out undesirable changes from association. I've added pull request to review.
