### ISSUE TITLE
Ecto.Query.API.type/2 cannot be used with primary keys anymore

### ISSUE THREAD

**Issue by manukall** [elixir-ecto/ecto#2213]
### Environment

* Elixir version (elixir -v): Elixir 1.5.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): ecto 2.2.1
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: Linux

### Current behavior

I'm not sure if this is a bug or expected behavior due to the disconnect between Ecto types and database types. But here it comes: 

After upgrading Ecto, new tables have a bigint primary key, while `Ecto.Query.API.type/2` still "pretends" they are integers. I've run into this while calling postgres's array_position function and received the error "function array_position(integer[], bigint) does not exist". I was calling that function in a fragment with `...array_position(?, ?)", type(^chart_order, {:array, c.id}), c.id)`.

### Expected behavior

It would be great if `type(123, schema.id)` would still work. Especially as `id` is probably the most popular field, given it's implicitly created.

**Comment by josevalim** [comment]
Can you please provide a test case or a sample code that reproduces the error concretely? For all purposes the code you have described in "Expected behaviour" should work and we don't special case or remove primary key in anyway, so it is likely something else happening here.

**Comment by manukall** [comment]
@josevalim i've added a test at https://github.com/pryin-io/ecto/blob/id_cast_to_integer_not_bigint/integration_test/pg/constraints_test.exs#L112.

this results in 
```
(Postgrex.Error) ERROR 42883 (undefined_function): function array_position(integer[], bigint) does not exist
```

The reason is that `type(^[1,2,3], {:array, c.id})` results in `[1,2,3]::integer` instead of `[1,2,3]::bigint`, which would be the actual type of `c.id` (in an array).

**Comment by josevalim** [comment]
Exactly what I needed, thank you!

**Comment by josevalim** [comment]
So the reason this happens is because `type(..., {:array, c.id})` is going to cause the fragment to be written as `array_position(integer[], bigint)`. Postgres does not like the type mismatch and causes it to fail.

I am not sure if there is something we can do besides introducing a `:biginteger` type so we can properly translate that to the database. Apparently there is no "meta" type we could use for postgres to identify both ints and bigints.

**Comment by michalmuskala** [comment]
What if we always casted ints as bigints for postgres? It would probably manage the downcasting on it's own, right?

**Comment by josevalim** [comment]
@michalmuskala great idea, let me try that out.
