### ISSUE TITLE
Preloading through associations with nils throws error

### ISSUE THREAD

**Issue by khamilowicz** [elixir-ecto/ecto#2216]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version: PostgreSQL 9.6.1
* Ecto version (mix deps): 2.2.2
* Database adapter and version (mix deps): 0.13.3
* Operating system: macOS 10.12.6

### Current behavior

Preloading 'through' associations with 'nil' intermediary causes error (but only if intermediary is already loaded):
```

defmodule User do
   use Ecto.Schema

   schema "users" do
       belongs_to :city, City
       has_one :country, through: [:city, :country]
   end
end

user = struct(User)
%User{city:  #Ecto.Association.NotLoaded<association :city is not loaded>, country: #Ecto.Association.NotLoaded<association :country is not loaded>}
user = Repo.preload(user, [:city, :country])
%User{city: nil, country: nil}
user = Repo.preload(user, [:city, :country])
** (UndefinedFunctionError) function nil.__struct__/0 is undefined or private                                                                                                        
    nil.__struct__()                                                                                                                                                                 
    (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
user = Repo.preload(user, [:city])
%User{city: nil, canton: nil}
```

### Expected behavior

`Repo.preload` shouldn't try to preload through nils but set them to `nil`/`[]`

(This was probably broken in 483fa649dd2adc7afb49a44e0084ed2df794619a)

**Comment by josevalim** [comment]
Thank you, fixed in v2.2 and master. A new release will be out in the next minutes.
