### ISSUE TITLE
Migration task appears to be failing when there are no migrations to run.

### ISSUE THREAD

**Issue by sumerman** [elixir-ecto/ecto#2219]
### Environment

* Elixir version: Erlang/OTP 20; Elixir 1.5.1, 1.4.5 
* Database and version: PostgreSQL 9.6
* Ecto version: 2.2.3
* Database adapter and version: `https://github.com/adjust/postgrex.git` @ `no_tables_on_boostrap`
* Operating system: OS X 10.12.6

### Current behavior

After upgrading to Ecto `2.2.3` when `DBConnection.Sojourn` connection pool is being used and   having `handle_sasl_reports: true` set in a config `mix ecto.migrate` appears (it's a purely cosmetic problem) to be failing when there are no migrations to run.

```
15:34:05.097 [info]  Already up

=SUPERVISOR REPORT==== 15-Sep-2017::17:34:05 ===
     Supervisor: {<0.676.0>,'Elixir.Supervisor.Default'}
     Context:    child_terminated
     Reason:     shutdown
     Offender:   [{pid,<0.680.0>},
                  {id,'Elixir.DBConnection.Watcher'},
                  {mfargs,
                      {'Elixir.DBConnection.Watcher',start_link,[<0.675.0>]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]


15:34:05.097 [error] Child DBConnection.Watcher of Supervisor #PID<0.676.0> (Supervisor.Default) terminated
** (exit) shutdown
Pid: #PID<0.680.0>
Start Call: DBConnection.Watcher.start_link(#PID<0.675.0>)
```

### Expected behavior

`ecto.migrate` should print `Already up` and exit quietly.

**Comment by josevalim** [comment]
Is that really a failure though? SASL reports when processes terminate, even when they do so "cleanly" and that's exactly what the report look like. :)

I mean, you will get a bunch of those reports and they are not necessarily right or wrong. They are just telling you which processes have been spawned.

**Comment by sumerman** [comment]
The last few lines are an error and even highlighted in red when it's enabled. Not a big deal but confusing and makes it harder to spot "already up" message

**Comment by josevalim** [comment]
Hrm, the reason is shutdown and shutdown was not supposed to generate logs afaik? /cc @fishcakez

**Comment by fishcakez** [comment]
Shutdown is generating a log here because the child is shutting down graceful but it is a permanent and this then causes the supervisor to log a shutdown. Can you add an issue to DBConnection to gracefully stop `DBConnection.Ownership` and `DBConnection.Sojourn` internals pools?

**Comment by josevalim** [comment]
@sumerman ping :)

**Comment by sumerman** [comment]
Oh, didn't realize it was @fishcakez was addressing me.

**Comment by josevalim** [comment]
Oh, maybe he wasn't! :D Thanks for doing it then! :heart:
