### ISSUE TITLE
Primary key constraint not changed when renaming table in postgresql

### ISSUE THREAD

**Issue by smartepsh** [elixir-ecto/ecto#2222]
### Environment

* Elixir version (elixir -v): 1.5.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.6
* Ecto version (mix deps): 2.1.6
* Database adapter and version (mix deps): 0.13
* Operating system: OSX

### Current behavior

The primary key index name is not changed

### Expected behavior

 I might be wrong but I expected the index name change to new_table_name_id_pkey.

**Comment by josevalim** [comment]
@smartepsh you need to do it by hand. Postgres doesn't change the name of the primary keys and foreign keys when you rename the table.
