### ISSUE TITLE
Improve the differentiation between cast / dump in Ecto.Type documentation

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#2229]
I've seen quite a few people on slack – as well as myself – initially not really understanding what the difference is for `cast` and `dump` callbacks in ecto types. It would be nice to have an example in the moduledoc, where the following 3 data types would be different to each other.

external data `--(cast)->` internal elixir data `--(dump)->` postgres data

People seem to think cast is for parsing data like this: external data `--(cast)->` postgres data

Sidenote: Having the function`cast/2` and the callback `cast/1` doesn't seem to make the finding the essential information better as the callback docs of `cast/1` do explain the above separation kinda ok. I still think most people will be guided by the big example implementation in the moduledoc.

**Comment by josevalim** [comment]
Can you please send a PR that improves those? One possible example we could use is to have structured data as the app representation but it is converted to a raw map when written to the database.
