### ISSUE TITLE
Dialyzer complains about schema given as module name in Multi.insert_all

### ISSUE THREAD

**Issue by wgslr** [elixir-ecto/ecto#2232]
### Environment

* Elixir version  
  Erlang/OTP 20 [erts-9.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
  Elixir 1.5.1
* Database and version: PostgreSQL 9.6.5
* Ecto version (mix deps): ` locked at 2.2.4 (ecto) defde3c8`
* Database adapter and version (mix deps): `locked at 0.13.3 (postgrex) c277cfb2`
* Operating system: `Linux 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux`

### Current behavior
I have a following function:
```ex
alias Server.User
alias ServerWeb.Repo
alias Ecto.Multi

def insert_multiple_users(users) do
    multi = Multi.insert_all(
      Multi.new,
      :insert_multiple_users,
      User,
      users)
    case Repo.transaction(multi) do
      {:ok, _} -> :ok
      {:error, failed_operation, failed_value, changes_so_far} ->
        {:error, :operation_failed}
    end
  end
```

It is working correcty, but dialyzer reports an error:
```
lib/server/resolvers/user.ex:48: Function insert_multiple_users/2 has no local return
lib/server/resolvers/user.ex:52: The call 'Elixir.Ecto.Multi':insert_all('Elixir.Ecto.Multi':t(),'insert_multiple_users','Elixir.Server.User',users@1::[any()]) will never return since it differs in the 3rd argument from the success typing arguments: ('Elixir.Ecto.Multi':t(),any(),binary() | {'nil' | binary(),binary()} | #{'__struct__':=atom(), atom()=>_},[[{atom(),_}] | map()])
```

If I change `User` to `%User{}` dialyzer says it's all good, but the function stops working.

### Expected behavior
Dialyzer does not report an error.

**Comment by josevalim** [comment]
Fixed on master and v2.2, thanks!
