### ISSUE TITLE
Multiple concurrent migrators should be optional

### ISSUE THREAD

**Issue by tlvenn** [elixir-ecto/ecto#2233]
With the recent commit from @blatyo to add support for multiple concurrent migrators, one side effect is that migrators are now locking the migration table.

The issue is I am using Ecto with CockroachDB, a Postgresql variant which does not support locking and therefore I can't run my migrations anymore on master.

Could we add the support of multiple concurrent migrators behind a flag so that if it's off, we dont lock the migration table ? Or if we want it to be the default, a way to turn it off ?

Thanks a lot in advance.

**Comment by josevalim** [comment]
Hi @tlvenn! Do you have your own adapter or are you using the Postgres adapter?

**Comment by tlvenn** [comment]
I am using a very slight fork from Postgrex just in order to override the query bootstrap function until CockroachDB support correlated subqueries.

Kinda hoping to get rid of that fork soon.

**Comment by josevalim** [comment]
@tlvenn so if I understand correctly you still use Ecto.Adapters.Posgres right? If so, we can provide a repository option called "lock_for_migrations" that defaults to "FOR UPDATE" but you can set it to nil. What do you think? Could you please send a PR?

**Comment by tlvenn** [comment]
Yes I am using `Ecto.Adapters.Postgres` and a repo option called `lock_for_migrations` would be great ! 

Any reason you dont want to simply use a boolean rather than "FOR UPDATE" ? Do you think the locking strategy could / should be pluggable so to speak ?

Happy to work on a PR

**Comment by josevalim** [comment]
@tlvenn I am not sure but given the default is "FOR UPDATE" and you just want to set it to nil, it covers your use case nicely and if someone needs something more in the future it will already be there. It is also less lines of code to implement.

**Comment by tlvenn** [comment]
Oky will submit a PR soon, thanks !

**Comment by blatyo** [comment]
I'm not sure the immediacy of this, but if you need it soon, you can update
your adapter fork to define the `lock_for_migrations` callback and have it
`nil` out the `:lock` option.

Allen Madsen
http://www.allenmadsen.com

On Thu, Sep 21, 2017 at 5:26 AM, Christian Meunier <notifications@github.com

**Comment by tlvenn** [comment]
@blatyo thanks for the tip, I actually dont fork the adapter but the postgresql driver Postgrex but dont worry I believe this should be quick enough.

@josevalim 2 questions for you:

1.  Name of the option: All other migration options are all prefixed with `migration_`. Shouldn't I name this one `migration_lock_type` instead for consistency ?

2. When I lookup repo config in the sql adapter with `{_repo_mod, _pool, default_opts} = lookup_pool(repo)`, any keyword with `nil` value are actually filtered out. Should I use an atom value like `:none` instead ?

Thanks

**Comment by josevalim** [comment]
@tlvenn `:migration_lock` then sounds good. Do you know where we are discarding nil configs? We probably should not...

**Comment by tlvenn** [comment]
`:migration_lock` it is then ;) I don't know where we are discarding nil configs, I will look into it.

**Comment by tlvenn** [comment]
Scratch that, nothing but my brain is discarding nil configs ;)
