### ISSUE TITLE
integer gets cast into Decimal when asserting

### ISSUE THREAD

**Issue by SLOBYYYY** [elixir-ecto/ecto#2234]
## Issue

When I assert the returned `category` of a `product` schema in a test, it gets converted into a `Decimal`

### I have a product schema
```
schema "products" do
    field :name, :string
    field :uuid, :string
    field :slug, :string
    field :description, :string
    field :price, :decimal
    field :category, :integer
    belongs_to :group, Group

    timestamps()
  end
```
### The test
```
test "create_product/1 with valid data creates a product" do
  valid_params = params_with_assocs(:product)
  IO.inspect valid_params
  assert {:ok, %Product{} = product} = Products.create_product(valid_params)
  IO.inspect product
  IO.inspect product.category
  assert product.category == valid_params.category
  assert product.description == valid_params.description
  assert product.name == valid_params.name
  assert product.price == valid_params.price
end
```
### Debug outputs

The output of `IO.inspect valid_params`:
```
%{category: 0, description: "<em>Some product related description</em>",
  group_id: 376, name: "product-3", price: 0,
  slug: "product-3", uuid: "ac5eeaa8-e43c-348f-9684-b4b9b72e9a1d"}
```
The output of `IO.inspect product`:
```
%FarmmixHomepage.Products.Product{__meta__: #Ecto.Schema.Metadata<:loaded, "products">,
 category: 0, description: "<em>Some product related description</em>",
 group: #Ecto.Association.NotLoaded<association :group is not loaded>,
 group_id: 376, id: 670,
 inserted_at: ~N[2017-09-21 09:51:43.500994], name: "product-3",
 price: #Decimal<0>, slug: "product-3",
 updated_at: ~N[2017-09-21 09:51:43.501005],
 uuid: "ac5eeaa8-e43c-348f-9684-b4b9b72e9a1d"}
```
The output of `IO.inspect product.category`:
```
0 
```
### Test output

```
  1) test creating products create_product/1 with valid data creates a product (FarmmixHomepage.ProductsTest)
     test/farmmix_homepage/products/products_test.exs:48
     Assertion with == failed
     code:  assert product.price() == valid_params.price()
     left:  #Decimal<0>
     right: 0
     stacktrace:
       test/farmmix_homepage/products/products_test.exs:57: (test)

```

It also fails for `assert product.price == valid_params.price`

## Expected behavior

Not surprisingly I want the following part to be true:
```
assert product.category == valid_params.category
assert product.description == valid_params.description
assert product.name == valid_params.name
assert product.price == valid_params.price
```
I assume the issue comes from these sources:
 - assert
 - Ecto field resolution
 - equals operator

But still, is this expected behavior?

## Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres 9.5
* Ecto version (mix deps): 2.1.6
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: Linux Mint

**Comment by josevalim** [comment]
@SLOBYYYY you are comparing data.price with params.price and the goal of casting is exactly to convert an external type to your domain type. When you are casting data, it by definition should convert between types.

The price field was declared as:

    field :price, :decimal

So this is expected:

     code:  assert product.price() == valid_params.price()
     left:  #Decimal<0>
     right: 0

For example, you can also pass the price params as a string and it will be cast to a decimal too.

**Comment by SLOBYYYY** [comment]
I feel bad. I did some modification on test generating data for category and it's fine now. The `:price` comparison was stupid from my part because it should fail since I was comparing it to an integer...

Sorry for the mistake @josevalim and thank you for the quick answer!
