### ISSUE TITLE
Handle unique constraint error

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-ecto/ecto#2237]
I am trying to handle the case when `unique_constraint` fails by checking `errors` for a specific key.  So I've checked the source and found that only message is given without any clarification what happened wrong, the expected behaviour is that 
```
errors: [name: {"has already been taken", []}]
```
could contain something like
```
errors: [name: {"has already been taken", [validation: :unique]}]
```
Is there any case that can help me to achieve my goal?

**Comment by josevalim** [comment]
@mojidabckuu the behaviour you proposed is available in master. :)

**Comment by mojidabckuu** [comment]
Hey Jose. Looks this one is missing now.
I've checked the version date around sep 22 and it has the validation key. But current 2.2.7 doesn't 
https://github.com/elixir-ecto/ecto/blob/3a0616a356ecbc3b6ba1e391e785a13f66c13da9/lib/ecto/changeset.ex#L2080

**Comment by josevalim** [comment]
master is going to be 3.0.

**Comment by mojidabckuu** [comment]
Any estimations for 3.0 to become rc?

**Comment by josevalim** [comment]
None so far.
