### ISSUE TITLE
Timeout on running migrations

### ISSUE THREAD

**Issue by tlvenn** [elixir-ecto/ecto#2245]
### Environment

* Elixir version (elixir -v): 1.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): CockroachDB 1.0.6 (pg variant)
* Ecto version (mix deps): Master
* Database adapter and version (mix deps): Postgres
* Operating system: OS X

### Current behavior

Since the commit around how migrations are run (d28aebac6c3b8203750bd23e965a7ba19d42bda6) by @blatyo I have issues running my migrations , Ecto raising the following error:

```
The database for Jumpn.Repo has been dropped
The database for Jumpn.Repo has been created
[debug] QUERY OK source="schema_migrations" db=14.1ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 []
** (exit) exited in: :gen_server.call(Jumpn.Repo.Pool, {:checkout, #Reference<0.1523100713.1094713348.227447>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:214: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:920: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:147: Ecto.Migrator.do_run_maybe_in_transaction/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I have update mix.lock to point to the commit just before 01c47d91249b2a7de2c74ee8a67e32224f2c4771 , then things are working again.

The weird part is initially that migration commit was not working with CDB because it was using a lock "FOR UDPATE" and I contributed a fix to make it work with CDB which I tested and it was working. And now out of the blue, without understanding why, I have this new issue.

I don't really understand what has changed on my side to trigger the issue but it's definitely related with a change on how migrations are being executed.

@blatyo would you have any idea what could cause the issue ?

I wonder if it could have something to do with wrapping migration in a task. Looking at the stack trace above, it seems to indicate that the task is getting a transaction which should not be happening given all my migrations have `@disable_ddl_transaction true`

Thanks in advance.

**Comment by josevalim** [comment]
How big is your pool? You need to have at least 2 connections in your pool
for the new migrations to run. Maybe we should even check for so because
issueing the command.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tlvenn** [comment]
Hi @josevalim , my default pool size is set to `10` so it should not be the reason.

Strangely enough, i have another stack trace now:

```
The database for Jumpn.Repo has been dropped
The database for Jumpn.Repo has been created
[debug] QUERY OK source="schema_migrations" db=5.1ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 []
[info] == Running Jumpn.Repo.Migrations.AddUsers.change/0 forward
[info] create table users
** (exit) exited in: :gen_server.call(Jumpn.Repo.Pool, {:checkout, #Reference<0.922878972.1931739138.68831>, true}, 5000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:214: :gen_server.call/3
    (poolboy) src/poolboy.erl:55: :poolboy.checkout/3
    (db_connection) lib/db_connection/poolboy.ex:41: DBConnection.Poolboy.checkout/2
    (db_connection) lib/db_connection.ex:920: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:262: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:204: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:85: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:85: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:106: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:104: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:28: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:159: Ecto.Migrator.attempt/6
```

At least there is no sign of transaction there anymore but still does not explain why a connection cannot be checkout.

I will try to turn on some debugging on CDB side to check if there is something useful there to understand what is happening.

**Comment by tlvenn** [comment]
So from those 2 traces, it looks like in the first case, Ecto wasn't even able to query the migration table which is done within a transaction and now somehow, it can but cannot run the first migration.

**Comment by blatyo** [comment]
Both stack traces look like it's unable to checkout a connection to run the migration in the time specified. The first wouldn't have made it to the point it did without successfully querying the migrations table.

@josevalim, is it possible connections are checked out, but not checked back in, now that the migrator is using tasks?

@tlvenn how many migrations are you running?

**Comment by josevalim** [comment]
@blatyo they are supposed to be checked back once the process dies... unless there is a bug.

**Comment by tlvenn** [comment]
@blatyo it blocks at the first migration and I have like 12 of them right now. And with the pool size set at 10, even if they were not checked back on, the pool should still have enough connections to run the first migrations...

I am fairly convinced it's an issue triggered by CDB somehow. I am trying to understand how wrapping the migrations with Task is suddenly changing the way Ecto is interacting with CDB.

**Comment by blatyo** [comment]
@tlvenn If I'm reading [this](https://www.cockroachlabs.com/blog/how-cockroachdb-distributes-atomic-transactions/) correctly, CockroachDB appears to globally only support one transaction at a time. If that's the case, I'd diagnose the issue as:

1. `lock_for_migrations` creates a transaction and waits for migrations finish to close it.
2. Your first migration tries to start a transaction, but must wait until `lock_for_migrations` has released the transaction.
3. Deadlock until timeout

As for it working and then not working, the only thing I can think of is if you disabled transactions on migrations.

I suspect you just don't want the `lock_for_migrations` transaction, since the only reason for it is to hold the lock on `schema_migrations` table, which your database doesn't support. Currently, the way to do that is to define your own Ecto adapter and define your own `lock_for_migrations` function like so:

``` elixir
def lock_for_migrations(repo, query, _opts, fun) do
  query
  |> Map.put(:lock, nil)
  |> repo.all()
  |> fun.()
end
```

@josevalim Maybe the new `migration_lock` setting should also disable the transaction?

**Comment by tlvenn** [comment]
Thanks for the follow up @blatyo !

I think the issue comes from the isolation level CDB is operating by default which is `Serializable` while Postgres is using `Read committed` which permits phantom read which is essentially what is happening here if I am not wrong:

1. `lock_for_migrations` is opening a T1 which select all elements from migration table
2. Migration 1 is modifying the migration table
3. T1 has now some phantom reads

I suspect that Postgres with an isolation level of `Serializable` would likely behave the same.
I am surprised no error is raised from the server though and we end up with a deadlock...

**Comment by tlvenn** [comment]
Maybe actually a deadlock is expected while the server is waiting for T1 to be committed and then it would raise.

**Comment by tlvenn** [comment]
If I am not wrong, this shows that this locking strategy for migration is not compatible when the database use `Serializable` for its transaction isolation.

**Comment by blatyo** [comment]
@josevalim It would be possible to support serializable isolation level. It would require a larger refactoring of the migrator though. If that's not what happens, there will at least need to be an off switch and docs about this.

I'll try out changing things to support serializable and we can see how complex it is.

**Comment by josevalim** [comment]
@blatyo isn't the issue DDL transactions though?

@tlvenn the deadlock is on the application side, there are no shared resources, so the server is probably correct in not emitting anything. Maybe we can allow the serialization level to be configured in lock_for_migrations?

**Comment by tlvenn** [comment]
All my migrations use '@disable_ddl_transaction true' so as far as I know, only the `lock_for_migrations` is opening a transaction I think.

Configuring the isolation level to be used for migration would work I believe, CDB can drop to snapshot isolation for a given transaction for example:
> https://www.cockroachlabs.com/docs/stable/transactions.html#isolation-levels

**Comment by blatyo** [comment]
@tlvenn can you try running `mix ecto.migrate --pool-size=2`

**Comment by tlvenn** [comment]
Hi @blatyo, running `mix ecto.migrate --pool-size=2` actually works...

Reading the migration doc again, I realize now that the migrations are run with a pool size of 1 by default if the repo is started as part of running a mix task.

So looks like @josevalim initial intuition was correct and it's indeed a pool size issue when executed within a mix task. Right now the default is 1, we should probably bump it to 2 with the new migration strategy.

**Comment by tlvenn** [comment]
@josevalim shouldn't we make a PR to bump the pool size to 2 by default ?

**Comment by josevalim** [comment]
The PR is already in master. :)

**Comment by tlvenn** [comment]
I guess the PR failed to mention this issue then ;) Thanks a lot by the way.
