### ISSUE TITLE
Migrations: Silent version collision in umbrella apps

### ISSUE THREAD

**Issue by Zeeker** [elixir-ecto/ecto#2250]
### Environment

* Elixir version: 1.5.1
* Database and version: Postgres 9.6.5
* Ecto version: 2.1.0
* Database adapter and version: Postgrex 0.13.3
* Operating system: macOS 10.12.6 (Sierra)

### Current behavior

Let's assume I have an umbrella application with multiple apps. The apps `foo` and `bar` both have their own repo, operating on the same database but each using a different schema in the Postgres database to avoid any collisions.

These two apps both have some migrations and due to unlucky circumstances two of those migrations have the same timestamp. Example:

- `apps/foo/priv/repo/migrations/20170901072523_create_some_foo_table.exs`
- `apps/bar/priv/repo/migrations/20170901072523_create_some_bar_table.exs`

When trying to run migrations in the root folder, only one of the above migrations will be executed. The other will be silently ignored.

### Expected behavior

Both migrations should be run, or a warning should be printed.

## Cause

I've taken a look at the migrator and migration runner. The "issue" lies in the fact that the `schema_migrations` identifies a migration only by it's version number (speak timestamp). 

I'm fully aware of the fact that this is a rare edge case. When each application uses it's own database this is no problem but in this case a silent version collision of two different migrations in two different apps happen.

The main gripe I have with this, is that one migration gets skipped silently. This makes the root cause hard to track down.

## Possible solution?

While I don't think that the migration name should be part of the unique identification of the migration, it should be checked that two separate migrations don't have the same version.

IMHO it would make sense to print a warning when a migration version collides. This could be achieved by persisting the migration name alongside the version, and then compare the name of a possible skipped migration against the list of already run migrations.

**Comment by josevalim** [comment]
How would we know that the migration version collides? Every time you run `ecto.migrate`, you will have a bunch of colliding versions for the migrations you ran in the past. The only alternative is to store the name, which I don't think we should. For example, what if there is a typo in the file that is fixed in another release?

In your case, I would simply give each app a different migration table by using the :migration_source option in the repo configuration (iirc).

**Comment by josevalim** [comment]
Thanks for the report @Zeeker! For now, I recommend for you to use the `:migration_source` option to store them in different tables. If you prefer, you can even send a PR that introduces a `:migration_prefix` if you want to store each migration in a different prefix as well.

**Comment by Zeeker** [comment]
@josevalim I wasn't aware of the `migration_source` option, I'll definitely make use of that for our case. In addition to thinking about a `migration_prefix` wouldn't it make sense to think about a general global `prefix` config per `Ecto.Repo`?

**Comment by josevalim** [comment]
This option is already available as an after_commect callback which can be
used to change the connection scheme as a whole.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
