### ISSUE TITLE
interpolation error in LIKE after upgrading to 2.2.5: (Postgrex.Error) ERROR 42P18 (indeterminate_datatype): could not determine data type of parameter $2

### ISSUE THREAD

**Issue by ZombieHarvester** [elixir-ecto/ecto#2253]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.6.5
* Ecto version (mix deps): 2.2.5
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: MacOS Sierra

### Current behavior

I've started getting `(Postgrex.Error) ERROR 42P18 (indeterminate_datatype): could not determine data type of parameter $2` error after updating ecto from 2.2.4 to 2.2.5

```
stacktrace:
  (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
  (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
  (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

This is the line that causes the error:
`like(i.category, ^"#{category}%")`

Explicitly casting it to string didn't help, same error
`like(i.category, type(^"#{category}%", :string))`

### Expected behavior

No errors

**Comment by josevalim** [comment]
Can you please provide the full query as it is logged?

**Comment by ZombieHarvester** [comment]
```
    query =
      from p in Proposal,
      join: i in Item, on: [proposal_id: p.id],
      where: not is_nil(i.retail_price_with_tax) and
             p.id in ^proposal_ids and
             ilike(i.category, type(^"#{category}%", :string)),
      group_by: p.id,
      select: {
        p.id
      }
```
generated sql
```
{"SELECT p0."id" FROM "proposals" AS p0 INNER JOIN "proposal_items" AS p1 ON p1."proposal_id" = p0."id" WHERE ((NOT (p1."retail_price_with_tax" IS NULL) AND p0."id" = ANY($1)) AND (p1."category" ILIKE $3::varchar)) GROUP BY p0."id"",
 [[1211, 1212], "112122088%"]}
```

**Comment by ZombieHarvester** [comment]
seems like in generated sql there should be `ILIKE $2` insted of `ILIKE $3` since we have only two params

**Comment by josevalim** [comment]
I have pushed a fix to the v2.2 branch, can you please give it a try? Just add to your mix.exs:

     {:ecto, github: "elixir-ecto/ecto", branch: "v2.2", override: true}

If it works, I will ship a new Ecto.

**Comment by ZombieHarvester** [comment]
@josevalim it now works, generated sql shows `ILIKE $2`. thanks

**Comment by josevalim** [comment]
v2.2.6 is out!
