### ISSUE TITLE
Error in subqueries with map updates and virtual fields

### ISSUE THREAD

**Issue by xadhoom** [elixir-ecto/ecto#2260]
### Environment

* Elixir version: 1.5.2
* Database and version: PostgreSQL 9.5
* Ecto version: master at 42d47a6 . Same with lastest 2.2
* Database adapter and version: postgrex master at a6c1f19
* Operating system: Linux Fedora 26

### Current behavior
I'm playing with schema virtual fields in order to select computed values without having to pollute the database with empty fields.
In my use case I'm computing a field using sql functions and the only way to have it in the returned struct is to use schema virtual fields. (and I can also cast it to a custom type!)

Virtual fields are perfect for that, except they won't work within a subquery.
Don't know if is by design or is an issue.

So:
> from u in User, select: %{u | computed: fragment("1")}

works ok, while
>query = from u in User, select: %{u | computed: fragment("1")}
    q = from q in subquery(query), where: q.computed == "1"

Doesn't.
Note that is not a matter of the `where` statement, even something like
>  q = from q in subquery(query), select: q

won't work

The interesting fact is that it fails not at compilation time, but when doing Repo.all(q).
The error is

     ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

         ** (Ecto.QueryError) invalid key `:computed` on map update in subquery in query:

         from u in EctoVirtualsTest.User,
           select: %{u | computed: fragment("1")}

     The subquery originated from the following query:

     from u in subquery(from u in EctoVirtualsTest.User,
       select: %{u | computed: fragment("1")}),
       where: u.computed == "1",
       select: u

and the used schema is here:
https://github.com/xadhoom/ecto_virtuals_test/blob/master/lib/ecto_virtuals_test/user.ex

Is this an issue, or working as expected or simply I'm missing something?

I've setup a demo repo here:
https://github.com/xadhoom/ecto_virtuals_test

with two tests which demonstrate my issue
https://github.com/xadhoom/ecto_virtuals_test/blob/master/test/ecto_virtuals_test_test.exs

### Expected behavior
Same select handling like in "plain" queries.

**Comment by xadhoom** [comment]
A workaround is to add the field into the schema as a non virtual and into database, like any other field.
This pollutes the tables (unused fields) but works.

**Comment by xadhoom** [comment]
the user [kylethebaker](https://elixirforum.com/u/kylethebaker) on the forum pointed out another solution, which may be the correct way or a workaround: https://elixirforum.com/t/ecto-subqueries-with-virtual-fields/9075/13?u=xadhoom

Basically using the select_merge statement and not doing the map update in the subquery does the trick:
> query = from u in User, select_merge: %{computed: fragment("1")}
> q = from q in subquery(query), where: q.computed == "1"

**Comment by josevalim** [comment]
We should probably make it work and if it doesn't raise an appropriate error message.

**Comment by josevalim** [comment]
Fixed in master and backported to v2.2 branch.
