### ISSUE TITLE
Parameters are not passed inside the parentheses in the COPY (...) TO query

### ISSUE THREAD

**Issue by anronin** [elixir-ecto/ecto#2261]
### Environment

* Elixir version (elixir -v): Elixir 1.6.0-dev (921f17e21)
* Database and version: PostgreSQL 9.6
* Ecto version (mix deps): ecto 2.1.4
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: Ubuntu 17.04

### Current behavior

I'm trying to export data from db to csv file for current user and get some strange error.
To simplify my request, I will give an example:
```
> Repo.query("COPY (SELECT email FROM subscribers WHERE user_id = $1) TO STDOUT WITH CSV", [46])

[debug] QUERY ERROR db=12.5ms
COPY (SELECT email FROM subscribers WHERE user_id = $1) TO STDOUT WITH CSV [46]
** (ArgumentError) parameters must be of length 0 for query %Postgrex.Query{columns: nil, name: "", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.4255116697.961806337.10297>, result_formats: [], result_oids: nil, result_types: nil, statement: "COPY (SELECT email FROM subscribers WHERE user_id = $1) TO STDOUT WITH CSV", types: {Ecto.Adapters.Postgres.TypeModule, #Reference<0.4255116697.952238081.65717>}}
    (postgrex) lib/postgrex/query.ex:49: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1071: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:93: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
```

I'm not sure if this is a bug or I'm doing something illegal, because, for example this works as expected

```
> Repo.query("(SELECT email FROM subscribers WHERE user_id = $1)", [46])                        

[debug] QUERY OK db=23.4ms decode=1.1ms
(SELECT email FROM subscribers WHERE user_id = $1) [46]
{:ok,
 %Postgrex.Result{
   columns: ["email"],
   command: :select,
   connection_id: 1425,
   num_rows: 10006,
   rows: [["testuser10000@example.com"], [...], ...]
 }}
```
### Expected behavior

If I do not pass parameters and I specify it manually, then everything works

```
> Repo.query("COPY (SELECT email FROM subscribers WHERE user_id = 46) TO STDOUT WITH CSV")      

[debug] QUERY OK db=19.1ms decode=0.3ms
COPY (SELECT email FROM subscribers WHERE user_id = 46) TO STDOUT WITH CSV []
{:ok,
 %Postgrex.Result{
   columns: nil,
   command: :copy,
   connection_id: 1427,
   num_rows: 10006,
   rows: ["testuser10000@example.com\n"...]
 }}
```

I suspect that somewhere there is a mistake but I do not know where, any thoughts?

**Comment by josevalim** [comment]
I believe Postgres' COPY does not allow parameters to be given. They need to be passed in the query as you specified.

**Comment by anronin** [comment]
but I specify parameters for `query` inside parentheses and not for COPY, is there are some workaround, because query may be very complex?

**Comment by josevalim** [comment]
The outer expression is still a COPY. I am not sure if there is a workaround when this is a Postgres limitation.

**Comment by xadhoom** [comment]
Why not just pass the interpolated string ?

<pre>
iex(17)> id = 1
1
iex(18)> q = "COPY (SELECT username FROM users WHERE id = #{id}) TO STDOUT WITH CSV"
"COPY (SELECT username FROM users WHERE id = 1) TO STDOUT WITH CSV"
iex(19)> Repo.query(q)
[debug] QUERY OK db=2.3ms queue=0.1ms
COPY (SELECT username FROM users WHERE id = 1) TO STDOUT WITH CSV []
{:ok,
 %Postgrex.Result{columns: nil, command: :copy, connection_id: 9588,
  num_rows: 1, rows: ["admin\n"]}}
</pre>

**Comment by anronin** [comment]
it's simplified query, it's maybe very complex with 5-6 params and may vary

**Comment by xadhoom** [comment]
well, if you're building a complex query for Repo.query API, it always a string, so you may interpolate as many parameters as needed.
Obviously you need to take care of escaping.

Another issue is if you're trying to do it using the Ecto query DSL.

**Comment by anronin** [comment]
i need to use COPY as its fastest variant and no need to use something like `CSV.encode` from https://github.com/beatrichartz/csv, but `query` may vary from that simply as above for all subscribers for user, and maybe only from the list (for that query, i use Ecto query dsl). And for that complex query, i got an error

**Comment by josevalim** [comment]
> it's simplified query, it's maybe very complex with 5-6 params and may vary. So maybe there is function that take query and return sql string with interpolated params, but i didn't find it?

There isn't because Ecto never interpolates those. We always pass them as parameters to the query, which is something that may not be possible in COPY. Which puts us back in the starting place.

**Comment by anronin** [comment]
i get it, but maybe if i can prepare query and then interpolate it to COPY, `some_func` maybe: 
```
prepared_query = some_func(Ecto.Query) => "SELECT username FROM users WHERE id = 45 AND suppressed_at IS NULL and consent = 2...."

Repo.query("COPY (#{prepared_query}) TO STDOUT WITH CSV)
```
?

**Comment by josevalim** [comment]
We have no plans for introducing this for this particular feature only. That's why it is probably best for you to tackle that in your app.

**Comment by josevalim** [comment]
Confirmed this is a Postgres issue. Params can't be given to query so you should interpolate them yourself.
