### ISSUE TITLE
Enhancement for `Ecto.Query.group_by` docs

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#2287]
### Environment

* Elixir version (elixir -v):
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps):
* Operating system:

### Current behavior

The docs of `Ecto.Query.group_by` do mention that one can supply a list of fields, but there's not really a good example to go with it. 

From the current text `group_by also accepts a list of atoms where each atom refers to a field in source.` I'd do expect something like this to work:

```elixir
from i in Item, 
group_by: [:id, :name]
```
What I'm missing is how to group by various fields from different sources:

```elixir
from i in Item, 
join: c in assoc(i, :category)
group_by: [i.id, c.name]
```
This seems to work, but I wouldn't necessarily expect `i.id` or `c.name` to be an atom like mentioned in the explaining text.

### Expected behavior

Maybe this can be explained a bit more eloquently and an example might not hurt as well.

**Comment by ericmj** [comment]
We can add example taking a list like you proposed. A PR would be appreciated.
