### ISSUE TITLE
Possible multi-process transaction side effect visibility bug

### ISSUE THREAD

**Issue by freshtonic** [elixir-ecto/ecto#2301]
For a test that reproduces the issue see: https://github.com/team-alembic/possible-ecto-concurrency-and-transactions-bug/blob/master/test/possible_ecto_transaction_bug_test.exs 

### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

```
psql --version
psql (PostgreSQL) 9.6.2
```

* Ecto version (mix deps):

`2.2.6`

* Database adapter and version (mix deps):

`postgrex 0.13.3`

* Operating system:

`macOS High Sierra`

### Current behavior

The effect of a committed transaction in an ExUnit test is not visible from another process that is spun up *after* the transaction is committed. I'm using the `Sandbox` mode `:auto` which I believe gives me the ability to control my own transactions within a unit test.

### Expected behavior

That the side effect (new record in the database) is visible from another process.

**Comment by freshtonic** [comment]
For reference, this is the failing test from the referenced git repo:

**Comment by freshtonic** [comment]
The failing line is:

**Comment by josevalim** [comment]
@freshtonic `:auto` means the transactions are checked out automatically but each test and each process still runs on their own transaction/connection. If you want to share them, you need to explicitly allow processes or you need to set the mode to shared.

**Comment by freshtonic** [comment]
@josevalim I *want* each process to have its own transaction and connection. That is what I’m trying to test. Database transaction semantics should ensure visibility of committed transactions to other connections. If using auto my test should have a different connection to the asynchronous task, right? If so then any committed transaction in the test should be visible from the task.

Is this just a limitation of the Sandbox? 

When I’m back in front of a computer i’ll try to reproduce the issue as two psql sessions to illustrate what I want. I don’t think shared mode is what I want.

**Comment by josevalim** [comment]
> Is this just a limitation of the Sandbox?

Yes, the sandbox creates its own transaction that *you cannot commit* to guarantee that the work in one test cannot be seen by others. This means that you need to explicitly list which other processes collaborate with a given test process.

**Comment by freshtonic** [comment]
@josevalim ok that mostly makes sense. I was under the false impression that it was possibly to bust out of that behaviour using auto.

**Comment by josevalim** [comment]
@freshtonic you can explicitly checkout a connection and disable the sandbox: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/sql/sandbox.ex#L457

But then it means any change you do in the database in that test will be visible on **all tests**. If you want to have collaboration between processes in your tests while still using the sandbox, then the answer is using the allowance mechanism or the shared mode.

**Comment by freshtonic** [comment]
@josevalim That cleared up my misunderstanding and now I have a passing test. Thanks mate!
