### ISSUE TITLE
"in" operator does not work when using an Array variable.

### ISSUE THREAD

**Issue by yukilau99** [elixir-ecto/ecto#2302]
### Environment

* Elixir version (elixir -v) : 1.5.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Oracle 11
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): Ecto.Adapters.Jamdb.Oracle
* Operating system: Mac Sierra

### Current behavior
When I use a ^variable in "where", the query sql is became "= ANY($1)"
iex(6)> ids=[1,2]
[1, 2]
iex(7)> from(p in Promotion, select: p, where: p.promotion_id in ^ids) |> Repo.all  
[debug] QUERY OK source="promotions" db=2.2ms queue=0.1ms
SELECT p0."id", p0."name", p0."promotion_id", p0."status", p0."inserted_at", p0."updated_at" FROM "promotions" AS p0 WHERE **(p0."promotion_id" = ANY($1)) [[1, 2]]**

And if I wrote the array in query directly, it works.
from(p in Promotion, select: p, where: p.promotion_id in [1, 2]) |> Repo.all
[debug] QUERY OK source="promotions" db=1.4ms
SELECT p0."id", p0."name", p0."promotion_id", p0."status", p0."inserted_at", p0."updated_at" FROM "promotions" AS p0 WHERE (p0."promotion_id" **IN (1,2)**) []

And it works on ECTO version of 2.1.4
### Expected behavior
Cast the "where: p.promotion_id in ^ids" to the right sql.

**Comment by josevalim** [comment]
Thanks for the report @yukilau99!  What is wrong about this query?

> SELECT p0."id", p0."name", p0."promotion_id", p0."status", p0."inserted_at", p0."updated_at" FROM "promotions" AS p0 WHERE (p0."promotion_id" = ANY($1)) [[1, 2]]

It seems to be the correct query to me? That's how you do a dynamic array lookup in PostgreSQL.

**Comment by yukilau99** [comment]
Oh, Sorry, I think this is the bug of Ecto.Adapters.Jamdb.Oracle. thanks for reply.

**Comment by josevalim** [comment]
:D
