### ISSUE TITLE
Bad ordering of interpolated expression when running `update_all`

### ISSUE THREAD

**Issue by into-resurrection** [elixir-ecto/ecto#2303]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2 (Erlang/OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.7.16
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): mariaex 0.8.3
* Operating system: macOS High Sierra version 10.13.1

### Current behavior

When I run an update_all, it doesn't update the specified row. Examining the query that is produced shows that it fails due to sticking the join interpolated value at the end instead of the beginning of the list:

```elixir
user = %User{id: 2, email: "foo@example.com", first_name: "needs", last_name: "changing"}
changeset = User.changeset(user, %{first_name: "José", last_name: "Valim"})
query = 
  from p in "people", join: u in "users",
  on: p.id == u.person_id and u.id == ^changeset.data.id,
  update: [set: ^Map.to_list(changeset.changes)]

Ecto.Adapters.SQL.to_sql(:update_all, Repo, query)
# => {"UPDATE `people` AS p0 INNER JOIN `users` AS u1 ON (p0.`id` = u1.`person_id`) AND (u1.`id` = ?) SET p0.`first_name` = ?, p0.`last_name` = ?",
#    ["José", "Valim", 2]}
```

### Expected behavior

I expect the list of values to use in the query to be in the correct order so that my update will work:
`[2, "José", "Valim"]`

**Comment by josevalim** [comment]
Maps have no order, so you will need to convert the fields to a list and then sort them in the order you expect.

**Comment by into-resurrection** [comment]
Who cares about the order of Maps? I don't care about the order of `first_name` and `last_name` (the only fields in the `Ecto.Changeset.changes` map) I care about the fact that `^changeset.data.id` is thrown at the end of the interpolated values list instead of at the beginning.

**Comment by josevalim** [comment]
Oops, sorry. I missed the `^changeset.data.id` on first look and saw only the `set` operation. Yup, this is a bug, thanks!
