### ISSUE TITLE
no way to work with sqlite "in memory"/temporary database 

### ISSUE THREAD

**Issue by anuragpeshne** [elixir-ecto/ecto#2305]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): sqlite3
* Ecto version (mix deps): ecto 2.2.6
* Database adapter and version (mix deps): esqlite 0.2.3
* Operating system: macOS 10.13.1

### Current behavior

I'm trying to use ([Sqlite "in memory" database](https://sqlite.org/inmemorydb.html)) by passing database name as `:memory:` or passing empty string (which results in temporary database). In both cases the database cease to exist after connection to database is closed.
The way ecto process works (or the way I could find), I have to first run `mix ecto.create` and `mix ecto.migrate` before running the actual application. But this would not work with these kind of database since the table created by `mix ecto.create` will cease to exist as soon as the process terminates.

### Expected behavior

Another way of creating tables, so that every time application runs, new tables can be created.

**Comment by ericmj** [comment]
Ecto does ship with support for sqlite, if you have any issue or questions please raise them with your Ecto adapter first.

**Comment by anuragpeshne** [comment]
This isn't an issue with sqlite adapter. This is issue with working with any temporary database which will cease to exist when connection to it is closed.
So, when you do `mix ecto.migrate`, tables will be created and then database will be destroyed as soon as `mix` completes. Subsequent calls to database/tables from `mix test` or escripts will fail.

There needs to be some way to create tables programmatically.

**Comment by ericmj** [comment]
If you need to run migrations when the application is started you can use the `Ecto.Migrator` API to programmatically run migrations. You can also run normal queries with your query adapter or with `Ecto.Adapters.SQL.query/4` if your adapter supports that.
