### ISSUE TITLE
Where clause, multiple :in conditions, consecutive numbering.

### ISSUE THREAD

**Issue by vstavskyi** [elixir-ecto/ecto#2306]
For multiple conditions, like `where: e.var2 in ^vars2_list or e.var3 in ^var3_list`,  my adapter generates this string:
`SELECT e0.var1 FROM test e0 WHERE (e0.var2 IN (:1,:2,:3,:4) OR e0.var3 IN (:1,:2,:3,:4))`
I'd like to change it to:
`SELECT e0.var1 FROM test e0 WHERE (e0.var2 IN (:1,:2,:3,:4) OR e0.var3 IN (:5,:6,:7,:8))
`
My code is based on reference adapter's code, and I think it has the same problem.
I've found constructor with indices for ANY.
`expr(left, sources, query), " = ANY($", Integer.to_string(ix + 1), ?)
`
But, where is constructor with indices for IN ?
`expr(left, sources, query), " IN ($", Integer.to_string(ix + 1), ?)
`

Could you realize in your reference postgres adapter consecutive numbering for bind variables using Agent or smth else.

**Comment by josevalim** [comment]
You don't need to use an agent, rather you need to pass a state as you generate the SQL string, so you can properly check the current entries.
