### ISSUE TITLE
Confusing error message when using Repo.transaction with an invalid argument

### ISSUE THREAD

**Issue by bellp** [elixir-ecto/ecto#2307]
### Environment

* Elixir version 1.5.2
* Postgres 9.6.5
* Ecto version 2.1
* Postgrex 0.12
* MacOS High Sierra

### Current behavior

I'm new to Ecto, and gave Repo.transaction a changeset instead of a Multi (my bad). However I found it very difficult to understand the error message given when passing a bad value to Repo.transaction/1 (see error below). I didn't explicitly call Multi.__apply__ and seeing it in the error message caused confusion.

iex(1)> Vendorhawk.Repo.transaction(42)
** (FunctionClauseError) no function clause matching in Ecto.Multi.__apply__/4

    The following arguments were given to Ecto.Multi.__apply__/4:

        # 1
        42

        # 2
        Vendorhawk.Repo

        # 3
        #Function<8.51665699/1 in Ecto.Repo.Queryable.transaction/4>

        # 4
        #Function<9.51665699/1 in Ecto.Repo.Queryable.transaction/4>

    Attempted function clauses (showing 1 out of 1):

        def __apply__(%Ecto.Multi{} = multi, repo, wrap, return)

    (ecto) lib/ecto/multi.ex:392: Ecto.Multi.__apply__/4
    (ecto) lib/ecto/repo/queryable.ex:21: Ecto.Repo.Queryable.transaction/4

### Expected behavior

I'd like to see an error showing what type is expected by Repo.transaction vs what I passed in... leaving __apply__ out of the message.

Thanks!
Peter

**Comment by michalmuskala** [comment]
The 2.2 branch will match on the argument earlier in the stack and should produce a more usable error. This is what you get on current ecto:
<img width="728" alt="screen shot 2017-11-13 at 20 24 35" src="https://user-images.githubusercontent.com/477062/32744699-b61cf6ce-c8b0-11e7-8349-2028976dc554.png">
