### ISSUE TITLE
Ecto not properly escaping UUID's in `in` clause

### ISSUE THREAD

**Issue by blatyo** [elixir-ecto/ecto#2309]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

9.6.1

* Ecto version (mix deps):

2.2.6

* Database adapter and version (mix deps):

postgrex 0.13.3

* Operating system:

OSX 10.11.5

### Current behavior

``` elixir
query = 
  from s in Schedule, 
    where: s.profile_id in ["c9c9f753-b099-4281-8670-85e93b28af98"])

Repo.to_sql(:delete_all, query)
# => {<<68, 69, 76, 69, 84, 69, 32, 70, 82, 79, 77, 32, 34, 115, 99, 104, 101, 100,
#   117, 108, 101, 115, 34, 32, 65, 83, 32, 115, 48, 32, 87, 72, 69, 82, 69, 32,
#   40, 115, 48, 46, 34, 112, 114, 111, 102, 105, 108, 101, 95, ...>>, []}
```

When this SQL executes, it generates:

`(Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0xa2`

### Expected behavior

Valid byte sequence is generated.

### Workaround

Using the pin operator allows this to work, but shouldn't be necessary.

``` elixir
query = 
  from s in Schedule, 
    where: s.profile_id in [^"c9c9f753-b099-4281-8670-85e93b28af98"])

Repo.to_sql(:delete_all, query)
#=> {"DELETE FROM \"schedules\" AS s0 WHERE (s0.\"profile_id\" IN ($1))",
# [<<201, 201, 247, 83, 176, 153, 66, 129, 134, 112, 133, 233, 59, 40, 175, 152>>]}
```

**Comment by josevalim** [comment]
You need to use the pin operator. If you are not using the pin operator, we will send it as is to the database. For example, if you do `f.some_integer_field == "13"`, we won't cast the string to integer as well. It is all up to the DB and changing that may have some consequences in other types, such as date/times, where the DB can accept a wider variety of formats.

**Comment by blatyo** [comment]
@josevalim Are you saying that depending on the DB, they may allow the UUID literal above, so it's not possible to raise an error like this?

``` elixir
query = 
  from s in Schedule, 
    where: s.profile_id in ["1"]

Repo.to_sql(:delete_all, x)
#=> (Ecto.QueryError) iex:9: value `"1"` cannot be dumped to type Ecto.UUID. Or the value is incompatible or it must be interpolated (using ^) so it may be cast accordingly in query
```

**Comment by josevalim** [comment]
@blatyo actually, that's a good counter example to what I said. We already dump the values. We could cast them too, although it is feels conceptually wrong for some reason.

Thoughts @michalmuskala and @ericmj?

**Comment by michalmuskala** [comment]
Isn't the problem in here that once we dump the UUID it's a plan binary. We dan try to include this binary without encoding in the query and it breaks since it's arbitrary bytes.

**Comment by josevalim** [comment]
Ah yes, you are right. We would then need to make it a parameter.

**Comment by michalmuskala** [comment]
I proposed some time ago that we use parameters for all literals in queries, but I'm not sure what impact that would have.

**Comment by ericmj** [comment]
Using parameters when we can use literals makes it harder for the optimizer and you need to give more hints to the type inference. It's likely that the new required hints will break peoples code.

**Comment by ericmj** [comment]
The problem is that we use `dump` for literal values when `dump` is supposed to be used for wire values.

We have a few ways to solve this:

1. Introduce a new `Ecto.Type` callback function for query literals
1. Only allow literals for ecto built-in types and have custom code to produce literals for all built-in types, this way we can support more types in literals such as datetime types
1. Dump UUIDs in the text format (xxx-yyy-zzz) and add a postgrex extension that supports both the binary and text formats
1. Stop supporting UUID literals and figure out a way to give a good error message

I'm leaning more towards 2 or 3.

**Comment by blatyo** [comment]
@michalmuskala One reason I would be opposed to always using parameters for literals is that all `in` clauses would turn into `= ANY` instead of `in`, which means that indexes for the column cannot be used in Postgres.

@ericmj My vote would be for 1 or 2. 1 is nice because the new callback can default to `dump` for existing behavior and be overridden for the cases that don't work. It also seems to be the place where most of this work tends to happen. 2 is nice because it allows extensibility outside of Ecto.

**Comment by ericmj** [comment]
@blatyo Postgres can use an index for `= ANY` in this case even if the value is parameterized.
