### ISSUE TITLE
unique index name inference inconsistency

### ISSUE THREAD

**Issue by dustinfarris** [elixir-ecto/ecto#2311]
### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.1
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): postgres 0.13.3
* Operating system: OSX and Debian

### Current behavior

I am having an issue with underscores where the index name generated in a migration is not matching the index name inferred in a changeset constraint.

When naming tables, i use single underscores to delimit a context and schema, and a _double underscore_ to delimit a join.  This is how Django does it.

For example, if I have a logical join table between a "person" in my system and a user id in a third-party (like twitter):

```ex
defmodule Website.Twitter.UserPerson do
  use Ecto.Schema
  
  alias Website.Accounts

  schema "twitter_users__accounts_people" do
    field :twitter_id, :string
    belongs_to :person, Accounts.Person
  end
end
```

I'll add a unique index using **[`Ecto.Migration.unique_index`](https://hexdocs.pm/ecto/Ecto.Migration.html#unique_index/3)** so that twitter id is only added once.

```ex
def change do
  create table(:twitter_users__accounts_people) do
    add :twitter_id, :string
    add :person_id, references(:accounts_people)
  end

  create unique_index(:twitter_users__accounts_people, [:twitter_id])
end
```

Ecto will generate an index _with the double underscore trimmed to a single underscore_.

```
Indexes:
    "twitter_users_accounts_people_twitter_id_index" UNIQUE, btree (twitter_id)
```

This is inconsistent with how **[`Ecto.Changeset.unique_constraint`](https://hexdocs.pm/ecto/Ecto.Changeset.html#unique_constraint/3)** works!

If I have an insert operation, e.g.:

```ex
change(%Twitter.UserPerson{}, twitter_username: "already joined!")
|> put_assoc(:person, person)
|> unique_constraint(:twitter_username)
|> Repo.insert()
```

I get an error:

```
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

         * unique: twitter_users_accounts_people_twitter_id_index

     If you would like to convert this constraint into an error, please
     call unique_constraint/3 in your changeset and define the proper
     constraint name. The changeset defined the following constraints:

         * unique: twitter_users__accounts_people_twitter_id_index
```

the constraint is using the actual table name with the _double underscore_.

### Expected behavior

`Ecto.Changeset.unique_constraint` and `Ecto.Migration.unique_index` should be consistent in how they infer the name of an index.

### Workaround

I know that I can explicitly add a `name` option to unique_constraint to override the inferred name.  This issue is about the inconsistency only.

**Comment by michalmuskala** [comment]
I think the problem is in the logic that generates the index name for the migration:

https://github.com/elixir-ecto/ecto/blob/48607c72c07f7cea08f0b943431c41a1bc8bdeda/lib/ecto/migration.ex#L583-L590

**Comment by josevalim** [comment]
Yeah, we should align the migration code with the changeset code. PR please?

**Comment by albertoalmagro** [comment]
Lets give this some love. I'll try this one.

**Comment by josevalim** [comment]
Please go ahead!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
