### ISSUE TITLE
DateTime microsecond precision is not respected

### ISSUE THREAD

**Issue by AntonShevel** [elixir-ecto/ecto#2314]
### Environment

* Elixir version: Elixir 1.5.2
* Ecto version (mix deps): Ecto 2.2.6
* Database adapter and version (mix deps): Postgrex 0.13.3
* Operating system: macos 10.12.6

### Current behavior

```
# create a new date
{:ok, date, _} = DateTime.from_iso8601("2017-11-20T14:04:42.878567Z")
# change the precision
date = Map.put(date, :microsecond, {878567, 3})
# make some query and execute it
query = Ecto.Query.from u in App.User, where: u.updated_at > ^date
App.Repo.all(query)
```
Query it makes
```
QUERY OK source="users" db=10.8ms queue=0.2ms
SELECT u0."id", u0."email", u0."first_name", u0."last_name", u0."avatar", u0."sex", u0."inserted_at", u0."updated_at" 
FROM "users" AS u0 WHERE (u0."updated_at" > $1) [{{2017, 11, 20}, {14, 4, 42, 878567}}]
```
As you can see it does not respect microsecond precision, and uses `878567`

### Expected behavior (according to my assumptions:) )

It makes a query using the date with millisecond precision: `878`

For now, In order to achieve needed behavior, I have to truncate microseconds
```
date = Map.put(date, :microsecond, {878000, 3})
```

Is it an expected behavior?

**Comment by josevalim** [comment]
It is expected because the data in the DateTime is invalid. You have to put `{878000, 3}`. Elixir v1.6 is adding DateTime.truncate to help exactly with that.

**Comment by AntonShevel** [comment]
Thanks @josevalim
