### ISSUE TITLE
Nested schemaless changesets

### ISSUE THREAD

**Issue by imranismail** [elixir-ecto/ecto#2321]
I'm wondering if this is supported right now?

I am trying to build a helper macro for doing request parameter validation but am stuck at implementing a solution for nested parameter

Gist below:

https://gist.github.com/imranismail/eb60c709b230c1cbf344553888b9387d

**Comment by michalmuskala** [comment]
No, this is not supported right now.

**Comment by aaronrenner** [comment]
It would be really great if we could use embeds with schemaless changesets. Ecto is awesome for casting JSON data into structs, but it gets difficult when the JSON contains several levels of nesting.

**Comment by kdawgwilk** [comment]
Is this still not supported? If not, is this something the project owners would be okay with as a new feature?  I would like to possibly implement this if there is a desire to have it.
