### ISSUE TITLE
Conflict target repo test can fail due to id collision race condition

### ISSUE THREAD

**Issue by fishcakez** [elixir-ecto/ecto#2323]
### Environment

* Elixir version (elixir -v): Any
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): SQL
* Ecto version (mix deps): master
* Database adapter and version (mix deps): Any
* Operating system: Any

### Current behavior

```
  1) test upsert via insert_all on conflict replace_all and conflict_target (Ecto.Integration.RepoTest)
     integration_test/cases/repo.exs:1541
     ** (Postgrex.Error) ERROR 23505 (unique_violation): duplicate key value violates unique constraint "posts_pkey"
     
         table: posts
         constraint: posts_pkey
     
     Key (id)=(252) already exists.
     code: TestRepo.insert_all(Post, changes, on_conflict: :replace_all, conflict_target: :uuid)
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:202: Ecto.Adapters.SQL.query!/4
       (ecto) lib/ecto/adapters/postgres.ex:92: Ecto.Adapters.Postgres.insert_all/7
       (ecto) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/7
       integration_test/cases/repo.exs:1558: (test)
```

On that line the id of the first post is being set to the id of the second post before second post id is incremented. I am able to repeat this on a machine the majority of the time with `MIX_ENV=pg mix test --seed=934285` 

### Expected behavior

IDs should not collide and tests should pass.

**Comment by josevalim** [comment]
@fishcakez we are likely conflicting with IDs created in another test, right? Maybe should we increment it by thousands instead of 2?

**Comment by fishcakez** [comment]
@josevalim I believe its conflicting with IDs in same test

**Comment by josevalim** [comment]
Does it happen if you only run that single test by giving it the file:line?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
@josevalim it requires the following async ordering:

1) Test inserts first post: id = n
2) Another test inserts a post: id = n + 1
3) Test inserts second posts: id = n + 2

Therefore when we update the first post to id = n + 2 we get duplicate keys. If we reorder the posts ordering in the changset it should be fixed. This module uses TestRepo so writes in other tests are invisible but will block on locks.

**Comment by josevalim** [comment]
Ok, that’s what I meant but I did not express myself well!

Any other suggestion besides using a larger number for bumping IDs? Besides
making the tests sync?


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
I think the other way would be to use `post_second.id + 1` and `post_second.id + 2` for the ids, i.e. ensure the first posts id gets bumped above the second posts id, and the second posts id gets bumped above that.

**Comment by josevalim** [comment]
I think we would still have a race with a test introducing an ID right
after that.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
I don't think we would because we are inside the sandbox in this test.
