### ISSUE TITLE
Make Changeset.cast accept only atoms

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2325]
Today, is't quite confusing that some changeset functions accept strings for field names, while others accept atoms. On couple occasions there were people confused about this on slack channel, who didn't know why their `cast` call was working OK, while `validate_required` was failing.

I suggest changing `cast` to accept only a list of atoms.

Unfortunately, this might be a disruptive change and I'm not sure what would be the best way to handle it, or even if it's really worth it. Maybe a warning instead of an outright error would be better?

**Comment by josevalim** [comment]
Definitely a warning.

**Comment by ybod** [comment]
Can I take a look at this?

**Comment by josevalim** [comment]
Yes pls.
