### ISSUE TITLE
Remove extra files from Hex bundle

### ISSUE THREAD

**Issue by yordis** [elixir-ecto/ecto#2326]
I noticed that you push `~w(integration_test/cases integration_test/sql integration_test/support)` to Hex, which I dont see the point of me downloading those files when I use `Ecto` as a dependency, unless I am missing somebody about it.

**Comment by josevalim** [comment]
It is necessary for external adapters built on top of Ecto to test
themselves.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by yordis** [comment]
@josevalim `testing` no for me when I use it as a dependency. 

I totally understand why those files should be on the project but I dont need them when I download the Ecto package as a dependency

**Comment by michalmuskala** [comment]
The whole set of integration tests is a little over 200KB vs 1.2MB for the whole ecto package. I really don't think this is going to cause problems and makes the life of adapter maintainers much easier.

**Comment by yordis** [comment]
@michalmuskala oh so some adapters actually use it for testing propose, is that right? 

And I actually do not have any issues with it outside of trying to rise awareness of what gets push to hex.pm

**Comment by michalmuskala** [comment]
Yup, I think all of them do in some way:

https://github.com/ankhers/mongodb_ecto/blob/master/test/ecto_test.exs
https://github.com/findmypast-oss/mssql_ecto/blob/f0fc8d3ef31c8f7c484d5092d21e4536086e273e/test/test_helper.exs
https://github.com/scouten/sqlite_ecto2/blob/master/integration/sqlite/all_test.exs
https://github.com/Nebo15/ecto_mnesia/blob/master/test/integration/integration_test.exs
