### ISSUE TITLE
ERROR 42883 (undefined_function): function is_nil(bigint) does not exist

### ISSUE THREAD

**Issue by ANujDixit** [elixir-ecto/ecto#2328]
### Environment
* Database : PostgreSQL 9.6
* Phoenix : 1.3

### Current behavior
query = from u in User,
                distinct: u.id,
                full_join: m in Membership, on: m.company_id == u.id,
                full_join: g in Group, on: m.group_id == g.id,
                where: u.company_id == ^company_id,
                select: %{id: u.id, name: u.name, username: u.username, m_id: m.id,
                          is_present: fragment("CASE when is_nil(?) THEN false ELSE true END", m.id)}
        query 
        |> Repo.all()  

[%{id: 1, is_present: true, m_id: 1, name: "test", username: "test@gmail.com"},
 %{id: 24, is_present: true, **m_id: nil,** name: "vsbdvjsdv", username: "sdnvkdvn@gmail.com"}]

### Expected behavior

is_present should be populated as false if m.id is nil

**Comment by zachdaniel** [comment]
you're putting `is_nil` inside of the fragment, meaning that it is trying to use a postgres function called `is_nil` that does not exist. What you'd want to do is

```
is_present: fragment("CASE when ? THEN false ELSE true END", m.id", is_nil(m.id))
```
However, with that said, you don't really need any of that

You can just say `is_present: is_nil(m.id)` and it will do what you want.

**Comment by josevalim** [comment]
Thanks @zachdaniel!
