### ISSUE TITLE
`replace_all` replaces `id` field on conflict

### ISSUE THREAD

**Issue by tpitale** [elixir-ecto/ecto#2329]
I'm using `on_conflict: :replace_all` in a few places, and in some cases I only want to update all fields, _except_ `id`. But … if the `conflict_target` is not `id` but some other unique index (for example) the `id` will be replaced with a new serial value when using `insert`.

@josevalim How would you feel if I made a PR to support a partial `replace` similar to feature from #1846 which added `replace_all` for `on_conflict`?

Instead of `replace_all` it would allow using the `EXCLUDED` value (and equivalent in mysql) on a subset of fields (rather than all the fields in `header`.

I'm thinking it would be similar to `:set`:

```ex
on_conflict: [replace: %{body: :body, title: :title}]
```

This would generate (for Postgres) `… ON CONFLICT UPDATE SET body = EXCLUDED.body, title = EXCLUDED.title …`

**Comment by tpitale** [comment]
I suppose I should start this on elixir-ecto forum … but it's a "problem" (for lack of a better term) that I'm facing right now.

**Comment by josevalim** [comment]
There is already replace_all_except_primary_keys. I am not sure if master only or if it was released.

**Comment by tpitale** [comment]
Github search is failing me looking for `replace_all_except_primary_keys`.

**Comment by tpitale** [comment]
Oh … this is already done in master: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L178

Seems to remove replace_all in favor of passing a list of fields to replace.

**Comment by josevalim** [comment]
But that's only at the adapter level. The repo API is here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L564

**Comment by tpitale** [comment]
@josevalim Does not appear that the commit that added it has been released: https://github.com/elixir-ecto/ecto/commit/d004624b9321a973fa10d91209882bbfa1b09e48
