### ISSUE TITLE
Side Navigation does show up on Firefox for documentations 

### ISSUE THREAD

**Issue by trojanh** [elixir-ecto/ecto#2331]
### Environment

* Browser: Firefox 57
* Operating system: Windows 10 Build 1703

### Current behavior

Side navigation for the topics does not show up on Firefox. 
For instance, if I open https://hexdocs.pm/ecto/Ecto.Changeset.html#delete_change/2 on Firefox it shows as follows

![firefox ecto docs bug](https://user-images.githubusercontent.com/22974490/33527132-6fd2383e-d871-11e7-94c5-2dbba3b20ade.PNG)

### Expected behavior

This navigation should be shown as it shows on Microsoft Edge and Google Chrome i.e 
![chrome docs](https://user-images.githubusercontent.com/22974490/33527170-f2531332-d871-11e7-9398-6618f35858df.PNG)

**Comment by josevalim** [comment]
Does it happen on any page here? https://hexdocs.pm/elixir/master/Kernel.html

**Comment by trojanh** [comment]
I do not see it for any of the hexdocs pages. Not even for Kernel i.e https://hexdocs.pm/elixir/master/Kernel.html

**Comment by josevalim** [comment]
@trojanh you do not see the bug or you do not see the panel? :)

**Comment by josevalim** [comment]
In any case, I have released Ecto 2.2.7 and pushed docs on the latest ExDoc version. If that does not fix it, then it is a ExDoc bug. :) Thanks for the report!

**Comment by trojanh** [comment]
Yeah, I think its ExDoc bug. Thanks for quick reply @josevalim . I'll report it on ExDoc.
