### ISSUE TITLE
Add Repo.exists/1 and Repo.query/2

### ISSUE THREAD

**Issue by MSch** [elixir-ecto/ecto#234]
I've been relying on them and was wondering what people are thinking about adding them to Ecto:

``` elixir
def query(sql, params, opts \\ []) do
  adapter.query(__MODULE__, sql, params, opts)
end

def exists(queryable) do
  query = Ecto.Query.from(x in queryable, select: 1, limit: 1) |> Ecto.Queryable.to_query
  case all(query) do
    [1] -> true
    [] -> false
  end
end
```

**Comment by axelson** [comment]
Note: this is now implemented in Ecto 3.0. So if you have added your own `exists?/1` to your repo you will need to remove it (but everything should continue to work). PR: https://github.com/elixir-ecto/ecto/pull/2577
