### ISSUE TITLE
select + select_merge + preload not working for some combinations

### ISSUE THREAD

**Issue by mbuhot** [elixir-ecto/ecto#2340]
### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.2
* Ecto version (mix deps): locked at 2.2.7 (ecto) 2074106f
* Database adapter and version (mix deps): locked at 0.13.3 (postgrex) c277cfb2
* Operating system: macOS 10.12.3

### Current behavior

I'm trying to dynamically build a query that will 1. optionally have a select list, and 2. optionally preload an association.  I'd like to use `select_merge` to ensure the foreign key is included in the select list when preloading the association.

In the examples below, schema `Comment` belongs_to `User`, with foreign_key `user_id`.

```elixir
  test "select comment body with preloaded user" do
    comments =
      from(c in Blog.Comment, select: struct(c, [:body]))
      |> select_merge([c], %{user_id: c.user_id})
      |> preload(:user)
      |> Blog.Repo.all()

    assert [%{body: "Great Article!", user: %{username: "jill"}}] = comments
  end
```

Fails with a `nil` value for the preloaded user.

```elixir
     match (=) failed
     code:  assert [%{body: "Great Article!", user: %{username: "jill"}}] = comments
     right: [%Blog.Comment{__meta__: #Ecto.Schema.Metadata<:loaded, "comments">,
              article: #Ecto.Association.NotLoaded<association :article is not loaded>,
              article_id: nil, body: "Great article!", id: nil,
              inserted_at: nil, updated_at: nil, user: nil, user_id: 1694}]
```

The following query does produce the expected results, by using a list of fields in `select_merge`.

```elixir
      from(c in Blog.Comment, select: [:body])
      |> select_merge([c], [:user_id])
      |> preload(:user)
      |> Blog.Repo.all()
```

However, using an atom list in `select_merge` breaks the case where I want to select all fields:

```elixir
  test "select all fields with preloaded user" do
    comments =
      from(c in Blog.Comment, select: c)
      |> select_merge([c], [:user_id])
      |> preload(:user)
      |> Blog.Repo.all()

    assert [%{body: "Great Article!", user: %{username: "jill"}}] = comments
  end
```

This time the preload works, but none of the other fields on `Comment` are populated

```
     match (=) failed
     code:  assert [%{body: "Great article!", user: %{username: "jill"}}] = comments
     right: [%Blog.Comment{__meta__: #Ecto.Schema.Metadata<:loaded, "comments">,
              article: #Ecto.Association.NotLoaded<association :article is not loaded>,
              article_id: nil, body: nil, id: nil, inserted_at: nil,
              updated_at: nil,
              user: %Blog.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">,
               articles: #Ecto.Association.NotLoaded<association :articles is not loaded>,
               bio: "Jill eats bananas",
               comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
               email: "jill@gmail.com", id: 1718,
               image: "http://imgur.com/jill/456.jpg",
               inserted_at: ~N[2017-12-12 00:42:34.028305], password: "bananas",
               updated_at: ~N[2017-12-12 00:42:34.028314], username: "jill"},
              user_id: 1718}]
```

### Expected behavior

1. When a query contains a `select` list, then it should be possible to use `select_merge` to add a foreign key to the select list, and then `preload` an association that requires the foreign key.

2. Supplying a list of fields to `select_merge` should behave the same as supplying a map:

```elixir
from query, select_merge: [:a, b, c]
``` 
should behave like:
```elixir
from x in query, select merge: %{a: x.a, b: x.b, c: x.c}
```

**Comment by josevalim** [comment]
@mbuhot could you please provide some tests on top of our integration test suite? You can run it as `MIX_ENV=pg mix test`. That would make it much easier for us to reproduce and fix those bugs. Thank you!

**Comment by mbuhot** [comment]
Thanks @josevalim, I've added 2 failing tests in https://github.com/mbuhot/ecto/commit/8e1c3da2bc7f8874c34dc5ef45090a68bcda70f2

First test fails to preload the association.
Second test fails to populate the fields of the parent struct.

**Comment by josevalim** [comment]
Thanks for the failing tests. I have pushed two commits and backported this to v2.2. Please give the v2.2 branch a try and, if everything works out, we can ship a new version.

**Comment by mbuhot** [comment]
Thanks @josevalim, looks like it's mostly fixed.

I've rebased my branch on ecto master, the original failing tests are working.
I've added two variations that use the `%struct{}` syntax in the `select`.
One case fails to populate the struct fields, and the other doesn't compile the query.

https://github.com/elixir-ecto/ecto/commit/7f5099fb2cd3e5a22f61e03ea5cca8ea105f245e

**Comment by josevalim** [comment]
Thanks. They should both be errors, I will fix them.
