### ISSUE TITLE
Unable to write a fragment for a @> operator on an int4range

### ISSUE THREAD

**Issue by axelson** [elixir-ecto/ecto#2343]
### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 10.1
* Ecto version (mix deps): 2.2.7
* Database adapter and version (mix deps): Postgrex 0.13.3
* Operating system: Arch Linux

### Current behavior

Given a table:

                                Table "public.games"
        Column    |            Type             | Collation | Nullable | Default
    --------------+-----------------------------+-----------+----------+---------
     id           | uuid                        |           | not null |
     num_players  | int4range                   |           |          |

And a query:

    query = (from g in Bug.BugExample)
    |> where([g], contains(g.num_players, ^num))

Where `contains` is:

    fragment("? @> ?", unquote(first), type(unquote(second), :integer))

Results in the SQL query:

    {"SELECT b0.\"id\", b0.\"num_players\" FROM \"bug_example\" AS b0 WHERE (b0.\"num_players\" @> $1::bigint)",
     [1]}

And the Postgres error:

    ** (Postgrex.Error) ERROR 42883 (undefined_function): operator does not exist: int4range @> bigint

### Expected behavior

The raw query should cast to `::integer`:

    {"SELECT b0.\"id\", b0.\"num_players\" FROM \"bug_example\" AS b0 WHERE (b0.\"num_players\" @> $1::integer)",
     [1]}

Reverting to Ecto 2.1.4 I no longer see the issue. Looking at the code it appears that this is the offending commit https://github.com/elixir-ecto/ecto/commit/ecd702dbe86707d57cd2af2ea621b112161fd959

I have a reproduction repo https://github.com/axelson/bigint_bug_repro

Test for yourself with:

    git clone https://github.com/axelson/bigint_bug_repro.git
    cd bigint_bug_repro 
    mix deps.get
    mix test

**Comment by josevalim** [comment]
Thanks @axelson. The changed was introduced because of issue #2213.

**Comment by axelson** [comment]
@josevalim yeah, I noticed that. There is probably a way to reoncile these two requirements so that both use-cases will work, but I don't currently know enough Ecto to know what the solution would be.

**Comment by ericmj** [comment]
You can do the type cast in the fragment string instead: `fragment("? @> ?::integer", unquote(first), unquote(second))`

**Comment by axelson** [comment]
@josevalim unfortunately I don't know enough about Postgres to make a recommendation for this use-case.

@ericmj Thanks! That's a good workaround and works for my current use-case.

**Comment by josevalim** [comment]
Let's go with won't fix for now and we will wait until we get more feedback. Thanks for the report!
