### ISSUE TITLE
Improve documentation for Repo modules

### ISSUE THREAD

**Issue by yordis** [elixir-ecto/ecto#2349]
Right now when I generate the documentation of my project I noticed that there is no typespec on my functions in the generated documentation.

I am not sure if this belongs to here, which probably means we have to add the typespec inside the macro?! or should belong to ex_doc where they should detect is a callback and add the typespec to the documentation, either way I am expecting to have the typespec on my repo module.

cc: @josevalim

**Comment by josevalim** [comment]
It is a docs issue, not an Ecto one.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by yordis** [comment]
@josevalim I will open an issue on ExDoc then. Thank you very much.
