### ISSUE TITLE
Issue with preload in child process when using Sandbox shared mode

### ISSUE THREAD

**Issue by bismark** [elixir-ecto/ecto#2356]
### Environment

* Elixir version: Elixir 1.5.2
* Database and version: MySQL 5.7.20
* Ecto version: ecto 2.2.7
* Database adapter and version: mariaex 0.8.3
* Operating system: MacOS 10.13

### Current behavior

See sample project here which exhibits the bug: https://github.com/bismark/ecto-test

When using the Sandbox in shared mode, if a child process's first interaction with the repo is a preload with multiple associations, it will raise an OwnershipError.

### Expected behavior

When using the Sandbox in shared mode, if a child process's first interaction with the repo is a preload with multiple associations, it should succeed.

**Comment by bismark** [comment]
I haven't tracked down the root cause but I believe it is related to adding the `:caller` option here:

https://github.com/elixir-ecto/ecto/blob/v2.2/lib/ecto/repo/preloader.ex#L105 

https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection/ownership/manager.ex#L111

**Comment by fishcakez** [comment]
The analysis looks spot on without trying the example repo. I think the bug is in DBConnection, and not Ecto itself, exactly where you pointed to.

**Comment by fishcakez** [comment]
Closing in favor of https://github.com/elixir-ecto/db_connection/issues/110
