### ISSUE TITLE
Ecto.Changeset.unique_constraint validation increases primary key sequence on fail insert

### ISSUE THREAD

**Issue by SofaKing18** [elixir-ecto/ecto#2358]
### Environment

* Elixir 1.5.2
* PostgreSQL 10.1
* ecto 2.2.7 (Hex package) (mix)
* postgrex 0.13.3 (Hex package) (mix)
* MacOS Sierra 10.12.6

### Current behavior

have "model" with unique_constraint field 'email', validation is possible only with insert or update. 
Example of model:
```
defmodule MyApp.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field(:email, :string)
    field(:crypted_password, :string)
    field(:password, :string, virtual: true)

    timestamps()
  end

  @required_fields ~w(email password)
  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @required_fields)
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 6)
  end
  
  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hash(changeset.params["password"]))
    |> repo.insert()
  end
end
```
I try to create User by code below:
```
  def create(changeset, repo) do
    changeset
    |> repo.insert()
  end
```
In situation when email is already used, insert in database fails, but sequence of primary key increases, so on next insert i have skipped ids in table

table users:
id  |   email
1 .     a@a.pepe
3 .    a@b.pepe

### Expected behavior
table users:
id  |   email
1 .     a@a.pepe
2 .    a@b.pepe

**Comment by wojtekmach** [comment]
> In situation when email is already used, insert in database fails, but sequence of primary key increases, so on next insert i have skipped ids in table

This is how Postgres works under the hood. If you increase a sequence in a transaction and the transaction is rolled back, the sequence stays increased. See e.g. https://stackoverflow.com/questions/19004453/postgresql-generate-sequence-with-no-gap

You can use [`Ecto.Changeset.unsafe_validate_unique/4`](https://hexdocs.pm/ecto/Ecto.Changeset.html#unsafe_validate_unique/4) which will _try_ to detect duplicated email before insertion is made
