### ISSUE TITLE
put_assoc  crash the server

### ISSUE THREAD

**Issue by mydearxym** [elixir-ecto/ecto#2366]
hi guys! 

i am facing a common situation which i want to add records to my `many_to_many` field , let's say i want to add `a lots of` comments to post: 

```elixir
schema "post" do 
  many_to_many(:comments, Comment, join_through: "cms_posts_comments")
  # ...
end
```

```elixir
def comment_post(post_id, body) do
    with {:ok, post} <- find_content(Post, post_id),
         {:ok, comment} <- create_comment(%{body: body}) do
      post_with_comments = post |> Repo.preload(:comments)

      post_with_comments
      |> Ecto.Changeset.change()
      |> Ecto.Changeset.put_assoc(:comments, post_with_comments.comments ++ [comment])
      |> Repo.update()

      # die
    else
      {:error, reason} ->
        {:error, reason}
    end
end
```

it works , but seems  the `put_assoc`  it`s not the right tool to do it.  i programed seed 10k comments to the same post , but the server crashed in about 3300 records

```elixir
def random(count \\ 10000) do
    for _u <- 1..count do
      CMS.comment_post(21, "fake comment")
    end
end
```
and after about 10 mins  server crashed ...

```elixir
[error] Postgrex.Protocol (#PID<0.261.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.73.0> timed out because it checked out the connection for longer than 15000ms
```

i am not sure it's a ecto bug or i am using it the wrong way .. 
how to add, update, and delete data from a many_to_many ?

**Comment by josevalim** [comment]
You are getting a timeout. Because put_assoc does everything in a transaction, the transaction is taking more than 15s and Ecto is finding it unexpected. You can fix it by passing the timeout option to Repo.update:

    Repo.update(timeout: 1000 * 60) # 1 minute

If you don't need transactional guarantees, you can also remove put_assoc and then introduce the comments after the post is created, without a transaction.

**Comment by mydearxym** [comment]
@josevalim  thanks 

i think the problem is i have to `preload` the old comments and `put_assoc` it with the new comment everytime.  i have tried inserting directly into the join table `cms_posts_comments` by using `Repo.insert_all`  , it works as expect with much better performence . 

maybe there is a missing macro for it, say `add_assoc` ?

**Comment by josevalim** [comment]
Going through the join table is the way to go! put_assoc is meant to compute the diffs between values and keep transactional guarantees.

**Comment by mydearxym** [comment]
got your point, thanks !
