### ISSUE TITLE
State metadata for subqueries

### ISSUE THREAD

**Issue by jueberschlag** [elixir-ecto/ecto#2367]
### Environment

* Elixir version (elixir -v): 1.5.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4.9
* Ecto version (mix deps): 2.2.7
* Database adapter and version (mix deps): Postgrex 0.13.3
* Operating system: Docker Elixir 1.5 image (based on Jessie)

### Current behavior

Subquery results have state of `:built` and not `:loaded`.

```elixir
alias MyApp.Repo
import Ecto.Query

my_post = Repo.insert!(%MyApp.Post{})

my_subquery = from(p in MyApp.Post, where: p.id == ^my_post.id)
my_query = from(s in subquery(my_subquery), select: s)

Repo.all(my_subquery)
Repo.all(my_query)
```

Results are
```elixir
[%MyApp.Post{__meta__: #Ecto.Schema.Metadata<:loaded, "posts">, ...}]
[%MyApp.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, ...}]
```

### Expected behavior

I would except results to be
```elixir
[%MyApp.Post{__meta__: #Ecto.Schema.Metadata<:loaded, "posts">, ...}]
[%MyApp.Post{__meta__: #Ecto.Schema.Metadata<:loaded, "posts">, ...}]
```

As the `state` metadata is not tested on the `subquery_test.exs` test I do not know if the behaviour is correct or if it is a bug.

**Comment by josevalim** [comment]
I am on this one!
