### ISSUE TITLE
Update specific fields from EXCLUDED table on conflict

### ISSUE THREAD

**Issue by IcyEagle** [elixir-ecto/ecto#2370]
Is it possible to do something like this on Postgres?

```
Repo.insert_all(Struct, entries, on_conflict: [set: [:foo, :bar])
```

I found solution via fragment (#1853) but this way I can't provide ```on_conflict``` value as an argument (I can't use ```fragment``` outside of ```from``` scope). Eventually I'd like to make the next code work:

```
def save(struct, entries, opts \\ []) do
  Repo.insert_all(struct, entries, opts)
end

save(MyStruct, [%MyStruct{foo: "foo", bar: "bar", bazz: "bazz"}], on_conflict: [set: [:foo, :bar])
```

I've checked *Ecto.Repo.Schema.on_conflict/6* and concluded it's just not supported at all. Are there any hacks here? :)

Many thanks!

**Comment by josevalim** [comment]
@IcyEagle can't you repeat the values given on set?

  save(MyStruct, [%MyStruct{foo: "foo", bar: "bar", bazz: "bazz"}], on_conflict: [set: [foo: "foo", bar: "bar"])

?

**Comment by IcyEagle** [comment]
@josevalim in case of insert_all I can't since there are many entries and each of them may contain different values in the same fields.

**Comment by josevalim** [comment]
I see, yes. Would you like to send a PR? Ecto master already allows custom fields to be given, we just don't expose it. So the API would be this:

    on_conflict: {:replace, [:foo, :bar]}

To make this work, you just need to match it [here](https://github.com/elixir-ecto/ecto/blob/f9eea6174f225d24737f6e4f01ddd724f7449a0f/lib/ecto/repo/schema.ex#L505), probably something like:

    {:replace, keys} when is_list(keys) ->
     {header, [], conflict_target}

And then update the docs and add a test. For the tests, [you can get those two tests and rewriting them using `{:replace, some_keys}`](https://github.com/elixir-ecto/ecto/blob/master/integration_test/cases/repo.exs#L1570-L1628).

**Comment by IcyEagle** [comment]
@josevalim thank you for help! :)

I'll try to provide PR soon.
