### ISSUE TITLE
Column type not supported | ODBC_CODE | SQL_SERVER_CODE 0 using type uniqueidentifier 

### ISSUE THREAD

**Issue by ruben44bac** [elixir-ecto/ecto#2377]
### Precheck

Hi
I have a problem to use type uniqueidentifier.
In my database i hava a table with column `pruebauuid uniqueidentifier` and in my schema used type :binary_id or :uuid or Ecto.UUID but always have same problem 

Column type not supported | ODBC_CODE | SQL_SERVER_CODE 0
lib/ecto/adapters/sql.ex
431    case sql_call(repo, :prepare_execute, [name, prepared], params, mapper, opts) do
432      {:ok, query, %{num_rows: num, rows: rows}} ->
433        update.({id, query})
434        {num, rows}
435      {:error, err} ->
436        raise err
437    end
438  end
439
440  defp execute_or_reset(repo, id, reset, cached, params, mapper, opts) do
441    case sql_call(repo, :execute, [cached], params, mapper, opts) do

### Environment

* Elixir version (elixir -v): 1.5.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): SQL SERVER 2014
* Ecto version (mix deps): 2.1.6
* Database adapter and version (mix deps): 
file_system 0.2.2 
connection 1.0.4
gettext 0.14.0
ranch 1.3.2
poolboy 1.5.1
decimal 1.4.1
poison 3.1.0
earmark 1.2.4 
ex_doc 0.18.1 
db_connection 1.1.2
ecto 2.1.6
phoenix_pubsub 1.0.2
cowlib 1.0.2
cowboy 1.1.2 
uuid 1.1.8
mime 1.2.0 
plug 1.4.3 
phoenix_html 2.10.5 
phoenix 1.3.0 
phoenix_live_reload 1.1.3 
mssqlex 0.8.0
mssql_ecto 0.3.1
phoenix_ecto 3.3.0 
* Operating system: Windows 10 Pro, 64-bit

## mix.ex

```
def application do
    [
      mod: {PruebaBien.Application, []},
      extra_applications: [:logger, :runtime_tools, :mssqlex, :mssql_ecto]
    ]
  end
```

```
defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:mssql_ecto, "~> 0.3.1"},
      {:mssqlex, "~> 0.8.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:ex_doc, "~> 0.12"},
      { :uuid, "~> 1.1" }
    ]
  end
```

## usuario.ex

```
defmodule Usuario do
    use Ecto.Schema
      import Ecto
      import Ecto.Changeset
      import Ecto.Query
    schema "usuario" do
        field :nombre, :string
        field :valor, :integer
        field :pruebauuid, Ecto.UUID
    end
    def changeset(struct, params) do
        struct
            |> cast(params, [:nombre, :valor])
            |> validate_required(:nombre)
    end
end
```

## table sql

```
create table usuario(
 id int auto_increment,
nombre varchar(50),
valor int,
pruebauuid uniqueidentifier,
primary key(id)
)
```

**Comment by josevalim** [comment]
Can you please file this on your the SQL adapter? Ecto is not responsible for this particular bit. Thanks!

**Comment by noizu** [comment]
This doesn't seem like quite the intractable issue others have been making it out to be. I added crude GUID read support with a rough patch of the erlang odbc driver in about an hour and a half. Obviously it will be quite a bit longer before I have full support e2e but if you run into this issue follow my fork and hopefully we can get things in an acceptable state to push upstream in an future release.

 https://github.com/noizu/otp/commit/33d1ba6c109b1e9056696ed375984abe6b50f386

![image](https://user-images.githubusercontent.com/6298118/77674602-6e1bb380-6fbe-11ea-960f-806a73c26ad6.png)

![image](https://user-images.githubusercontent.com/6298118/77674666-82f84700-6fbe-11ea-888b-d9232b219737.png)
