### ISSUE TITLE
Error on `insert` callback when `on_conflict: :nothing` is used

### ISSUE THREAD

**Issue by alhambra1** [elixir-ecto/ecto#2378]
Hi,

Thank you for your wonderful contribution!

We've run into a little trouble with our Ecto adapter for DynamoDB after updating Ecto from 2.1 to 2.2.8. (See our project here: https://github.com/circles-learning-labs/ecto_adapters_dynamodb)

When calling `Repo.insert(changeset, on_conflict: :nothing)` we get the following error when our adapter provides the return value for the `insert` callback as `{:ok, [id: nil]}`. Please see the trace directly below:
```
** (FunctionClauseError) no function clause matching in Ecto.Repo.Schema.load_each/4    
    
    The following arguments were given to Ecto.Repo.Schema.load_each/4:
    
        # 1
        %Dynamotest.Person{__meta__: #Ecto.Schema.Metadata<:loaded, "person">,
     circles: nil, email: "poiu", first_name: "asdf", id: "zxcv",
     inserted_at: ~N[2018-01-16 20:54:55.681880], int: nil, last_name: "qwer",
     list: nil, password: nil, set: nil, updated_at: ~N[2018-01-16 20:54:55.681892]}
    
        # 2
        [id: nil]
    
        # 3
        []
    
        # 4
        Ecto.Adapters.DynamoDB
    
    (ecto) deps/ecto/lib/ecto/repo/schema.ex:645: Ecto.Repo.Schema.load_each/4
    (ecto) deps/ecto/lib/ecto/repo/schema.ex:633: Ecto.Repo.Schema.load_changes/8
    (ecto) deps/ecto/lib/ecto/repo/schema.ex:217: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
```
I am wondering if this may be related to the following code block in Ecto, file "ecto/lib/ecto/repo/schema.ex", line 176:

```
   {return_types, return_sources} =    
      schema
      |> returning(opts)                
      |> add_read_after_writes(schema)  
      |> fields_to_sources(dumper)
```

If the option `:returning` is not set, this block yields empty lists for `return_types, return_sources`, which then get passed through producing the error above. Is there anything we should be doing differently, or is this possibly an Ecto bug?

Please see our return process for the Ecto adapter `insert` callback on lines 519-533 here:
https://github.com/circles-learning-labs/ecto_adapters_dynamodb/blob/master/lib/ecto_adapters_dynamodb.ex#L522

Thank you for your time and consideration!
Gilad 

### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): DynamoDB (local)
* Ecto version (mix deps): 2.8
* Database adapter and version (mix deps): ecto_adapters_dynamodb, tag 0.3.0
* Operating system: MacOS High Sierra 10.13.2

**Comment by josevalim** [comment]
You are correct, without `:returning`, we don't expect the adapter to return anything. We could figure out a way to make it work but I would like to understand why you are returning nil and if that's indeed the preferred approach in your case.

**Comment by alhambra1** [comment]
Hi Jose,

Thank you for your response. Having the adapter return `{:ok, [id: nil]}` in Ecto 2.1 resulted in the behaviour described in Ecto's documentation where the final returned struct's `id` field is `nil` (lines 765-770 in file, "https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex"):

```
      {:ok, inserted} = MyRepo.insert(%Post{title: "this is unique"})
  Now we can insert with the same title but do nothing on conflicts:
      {:ok, ignored} = MyRepo.insert(%Post{title: "this is unique"}, on_conflict: :nothing)
      assert ignored.id == nil
```

Could you please clarify what you mean by expecting the adapter not to "return anything?" I'm not sure how to do that in Elixir :) If you mean to have the adapter return `{:ok, []}` when calling `Repo.insert(changeset, on_conflict: :nothing)` - in Ecto 2.2.8 we get the original `id` of the insert, which does not seem to correspond with Ecto's documentation mentioned above: 

```
{:ok, %Dynamotest.Person{__meta__: #Ecto.Schema.Metadata<:loaded, "person">,
 ... id: "zxcv"...}
```

Sincerely,
Gilad

**Comment by josevalim** [comment]
Do you have the IDs generated in the adapter/client? If so, that would explain it.

The `on_conflict: :nothing` documentation is not saying the ID is being set to nil but rather that we are not getting an ID from the database. But if the ID is generated in the client, then we will have whatever was generated.

So one option to proceed here is indeed return `[]` and we update the docs to clarify what we mean by nil ID.

Thoughts?

**Comment by alhambra1** [comment]
We are inserting the id in the changeset. The adapter does nothing. In this case there is no way to know if there was a conflict or not.

**Comment by alhambra1** [comment]
Ah, I think I see what you mean -- Ecto docs: ""`id` will be nil if the field is autogenerated by the database and no insert happened." But in our case, or the case when there is no autogeneration, and we insert an `id` in the changeset, then the expected behaviour is to get it back (even though we can't readily know from the result if there was a conflict).

That behaviour seems fine to me now that I understand it better. We'll let you know if we have further thoughts.

Thanks!
Gilad

**Comment by josevalim** [comment]
Perfect! I will keep this open until I fix the docs. :)

**Comment by josevalim** [comment]
This has been fixed in master. :)
