### ISSUE TITLE
Can't group_by substring of column

### ISSUE THREAD

**Issue by alli5723** [elixir-ecto/ecto#2379]
### Environment

* Elixir version (elixir -v):
* Database and version (PostgreSQL 9.4):
* Ecto version (mix deps):
* Database adapter and version (mix deps):
* Operating system: MacOS High Seria

### Current behavior
It seems impossible to query the database for example 
* query = from m in Message,
     where: [account_id: ^id],
     group_by: m.network, 
     group_by: substring(m.recipient, 1, 6),
     group_by: m.status_description

### Expected behavior
The essence of this particular example is to get the count for unique number blocks in the database, I think this should be made available in ecto also since it is possible to run normal sql queries with such.
* select substring(recipient, 1, 6) m, status, count(*) from outbox where schedule_id in (SELECT schedule_id FROM scheduler where company = 'xx') group by m order by m

**Comment by josevalim** [comment]
You should pass it as a single list:

```
query = from m in Message,
where: [account_id: ^id],
group_by: [m.network, substring(m.recipient, 1, 6), m.status_description]
```

**Comment by alli5723** [comment]
I still get an error with the single list, seems ecto doesn't know how to deal with the function "substring".

![screen shot 2018-01-17 at 5 54 51 pm](https://user-images.githubusercontent.com/3235411/35052178-9dfb5a7c-fbaf-11e7-9125-0bdfc2bd4d22.png)

**Comment by josevalim** [comment]
Yes, in those cases you can use fragment:

    fragment("substring(?, ?, ?)", m.recipient, 1, 6)

**Comment by josevalim** [comment]
To learn more about fragments and the supported functions, please see: hexdocs.pm/ecto/2.2.6/Ecto.Query.API.html#fragment/1

**Comment by alli5723** [comment]
Thank you,
The fragment works as intended.
