### ISSUE TITLE
Upsert has unexpected effects on `timestamps`

### ISSUE THREAD

**Issue by grantovich** [elixir-ecto/ecto#2382]
### Environment

* Elixir version: **1.5.2**
* Database and version: **PostgreSQL 9.6**
* Ecto version: **2.2.6**
* Database adapter and version: **postgrex 0.13.3**
* Operating system: **Alpine Linux 3.6**

### Current behavior

When using `Ecto.Repo.insert` with the `on_conflict` option to perform an "upsert", there are some surprising effects on timestamp columns defined with `Ecto.Schema.timestamps`:

1. With `on_conflict: :replace_all`, conflicting rows have _both_ their `updated_at` and `inserted_at` timestamps updated, despite only having been updated.

2. With `on_conflict` set to a specific update instruction in the style of `update_all`, conflicting rows have _neither_ of their timestamps updated — despite the function apparently being capable of this, as shown by case 1.

The `Ecto.Repo.insert` documentation does contain this remark, hiding in a section about how to tell whether an upserted record was inserted or updated:

> In case an update happened, the data in the struct most likely does not match the data in the database. For example, autogenerated fields such as `inserted_at` will point to now rather than the time the struct was actually inserted.

The wording is ambiguous but seems to suggest it's only the in-memory struct itself, and _not_ the record in the database, that would have the wrong timestamp.

### Expected behavior

Ideally, I think upserts should respect the intent of `timestamps`, only (and always) touching the `updated_at` timestamp when a conflicting row is updated.

Less ideally, I think the documentation should call out, clearly and prominently, exactly how upserts will affect timestamps. The overwriting of the insert timestamp in the likely-common `replace_all` case is especially surprising, and recently caused some data corruption in a production app I work on (thankfully we had backups).

**Comment by josevalim** [comment]
Thanks for the report.

We will improve the documentation since I would expect an operation called `:replace_all` to indeed replace all fields. Otherwise we are just preparing ourselves to an inevitable report of how `:replace_all` does not really replace all fields. :)

**Comment by grantovich** [comment]
Thank you for the quick response, @josevalim, and for maintaining Ecto 😃

> We will improve the documentation since I would expect an operation called `:replace_all` to indeed replace all fields.

Here's the unintuitive aspect to me: I would certainly expect `replace_all` to replace all fields _that I specified_ in the struct/changeset, but I'm not specifying a value for `inserted_at` (supplying either a struct where the field is `nil`, or a changeset that does not include it). The documentation seems to have the same expectation:

> `:replace_all` - replace all values on the existing row with the values in the excluded row (the record given in the function parameters)

`inserted_at` is not present in "the record given in the function parameters", but it is still replaced with a new value. I assume this value originates within the `timestamps` macro (not sure how it works exactly), so maybe that code is not accounting for upserts?

**Comment by josevalim** [comment]
You are correct the documentation there is wrong. It is supposed to mean it is replaced by all values *sent* to the database and that includes client generated timestamps.

**Comment by grantovich** [comment]
Thanks, that makes sense. To clarify your view on this, do you think this is 100% a "working as designed" scenario (and just needs doc improvements), or is there a case to be made that e.g. the logic added by the `timestamps` macro should better handle upserts? Or would that be inadvisable, or even impossible due to the way upserts work?

**Comment by josevalim** [comment]
Working as designed in the sense replace_all should replace all entries. We
could fix it but I don’t think we should.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by grantovich** [comment]
Oh, I'd agree on the `replace_all` point. I was wondering if there's a way to change how `timestamps` works, so it doesn't send any value for `inserted_at` when an update occurs (`replace_all` would still replace all values _sent to the database_, as you say).

For comparison, although ActiveRecord doesn't have a native upsert function, there is a third-party gem [`active_record_upsert`](https://github.com/jesjos/active_record_upsert) that implements it and automatically respects timestamps, so it seems this behavior is desirable.

**Comment by josevalim** [comment]
@grantovich the values that you send on update are completely controlled by the `:on_conflict` option. If you don't want `:inserted_at` to be part of it, then you should not include it.

**Comment by grantovich** [comment]
I understand that, from a technical standpoint, everything is within my control here and Ecto provides the tools to accomplish the desired behavior. It makes sense why each individual piece works the way it does. My perspective is that the "user experience" produced when these pieces interact is nevertheless likely to cause confusion and data loss for users not intimately familiar with the implementation.

An example:

```elixir
defmodule MyApp.User do
  use MyApp.Web, :model

  schema "users" do
    field :email, :string
    field :name, :string
    timestamps
  end
end
```

```elixir
%MyApp.User{email: "tester@example.com", name: "Tester"}
|> MyApp.Repo.insert!(on_conflict: :replace_all, conflict_target: :email)
```

Considering I didn't write `inserted_at` anywhere in this code, I'm probably not expecting it to change. In fact I don't expect `inserted_at` to ever change on any record update, since that would defeat the purpose of an insert timestamp. Although `inserted_at` changing is a _technically correct_ consequence of how upserts and timestamps are implemented, it's unintuitive and probably not what I want.

My initial comment here was more "bug report" than "feature request", but with a better understanding of the implementation I see this falls into the latter category. Please consider it as such 🙂

**Comment by josevalim** [comment]
`{:replace_all_except, fields}` have been added to make handling this easier.
