### ISSUE TITLE
Allow passing table hints to the db via Ecto

### ISSUE THREAD

**Issue by JamesFerguson** [elixir-ecto/ecto#2392]
### Environment

* Elixir version (elixir -v): 1.5.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6.38
* Ecto version (mix deps): 2.1.6
* Database adapter and version (mix deps): mariaex 0.8.1
* Operating system: OSX 10.11.6

### Current behavior

Previously discussed on SO here: https://stackoverflow.com/questions/48394148/how-to-give-an-index-hint-to-mysql-through-ecto

Please bear in mind I'm an Elixir/Ecto noob.

I need to pass an index hint to MySQL in an Ecto query and it seems this is not currently supported.

The syntax for MySQL is defined [here](https://dev.mysql.com/doc/refman/5.7/en/index-hints.html). It seems from a brief googling that it's not standard SQL (Postgres doesn't support it at all) and each DB adapter would need to handle it differently.

For example, if the following query needs manual optimization:

```
SELECT *
FROM posts AS p
  JOIN comments AS c ON c.post_id = p.id
```

I might want the following query produced:

```
SELECT *
FROM posts AS p
  JOIN comments AS c USE INDEX(comments_index) ON c.post_id = p.id
```

I have tried a number of hacks, like:

```
from p in Post
  join: c in fragment("comments AS c USE INDEX(comments_index) ON c.post_id = p.id")

# produces the SQL

SELECT *
FROM posts AS p
  JOIN (comments AS c USE INDEX(comments_index) ON c.post_id = p.id) AS f1

# which is obviously invalid SQL syntax
```

and also

```
from p in Post
  join: c in "comments AS c USE INDEX(comments_index) ON c.post_id = p.id"

# produces the SQL

SELECT *
FROM posts AS p
  JOIN `comments AS c USE INDEX(comments_index) ON c.post_id = p.id`

# which is results in a 'table name too long' error
```

### Expected behavior

Ideally there'd be a feature added so I could do:

```
from p in Post
  join: c in Comment
  use: "comments_index"

# produces the SQL

SELECT *
FROM posts AS p
  JOIN comments AS c USE INDEX(comments_index) ON c.post_id = p.id
```

if nothing else it would be nice if I could do something like:

```
from p in Post
  join: c in fragment("comments AS c USE INDEX(comments_index) ON c.post_id = p.id", raw: true)

# produces the SQL

SELECT *
FROM posts AS p
  JOIN comments AS c USE INDEX(comments_index) ON c.post_id = p.id
```

**Comment by josevalim** [comment]
We have changed how `Ecto.Query.join/5` accepts options, which means that we can add a `:use_index` key to `JoinExpr` and it should be an atom or a list of atoms. It will only work for MySQL, other databases should raise.

**Comment by josevalim** [comment]
I have changed the title of the issue to be about **table hints**. Both SQLServer and MySQL supports this and they support a variety of commands. For example, [in MySQL](https://dev.mysql.com/doc/refman/5.7/en/index-hints.html):

    SELECT * FROM t1 USE INDEX FOR JOIN (i1) FORCE INDEX FOR JOIN (i2);

Or [in SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-2017):

    FROM t WITH (TABLOCK, INDEX(myindex))  

My suggestion is to introduce a new option called `:hints` that is either a literal string or a literal list of strings. Translating both examples above:

    from t, hints: "USE INDEX FOR JOIN (i1) FORCE INDEX FOR JOIN (i2)"
    from t, hints: ["TABLOCK", "INDEX(myindex)"]

`:hints` will be supported in `from` and `join`. Thoughts?

**Comment by michalmuskala** [comment]
That looks good to me 👍

**Comment by zachdaniel** [comment]
Same here.

**Comment by ukutaht** [comment]
Hey 👋

I maintain our own fork of `clickhouse_ecto` for connecting to ClickHouse. Trying to make their `SAMPLE` hint work with ecto, here are the [docs](https://clickhouse.tech/docs/en/sql-reference/statements/select/sample/) for it but it's pretty straightforward. I need to compile a query like this:

```sql
SELECT .. FROM events SAMPLE 10000 ...
```

The `hints` feature works OK for this, I can access the hints in the ecto adapter and compile it as necessary. However, I ran into a limitation with trying to make the sampling threshold configurable for the app:

```elixir
from(e in "events", hints: ["SAMPLE #{sample_threshold()}"])

** (Ecto.Query.CompileError) `hints` must be a compile time string or list of strings, got: `["SAMPLE #{sampling_factor()}"]`
```

We want different sampling levels based on available server resources and different data characteristics. It should be configurable for each instance. I'm curious as to why the `hints` field is limited to compile-time strings? Defense against SQL injection? Ideas on how this SAMPLE use-case could be supported?

Thanks

**Comment by josevalim** [comment]
Hi @ukutaht! Yes, the issue is to avoid SQL injection. If you can interpolate anything in there, someone may pass external data, which can break things.

Maybe in this case what we can do is to allow hints to be a tuple and then it becomes responsibility of the adapter to encode that tuple properly. The built-in SQL adapters should raise if they see something that is not a binary. At compile-time, we will enforce them to be binaries or tuples. Tuples are not checked on their contents.

WDYT?

**Comment by ukutaht** [comment]
Thanks for the quick reply! By a tuple do you mean something like this?

```sql
from(e in "events", hints: [{"SAMPLE", sample_threshold()])
```

It would work great for me. It's a simple enough change that I can probably PR it as well some time next week.

**Comment by josevalim** [comment]
Yes! In this case I would even do: `from(e in "events", hints: [sample: sample_threshold()])`. :)
