### ISSUE TITLE
Warnings with Elixir 1.5.2 and version 2.2.8

### ISSUE THREAD

**Issue by quatermain** [elixir-ecto/ecto#2393]
Hello,

I got couple of warnings:
```
warning: variable "ansi_color" is unused
  lib/ecto/log_entry.ex:41

warning: variable "connection_pid" is unused
  lib/ecto/log_entry.ex:41
```

### Environment

* Elixir 1.5.2 Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Ecto 2.2.8
* postgrex 0.13.3
* OS X

**Comment by josevalim** [comment]
This is happening because you set compile_time_purge_level. The logger call is removed and then the variables are unused. We should probably fix this in Elixir.

**Comment by josevalim** [comment]
Fixed here: https://github.com/elixir-lang/elixir/commit/edb52b7ca5ff88e2a376119247092b4370aca918
