### ISSUE TITLE
DOCUMENTATION IMPROVEMENT: custom database table- and column-names

### ISSUE THREAD

**Issue by fireproofsocks** [elixir-ecto/ecto#2398]
This is my first pull request, so please let me know if it's not the proper flow.  I wanted to include a couple more clarifications/examples in the Ecto docs for using it with existing databases. 

Specifically: it would be helpful to demonstrate how to reference an existing primary key that is not named "id", and demonstrate how to alias column names.

How to set this up is not easily distilled from the current documentation, so adding a couple examples could save others some time.

**Comment by josevalim** [comment]
A PR will be appreciated, definitely. :)

**Comment by fireproofsocks** [comment]
PR is here: https://github.com/elixir-ecto/ecto/pull/2399

Please let me know if the suggestions are acceptable or let me know if they would be more appropriate somewhere else.  Also, I wasn't sure of the branching strategy.  Thanks!
