### ISSUE TITLE
"Internal consistency check failed" during compilation using Erlang/OTP 18.3.4.7

### ISSUE THREAD

**Issue by hfiguera** [elixir-ecto/ecto#2403]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 18 [erts-7.3.1.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

(PostgreSQL) 9.5.10

* Ecto version (mix deps):

ecto 2.2.8

* Database adapter and version (mix deps):

postgrex 0.13.2

* Operating system:

macOS High Sierra 10.13.3

### Current behavior

Compiling 70 files (.ex)

== Compilation error on file lib/ecto/query/builder/select.ex ==
** (CompileError) Elixir.Ecto.Query.Builder.Select: function '-merge_take/3-fun-0-'/3+24:
  Internal consistency check failed - please report this bug.
  Instruction: {test,is_tuple,{f,133},[{x,2}]}
  Error:       {uninitialized_reg,{x,2}}:

    (stdlib) lists.erl:1337: :lists.foreach/2
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

### Expected behavior

Compiling 70 files (.ex)
...
Generated ecto app

Note: in version ecto 2.2.7 there was no problem

**Comment by michalmuskala** [comment]
"Internal consistency check failed" errors are bugs in the Erlang compiler. I'll try looking into working around it. The immediate solution would be to update Erlang/OTP.
