### ISSUE TITLE
Add common DSLs to .formatter.exs

### ISSUE THREAD

**Issue by darkbaby123** [elixir-ecto/ecto#2404]
Hello guys, we recently upgraded our app (with Phoenix & Ecto) to Elixir 1.6. And we currently add many DSL functions to `.formatter.exs`. Below are some for Ecto:

```elixir
[
  locals_without_parens: [
    # Ecto

    ## schema
    field: :*,
    belongs_to: :*,
    has_one: :*,
    has_many: :*,
    many_to_many: :*,
    embeds_one: :*,
    embeds_many: :*,

    ## migration
    create: :*,
    create_if_not_exists: :*,
    alter: :*,
    drop: :*,
    drop_if_exists: :*,
    rename: :*,
    add: :*,
    remove: :*,
    modify: :*,
    execute: :*
  ]
]
```

 I think they're very common for most of the users. If they're in the Ecto's `.formatter.exs` then developers can simply `import_deps: [:ecto]`. If you agree I'd like to make a PR for it.

**Comment by josevalim** [comment]
That's the plan! Although we think we could handle migrations in a slightly different way. We are not quite sure yet.

**Comment by josevalim** [comment]
We can start with the schema one though. Could you please send a PR? Thank you!

**Comment by darkbaby123** [comment]
The schema DSLs are added. But I found that adding things to both `locals_with_parens` and `export` is duplicated. I can extract a variable in `.formatter.exs` like below:

```elixir
locals_without_parens = [
  dsl_1: :arity,
  dsl_2: :arity
]

[
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
```

It works for `mix format`, but I'm not sure if it's a preferred way?

**Comment by darkbaby123** [comment]
After checking the source of `mix format`, I found that the `.formatter.exs` is evaluated with `Code.eval_file/2`. Since we only use evaluation result but not bindings, it's safe to use variables in `.formatter.exs`. The PR is also updated.

**Comment by josevalim** [comment]
Yup, it is totally safe. Closing this in favor of the PR. :)

**Comment by hauleth** [comment]
It seem that `.formatter.exs` has `export` section, but it seem that this file isn't present in release which mean that `import_deps: [:ecto]` does nothing.

**Comment by josevalim** [comment]
Pushed to v2.2. It iwll be fixed in the next release.

**Comment by rbino** [comment]
I came across this issues after asking myself if I had to put parentheses or not in migrations, it seems that at the end the migrations DSL was not added in formatter.exs (@josevalim talks about "handle migrations in a slightly different way" in the first comment above) but the docs show migrations without parentheses.

Should the migration DSL be added in formatter.exs? I can send a PR if it's needed.

**Comment by josevalim** [comment]
@rbino it is in the formatter of `:ecto_sql`. :)

**Comment by rbino** [comment]
Didn't see that one, I'll import also ecto_sql then. Thanks! :smile:

**Comment by josevalim** [comment]
@rbino understandable, it was added like yesterday :D
