### ISSUE TITLE
Mixing fragments and dynamics

### ISSUE THREAD

**Issue by ericmj** [elixir-ecto/ecto#2408]
This query is currently not possible: `fragment("function(?)", ^dynamic([x], true))`.

Being able to compose dynamics and fragments is especially useful when calling functions that are not exposed in `Ecto.Query.API`, which is not possible today.

**Comment by michalmuskala** [comment]
I think we support dynamics only at the top-level of a `where` or a `having` part of the query. Would this feature mean allowing using dynamics anywhere in the query?

**Comment by ericmj** [comment]
> I think we support dynamics only at the top-level of a where or a having part of the query. Would this feature mean allowing using dynamics anywhere in the query?

I'm not sure how feasible that is, but it wouldn't be a bad thing to support. You can work around it today by first interpolating inside another dynamic which you then interpolate at the top-level. But there is no workaround for fragment interpolation currently afaik.

**Comment by josevalim** [comment]
The problem with supporting dynamic everywhere is that `order`, `group_by` and `select` use different composition rules.

But I forgot about the top-level restriction. It exists because otherwise it makes composing expensive, we may not be able to lift this restriction. :( I will have to investigate.

**Comment by josevalim** [comment]
I did some work on this and unfortunately it is not possible. Since dynamic has its own bindings, if we allow it anywhere in a query expression, it means we always need to do a deep merge for handling the binding and that can get really complex.
