### ISSUE TITLE
Make Ecto.Migration.remove/1 reversible

### ISSUE THREAD

**Issue by manukall** [elixir-ecto/ecto#2418]
As proposed [on the mailing list](https://groups.google.com/forum/#!topic/elixir-ecto/a5mL9nvnITw), it would be great if Ecto.Migration.remove/1 could be reversible.

We could add optional arguments `type` and `opts`, giving it the same signature as Ecto.Migration.remove/3 and inflect the down-command when those are present.

**Comment by m13m** [comment]
@josevalim I want to take this any heads up will be great

**Comment by josevalim** [comment]
Just go ahead. :) Let us know if you have questions!

**Comment by m13m** [comment]
I started working on this but don't understand how "Ecto would know how to reverse the migration"?

**Comment by bobishh** [comment]
Hey, tried to fix an issue [here](https://github.com/elixir-ecto/ecto/pull/2420), @m13m sorry for stealing this )
Point me what needs to be fixed, I don't know if I did everything right :-)

**Comment by manukall** [comment]
thanks to all of you!
