### ISSUE TITLE
 Ecto.Adapters.SQL.query with MySQL

### ISSUE THREAD

**Issue by cesardgt** [elixir-ecto/ecto#2419]
### Environment

* Elixir version (elixir -v): Elixir 1.6.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6.35
* Ecto version (mix deps): 2.2.8
* Database adapter and version (mix deps): mariaex 0.8.4
* Operating system: Ubuntu 16.04

### Current behavior
Code:
```
query = " select id from $1 where id = $2 "
Ecto.Adapters.SQL.query!(Repo, query, [table, id])
```
Result
```
[debug] QUERY ERROR db=0.5ms
 select id from $1 where sysid = $2  ["activities", "469601326"]
[info] Application dgtidx exited: Docomo.Application.start(:normal, []) returned an error: shutdown: failed to start child: Docomo.Consumer
    ** (EXIT) an exception was raised:
        ** (Mariaex.Error) (1146): Table 'test.$1' doesn't exist
```

**Comment by josevalim** [comment]
You can't pass a parameter on the table name. This is a MySQL restriction, not an Ecto one. :)
