### ISSUE TITLE
Repo.insert should represent actually inserted data.

### ISSUE THREAD

**Issue by ppraisethesun** [elixir-ecto/ecto#2427]
### Environment

* Elixir version (elixir -v): 1.7.0-dev (0d0af06)
* Database and version: PostgreSQL 9.5.11
* Ecto version (mix deps): "~> 2.1"
* Database adapter and version (mix deps): {:postgrex, ">= 0.0.0"}
* Operating system: Ubuntu 16.04

Schema definition:
```
defmodule MySchema do
  use Ecto.Schema
  import Ecto.Changeset

  schema "example" do
    field(:field, :map)
  end

  def changeset(data, attrs) do
    data
    |> cast(attrs, [:field])
  end
end
```

### Current behavior
```
iex(1)> attrs = %{
       field: %{
         :one => :one,
         "two" => :two,
         3 => "three",
         :four => [1, "2", :three]
       }
     }
```

> ```
> %{
>   field: %{3 => "three", :four => [1, "2", :three], :one => :one, "two" => :two}
> }
> ```

```
iex(2)> %MySchema{} |> MySchema.changeset(attrs) |> Repo.insert!()
```

> ```
>  %MySchema{
>    __meta__: #Ecto.Schema.Metadata<:loaded, "example">,
>    field: %{
>      3 => "three",
>      :four => [1, "2", :three],
>      :one => :one,
>      "two" => :two
>    },
>    id: 1
>  }
> ```

```
iex(3)> Repo.get(MySchema, 1)
```

> ```
> %MySchema{
>   __meta__: #Ecto.Schema.Metadata<:loaded, "example">,
>   field: %{
>     "3" => "three",
>     "four" => [1, "2", "three"],
>     "one" => "one",
>     "two" => "two"
>   },
>   id: 1
> }
> ```

### Expected behavior
Repo.insert should represent actually inserted data.
Results of Repo.insert! and Repo.get should be the same.

**Comment by josevalim** [comment]
This will happen on every field that has loss of information when serializing or when persisting to the database. For example, if you have a timestamp with a higher precision than the one in the database, then they will be different.

You can set the field to `read_after_writes: true` if you want to read the data from the database back after you perform write and make sure they are consistent.
