### ISSUE TITLE
Provide public query planning API

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2448]
Today adapters need to rely on the Planner API, which is private. We need to provide at least two public functions: `plan_query_with_cache` and `plan_query_without_cache`. The question is just which module would be the best to add those functions. Maybe directly in Ecto.Adapter?

/cc @michalmuskala

**Comment by michalmuskala** [comment]
I'm not exactly sure, I understand what those functions would do. @josevalim, could you expand a bit?

**Comment by josevalim** [comment]
We need it for #2558. Today all adapters end-up accessing a private query
API to test queries and we should fix that, especially if we are moving
Ecto.SQL out.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Should the query cache be part of ecto itself or rather ecto_sql? For example, the cache is completely useless for mongodb, but I think some other NoSQL database like cassandra or orientdb could use it, since they also have a textual query format.
