### ISSUE TITLE
Some binaries fail required validation

### ISSUE THREAD

**Issue by haljin** [elixir-ecto/ecto#2455]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `postgres (PostgreSQL) 10.2`
* Ecto version (mix deps): `ecto 2.2.8 (Hex package) (mix)`
* Database adapter and version (mix deps): `postgrex 0.13.5 (Hex package) (mix)`
* Operating system: `OS X High Sierra`

### Current behavior

I have the following schema defined:
```elixir
defmodule PaintSchemer.Paints.Paint do
  use Ecto.Schema
  import Ecto.Changeset
  alias PaintSchemer.Paints.Paint


  schema "paints" do
    field :color, :binary
    field :name, :string
    belongs_to :manufacturer, PaintSchemer.Paints.Manufacturer
    belongs_to :type, PaintSchemer.Paints.PaintType

    timestamps()
  end

  @doc false
  def changeset(%Paint{} = paint, attrs) do
    paint
    |> cast(attrs, [:name, :color, :type_id, :manufacturer_id])
    |> validate_required([:name, :color, :type_id, :manufacturer_id])
  end
end
```

With the table created like this:
```elixir
defmodule PaintSchemer.Repo.Migrations.CreatePaints do
  use Ecto.Migration

  def change do
    create table(:paints) do
      add :name, :string
      add :color, :binary
      add :manufacturer_id, references(:paint_manufacturers, on_delete: :nothing)
      add :type_id, references(:paint_types, on_delete: :nothing)

      timestamps()
    end

    create index(:paints, [:manufacturer_id])
    create index(:paints, [:type_id])
  end
end
```

I also have some unit tests, that want to create this schema:

```elixir
@create_attrs %{color: <<12, 12, 12>>, name: "some name"}
  @update_attrs %{color: <<13, 12, 12>>, name: "some updated name"}
  @invalid_attrs %{color: nil, name: nil}

  def fixture(:paint) do
    {:ok, type} = Paints.create_paint_type(%{name: "Some paint type"})
    {:ok, manufacturer} = Paints.create_manufacturer(%{name: "Some manufacturer"})
    {:ok, paint} =
      @create_attrs
      |> Map.merge(%{type_id: type.id, manufacturer_id: manufacturer.id})
      |> Paints.create_paint
    paint
  end
```

When I run the tests I get the following error: 
```
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{manufacturer_id: 1594, name: "some name", type_id: 1636}, errors: [color: {"can't be blank", [validation: :required]}], data: #PaintSchemer.Paints.Paint<>, valid?: false>}
```

When I print out all the data in `changeset/2` I can see something like this:
```
attrs: %{color: "\f\f\f", manufacturer_id: 1615, name: "some name", type_id: 1657}
result: #Ecto.Changeset<
  action: nil,
  changes: %{manufacturer_id: 1615, name: "some name", type_id: 1657},
  errors: [color: {"can't be blank", [validation: :required]}],
  data: #PaintSchemer.Paints.Paint<>,
  valid?: false
>
```

Funnily enough, if I change the color to e.g. `@create_attrs %{color: <<15, 12, 12>>, name: "some name"}` everything works fine and I can write to the database.

I can see that the documentation for changeset says `If the value of a field is nil or a string made only of whitespace, the changeset is marked as invalid and an error is added`. It seems wrong however that `:binary` is treated the same as a `:string`, while they may use the same implementation in Elixir, that does not mean they are the same

### Expected behavior

I would expect with an arbitrary binary type I can put any binary I want into the database. Why are some binaries better than others? There does not seem to be any explanation for this in the documentation.

**Comment by josevalim** [comment]
It is a bug in `validate_required`. We use `String.trim_leading` although that should be used for strings. When you use it in a binary, it is trying to parse the bytes and the byte 12 is an empty character in strings.

My suggestion is to change `missing?` in Ecto.Changeset to read the type from the changeset and avoid the `String.trim` check for binaries. The question is if we also consider an empty binary to be missing or not.

**Comment by josevalim** [comment]
Related to this, we may also want to allow counting bytes in `validate_length`.

**Comment by hlhr** [comment]
I checked the code and think I can fix the bug as you suggested.

Maybe it makes sense to create a second issue for changing the behaviour for validate_length to separate these changes? I'm not sure if these should get mixed up.

**Comment by josevalim** [comment]
Yup. A separate issue sounds good. Especially because we may use a
different solution there.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hlhr** [comment]
Regarding validate_length:
I checked the code and tested it. <<12, 12, 12>> has the length of 3 is gets validated successfully with that length.
I also checked validate_length for and there is no String.trim_leading but maybe it should trim to get the same behaviour as validate_length.
So I'm not sure if there is a problem, maybe you can create the issue and specify the problem in detail.
