### ISSUE TITLE
On conflict fixes and improvements missing from releases 

### ISSUE THREAD

**Issue by icorderi** [elixir-ecto/ecto#2459]
@josevalim why are this fixes not being cherry picked into *2.x* ? 

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L492-L520

Some of that work was fixed in master 7 months ago. 

cc: @pedrofranceschi

**Comment by josevalim** [comment]
Because those features require changing adapters and we are not going to do that in a 2.2.x release.

**Comment by icorderi** [comment]
Well, then lets get a _2.3_ out of the door then, because `:replace_all` is overwriting the PK and we are not the only ones needing a conflict resolution that doesn't blow up foreign keys. 

This was brought up again back in nov 2017 https://github.com/elixir-ecto/ecto/issues/2329

**Comment by josevalim** [comment]
You can cherry pick that commit to a fork and use a fork. We have no plans
for a 2.3 release.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by icorderi** [comment]
So what about the 242 extra commits in master? are they just gonna be gathering dust indefinitely?

**Comment by josevalim** [comment]
Master is tracking 3.0. See the CHANGELOG.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
