### ISSUE TITLE
Update All with Fragments and Dynamic Columns

### ISSUE THREAD

**Issue by benwilson512** [elixir-ecto/ecto#2460]
In order to do an `update_all` with fragments the update bit needs to be in the ecto query via `update:`. However, `update` does not presently permit dynamic columns.

## Motivating Example
I have a set of tables from which I am trying to excise identification information. There are a set of columns one each table that I want to overwrite, in this case the user name would simply become `"User #{user.id}"`. This is demonstrable with the slightly simpler example:

```
col = :name
from u in User,
  update: [set: [{^col, "foo"}]]
```
```
malformed :set in update `[{^col, "foo"}]`, expected a keyword list
```
You get the same or similar errors with a bare `col` or `field(u, ^col)`.

Issue created per conversation with @josevalim

**Comment by michalmuskala** [comment]
We should probably allow using `^col` there. I don't think `field` is a good idea, because we can update just the main table anyway - `field` would allow setting update for a joined table, which doesn't make much sense.

**Comment by benwilson512** [comment]
Yup agreed, `^col` feels right to me here as well.
