### ISSUE TITLE
Removing defaults of string columns in migrations using postgres appears to set the default to "NULL"

### ISSUE THREAD

**Issue by doughsay** [elixir-ecto/ecto#2461]
### Environment

* Elixir version (elixir -v): 1.6.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql (9.6.8)
* Ecto version (mix deps): 2.2.9
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: macOS 10.13.3

### Current behavior

Please see this simple example app's migration: https://github.com/doughsay/ecto_default_test/blob/master/priv/repo/migrations/20180312220219_test_defaults.exs

The migration simply creates a table with an integer column and a string column, both with defaults.  It then attempts to remove the defaults.

```elixir
create table(:defaults_test) do
  add(:integer_test, :integer, default: 1337)
  add(:string_test, :string, default: "foo")
end

flush()

alter table(:defaults_test) do
  modify(:integer_test, :integer, default: nil)
  modify(:string_test, :string, default: nil)
end
```

This results in the following table schema after the migration is run:

```psql
ecto_default_test_repo=# \d defaults_test
                                    Table "public.defaults_test"
    Column    |          Type          |                         Modifiers
--------------+------------------------+------------------------------------------------------------
 id           | bigint                 | not null default nextval('defaults_test_id_seq'::regclass)
 integer_test | integer                |
 string_test  | character varying(255) | default NULL::character varying
Indexes:
    "defaults_test_pkey" PRIMARY KEY, btree (id)
```

As you can see, it appears that the integer column's default was correctly removed, but the string column's default was set to the string "NULL".

### Expected behavior

Expected that the string column's default is removed.

### Additional info

Forgive me if this has already been addressed, but I searched pretty thoroughly through ecto and postgrex issues and couldn't find anything that looked like it was related.  Also, I attempted to make the sample app with the latest git versions of ecto and postgrex, but dependency conflicts prevented me from trying that, so I used the latest published versions.

**Comment by michalmuskala** [comment]
It seems this default is not string "NULL", but actually null value. I'm not sure why it's printed that way in the table description, though.

Trying out this locally, the default value for the `string_test` column is `NULL`:

```
ecto_default_test_repo=# \d defaults_test
                                       Table "public.defaults_test"
    Column    |          Type          | Collation | Nullable |                  Default
--------------+------------------------+-----------+----------+-------------------------------------------
 id           | bigint                 |           | not null | nextval('defaults_test_id_seq'::regclass)
 integer_test | integer                |           |          |
 string_test  | character varying(255) |           |          | NULL::character varying
Indexes:
    "defaults_test_pkey" PRIMARY KEY, btree (id)

ecto_default_test_repo=# INSERT INTO defaults_test(integer_test) VALUES (1);
INSERT 0 1
ecto_default_test_repo=# SELECT * FROM defaults_test;
 id | integer_test | string_test
----+--------------+-------------
  1 |            1 |
(1 row)

ecto_default_test_repo=# SELECT * FROM defaults_test WHERE string_test IS NULL;
 id | integer_test | string_test
----+--------------+-------------
  1 |            1 |
(1 row)
```

It's true that the postgres documentation recommends using `DROP DEFAULT` for removing default, but just in the next paragraph says it is effectively equivalent to doing `DEFAULT NULL`, which is the SQL ecto is emitting here.

**Comment by doughsay** [comment]
@michalmuskala thanks for looking into it!  I'm sorry I didn't check that myself, but you can see how confusing that is.  Glad it's not a bug and I can continue to use this pattern without problems.
