### ISSUE TITLE
Migrations table and Ecto docs out of sync?

### ISSUE THREAD

**Issue by carlodicelico** [elixir-ecto/ecto#2462]
### Environment

* Elixir version (elixir -v): Elixir 1.6.3 (compiled with OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): ecto 2.2.9 (Hex package) (mix)
* Database adapter and version (mix deps): phoenix_ecto 3.3.0 (Hex package) (mix) / postgrex 0.13.5 (Hex package) (mix)
* Operating system: macOS High Sierra 10.13.3

### Current behavior

The [Ecto documentation](https://hexdocs.pm/ecto/Ecto.Migration.html#module-repo-configuration) and [code](https://github.com/elixir-ecto/ecto/blob/v2.2.9/lib/ecto/migration.ex#L152) state that the schema_migrations table's primary key and migration timestamps can be changed in the app repo's config:

```
config :app, App.Repo, migration_primary_key: [name: :uuid, type: :binary_id]
config :app, App.Repo, migration_timestamps: [type: :utc_datetime]
```

However, when I set the config properties above, they seem to be ignored, and the table is created with the default settings. Here, it is `version`, with a type of `bigint` (`bigserial` is turned into `bigint` [in the adapter](https://github.com/elixir-ecto/ecto/blob/v2.2.9/lib/ecto/adapters/postgres/connection.ex#L856)) as the primary key (not `id`). I'm unsure if `id` in the docs is meant to refer to `version`, or if the PK is not being created properly.

![image](https://user-images.githubusercontent.com/1778532/37361044-4bfdad44-26c8-11e8-9df9-c81f62bc612a.png)

### Expected behavior

I would expect the column to be called `id` (I think? 🤔) and to have the type set in my config, and the timestamp to have the type specified in my config.

Is this a legit issue or am I just missing something?

#### Update:

I _think_ I found where `version` [comes from](https://github.com/elixir-ecto/ecto/blob/v2.2.9/lib/ecto/migration/schema_migration.ex#L8). It seems that maybe this is where my config gets ignored, as well? 

_Also_ interesting: I see `:migration_source` appears to be checked much more often than `:migration_primary_key` or `:migration_timestamps`. See https://github.com/elixir-ecto/ecto/search?utf8=%E2%9C%93&q=migration_source&type= vs. https://github.com/elixir-ecto/ecto/search?utf8=%E2%9C%93&q=migration_primary_key&type= and https://github.com/elixir-ecto/ecto/search?utf8=%E2%9C%93&q=migration_timestamps&type=.  _Not_ entirely sure that actually means anything yet, just noting it.

Hmm... 🤔 yes, I think those config options don't actually make it through when the migrations table is created, based on my reading of https://github.com/elixir-ecto/ecto/blob/v2.2.9/lib/ecto/migrator.ex#L41 and https://github.com/elixir-ecto/ecto/blob/v2.2.9/lib/ecto/migration/schema_migration.ex.

**Comment by josevalim** [comment]
You are looking at the code for master. Please check the code in the branch with the version you are using. :)

**Comment by carlodicelico** [comment]
Whoops! Updated.

**Comment by josevalim** [comment]
Thanks for the updates! I think this is a documentation issue, because those options do not configure the migration table, it configures the defaults inside your own migrations. :)

**Comment by carlodicelico** [comment]
OH! Yes, that makes a _lot_ more sense...doh!  😂 Thank you, José!
