### ISSUE TITLE
Show Postgres notices when running migrations

### ISSUE THREAD

**Issue by quolpr** [elixir-ecto/ecto#2463]
#### Elixir version

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.3 (compiled with OTP 19

#### Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

postgres (PostgreSQL) 10.1

#### Ecto version (mix deps):

ecto 2.1.6

#### Database adapter and version (mix deps):

postgrex 0.13.5 (Hex package) (mix)

#### Operating system:

MacOs 10.12.6

### Current behavior

Postgres just silently truncate very long index name to 63 bytes:

https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes

Also, because of this the `unique_constraint()` validation suggest the full index name, while in DB the index name is truncated.

### Expected behavior

`Ecto.Migration.Runner` should show the notice from postgres, or just exit with error, like it is done in ActiveRecord (but it may break old ecto migrations)

I didn't check how it is working with table names, column names, etc... But should have the same silent truncating behavior

**Comment by josevalim** [comment]
Thanks. I have moved this issue here: https://github.com/elixir-ecto/postgrex/issues/346

**Comment by michalmuskala** [comment]
What do we need to do in this issue besides what was already done in postgrex?

**Comment by josevalim** [comment]
We need to take them out of the struct and print them.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
I have changed the adapter contract to support this in the future.

**Comment by qcam** [comment]
I could grab this issue if no one has taken. Guidances would be very appreciated though since I'm not super familiar with `postgrex` interface 😃.

**Comment by josevalim** [comment]
@qcam i am not sure quite how this looks like but if you look at `execute_ddl`, you will see that we make multiple queries. For postgres, it returns a Postgrex.Result struct that should have something like `:notices` inside of it. Then we need to figure out a contract to return it and print them from the migration runner.

**Comment by qcam** [comment]
@josevalim thanks for the guide, I think I could come up with a PR later today or tomorrow. As you suggested, I will wrap them (`Mariaex.Result` and `Postgrex.Result`) into something like `DDLResult`, then print them in the migration runner.

**Comment by josevalim** [comment]
I don't think we need a DDL result. I think we can ask adapters to return a list of `[{status, message}]` and that should be enough. :)

**Comment by josevalim** [comment]
Closing in favor of #2720.
