### ISSUE TITLE
Test Environment Setup Documentation

### ISSUE THREAD

**Issue by philippneugebauer** [elixir-ecto/ecto#2465]
I wanted to extend my existing Elixir application with Ecto. While the setup of the normal application was straight-forward through the documentation, I struggled a lot to set up the test environment. Finally, I was able to set it up to work following this post:
https://elixirforum.com/t/how-to-set-up-the-testing-environment-for-a-library-that-uses-ecto/4770/3

I was searching quite a time to find possible test setups but they all didn't work till the last one right now. I think, we should extend the documentation about the information of the post since it is relevant information.

**Comment by josevalim** [comment]
Thanks @philippneugebauer! Could you please send a pull request with this documentation?

I would add a new file [here](https://github.com/elixir-ecto/ecto/tree/master/guides) saying "Adding Ecto to a project.md" that covers regular and the test environment setup.

Let me know if you have any questions!

**Comment by philippneugebauer** [comment]
@josevalim what happens then to the at least partially redundant information in getting started?
Should it be added to the Readme as well?

**Comment by josevalim** [comment]
@philippneugebauer oh, I see. Let's add them a "Testing with Ecto" section and make sure to link to it from the Getting Started. :)
