### ISSUE TITLE
an alternative to the callbacks 

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#2470]
Since the callbacks such as "after_create" have been eliminated, what's the alternative to them?

**Comment by AndrewDryga** [comment]
@GildedHonour Can you provide a use case so we can discuss it on an example?

Generally, instead of having a callback you just need a function that would do an insert and then whatever you want to do after data is inserted, this is much more explicit and, from my experience, it works really well.

**Comment by josevalim** [comment]
Please use the ElixirForum or StackOverflow for questions, we reserve the issues tracker for issues only.

**Comment by GildedHonour** [comment]
> Generally, instead of having a callback you just need a function that would do an insert and then whatever you want to do after data is inserted, this is much more explicit and, from my experience, it works really well.

bingo. that's a callback.
