### ISSUE TITLE
Swap embedded schemas dynamically

### ISSUE THREAD

**Issue by IcyEagle** [elixir-ecto/ecto#2479]
I wonder if is it possible to set embedded schema dynamically?

Example:
```elixir
def FirstOperation do
  embedded_schema do
    field :foo, :string
  end

  def changeset(data, params) do
    data
    |> cast(params, [:foo])
  end
end

def SecondOperation do
  embedded_schema do
    field :bar, :string
  end

  def changeset(data, params) do
    data
    |> cast(params, [:bar])
  end
end

defmodule Operation do
  schema "operations" do
    field :type, :string
    field :data, :map
  end

  def changeset(operation, params) do
    data_module = if operation.type == :first, do: FirstOperation, else: SecondOperation

    operation
    |> cast(params, [:type, :data])
    # the next line is incorrect I think
    |> cast_embed(:data, with: &data_module.changeset/2)
  end
end
```

**Comment by IcyEagle** [comment]
Related issue #1750

**Comment by IcyEagle** [comment]
Well, I've found solution [here](https://hexdocs.pm/ecto/Ecto.Changeset.html#module-schemaless-changesets) actually :)

Take a look at this [PR](https://github.com/elixir-ecto/ecto/commit/efbfe10c799b41ac71c982eac021f331c4d724d0) for details.

**Comment by meatherly** [comment]
```
** (Ecto.ChangeError) value `#Ecto.Changeset<action: :insert, changes: %{payload: "ABFF", port: 1}, errors: [], data: #CustomNested<>, valid?: true>` for `Parent.data` in `insert` does not match type :map

```
@IcyEagle were able to get around this error when trying to insert your dynamic embedded into the db?

**Comment by IcyEagle** [comment]
@meatherly I suddenly switched to another task and this feature was postponed so I didn't try. By the way there is another problem here. How to cast `:map` to the specific embedded schema when your model is fetched? Probably it's possible to setup kind of callback or maybe create new type for that but currently it's [not supported](https://groups.google.com/forum/#!topic/elixir-ecto/Okf87dNhNFk).

**Comment by 1player** [comment]
I've shared a code snippet that does this on another issue, hope it helps: https://github.com/elixir-ecto/ecto/pull/2113#issuecomment-412829999
