### ISSUE TITLE
Queries in associations must be known at compile time

### ISSUE THREAD

**Issue by zachdaniel** [elixir-ecto/ecto#2480]
So I went about using this more in depth in my own codebase, and I'm realizing that there is probably a flaw in the initial implementation (sorry D:). Lets say we have two separate files: post.ex, and comment.ex

```
# post.ex
defmodule Post do
  use Ecto.Schema
  schema "posts" do
    field :active, :boolean
    has_many :active_comments, Comment.active()
  end

  def active() do
    from row in __MODULE__,
      where: row.active
  end
end

#comment.ex
defmodule Comment do
  use Ecto.Schema
  schema "comments" do
    field :active, :boolean
    has_many :posts, Post.active()
  end

  def active() do
    from row in __MODULE__,
      where: row.active
  end
end
```

For obvious reasons, this can't work. Does anyone have any ideas for this one?

**Comment by zachdaniel** [comment]
This *also* doesn't work if the functions are in separate files I think, becuase `from` calls `.__schema__()`, so these would still have a transitive compile time dependency on eachother in that case.

**Comment by josevalim** [comment]
I was aware of the first part of the flaw but I forgot it would also hit for regular queries. I am not sure of the proper fix right now.

**Comment by zachdaniel** [comment]
@josevalim we could make the destination query a runtime concern as opposed to a compile time concern? `has_many, :posts, Post, queryable: &Post.active/0` That honestly seems pretty heavy handed, and I feel like there are tools already in use in ecto to resolve the unresolvable things at runtime. We just need to find a way to make a query used in the association do the same thing.

**Comment by zachdaniel** [comment]
I think this might also make self association w/ a query impossible.

**Comment by josevalim** [comment]
Your option is one way to go but we would need to use an atom and/or MFArgs tuple:

    has_many :posts, Post, queryable: :active
    has_many :posts, Post, queryable: {Post, :active, []}

Another option is to allow the user to pass the `where` clauses directly:

    has_many :posts, Post, where: [active: true]

This would allow us to automatically set active to true when using build_assoc but it would limit our filters only to comparisons unless we allow `dynamic`:

    has_many :posts, Post, where: dynamic([p], ...p.active...)

Both cases hurt composition though as you need to define the query inline instead of reusing a previou definition.

**Comment by zachdaniel** [comment]
I wonder if we could do something here:
```
  defmacro has_many(name, queryable, opts \\ []) do
    related = parse_related_out_of_ast(queryable) #I'm sure this helper exists already
    queryable = expand_alias(related, __CALLER__)
    quote do
      Ecto.Schema.__has_many__(__MODULE__, unquote(name), unquote(queryable), unquote(opts), queryable)
    end
  end
```
leaving the actual query itself quoted until a later time?

**Comment by zachdaniel** [comment]
ah, but the destination wouldn't be in there, because it could be anything, like a function call.

**Comment by zachdaniel** [comment]
I'm also not 100% sure exactly where this breaks :/

**Comment by zachdaniel** [comment]
I think I'm partial to `has_many :posts, Post, queryable: {Post, :active, []}`. I think the compile time dependencies getting added makes this a feature that too many people would *start* using, and then the first time they complete a circle somewhere they'd be having a bad time. With that in mind, I think we should remove the original version of this, and then implement an alternative.

**Comment by zachdaniel** [comment]
We could do it in a way similar to `field_mapper` where we do some kind of dispatch? Like `assoc_mapper: ` where they can define a function in their schema that does the work? so they can set that, and then do ```
def query_for_association(:comments) do
  Comment.active()
end
```

**Comment by zachdaniel** [comment]
@josevalim I think I found a way to make this compile time dependency unnecessary. If we had a pattern for sources that was `{prefix, "table", Schema}` then we would never need to call `__schema__(:prefix)`  in `from`. Or if we had a global option to disable that entirely, or something along those lines. Either one of those would enable a workaround for this, which is specifying all of the potential compile time dependency information directly in the query. granted this is only compile time if its referenced in an association now, so its not a *true* compile time dependency unless you are using this feature.

**Comment by zachdaniel** [comment]
Thinking about our use case, I think the only win is for it to be determined at runtime, like this: `has_many :posts, Post, queryable: {Post, :active, []}`

**Comment by zachdaniel** [comment]
@josevalim Have you had any thoughts on this?

**Comment by josevalim** [comment]
I haven't reached a decision yet. I think the most natural is to pass a `where` to the association, even though it leads to duplication. It is also worth noting the query would work as `from p in "posts", ...` but I have no idea how to enforce that.

**Comment by josevalim** [comment]
Actually, I think I know of a way to make this work as is. I will try it later. :)

**Comment by zachdaniel** [comment]
That would be awesome :)

**Comment by josevalim** [comment]
Actually, we can support:

    has_many :posts, from(p in Post, ....)

I don’t think we can support Post.active all the way because there is no
way that can’t be a cyclic dependency.

So we have two options:

1. Keep the current API but the user will be able to invoke the other
module only on half of the cases

2. Pass the “where: ...” option to associations.

 Preferences?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
The :where option could support expressions by using the dynamic macro.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
After a bit more thought and trying a couple things around, I think `where` is the best way to go. Because even though I could fix `from`, at the moment we support custom expressions, there will always be some sort of expression that could go wrong.

What do you think? Would you give it a try?

**Comment by zachdaniel** [comment]
@josevalim I think we could work with that, yes :D. I think step one would just be reverting the original implementation, and then we can go from there.

**Comment by josevalim** [comment]
@zachdaniel it is up to you. :) If you want to revert, you can just send a PR that reverts it. :)

**Comment by josevalim** [comment]
Although I think the docs and tests will mostly still hold. But your call, really.

**Comment by zachdaniel** [comment]
@josevalim I think you are right, that most things will hold. It would significantly help my use-case if it where possible to provide a mfa to the `where` option. I'm imagining instead of
```
  has_many :posts, Post.special()
```
We will see
```
has_many :posts, Post, where: Post.special()
# or
has_many :posts, Post, where: [special: true]
```
And if I can already tell that if I'm going to be taking that option and adding it to the query, that it would be trival to also accept
```
has_many :posts, Post, where: {Post, :special, []}
# or
has_many :posts, Post, where: &Post.special/0
```

**Comment by josevalim** [comment]
@zachdaniel I think we can support `has_many :posts, Post, where: Post.special()` where `Post.special` returns a keyword list or a dynamic query. It has the benefit of working at compile-time.

**Comment by zachdaniel** [comment]
The issue for us is that it would take a significant amount of work to move that logic into separate modules, i.e not the modules that are also the destination of the relationship. But since many of our relationships need to express this between each other, if it *has* to work at compile time then we will have to do a lot of legwork to move things around. Using the keyword/dynamic makes it possible for us (since keywords/dynamics don't incur the compile time dependencies like a query does), but its far from ideal to have to take what is currently a `.query()` function on each of our schemas and move it to an external module to be referenced.

**Comment by zachdaniel** [comment]
:+1:

**Comment by zachdaniel** [comment]
I'm also getting errors when trying to use dynamic, due to it trying to quote the anonymous function inside of the DynamicExpr. ```
** (ArgumentError) cannot escape #Function<1.4162596/1 in Ecto.AssociationTest.AuthorPermalink.active/0>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
```

**Comment by josevalim** [comment]
`join_throuogh_where` looks good to me unless you have better suggestions. :)

And good catch regarding `dynamic`. We may need t convert it to a MFA tuple first. Would you give it a try? Otherwise I can take a look at it later, just let me know.

**Comment by zachdaniel** [comment]
@josevalim so if I see a function call like `Post.active()` I should just destructure that into an MFA? Or is it something more specific than that, like taking the return value of that function, and determining if it returns a `dynamic` and then somehow converting that to an MFA?

**Comment by zachdaniel** [comment]
Oh, duh. That can be converted to the obvious MFA of `{Ecto.Query, :dynamic, [expr]}`. Nevermind me :)

**Comment by zachdaniel** [comment]
I think I've got it. Gotta run to dinner will PR tonight.

**Comment by josevalim** [comment]
> so if I see a function call like Post.active() I should just destructure that into an MFA?

No, we will just invoke it normally.
