### ISSUE TITLE
Please :time field support "hh:mm" format

### ISSUE THREAD

**Issue by kobatako** [elixir-ecto/ecto#2481]
Hi.

I use :time field in ecto schema, but catch invalid error :time field.
Attempting to enter a value of format "hh: mm" will result in invalid.

```
> Ecto.Changeset.cast(%User{}, %{"set_time" => "10:30"}, [:set_time])
%Ecto.Changeset{
  action: null,
  changes: %{},
  errors: [
    set_time: {"is invalid", [type: :time, validation: :cast]}
  ],
  data: #Example.User<>,
  valid?: false
}
```

Is it possible to add functions so that "hh: mm" format can be supported?

**Comment by josevalim** [comment]
We can support it. Meanwhile, note that Ecto allows you to create custom types with custom casting rules. See the documentation for `Ecto.Type` for more information.

**Comment by kobatako** [comment]
Thank you for your reply.
I knew that I could customize with Ecto.Type, but I'm glad that I can handle it with modules.
May I give this pull request by myself?

**Comment by josevalim** [comment]
> May I give this pull request by myself?

Yes please! :)

**Comment by kobatako** [comment]
OK!!

**Comment by wojtekmach** [comment]
@josevalim what do you think about similarly making this work:

```elixir
iex> Ecto.Type.cast(:naive_datetime, "2018-01-01 09:00")
```

this would be consistent with what this issue is about as well as:

```elixir
iex> Ecto.Type.cast(:naive_datetime, %{year: 2018, month: 1, day: 1, hour: 9, minute: 0})
{:ok, ~N[2018-01-01 09:00:00]}
```

Same for `:utc_datetime`. If sounds good I'll create an issue for it.
