### ISSUE TITLE
select: type(sum(l.amount),ModuleName) raises exception

### ISSUE THREAD

**Issue by kipcole9** [elixir-ecto/ecto#2485]
### Environment

* Elixir master and 1.6.4
* Mac OSX High Sierra

### Current behavior

```elixir
iex> q = from l in Ledger, select: type(sum(l.amount), Money.Ecto.Composite.Type)
** (UndefinedFunctionError) function :__aliases__.type/1 is undefined (module :__aliases__ is not available)
    :__aliases__.type({:__aliases__, [line: 8, counter: -576460752303421118], [:Money, :Ecto, :Composite, :Type]})
    (ecto) lib/ecto/type.ex:243: Ecto.Type.match?/2
    (ecto) lib/ecto/query/builder.ex:374: Ecto.Query.Builder.assert_type!/3
    (ecto) lib/ecto/query/builder.ex:235: Ecto.Query.Builder.escape/5
    (ecto) lib/ecto/query/builder/select.ex:119: Ecto.Query.Builder.Select.escape_with_type/5
    (ecto) lib/ecto/query/builder/select.ex:204: Ecto.Query.Builder.Select.build/5
    (ecto) expanding macro: Ecto.Query.select/3
    iex:8: (file)
```

Where `amount` is a [custom ecto type](https://github.com/kipcole9/money/blob/master/lib/money/ecto/money_ecto_composite_type.ex) that supports a [Postgres composite type](https://github.com/kipcole9/money/blob/master/lib/mix/tasks/money_postgres_migration.ex#L53-L57). There are no known issues with this part which has been around for a while.

### Source of the error

The error surfaces with a `select` containing an aggregate function inside a `type` expression with a custom Ecto type.  In this case the aggregate is `sum(l.amount)` and the custom type module is `Money.Ecto.Composite.Type`.

The issue appears to be in `Ecto.Query.Builder`
```elixir
  defp assert_type!(expr, type, actual) do
    if Ecto.Type.match?(type, actual) do   <<---- type is quoted
      :ok
    else
      error! "expression `#{Macro.to_string(expr)}` does not type check. " <>
             "It returns a value of type #{inspect actual} but a value of " <>
             "type #{inspect type} is expected"
    end
  end
```
because `type` in this case is the quoted form of the module `Money.Ecto.Composite.Type`

### Possible fix

The fix appears to be a simple one (tested on master with `mix test`) and all tests pass.  Simply expanding the type before calling `Ecto.Type.match?/2`.
```elixir
  defp assert_type!(expr, type, actual) do
    if Ecto.Type.match?(Macro.expand(type, __ENV__), actual) do
      :ok
    else
      error! "expression `#{Macro.to_string(expr)}` does not type check. " <>
             "It returns a value of type #{inspect actual} but a value of " <>
             "type #{inspect type} is expected"
    end
  end
```

### Future work

I took a look at the test suite but its not clear to me where to add tests and how best to test this.  Suggestions welcome.  Also fine to submit a PR.

### Expected behavior

When testing with this change the correct result is returned:
```elixir
iex> q = from l in Ledger, select: type(sum(l.amount), Money.Ecto.Composite.Type)  
#Ecto.Query<from l in Ledger,
 select: type(sum(l.amount), Money.Ecto.Composite.Type)>
iex> Repo.all q                                                                    
[debug] QUERY OK source="ledgers" db=6.0ms
SELECT sum(l0."amount")::money_with_currency FROM "ledgers" AS l0 []
[#Money<:USD, 600.00000000>]
```

**Comment by zachdaniel** [comment]
I wonder if `select: type(sum(l.amount), ^Money.Ecto.Composite.Type)` would also work?

**Comment by josevalim** [comment]
@kipcole9 beautiful. Could you please send a PR with tests? We have some custom types already in ecto test suite you could use. Thanks!

**Comment by kipcole9** [comment]
Closing since this is working as expected on master.

**Comment by LostKobrakai** [comment]
I just came to the same issue and I cannot use a `source.field` notation as I'm querying a dynamic field:

```elixir
select: type(sum(field(x, ^field)), Money_Composite)
select: type(sum(field(x, ^field)), ^Money_Composite)
select: type(sum(field(x, ^field)), :money_with_currency)
select: type(sum(field(x, ^field)), field(x, ^field))
```

Neither of the above seem to work.

**Comment by josevalim** [comment]
Can you please open up a new issue with Ecto version, sample queries,
letting us know if this a regression or not and so on? Thank you.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
