### ISSUE TITLE
ConstraintError message issue

### ISSUE THREAD

**Issue by lobo-tuerto** [elixir-ecto/ecto#2492]
### Environment

* Elixir version (elixir -v): **1.6.4**
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): **psql (PostgreSQL) 10.3**
* Ecto version (mix deps): **ecto 2.2.9 (Hex package) (mix)**
* Database adapter and version (mix deps): **postgrex 0.13.5 (Hex package) (mix)**
* Operating system: **Manjaro Linux 17.1.7**

### Current behavior

When you have a unique index but don't have a constraint declared in your changeset, you'll see this error:

```bash
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * unique: users_email_index

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

    (ecto) lib/ecto/repo/schema.ex:574: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/schema.ex:559: Ecto.Repo.Schema.constraints_to_errors/3
    (ecto) lib/ecto/repo/schema.ex:222: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
```

### Expected behavior

I think this line:

```bash
If you would like to convert this constraint into an error, please...
```

Should read:

```bash
If you would like to convert this error into a constraint, please...
```

Since what you are getting is an error already, and you probably want to turn that error into a constraint in your model.

Is my understanding right or am I mixing things —and semantics— up?

**Comment by josevalim** [comment]
Good call! I think the issue here is that error is ambiguous. We meant to say a "changeset error" and not an exception. Here are some more options:

> If you would like to convert this exception into a changeset error, please...

> If you would like to convert this constraint violation into a changeset error, please...

I think I prefer the second. Thoughts?

**Comment by michalmuskala** [comment]
The second proposal seems better to be as well :+1:

**Comment by zachdaniel** [comment]
I think that the most important distinction is that it will no longer raise after you do this.

> If you would like to stop this violation from raising an exception, and instead have it added as a changeset error...

`convert this constraint violation into a changeset error` doesn't necessarily imply to the inexperienced what is going to change when they do that.

**Comment by josevalim** [comment]
@zachdaniel :+1: I will go with something like that. Commit incoming. :)

**Comment by lobo-tuerto** [comment]
I think this is the fastest reply I have ever had on GitHub, kudos to you all! :D
