### ISSUE TITLE
Ecto drop/create/migrate should prioritize its own configuration over any existing default env variables for Postgres database.

### ISSUE THREAD

**Issue by mkreyman** [elixir-ecto/ecto#2493]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.2 (compiled with OTP 20)
```
* Database and version (postgres -V): `postgres (PostgreSQL) 10.3`
* Ecto version (mix deps): `phoenix_ecto 3.3.0`
* Database adapter and version (mix deps): `postgrex 0.13.5`
* Phoenix version (mix deps): `phoenix 1.3.2`
* Operating system: `macOS Sierra, 10.12.6`

### Current behavior

A "new" project seems to use configuration for an "old" project and ignores its own `config/dev.exs`. I have the following in my `~/.bash_profile` for an "old" phoenix project:
```
export DB_USER=$USER
export DB_PASSWORD=''
export DB_NAME='old_project_dev'
export DB_HOST='localhost'
export DATABASE_URL="ecto://$DB_USER:$DB_PASSWORD@$DB_HOST/$DB_NAME"
```

...and here's `config/dev.exs` for it:
```
config :old_project, OldProject.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD"),
  database: System.get_env("DB_NAME"),
  hostname: System.get_env("DB_HOST"),
  pool_size: 10
```

Here's the "new" project's `config/dev.exs`:
```
config :new_project, NewProject.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "new_project_dev",
  hostname: "localhost",
  pool_size: 10
```

Now, when I drop, create and run migrations in the "new" project's directory, those actions are getting executed on the "old" database!

Renaming the env variables for the "old" project resolved the issue.

### Expected behavior

Ecto drop/create/migrate should prioritize its own configuration over any existing default env variables for Postgres database.

**Comment by mkreyman** [comment]
@josevalim, I suspect that this issue is related to https://github.com/elixir-ecto/ecto/issues/2169 somehow. And what throws the ecto config off is the existence of those specific env variables in computer memory: `DB_USER`, `DB_PASSWORD`, `DB_NAME`, `DB_HOST` and `DATABASE_URL`. 

To reproduce the issue, please export those env variables from your shell, verify they exist with `echo $DB_NAME`, etc., and then try to run ecto commands. See if ecto honors its configuration in `config/dev.exs` or the values configured in the above env variables.

Again, to fix the issue all I had to do is to rename those vars, in my `.bash_profile` and in my "old" project config, and then to restart my shell.

**Comment by josevalim** [comment]
@mkreyman I cannot reproduce it. Here is what I did:

```
$ git clone ecto
$ cd examples/friends
$ mix deps.get
$ DB_USER="not_available" mix ecto.create
```

And it creates the database just fine, which means it is not picking the DB_USER environment variable.

I have also searched ecto and all of its dependencies and I could not find DB_USER listed anywhere.

**Comment by mkreyman** [comment]
I did the following steps and was able to reproduce again:

```
# in my ~/.bash_profile
export DB_USER=$USER
# blank password
export DB_PASSWORD=''
export DB_NAME='old_project_dev'
export DB_HOST='localhost'
export DATABASE_URL="ecto://$TM_DB_USER:$TM_DB_PASSWORD@$TM_DB_HOST/$TM_DB_NAME"

# Now from my shell...

$ psql -l
# old_project_dev exists

$ mix phx.new new_project
$ cd new_project/
$ mix deps.get
$ mix ecto.create
=> Compiling 13 files (.ex)
     Generated new_project app
     The database for NewProject.Repo has already been created

$ psql -l
# the new_project_dev doesn't exist; it's old_project_dev that mix ecto.create reported as existing.
```

**Comment by josevalim** [comment]
@mkreyman ah, that's because of the DATABASE_URL and Phoenix. If you look at the repository generated by your Phoenix application inside lib/my_app/repo.ex, you will see it is reading DATABASE_URL and using it to override your config. If you remove that code or change the environment variable you should be good to go.

**Comment by mkreyman** [comment]
Got it. Thanks!

**Comment by mkreyman** [comment]
@josevalim Frankly, I still find it confusing that phoenix would have two places to retrieve db configuration from, and that `lib/my_app/repo.ex` would override `config/*.exs` instead of referencing it.
