### ISSUE TITLE
[Docs] The Associations many_to_many guide causes a runtime error due to non-preloaded associations

### ISSUE THREAD

**Issue by mindseyeblind** [elixir-ecto/ecto#2495]
The Persistence section is the culprit - line 2 of the 3rd code block:
```
post_with_tags = Ecto.Changeset.put_assoc(post_changeset, :tags, [clickbait_tag, misc_tag])
```
spawns the error
```
(RuntimeError) attempting to cast or change association `components` from `EctoAssoc.Post` that was 1not loaded. Please preload your associations before manipulating them through changesets
```
Also, clicking the [link](https://hexdocs.pm/ecto/associations.html#persistence) next to the Persistence heading takes you to the Persistence section under one-to-one. Maybe customize the headings so that they're unique?

### Environment

* Elixir version: 1.6.4
* Database and version: PostgreSQL 9.6
* Ecto version: 2.2.9
* Database adapter and version: postgrex 0.13.4
* Operating system: Ubuntu 17.10

**Comment by josevalim** [comment]
Sounds good! @mindseyeblind, could you please send a PR?

**Comment by mindseyeblind** [comment]
I will, sometime over the weekend. Gonna rename the section headings too, to a format like "Persisting Many-to-Many Associations" so that they are all unique

**Comment by josevalim** [comment]
@mindseyeblind perfect.

**Comment by josevalim** [comment]
Ping. :)

**Comment by mindseyeblind** [comment]
This is actually fixed in the v3 docs as of @radar's PR referencing issue #2417. I'm still going to make a PR for the section header thing, a couple other fixes, and an addition to the many-to-many guide.
