### ISSUE TITLE
Ecto.Query.API.type/2 does not compiles in order_by macro

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#2496]
### Environment

```bash
$ asdf current
elixir         1.6.4-otp-20
erlang         20.3.2
postgres       10.3

$ mix deps
# …
* postgrex 0.13.5 (Hex package) (mix)
  locked at 0.13.5 (postgrex) 3d931aba
  ok
* ecto 2.2.8 (Hex package) (mix)
  locked at 2.2.8 (ecto) a4463c09
  ok
# …
```
Funtoo Linux current x86-64bit on intel64-ivybridge

### My situation

I already have created my own query builder (from parameters send to API).

Everything is working, but we found issue that our API does not sort well fields in embedded schema.
I found that it's because we do not store some types in json column (which is normal in this format) and sorting its values causes sorting based on stored string and not on real values (like numbers).

To solve that I decided to dynamically find embedded field type and cast it. All variables are already prepared, but it fails when compiling project.

I tried to create a simple query in console and found that `order_by` does not allow calling: `&Ecto.Query.API.type/2`.

### Current behavior

Same code in `select` works, but it does not work in `order_by`.

### Example

```
import Ecto.Query

# this works:
Repo.all from m in Model, select: type(fragment("(?->>?)", field(m, :field_name), "json_key_name"), :type)

# this one also works
Repo.all from m in Model, order_by: fragment("(?->>?)", field(m, :field_name), "json_key_name")

# but this not
Repo.all from m in Model, order_by: type(fragment("(?->>?)", field(m, :field_name), "json_key_name"), :type)
```

### Error

```
== Compilation error in file path/to/file.extension ==
** (Ecto.Query.CompileError) `type(fragment("(?->>?)", field(query, ^field_name), ^json_key_name), ^cast_type)` is not a valid query expression.

* If you intended to call a database function, please check the documentation
  for Ecto.Query to see the supported database expressions

* If you intended to call an Elixir function or introduce a value,
  you need to explicitly interpolate it with ^

    expanding macro: Ecto.Query.order_by/3
    path/to/file.extension:line: Called.Project.function/arity
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by josevalim** [comment]
The reason why `type/2` works with fragments in select is because we are using type to customize the output value. In the order by case, there is no output value, so type/2 doesn't make much sense there.

We could make it work, just so you can use the type expressions consistently in order_by and select. However, type/2 also performs type casting, so you need to have in mind that `type(fragment("(?->>?)", field(m, :field_name), "json_key_name"), :type)` in the order by will cast the result to `type` too.

**Comment by Eiji7** [comment]
@josevalim 
> We could make it work, just so you can use the type expressions consistently in order_by and select. However, type/2 also performs type casting, so you need to have in mind that type(fragment("(?->>?)", field(m, :field_name), "json_key_name"), :type) in the order by will cast the result to type too.

It's exactly what I need. I want to cast json value to real value at database level (as in my schema) to properly sort it using `order_by` macro. Currently I'm using `__schema__(:type, :field_name)` to find a type of field and convert it to database cast type which I wanted to pass as `type/2` argument.

I tried to use `fragment("(?->>?)::?", …)` but it also not worked and then I found `type/2` call in documentation.

**Comment by josevalim** [comment]
@Eiji7 makes sense. A pr would be welcome then! It should be a matter of porting the type validation logic that exists in query/select.ex to query/builder.ex, so it becomes general, and writing a test for both test/ecto/adapters/mysql_test and test/ecto/adapters/postgrex_test
