### ISSUE TITLE
Add error function to Multi

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2507]
For example, `Multi.error(multi, :subscription, "subscription failed")`. This is a shortcut to return a failed multi to an API that expected a multi.

If an error is present, we shouldn't even start the transaction (which is similar to how the changeset functions work).

/cc @ericmj @michalmuskala

**Comment by hlhr** [comment]
I would give it a try.

**Comment by josevalim** [comment]
Thanks @hlhr! Someone pointed out that this function is already part of the API, so it is just a matter of guaranteeing it fails early and updating the docs. :)

**Comment by hlhr** [comment]
@josevalim Yes I already saw that. Just to make sure, what do you mean with "just a matter of guaranteein"? Do you mean change the ordering of the calls or put the `:error` as the first call?
