### ISSUE TITLE
Ecto.Query.API.type/2 translate integer as bigint in PostgreSQL

### ISSUE THREAD

**Issue by darkbaby123** [elixir-ecto/ecto#2509]
### Environment

* Elixir version (elixir -v): 1.6.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.3
* Ecto version (mix deps): 2.2.9
* Database adapter and version (mix deps): 0.13.5
* Operating system: Ubuntu

### Current behavior

I have a table with `integer[]` type in PostgreSQL. In migration I define the column as `add :some_field, {:array, :integer}`. When building a query I use `type(^value, {:array, :integer})` and the generated SQL fragment is `?::bigint[]`. When combine with array operators and functions, PostgreSQL raises error about type mismatch.

The reason is that Ecto treat `integer` as `bigint` in database level [here](https://github.com/elixir-ecto/ecto/blob/v2.2.10/lib/ecto/adapters/postgres/connection.ex#L532). There's a related issue #2343 . 

I know that the column type in migration and field type in schema are 2 things. But `type/2` has to concern data type transformation in both application level and database level. So it's not wise to force `type/2` to treat `integer` as `bigint`. It's very confusing, and people can't specify `integer` type in PostgreSQL.

### Expected behavior

I suggest 2 solutions.

Solution 1: let `type/2` to support all PostgreSQL integer types (`smallint`, `integer` and `bigint`).

Solution 2: let `type/2` don't concern types in database level.

Personally I prefer solution 2. It's more clear to separate types in application level (schema and type) and database level (migration). If the data is the right type in application level, it works fine in most case. Users can also explicitly write `::type` with fragment if necessary.

**Comment by josevalim** [comment]
type/2 may perform casting on interpolated inputs and therefore it must
concern itself with Ecto types. The solution here is indeed to use a
fragment.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by darkbaby123** [comment]
Yes `type/2` should perform casting on interpolated inputs. But the issue is that it also generate `::bigint[]` in SQL (when we use `{:array, :integer}`). I don't think it's an expected behaviour because of 2 reasons.

1. Ecto type `:integer` translates to PostgreSQL type `bigint` is wrong and confusing. Especially in the migration `:integer` means PostgreSQL type `integer`.
2. User can not specify PostgreSQL `integer` with `type/2`, unless he manually use `::`. It makes `type/2` less useful.

Given my use case as an example. I have a `samples` table which has a `filter_ids` column, the type is `integer[]`. In the query I want to use array operator `@>`, so I write code like this:

```elixir
# Explicit specify type
fragment("? @> ?", sp.filter_ids, type(val, {:array, :integer}))

# Use the same type as filter_ids
fragment("? @> ?", sp.filter_ids, type(val, sp.filter_ids))
```

In both form, the generated SQL is like `s0.filter_ids @> $1::bigint[]`. Because PostgreSQL is explicit about types when calling operators and functions, the SQL will raise error. The solution is either changing column type to `bigint[]` or using `fragment("? @> ?::integer[]")`.

Actually I think `type/2` can't guess the database level type correct. For example I can have `{:array, :map}` in schema and the database level type is `jsonb`. So my opinion is, if it can't guess right, just don't guess.
