### ISSUE TITLE
Clearly document supported field data types

### ISSUE THREAD

**Issue by AndresOsinski** [elixir-ecto/ecto#251]
I have been looking for quite a while in the docs and examples where the full listing of supported data types and coercions is.

I'm willing to submit a patch with that if anyone can point me to the right place in the source.

**Comment by maxim** [comment]
For future googlers, the list of primitive types is at https://hexdocs.pm/ecto/Ecto.Schema.html - search page for primitive types.

**Comment by lukerollans** [comment]
@maxim Future googler reporting in, thanks!
