### ISSUE TITLE
mix.exs Postgrex Dependency 

### ISSUE THREAD

**Issue by asummers** [elixir-ecto/ecto#2516]
[The mix file](https://github.com/elixir-ecto/ecto/blob/master/mix.exs#L48) references a `0.14.0-dev`, but I cannot find this on Hex in the list of versions [here](https://hex.pm/packages/postgrex) or in the branches on GitHub for Postgrex [here](https://github.com/elixir-ecto/postgrex/branches/all) or releases [here](https://github.com/elixir-ecto/postgrex/releases). My `mix.lock` file seems to point to [this](https://github.com/elixir-ecto/postgrex/commit/648e59870d4bb3df0c553b9b43eeaeaac5791687) commit, but I'm unsure why that commit in particular is being pinned. I feel like the dependency in the `mix.exs` file should be pointing to a different branch/SHA, but I'm unsure what it should ultimately be pointing to. 

Unsure if this is an actual bug, but I figured I'd open an an issue anyway because I don't understand the current behavior and the explanation itself might be enlightening 😄.

**Comment by fishcakez** [comment]
Hi @asummers this isnt a bug, master is pointing to master on git while Ecto 3 work is underway. We don't want to release breaking changes in drivers only to revert them if Ecto 3 requires it. You should stick with hex releases or v2.2 branch if you insist on following git.
