### ISSUE TITLE
Migrations being applied to the wrong repo with multiple repos

### ISSUE THREAD

**Issue by dantswain** [elixir-ecto/ecto#2521]
### Precheck

Wasn't able to find this reported anywhere else.

### Environment

* Elixir version (elixir -v):  1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 9.5
* Ecto version (mix deps): 2.2.9
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: mac OS 10.13.4

### Current behavior

I have an app with two repos:  `MyApp.Repo` for the application itself, and `MyAppTest.Repo` for testing.  In config.exs, I only configure `MyApp.Repo`.  In `test.exs`, I configure both.

I can create/drop/etc the test repo by running commands with `MIX_ENV=test` - e.g., `MIX_ENV=test mix ecto.create` creates both test repos.  `mix ecto.create` creates only the dev repo.   This is what I expected :+1:.

The weirdness comes with migrations.  I can create a migration for `MyAppTest.Repo` using `MIX_ENV=testd mix ecto.gen.migration some_migration -r MyAppTest.Repo` and it creates a file in `priv/repo/migrations` that defines `MyAppTest.Repo.Migrations.SomeMigration`.  When I run `mix ecto.migrate` the migration is applied to `MyApp.Repo`.  When I run `MIX_ENV=test mix ecto.migrate`, it applies the migration to BOTH repositories.

Another slightly odd thing that happens is that I get warnings that the migration modules are being redefined `(current version defined in memory)` when I run `MIX_ENV=test mix ecto.migrate`.

### Expected behavior

I expected that the migrations would be applied to the appropriate repos.  It's not clear from the documentation how ecto chooses which migrations to apply to which repos.  I assumed this was "automatic" based on comparing the repo name and the module name - I.e., `MyApp.Repo.Migrations.*` vs `MyAppTest.Repo.Migrations.*`.  Perhaps there should be an explicit way to specify this.

I might be able to extract my set up to a simplified dummy repository for reproduction if that would help.

**Comment by josevalim** [comment]
We use last part of your repository name for figure out the path. The module names do not matter. You can configure it by setting the priv key in your repository configuration. [More info in the `ecto.migrate` command docs](https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Migrate.html).

**Comment by josevalim** [comment]
In any case, thanks for opening up the issue @dantswain! I have also pushed improved docs to master!

**Comment by dantswain** [comment]
Thanks, @josevalim!  Knowing how ecto finds/selects migrations is a big help.

I think there may still be a bug here.  When I create a migration with the `-r` option, it does not put the migration in a repo-specific subdirectory - it just puts it in `/priv/repo/migrations`.

Also, I just tried adding the `:priv` key to the repo config, and it generates the migration in the directory named there and not a subdirectory of `priv` (which is how I read the docs) - i.e.,

```
config :my_app, MyTestRepo,
  priv: "test_repo"
```

puts generated migrations in `test_repo/` not `priv/test_repo`.

**Comment by josevalim** [comment]
> I think there may still be a bug here. When I create a migration with the -r option, it does not put the migration in a repo-specific subdirectory - it just puts it in /priv/repo/migrations.

In your case they share the same directory, that's why it always ends up there.

> Also, I just tried adding the :priv key to the repo config, and it generates the migration in the directory named there and not a subdirectory of priv (which is how I read the docs) - i.e.,

Yeah, I agree the previous docs were lacking examples. This is how they look like now: https://github.com/elixir-ecto/ecto/blob/5c2cde986cd038d698b2cedcf2ca76536e0d86b1/lib/mix/tasks/ecto.migrate.ex#L10

Does it make it clear?

**Comment by dantswain** [comment]
> Migrations are expected at “priv/YOUR_REPO/migrations” directory of the current application but it can be configured to be any subdirectory of priv by specifying the :priv key under the repository configuration.

For sure this could just be me, but I read this to say migrations will be at `priv/YOUR_REPO/migrations` _by default_ - i.e., without declaring an override, `MyApp.Repo1` would look in `priv/repo1` and `MyApp.Repo2` would look in `priv/repo2`.  It's not super prescriptive, so I am definitely making some assumptions.

I also read "can be configured to be any subdirectory of priv by specifying the :priv key" to mean that that value would specify the subdirectory of `priv`.

I'd be glad to try to put together some proposed improvements if you'd like.  I think it's just a matter of being precise and verbose.

**Comment by josevalim** [comment]
@dantswain the new documentation link I pointed to above does not use that phrasing anymore. In any case, PRs to further improve this are definitely welcome!

**Comment by dantswain** [comment]
Oh cool, when you first posted that snippet I don't think github had become "eventually consistent" so I was seeing the old language still.  The new language is much better :+1:.  I may take a look at `gen.migration` as well to see if anything there might have helped me stay on track.  Thanks again!
