### ISSUE TITLE
Preload with function sorts results that were provided in preferred order

### ISSUE THREAD

**Issue by aiwilliams** [elixir-ecto/ecto#2524]
### Environment

* Elixir version (elixir -v): 1.4.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: MacOS 10.13.4

### Current behavior

I'm using `Ecto.Query.preload/2` with a function. The function receives the ids of the target record and performs a query such as (simplified; the real query is complex enough to warrant the preload function approach):

```elixir
from e in "events",
  where: e.id in ^event_ids,
  order_by: [e.id, e.position],
  select: %{id: e.id, position: e.position}
```

The results are in the expected order. However, [`preloader.ex` uses `Enum.sort`](https://github.com/elixir-ecto/ecto/commit/618dacdad5d3dceab836078794b364d820bfa95f#diff-9dab1b1adef58f372bcbdd976c02f663R147) on the results so that the association is assigned a list ordered ascending by the `id` attribute.

### Expected behavior

I would expect that the order of the results provided by the function would be maintained. Documentation for `Ecto.Query.preload/2` does say that the results of the function will be sorted, but I think that is odd compared to how preload queries are allowed to `order_by`.

**Comment by josevalim** [comment]
I could relax this constraint a bit so it works in your case but it still requires id sorting.
