### ISSUE TITLE
Default value in Schema

### ISSUE THREAD

**Issue by denqxotl** [elixir-ecto/ecto#2526]
So I have `my_perfect_random` function that returns value of string
```elixir  
schema "something_greate" do
  field :my_amazing_field, :string, default: my_perfect_random
  timestamps()
end
```
the error is 
```undefined my_perfect_random/0```

The function is written in the same module. I've tried to use `MyModule.my_perfect_random`, but got the same error

Pls help me to fix it

**Comment by michalmuskala** [comment]
Please use the elixir forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you.

---

Defaults in schema can only be static variables similar to structs. You can use changesets to provide dynamic defaults.

**Comment by denqxotl** [comment]
@michalmuskala ok, sorry for it
