### ISSUE TITLE
Ecto TRUNCATE for test env does not work properly

### ISSUE THREAD

**Issue by Virviil** [elixir-ecto/ecto#2543]
### Environment

* Elixir version (elixir -v): **Elixir 1.6.3 (compiled with OTP 19)**
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): **PostgreSQL 10.3 on x86_64-apple-darwin17.3.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.39.2), 64-bit**
* Ecto version (mix deps): Ecto 2.1 ref: **a4cdac62d2c411b98814f68dac04a8b5174e9f22**
* Database adapter and version (mix deps): **:postgrex, "0.13.5", "3d931aba29363e1443da167a4b12f06dcd171103c424de15e5f3fc2ba3e6d9c5"**
* Operating system: **MacOS 10.13.4**

### Current behavior

After adding `VIEW` to databases schema, stoped working database truncation after every test.
Test data doesn't clear itself after each and every test.

In `debug` terms, the problems seems to be defined:

* Before each and every test `Ecto` sends the query:
    `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`
* It excludes _migrations_ table from the list, and tries to truncate all other tables using previous selected data:
    `TRUNCATE #{tables_list} RESTART IDENTITY CASCADE`
* This truncate fails, because `VIEW` was selected in previous step.
* So the data is not deleted from the table.

### Expected behavior

* The _tables_ query should be different a bit:
    `SELECT * FROM information_schema.tables WHERE table_schema = 'public' and table_type = 'BASE TABLE'`
* Thus, only table names will get into _truncate_ script
* And everything will be cleaned.

**Comment by josevalim** [comment]
Hi @Virviil! Ecto does not provide any truncation feature, so this is probably coming from elsewhere. Please find the source and report them accordingly. Thank you.

**Comment by Virviil** [comment]
Yep, directly! It's not `ecto`. I've finally found the problem place. Thank you
