### ISSUE TITLE
Сould not save data to database

### ISSUE THREAD

**Issue by dersar00** [elixir-ecto/ecto#2549]
Hello! 
I'm new in elixir and I have a problem with saving data to db through code, if I try to do it through `iex` like [here](https://hexdocs.pm/ecto/getting-started.html#inserting-data), everything saved well but if I tried to do it through code I got error: 
![image](https://user-images.githubusercontent.com/17855733/40119639-7db61678-591d-11e8-93ad-d6ac5ce600c1.png)
Error after running code on `postgres_branch`.

I have a suggestion that this is due to the fact that the post-grace does not start at startup.

I use a simple elixir app without Phoenix. [Myrepo](https://github.com/dersar00/friends), `master` is with using mongodb, `postgres_branch` - when try to use postgres.

Env info:
`elixir -v 1.6.2`;
DB:
tried do it with postgres and mongodb too;
`ecto -v 2.2.10`
OS:
`mac OS X`

**Comment by josevalim** [comment]
That's because the Friends.save() at the end of the file is trying to execute some code when your application is being compiled, before it is fully compiled and before its services are started. We need to improve the error message here but genereally speaking you should use `iex` to try out code. So you can remove the `Friends.save` from the bottom of the file and do `iex -S mix` and then type `Friends.save` in there.

**Comment by dersar00** [comment]
@josevalim and what you can say now?
![image](https://user-images.githubusercontent.com/17855733/40121653-57f9c6fa-5922-11e8-81bc-44ecc17eec02.png)

**Comment by josevalim** [comment]
Remove this line https://github.com/dersar00/friends/blob/master/mix.exs#L17, as you are using Elixir v1.6, to make sure everything is started. If it doesn't work, then you should rather ask in the mongodb_ecto folks or elixirforum.

**Comment by zoldar** [comment]
FWIW, the code from `postgres_branch` (after removing  `Friends.module()` call at the end of `lib/friends.ex`) works for me:

```
$ mix deps.get
...
$ mix do ecto.create, ecto.migrate
...
$ iex -S mix
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

23:59:35.773 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.174.0> exit with reason normal in context child_terminated
23:59:35.823 [info] Application lager started on node nonode@nohost
23:59:35.828 [info] Application xmerl started on node nonode@nohost
23:59:35.831 [info] Application jsx started on node nonode@nohost
23:59:35.836 [info] Application ranch started on node nonode@nohost
23:59:35.838 [info] Application ranch_proxy_protocol started on node nonode@nohost
23:59:35.840 [info] Application recon started on node nonode@nohost
23:59:35.840 [info] Application rabbit_common started on node nonode@nohost
23:59:35.848 [info] Application amqp_client started on node nonode@nohost
23:59:35.848 [info] Application amqp started on node nonode@nohost
23:59:35.854 [info] Application connection started on node nonode@nohost
23:59:35.864 [info] Application db_connection started on node nonode@nohost
23:59:35.865 [info] Application decimal started on node nonode@nohost
23:59:35.869 [info] Application postgrex started on node nonode@nohost
23:59:35.872 [info] Application poolboy started on node nonode@nohost
23:59:35.874 [info] Application ecto started on node nonode@nohost
23:59:35.902 [info] Application friends started on node nonode@nohost
Interactive Elixir (1.6.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Friends.module
%Friends.Person{
  __meta__: #Ecto.Schema.Metadata<:built, "people">,
  age: 28,
  first_name: nil,
  id: nil,
  last_name: nil
}

23:59:52.444 [debug] QUERY OK db=6.3ms
INSERT INTO "people" ("age") VALUES ($1) RETURNING "id" [28]
{:ok,
 %Friends.Person{
   __meta__: #Ecto.Schema.Metadata<:loaded, "people">,
   age: 28,
   first_name: nil,
   id: 1,
   last_name: nil
 }}
iex(2)>
```
