### ISSUE TITLE
Ecto.Query.API.map broken on single nil column with join when merging select clauses

### ISSUE THREAD

**Issue by JEG2** [elixir-ecto/ecto#2553]
### Environment

* Elixir version (elixir -v):  1.6.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 9.6.1
* Ecto version (mix deps):  2.2.10
* Database adapter and version (mix deps):  0.13.5
* Operating system:  macOS High Sierra 10.13.4

### Current behavior

I'm pretty sure this is another edge case of the now fixed #2380.  I'm dynamically building queries in an application and I run into trouble when merging selects.  All other details match that original bug.

I believe this is the minimum code to reproduce the problem, assuming a `ResponseSet` is saved in the database with a `nil` in `user_id`:

```elixir
      from(
        r in Response,
        inner_join: s in ResponseSet, on: s.id == r.response_set_id,
        select: %{ },
        select_merge: map(s, [:user_id])
      )
      |> Repo.all
```

This is the error Ecto tosses:

```
  1) test bugs ecto's nil results in map merge (DataTest)
     test/data_test.exs:583
     ** (ArgumentError) cannot merge because the right side is not a map, got:  nil
     code: |> Repo.all
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:213: Ecto.Repo.Queryable.process/5
       (ecto) lib/ecto/repo/queryable.ex:189: anonymous fn/4 in Ecto.Repo.Queryable.postprocessor/4
       (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
       (ecto) lib/ecto/repo/queryable.ex:139: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
       test/data_test.exs:593: (test)
```

### Expected behavior

The query should return:  `%{user_id: nil}`.

**Comment by josevalim** [comment]
Ecto doesn't work if you don't retrieve all of the columns involved in the association. I am not sure though if that is the root of the failure or if you removed the remaining columns when building the minimum example. So could you please expand?

Also note that #2380 is only in master and it has not been released yet. Did you give master a try?

**Comment by JEG2** [comment]
> Ecto doesn't work if you don't retrieve all of the columns involved in the association

I don't think I fully understood this comment.  It definitely sounds like something I did wrong though.  Feel to close this issue.

> Also note that #2380 is only in master and it has not been released yet. Did you give master a try?

Ah, good tip.  I didn't catch that.  

Switching to master takes me from one failing test to 10.  :(

**Comment by JEG2** [comment]
> We do have some breaking changes since it is Ecto 3.0. Are they related to microsecond precision maybe? 

Five of my failures are this.  They are easily fixed.  No worries there.

> Here is the CHANGELOG: https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md

The other five failures are related to `select_merge`.  I don't see a relevant entry in the CHANGELOG.  Here's a sample failure:

```
  4) test core commands plucks individual fields out of matching records (DataTest)
     test/data_test.exs:141
     ** (Ecto.QueryError) cannot select_merge source at position 0 into %{}, those select expressions are incompatible in query:
     
     from r0 in Reporter.Response,
       join: r1 in Reporter.ResponseSet,
       on: r1.id == r0.response_set_id,
       select: %{}
     
     code: |> Data.pluck
     stacktrace:
       (ecto) lib/ecto/query/builder/select.ex:260: Ecto.Query.Builder.Select.merge/6
       (reporter) lib/reporter/data.ex:337: Reporter.Data.add_select_clause/3
       (reporter) lib/reporter/data.ex:92: Reporter.Data.pluck/1
       test/data_test.exs:154: (test)
```

**Comment by JEG2** [comment]
I made an example with a README to walk you through seeing it in action:

https://github.com/JEG2/ecto_change

Let me know if you have any questions.

**Comment by josevalim** [comment]
@JEG2 thank you so much, I have fixed it in master.

I forgot to ask: did master also address your original issue... or not really?

**Comment by JEG2** [comment]
> I forgot to ask: did master also address your original issue... or not really?

This specific issue does seem fixed with current `master`, yes.  It looks like I have one more minor problem, but I believe it's different.  I'll try to reduce it to a minimal example and submit a new issue for it.
