### ISSUE TITLE
Optimise memory use of metadata structs

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2557]
The metadata structs are never shared, because they are always mutated when data is loaded from database. This means that when loading a lot of data, lots of memory will be used by the metadata structs.

A way to remedy this would be precompute some data so it goes into the literal pool and make sure we actually don't update the struct if the update wouldn't change anything.

Places to look at:
* https://github.com/elixir-ecto/ecto/blob/ad8d474d09a4b12bca2145a75491f6210ce8d099/lib/ecto/repo/queryable.ex#L268 - precompute the metadata struct with `loaded` info and don't update the prefix if it's already the same as the default one
* https://github.com/elixir-ecto/ecto/blob/ad8d474d09a4b12bca2145a75491f6210ce8d099/lib/ecto/schema.ex#L1656 - similar
* https://github.com/elixir-ecto/ecto/blob/ad8d474d09a4b12bca2145a75491f6210ce8d099/lib/ecto/schema.ex#L1679 - similar
* https://github.com/elixir-ecto/ecto/blob/68715062d75ef2b374a063f50a073b5154bc4bd3/lib/ecto.ex#L565 - return the same struct as original if the update would be a noop
* https://github.com/elixir-ecto/ecto/blob/5fba18310fc51de8f4a7cc2f5fcaa5083175058b/lib/ecto/association.ex#L298 - manipulate the data directly, skipping updates for default values
* https://github.com/elixir-ecto/ecto/blob/5fba18310fc51de8f4a7cc2f5fcaa5083175058b/lib/ecto/association.ex#L309 - similar

**Comment by mguimas** [comment]
It seems that this solution

```

**Comment by mguimas** [comment]
There seems some metadata stuff that could still be optimized.

For example, give the schema
```
%User{
  __meta__: #Ecto.Schema.Metadata<:built, "users">,
  account: #Ecto.Association.NotLoaded<association :account is not loaded>,
  ...
}
```
we still get in Ecto 3.0.1 the following
```
u1 = %User{}
u2 = %User{}
:erts_debug.size(u1)
:erts_debug.size(u2)
:erts_debug.size({u1, u2})
:erts_debug.size(u1.account)
:erts_debug.size(u2.account)
:erts_debug.size({u1.account, u2.account})
```
That is, the `u1.account` and `u2.account` are not shared.

**Comment by josevalim** [comment]
I believe you need to use `:erts_debug.same` to check. This test passes for me in Ecto 3.0 for a comment belongs_to association:

```elixir
    schema1 = %Schema{}
    schema2 = %Schema{}
    assert :erts_debug.same(schema1, schema2)
    assert :erts_debug.same(schema1.comment, schema2.comment
```

**Comment by michalmuskala** [comment]
How are you running the tests? In general, don't test things like performance or memory use inside IEx - it's not running the actual code that would be compiled, but runs an interpreter instead. Things like this are where there are some differences between the two.

**Comment by mguimas** [comment]
@josevalim @michalmuskala 

You are right. If I wrap the test inside a module and past it in IEx, I get this

```
iex(125)> defmodule MemSize do
...(125)> def show do
...(125)> u1 = %User{}
...(125)> u2 = %User{}
...(125)> IO.puts :erts_debug.size(u1)
...(125)> IO.puts :erts_debug.size(u2)
...(125)> IO.puts :erts_debug.size({u1, u2})
...(125)> IO.puts :erts_debug.size(u1.account)
...(125)> IO.puts :erts_debug.size(u2.account)
...(125)> IO.puts :erts_debug.size({u1.account, u2.account})
...(125)> IO.puts :erts_debug.same(u1.account, u2.account)
...(125)> end
...(125)> end
{:module, MemSize,
 <<70, 79, 82, 49, 0, 0, 9, 208, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 183,
   0, 0, 0, 21, 14, 69, 108, 105, 120, 105, 114, 46, 77, 101, 109, 83, 105, 122,
   101, 8, 95, 95, 105, 110, 102, 111, 95, ...>>, {:show, 0}}

iex(126)> MemSize.show
87
87
177
12
12
15 <-- no mem increase beyond 3 bytes for the tuple
true <-- they are definitely the same
:ok
iex(127)>
```

This is good to know: that every performance and memory test should be wrapped in a module so that IEx can compile it, and proper benchmark results are read.

Thanks
