### ISSUE TITLE
Ecto.LogEntry ignores the color configuration from Elixir's Logger

### ISSUE THREAD

**Issue by ek1506** [elixir-ecto/ecto#2566]
### Environment
Elixir version: 1.6.4
Database and version: PostgreSQL 10.3
Ecto version: 2.2.10
OS: Windows 7 (Emacs using M-x shell)

### Current behavior
I configured Elixir's logger to use red color for debug messages, but Ecto.LogEntry ignores this and uses the default cyan color.

Example:
![Example:](https://i.imgur.com/z9Vdd0N.png)

Config.exs:
![My config.exs](https://i.imgur.com/bhDIceD.png)

### Expected behavior
I would expect the Ecto log entries to use the red color from Elixir's logger configuration. The Ecto.LogEntry struct has an ansi_color field but this doesn't look like something you can configure from the Ecto.Repo :logger configuration.

**Comment by josevalim** [comment]
Yes, Ecto.LogEntry has its own color schema on top. You can remove it by providing your own log callback in the repository configuration.
