### ISSUE TITLE
Switch to using = ANY(SELECT unnest(?)) instead of = ANY(?) for IN operator

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2570]
The problem of `in (?, ?, ...)` is that it requires different SQL for different number of elements and in effect prevents caching queries. Because of that we switched to `= ANY(?)`, but that prevents using indices for the comparison.

@talentdeficit suggested using `= ANY(SELECT unnest(?))` instead, which supports using indices. The downside is that this relies on support of `unnest` function. To my knowledge the databases that don't support it (redshift) also don't support use of `= ANY(?)`, so it shouldn't be removing any feature.

**Comment by josevalim** [comment]
Can we please do actual tests on this? Let's run some explain commands, benchmark on large data and what not. Otherwise, I don't think we should move forward.

**Comment by josevalim** [comment]
I will close this for now, unless somebody is interested in running some tests and sharing their results. :)
