### ISSUE TITLE
Ditch compile-time config

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#2571]
Today the only two compile-time values are adapter and loggers. 

We need the adapter because it might do some code generation. This can be solved, by recommending that the adapter is passed directly to `use Ecto.Repo` call instead of passing it through config. This is already possible today, but should be promoted as a default.

The other compile-time value is `loggers` - we read it at compile-time to minimise the cost of logging. Doing it at runtime, though should be only marginally less efficient. This might require some measurements. It is also possible to pass this option directly to `use` today.

Right now, even if all required compile-time options are passed to `use` directly, ecto still requires an empty config (e.g. `config :my_app, MyApp.Repo, []`). This shouldn't be necessary.

**Comment by michalmuskala** [comment]
We could always make `log` an overridable callback in repo. This would mean changing the mechanism completely, though.

**Comment by josevalim** [comment]
@michalmuskala i am working on making the dynamic repo which basically means all the data should come from ets. I guess we can just store the list of loggers in ets?

**Comment by michalmuskala** [comment]
I think it would be fine to have logging statically defined in the module in the dynamic repo. But reading from ets should be fine too. 
I wonder if we could combine the reads - we'd probably be reading multiple things from ets on each repo call.

**Comment by josevalim** [comment]
Loggers are now runtime based in master.

**Comment by josevalim** [comment]
It is still the same API, except we traverse them at runtime.
