### ISSUE TITLE
Preload query result doesn't match raw SQL result

### ISSUE THREAD

**Issue by leveloid** [elixir-ecto/ecto#2573]
### Environment

* Elixir version (elixir -v): 1.6.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.3
* Ecto version (mix deps): 2.2

### Current behavior

I'm seeing something off, but not sure it's a bug:

This preload query:
```
Repo.all(
from(m in Message, 
join: c in assoc(m, :chats), 
where: m.id == ^id, 
preload: [chats: c] ))
```
generates this sql:
```
SELECT m0."id", m0."inserted_at", m0."updated_at", c1."id", c1."message_id", c1."inserted_at", c1."updated_at" 
FROM "messages" AS m0 
INNER JOIN "chats" AS c1 ON c1."message_id" = m0."id" 
WHERE (m0."id" = $1) [<<155, 216, 86, 49, 172, 123, 69, 18, 143, 151, 197, 31, 234, 234, 237, 43>>]
```
and returns a single record with a "chats" field containing an array of associated chats.

Running that same SQL query manually, however:
```
Ecto.Adapters.SQL.query(Repo, [above query here])
or via a Postgres GUI
```
returns a result with N rows, one for each associated chat. 

The only explanation I have is that Ecto is performing some transformation on the result via preload, but I'm not seeing anything like this documented anywhere.

Thanks for your time!

**Comment by josevalim** [comment]
Yes, that's exactly what preload does, we get all comments and put them inside the posts, so you return `number_of_posts` instead of `number_of_posts * number_of_comments`. If you remove the preload you will get the same result as the query. I have improved the docs, thank you!
