### ISSUE TITLE
Remove compile-time dependency on many_to_many association

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#2579]
### Environment

* Ecto version (mix deps): master

### Current behavior

```
$ cd ecto/examples/ecto_assoc
$ mix xref graph --format=dot && dot -Tpng xref_graph.dot -o xref_graph.png
```

![xref_graph](https://user-images.githubusercontent.com/76071/41005977-e8a06846-691f-11e8-80d2-982c3fd3de2a.png)

### Expected behavior

No compile-time dependency.

---

I haven't looked closely at the code yet, but as seen above other associations don't have this problem. Happy to explore this if it seems feasible.

**Comment by josevalim** [comment]
Please do take a look. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
