### ISSUE TITLE
Customize NotFound

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-ecto/ecto#2586]
### Current behavior

Ecto handles 404 for me and even if I try to get the data it assigns only message, but there is not way to understand which model is missing and make a custom message basing on this.

So in my `ErrorView` or catching mechanism I could get only
```
%{kind: :error, layout: false, reason: %Ecto.NoResultsError{message: "expected at least one result but got none in query: ... "}}
```

### Expected behavior
Ecto.NoResultsMessage and others contain module name/schema.
```
%{kind: :error, layout: false, reason: %Ecto.NoResultsError{schema: MyApp.User, message: "expected at least one result but got none in query: ... "}}
```

**Comment by josevalim** [comment]
Hi! If you feel like you need to customize for certain schemas, then the best is to use `one()` and pattern match on the result. We don't have a schema per se, since we are working with queries, and it may have multiple schemas or be query dependent.

**Comment by mojidabckuu** [comment]
@josevalim Does it make sense to put `queryable` into `Ecto.NoResultsError` to be able distinguish which Schema was queried? I think it makes sense to check what was the schema and handle pattern `query.from` instead of multiple places with `case do` statement
