### ISSUE TITLE
Mix ecto.migrate times out with too many migrations

### ISSUE THREAD

**Issue by MHadley09** [elixir-ecto/ecto#2590]
### Environment

* Elixir version (elixir -v): 1.6.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  Postgres 9.6.8
* Ecto version (mix deps): 3.0.0
* Database adapter and version (mix deps): db_connection 1.2.2; postgrex 0.14.0-dev
* Operating system:  Ubuntu

### Current behavior

Running: 
 `MIX_ENV=test mix ecto.create`

Results in: 
`The database for Galaxy.Repo has been created`

Next we run:

`MIX_ENV=test mix ecto.migrate`

This generates a timeout error of:

`09:09:12.208 [error] Postgrex.Protocol (#PID<0.219.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.74.0> timed out because it owned the connection for longer than 15000ms
09:09:12.249 [error] Could not update schema migrations. This error usually happens due to the following:

 * The database does not exist
 * The "schema_migrations" table, which Ecto uses for managing
   migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

   config :galaxy, Galaxy.Repo,
     migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (DBConnection.ConnectionError) tcp send: closed
   (elixir) lib/keyword.ex:504: Keyword.delete_key/3
   (elixir) lib/keyword.ex:501: Keyword.delete_key/3
   (elixir) lib/keyword.ex:501: Keyword.delete_key/3
   (elixir) lib/keyword.ex:493: Keyword.put/3
   lib/galaxy/repo.ex:9: Galaxy.Repo.init/2
   (ecto) lib/ecto/repo/supervisor.ex:24: Ecto.Repo.Supervisor.runtime_config/4
   lib/galaxy/repo.ex:2: Galaxy.Repo.config/0
   (ecto) lib/ecto/migrator.ex:441: Ecto.Migrator.verbose_schema_migration/3
09:09:12.309 [error] GenServer Galaxy.Repo terminating
** (DBConnection.ConnectionError) tcp send: closed
   (elixir) lib/keyword.ex:504: Keyword.delete_key/3
   (elixir) lib/keyword.ex:501: Keyword.delete_key/3
   (elixir) lib/keyword.ex:501: Keyword.delete_key/3
   (elixir) lib/keyword.ex:493: Keyword.put/3
   lib/galaxy/repo.ex:9: Galaxy.Repo.init/2
   (ecto) lib/ecto/repo/supervisor.ex:24: Ecto.Repo.Supervisor.runtime_config/4
   lib/galaxy/repo.ex:2: Galaxy.Repo.config/0
   (ecto) lib/ecto/migrator.ex:441: Ecto.Migrator.verbose_schema_migration/3
Last message: {:EXIT, #PID<0.74.0>, {%DBConnection.ConnectionError{message: "tcp send: closed"}, [{Keyword, :delete_key, 3, [file: 'lib/keyword.ex', line: 504]}, {Keyword, :delete_key, 3, [file: 'lib/keyword.ex', line: 501]}, {Keyword, :delete_key, 3, [file: 'lib/keyword.ex', line: 501]}, {Keyword, :put, 3, [file: 'lib/keyword.ex', line: 493]}, {Galaxy.Repo, :init, 2, [file: 'lib/galaxy/repo.ex', line: 9]}, {Ecto.Repo.Supervisor, :runtime_config, 4, [file: 'lib/ecto/repo/supervisor.ex', line: 24]}, {Galaxy.Repo, :config, 0, [file: 'lib/galaxy/repo.ex', line: 2]}, {Ecto.Migrator, :verbose_schema_migration, 3, [file: 'lib/ecto/migrator.ex', line: 441]}]}}`

However,  if we run:

`MIX_ENV=test mix ecto.migrate --step 40` 17 times everything processes correctly with no issues.

### Expected behavior

After running `MIX_ENV=test mix ecto.create`, we expect `MIX_ENV=test mix ecto.migrate` to successfully run all 648 migrations at once.

**Comment by josevalim** [comment]
Good call!

**Comment by josevalim** [comment]
Hi @MHadley09! The proper fix for here is simply to increase the ownership timeout in your config/test.exs file:

```elixir
config :galaxy, Galaxy.Repo,
  ownership_timeout: :infinity
```

The timeout exists mostly for sanity checking purposes, to ensure there are no leaked connections, but it may have false positives in case of long running actions like yours. It can be bumped whenever necessary! :+1:
