### ISSUE TITLE
`count(<field>)` can sometimes be much slower than `count(*)`

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#2595]
### Environment

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL (possibly other SQL DBs, unsure about NoSQLs)
* Ecto version (mix deps): 2.0+

### Current behavior

Currently there is no way (other than using fragment) to run query like `count(*)`. This can be problematic as `count(<field>)` on `<field>` that isn't indexed can be terribly slow (found by @mkaszubowski). The reason why this is happening is that by SQL standard `COUNT(<field>)` should return count of non-null values in DB so that mean it need to check wether any value in given field is empty or not, while `COUNT(*)` do not have this limitation and always return count of all matched rows.

Currently there is available workaround in form of `count(true)` in Ecto, but this isn't obvious solution and for sure isn't idiomatic.

### Expected behavior

There should be `count/0` function that would expand to counting all entries matching the query which I believe that most DBs have optimised enough.

**Comment by josevalim** [comment]
Sounds good to me! PR please?

**Comment by mkaszubowski** [comment]
Just to clarify: the problem exists even if the fields used in `count` is indexed properly. The difference between two approaches is that when using `count(<field>)`, PostgreSQL uses an `index scan` and still has to fetch the rows. With `count(*)` it can use `index only scan` without fetching the rows, which is way faster.

**Comment by soteras** [comment]
I have a closed pr about *count* function #2575 if you want i can modify for that situation.

**Comment by josevalim** [comment]
@soteras a PR is definitely welcome. Although note that we are not adding new callbacks to the repo module. The new count function will belong to the `Ecto.Query.API` instead. Please let me know if you have any questions!

**Comment by hauleth** [comment]
@josevalim any sources where I could learn how are aggregate functions in `Ecto.Query.API` handled? Because it seems a little convoluted (as most macro systems).

**Comment by josevalim** [comment]
There is a step in the middle, which is the Ecto.Query.Planner. My suggestion is to search the codebase for a less commonly used aggregator, such as `avg`, and see where in the codebase we touch it.

**Comment by soteras** [comment]
@hauleth are you doing that or wants to?

**Comment by hauleth** [comment]
I want to, but if you are willing then you can try as I do not have time right now to dig into it properly.

**Comment by hauleth** [comment]
It seem it was merged. @soteras thanks for your work.
