### ISSUE TITLE
Allow column renames in MySQL adapter

### ISSUE THREAD

**Issue by thecodeboss** [elixir-ecto/ecto#2601]
Ecto migrations support renaming columns with [`rename/3`](https://hexdocs.pm/ecto/Ecto.Migration.html#rename/3):
```elixir
rename table(:table_name), :old_column_name, to: :new_column_name
```
However for MySQL this raises:
```
** (ArgumentError) MySQL adapter does not support renaming columns
```
I see this functionality was removed in 1ce086c3ee44ed82d24878bad0370f054434539f, but with no explanation added as to why.
So I'd like to request the functionality get added back, or if it's not possible for whatever reason, at least this PR will have the discussion about why.

**Comment by josevalim** [comment]
When we started using prepared statements, it become impossible to run migration commands with large expressions inside. We will be glad to bring `rename/3`column back but it needs to be properly supported by MySQL. IIRC the only API supported by MySQL requires passing the data types again, which doesn't match the `rename/3` API. In the worst scenario you can do it yourself with `execute/2` statements.

**Comment by wojtekmach** [comment]
@josevalim I noticed that MySQL introduced `ALTER TABLE ... RENAME COLUMN` syntax in 8.0.3 [1] which is exactly what we need, but we obviously don't have that on 5.x.

Perhaps we could try performing this query and if it fails try to provide a good error message? I'd like to work on it; should I open an issue on ecto_sql?

https://bugs.mysql.com/bug.php?id=58006

**Comment by josevalim** [comment]
@wojtekmach our approach is to usually emit the command and let it fail if people are using older versions. :) But yes, that would be nice to support!
