### ISSUE TITLE
binary id odd bug

### ISSUE THREAD

**Issue by revati** [elixir-ecto/ecto#2602]
### Environment

**Elixir version (elixir -v):**
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)

**Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):**
MySQL 5.7.22 and 8.0.11

**Ecto version (mix deps):**
  ecto 2.2.10 (Hex package) (mix)
  locked at 2.2.10 (ecto) e7366dc8

**Database adapter and version (mix deps):**
  mariaex 0.8.4 (Hex package) (mix)
  locked at 0.8.4 (mariaex) 5dd42a60

**Operating system:** Mac OS 10.13.5 (17F77)

### Current behavior

There are 2 problems:
* Ids mismatch when inserting a new row
* I can fetch single row by id using two different ids.

```elixir
entity = %MyModule{} |> Repo.insert!
entity.id # 38b128b1-ca17-4570-a027-01c81a595db4
new = Repo.get! MyModule, entity.id
new.id # 383f283f-3f17-4570-3f27-013f1a595d3f
entity.id == new.id # false

# I can even do 

id = Ecto.UUID.generate # 2065b985-6b29-4511-b826-91c5a365f254
entity = %MyModule{id: id} |> Repo.insert!
entity.id # 2065b985-6b29-4511-b826-91c5a365f254
new = Repo.get! MyModule, id
new.id # 383f283f-3f17-4570-3f27-013f1a595d3f
entity.id == new.id # false
entity.id == id # true
new.id == id # false

new2 = Repo.get! MyModule, new.id
new2.id == new.id # true
```

Somehow when I insert a new row, id in mysql table is switched to different one.
Somehow I still am able to query that row by both ids: initial one and switched one.

in all examples `entity`, `new` and `new2` is the same row in DB, as only one row in DB exists.

### Expected behavior

```elixir
entity = %MyModule{} |> Repo.insert!
new = Repo.get! MyModule, entity.id
entity.id == new.id # true
```

I expect when I insert new row either with or without id after `entity = %MyModule{} |> Repo.insert!` `entity` will hold actuall id, that is in db.
if this uuid is passed to me from other system (api consumer) i must save row with that id.

Other thing i expect is that only one uuid can be used to fetch row from db by id.

**Comment by revati** [comment]
https://elixirforum.com/t/odd-binary-id-mismatch/14719/8

**Comment by josevalim** [comment]
What happens if you do `Repo.all`, which id is returned? I would suspect that the `id` you are setting explicitly with `id: id` is being completely ignored and another is being generated by the database. You can also see the insert queries being sent to the database and if they look correct.

**Comment by josevalim** [comment]
To be more precise, please let us know the result of `Repo.all` and how the insert queries logged in your terminal look like in the example above. :)

**Comment by revati** [comment]
```elixir
$ iex -S mix phx.server
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

[info] Running StatsWeb.Endpoint with Cowboy using http://0.0.0.0:4000
Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> alias Stats.Repo
Stats.Repo
iex(2)> id = Ecto.UUID.generate
"f6c8ea7a-1d90-4648-b01e-387836008754"
iex(3)> entity = %MyModule{id: id} |> Repo.insert!
[debug] QUERY OK db=4.6ms
INSERT INTO `my_modules` (`id`) VALUES (?) [<<246, 200, 234, 122, 29, 144, 70, 72, 176, 30, 56, 120, 54, 0, 135, 84>>]
%MyModule{
  __meta__: #Ecto.Schema.Metadata<:loaded, "my_modules">,
  id: "f6c8ea7a-1d90-4648-b01e-387836008754"
}
iex(4)> Repo.all MyModule
[debug] QUERY OK source="my_modules" db=2.2ms decode=1.7ms
SELECT m0.`id` FROM `my_modules` AS m0 []
[
  %MyModule{
    __meta__: #Ecto.Schema.Metadata<:loaded, "my_modules">,
    id: "3f3f3f7a-1d3f-4648-3f1e-387836003f54"
  }
]
iex(5)> new = Repo.get! MyModule, id
[debug] QUERY OK source="my_modules" db=1.0ms
SELECT m0.`id` FROM `my_modules` AS m0 WHERE (m0.`id` = ?) [<<246, 200, 234, 122, 29, 144, 70, 72, 176, 30, 56, 120, 54, 0, 135, 84>>]
%MyModule{
  __meta__: #Ecto.Schema.Metadata<:loaded, "my_modules">,
  id: "3f3f3f7a-1d3f-4648-3f1e-387836003f54"
}
iex(6)> new.id == entity.id
false
iex(7)> new2 = Repo.get! MyModule, new.id
[debug] QUERY OK source="my_modules" db=1.2ms
SELECT m0.`id` FROM `my_modules` AS m0 WHERE (m0.`id` = ?) [<<63, 63, 63, 122, 29, 63, 70, 72, 63, 30, 56, 120, 54, 0, 63, 84>>]
%MyModule{
  __meta__: #Ecto.Schema.Metadata<:loaded, "my_modules">,
  id: "3f3f3f7a-1d3f-4648-3f1e-387836003f54"
}
```

```
f6c8ea7a-1d90-4648-b01e-387836008754 = 
<<246, 200, 234, 122, 29, 144, 70, 72, 176, 30, 56, 120, 54, 0, 135, 84>>

# and

3f3f3f7a-1d3f-4648-3f1e-387836003f54 = 
<<63, 63, 63, 122, 29, 63, 70, 72, 63, 30, 56, 120, 54, 0, 63, 84>>
```

```elixir
# both queries

SELECT m0.`id` FROM `my_modules` AS m0 WHERE (m0.`id` = ?) [<<246, 200, 234, 122, 29, 144, 70, 72, 176, 30, 56, 120, 54, 0, 135, 84>>]

# and 
SELECT m0.`id` FROM `my_modules` AS m0 WHERE (m0.`id` = ?) [<<63, 63, 63, 122, 29, 63, 70, 72, 63, 30, 56, 120, 54, 0, 63, 84>>]

# returns the same row

%MyModule{
  __meta__: #Ecto.Schema.Metadata<:loaded, "my_modules">,
  id: "3f3f3f7a-1d3f-4648-3f1e-387836003f54"
}
```

**Comment by josevalim** [comment]
Thanks! Can we see how the `MyModule` table is defined in your database? Maybe your migration files?

**Comment by revati** [comment]
I created separate mix project with ecto and minimal migrations and model to replicate this issue: https://github.com/revati/ecto_mysql_bug

**Comment by josevalim** [comment]
Thanks for the app! The test passes here using MySQL 5.7.20. I am trying to see if changing the collation affects anything. Otherwise I will update MySQL version.

**Comment by josevalim** [comment]
@revati I have upgraded to MySQL 8.0.11 and it also worked. Can you try Elixir v1.6.6 just in case?

**Comment by revati** [comment]
I updated elixir to v1.6.6 still have that problem. What collation do you use? I could try with yours.

**Comment by josevalim** [comment]
@revati I even tried the same collation as yours and it worked just fine. Which is expected since binaries should not be affected by the collation.

**Comment by josevalim** [comment]
It would be great if somebody else could reproduce this so we try to find more information on why this is going wrong. AFAIK we are using the same OS. How did you install mysql? Homebrew?

**Comment by revati** [comment]
😭 
I will try to install MySQL locally, I till now used remote MySQL on ubuntu server

**Comment by revati** [comment]
So I installed MySQL locally and now all tests pass.
I put elixir on ubuntu server, and there is that problem

Sorry, @josevalim, I had to check this beforehand.

## Actual environment Environment

**Elixir version (elixir -v):**
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 20)

**Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):**
MySQL 5.7.22 and 8.0.11

**Ecto version (mix deps):**
ecto 2.2.10 (Hex package) (mix)
locked at 2.2.10 (ecto) e7366dc8

**Database adapter and version (mix deps):**
mariaex 0.8.4 (Hex package) (mix)
locked at 0.8.4 (mariaex) 5dd42a60

**Operating system:**
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-101-generic x86_64)
Codename: xenial

**Comment by josevalim** [comment]
@revati given this information, it feels like a MySQL or a MySQL+Ubuntu problem, but I have no idea where to look. Maybe there is a configuration or extension installed on MySQL side that may be messing it up?

**Comment by josevalim** [comment]
@revati can you try connecting to MySQL and writing to the table in another programming environment? Does it have the same issues?

**Comment by josevalim** [comment]
@revati please let us know if you have more news on how we can reproduce this, thank you!

**Comment by hylkealons** [comment]
@josevalim @revati I am asking to reopen this issue as I run into similar behaviour, including the inconsistencies between the environments.

I have several environments and it was a headache to set them up:
- Development (Mac) -> Between different environment inconsistent behaviour
     - For tests, we have added mix ecto.drop to the aliases in `mix.env`
- Staging -> Working (Docker elixir:1.6.6-slim)
- Sandbox -> Working after several mix ecto.drop, create and migrates, included an entire drop of the database
- Production -> Working after singular database drop, recreating it, mix ecto.drop, create and migrate

Similar behaviour: 
upon storing the record, my record has a different uuid than the one stored in the database. To make it even weirder, sometimes it is equal, for an entire table.

My schema

```
    field(:uuid, Ecto.UUID, autogenerate: true)
```

Migration

```
    add(:uuid, :uuid)

    create(unique_index(:table, [:uuid]))
```

Also opened conversation in slack https://elixir-lang.slack.com/archives/C087B66BY/p1532069727000040

Ecto:
```
  "ecto": {:hex, :ecto, "2.2.10", "e7366dc82f48f8dd78fcbf3ab50985ceeb11cb3dc93435147c6e13f2cda0992e", [:mix], [{:db_connection, "~> 1.1", [hex: :db_connection, repo: "hexpm", optional: true]}, {:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.8.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, repo: "hexpm", optional: true]}], "hexpm"},
```

phoenix_ecto
```
  "phoenix_ecto": {:hex, :phoenix_ecto, "3.3.0", "702f6e164512853d29f9d20763493f2b3bcfcb44f118af2bc37bb95d0801b480", [:mix], [{:ecto, "~> 2.1", [hex: :ecto, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.9", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
```

Elixir: 1.6.6

It would be great if you can help us out here. Let me know if more information is needed.

**Comment by josevalim** [comment]
@hylkealons can you please provide a small application that reproduces the error? Also take a look at #2615, as it may be the same issue?

**Comment by hylkealons** [comment]
actually it might be related to issue #2615, as we are also having an `id` (autoincrement, pk) and a `uuid` (non-pk), but without a prefix.

The small application will have to wait a while, as I'll be on holidays in a few hours. I wonder if it would add any value anyway, as the inconsistency is the pain here.

**Comment by josephan** [comment]
This issue occurred for me as well when the character set was set to `utf8mb4`.
From running `ALTER DATABASE db_name CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`
Once I ran `mix ecto.reset` and the character set was back to `utf8` it was correct.
I would like to keep using `utf8mb4` for emojis. (https://stackoverflow.com/a/30074553/4678727)

**Comment by josephan** [comment]
Fixed by adding
```
  charset: "utf8mb4",
  collate: "utf8mb4_unicode_ci"
```
to the `Repo`'s configs in `config.exs`
