### ISSUE TITLE
select_merge throws an exception when '...' is used in the bindings list

### ISSUE THREAD

**Issue by ideanl** [elixir-ecto/ecto#2605]
* Elixir version (elixir -v): 1.6.5
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.4
* Ecto version (mix deps): 2.2-3.0.0-dev
* Database adapter and version (mix deps): 0.13.5-Postgrex from ecto master mix.lock
* Operating system: macOS High Sierra

### Current behavior

select_merge throws an exception when '...' is used in the bindings list.

```
  query =
        "posts"
        |> select_merge([..., p], %{title: p.title})

  ** (CompileError) test/ecto/query/builder/select_test.exs:121: undefined function escape_count/0
      (stdlib) lists.erl:1338: :lists.foreach/2
      (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
      (elixir) lib/code.ex:677: Code.require_file/2
      (elixir) lib/kernel/parallel_compiler.ex:201: anonymous fn/4 in   Kernel.ParallelCompiler.spawn_workers/6
```

### Expected behavior

Should not throw exception

**Comment by tslim** [comment]
Sorry for this rather dumb question. How do I get this fix in Ecto 2.2? Is there any reason it wasn't included? @josevalim

**Comment by josevalim** [comment]
Good question, it is a small fix, so we can definitely backport. I have done this and pushed to the v2.2 branch. But generally we only backport when asked, as we tend to focus mainly on the upcoming release (and v3.0-rc is out).

**Comment by tslim** [comment]
Thank you @josevalim Sorry for the trouble.

**Comment by josevalim** [comment]
No trouble at all :)
