### ISSUE TITLE
Delegating virtual fields to function calls

### ISSUE THREAD

**Issue by skylerparr** [elixir-ecto/ecto#2608]
Is there a way to specify a function delegate that gets called when accessing a virtual field? Something like this for example:

```
defmodule MyApp.Schema.User do
  use Ecto.Schema

  schema "users" do
    field :first_name, :string
    field :last_name, :string
    field :full_name, :string, virtual: true, to: &get_full_name/1
  end
  
  def get_full_name(user) do
    "#{user.first_name} #{user.last_name}"
  end
end

iex> user = Repo.get(MyAppSchema.User, 1)
iex> user.full_name
"foo bar"
```

This would help immensely without having to do manual setting of the virtual fields.

**Comment by josevalim** [comment]
It is not possible, struct access is part of Elixir semantics, there is nothing Ecto can do. My recommendation is to not even rely on virtual fields but call functions that compute this data for you. I recommend moving this discussion to Elixir Forum to get opinions from others, as this is not an Ecto issue per se. Thanks!
