### ISSUE TITLE
Deffered triggers of PostgreSQL not work on sandbox mode

### ISSUE THREAD

**Issue by nallwhy** [elixir-ecto/ecto#2621]
### Environment

* Elixir version (elixir -v): 1.6.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PotgresSQL 9.6
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): 0.13.5
* Operating system: macOS

### Current behavior

https://github.com/nallwhy/ecto_deffered_trigger

On the test project above, Both works well without sandbox mode.
But on test, deffered triggers not work.

```elixir
iex -S mix

iex> {:ok, item} = DefferedTrigger.Item.create(%{})
{:ok,
 %DefferedTrigger.Item{
   __meta__: #Ecto.Schema.Metadata<:loaded, "items">,
   field_deffered_trigger: nil,
   field_trigger: nil,
   id: 1
 }}

# need to reload because those are `AFTER` triggers.

iex> DefferedTrigger.Item |> DefferedTrigger.Repo.get(1)
%DefferedTrigger.Item{
  __meta__: #Ecto.Schema.Metadata<:loaded, "items">,
  field_deffered_trigger: "hello",
  field_trigger: "hi",
  id: 1
}
```

```elixir
mix test

  1) test  (DefferedTrigger.ItemTest)
     test/deffered_trigger/item_test.exs:6
     Assertion with == failed
     code:  assert item.field_deffered_trigger() == "hello"
     left:  nil
     right: "hello"
     stacktrace:
       test/deffered_trigger/item_test.exs:11: (test)
```

### Expected behavior

Deffered triggers works well with sandbox mode because it's one transaction.

**Comment by nallwhy** [comment]
@josevalim I got it. Thanks!

**Comment by nallwhy** [comment]
@josevalim I've solved this problem by query "SET CONSTRAINTS ALL IMMEDIATE;" to trigger deffered triggers.

**Comment by egeersoz** [comment]
> Yes, they won't work because the sandbox is one big transaction. We will make sure to add notes to the documentation about this.

Sorry to revive this 6.5 years later, but I couldn't find anything in the Ecto docs about this. I did find [this bit](https://github.com/elixir-ecto/ecto/pull/2396/files), but that is talking about changesets and doesn't sound directly relevant to this issue, which is about sandbox mode specifically.

To provide some context, I have the constraint below, which ensures that two form sections cannot have the same `position` value inside a given form:
```
ALTER TABLE #{prefix()}.form_sections
    ADD CONSTRAINT unique_form_section_position
        UNIQUE(form_id, position)
        DEFERRABLE INITIALLY IMMEDIATE;
```
Ecto transaction:
```
def create_form(tenant, attrs) do
  prefix = TenantActions.build_prefix(tenant)

  Ecto.Multi.new()
  |> Ecto.Multi.insert(:form, Form.changeset(%Form{}, attrs), prefix: prefix)
  |> Ecto.Multi.run(:defer, fn(_repo, _result) ->
    Repo.query("SET CONSTRAINTS #{prefix}.unique_form_section_position DEFERRED", [], prefix: prefix)
  end)
  |> Ecto.Multi.run(:form_sections, fn(_repo, %{form: form}) ->
    Enum.each(attrs["form_sections"], fn section_attrs ->
      attrs = Map.merge(section_attrs, %{"form_id" => form.id})

      {:ok, section} =
        %FormSection{}
        |> FormSection.changeset(attrs)
        |> Repo.insert(prefix: prefix)
    end)

    {:ok, ""}
  end)
  |> Repo.transaction()
end
```
The attrs:
```
%{
  "title" => "Test form",
  "form_sections" => [
    %{
      "title" => "section 1",
      "position" => 0,
    },
    %{
      "title" => "section 2",
      "position" => 0,
    }
  ]
}
```
When running tests, a form with the above attributes actually gets created. `IO.inspect` shows this:
```
%Form{
  __meta__: #Ecto.Schema.Metadata<:loaded, "tenant_testcompanyinc", "forms">,
  id: 13,
  title: "Test form",
  form_sections: [
    %FormSection{
      __meta__: #Ecto.Schema.Metadata<:loaded, "tenant_testcompanyinc", "form_sections">,
      id: 16,
      title: "section 1",
      position: 0,
      form_id: 13
    },
    %FormSection{
      __meta__: #Ecto.Schema.Metadata<:loaded, "tenant_testcompanyinc", "form_sections">,
      id: 17,
      title: "section 2",
      position: 0,
      form_id: 13
    }
  ]
}
```
Outside of tests, it doesn't (which is the correct behavior):
```
** (Postgrex.Error) ERROR 23505 (unique_violation) duplicate key value violates unique constraint "unique_form_section_position"

    table: form_sections
    constraint: unique_form_section_position

Key (form_section_id, "position")=(1, 0) already exists.
    (db_connection 2.7.0) lib/db_connection.ex:1791: DBConnection.run_transaction/4
    (ecto 3.12.5) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
```
I also found [this](https://github.com/elixir-ecto/ecto/issues/2394#issuecomment-360545178), and that approach _seems_ to work (i.e. tests where the unique constraint is violated actually fail like they should). However, I want to make sure that the recommended workaround for testing deferrable constraints in sandbox mode is to actually append this in every transaction where we defer constraints:
```
[...previous multis omitted...]
|> Ecto.Multi.run(:undefer, fn(_repo, _x) ->
  Repo.query("SET CONSTRAINTS ALL IMMEDIATE", [], prefix: TenantActions.build_prefix(tenant))
end)
|> Repo.transaction()
```
Apologies if this is just some big confusion on my part, but I did waste a couple of frustrating hours on this last night, so I want to make sure I have it 100% correct.
