### ISSUE TITLE
Docs are missing for the Ecto.Migration callbacks

### ISSUE THREAD

**Issue by tsutsu** [elixir-ecto/ecto#2623]
### Environment

* Elixir version (elixir -v): `Elixir 1.6.6 (compiled with OTP 20)`
* Ecto version (mix deps): `locked at 2.2.10 (ecto) e7366dc8`

### Expected behavior

The `Ecto.Migration.up/0`, `Ecto.Migration.down/0`, and `Ecto.Migration.change/0` callbacks should be documented.

I've seen several instances in the Elixir Slack group of people looking for more documentation about valid/invalid definitions of these callbacks than the `Ecto.Migration` moduledoc provides, expecting to find such information in callback docs that aren't there.

Specifically, the callback docs for `change/0` could provide more detail on what constitutes "a non-reversible command" (referred to in https://hexdocs.pm/ecto/Ecto.Migration.html#module-change), which is a frequent question.

**Comment by josevalim** [comment]
Thanks for the feedback! A PR would be welcome too. :)

**Comment by tsutsu** [comment]
Will do—though I am actually not exactly sure myself what guarantees the docs should be making, and what guidance / rules of thumb they should be giving. (It's easy enough to write a PR for the docs if I knew the spec these callbacks are implicitly following—but I don't know the spec, just the current implementation. The spec for "what a valid `change/0` function looks like", as it pertains to the evolution of Ecto over time, is still something that's just in the Ecto maintainers' heads at this point, I think.)

For example, here are things I think would need to be fleshed out just for the "Reversibility" section of the `change/0` callback:

* Is reversibility something that can be determined by looking at the set of migration-command macros used, or do you also have to look at their parameters? I don't believe there is currently a case where a command's do-block could be the difference between it being reversible or not, but might such a command be introduced in the future, or is there a guarantee that a given command will either be always-reversible or never-reversible?
* Presumably, a command macro that was reversible in one Ecto release won't become irreversible in a newer Ecto release, for backward compatibility. But will a previously-irreversible command macro ever become reversible in a newer Ecto release? Which is to say, could a migration `change/0` body that can't actually be rolled back because it contains irreversibles as of one Ecto release, become able to be rolled back with a later release?
* Are command macros expected to be reversible-unless-otherwise-specified, or irreversible-unless-otherwise-specified, or neither? If there is a new migration-command macro introduced in a later Ecto version, and a developer is unfamiliar with it, but has read the migration callback docs, would it make sense for the migration callback docs to provide guidance so the dev can recall it and assume the reversibility of the new command, without looking at the command macro's docs? (For example: "information-destroying migration commands, such as `drop/1`, are irreversible. `execute/1` is also irreversible, because the effects of executing arbitrary SQL cannot be predicted by Ecto. All other commands are reversible.")

Glad to write the actual docs if we first hammer out what wisdom they're imparting :smile:

**Comment by josevalim** [comment]
Hi @tsutsu, answers follow:

> Is reversibility something that can be determined by looking at the set of migration-command macros used, or do you also have to look at their parameters? 

The reversibility is usually specified by the command (name+arity). I think having it depend on the argument can be confusing, so I would generally avoid it.

> But will a previously-irreversible command macro ever become reversible in a newer Ecto release?

Yes, it may. You should rely on reversibility, not on irreversibility.

> Are command macros expected to be reversible-unless-otherwise-specified, or irreversible-unless-otherwise-specified, or neither?

reversible-unless-otherwise-specified

> Right now only command macros with SQL-standard-guaranteed (ir)reversibility semantics are provided. 

The behaviour is always adapter specific but, as you noted, we do our best to keep it general.

**Comment by josevalim** [comment]
Improved docs in master.
