### ISSUE TITLE
When using Ecto.Repo.get/2 in a gen_statem the connection times out even after the call returns

### ISSUE THREAD

**Issue by QuantamHD** [elixir-ecto/ecto#2629]
### Environment

* Elixir version 1.7
* PostgreSQL 10
* Ecto 2.2.10
* Postgrex 0.13.5
* Operating system: OSX

### Current behavior

In Ecto using the Repo.get/2 call inside a gen_statem callback function will not release the connection back to the pool when the call is complete and returns 

`[error] Postgrex.Protocol (#PID<0.394.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.538.0> timed out because it owned the connection for longer than 15000ms`

My use case requires that I start a dynamic amount of these state machines through a webserver to do some task. They consistently back their state up postgres for relaunch in the case of Node faliure. From my understanding the connection pool is granting a particaular process ownership of the connection which times out after 15s by default. The call does infact return in only 1ms, but the connection is never returned to the pool. The way I workaround this is by launching each database call inside a task which dies and returns the connection however I am weary about both the complexity of this and performance implications. 

```elixir
defmodule WorkflowEngine.Runner do
  use GenStateMachine, callback_mode: [:handle_event_function]

  alias Project.Repo
  alias Project.Instance
  require Logger

  def child_spec(args) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, args},
      restart: :transient
    }
  end

  def start_link(instance_id) do
    GenStateMachine.start_link(__MODULE__, instance_id)
  end

  @impl true
  def init(instance_id) do
    {:ok, :loading, instance_id, [{:next_event, :internal, :load_instance}]}
  end

  @impl true
  def handle_event(:internal, :load_instance, :loading, instance_id)
      when is_integer(instance_id) do
    Logger.info("Starting workflow instance #{inspect workflow_instance_id}")

    case Repo.get(Instance, instance_id) do
      %Instance{running: false} = workflow_instance ->
        Logger.info("Initialized starting loop workflow instance #{workflow_instance_id}")
        {:next_state, :execute, workflow_instance, [{:next_event, :internal, :launch}]}

      error ->
        Logger.info("in internal load_instance")
        {:stop, :normal}
    end
  end
end

```

I can provide an example project on request, but this simple use case of gen_statem has be sufficent to reproduce the issue.
### Expected behavior

To me the expected behavior should be that on call return the connection should be retured to the pool or provide a way to release the ownership of the connection in long running processes.

**Comment by QuantamHD** [comment]
Hi José,

I've included the configuration below. I'm seeing this error in my running it as MIX_ENV=dev

```elixir
config :workflow_engine, WorkflowEngine.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("DB_USERNAME") || "postgres",
  password: System.get_env("DB_PASSWORD") || "postgres",
  database: System.get_env("DB_NAME") || "workflow_engine_dev",
  hostname: System.get_env("DB_HOSTNAME") || "127.0.0.1",
  port: System.get_env("DB_PORT") || 5432,
  pool: Ecto.Adapters.SQL.Sandbox
```
I think I may see the issue now. I'm assuming this is caused because I ran the development system under the Ecto.Adapters.SQL.Sandbox model. I apologize for the errounous report if that's the case.

**Comment by josevalim** [comment]
Yes, you should not use the sandbox in dev. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by QuantamHD** [comment]
Thanks again José! Sorry about the incorrect issue.
