### ISSUE TITLE
Setting an integer value that is equal to the default value prevents the field from being included in the changes map

### ISSUE THREAD

**Issue by aesmail** [elixir-ecto/ecto#2630]
### Environment

* Elixir version (elixir -v): 1.7.1
* Database and version: PostgreSQL 10.4
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: macOS

### Current behavior
I am testing my schemas and changesets in ExUnit.

This is my schema definition:
```elixir
schema "payments_items" do
    # ... some other fields
    field :identifier, :string
    field :resource, :string
    field :title, :string
    field :description, :string
    field :quantity, :integer, default: 1
    field :unit_price, :decimal
    belongs_to :receipt, Payments.Schemas.Receipt
    timestamps()
end
```

Notice the default value for `quantity` is 1.

I have the following test values for my `Item` schema:

```elixir
valid_items = [
      %{
        item: %{
          :identifier => "3",
          :resource => "course",
          :title => "How to Deprogram in Objective-C",
          :description => "",
          :quantity => 1,
          :unit_price => 29,
          :visible => true,
        }
      },
      %{
        item: %{
          :identifier => "2",
          :resource => "course",
          :title => "How to Program in Swift",
          :description => "",
          :quantity => 6,
          :unit_price => 4,
          :visible => true,
        }
      },
    ]
```

Notice that `quantity` is 1 and 6 for both items respectively.

```elixir
def changeset(item, attrs) do
    item
    |> cast(attrs, [:description, :quantity, :unit_price, ...other fields])
    |> calculate_total_amount()
    |> validate_required([:quantity, :unit_price, :visible, :ignore, :status, :total_amount])
    ...
end

defp calculate_total_amount(%Ecto.Changeset{valid?: true, changes: %{quantity: quantity, unit_price: unit_price}} = changeset) do
    IO.puts "calculating total amount..."
    total_amount = Decimal.mult(quantity, unit_price)
    new_changeset = put_change(changeset, :total_amount, total_amount)
    IO.inspect new_changeset
    new_changeset
end
defp calculate_total_amount(changeset), do: changeset
```

When I call the changeset function, I get an invalid changeset and the `changes` map in the changeset doesn't include the `quantity` field if `quantity` equals to the default value that was set in the schema. If I change the default to `default: 2` and set `:quantity => 1` everything works as expected.

### Expected behavior

The value of the field should be set in the changeset's `changes` map regardless of the actual value when creating a new struct.

I'm sure I'm missing something here, but that's what the tests show.

**Comment by josevalim** [comment]
The changes are only going to include what changed. The issue here is rather that you are pattern matching on the changes, while instead you should use `Ecto.Changeset.get_field` to get the value, be it from changes or from the struct.

**Comment by aesmail** [comment]
True, but shouldn't `Item.changeset(%Item{}, valid_item_params)` include the `quantity` field in changes since %Item{} doesn't include any values?

**Comment by michalmuskala** [comment]
If it's the default, it does include the value.

**Comment by aesmail** [comment]
This goes also for the `visible` field and any field that has a "new" value that is equal to the default value.

**Comment by aesmail** [comment]
Ok, so the value of `%Item{}` already will assign the values 1 and true to quantity and visible and then THAT is passed to the `changeset()` function which sees that the values weren't changed.

It makes sense, but it was a bit strange that I'm assigning "new" values that weren't included in the changes. Maybe that should be mentioned in the docs somewhere?

**Comment by aesmail** [comment]
I guess the confusion was around thinking that default values would be set IF they weren't populated from the attributes, i.e., `cast/4` would set the default values after checking all the passed in attributes, not the other way around.

**Comment by michalmuskala** [comment]
Yeah, the `default` option is like passing a value on a `defstruct` definition. It's similar as if you called `Item.changeset(%Item{guantity: 1}, item_attrs)`

I'm not sure where we could mention this to make this more apparent. Maybe in the documentation for the `changes` field of the changeset
