### ISSUE TITLE
Provide better documentation for inline embeds options

### ISSUE THREAD

**Issue by tcoopman** [elixir-ecto/ecto#2631]
Maybe it's just me, but it took me a long while to find out how I should add options to inline embeds. I couldn't find anything in the documentation, and it was only after I was reading the code that I figured out that it was possible.

This could be improved by adding an example to https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_many/3-inline-embedded-schema.

If you're open to it I can provide an PR with an example like:

```elixir
defmodule Parent do
  use Ecto.Schema
  schema "parents" do
    field :name, :string
    embeds_many :children, Child, [on_replace: :delete] do
      field :name, :string
      field :age,  :integer
    end
  end
end
```

**Comment by josevalim** [comment]
Please do send a PR!
