### ISSUE TITLE
Timestamps: updated_at greater that inserted_at on creation

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-ecto/ecto#2633]
### Environment

* Elixir version (elixir -v): Elixir 1.5.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: Mac OS 

### Current behavior

I found that `updated_at` is always greater then `inserted_at` timestamp. Is there any reason why autogen works like this?

### Expected behavior

Once record created `updated_at` equals to `inserted_at`

**Comment by fertapric** [comment]
https://github.com/elixir-ecto/ecto/issues/1486 is a bit related to this issue.

Looking at the implementation, both are generated independently and it would require one to know about the other.

**Comment by mojidabckuu** [comment]
@fertapric Yeah! I've checked the source. But I can't understand is there any way to synchronise `inserted_at` and `updated_at` timestamps on creation

**Comment by AndrewDryga** [comment]
You might try to generate timestamps on PostgreSQL side, `NOW()` within the transaction doesn't change.

> It is quite important to realize that CURRENT_TIMESTAMP and related
functions all return the time as of the start of the current transaction;
their values do not increment while a transaction is running.

**Comment by michalmuskala** [comment]
I think the only way to achieve this would be to have some wrapper around `DateTime` that does something similar to database itself - it freezes the time during `Repo.transaction` calls.

It could be something like:
```elixir
defmodule Ecto.FrozenDateTime do
  def freeze_time(fun) do
   old_value = Process.put(:ecto_frozen_time, DateTime.utc_now())
   try do
     fun.()
   after
     if old_value do 
       Process.put(:ecto_frozen_time, old_value)
     else
       Process.delete(:ecto_frozen_time)
     end
   end 
  end

  def date_time do
    Process.get(:ecto_frozen_time)
  end

  def date do
    DateTime.to_date(Process.get(:ecto_frozen_time))
  end

  # and similar
end
```

We could wrap the auto-generation part of `Repo` calls and possibly the entire `Repo.transaction` in such a `Ecto.FrozenDateTime.freeze_time(fn -> ... end)` call. We then use the functions in that module for auto-generating values in timestamps instead of using the regular `DateTime.utc_now()` calls. I'm not 100% convinced that's a good idea, though, but that's probably the only way to achieve this.

**Comment by fertapric** [comment]
@michalmuskala Would that mean that the records of this example would all have the same timestamps?

```elixir
Repo.transaction(fn ->
  Repo.insert!(...) # Record 1
  Repo.insert!(...) # Record 2
  Process.sleep(2000)
  Repo.insert!(...) # Record 3
end)
```

**Comment by mojidabckuu** [comment]
@michalmuskala is it not that expensive to get frozen time during opened transaction? 
Right now I solved it with a custom module that put timestamps manually 
```elixir
defmodule Ecto.Timestamps do
  import Ecto.Changeset

  @default_opts [inserted_at: :inserted_at, updated_at: :updated_at]

  def put_timestamps(%Ecto.Changeset{} = changeset, opts \\ @default_opts) do
    inserted_at_key = Keyword.fetch!(opts, :inserted_at)

    if not is_nil(Map.get(changeset.data, inserted_at_key)) do
      do_put_update_timestamps(changeset, opts)
    else
      do_put_all_timestamps(changeset, opts)
    end
  end

  defp do_put_all_timestamps(changeset, opts) do
    inserted_at_key = Keyword.fetch!(opts, :inserted_at)
    updated_at_key = Keyword.fetch!(opts, :updated_at)

    timestamp = DateTime.utc_now()
    changeset
    |> put_change(inserted_at_key, timestamp)
    |> put_change(updated_at_key, timestamp)
  end

  defp do_put_update_timestamps(%Ecto.Changeset{} = changeset, opts) do
    updated_at_key = Keyword.fetch!(opts, :updated_at)

    timestamp = DateTime.utc_now()
    changeset
    |> put_change(updated_at_key, timestamp)
  end
end
```
But not sure that it solves the problem properly

**Comment by michalmuskala** [comment]
@fertapric yes, they would all have the same time-stamp, following exactly the database semantics of `NOW()` or `CURRENT_TIMESTAMP` within a transaction.

The frozen time would actually be more performant than the current implementation - right now we need to get the time source each time we need to generate a value and then we need to convert it each time.

**Comment by fertapric** [comment]
Here is a crazy idea.

What if you can have more than one field in `:autogenerate`:

https://github.com/elixir-ecto/ecto/blob/f608c18547b3ade9c9fcd06a054ce8d544ca2c49/lib/ecto/repo/schema.ex#L783-L787

This would be something like:

```elixir
defp autogenerate_changes(schema, action, changes) do 
  action
  |> action_to_auto()
  |> schema.__schema__()
  |> Enum.reduce([], fn {keys, {mod, fun, args}}, acc ->
      value = apply(mod, fun, args)
      
      autogenerated_changes = 
         for key <- List.wrap(keys),
           not Map.has_key?(changes, key), 
           do: {key, value}
           
      acc ++ autogenerate_changes
    end) 
end
```

so you can pass both when defining the timestamps:

https://github.com/elixir-ecto/ecto/blob/f608c18547b3ade9c9fcd06a054ce8d544ca2c49/lib/ecto/schema.ex#L606-L615

```elixir
inserted_at = Keyword.fetch!(timestamps, :inserted_at)
updated_at = Keyword.fetch!(timestamps, :updated_at)

cond do
  inserted_at and updated_at ->
    Ecto.Schema.field(inserted_at, type, [])
    Ecto.Schema.field(updated_at, type, [])
    Module.put_attribute(__MODULE__, :ecto_autogenerate, {[inserted_at, updated_at], autogen})
    Module.put_attribute(__MODULE__, :ecto_autoupdate, {updated_at, autogen})

  inserted_at ->
    Ecto.Schema.field(inserted_at, type, [])
    Module.put_attribute(__MODULE__, :ecto_autogenerate, {inserted_at, autogen})

  true ->
    Ecto.Schema.field(updated_at, type, [])
    Module.put_attribute(__MODULE__, :ecto_autogenerate, {updated_at, autogen})
    Module.put_attribute(__MODULE__, :ecto_autoupdate, {updated_at, autogen})
end
```

I might have missed other implications of the autogenerated fields.

Thoughts?

**Comment by michalmuskala** [comment]
I'm sorry, but I don't understand what that would do or allow.

**Comment by fertapric** [comment]
It would allow to assign the same autogenerated value to more than one field at a time.

**Comment by fertapric** [comment]
> Ah I see. It does solve the problem of different values in one struct, but it still leaves the issue that you get different values when you insert together some nested associations.

Yeah. Could that be a good compromise?

> @fertapric yes, they would all have the same time-stamp, following exactly the database semantics of NOW() or CURRENT_TIMESTAMP within a transaction.

Could it be confusing if developers use `DateTime.utc_now()` for populating other timestamps, like`archived_at` or `deleted_at`. In such cases, if the date time is frozen at the beginning of the transaction, the `:updated_at` timestamp will always be in the past, which I think will break the semantics of that attribute.

**Comment by fertapric** [comment]
Other option is to make that "frozen date time" function public and document it, so developers can assign that value to those custom timestamps.

**Comment by michalmuskala** [comment]
Yeah, we could make the module public so developers can use it for populating other fields, if they wish to.

**Comment by josevalim** [comment]
@michalmuskala I don't think it would work because in many cases, the attributes of both parent and associations records are set BEFORE starting a transaction. The transaction is only started when you sent things to the repo.

**Comment by wojtekmach** [comment]
I'm not sure if this was previously discussed, but another solution is to let DB handle inserted_at/updated_at via triggers. This has added benefit of also populating the fields with insert_all/update_all. There could be some DSL for creating these triggers in migrations. I haven't tried it, but I know diesel.rs takes this approach.

**Comment by josevalim** [comment]
@whatyouhide the issue is that we can't get this data back in databases like MySQL. :(

**Comment by michalmuskala** [comment]
@josevalim we execute `autoupdate` and `autoinsert` inside repo within the transaction call.

https://github.com/elixir-ecto/ecto/blob/df7fd0a32c5e9bfb78ed1bca1dbeacd315f5aa86/lib/ecto/repo/schema.ex#L217-L218

So it would work for autogeneration.

**Comment by josevalim** [comment]
@michalmuskala but only auto-generation. I was replying to this:

> Yeah, we could make the module public so developers can use it for populating other fields, if they wish to.

Unfortunately I don't see how making it public would address the issue with other fields.

**Comment by michalmuskala** [comment]
Soo... More hacks continue - we could make the function return some data structure we would convert to the actual timestamp in the `dump` callback which also happens inside repo and inside transaction. But yeah, this starts to becoming ridiculous.

**Comment by josevalim** [comment]
@michalmuskala yeah, I would fix the builtin timestamps and call it a day, using an approach similar to the one from @fertapric.

**Comment by qcam** [comment]
I can give this PR a try if it has not been taken.

**Comment by josevalim** [comment]
That will be great @qcam! Before implementing though, we should probably discuss how to best tackle it. Do you have any ideas? I am afraid this can turn out to be a very complex issue. :)

**Comment by qcam** [comment]
@josevalim my plan is to take @fertapric's approach (at least I thought we kinda consent on that from what I read?), by putting `{inserted_at, updated_at}` pair into `@autogenerate` instead of splitting them into two entries when generating the schema.

For runtime I guess changing the implementation here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L802-L806

Maybe I'm too optimistic?

**Comment by josevalim** [comment]
@qcam maybe we could make that the autogenerated functions returns a list of changed fields? But that would require  some big changes to the schema... some of them may even be backwards incompatible. :(

**Comment by qcam** [comment]
> maybe we could make that the autogenerated functions returns a list of changed fields?

Sorry for the spamming it might be but I don't think I get this. 😳

**Comment by qcam** [comment]
I kinda came up with a commit here to explain what I have in mind. Would you mind taking a look? https://github.com/qcam/ecto/commit/88edbe7546d6ab7467dea5f144ec248054de14bd.

**Comment by josevalim** [comment]
@qcam oh, I see. I like it. Let's do this :)

**Comment by qcam** [comment]
Thanks @fertapric. I have added `true -> :ok` to the PR #2711, would be appreciated if you could take a look ^_^.

Regarding the autogenerates, I might be wrong but I don't think we have any documentation for it publicly in [Module Reflection](https://hexdocs.pm/ecto/Ecto.Schema.html#module-reflection) so I made an assumption that it's only for internal use.
