### ISSUE TITLE
add option to provide default to `embeds_one`

### ISSUE THREAD

**Issue by tcoopman** [elixir-ecto/ecto#2634]
I'm trying to set a default value for an `embedded_schema` with an `embeds_one`. 

As I'm talking about an `embedded_schema` I can't set a default on the database.
It would be nice if this were possible the same way like for `field(:foo, :string, "bar)`:
```elixir
embeds_one, :user, User, default: %{} do
...
end
```

**Comment by josevalim** [comment]
Hi @tcoopman. For example, in this case you would set the default to an empty map, which would not be valid. Probably you are suggesting for us to automatically merge this empty map into the schema definition, then it behaves quite differently than the field default. It is for those reasons why we do not allow defaults for embeds and relationships, but you can always set it when building the struct! Thanks!
