### ISSUE TITLE
Unnecessary warning for two fields pointing to same source

### ISSUE THREAD

**Issue by imranismail** [elixir-ecto/ecto#2638]
### Environment

* Elixir version (elixir -v): 1.7.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.4
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): Postgres
* Operating system: MacOS

### Current behavior

```elixir
    field :transaction_details, :map
    
    embeds_one :transaction_detailz, Transactiondetail, source: :transaction_details, primary_key: false do
      field :currency, :string
    end
```

Throws a warning like so:

```
warning: this clause cannot match because a previous clause at line 18 always matches
  lib/inventory/models/reservation_set.ex:18
```

### Expected behavior

It should not throw a warning because those are two different fields but from the same source

**Comment by josevalim** [comment]
@imranismail the warning can also be revealing that this was not thought out and it may not work as expected. How is it working so far?

**Comment by imranismail** [comment]
It works perfectly 👍
