### ISSUE TITLE
 Errors, when clear deps folder for compiled app

### ISSUE THREAD

**Issue by SofaKing18** [elixir-ecto/ecto#2644]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.4 (compiled with OTP 19)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
PostgreSQL 9.6
* Ecto version (mix deps):
v2.2.10
* Database adapter and version (mix deps):
postgrex v0.13.5
* Operating system:
Mac OS High SIerra 10.13.4

### Current behavior

➜ phoenix_app git:(master) ✗ mix ecto.migrate
2018-08-06 15:37:57.830 [info][module: Ecto.Migrator] Already up
➜ phoenix_app git:(master) ✗ rm -rf deps
➜ phoenix_app git:(master) ✗ mix ecto.migrate --no-compile --no-deps-check
Unchecked dependencies for environment dev:

bcrypt_elixir (Hex package)
the dependency is not available, run "mix deps.get"
eredis (https://github.com/savonarola/eredis.git)
the dependency is not available, run "mix deps.get"
phoenix_bootstrap_form (Hex package)
the dependency is not available, run "mix deps.get"
httpotion (Hex package)
the dependency is not available, run "mix deps.get"
phoenix_pubsub (Hex package)
the dependency is not available, run "mix deps.get"
uuid (Hex package)
the dependency is not available, run "mix deps.get"
ibrowse (Hex package)
the dependency is not available, run "mix deps.get"
phoenix (Hex package)
the dependency is not available, run "mix deps.get"
postgrex (Hex package)
the dependency is not available, run "mix deps.get"
instream (Hex package)
the dependency is not available, run "mix deps.get"
....
Expected behavior
Expected, that there are no errors or checking of deps, because sources already compiled in _build

Is it possible to turn off deps checks like @josevalim says in https://github.com/elixir-lang/elixir/issues/8058?

**Comment by josevalim** [comment]
Hi @SofaKing18 , thanks for opening the issue here. We will have to pass those flags forward, which I don't believe we do right now.

**Comment by SofaKing18** [comment]
Tell please which files to look for, may be i will be able to make PR

**Comment by josevalim** [comment]
It starts here: https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.migrate.ex

But you will have to find out where the app is started from there. Probably somewhere in Mix.Ecto!

**Comment by josevalim** [comment]
@SofaKing18 i have investigated this and there is nowhere in Mix that we guarantee you can run without the source code. That's because the `_build` in mix contain symlinks to the deps directory. You can use the `--no-deps-check` to remove things such as the `.git` directories inside "deps" but the "deps" directory has to be there until a release is built. Thanks for following through though!
