### ISSUE TITLE
timestamp/naive_datetime fields always appear in changeset "changes" even if not changed

### ISSUE THREAD

**Issue by luccasmaso** [elixir-ecto/ecto#2646]
### Current behavior

As here in the docs says:
"By default, if there are no changes in the changeset, update/2 is a no-op."
https://hexdocs.pm/ecto/Ecto.Repo.html#c:update/2

But I've noticed that `updated_at` column was being updated even with the same update attributes already in database. This case happened when the changeset includes timestamp columns:

Notice that in the example below the first image is the first update:

<img width="1210" alt="screen shot 2018-08-07 at 23 02 59" src="https://user-images.githubusercontent.com/1427231/43812192-736fc596-9a96-11e8-889c-60bb817b8102.png">

In the second one I've submitted the same changeset, but this time the `changes` does not include the varchar column `status` with the value `canceled"` (because it didn't changed). The other timestamp columns were marked as changed but actually they are not.

Is this an expected behaviour? If not, maybe is a NaiveDatetime to timestamp conversion...

<img width="1206" alt="screen shot 2018-08-07 at 23 03 08" src="https://user-images.githubusercontent.com/1427231/43812312-14750e92-9a97-11e8-9426-9835ed9801d9.png">

Thanks

### Expected behavior

The expected behaviour should be that no changes are applied to the changeset and the `updated_at` column is not updated.

**Comment by luccasmaso** [comment]
Maybe this can help. The first image prints fields from Repo.get(...). The second one prints fields from a Repo.insert/update(...).

<img width="333" alt="screen shot 2018-08-08 at 00 48 04" src="https://user-images.githubusercontent.com/1427231/43815169-cb68f32c-9aa4-11e8-8f16-212cb58d57c5.png">

<img width="316" alt="screen shot 2018-08-08 at 00 48 14" src="https://user-images.githubusercontent.com/1427231/43815168-cb48c26e-9aa4-11e8-9f33-8c56eabf1f49.png">

**Comment by wojtekmach** [comment]
@lucasmazza looking at your last comments when data returned by Repo.get has microsecond precision but data returned by Repo.insert doesn't (because your changeset had timestamps without microseconf precision too), the issue seems related to https://github.com/elixir-ecto/ecto/issues/2018 and will be fixed in ecto 3.0 by introducing separate types.

In the future when submitting bugs please fill in issue template especially ecto version & which db you use!

**Comment by josevalim** [comment]
@wojtekmach you pinged the wrong Lucas. :) 

@luccasmaso as @wojtekmach explained, this is being addressed in the next ecto release!

**Comment by wojtekmach** [comment]
sorry @lucasmazza 😂

**Comment by lucasmazza** [comment]
@wojtekmach all good, haha 👋
