### ISSUE TITLE
Chosing between setting `on_delete: :delete_all` in schema or in migration should be clarified or avoided

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#2657]
The Ecto 2.2.10 docs page for [many-to-many/3](https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3) states:

> Notice :on_delete may also be set in migrations when creating a reference. If supported, relying on the database via migrations is preferred. 

It is not clear what "If supported" means. If supported by what? The database Ecto adapter, the database itself, or something else?

And when I asked in Ecto's Slack channel the question

> How to choose between setting `on_delete: :delete_all` in schema or in migration?

a member suggested

> do not choose, use in both of them if you can

without further clarification.

On the other hand, being Ecto a layer between application and the database, shouldn't there exist just one place where to set `on_delete: :delete_all`, and then, Ecto decides to implement it by generating the code to delete the associations or let the database do this instead (e.g., via `ON CASCADE DELETE` or something alike specific to the database being used) ?

My expectation with this ticket is one of (preferred first):
1. avoid developers from doing this choice by having just one place to set this option (and then, Ecto decides the best to do);
2. or, provide a better description to support the decision to set the option via the schema, migration, or both.

Thanks

**Comment by josevalim** [comment]
Hi @mguimas.

No need to set on both. The migration one should be preferred **if your database supports it** as the database will do a job of guaranteeing integrity. Most SQL ones do.

Does it clarify it? Can you please send a PR?

**Comment by mguimas** [comment]
Hi @josevalim 

so you opt for solution 2 to make the documentation more clear? Is that so?

I believe that the separation between schemas and migrations -- a design decision, which I suppose, permits Ecto to be very flexible in configuring persistence -- makes it difficult to decide where to put this option in just one place, anyway.

Thanks

**Comment by josevalim** [comment]
Yes, documentation clearer. I would say the order would be actually surprising given Ecto context, as we don't generally do reflection on the database to figure out how the schema should work.
