### ISSUE TITLE
Allow using binding variables directly to support calling custom functions

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#2659]
### Current behavior

Currently I'm getting this error:
```
** (Ecto.Query.CompileError) variable `(…)` is not a valid query expression. If you wanted to inject a variable, you have to explicitly interpolate it with ^. If you wanted to refer to a field, use the source.field syntax
```

When I'm trying to manually type first character of variable name with `0` suffix then it works well without any problem, but in much more complex queries it could be a big problem. Any `ecto` update or at least part of query update could cause problem like:

```
** (Postgrex.Error) ERROR 42703 (undefined_column) column "(…)" does not exist

    query: (…)

    hint: Perhaps you meant to reference the column "(…).id" or the column "(…).id".
    (ecto) lib/ecto/adapters/sql.ex:439: Ecto.Adapters.SQL.execute_and_cache/6
    (ecto) lib/ecto/adapters/sql.ex:413: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:148: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

which could be really hard to find especially with large debugged (truncated?) `query`.

### Expected behavior

I think that `ecto` should support it to allow easily using custom functions in fragments like:

```
MyModel
|> from()
|> select([variable_name], fragment("function_name(?))", variable_name))
```

**Comment by josevalim** [comment]
Can you provide an example of the custom function you are trying to invoke that requires you to pass the whole binding?

**Comment by Eiji7** [comment]
@josevalim sure, no problem

Here is [execute](https://gitlab.com/ex-open-source/invoicex/blob/master/lib/invoicex/migration.ex#L238) call. I made this in few functions to easily show whole logic part by part. This function is simply calculating `total` decimal value for given `invoice` (from `invoices` table).

Example call:
```sql
select invoice.id, invoicex_total(invoice) from invoices invoice;
```

**Note**: Of course I could pass just some fields, but this would make calling function much longer. The idea here is to write as simple function as possible, so it could be used anywhere without bigger effort.

**Comment by josevalim** [comment]
@Eiji7 thanks! Can you please send a PR? I would implement this by adding a simple test to `test/ecto/adapters/postgres_test.exs` and then go through the failures until you make sure it passes.
