### ISSUE TITLE
Endiness check for UUIDs

### ISSUE THREAD

**Issue by benperiton** [elixir-ecto/ecto#2660]
### Environment

* Elixir version (elixir -v): Elixir 1.7.2 (compiled with Erlang/OTP 19
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 2.1
* Database adapter and version (mix deps): N/A
* Operating system: Linux Mint

### Current behavior

Using Exldap to retrieve user details from Active Directory, one of the fields I wish to use is a GUID.
The textual representation of this GUID is ```4FC10CDB-5197-4B99-8058-17603B0A21AF```.

```elixir
'objectGUID' => [
    [219, 12, 193, 79, 151, 81, 153, 75, 128, 88, 23, 96, 59, 10, 33, 175]
]
```

```elixir
[219, 12, 193, 79, 151, 81, 153, 75, 128, 88, 23, 96, 59, 10, 33, 175]
|> :binary.list_to_bin
|> Ecto.UUID.load

{:ok, "db0cc14f-9751-994b-8058-17603b0a21af"}
```

Notice that the first 3 parts are reversed. This seems to be (according to wikipedia):
> Variant bits aside, the two variants are the same except that when reduced to a binary form for storage or transmission, variant 1 UUIDs use “network” (big-endian) byte order, while variant 2 GUIDs use “native” (little-endian) byte order. In their textual representations, variants 1 and 2 are the same except for the variant bits.

> When byte swapping is required to convert between the big-endian byte order of variant 1 and the little-endian byte order of variant 2, the fields above define the swapping. The first three fields are unsigned 32- and 16-bit integers and are subject to swapping, while the last two fields consist of uninterpreted bytes, not subject to swapping. This byte swapping applies even for version 3, 4, and 5 UUID’s where the canonical fields do not correspond to the content of the UUID

If I swap the first parts, it then works.
```elixir
Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> << a::32, b::16, c::16, d::16, e::48 >> = [219, 12, 193, 79, 151, 81, 153, 75, 128, 88, 23, 96, 59, 10, 33, 175] |> :binary.list_to_bin
<<219, 12, 193, 79, 151, 81, 153, 75, 128, 88, 23, 96, 59, 10, 33, 175>>

iex(2)> << a::32-little, b::16-little, c::16-little, d::16-big, e::48-big >> |> Ecto.UUID.load                                                 
{:ok, "4fc10cdb-5197-4b99-8058-17603b0a21af"}
```

Note: Im not sure if this is an actual issue with Ecto, or if it is just a quirk of how AD stores the represenation.

### Expected behavior

That the correct value is returned when using Ecto.UUID.*

**Comment by josevalim** [comment]
As the wikipedia page says, you don't have a UUID, but rather a GUID. My suggestion is for you to implement a custom type based on `Ecto.UUID`, named `EctoGUID`, and use it as part of your project.

**Comment by benperiton** [comment]
I had always assumed that the term GUID and UUID were interchangeable - I wasn't aware that there was any difference. But if Ecto treats them differently, then yep, I'll create a custom type to use.

Thanks!

**Comment by josevalim** [comment]
AFAIK the endianess is the main difference. So a custom type is the way to go here. :)
