### ISSUE TITLE
Too much intermediate data loaded using has_many :through?

### ISSUE THREAD

**Issue by gmile** [elixir-ecto/ecto#2665]
When asked to preload a `:through` association, Ecto loads a lot of intermediate data.

If I run this code:

<details>
<summary>Schema</summary>

```elixir
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    field :full_name, :string
    field :email, :string
  end
end

defmodule Comment do
  use Ecto.Schema

  schema "comments" do
    field :subject, :string
    field :content, :string
    field :post_id, :integer

    belongs_to :author, Author
  end
end

defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field :title, :string
    field :body, :string

    has_many :comments, Comment
    has_many :commenters, through: [:comments, :author]
  end
end
```
</details>

<details>
<summary>Data</summary>

```elixir
RedundancyRepo.insert_all("posts", [
  %{id: 1, title: "My title", body: "My body"}
])

RedundancyRepo.insert_all("authors", [
  %{id: 1, full_name: "Full name 1", email: "client1@server.com"},
  %{id: 2, full_name: "Full name 2", email: "client2@server.com"},
  %{id: 3, full_name: "Full name 3", email: "client3@server.com"}
])

RedundancyRepo.insert_all("comments", [
  %{id: 1, post_id: 1, author_id: 1, subject: "Subject 1", content: "Big content 1"},
  %{id: 2, post_id: 1, author_id: 2, subject: "Subject 2", content: "Big content 2"},
  %{id: 3, post_id: 1, author_id: 3, subject: "Subject 3", content: "Big content 3"},
  %{id: 4, post_id: 1, author_id: 1, subject: "Subject 4", content: "Big content 4"},
  %{id: 5, post_id: 1, author_id: 2, subject: "Subject 5", content: "Big content 5"},
  %{id: 6, post_id: 1, author_id: 3, subject: "Subject 6", content: "Big content 6"}
])
```

</details>

```elixir
commenter_emails_query = from a in Author, select: struct(a, [:id, :email])
posts_query = from p in Post, preload: [commenters: ^commenter_emails_query]

[post] = RedundancyRepo.all(posts_query)
```

Ecto produces the following SQL statements:

```
15:11:18.730 [debug] QUERY OK source="posts" db=0.3ms queue=0.1ms
SELECT p0."id", p0."title", p0."body" FROM "posts" AS p0 []

15:11:18.730 [debug] QUERY OK source="comments" db=0.4ms
SELECT c0."id", c0."subject", c0."content", c0."post_id", c0."author_id", c0."post_id" FROM "comments" AS c0 WHERE (c0."post_id" = $1) ORDER BY c0."post_id" [1]

15:11:18.731 [debug] QUERY OK source="authors" db=0.3ms
SELECT a0."email", a0."id" FROM "authors" AS a0 WHERE (a0."id" = ANY($1)) [[1, 2, 3]]
```

(the repo with example above is available as [`ecto_redundancy_issue`](https://github.com/gmile/ecto_redundancy_issue))

Note the `SELECT c0."id", c0."subject", c0."content", c0."post_id", c0."author_id", c0."post_id" FROM "comments" ...` query. 

If I was interested in fields from comments, I'd have `preload: [:comments]` included explicitly, as an association I want to preload and build structs for. However, I'm only interested in comment authors' emails, so I have `preload: [:commenters]`.

In this case loading comments is not desirable:

* it adds network pressure when passing around potentially big chunks of `comments.content` text data,
* it adds processor and memory pressure when building structs for `comments`, which are thrown away.

Unless it was a design decision to keep Ecto complexity moderate for the case described, would it be possible to not preload intermediate records fully, and only preload foreign keys, required to tie the intermediate record in question to its parent, and to establish which children there's to load?

For example, given the comments query above:

```sql
SELECT c0."id", c0."subject", c0."content", c0."post_id", c0."author_id", c0."post_id" FROM "comments" AS c0 WHERE (c0."post_id" = $1) ORDER BY c0."post_id" [1]
```

It could be rewritten to this:

```sql
SELECT c0."id", c0."author_id", c0."post_id" FROM "comments" AS c0 WHERE (c0."post_id" = $1) ORDER BY c0."post_id" [1]
```

Here, `post_id` is present to tie comments to the parent, and `author_id` is present to establish the IDs for the next query.

### Environment

* Elixir version: Elixir 1.7.2 (compiled with Erlang/OTP 21)
* Database and version: PostgreSQL 10.5
* Ecto version (mix deps): master branch, specifically 63d075d66201819e37d6774f155a487ace583855
* Database adapter and version (mix deps): 0.13.5
* Operating system: macOS

### Current behavior

Preload is loading all intermediate data.

### Expected behavior

Maybe: preload only foreign keys?

**Comment by josevalim** [comment]
`:through` is meant to be literally through each step along the way, that's why the intermediate fields are filled. If you want to avoid the intermediate data, then declaring a many to many relationship is the way to go.

**Comment by gmile** [comment]
@josevalim Noted on the many_to_many. Thank you for explaining the motivation behind `through`!
