### ISSUE TITLE
Schema without source name, what does it mean?

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#2668]
### Environment

Elixir 1.7.2
Ecto 2.2.10

### Current behavior

The documentation does not explain what a schema without a table name means, like the following

```
iex(18)> defmodule X do
...(18)>   use Ecto.Schema
...(18)>   schema "" do
...(18)>     field :x, :string
...(18)>   end
...(18)> end
{:module, X,
 <<70, 79, 82, 49, 0, 0, 11, 52, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 149,
   0, 0, 0, 44, 8, 69, 108, 105, 120, 105, 114, 46, 88, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>,
 {[
    %X{__meta__: #Ecto.Schema.Metadata<:built, "">, id: nil, x: nil},
    {:__changeset__, 0},
    {:__schema__, 1},
    {:__schema__, 2},
    {:__schema__, 1},
    {:__schema__, 1},
    {:__schema__, 2},
    {:__schema__, 2},
    {:__schema__, 2},
    {:__schema__, 1},
    {:__schema__, 1}
  ], []}}
```

Apparently this is very similar to an `embedded_schema` like this (only some bytecodes seem to differ):

```
iex(19)> defmodule X do
...(19)>   use Ecto.Schema
...(19)>   embedded_schema do
...(19)>     field :x, :string
...(19)>   end
...(19)> end
warning: redefining module X (current version defined in memory)
  iex:19

{:module, X,
 <<70, 79, 82, 49, 0, 0, 10, 232, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 159,
   0, 0, 0, 45, 8, 69, 108, 105, 120, 105, 114, 46, 88, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>,
 {[
    %X{id: nil, x: nil},
    {:__changeset__, 0},
    {:__schema__, 1},
    {:__schema__, 2},
    {:__schema__, 1},
    {:__schema__, 1},
    {:__schema__, 2},
    {:__schema__, 2},
    {:__schema__, 2},
    {:__schema__, 1},
    {:__schema__, 1}
  ], []}}

```

### Expected behavior

The documentation about `schema` and `embbeded_schema` should be clear about their use cases. In particular, it should state what does `schema "" do ... end` means.

Alternatively, if an empty source name is something wrong, then the API should reject it with some kind of error or exception, or this is something that must be fixed (i.e., a bug to fix).

**Comment by josevalim** [comment]
@mguimas there is nothing wrong with it. :) The schema argument needs to map to something that exists in the database. If your database allows empty table names, then an empty schema name is totally fine. You will only know if a schema is valid when you try to write it to the database.

**Comment by mguimas** [comment]
That is really providing extremelly generic support. Ok, but then it would be useful to write something about that in the docs: it can be just what you stated.

Now, regarding `embbedded_schema`, it seems that it is being used for in-memory struct manipulation via `Ecto.Changeset`, and not only being used as documented. It would be nice to describe this use case in the docs, or alternatively, to recommend developers to not make such use case, to block it from being done in Ecto, or to deprecate such use case in favor of a new function with a more meaningful name to support such use case. You would consider this, perhaps in this issue, or in another issue to be opened?

**Comment by mguimas** [comment]
@josevalim Also regarding the use `embbedded_schema`, it seems that it is being used for in-memory struct manipulation via `Ecto.Changeset`, and not only being used as documented. It would be nice to describe this use case in the docs, or alternatively, to recommend developers to not make such use case, to block it from being done in Ecto, or to deprecate such use case in favor of a new function with a more meaningful name to support such use case. You would consider this, perhaps in this issue, or in another issue to be opened?

**Comment by josevalim** [comment]
@mguimas the thing is that I am not sure if we can confidently say that all empty sources is a bug. It is really not up to Ecto to decide that. If you really don't care about the data source, then `embedded_schema` is most likely the way to go.

That said, using `embedded_schema` for in-memory structs is officially supported so I suggest improving the documentation on this area. Can you please send a PR?

**Comment by mguimas** [comment]
@josevalim I understand your point about being a bug or not, but I suggest for you to consider it a bug. Also, any future such adapter, if it ever comes to exist, can easily ignore the source name, so there will be no obstacle to writting such adapter.

Regarding the `embedded_schema` I don't think it is clean to use this keyword to support two different features: true embedded schemas, and in-memory schemas. It is confusing, and the keyword name only makes one recall the first use. I would suggest supporting `schema do ... end` for in-memory schemas, which could support `embedded_schema`s inside them properly. That said, the second use of `embedded_schema` would be then marked or documented as deprecated.

I think this is a preferred way to go, one that will make Ecto cleaner. What do you think?

**Comment by josevalim** [comment]
I don't see the purpose in forbidding `schema "" do`. Why would somebody write that in the first place? It is not different from `schema "whatever" do`. This is not about ignoring the source name. If there is an adapter that does not care about source names, then we can gladly reopen this discussion and figure out the best API there.

`embedded_schema` also changes the primary key type and skips the `__meta__` field, so I don't think it can be replaced by `schema do` as that would be a big difference between `schema/1` and `schema/2`. I am also not a big fan of having something like `in_memory_schema`, which would literally be the same as an `embedded_schema`.

If we can find a name that reveals both intents, I will be glad to consider it, but it needs to be a considerable improvement if we want to push folks through a deprecation. Meanwhile, the best we can do is to improve the docs, as the docs will be useful regardless of the old or new APIs.

**Comment by mguimas** [comment]
ok, seems reasonable, and the fastest thing to do at the moment. Thanks
