### ISSUE TITLE
mix ecto.create error in a new fresh project with an Ecto.InvalidURLError( unsupported query parameter `sslmode`)

### ISSUE THREAD

**Issue by mayulu** [elixir-ecto/ecto#2672]
Hi,

After I started a new phoenix project with `mix phx.new myproject`, `cd myproject`, and then modify the `config/dev.exs`, changed the database config part:
```
config :qbme, Qbme.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "xxx",
  password: "xxxxxxx",
  database: "myproject_dev",
  hostname: "localhost",
  pool_size: 10
```
And then run `mix ecto.create`, I got the error:
```
** (Ecto.InvalidURLError) invalid url postgres://xxx:xxxxxxxxx@127.0.0.1:5432/postgres?sslmode=disable, unsupported query parameter `sslmode`
```

### Environment
* Elixir version : 1.7.3
* phoenix version: 1.3.4
* Database and version (PostgreSQL):  10.5
* Ecto version : 2.2.10
* phoenix_ecto: 3.3.0
* Database adapter and version : postgrex-0.13.5
* Operating system: macOS 10.13.6

Anyone can give a glue?

Thanks

**Comment by josevalim** [comment]
You need to remove the ?sslmode=... part from your URL. Also, please don’t
use the issues tracker for questions/help, use Elixir Forum or Stack
Overflow were more people will be available to help you. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Oh, I am sorry. I see where the confusion comes from. You likely have the
DATABASE_URL environment variable set in your dev machine. If you see
lib/your_app/repo.ex, you can see that it uses the environment variable if
one is available. You can either clean up the env variable or remove the
“init” function from your repository.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
