### ISSUE TITLE
Validations don't clear existing errors

### ISSUE THREAD

**Issue by bencates** [elixir-ecto/ecto#2680]
### Environment

* Elixir version: 1.7.2
* Ecto version: 2.2.8

### Current behavior

```elixir
defmodule TestSchema do
  use Ecto.Schema
  embedded_schema do
    field :key, :string
  end
end

alias Ecto.Changeset

changeset =
  %TestSchema{}
  |> Changeset.change(%{})
  |> Changeset.validate_required(:key) # <= Changeset marked invalid here
  |> Changeset.put_change(:key, "value")
  |> Changeset.validate_required(:key)

changeset.valid? == false
changeset.errors == [key: {"can't be blank", [validation: :required]}]
```

### Expected behavior

Validations like `validate_required/3` should remove the previous error and, assuming there are no other errors, mark the changeset as valid again.

**Comment by fertapric** [comment]
In the given example, could be an option to first set the value of `:key` conditionally and then perform the `validate_required/3` validation? Having two `validate_required/3` over the same field in a changeset pipeline feels a bit weird to me. Semantically, it would mean that the value is not “required” after all 🙂

**Comment by josevalim** [comment]
This would be a breaking change too. There is nothing today requiring validation_required to come before all other validations, so removing any error once the field is there would certainly lead to bugs. The best solution in this case is to guarantee the data is in the proper shape before validating it.

**Comment by bencates** [comment]
The listed code snippet is drastically simplified, of course. The actual issue in our application is that when `TestSchema.changeset/2` returns an invalid changeset I am unable to repair it in the calling context.

A less minimized example:

```elixir
def create_purchase_order(attrs) do
  # `attrs` is raw user input. It may specify a PO Number or allow the accounting
  # system to generate one automatically. It may have either atom or string keys.

  # `:po_number` is a required field in the changeset (and a `NOT NULL column
  # in the underlying database). If the user did not specify one then the resulting
  # changeset will be invalid at this stage. Either way we want to extract an in
  # memory record to use as a parameter for the following cleanup work.
  changeset = PurchaseOrder.changeset(%PurchaseOrder{}, attrs)
  purchase_order = Changeset.apply_changes(changeset)

  # We then have to make an external API call to register the new PO with
  # our accounting system.
  {:ok, res} = AccountingSystem.create_purchase_order(purchase_order)

  # 
  changeset
  |> Changeset.put_change(:po_number, res["poNumber"])
  |> Changeset.validate_required(:po_number)
  |> Repo.insert!
end
```

**Comment by josevalim** [comment]
The problem is that if there is any other validation in `po_number` that failed, we can't just remove it. If in your application you can assume that all prior errors to `po_number` can be discarded, then I would rather manually go and delete the `po_number` errors.

We would also be glad to support a function such as `Ecto.Changeset.remove_errors(changeset, key)` that removes all errors for the given key. What do you think?

**Comment by bencates** [comment]
I'm not sure that removing only the error generated by the original `validate_required/3` call would be a breaking change.

The tuple in the error object appears to specify the validation type. Rerunning the validation wouldn't need to remove all the errors for the now-valid key, only those that match `{_, [validation: :required]}` (and similarly for the other built-in validations).

That said, explicitly removing any errors on the key would work as well.

I think I would still prefer for the validations to do this implicitly. It seems buggy to me to have any case where a given validation passes but nevertheless returns a changeset which reports that it failed. Plus leaving this in the validations would force me to be explicit about exactly what I was attempting to repair. Custom validations would need access to something like a `remove_errors/2` anyway to be able to emulate that behavior, though.

**Comment by josevalim** [comment]
> That said, explicitly removing any errors on the key would work as well.

We can try this direction as well because none of the validations are fixed once we change the value, even if they pass, so it isn't an issue only with required, but all other validations.

**Comment by floodico** [comment]
Maybe someone who comes across this will find it useful: 
```
def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields ++ @optional_fields)
    |> maybe_delete_previous_errors()
    |> validate_required(@required_fields)
  end

  defp maybe_delete_previous_errors(%Ecto.Changeset{valid?: true} = changeset), do: changeset

  defp maybe_delete_previous_errors(%Ecto.Changeset{changes: changes, errors: errors} = changeset) do
    changed_values_keys = Map.keys(changes)
    remaining_errors = Enum.reject(errors, fn {key, _} -> key in changed_values_keys end)

    %{changeset | errors: remaining_errors, valid?: remaining_errors == []}
  end
```
