### ISSUE TITLE
v2: usec:false does not truncate datetime representation

### ISSUE THREAD

**Issue by fenollp** [elixir-ecto/ecto#2681]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
`PG 9.6.6`
* Ecto version (mix deps): `v2.2.10`
* Database adapter and version (mix deps): `:postgrex, "0.13.5"`
* Operating system: `OSX 10.13.6`

### Current behavior

Using `usec: false` in my `@timestamps_opts`:

```elixir
# cat lib/schema.ex
defmodule EctoPanda.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema

      # Project-wide settings
      # See https://hexdocs.pm/ecto/Ecto.Schema.html#module-schema-attributes
      @timestamps_opts [
        # Use UTC instead of naive
        type: :utc_datetime,
        # Deactivate microseconds precision (for legcay API compatibility on dumps)
        #   Otherwise we'd get `2018-09-20T09:00:00.000000Z`
        #           instead of `2018-09-20T09:00:00Z`
        usec: false
      ]
    end
  end
end
```

When serializing a datetime defined with something along:
```
# model
    field(:revoked_at, :utc_datetime)
# migration
    add(:revoked_at, :utc_datetime)
```
I still get dates as `2018-09-20T09:00:00.000000Z`

### Expected behavior

When I expect instead: `2018-09-20T09:00:00Z`.

### What I tried

I thought `DateTime.utc_now() |> DateTime.truncate(:second)` in ./lib/ecto/schema.ex's `__timestamps__/2` would help but it doesn't. Is it something that has to do with cast/dump/load of the `utc_datetime + usec:false` type of v2?

We need to show only meaningful data in our API, right now this adds a few zeros that we'd prefer to not include.
Current workaround is to do the `truncate/2` call in the controllers/serialyzers.

**Comment by josevalim** [comment]
This is fixed in Ecto master (upcoming v3) where we introduce `_usec` types and totally truncate the `non_usec` ones. You can achieve similar behaviour in Ecto v2 by introducing a custom type and make sure you always truncate as you desire. :)
