### ISSUE TITLE
make modify work with ecto.rollback

### ISSUE THREAD

**Issue by clouds56** [elixir-ecto/ecto#2682]
* Elixir version (elixir -v): 1.7.0
* Database and version: psql (PostgreSQL) 10.4
* Ecto version (mix deps): ecto 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: macOS 10.13.3

see also https://github.com/elixir-ecto/ecto/issues/858,
is it possible to make some modify to `modify` function (like add some option called `:from`) in order to support rollback/down?

```elixir
def change do
  alter table(:user) do
    # when down the change, just read it as "modify :username, :integer"
    # if not supplied with the :from option, just refuse rollback like the behavior now
    modify :username, :string, from: :integer
  end
end
```

otherwise I have to use `execute` for every single modify

```elixir
# lost the generalization and may not work in some database
execute """ALTER TABLE "user" ALTER COLUMN "username" TYPE VARCHAR""",
        """ALTER TABLE "user" ALTER COLUMN "username" TYPE INT"""
```

(and thus function `modify` would be never useful for me)

not to mention it is hard to hand write `execute` command like

```elixir
modify :user_id, references(:users, type: :string), from: :string
```

I really need `ecto.rollback`, but I won't write `down` unless `modify` is the only action in `change` (otherwise, I'd have to revert every action in `down` even if it could be automatically `down`)

**Comment by josevalim** [comment]
Sounds good to me. Can you please send a pull request?
