### ISSUE TITLE
`Ecto.Migration.index/3` silently mishandles multiple `:where` clauses

### ISSUE THREAD

**Issue by nathanl** [elixir-ecto/ecto#2690]
### Environment

* Elixir version (elixir -v): Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.2
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): Postgrex 0.13.5
* Operating system: MacOS High Sierra (10.13.6)

## Problem

`Ecto.Query.from` allows multiple `where:` clauses. So it seems natural to use multiple `where:` clauses when creating an index with `Ecto.Migration`. However, doing so fails in a surprising way.

### Current behavior

This statement:

```elixir
    create(
      index(
        "seasons",
        :team_id,
        where: "started_at is not null",
        where: "ended_at is null",
        unique: true,
        name: "only_one_active_season_per_team"
      )
    )
```

...creates an index where only the second `where:` clause is used.

### Expected behavior

Either `index/3` should combine all `where:` clauses using `AND`, or it should raise an error when multiple `where:` clauses are given, suggesting that the user combine them.

**Comment by josevalim** [comment]
Given those are strings and not query expressions, I think we can detect and raise them. PR please? :)

**Comment by nathanl** [comment]
I'll try to make a PR for this in the next week or two.
