### ISSUE TITLE
It's not possible to know was changeset inserted or not on Upsert

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#2694]
### Environment

* Elixir version (elixir -v): 1.7.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10
* Ecto version (mix deps): master, commit bba34c5ba218537bf196630179e4934946ab94e0
* Database adapter and version (mix deps): 6cabc3b018cabc6e036e7d162414889a20785b96
* Operating system: MacOS

### Current behavior

Quote from Ecto.Repo docs:
> Now we can insert with the same title but do nothing on conflicts:
> ```elixir
> {:ok, ignored} = MyRepo.insert(%Post{title: "this is unique"}, on_conflict: :nothing)
> 
> assert ignored.id == nil
> ```

This way of determining was something inserted or not only works when you use structs, but it fails with changesets, here is pseudo-code:

```elixir
post = Post.changeset(%{"title" => "this is unique"})
{:ok, ignored} = MyRepo.insert(post, on_conflict: :nothing, returning: true)
assert ignored.id == # it's not nil any more, but a randomly generated UUID
```

I believe it’s because ID is generated when we turn changeset into schema right before inserting it, not sure why Ecto does not read the ID back though.

(My specific use case is inserting changeset via `Ecto.Multi.insert`, but it should not be relevant. Primary keys are set to `:binary_id, autogenerate: true`.)

### Expected behavior

A way to determine was changeset inserted or not.

cc @wojtekmach

**Comment by josevalim** [comment]
In cases like that we simply can't know because the database does not return us any information. So you need to have at least some field with read_after_writes set to true or let the database generate the UUID for you. You can also perform a separate read  but there is nothing "built-in".

**Comment by AndrewDryga** [comment]
Thank you, got it. As a workaround for people came from Google I'm removing `on_conflict` from `insert/2` and adding a unique constraint to the changeset. So I can read back inserted struct only when conflict occurred and proceed with loaded data.

**Comment by AndrewDryga** [comment]
@josevalim just to confirm, `returning: true` also doesn't help there? I thought it should read all the fields back? Similar to having `read_after_writes` set on all the fields.

**Comment by AndrewDryga** [comment]
@josevalim should not just override all fields in the returned schema? I'm not sure how to define the diff there because I do not get two copies of the data.

**Comment by josevalim** [comment]
>  should not just override all fields in the returned schema?

It should.

But if you want to know exactly what happened, then you need a before (before you call insert) and an after (the returned value) and at least one value that is guaranteed to change (it could be inserted_at).

**Comment by AndrewDryga** [comment]
> It should.

So in real life it does not, then I guess it is a real bug?

**Comment by josevalim** [comment]
I don't think the database will return anything in case of a failed insert. So you can check that by verifying that the created_at column didn't change.
