### ISSUE TITLE
Changing `has_many` association via `post_assoc` not committing to the database.

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#2701]
### Environment

Ecto 2.2.10
Elixir 1.7.3
macOS High Sierra 10.13.6

### Current behavior

Given:

```
defmodule EctoAssoc.User do
  use Ecto.Schema

  alias Ecto.Changeset
  alias EctoAssoc.{Avatar, Post}

  schema "users" do
    field(:name, :string)
    field(:email, :string)
    has_one(:avatar, Avatar, on_replace: :update)
    has_many(:posts, Post, on_replace: :delete)
  end

...
end
```

Changing an item in the `:posts` association in the `User` schema, acknowledges a change in the changeset, returns an updated struct, but nothing happens in the database:

```
iex(93)> u = Repo.get(User, 5) |> Repo.preload(:posts)

14:46:14.903 [debug] QUERY OK source="users" db=2.1ms
SELECT u0."id", u0."name", u0."email" FROM "users" AS u0 WHERE (u0."id" = $1) [5]

14:46:14.906 [debug] QUERY OK source="posts" db=2.3ms queue=0.1ms
SELECT p0."id", p0."header", p0."body", p0."lock_version", p0."user_id", p0."user_id" FROM "posts" AS p0 WHERE (p0."user_id" = $1) ORDER BY p0."user_id" [5]
%EctoAssoc.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  avatar: #Ecto.Association.NotLoaded<association :avatar is not loaded>,
  email: "john@company.com",
  id: 5,
  name: "John",
  posts: [
    %EctoAssoc.Post{
      __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
      body: nil,
      header: "My header",
      id: 9,
      lock_version: 1,
      tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
      user: #Ecto.Association.NotLoaded<association :user is not loaded>,
      user_id: 5
    },
    %EctoAssoc.Post{
      __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
      body: "The corals are wonderful.",
      header: "Beautiful sea",
      id: 2,
      lock_version: 1,
      tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
      user: #Ecto.Association.NotLoaded<association :user is not loaded>,
      user_id: 5
    }
  ]
}
iex(94)> u = u |> change |> put_assoc(:posts, [%Post{id: 2, header: "Marvellous sea"}])
#Ecto.Changeset<
  action: nil,
  changes: %{
    posts: [
      #Ecto.Changeset<action: :replace, changes: %{}, errors: [],
       data: #EctoAssoc.Post<>, valid?: true>,
      #Ecto.Changeset<action: :update, changes: %{}, errors: [],
       data: #EctoAssoc.Post<>, valid?: true>
    ]
  },
  errors: [],
  data: #EctoAssoc.User<>,
  valid?: true
>
iex(95)> u = Repo.update!(u)

14:46:15.914 [debug] QUERY OK db=1.0ms
begin []

14:46:15.919 [debug] QUERY OK db=4.7ms
DELETE FROM "posts" WHERE "id" = $1 [9]

14:46:15.921 [debug] QUERY OK db=1.9ms
UPDATE "posts" SET "user_id" = $1 WHERE "id" = $2 [5, 2]

14:46:15.924 [debug] QUERY OK db=2.0ms
commit []
%EctoAssoc.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  avatar: #Ecto.Association.NotLoaded<association :avatar is not loaded>,
  email: "john@company.com",
  id: 5,
  name: "John",
  posts: [
    %EctoAssoc.Post{
      __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
      body: nil,
      header: "Marvellous sea",
      id: 2,
      lock_version: 1,
      tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
      user: #Ecto.Association.NotLoaded<association :user is not loaded>,
      user_id: 5
    }
  ]
}
```
but in the database the header of post `id:2` did not change; only the other post was deleted as expected per the `on_replace` configuration.

I believe the changeset above

`#Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #EctoAssoc.Post<>, valid?: true>`

should have had its field as `changes: %{header: "Marvellous sea"}`, not as `changes: %{}`.

Also note what was sent to the database `UPDATE "posts" SET "user_id" = $1 WHERE "id" = $2 [5, 2] ` which does nothing ...

Another problem, don't know if related to this, happens when switching the order of the key value pairs from `%Post{id: 2, header: "Marvellous sea"}` to `%Post{header: "Marvellous sea", id: 2}`, in which case:

- the changesets resulting from the executions at lines "iex(94)" above and "iex(124)" below, are different;

- and, the returned post struct still has the old header, instead of "Marvellous sea" as above;

```
iex(123)> u = Repo.get(User, 5) |> Repo.preload(:posts)

14:48:04.034 [debug] QUERY OK source="users" db=1.1ms
SELECT u0."id", u0."name", u0."email" FROM "users" AS u0 WHERE (u0."id" = $1) [5]

14:48:04.035 [debug] QUERY OK source="posts" db=0.8ms queue=0.1ms
SELECT p0."id", p0."header", p0."body", p0."lock_version", p0."user_id", p0."user_id" FROM "posts" AS p0 WHERE (p0."user_id" = $1) ORDER BY p0."user_id" [5]
%EctoAssoc.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  avatar: #Ecto.Association.NotLoaded<association :avatar is not loaded>,
  email: "john@company.com",
  id: 5,
  name: "John",
  posts: [
    %EctoAssoc.Post{
      __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
      body: "The corals are wonderful.",
      header: "Beautiful sea",
      id: 2,
      lock_version: 1,
      tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
      user: #Ecto.Association.NotLoaded<association :user is not loaded>,
      user_id: 5
    }
  ]
}
iex(124)> u = u |> change |> put_assoc(:posts, [%Post{header: "Marvellous sea", id: 2}])
#Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #EctoAssoc.User<>,
 valid?: true>
iex(125)> u = Repo.update!(u)
%EctoAssoc.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  avatar: #Ecto.Association.NotLoaded<association :avatar is not loaded>,
  email: "john@company.com",
  id: 5,
  name: "John",
  posts: [
    %EctoAssoc.Post{
      __meta__: #Ecto.Schema.Metadata<:loaded, "posts">,
      body: "The corals are wonderful.",
      header: "Beautiful sea",
      id: 2,
      lock_version: 1,
      tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
      user: #Ecto.Association.NotLoaded<association :user is not loaded>,
      user_id: 5
    }
  ]
}
iex(126)>
```
and again, the post `id:2` did not have its header changed in the database.

Note in this case that there are no changes in the changeset, and no SQL was sent to the database on the update.

### Expected behavior

This is to have the post with `id:2` modified in the database, irrespective of the order of the keys in the `%Post{...}` map.

**Comment by josevalim** [comment]
This is expected behavior but our documentation does such a poor job of
explaining this that it is not surprising this is confusing. I will rework
the docs and clarify all of those cases.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by mguimas** [comment]
Thanks,
if you can, please, add it to version Ecto 3.0 (I believe this is the next one, right?)

**Comment by mguimas** [comment]
@josevalim I have read the docs updates and have these comments:

1) Regarding 

>  This function is used to work with associations as a whole. For example,
  if a Post has many Comments, it allows you to replace, change or move all
  comments at once. If your goal is to simply add a new comment to a post,
  then it is preferred to do so manually, as we will describe later in the
  "Example: Adding a comment to a post" section.

what does it mean to "move all comments" ? What does "move" mean?

2) This sentence

> A map or keyword list can be given to update an existing association as long as they have matching primary keys.

seems that `put_assoc` can be used to update a single associated entity, which is contraditory with this

> This function is used to work with associations as a whole.

Overall, I find the `put_assoc` function too much complex to keep exactly what it does in the mind of the developer ... For example, it does one thing when maps or keyword lists are passed, and does another when changesets or structs are passed. This is too complex.

**Comment by josevalim** [comment]
> seems that put_assoc can be used to update a single associated entity, which is contraditory with this

Why is that sentence contradictory? You still need to pass the maps/keywords for **all entries**. Or do you mean the wording "an existing association" gives the impression it is for a single one?

**Comment by mguimas** [comment]
@josevalim Yes, it gives that impression.

**Comment by mguimas** [comment]
Sometimes the term "association" is used to mean one entity, other times means the association as a whole. This problem appears here and there throughout Ecto docs.

**Comment by josevalim** [comment]
> Sometimes the term "association" is used to mean one entity, other times means the association as a whole. This problem appears here and there throughout Ecto docs.

We would love a PR that unifies this usage.
