### ISSUE TITLE
mix ecto.create error

### ISSUE THREAD

**Issue by rizafahmi** [elixir-ecto/ecto#272]
I tried to run `mix ecto.create Repo`, I've got an error:

```
** (Mix.Error) The database for repo Repo couldn't be created, reason given: psql: FATAL:  database "riza" does not exist
```

The repo is this:

```
defmodule PhoenixJobsThree.Repo do
    use Ecto.Repo, adapter: Ecto.Adapters.Postgres

    def conf do
      parse_url "ecto://riza:secret@localhost/phoenix_database"
    end

    def priv do
      app_dir(:phoenix_jobs, "priv/repo")
    end
end
```

It's looks like it was read `:username` as `:database`.

I used Ecto version 0.2.3

**Comment by whatyouhide** [comment]
@ericmj I'm still getting this error with v0.7.1. I'm not sure if it has been fixed though!

**Comment by josevalim** [comment]
It is fixed in master, I accidentally broke it :(

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by whatyouhide** [comment]
Works if I pull from master, thanks! :heart:
