### ISSUE TITLE
Missing error metadata on invalid association

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#2722]
Ref: https://elixirforum.com/t/problem-with-phoenix-and-errorhelpers/16979/12

### Environment

* Ecto version (mix deps): master

### Current behavior

```elixir
  # test/ecto/repo/belongs_to_test.ex
  test "bad assoc" do
    changeset =
      %MySchema{assoc: :bad}
      |> Ecto.Changeset.change()

    {:error, changeset} = TestRepo.insert(changeset)
    assert [assoc: {"is invalid", _}] = changeset.errors
  end
```

this test fails because `changeset.errors` are `[assoc: "is invalid"]`
Worth mentioning that if we put the assoc through `put_assoc` then it works as expected:

```elixir
    changeset =
      %MySchema{}
      |> Ecto.Changeset.change()
      |> Ecto.Changeset.put_assoc(:assoc, :bad)

    {:error, changeset} = TestRepo.insert(changeset)
    assert [assoc: {"is invalid", [type: :map]}] = changeset.errors
```

### Expected behavior

errors should be: `[assoc: {"is invalid", [type: :map]}]`, same as when using `put_assoc`.

**Comment by qcam** [comment]
I can give this a try if you haven't started on it @wojtekmach :).

**Comment by wojtekmach** [comment]
@qcam please go ahead :)
