### ISSUE TITLE
Updated to Ecto 2.2.11 and wrong microseconds attempt with timestamps

### ISSUE THREAD

**Issue by pedromvieira** [elixir-ecto/ecto#2727]
Just upgraded to Ecto 2.2.11, no code change in our changesets.

### Environment

Elixir 1.7.2
Erlang 21.0.5

### Current behavior

`** (FunctionClauseError) no function clause matching in Ecto.Schema.__timestamps__/2

    The following arguments were given to Ecto.Schema.__timestamps__/2:

        # 1
        :naive_datetime

        # 2
        :microseconds

    Attempted function clauses (showing 4 out of 4):

        def __timestamps__(:naive_datetime, :second)
        def __timestamps__(:naive_datetime, :microsecond)
        def __timestamps__(type, :second)
        def __timestamps__(type, :microsecond)`

### Expected behavior

Changeset working as previous.

**Comment by pedromvieira** [comment]
Just downgrade to 2.2.10 and it works.

**Comment by josevalim** [comment]
@pedromvieira can you please upgrade to 2.2.11 back again, remove _build, and let us know if the error persists? It is weird we are passing `:microseconds` there when there is no occurrence of `:microseconds` in the codebase.

**Comment by pedromvieira** [comment]
> @pedromvieira can you please upgrade to 2.2.11 back again, remove _build, and let us know if the error persists? It is weird we are passing `:microseconds` there when there is no occurrence of `:microseconds` in the codebase.

OK. After upgrade back again to 2.2.11 and cleaning _build on my umbrella I confirm that it's working as intended again. Thanks @josevalim

**Comment by josevalim** [comment]
@pedromvieira thanks for double checking. this actually means it is a bug in Elixir, it seems we did not track dependnecies properly. I will investigate.

**Comment by stevedomin** [comment]
@josevalim fyi, just ran into the same issue in an umbrella application

**Comment by josevalim** [comment]
@stevedomin if you have a way to reproduce it, then let me know :) Otherwise, is cleaning `_build` enough to fix the bug for you?

**Comment by stevedomin** [comment]
Cleaning `_build` did fix the issue. Did it before I posted here so no repro case unfortunately...

**Comment by janpieper** [comment]
We upgraded to 2.2.11 and had the mentioned error for one of our schemas. All others worked like before.

Cleaning `_build` did not work for us! We were forced to downgrade to 2.2.10.

```
$ iex --version
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

IEx 1.7.3 (compiled with Erlang/OTP 21)
```
