### ISSUE TITLE
Ecto Schema assumes that a changeset/2 function will be provided with no warning when one isn't provided.

### ISSUE THREAD

**Issue by coby-spotim** [elixir-ecto/ecto#2734]
### Environment

* Elixir version (elixir -v): 1.6.6
* Database and version: PostgreSQL 9.4
* Ecto version (mix deps): latest version
* Database adapter and version (mix deps): latest version of postgrex
* Operating system: Mac OS High Sierra

### Current behavior

When creating an Ecto Schema, there is no warning during compilation about not including a `changeset/2` function. It is assumed that every schema will have one, but none is provided by default. This is problematic when using `cast_assoc` as it expects a `changeset/2` function in your schema module.

### Expected behavior

During compilation, provide a warning for the user to see that they do not have a `changeset/2` function in their module. Optionally, inject a basic `changeset/2` function.

This behaviour is suggested as it is similar to the behaviour of GenServer with regards to the `init` function.

**Comment by josevalim** [comment]
The changeset/2 function is definitely not required. We shouldn't always define it only in the off chance someone may use `cast_assoc/2`. I would rather make sure that we raise a good error message on cast_assoc/2 if changeset/2 is not there rather then define it upfront. Thanks!

**Comment by josevalim** [comment]
It seems we already raise a proper error message in those cases: https://github.com/elixir-ecto/ecto/blob/9785114f545525cc57a89f3726b979619cbf3dc5/lib/ecto/changeset.ex#L772-L795

**Comment by coby-spotim** [comment]
@josevalim Thanks for the quick answer!

I'd like to discuss this a bit further if you don't mind, as I'm not entirely sure if I agree with this.

While raising a good error is also important, I don't think it's explicit enough to the user. I believe there should be a warning for this in compilation, since then the user at least has some sort of knowledge of this before runtime, and it's a more explicit way of letting them know, otherwise they wouldn't know until runtime when it happens.

Defining it automatically might not be the best idea (I just got that idea from the `gen_server.ex` implementation), but at least it should be something that is apparent to the user before deploying and running code (disregarding tests as they don't always catch everything).

**Comment by coby-spotim** [comment]
I apologize if I come off as rude and ignorant, I'm new here, just getting my feet wet for the first time!

**Comment by josevalim** [comment]
We can't check at compile time because we don't know if a schema is using cast_assoc or not. And I am worried about imposing a tax on all schemas (the tax being defining changeset/2) when only a very small part of them will actually use `changeset/2`. So I think the way to go is with docs and good error messages, I don't think we can move this to compile time.

PS: Don't worry, you are not coming off as rude or ignorant. :)

**Comment by josevalim** [comment]
No because you are not required to use `cast_assoc` if you are using has_one or has_many. There are other ways to handle associations, such as `build_assoc` or `put_assoc`.

**Comment by coby-spotim** [comment]
Alright, that makes sense!

If there would be a way to check at compile time if someone is using `cast_assoc`, then I would say that there should definitely be a warning there, but for now I agree that the assumption doesn't hold.

I appreciate the help!

(also, I look forward to speaking to you soon in other repos as well! my team and I are working hard on a lot of systems in Elixir and we've already found some interesting issues. we're preparing example projects to provide right now, so hopefully soon you'll be hearing more from me!)

**Comment by josevalim** [comment]
Glad to help!
