### ISSUE TITLE
source and query time not included in Logger metadata

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto#2741]
We have queries that look like this:

`QUERY OK source="property_listing_prices" db=0.8ms SELECT p0."id",`

Unfortunately neither `source` nor `db` are added to the actual Logger metadata. Since we use a custom logging backend, this makes it difficult to search for queries to a certain database or queries that took over a certain amount of time.

**Comment by josevalim** [comment]
Ecto has an extensible logging mechanism. You can replace our own logger by your own and log any data you want with whatever metadata you want. :) See `:loggers` configuration in the released docs in your Ecto.Repo configuration.
