### ISSUE TITLE
Allow for beter errors for `Ecto.Type`

### ISSUE THREAD

**Issue by tcoopman** [elixir-ecto/ecto#2746]
At the moment, you can only pass `:error` when a `cast` fails with `Ecto.Type`. 

It would be really useful to be able to pass custom error messages. For example `{:error, "some custom error message}`, to help finding out why something failed.

**Comment by wojtekmach** [comment]
I agree something like this would be nice, I wrote a proposal here: https://groups.google.com/forum/#!topic/elixir-ecto/amPob2hSjwA.

**Comment by josevalim** [comment]
@tcoopman could you please send a pull request based on @wojtekmach's proposal? We want to release a RC today but if the PR is sent soon, then it can the make final release.
