### ISSUE TITLE
Doc instructs the reader to use a version of ecto_sql that is not available on Hex

### ISSUE THREAD

**Issue by marcofognog** [elixir-ecto/ecto#2748]
### Environment

* Elixir version (elixir -v): Elixir 1.7.3 (compiled with Erlang/OTP 19)

### Current behavior

The Getting Started doc instructs the reader to use a version of ecto_sql that is not available on Hex, in the lines:

```
defp deps do
  [
    {:ecto_sql, "~> 3.0"},
    {:postgrex, ">= 0.0.0"}
  ]
end
```

https://github.com/elixir-ecto/ecto/blob/master/guides/Getting%20Started.md

### Current behavior

Runing mix deps.get results in:

```
** (Mix) No matching version for ecto_sql ~> 3.0 (from: mix.exs) in registry

While there is no package matching the requirement above, there are pre-releases available:

  * 3.0.0-rc.0

In order to match any of them, you need to include the "-pre" suffix in your requirement, where "pre" is one of the suffixes listed above.
```

### Expected behavior

Following the instruction should resolve the dependencies successfuly.

**Comment by josevalim** [comment]
This is temporary for now but it will be addressed as soon final is out. :) Which is likely the next release anyway, thanks for letting us know! :heart:

**Comment by idyll** [comment]
@josevalim it looks like Ecto 3.0.0 has been released. Will a release for EctoSQL follow shortly? :)

**Comment by josevalim** [comment]
@idyll unfortunately it is blocked on mariaex, so we are waiting for it.

**Comment by nathany** [comment]
related: https://github.com/xerions/mariaex/pull/244

**Comment by josevalim** [comment]
ecto_sql is out. :)
