### ISSUE TITLE
README deps not quite accurate.

### ISSUE THREAD

**Issue by Shmink** [elixir-ecto/ecto#2755]
Ecto 3.0 dependancy not working as README would suggest. 

```elixir
defp deps do
  [
    {:ecto_sql, "~> 3.0"},
    {:postgrex, ">= 0.0.0"}
  ]
end
```

results are of course that there is no matching version because `~>` doesn't do pre-releases if I understand correctly.

**Comment by josevalim** [comment]
Thanks! Dup of #2748.
