### ISSUE TITLE
Changelog update for Mix.Ecto.migrations_path/1

### ISSUE THREAD

**Issue by kipcole9** [elixir-ecto/ecto#2763]
## Changelog update for backward incompatible API change

The function `migrations_path/1` has moved from `Mix.Ecto` to `Ecto.Migrator`.  This is understandable since `ecto 3` shouldn't have database knowledge as that's moved to `ecto_sql`.

### Backwards incompatible changes

* [Mix.Ecto] `Ecto.migrations_path/1` has been removed from the `Mix.Ecto` module and added to the `Ecto.Migrator` module in the `ecto_sql` package.

**Comment by josevalim** [comment]
Thanks @kipcole9! Note that [Mix.Ecto was private](https://github.com/elixir-ecto/ecto/blob/v2.2.11/lib/mix/ecto.ex#L3), which is why we didn't list this change in the CHANGELOG.

**Comment by kipcole9** [comment]
Thanks José.  May I assume `Ecto.Migrator.migrations_path/1` is public?  I see nothing in the module to suggest otherwise and being consistent about where to generate migrations for libs is very helpful.

I try to use only public API's but seems I regularly step over the line unknowingly.  I have interpreted an `@doc` on a `def` function as public - is that the wrong assumption?

**Comment by josevalim** [comment]
Oh, i see. If you have `@moduledoc false` in a module, then all functions in that module are private, regardless of `@doc`. If in doubt, you can consult the online docs. `Ecto.Migrator.migrations_path` is pubic though :+1:.

**Comment by nathany** [comment]
How should a library find the migrations_path for Ecto 2.x and 3.x?

See https://github.com/ueberauth/guardian_db/issues/93

**Comment by josevalim** [comment]
The suggested Ecto.Migrator.migration_path should work on both.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by nathany** [comment]
Doesn't work for me.

**Comment by josevalim** [comment]
Ah, you are correct, sorry.

i think you can check the Ecto version or if use code.ensure_loaded? and
function_exported? to see if the migrator function exists accordingly.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by nathany** [comment]
Thanks @josevalim.

Example of resolving this in another library (as pointed out on Slack):
https://github.com/kipcole9/money/commit/c2766dece7f241f25b86999876d756d7b7d7a4be
