### ISSUE TITLE
API proposal for common table expressions

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#2769]
Since keyword queries in Ecto start with `from`, we would need to have a longer discussion on how to best integrate CTE into the keyword query syntax. For this reason, we will ship v3.0 only with support for the call/pipe based query syntax.

There will be two new functions:

The first one is `with_cte(query, cte_name, as: query_of_fragment)`. Note `cte_name` must be a string at compile time. The `as: option` also need to be given at compile time and it is either an interpolated query or a fragment. Example:

    some_cte_query = from ...
    with_cte(my_query, "category_posts", as: ^some_cte_query)

The fragment will allow us to support inserts and the like:

    with_cte(my_query, "category_posts", as: fragment("INSERT ..."))

This means `with_cte` is a macro and it cannot be a function. You can look at `union_all` in master as a reference, as it was recently changed to require query interpolation (although it doesn't support fragments, yet).

We will also add a `recursive_ctes(query)` function, that simply marks the query as recursive.

Internally we will define a new struct, called WithExpr. It has two fields, a recursive field as a boolean, and a queries field that keeps a list of tuples with the first element as the name and the second element is either a QueryExpr (in case of fragments) or a Query itself.

/cc @feymartynov

**Comment by feymartynov** [comment]
Ok. I'm going to implement it.

**Comment by hauleth** [comment]
However it must be mentioned that second argument will be used as table name, so you must be extremely careful when using this feature to not introduce recursive queries without stop parameter or to not shadow existing tables, otherwise you can end with strange errors.

**Comment by josevalim** [comment]
@hauleth that's a very good point and we need to make it VERY explicit in the docs - it is the same with SQL. We also need to mention in the docs how to cast the CTE results to an existing schema, such as `from p in {"table_from_cte", Foo}`.

**Comment by hauleth** [comment]
The last one isn't that needed, as there is already information that you can use `{"table_name", Foo}` as a query source. It is worth adding anyway though. My main gripe comes from the fact that it can change behaviour of other "hidden" functions like `assoc/2` but it will change them only if the schema do not define `prefix`. So there is a lot of "ifs" in the process.

**Comment by josevalim** [comment]
Closing in favor of the PR.
