### ISSUE TITLE
Strange performance degradation over repeated queries

### ISSUE THREAD

**Issue by waffleau** [elixir-ecto/ecto#2771]
### Environment

Elixir: `1.7.3`
Database: `PostgreSQL 10.5`
Ecto version: `2.2.11 (via phoenix_ecto)`
DB adapter: `postgrex 0.13.5`
OS: `OSX 10.13.6`

### Current behavior

I've run into a strange issue with query performance. I think this may be related to Ecto, but I'm having a hard to making sense of it, so please redirect me if I'm in the wrong place.

I've got a table that contains about 82,000 rows, and a query that returns a small subset. After booting Phoenix, I get this performance for repeated executions of the same query:

`[debug] [18:12:02.059] QUERY OK source="engagements" db=19.4ms decode=1.2ms`
`[debug] [18:12:26.821] QUERY OK source="engagements" db=15.0ms decode=2.3ms`
`[debug] [18:12:29.674] QUERY OK source="engagements" db=8.7ms decode=2.2ms`
`[debug] [18:12:31.277] QUERY OK source="engagements" db=8.8ms decode=1.1ms`
`[debug] [18:12:32.887] QUERY OK source="engagements" db=8.7ms decode=2.6ms`
`[debug] [18:13:22.482] QUERY OK source="engagements" db=8.4ms decode=2.2ms`
`[debug] [18:13:33.722] QUERY OK source="engagements" db=9.5ms decode=1.0ms`
`[debug] [18:13:47.186] QUERY OK source="engagements" db=8.5ms decode=2.2ms`
`[debug] [18:14:02.293] QUERY OK source="engagements" db=8.4ms decode=2.4ms`
`[debug] [18:14:12.637] QUERY OK source="engagements" db=9.5ms decode=2.2ms`
`[debug] [18:14:27.575] QUERY OK source="engagements" db=297.0ms decode=1.3ms`
`[debug] [18:14:38.714] QUERY OK source="engagements" db=309.5ms decode=2.3ms`
`[debug] [18:14:49.700] QUERY OK source="engagements" db=326.6ms decode=2.4ms`

For some reason, on the 11th attempt, performance degrades massively and never recovers. I'm having difficulty pinpointing where exactly in the stack the issue is.

The generated SQL looks something like this (excuse the noise on the ID clause):
```sql
SELECT 
    distinct on (post_id) * 
FROM 
    engagements 
WHERE 
    post_id = ANY(ARRAY[30783,31047,31006,31182,31131,30973,33910,30994,33849,30894,30947,30980,30606,30551,31066,30661,30581,30901,31061,30583,31234,31236,30757,30892,31216,31089,31104,30562,30987,37307,30972,30587,31037,31029,30592,33958,31430,30963,30594,30916,31033,33955,31062,30930,33917,33957,31077,30806,31153,30899,33950,30546,30658,31043,31008,31152,27286,30572,33954,30881,30948,30974,30691,30998,33855,31032,33857,33842,30919,31433,30566,31071,33856,33845,33948,31460,30895,33926,30663,33919,30900,33892,31070,31304,30920,31057,33915,30903,33930,30734,30591,30891,31470,30893,30803,31002,33939,31482,30946,37308,31408,33956,31173,31405,30960,31294,33854,30598,30941,31266,31055,31019,33912,31014,30807,33938,30897,31235,30944,33904,33913,30786,31409,30898,30604,30825,33914,35247,36954,27549,31677,36057,37156,35672,34615,31970,35249,35231,37176,32590,35244,33872,35304,34155,35003,35298,35029,35256,28436,36232,28780,32023,35223,37169,35228,34655,34717,32163,35745,34162,28899,32743,35790,34080,34654,35772,29093,35250,35232,29307,35074,33043,35793,29388,35240,36201,34661,35778,28737,34656,35791,34055,35252,35005,35243,35128,34932,36172,33145,34081,32711,35225,35255,35794,35226,35316,28949,33025,28964,36002,29104,35948,35132,35246,31523,35581,35238,35257,34645,34630,35629,28822,35245,29137,35282,35587,34110,32866,28838,35275,33196,28253,36055,34052,35801,35242,35626,28594,35269,36205,28150,35420,34681,35747,35220,35305,36060,35673,36059,34077,35424,29089,34277,31625,29117,32123,32899,32904,35310,29076,34991,34076,36382,33565,32750,35040,28977,35682,35253,36056,27815,35030,34617,32728,34795,36380,35227,28892,34815,35077,32010,33633,35229,32147,31322,35251,35179,35241,35340,29261,35617,36371,36001,28005,33462,35292,29448]::int[]) and 
    date >= '2018-09-01' and 
    date <= '2019-03-01' 
ORDER BY 
    post_id, date DESC;
```

And the `explain analyze`:

```sql
 Unique  (cost=2989.66..2998.20 rows=1580 width=93) (actual time=4.905..5.349 rows=282 loops=1)
   ->  Sort  (cost=2989.66..2993.93 rows=1708 width=93) (actual time=4.902..5.043 rows=1571 loops=1)
         Sort Key: post_id, date DESC
         Sort Method: quicksort  Memory: 269kB
         ->  Bitmap Heap Scan on engagements  (cost=933.77..2897.95 rows=1708 width=93) (actual time=2.413..3.666 rows=1571 loops=1)
               Recheck Cond: ((post_id = ANY ('{30783,31047,31006,31182,31131,30973,33910,30994,33849,30894,30947,30980,30606,30551,31066,30661,30581,30901,31061,30583,31234,31236,30757,30892,31216,31089,31104,30562,30987,37307,30972,30587,31037,31029,30592,33958,31430,30963,30594,30916,31033,33955,31062,30930,33917,33957,31077,30806,31153,30899,33950,30546,30658,31043,31008,31152,27286,30572,33954,30881,30948,30974,30691,30998,33855,31032,33857,33842,30919,31433,30566,31071,33856,33845,33948,31460,30895,33926,30663,33919,30900,33892,31070,31304,30920,31057,33915,30903,33930,30734,30591,30891,31470,30893,30803,31002,33939,31482,30946,37308,31408,33956,31173,31405,30960,31294,33854,30598,30941,31266,31055,31019,33912,31014,30807,33938,30897,31235,30944,33904,33913,30786,31409,30898,30604,30825,33914,35247,36954,27549,31677,36057,37156,35672,34615,31970,35249,35231,37176,32590,35244,33872,35304,34155,35003,35298,35029,35256,28436,36232,28780,32023,35223,37169,35228,34655,34717,32163,35745,34162,28899,32743,35790,34080,34654,35772,29093,35250,35232,29307,35074,33043,35793,29388,35240,36201,34661,35778,28737,34656,35791,34055,35252,35005,35243,35128,34932,36172,33145,34081,32711,35225,35255,35794,35226,35316,28949,33025,28964,36002,29104,35948,35132,35246,31523,35581,35238,35257,34645,34630,35629,28822,35245,29137,35282,35587,34110,32866,28838,35275,33196,28253,36055,34052,35801,35242,35626,28594,35269,36205,28150,35420,34681,35747,35220,35305,36060,35673,36059,34077,35424,29089,34277,31625,29117,32123,32899,32904,35310,29076,34991,34076,36382,33565,32750,35040,28977,35682,35253,36056,27815,35030,34617,32728,34795,36380,35227,28892,34815,35077,32010,33633,35229,32147,31322,35251,35179,35241,35340,29261,35617,36371,36001,28005,33462,35292,29448}'::integer[])) AND (date >= '2018-07-30'::date) AND (date <= '2018-10-20'::date))
               Heap Blocks: exact=635
               ->  Bitmap Index Scan on engagements_post_id_date_desc_index  (cost=0.00..933.35 rows=1708 width=0) (actual time=2.241..2.242 rows=1571 loops=1)
                     Index Cond: ((post_id = ANY ('{30783,31047,31006,31182,31131,30973,33910,30994,33849,30894,30947,30980,30606,30551,31066,30661,30581,30901,31061,30583,31234,31236,30757,30892,31216,31089,31104,30562,30987,37307,30972,30587,31037,31029,30592,33958,31430,30963,30594,30916,31033,33955,31062,30930,33917,33957,31077,30806,31153,30899,33950,30546,30658,31043,31008,31152,27286,30572,33954,30881,30948,30974,30691,30998,33855,31032,33857,33842,30919,31433,30566,31071,33856,33845,33948,31460,30895,33926,30663,33919,30900,33892,31070,31304,30920,31057,33915,30903,33930,30734,30591,30891,31470,30893,30803,31002,33939,31482,30946,37308,31408,33956,31173,31405,30960,31294,33854,30598,30941,31266,31055,31019,33912,31014,30807,33938,30897,31235,30944,33904,33913,30786,31409,30898,30604,30825,33914,35247,36954,27549,31677,36057,37156,35672,34615,31970,35249,35231,37176,32590,35244,33872,35304,34155,35003,35298,35029,35256,28436,36232,28780,32023,35223,37169,35228,34655,34717,32163,35745,34162,28899,32743,35790,34080,34654,35772,29093,35250,35232,29307,35074,33043,35793,29388,35240,36201,34661,35778,28737,34656,35791,34055,35252,35005,35243,35128,34932,36172,33145,34081,32711,35225,35255,35794,35226,35316,28949,33025,28964,36002,29104,35948,35132,35246,31523,35581,35238,35257,34645,34630,35629,28822,35245,29137,35282,35587,34110,32866,28838,35275,33196,28253,36055,34052,35801,35242,35626,28594,35269,36205,28150,35420,34681,35747,35220,35305,36060,35673,36059,34077,35424,29089,34277,31625,29117,32123,32899,32904,35310,29076,34991,34076,36382,33565,32750,35040,28977,35682,35253,36056,27815,35030,34617,32728,34795,36380,35227,28892,34815,35077,32010,33633,35229,32147,31322,35251,35179,35241,35340,29261,35617,36371,36001,28005,33462,35292,29448}'::integer[])) AND (date >= '2018-07-30'::date) AND (date <= '2018-10-20'::date))
 Planning time: 2.502 ms
 Execution time: 5.571 ms
(11 rows)
```

My initial thought was that I'm doing the wrong thing with my query, but the query time in `psql` is stable over any number of requests. Killing off phoenix and starting it again however will restart the degradation pattern.

I've run a `vacuum analyze`, and I only see this problem on this one particular table. Any help figuring out why performance is dropping would be much appreciated, even if it's just pointing me towards areas of investigation.

**Comment by josevalim** [comment]
Is it always after 10? If so, what is your pool size? What if you increase
and reduce the pool size? Does that affect the results?

Also, how are you running those queries? If you run each query in a
separate process by using Task.async(fn-> run_query(); :ok end) |>
Task.await, does it change the results too?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by waffleau** [comment]
Wow, thanks for the quick reply!

I tried tweaking the pool size, and it's definitely correlated. It happens after `pool_size * 5` requests. Any ideas why this might be the case?

Using `Task.async` has no effect.

**Comment by josevalim** [comment]
@waffleau would you be wiling to give Ecto 3.0 a try? It is currently in rc, you can read more about it here: https://elixirforum.com/t/ecto-3-0-rc-is-out-and-stable-api/17306

I am not sure why this is happening, but I am wondering if it has been fixed. @fishcakez may know better.

**Comment by josevalim** [comment]
Hi @waffleau, @fishcakez is thinking this could be related to the query planning in PG. If you build the query by hand and send it twice using `Repo.query!(sql, [])` do you see the same issue? IF so, what happens if you replace the `post_id = ANY(ARRAY[])` by a `post_id IN ()`?

**Comment by waffleau** [comment]
I tried updating to Ecto 3.0 and changing to an `id in ()` query and got the same results. I took the raw SQL as in the first post and tried it with `Repo.query` and didn't see the problem however. 

This is a little confusing though, as the raw SQL I pasted initially I obtained in the first place by copying the query that Ecto had planned:

```sql
SELECT DISTINCT ON (e0."post_id") e0."*" FROM "engagements" AS e0 WHERE (e0."date" >= $1) AND (e0."date" <= $2) AND (e0."post_id" = ANY($3)) ORDER BY e0."post_id", e0."date" DESC [{2018, 7, 30}, {2018, 10, 20}, [30783, 31047, 31006, 31182, 31131, 30973, 33910, 30994, 33849, 30894, 30947, 30980, 30606, 30551, 31066, 30661, 30581, 30901, 31061, 30583, 31234, 31236, 30757, 30892, 31216, 31089, 31104, 30562, 30987, 37307, 30972, 30587, 31037, 31029, 30592, 33958, 31430, 30963, 30594, 30916, 31033, 33955, 31062, 30930, 33917, 33957, 31077, ...]] 
```

**Comment by josevalim** [comment]
@waffleau sorry, do you mean that updating to Ecto 3.0 made no difference?

>  I took the raw SQL as in the first post and tried it with Repo.query and didn't have the problem however.

Can you post the exact commands you tried with Repo.query? Basically, I think we need to test two different scenarios. One where all of the IDs are directly in the query and another where the IDs are passed as paraemter, and see if any of them trigger the behaviour.

**Comment by waffleau** [comment]
That's correct, no difference with Ecto 3.0.

I initially ran the Repo.query as a pure string, but your comment has clued me in to try it with passed params. I didn't experience the performance drop when doing this. The exact query:

```sql
sql = """
SELECT DISTINCT ON (e0."post_id") e0.*
FROM "engagements" AS e0
WHERE (e0."date" >= $1) AND (e0."date" <= $2) AND (e0."post_id" = ANY($3))
ORDER BY e0."post_id", e0."date" DESC
"""

from_date = {2018, 7, 30}
to_date = {2018, 10, 20}
post_ids = [...] # big list, omitted here

Enum.each(1..100, fn index ->
   Repo.query(sql, [from_date, to_date, post_ids])
end)
```

**Comment by josevalim** [comment]
That's very weird. What if you do something like this:

    {:ok, pid} = Postgrex.start_link(YourApp.Repo.config)
    {:ok, query} = Postgrex.prepare(pid, "hello", sql)
    Postgrex.execute(pid, query, [from_date, to_date, post_ids])

If you do the execute a couple times, is it enough to reproduce the issue?

**Comment by waffleau** [comment]
Using the direct postgres execution, I do run into the error after five requests:

```
[info] [09:50:25.102] [Attempt # 1] Benchmark total - 131ms 
[info] [09:50:25.116] [Attempt # 2] Benchmark total - 14ms 
[info] [09:50:25.129] [Attempt # 3] Benchmark total - 13ms 
[info] [09:50:25.143] [Attempt # 4] Benchmark total - 13ms 
[info] [09:50:25.156] [Attempt # 5] Benchmark total - 13ms 
[info] [09:50:25.486] [Attempt # 6] Benchmark total - 330ms 
[info] [09:50:25.806] [Attempt # 7] Benchmark total - 319ms 
[info] [09:50:26.120] [Attempt # 8] Benchmark total - 314ms 
[info] [09:50:26.446] [Attempt # 9] Benchmark total - 325ms 
```

**Comment by fishcakez** [comment]
@waffleau see the notes section in https://www.postgresql.org/docs/10/static/sql-prepare.html#SQL-PREPARE-NOTES

**Comment by josevalim** [comment]
> Does this mean my best bet is opening an issue the postgrex library?

As @fishcakez posted, I actually think this is related to Postgres. You could try testing this in another language that talks to Postgres, using the same queries and parameters, but it is most likely Postgres doing a bad choice during planning/execution.

**Comment by waffleau** [comment]
Thanks for your help @josevalim and @fishcakez. I'll close this issue and continue working my way down the stack.
