### ISSUE TITLE
elixir_ls compile issue

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#2772]
### Environment

* Elixir version (elixir -v): 1.7.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 10
* Ecto version (mix deps): 3.0.0-rc.1
* Database adapter and version (mix deps): postgrex 0.14-rc.1
* Operating system: Mac OS X

### Current behavior

```
== Compilation error in file lib/ecto/repo/queryable.ex ==
** (UndefinedFunctionError) function Ecto.Query.Builder.escape_binding/3 is undefined or private. Did you mean one of:

      * escape_binding/2

    Ecto.Query.Builder.escape_binding({:__block__, [line: 361], [{:=, [line: 361], [{:query, [line: 361], Ecto.Query.Builder}, {:query, [line: 361], nil}]}, {{:., [line: 361], [Ecto.Query.Builder.From, :apply]}, [line: 361], [{:query, [line: 361], Ecto.Query.Builder}, 1]}]}, [x: 0], %Macro.Env{aliases: [{Queryable, Ecto.Queryable}, {Query, Ecto.Query}, {Planner, Ecto.Query.Planner}, {SelectExpr, Ecto.Query.SelectExpr}], context: nil, context_modules: [Ecto.Repo.Queryable], contextual_vars: [], current_vars: %{{:id, nil} => {0, :term}, {:pk, nil} => {0, :term}, {:query, nil} => {0, :term}, {:queryable, nil} => {0, :term}, {:schema, nil} => {0, :term}}, file: "/Users/benni/Sites/connect/deps/ecto/lib/ecto/repo/queryable.ex", function: {:query_for_get, 2}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, bit_size: 1, byte_size: 1, div: 2, elem: 2, exit: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, is_bitstring: 1, is_boolean: 1, is_float: 1, is_function: 1, is_function: 2, ...]}], lexical_tracker: #PID<0.4784.2>, line: 361, macro_aliases: [], macros: [{Kernel, [!: 1, &&: 2, ..: 2, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, in: 2, is_nil: 1, match?: 2, or: 2, pop_in: 1, ...]}], module: Ecto.Repo.Queryable, prematch_vars: :warn, requires: [Ecto.Query, Kernel, Kernel.Typespec], unused_vars: %{{{:id, nil}, 0} => 356, {{:pk, nil}, 0} => 360, {{:query, nil}, 0} => false, {{:queryable, nil}, 0} => false, {{:schema, nil}, 0} => false}, vars: [id: nil, pk: nil, query: nil, queryable: nil, schema: nil]})
    lib/ecto/query/builder/filter.ex:60: Ecto.Query.Builder.Filter.build/6
    expanding macro: Ecto.Query.where/3
    lib/ecto/repo/queryable.ex:361: Ecto.Repo.Queryable.query_for_get/2
    expanding macro: Ecto.Query.from/2
    lib/ecto/repo/queryable.ex:361: Ecto.Repo.Queryable.query_for_get/2
```

The output of elixir_ls trying to compile my project in vscode (MIX_ENV: test). Though I'm not sure if that's elixir_ls fault or ectos.

### Expected behavior

It compiling.

**Comment by josevalim** [comment]
The function definitely exists and it is public. So I would say it is an issue with Elixir LS in that it has conflicting versions of modules around. Is there a way you can ask Elixir LS to purge all cached data?

**Comment by LostKobrakai** [comment]
I've already tried removing the .elixir_ls folder in my project. I'll see if there's also some place, which might store stuff globally.

**Comment by LostKobrakai** [comment]
Also it's certainly working if I manually compile it with MIX_ENV=test.

**Comment by josevalim** [comment]
@LostKobrakai here is the function: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder.ex#L635

It is very unlikely to be a bug in Ecto. We will most likely need a way to reproduce it. If you can isolate it without Elixir LS and still reproduce it, then let us know and we will gladly reopen it.

**Comment by josevalim** [comment]
Also, please try killing any background worker Elixir LS may have, maybe by shutting down the editor, then removing the .elixir_ls directory, and starting it again, just in case it actually has a bad version of the module in memory.

**Comment by josevalim** [comment]
Btw, Ecto 2.2 only defined escape_binding/2: https://github.com/elixir-ecto/ecto/blob/v2.2/lib/ecto/query/builder.ex#L461-L483

So it really seems your Ecto 3.0 version is calling a module from Ecto 2.2.

**Comment by LostKobrakai** [comment]
Seems like it was some caching issue with elixir_ls. Running `rm -rf deps _build .elixir_ls && mix deps.get` with vscode closed has fixed the issue.
