### ISSUE TITLE
Where is the ecto association guide?

### ISSUE THREAD

**Issue by tcoopman** [elixir-ecto/ecto#2777]
I was looking for some info on associations in google (ecto association) and the first link turns up to be not working: https://hexdocs.pm/ecto/associations.html

So I came looking here and saw that the guide was also removed from the code. Why was it removed?
I came looking on how I should write my migrations for tables with associations (`add :user_id, references(:users)`) but it's not mentioned in the [Ecto.Schema](https://hexdocs.pm/ecto/Ecto.Schema.html) docs, so you have to go over to [Ecto.Sql](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#add/3) to find it.

In the guide this was way more clear to discover and learn about.

**Comment by josevalim** [comment]
@tcoopman unfortunately many people criticized this particular guide over the months and, when asked for improvements, they failed to provide any meaningful contributions. We have removed the guide for now, in the hope it kicks someone into gears into contributing something that the community believes is appropriate to its standards.

That said, improvement to the Ecto.Schema docs and/or a draft of an association guide would be very welcome. Thanks!

**Comment by alathon** [comment]
@josevalim Is there info available somewhere about what's been criticized / is missing from it? That'd make it easier for me to spend some time throwing together a PR on it :)

**Comment by josevalim** [comment]
@alathon it has been scattered throughout many issues but in a nutshell it did not feel like a guide, more like a quick reference, so there are many places where the user would have to fill in the blanks.
