### ISSUE TITLE
Ecto.Schema.Metadata not listed backward incompatible change

### ISSUE THREAD

**Issue by tomciopp** [elixir-ecto/ecto#2778]
There was a backward incompatible change for `Ecto.Schema.Metadata` that was not listed in the changelog for Ecto 3. The `source` key used to return a tuple of the schema prefix and the table name `{prefix, table}`, and now it returns just the table name. You may want to update the Changelog to account for this issue as people who have multi tenant setups may  be relying on this behavior.

**Comment by josevalim** [comment]
@tomciopp great catch, thank you!

**Comment by josevalim** [comment]
Btw, it would be fantastic if you could you send a PR, otherwise I will push a fix later.

**Comment by tomciopp** [comment]
@josevalim #2779
