### ISSUE TITLE
Bug: Ecto 3 breaks prefix support for associations using `join`

### ISSUE THREAD

**Issue by tomciopp** [elixir-ecto/ecto#2780]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.0
* Ecto version (mix deps): 3.0.0
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system: macOS 10.14 (Mojave)

### Current behavior
I have a multi tenant application that has `User` and `UserRole` schemas where a user `has_many` user roles. After updating to Ecto 3, when querying using the following:

    MyApp.User
    |> join(:inner, [user], ur in assoc(user, :user_roles))
    |> Repo.all(prefix: prefix)

I get this error message:

    ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "user_roles" does not exist

It looks like the join is happening on the `public` schema instead of using the prefix as was the previous behavior. I've taken a look at the docs and it does look like there was a `prefix` option added to `Ecto.Query.join`. However, when I attempt to use that option with a dynamic value, like so: 

    MyApp.User
    |> join(:inner, [user], ur in assoc(user, :user_roles), prefix: prefix)
    |> Repo.all(prefix: prefix)

I get this error message:

    (Ecto.Query.CompileError) `prefix` must be a compile time string, got: `prefix`

Include code samples, errors and stacktraces if appropriate.

### Expected behavior
The prefix option on the `Ecto.Repo.all` callback should carry over to all other query fragments unless otherwise stated as was done previously.

**Comment by josevalim** [comment]
Yes, the prefix in the query should win. Can you please post the SQL query
being logged?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Or rather, the prefix  in the query should be used as the fallback if no
other is specified.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tomciopp** [comment]
```SQL
an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 
12000, decode_time: nil, params: [], pool_time: 836000, query: %Postgrex.Query{cache: :reference, 
columns: nil, name: "ecto_1411", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, 
result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT u0.\"id\", u0.\"username\", 
u0.\"password_hash\", u0.\"used_password_hashes\", u0.\"reset_password_token\", 
u0.\"reset_password_expires_at\", u0.\"failed_attempts\", u0.\"unlock_token\", u0.\"locked_at\", 
u0.\"sign_in_count\", u0.\"current_sign_in_at\", u0.\"last_sign_in_at\", u0.\"current_sign_in_ip\", 
u0.\"last_sign_in_ip\", u0.\"finished_sign_up_at\", u0.\"encryption_version\", u0.\"inserted_at\", 
u0.\"updated_at\" FROM \"tenant-3ae976e6-140b-483c-929d-07745a1407c8\".\"users\" AS u0 INNER 
JOIN \"user_roles\" AS u1 ON u1.\"user_id\" = u0.\"id\"", types: nil}, result: {:error, 
%Postgrex.Error{connection_id: 22371, message: nil, postgres: %{code: :undefined_table, file: 
"parse_relation.c", line: "1180", message: "relation \"user_roles\" does not exist", pg_code: "42P01", 
position: "470", routine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}, query: "SELECT 
u0.\"id\", u0.\"username\", u0.\"password_hash\", u0.\"used_password_hashes\", 
u0.\"reset_password_token\", u0.\"reset_password_expires_at\", u0.\"failed_attempts\", 
u0.\"unlock_token\", u0.\"locked_at\", u0.\"sign_in_count\", u0.\"current_sign_in_at\", 
u0.\"last_sign_in_at\", u0.\"current_sign_in_ip\", u0.\"last_sign_in_ip\", u0.\"finished_sign_up_at\", 
u0.\"encryption_version\", u0.\"inserted_at\", u0.\"updated_at\" FROM \"tenant-3ae976e6-140b-483c-929d-07745a1407c8\".\"users\" AS u0 INNER JOIN \"user_roles\" AS u1 ON u1.\"user_id\" = 
u0.\"id\""}}}: ** (ArgumentError) argument error

```

**Comment by josevalim** [comment]
Wait, why are you getting "an exception was raised logging"? Instead of a proper exception? :)

**Comment by tomciopp** [comment]
I have no idea, that's just what I get when running the query with `iex -S mix`. I've just cut & paste exactly what has been spit out to the terminal. I also found that to be suspicious, but it looks like this is not the only case where that error is showing up in my app after the upgrade. Any thoughts on what might be going on?

**Comment by tomciopp** [comment]
Perhaps there is an error in version 2 of `db_connection`?

**Comment by josevalim** [comment]
If you call Application.start(:telemetry), what does it return?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tomciopp** [comment]
`:ok`

**Comment by josevalim** [comment]
So it means telemetry is not started. Please make sure to include ecto_sql
in your list of applications dependencies. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tomciopp** [comment]
Ah, that makes sense. Should we update the changelog to state that this is now necessary?  Prior to this phoenix apps did not require you to include `:ecto` in the applications list. I'm certain that I won't be the only person to run into this issue. If you want, I can write up a quick PR.

**Comment by josevalim** [comment]
Yes, let’s say in the CHANGELOG, when we talk about the split, that if you
have an :applications key, you should list ecto_sql there (but it is not
necessary if you have :extra_applications).
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by imranismail** [comment]
I'm facing this issue now. I can't pass the join `prefix` dynamically.
