### ISSUE TITLE
DBConnection.OwnershipError bug in tests

### ISSUE THREAD

**Issue by tomciopp** [elixir-ecto/ecto#2782]
I've been on a roll today.

### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10
* Ecto version (mix deps): 3.0.0
* Database adapter and version (mix deps): Postgrex 0.14.0
* Operating system: MacOS Mojave

### Current behavior

Include code samples, errors and stacktraces if appropriate.
I'm running tests that rely upon Ecto.Migrator to run migrations during tests. After upgrading Ecto to version 3.0 some of my tests now are failing with the following error message:

    ** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.700.0>.

     When using ownership, you must manage connections in one
     of the four ways:

     * By explicitly checking out a connection
     * By explicitly allowing a spawned process
     * By running the pool in shared mode
     * By using :caller option with allowed process

     The first two options require every new process to explicitly
     check a connection out or be allowed by calling checkout or
     allow respectively.

     The third option requires a {:shared, pid} mode to be set.
     If using shared mode in tests, make sure your tests are not
     async.

     The fourth option requires [caller: pid] to be used when
     checking out a connection from the pool. The caller process
     should already be allowed on a connection.

     If you are reading this error, it means you have not done one
     of the steps above or that the owner process has crashed.

     stacktrace:
       (db_connection) lib/db_connection.ex:766: DBConnection.transaction/3
       (ecto_sql) lib/ecto/migrator.ex:185: Ecto.Migrator.do_run_maybe_in_transaction/3
       (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
       (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
       (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

### Expected behavior

The tests should not error out since my application is running the pool in shared mode. Here is the following `setup` macro for my application

    setup tags do
      :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)

      unless tags[:async] do
        Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
      end

      {:ok, conn: Phoenix.ConnTest.build_conn()}
    end

I've confirmed that the `async` tag is set to `true` when running the failing test. It looks like the `do_run_maybe_in_transaction` function includes a call to `Task` where it previously did not.

**Comment by josevalim** [comment]
Can you please provide a sample application or a sample test that reproduces the error?

**Comment by josevalim** [comment]
Actually, I was able to reproduce it easily. The new migration system now locks the cluster, which means you won't be able to run it concurrently in the tests, not in shared mode nor in manual mode, also because it needs two connections. I need to think what would be the best solution here.

**Comment by josevalim** [comment]
The only option I can think of is to set the sandbox back to automatic mode, but this means your migrations will no longer run inside a transaction and permanently affect the state of your repository. If going in this direction, I would say the best approach is to likely create a new repository that you will use exclusively to test migrations. This may be the desired outcome after all because if you run migrations inside a sandbox, the behaviour cannot really be guaranteed. I will update the CHANGELOG as well, thanks!

**Comment by josevalim** [comment]
So there was [a bug in DBConnection](https://github.com/elixir-ecto/db_connection) that may have been the cause for this. Can you please run `mix deps.update db_connection` and let us know how it goes?

**Comment by tomciopp** [comment]
Based on my reading of the Changelog, what I was doing in my tests is now not possible due to the migrations locking. So I decided to add a task before mix test runs to create those records as fixtures in the db before running the test suite. This solved my problem.
