### ISSUE TITLE
redefining module Jason.Encoder.Ecto.Association.NotLoaded

### ISSUE THREAD

**Issue by amit115532** [elixir-ecto/ecto#2786]
* Elixir version (elixir -v): 1.7
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): 3.0
* Database adapter and version (mix deps): 0.14.0
* Operating system: alpine

Hello, I have just updated to ecto 3.0
I created a custom Jason encoding implementation for Ecto.Association.NotLoaded, otherwise I wouldnt be able to encode a model from ecto that did not have all associations loaded.

I never liked that solution as I couldnt get rid of the unloaded associations and I needed a custom protocol in frontend to ignore them.
But in Ecto 3, im getting a warning that is causing my deploy to fail since im redefining the protocol which has been introduced in ecto 3.

Have to say that im very frustrated with how Elixir community is neglecting these kind of problems. its become a mess to handle data types and encoding and it seems like no one really care about it as its something that can be solved using Phoenix.

Im not using Phoenix, all I want is to is to encode data I have retrieved from Ecto.

**Comment by josevalim** [comment]
Hi @amit115532!

I am sorry you find it frustrating but we believe our position on this matter is the correct one: **you cannot encode something that is not loaded**. For example, if you decide to encode a not loaded association as an empty list or nil, then **you are encoding the wrong information**.

There are some possible solutions here. For example, you could have a function that receives a struct or a list of structs and then do a pre-pass on the data, replacing all association not loaded structs by nil or an empty list. Another approach is to do a conversion pass on the data, converting all struct to maps, with only the fields you care about, and removing all associations. 

In any case, we will stick with our defaults. If you really want to redefine a protocol, then you can ping whatever you are using for deployment so it doesn't warn on duplicate modules, or it provides a mechanism to solve so.

**Comment by amit115532** [comment]
Totally agree that its the wrong information to encode, but the real problem is that I receive and have to handle with NotLoaded instead of just not including it in the result of a query.

All I say is that I have to hack around everything in context of structs and its very frustrating as its something I only see in Elixir.

**Comment by josevalim** [comment]
Elixir is a great language for data transformation. You should be
transforming your structs into the representation you want to render.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by user20230119** [comment]
This encodes `Ecto.Association.NotLoaded` to an empty array `[]`.
```
defimpl Jason.Encoder,
  for: [
    Ecto.Association.NotLoaded
  ] do
  def encode(value, opts) do
    "[]"
  end
end
```
