### ISSUE TITLE
The cases for `Ecto.StaleEntryError` are not clear in the documentation

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#2788]
### Environment

* Elixir 1.7.3
* Ecto 3.0.1

### Current behavior

The documentation for `Ecto.Repo.insert` and `Ecto.Repo.update` does not state in which situations an `Ecto.StaleEntryError` can be generated when calling these functions. Without such documentation it is not possible for the programmer to know what to do in case such error happens (i.e., should the application handle it or not?).

### Expected behavior

Be sure to document clearly in which situations does `insert`, `delete`, and `update` can generate an `Ecto.StaleEntryError`. The documentation is that in https://hexdocs.pm/ecto/Ecto.Repo.html

**Comment by qcam** [comment]
I think we somehow have it documented in [options](https://hexdocs.pm/ecto/Ecto.Repo.html#c:update/2-options) but I agree it could be better.
