### ISSUE TITLE
Repo is so slow

### ISSUE THREAD

**Issue by duanzhichao** [elixir-ecto/ecto#2791]
### Repo is so slow

* I execute sql 
      'select count(*), avg(total_expense), sum(acctual_days) from wt4_2016 where drg_bj ~* 'QY'  '.
   Psql  5.2 secs return result,  but Repo always query, not  return result 

* Elixir version (elixir -v): 1.7.3
* Database and version PostgreSQL 9.5 
* Ecto version:  3.2
* Database adapter and version: postgrex 0.14.0
* Operating system: ubuntu16.04

**Comment by josevalim** [comment]
Thanks, unfortunately this is very hard for us to solve without having a mechanism to reproduce the error. So can you please provide a small application that reproduces this? Thank you.

**Comment by duanzhichao** [comment]
Sorry,  data is private, i can't provide to you, i will try outher method

**Comment by josevalim** [comment]
@duanzhichao yes, this is understandable, usually we ask developers to create a smaller application with fake data, but enough to reproduce the issue.
