### ISSUE TITLE
Inserting a data with the on_conflict option does not have the same behavior between ecto 2.2 and ecto 3.0.1

### ISSUE THREAD

**Issue by lanarchyste** [elixir-ecto/ecto#2799]
### Environment

* Elixir version (elixir -v): 1.7.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.5
* Ecto version (mix deps): ecto 3.0.1
* Database adapter and version (mix deps): ecto_sql 3.0.0, postgrex 0.14.0
* Operating system: docker image based on elixir image

### Current behavior

I create a changeset with the data I only want to edit

```elixir
@primary_key {:account_id, :binary_id, autogenerate: false}
  schema "synchronization_monitoring" do
    field(:last_synchronization_at, :utc_datetime)
    field(:client_synchronization_status, SynchronizationStatusEnum)
    field(:catalog_synchronization_status, SynchronizationStatusEnum)

    timestamps()
  end
```

```elixir
@required_fields [:account_id]
@allowed_fields @required_fields ++
     [ :client_synchronization_status,
       :catalog_synchronization_status,
       :last_synchronization_at
     ]
```

```elixir
%SynchronizationMonitoring{account_id: account_id}
      |> cast(%{last_synchronization_at: last_synchronization_date}, @allowed_fields)
      |> validate_required(@required_fields)
      |> unique_constraint(:account_id)
      |> Repo.insert(on_conflict: :replace_all, conflict_target: :account_id)
```

When the data is inserted, if the row already exists, it will apply the changeset but it will modify the other columns with the default values

### Expected behavior

When the data is inserted, if the line already exists, we must update only the columns that are defined in the changeset and not update the values of the other columns

**Comment by josevalim** [comment]
Hi @lanarchyste! This was considered a bug fix between the releases. Although I can see some people may see this as a breaking change, so we also list it as so in the CHANGELOG. If you don't want this behaviour, you can explicitly list what you want to replace from the changeset:

    on_conflict: {:replace, Map.keys(changeset.changes)}

**Comment by lanarchyste** [comment]
I was able to get the expected behavior with your sample code.

Thank you so much !
