### ISSUE TITLE
Using on_conflict: :replace_all does not infer column name when the name of the field is different from the name of the column

### ISSUE THREAD

**Issue by esdras** [elixir-ecto/ecto#2807]
Hi Team.

I think I found a bug, details below.

Thank you very much for your work in Ecto and Elixir in general ❤️ 

### Environment

* Elixir version (elixir -v): Elixir 1.7.1
* Database and version: PostgreSQL 11
* Ecto version (mix deps): ecto 3.0.1, ecto_sql 3.0.0
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system: macOS Sierra 10.12.6

### Current behavior
```elixir
# schema definition
defmodule Wallet do
  schema "wallets" do
    #... other fields
    field(:__rev__, :integer, source: :__gut_rev__) #source and field have different names
  end
end

cs = Wallet.changeset(%Wallet{}, params)
Repo.insert(cs, on_conflict: :replace_all, conflict_target: [:id])

```

```bash
# complains the database does not have a column named __rev__
21:51:17.563 link_id=1 [error] Task #PID<0.837.0> started from #PID<0.832.0> terminating
** (Postgrex.Error) ERROR 42703 (undefined_column) column excluded.__rev__ does not exist
```

### Expected behavior
When I remove the `source` option and rename the field to the name of the column, the error does not occur. I think this should be the expected behavior.

I think it has to do with this function:
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L576

Thank you.

**Comment by josevalim** [comment]
Yeah, I don't think we are normalizing any of the fields given to replace. We have to address this. Good catch!

**Comment by qcam** [comment]
I can work on this if it has not been taken.

**Comment by josevalim** [comment]
Please go ahead!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Closing in favor of #2808.
