### ISSUE TITLE
Add option to check validations only for changed fields

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#2814]
### Environment

* Elixir 1.7.3
* Ecto 3.0.1

### Current behavior

All validations configured for a changeset are being checked even when the corresponding fields are not being changed. To avoid this issue, three solutions are:

1. To load from the database the entire entity to change, thus making a database access and bringing into memory data that is not necessary, thus degrading performance.

2. To create a changeset specific for the fields being changed, but this is unpractical due to the possible large number of field combinations.

3. To use `Repo.update_all` function, passing only the fields being changed, but this does not leverage the advantages of the `validate_*` functions.

All these solutions seem unsatisfactory from different points of view.

### Expected behavior

The proposed solution is to define a new option so that the `validate_*` functions only check their fields if these are being changed.

This option could be `only_changed: true`, `strictly_changed: true`, `only_changes: true` or something nicer, and when not present, or when set to `false` (the default), the `validate_*` functions would behave as of today (Ecto 3.0.1).

**Comment by mguimas** [comment]
At least the previous "check all behavior" has been observed with `validate_required`.

**Comment by josevalim** [comment]
This behaviour only exists for `validate_required` and it is by design. After all, `validate_required` is about checking that all of the relevent fields have been given as a change. If something was not given, then it should have been. All other validations use  `validate_change`, which only run indeed if something changed, thank you!

**Comment by mguimas** [comment]
Nice to know that about the other `validate_*` functions.

When you say that

> "... `validate_required` is about checking that all of the relevent fields have been given as a change.  If something was not given, then it should have been."

I think you are not meaning that this function checks that the fields passed to it are included in the `params` argument to `cast/4`, because this is not what this function does.

Can you clarify your statement then? Thanks.

**Comment by josevalim** [comment]
I meant that about the fields given to validated_required. They should be
checked even if they are not in change. For example, if somebody does not
pass a parameter via an API, it won’t be change, and validate_required
should still fail.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mguimas** [comment]
@josevalim What was the rationale behind that decision? If changesets are supposed, as their name implies, to support computing and validating *changes*, why does `validate_required` checks fields that are not being changed? Knowing this would make its use and that of changesets more clear. Thanks.

**Comment by josevalim** [comment]
I have explained this above:

> For example, if somebody does not pass a parameter via an API, it won’t be in change, and validate_required should still fail.

The whole point of `validate_required` is to make sure something was listed as a change.

**Comment by mguimas** [comment]
@josevalim Sorry to insist, but "make sure something was listed as a change" is to check if a field is passed in `params` argument (and in the `permitted` argument too) of `cast/4`.

But `validate_required` is not validating this, it is validating fields that are not being passed anywhere.

**Comment by josevalim** [comment]
> Sorry to insist, but "make sure something was listed as a change" is to check if a field is passed in params argument (and in the permitted argument too) of cast/4.

That's not what it means. `cast/3` checks for the fields, regardless if they are given or not. So for example, in a form where you have `username` and `name`, where `name` is optional, you would have this:

```elixir
user
|> cast(params, [:username, :name])
|> validate_required([:username])
```

`cast` won't check if something is required. It will cast if it is given, but not enforce it.

**Comment by mguimas** [comment]
@josevalim Have a look at it here:

```
iex(22)> %User{pid: 1} |> Ecto.Changeset.cast(%{username: "", email: "me@gmail.com"}, [:username, :email, :name]) |> Ecto.Changeset.validate_required([:username, :name])
#Ecto.Changeset<
  action: nil,
  changes: %{email: "me@gmail.com"},
  errors: [
    username: {"can't be blank", [validation: :required]},
    name: {"can't be blank", [validation: :required]}
  ],
  data: #User<>,
  valid?: false
>
```
What I mean is that `:name` is being validated though it is not being changed. That is, `validate_required` is checking a field that is not being changed.

**Comment by mguimas** [comment]
@josevalim I understand what you mean, but then I suggest you make it more clear in the docs of `validate_required`, especially that it has different behavior with respect to the other `validate_*` functions.

In a future release, it would be nice to have a `validate_required_params`, or something alike, that would validate "requiredness" only for fields that are really being changed, thus making it consistent with the other `validate_*` functions.

Thanks.

**Comment by josevalim** [comment]
> In a future release, it would be nice to have a validate_required_params, or something alike, that would validate "requiredness" only for fields that are really being changed, thus making it consistent with the other validate_* functions.

This means the function would never fail and it would never add an error.

**Comment by mguimas** [comment]
@josevalim I do not agree.

It means that the function would fail if a required field was passed with an empty value in `params`, but it would not fail if a required field was already empty in the struct but not passed in `params` (ie., a field that is not being changed at all).

This would make validation of required fields consistent with all other validation functions which only validate what is being changed.

Also, changesets should be validating only *changes* and nothing else. One should use changesets to validate changes, not to validate something that did not change.

NOTE: you do not need to break `validate_required` as it is if you don't want to. Just accept the possibility of adding `validate_required_params`, and if you can and want to clean the changeset API, to make it only validate what is being changed, then also deprecate `validate_required`, and in two or five years from now delete it.

**Comment by josevalim** [comment]
The rationale for the current behaviour and why it is desired has been explained multiple times. We won't change it and we won't deprecate stable APIs.

**Comment by josevalim** [comment]
One final observation: note in your example that username and name is treated as equals, they are both not added as change. That's because in many medium, such as command line and HTML forms, there is no distinction between not sent and empty string. So the whole system was design to take this into account. If you still don't think the mechanism makes sense, then you are welcome to pick another library, write your own, fork Ecto, etc.
