### ISSUE TITLE
Compile issue in case of `compile_time_purge_matching` logger option

### ISSUE THREAD

**Issue by van-mronov** [elixir-ecto/ecto#2817]
### Precheck

Adding logger compile_time_purge_matching option is causing ecto compilation fail.

### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): -
* Ecto version (mix deps): 3.0.1
* Database adapter and version (mix deps): -
* Operating system: Mac OS X

### Current behavior

[Here](https://github.com/van-mronov/ecto_demo) is an example of application.

```elixir
config :logger,
  compile_time_purge_matching: [
    [application: :ecto_demo, level_lower_than: :info]
  ]
```

```sh
$ mix deps.compile ecto
==> ecto
Compiling 1 file (.ex)

== Compilation error in file lib/ecto/log_entry.ex ==
** (FunctionClauseError) no function clause matching in Keyword.fetch/2

    The following arguments were given to Keyword.fetch/2:

        # 1
        {:metadata, [line: 50], nil}

        # 2
        :application

    Attempted function clauses (showing 1 out of 1):

        def fetch(keywords, key) when is_list(keywords) and is_atom(key)

    (elixir) lib/keyword.ex:362: Keyword.fetch/2
    (logger) lib/logger.ex:829: anonymous fn/4 in Logger.compile_time_purge_matching?/2
    (elixir) lib/enum.ex:2850: Enum.all_list/2
    (elixir) lib/enum.ex:2864: Enum.any_list/2
    (logger) lib/logger.ex:800: Logger.macro_log/4
    (logger) expanding macro: Logger.log/3
    lib/ecto/log_entry.ex:50: Ecto.LogEntry.log/3
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

### Expected behavior

It is compiled.

**Comment by zachdaniel** [comment]
So, I haven't looked very deeply into this yet, but looking at the documentation for `compile_time_purge_matching`, shouldn't your config be this instead?

```
config :logger,
  compile_time_purge_matching: [
    [application: :ecto_demo],
    [level_lower_than: :info]
  ]
```

**Comment by josevalim** [comment]
The config is correct. This is a bug in Elixir. :) @van-mronov can you please report it on the elixir issues tracker? Thanks!

**Comment by zachdaniel** [comment]
Just came back to correct my comment after reading the docs a bit more but you beat me to it :)

**Comment by van-mronov** [comment]
@josevalim ok)

**Comment by van-mronov** [comment]
[Issue](https://github.com/elixir-lang/elixir/issues/8389) is reported in elixir repo.
