### ISSUE TITLE
casting of buggy embeds does not fail properly

### ISSUE THREAD

**Issue by evadne** [elixir-ecto/ecto#2819]
### Environment

* Elixir version (elixir -v): 1.7.4
* Ecto version (mix deps): 3.0.1
* Operating system: macOS

### Current behavior

If a schema uses embeds but the embedded schema is buggy (and does not import `Ecto.Changeset`) it will still compile but then the parent changeset function will be buggy and never casting the embed.

For Example:

```elixir
defmodule Parent do
  use Ecto.Schema
  import Ecto.Changeset
  
  @primary_key false
  schema "parent" do
    embeds_one :child, __MODULE__.Child
  end
  
  defmodule Child do
    use Ecto.Schema
    # <---- missing import Ecto.Changeset here

    @primary_key false
    embedded_schema do
      field :name, :string
    end
  
    def changeset(schema, params \\ %{}) do
      schema
        |> cast(params, ~w(name)a) # <- this should fail as function should be undefined
        |> validate_required(~w(name)a) # <- this should fail as well
    end
  end

  def changeset(schema, params \\ %{}) do
    schema
      |> cast(params, [])
      |> cast_embed(:child, required: true)
  end
end
```

In this case:

```
iex(1)> Parent.changeset(%Parent{}, %{})
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [child: {"can't be blank", [validation: :required]}],
  data: #Parent<>,
  valid?: false
>
```

But it should really not even compile IMO

### Expected behaviour

I am not sure what is expected but current behaviour seems wrong. And if I move the child module out then the code rightfully does not compile. This might actually be an Elixir issue.

**Comment by wojtekmach** [comment]
It compiles because inner module gets aliases and imports from the outer module, probably what is happening is they are carried over in macro env when expanding the modules. Coincidently it was just mentioned on forum as undocumented behaviour: https://elixirforum.com/t/cultivates-elixir-posts/17948/2

**Comment by josevalim** [comment]
This is "documented" when we say that `alias`, `import` and `require` are lexical. It means they do not care about functions, modules, conditionals, cases. At the moment they are defined, everything below the declaration in the same code branch will have the same aliases, imports, etc.

Of course, saying that the documentation is in the word "lexical" is a bit cryptic, so improvements to the Elixir documentation with examples are very welcome. Thank you! :heart:

**Comment by evadne** [comment]
I did notice though, that although the code still did compile, the behaviour was wrong. So perhaps we should not close this so quickly.

**Comment by josevalim** [comment]
Thanks @evadne for the follow up. Reopening now. Can you please let us know which behaviour is wrong?

**Comment by evadne** [comment]
Will check this again shortly, I might be totally wrong though so please do not feel alerted yet 😯

**Comment by evadne** [comment]
@josevalim sorry, I am a mong and the bug was in my test.
