### ISSUE TITLE
id has to be integer

### ISSUE THREAD

**Issue by bradleyd** [elixir-ecto/ecto#282]
Hello,
I used to be able to do something like this before updating Ecto

``` elixir
def show(conn, %{"id" => id}) do
    post = Repo.get(Post, id)
    render conn, "show", post: post
end
```

Without errors...
But now I get 
`(Ecto.Query.TypeCheckError) the following expression does not type check: &0.id() == ^0 Allowed types for ==/2: number == number var == var nil == _ _ == nil Got: integer == string`

I assume it has to do with Ecto Backend matching on ^id
Is there something else I should be doing or do I need to convert the id via `Integer.parse("1")` before querying the database?

I appreciate any help you can give.

Take care,
Brad

**Comment by stevegraham** [comment]
I'm having a similar problem when using UUID primary keys, e.g. `Repo.get Model, "35fc50e2-fd7b-49ca-88d9-46332c96ac41"` will raise an Ecto.CastError. Is there a workaround for this?

**Comment by josevalim** [comment]
You need to configure the primary key. Check Ecto.Schema docs iirc. Basically, define:

    @primary_key {:id, Ecto.UUID, []}

Before calling `schema/2`.

**Comment by stevegraham** [comment]
Thanks @josevalim. Really appreciate how helpful you are. ❤️
