### ISSUE TITLE
Ecto.Repo.Supervisor does not work with new-style child specs

### ISSUE THREAD

**Issue by evadne** [elixir-ecto/ecto#2820]
* Elixir version (elixir -v): 1.7.4
* Ecto version (mix deps): 3.x
* Operating system: macOS

### Current behavior

When creating a new adapter, this works:

```
defmodule Adapter do
  @behaviour Ecto.Adapter
  def init(config) do
    child_spec = Supervisor.Spec.worker(Worker, [])
    adapter_meta = %{}
    {:ok, child_spec, adapter_meta}
  end
end
```

This does not:

```
defmodule Adapter do
  @behaviour Ecto.Adapter
  def init(config) do
    child_spec = Worker.child_spec([])
    adapter_meta = %{}
    {:ok, child_spec, adapter_meta}
  end
end
```

I think this is due to `Ecto.Repo.Supervisor` calling `supervise/2` (old behaviour).

### Expected behaviour

Would it be worth considering whether to support the new style?

**Comment by josevalim** [comment]
Definitely. We should call Supervisor.init/2 if available and fallback to
Supervisor.Spec.supervise/2 if not, as we still support older Elixir
versions.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Thanks, new version released!
