### ISSUE TITLE
Dynamically select named binding

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#2832]
### Environment

* Elixir version (elixir -v): 
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
* Ecto version (mix deps): ecto 3.0.2, ecto_sql 3.0.1
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system:

### Current behavior

When trying to select a named binding dynamically for a `Ecto.Query.API` macro the only way to do it currently seems to be using the `[{as, position}]` syntax:

```elixir
position = Map.get(query.aliases, binding_name)
select_merge(query, [{x, position}], %{id => x.id})
```

```elixir
select_merge(query, [{x, binding_name}], %{id => x.id}) // doesn't work
# ** (UndefinedFunctionError) function :binding_atom.__schema__/2 is undefined
```

### Expected behavior

- Some way to just do e.g. `[{x, binding_name}]` and it doing the position detection internally.
- Better error message: 
`(Ecto.Query.CompileError) binding list should contain only variables or {as, var} tuples, got: {^binding, x}`  
`{as, var}` is not really descriptive if it's more of a `{as, position}`
- Documenting the `[{as, position}]` syntax. I only found out how it's supposed to work by reading the tests after getting the above error message, which hinted there's some form of not hardcoded keywork list.

**Comment by josevalim** [comment]
For now I would go with a better error message. :)

**Comment by kenken1mura** [comment]
delet

**Comment by kenken1mura** [comment]
delet

**Comment by kenken1mura** [comment]
delet

**Comment by qcam** [comment]
@LostKobrakai Pardon me if I'm wrong but shouldn't it be?

```ex
select_merge(query, [{binding_name, x}], %{id => x.id})
```

**Comment by LostKobrakai** [comment]
If you want to refer to `[binding_name: x]`, yes yours seems like the better idea. But ecto internally doesn't use a keyword list. It uses positional bindings (binding -> position) and a separate mapping for name -> position. So that's why `[{x, position}]` was already existing (even before ecto 3) as a way to get the binding at position `position` as `x`. So it's probably more appropiate to use `[{x, binding_name}]`, where binding_name is just another for of saying, which binding to use, as it's more in line with existing behavior.

**Comment by qcam** [comment]
That's fair. But as you already pointed out `{x, position}` is an internal implementation and isn't publicly documented 🤔. So this can be changed without notice, depending on this is kinda risky, isn't it?

The reason why I'm asking this was to figure out what would be a better error message, since I think the current message makes sense to me, as `{as, var}` means exactly `[binding_name: x]` if I'm not wrong :).

**Comment by LostKobrakai** [comment]
That's exactly the issue I have with the current error. `{as, var}` is not `[{name: binding_var}]`, but it refers to being able to use `Schema |> select([{s, 0}], s.id)`. So `as` is meant to be the variable you want to be using and `var` is the position number of the binding.

**Comment by josevalim** [comment]
We don't plan to support this for now unless somebody decides to write a proposal and submit the according implementation. If somebody submits a PR with a better error message, it would be appreciated too. Thanks!
