### ISSUE TITLE
Ecto.Query.API.type/2 with dynamic field

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#2835]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres 10
* Ecto version (mix deps): 3.0.3 (3.0.2 ecto_sql)
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system:

### Current behavior

Follow up to https://github.com/elixir-ecto/ecto/issues/2485#issuecomment-440874401

I've added a few failing tests: 
https://github.com/LostKobrakai/ecto_sql/commit/a9e22c1296065ac809c9e2b341b56e3aa96061c3

The current error message `** (Ecto.Query.CompileError) type/2 expects an alias, atom or source.field as second argument, got: field(x, ^field)` would suggest my test examples should work, as the type is defined via an alias. But using an alias errors with 

```
** (ArgumentError) you attempted to apply :type on {:__aliases__, [line: 101], [:ConnectAuxiliary, :Ecto, :Money_Composite]}. If you are using apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function, make sure the left side of the dot is an atom or a map
    :erlang.apply({:__aliases__, [line: 101], [:ConnectAuxiliary, :Ecto, :Money_Composite]}, :type, [])
    lib/ecto/type.ex:263: Ecto.Type.match?/2
    lib/ecto/query/builder.ex:546: Ecto.Query.Builder.assert_type!/3
    lib/ecto/query/builder.ex:360: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder.ex:407: Ecto.Query.Builder.escape_with_type/5
    lib/ecto/query/builder/select.ex:104: anonymous fn/4 in Ecto.Query.Builder.Select.escape_pairs/4
    (elixir) lib/enum.ex:1418: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    lib/ecto/query/builder/select.ex:75: Ecto.Query.Builder.Select.escape/4
```

I'm not sure if `select: type(sum(field(x, ^name)), field(x, ^name))` is supposed to work. Having aliases work would be enough for my case for now.

### Expected behavior

Have some way to not need to hardcode a column name to be able to type things in an ecto query.

**Comment by josevalim** [comment]
Closing in favor of the PR.
