### ISSUE TITLE
Defining custom field types

### ISSUE THREAD

**Issue by HashNuke** [elixir-ecto/ecto#284]
Hi all,

I was working at a hackathon with Ecto riak adapter today (the one I've been writing).

Works well with simple fields like string, int etc. But when I tried to insert a model, with an elixir map as the value of a field, the validation failed because map is an unknown type.
- Noticed that a list of known types are being maintained here https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/util.ex#L42-L45
-  The validation is being done here - https://github.com/elixir-lang/ecto/blob/master/lib/ecto/repo/backend.ex#L193-L200

Is there any way to define custom fields types in an Ecto adapter? It would be nice to have that as a possibility because some databases support custom types.

P.S: The riak adapter serializes all the model's field-values as a json object, before storing it in riak and indexed in Solr (Riak 2.0 supports maps & sets, which I haven't explored yet. I'm just being opinionated for now)

**Comment by stavro** [comment]
Preliminary Hstore support for Ecto added here: https://github.com/stavro/ecto_hstore

**Comment by ericmj** [comment]
@stavro That's awesome! I have two comments on the code.

Don't use the `Ecto` namespace, it's reserved for ecto, you should a unique one for your project.

You use the text format of hstore, the binary format is more efficient and should be implemented through postgrex encoders/decoders (will be called extensions in the next version of postgrex). In fact, postgrex will not keep automatically accepting binaries for unsupported types in the next version so this code will stop working.

**Comment by stavro** [comment]
Thanks @ericmj ! I will look into your suggestions...

Also, querying is quite rough with hstore objects, and the only way I have found to do so requires raw SQL queries through `Ecto.Adapters.SQL.query`.

However, I wanted to get _something_ out there to get community feedback before getting too far down any rabbit holes.  If you have any suggestions on continuing with this extension addition let me know!  This is my first elixir package and I look forward to continuing to improve it

**Comment by ericmj** [comment]
> Also, querying is quite rough with hstore objects, and the only way I have found to do so requires raw SQL queries through Ecto.Adapters.SQL.query.

Query fragments allow you to insert custom SQL expressions inti ecto queries which should make it easier to use the hstore operators and functions.

**Comment by stavro** [comment]
Perfect!

```elixir
query = from u in User,
          where: fragment("?->'?' = '?'", u.flags, "key2", "value2"),
          select: u
```

Much appreciated.

**Comment by josevalim** [comment]
Maybe it is time to support macros or something similar in query
expressions so people
can extend those.

On Tuesday, February 10, 2015, Sean Stavropoulos <notifications@github.com>
wrote:

> Perfect!
>
> query = from u in User,
>           where: fragment("?->'?' = '?'", u.flags, "key2", "value2"),
>           select: u
>
> Much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/ecto/issues/284#issuecomment-73641623>.
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*
