### ISSUE TITLE
Schema prefix should override Repo prefix when preloading associations

### ISSUE THREAD

**Issue by whitepaperclip** [elixir-ecto/ecto#2841]
(Per IRC ~discussion~ monologue)

Given modules:

```elixir
defmodule Post do
  @schema_prefix "public"
  schema "posts" do
    # ...
    has_many :comments, Comment
  end
end

defmodule Comment do
  @schema_prefix "child"
  schema "comments" do
    # ...
    belongs_to :post, Post
  end
end

defmodule Repo do
  # ...
end

config :app, Repo,
  after_connect: {Postgrex, :query!, ["SET search_path TO child", []]}
```

Given call:

```elixir
Comment |> preload(:posts) |> Repo.all()
```

I would expect that the prefix of the particular schema would override the prefix set on the repo. Actually, the prefixes *should* be in the following order:

`repo.prefix || schema.prefix || query.prefix || nil`

**Comment by josevalim** [comment]
A PR is appreciated. You can look at the preloader, there we check the repo.prefix and then fallback to the query.prefix (which is the prefix of the given record) but it should first lookup the schema prefix before falling back to the query one. I think you will have to move the `preload_prefix` call to inside `fetch_query`.
