### ISSUE TITLE
Use `type/2` with window functions

### ISSUE THREAD

**Issue by alex88** [elixir-ecto/ecto#2844]
Initially erroneously posted here: https://github.com/elixir-ecto/ecto_sql/issues/59

### Environment

* Elixir version (elixir -v): 1.7.4 OTP 21
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.5
* Ecto version (mix deps): 3.0.0
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system:

### Current behavior

Doing `avg(d.production)` by default returns a `%Decimal{}`, to have it return a float I usually do `type(avg(d.production), :float)` or use `fragment`, both work fine.

However, I've tried multiple ways of having the same behavior while using window functions:

 - `over(type(avg(d.production), :float), :interval)` throws `unknown window function type/2. See Ecto.Query.WindowAPI for all available functions`
 - `type(over(avg(d.production), :interval), :float)` throws `type(over(avg(d.production()), :interval), :float) is not a valid query expression.`

### Expected behavior

The select returns that value as float

**Comment by josevalim** [comment]
Did you try putting it inside the avg?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by alex88** [comment]
@josevalim yup that works, I haven't tried  inside because I thought `avg` was the one returning a non integer (since in my case `d.production` is an integer)
