### ISSUE TITLE
Ecto latency issue

### ISSUE THREAD

**Issue by kattawar** [elixir-ecto/ecto#2846]
### Environment

* Elixir version (elixir -v): 1.7.1
* Database and version : 9.6 postgres
* Ecto version : 3.0.4 (same problem with 2.2)
* Database adapter and version: postgrex 0.14.1
* Operating system: alpine

### Current behavior

I’m having some issues with ecto when running our app in production where around 1/5 of the queries that ecto processes take around 10x (fast: 5-10ms, slow: 75-100ms) as long as the quickest ones even if it’s the exact same query running. The only place I’m seeing the spike in the ecto query_time is on the the first database call that the server must make when it is flowing through all the code required to respond to a request. After the first db query is made wether it was slow or fast all of the following db queries are very fast around 1-3 ms. If I hit a different route that runs a different first query upon request I can see the exact same random latency of about 1/5 requests. 

Context of environment: I’m running this on an AWS instance and also using an Aurora Postgres instance from AWS. The server is running inside of a kubernetes cluster and we have two pods running, each with one container running our service. In the AWS database dashboard I can see there are 20 active connections at almost all times unless we take something down, which makes sense because our pool size is set to 10 and we have two pods. When I look at the postgres logs for how long it spends processing the queries on the actual db itself every single query is under 1ms because I’m not doing anything to complex basically just selecting based on a column on a relatively small table of under 100 rows.

My only thought is that something around the connection pool is not working properly which is causing the random lag time on some of the requests. I also have the ecto.logentry record broken down into little sections and have found that the queue_time is almost instant (under 1 ms), the decode_time is also almost instant (about 1 ms), but the query_time is 75ms+. I am absolutely shocked that it is the query_time that is taking so long for us because on the actual DB the query is handled basically instantly (1 ms). My only thought is that there is some sort of random overhead that ecto adds to the query when it is the first query run for any given network request. 

This seems to be a bug in how the connections are handled in the connection pool or something related to that.

Does anybody have any ideas on what could be causing this or have any ideas on a little experiment that I could write that could possibly help me debug this?

### Expected behavior

I expect my ecto queries to the DB to have a more predictable and stable outcome

**Comment by josevalim** [comment]
It is worth noting that the "query_time" is not the time reported by the database but the time Ecto takes making the query. Therefore, if the system is overloaded and the VM needs to schedule out the current process doing the query for something else to run, then that will be reported as a very high time.

So my suggestion is to start tracking memory usage, run queue, load and other information of the current node. If all values are low and without spikes and you still see spikes in the query time, then something else is the root cause.

**Comment by kattawar** [comment]
So if I do somehow discover that our process is getting preempted and its just taking a little bit of time to get switched back to (around 70ms) is there anything I can do about this to make it not happen? Is there any way to give phoenix and elixir a higher priority for the OS scheduler so that they dont get preempted? Or is this something I maybe just have to just accept?

**Comment by josevalim** [comment]
If the OS process is the one preempting it, then you need to run less things on that particular node. If the preempting is coming from Erlang, then your machine is overloaded, and you need to bump resources. In other words, if your system is overloaded, I don't think you can escape from adding more resources.

**Comment by kattawar** [comment]
I dug down a little lower level and found the +sbt option we can pass to the erlang vm, do you have a good idea of any settings I could maybe give to +sbt that would reduce the worst case latency from context switching If I dont need to do insane amounts of conccurent traffic and just want reduced latency on all requests across the board?

**Comment by josevalim** [comment]
Maybe if you tie it to some schedulers and configure the OS to rely on the other ones, it could work, but it is hard to know without figuring out the root cause and the type of payloads.

**Comment by kattawar** [comment]
ok gotcha, If we boot our server with mix phx.server in our dockerfile is there a way I can pass erlang vm options to it? Locally i got 'iex --erl "options_here" -S mix phx.server' to start up fine and when i replace iex with 'elixir' it fails due to some error in redis. Is there a way I can set a flag for the --erl options or is there a line I can add to my mix.exs? I looked around and found something called exrm, but it looked like quiet a bit of changes I would need to do in order to test one small thing.

**Comment by kattawar** [comment]
Yea I would've expected it to work as well when i run it with elixir at the front I get a stacktrace 

`** (Mix) Could not start application aaa_service: exited in: AaaService.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Redix.Utils.sanitize_starting_opts/2
            (redix) lib/redix/utils.ex:35: Redix.Utils.sanitize_starting_opts(nil, [name: :redix])
            (redix) lib/redix/connection.ex:34: Redix.Connection.start_link/2
            (aaa_service) lib/aaa_service/application.ex:26: AaaService.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4`


However when i run with iex it works just fine. Not really sure how to proceed from here. I can go post this in a different forum now that it's getting into the weeds. Thanks for everything you are very helpful

**Comment by josevalim** [comment]
Maybe you are forgetting to set some environment variables that are actually set when the `iex` command is running?

**Comment by kattawar** [comment]
So we looks at our CPU usage over time and we don't go above 5%. So I would think we are on a relatively low load. I tried deploying with the various flags that we can pass to +sbt in order to try to change the way the erlang vm is scheduling things, but none of the settings seemed to affect anything in the way we needed it to. Is it worth trying to manually set the process_priority level when we are about to make an ecto call so that the current thread might not get switched out and have to context switch back? I don't mean setting the priority to max because that will of course bog down the scheduler for erlang to do the things it needs to do, but what about setting it to something like 'high'? any thoughts on whether this might do anything for us?

**Comment by josevalim** [comment]
At this point we can only speculate. The next would be to make this reproducible somehow so we can take a further look at it. :)

**Comment by josevalim** [comment]
Hi @kattawar! Please let us know if we can reproduce this issue. Otherwise, our hands are tied. In case you have a reproduction case, we will gladly reopen this. Thank you.
