### ISSUE TITLE
cast utc_datetime_usec: dropping microseconds for non-utc datetimes

### ISSUE THREAD

**Issue by hauptbenutzer** [elixir-ecto/ecto#2848]
### Environment

* Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): doesn't matter
* Ecto version (mix deps): 2.x and 3.x
* Operating system: macOS 10.14.1 (18B75)

### Current behavior

I stumbled upon the following behaviour using Ecto 2.2: 

```elixir
iex(1)> berlin = "2018-12-03 00:00:00.000001" |> NaiveDateTime.from_iso8601!() |> Timex.to_datetime("Europe/Berlin")
#DateTime<2018-12-03 00:00:00.000001+01:00 CET Europe/Berlin>
iex(2)> utc = "2018-12-02 23:00:00.000001" |> NaiveDateTime.from_iso8601!() |> Timex.to_datetime("Etc/UTC")
#DateTime<2018-12-02 23:00:00.000001Z>
iex(3)> Ecto.Type.cast(:utc_datetime, berlin)
{:ok, #DateTime<2018-12-02 23:00:00Z>}
iex(4)> Ecto.Type.cast(:utc_datetime, utc)
{:ok, #DateTime<2018-12-02 23:00:00.000001Z>}
```

Nevermind the Timex conversion, the important bit is, that the microseconds are lost when casting a non-UTC DateTime struct. I then went investigating and found that this stems from https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L936 , where microseconds are ignored. This function is also used in Ecto 3 for casting `utc_datetime_usec`, so the problem persists.

### Expected behavior

I would expect either 

* Ecto to error when casting a non-UTC DateTime struct (as it seems to do for `load` and `dump`)
* Or, preferably, keep the microseconds on cast

I've wrote some failing tests and added a fix proposition over here: https://github.com/hauptbenutzer/ecto/commits/fix/utc_datetime_usec_timezone 
I'd gladly open a PR for this, if desired. 

Cheers

**Comment by wojtekmach** [comment]
I tried this on Ecto master and here are results:

```elixir
iex> berlin = %{DateTime.from_naive!(~N[2018-12-03 00:00:00.000001], "Etc/UTC") | zone_abbr: "CET", time_zone: "Europe/Berlin", utc_offset: 3600}
#DateTime<2018-12-03 00:00:00.000001+01:00 CET Europe/Berlin>

iex> utc = DateTime.from_naive!(~N[2018-12-02 23:00:00.000001], "Etc/UTC")
#DateTime<2018-12-02 23:00:00.000001Z>

iex> Ecto.Type.cast(:utc_datetime, berlin)
{:ok, #DateTime<2018-12-02 23:00:00Z>}

iex> Ecto.Type.cast(:utc_datetime, utc)
{:ok, #DateTime<2018-12-02 23:00:00Z>}
```

so it seems correct. Could you verify this on Ecto master?

> Ecto to error when casting a non-UTC DateTime struct (as it seems to do for load and dump)

casting is more lenient than dumping and loading. In this case, we can safely turn a non-UTC date time into a UTC one so we allow that.

> Or, preferably, keep the microseconds on cast

That's a deliberate decision to leave microseconds out; if you need microsecond precision please use `:utc_datetime_usec` type.

**Comment by hauptbenutzer** [comment]
Hi! Sorry for maybe making this more confusing than it already is! What I meant to say was
1. In Ecto 2.x `cast(:utc_datetime, ..)` has the mentioned behaviour of dropping microseconds
2. In Ecto 3, `utc_datetime_usec` (not `utc_datetime`) has inherited this unwanted behaviour

The failing tests I wrote are indeed for casting `utc_datetime_usec` https://github.com/hauptbenutzer/ecto/commit/2f443eba4ffad70328b4f5600fcad46cb84734c0

**Comment by wojtekmach** [comment]
@hauptbenutzer oh, there's a bug when casting utc_datetime_usec indeed! Your branch looks good, please send a PR.
