### ISSUE TITLE
(CaseClauseError) no case clause matching: {:error, :rollback}

### ISSUE THREAD

**Issue by beerlington** [elixir-ecto/ecto#2862]
### Environment

* Elixir version (elixir -v): 1.7.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.2
* Ecto version (mix deps): 3.0.5
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system: Heroku Stack heroku-18

### Current behavior

Hello!

After upgrading to the newest versions of Ecto and Phoenix, we're seeing some errors on production and can't seem to pinpoint exactly what is causing it. The stack trace is:

```
Elixir.CaseClauseError: no case clause matching: {:error, :rollback}
  File "lib/ecto/repo/transaction.ex", line 16, in Ecto.Repo.Transaction.transaction/3
  File "lib/stone/my_context/my_module.ex", line 43, in anonymous fn/4 in Stone.MyModule.my_func1/3
    |> my_func2(arg2)
  File "lib/enum.ex", line 765, in Enum."-each/2-lists^foreach/1-0-"/2
  File "lib/enum.ex", line 765, in Enum.each/2
  File "lib/stone/server_action/worker.ex", line 134, in Stone.ServerAction.Worker.handle_cast/2
    MyModule.my_func1(id, template, opts)
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 711, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

I changed the name of the module and function in our app, but it's chaining a bunch of `Multi.run` functions with `Repo.transaction()` at the end:

```ex
  defp my_func2(arg1, arg2) do
    Multi.new()
    |> Multi.run(:name1, fn _, _ ->
      # removed
    end)
    |> Multi.run(:name2, fn _repo, %{name1: name1} ->
      # removed
    end)
    |> Multi.run(:name3, fn _, _ ->
      # removed
    end)
    |> Multi.run(:name4, fn _repo, %{name3: name3, name1: name1} ->
      # removed
    end)
    |> Repo.transaction()
  end
```

### Expected behavior

I'm not sure what the expected behavior is, but I would expect more information about what triggered the rollback.

I'm sort of able to reproduce it by explicitly triggering a rollback with the value `:rollback`, however, we're not doing any explicit rollbacks in our application:

```ex
  def test do
    Multi.new()
    |> Multi.run(:test, fn _, _ ->
      Repo.rollback(:rollback)
    end)
    |> Repo.transaction
  end
```

Thanks!

**Comment by wojtekmach** [comment]
Hey @beerlington, does the error happen only in production? Are you able to reproduce it in `:dev` or `:test` environments? (In `:test`, sandbox could be relevant.) Hard to say what could go wrong here, could you prepare a smaller repro that we can run ourselves?

**Comment by wojtekmach** [comment]
Oh, and whats your ecto_sql version?

**Comment by beerlington** [comment]
@wojtekmach I've been trying to reproduce it in dev and test, but cannot. The snippet I posted at the bottom does produce the error in dev, but I'm not sure if I'm even using rollback correctly:

```ex
defmodule MyModule do
  alias Ecto.Multi
  alias Stone.Repo

  def test do
    Multi.new()
    |> Multi.run(:test, fn _, _ ->
      Repo.rollback(:rollback)
    end)
    |> Repo.transaction
  end
end

```

Does ^ that seem like it should raise this exception?:

```
iex(11)> MyModule.test()
[debug] QUERY OK db=0.9ms
begin []
[debug] QUERY OK db=0.6ms
rollback []
** (CaseClauseError) no case clause matching: {:error, :rollback}
    (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
```

Would it make sense to see if that's reproducible in a separate app?

**Comment by beerlington** [comment]
We're using `ecto_sql 3.0.3`

**Comment by wojtekmach** [comment]
this:

```elixir
  def test do
    Multi.new()
    |> Multi.run(:test, fn _, _ ->
      Repo.rollback(:rollback)
    end)
    |> Repo.transaction
  end
```

I think should work, however please try changing `Repo.rollback` to `repo.rollback` that's passed in to the function:

```elixir
    |> Multi.run(:test, fn repo, _ ->
      repo.rollback(:rollback)
    end)
```

**Comment by beerlington** [comment]
yea same results with:

```ex
defmodule MyModule do
  alias Ecto.Multi
  alias Stone.Repo

  def test do
    Multi.new()
    |> Multi.run(:test, fn repo, _ ->
      repo.rollback(:rollback)
    end)
    |> Repo.transaction
  end
end
```

I'll see if I can get a new app together that reproduces that.

**Comment by wojtekmach** [comment]
@beerlington I was able to reproduce this:

```
# a.exs
alias Hexpm.Repo

# this works
{:error, :foo} =
  Repo.transaction(fn ->
    Repo.rollback(:foo)
  end)

# this doesn't
Ecto.Multi.new()
|> Ecto.Multi.run(:foo, fn repo, _ ->
  repo.rollback(:bar)
end)
|> Repo.transaction()
```

```
mix run a.exs
[debug] QUERY OK db=1.2ms queue=10.1ms
begin []
[debug] QUERY OK db=0.2ms
rollback []
[debug] QUERY OK db=0.2ms
begin []
[debug] QUERY OK db=0.1ms
rollback []
** (CaseClauseError) no case clause matching: {:error, :bar}
    (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
    (elixir) lib/code.ex:767: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:147: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:86: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

Instead of calling `Repo.rollback` in a multi step we can return `{:error, result}` and the transaction will be rolled back, and we'll get `result` under operation key that failed. So I think that's the way to go.

I think we could raise a better error message under these circumstances.

**Comment by michalmuskala** [comment]
Yeah, this should fail more gracefully or maybe even just return the error tuple from the transaction call directly.

**Comment by josevalim** [comment]
Closing in favor of #2867 .
