### ISSUE TITLE
Schema (with JSON) returned after insert and after get is not the same

### ISSUE THREAD

**Issue by EskiMag** [elixir-ecto/ecto#2864]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.6
* Ecto version (mix deps): ecto 3.0.5, ecto_sql 3.0.3
* Database adapter and version (mix deps): postgrex 0.14.0
* Operating system: macOS Mojave 10.14.2 (18C54)

Hi,

I am working with `Ecto.Schema` which has one field `:payload` defined as a `:map` (backed by jsonb).
see: https://github.com/EskiMag/ecto_json_inconsistency/blob/master/lib/bug/model.ex

I am saving `Payload` struct into the `:payload` field. Payload struct is implementing `Jason.Encoder`, and the saved DB row looks correctly (has no `__meta__`, `__struct__` fields saved etc. only `{"field": "some-value"}`)
see: https://github.com/EskiMag/ecto_json_inconsistency/blob/master/lib/bug/payload.ex

And after I insert Model into DB, `{:ok, model}` is returned, but the payload field inside the model is a struct, not a map.
see: https://github.com/EskiMag/ecto_json_inconsistency/blob/master/test/bug/model_test.exs

I am not 100% sure this is a bug, but I really think this should be consistent. Or am I missing something? Thank you very much for your help.

**Comment by josevalim** [comment]
Unfortunately conversion to JSON is lossy. For example, if you convert an Elixir decimal to JSON, when you try to decode it, you will either get a string or a float back, but not a decimal. Something similar is happening here. You either need to use embeds or use a custom type. :+1:

**Comment by josevalim** [comment]
Yeah, we can't know how to convert it back without you writing custom code to handle it, so you need a custom type or embeds. Just as an example, if your struct had a decimal in it, even if we were able to get the struct itself right, the values themselves would be wrong.

So you can say it is consistently lossy. 😅

**Comment by EskiMag** [comment]
OK, so what should I do, to have the result of `Repo.insert` in plain lossy form (`%{"key" => "value"}`) - the same as is returned after `Repo.get()`? Should I traverse the map recursively to convert the keys from atoms to strings?

**Comment by josevalim** [comment]
You can define a custom type that rebuilds it back for you (see Ecto.Type) or use the embeds feature (see Ecto.Schema).

**Comment by EskiMag** [comment]
Thank you very much for the hints. I'll check them. Have a nice day. 👍🏻
