### ISSUE TITLE
What does the `defaults` option do in `belongs_to`?

### ISSUE THREAD

**Issue by samphilipd** [elixir-ecto/ecto#2870]
The documentation states:

`:defaults - Default values to use when building the association`

With no further elaboration, this is not particularly enlightening. I can't find it easily in the source either.

I want to set a default foreign key, but I have no idea how to do that with this option, or indeed if this is the correct option to use.

**Comment by josevalim** [comment]
Imagine Post.has_many :comments, defaults: `[public: true]`. Then when you say `Ecto.build_assoc(post, :comments)` that comment will have `comment.public == true`, regardless of the default in the comment schema. Can you please send a PR amending the docs? Thank you!

**Comment by samphilipd** [comment]
PR opened.

Does this mean there is no way to set a default foreign key value?

**Comment by josevalim** [comment]
@samphilipd only for another association than the one being built. Can the default foreign key be set as a default in the schema?

**Comment by samphilipd** [comment]
That's exactly what I'm trying to do:

I want something like this:

```
 belongs_to(
      :buyer_property_interest_status,
      NestDB.InputChoice.BuyerPropertyInterestStatus,
      default: @b01_enquired_id
    )
```

But the only available option is `defaults` - `default` doesn't exist.

**Comment by samphilipd** [comment]
Great, that works!
