### ISSUE TITLE
Repo.preload using a has_many(_, through: _) association does not always load all structs

### ISSUE THREAD

**Issue by dallincrane** [elixir-ecto/ecto#2873]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.6
* Ecto version (mix deps): 3.0.5
* Database adapter and version (mix deps): Postgrex 0.14.1
* Operating system: MacOS

### Current behavior

Using a join table schema with `@primary_key false` as [suggested in the docs](https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3-join-schema-example) causes `Repo.preload` to only add one of the records of a `has_many(_, through: [_, _])` association

Using the example in the docs

```
defmodule UserOrganization do
  use Ecto.Schema

  @primary_key false
  schema "users_organizations" do
    belongs_to :user, User
    belongs_to :organization, Organization
  end
end
```

with one organization and two associated users in the db, running  
`Organization |> Repo.all() |> Repo.preload(:users)`  
would return

```
[
  %Organization{
    __meta__: #Ecto.Schema.Metadata<:loaded, "organizations">,
    id: 1,
    name: "Citadel of Ricks",
    users_organizations: [
      %UserOrganization{
        __meta__: #Ecto.Schema.Metadata<:loaded, "users_organizations">,
        organization: #Ecto.Association.NotLoaded<association :organization is not loaded>,
        organization_id: 1,
        user: %User{
          __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
          id: 1,
          name: "Rick",
          organizations: #Ecto.Association.NotLoaded<association :organizations is not loaded>,
          users_organizations: #Ecto.Association.NotLoaded<association :users_organizations is not loaded>,
        },
        user_id: 1
      },
      %UserOrganization{
        __meta__: #Ecto.Schema.Metadata<:loaded, "users_organizations">,
        organization: #Ecto.Association.NotLoaded<association :organization is not loaded>,
        organization_id: 1,
        user: %User{
          __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
          id: 2,
          name: "Morty",
          organizations: #Ecto.Association.NotLoaded<association :organizations is not loaded>,
          users_organizations: #Ecto.Association.NotLoaded<association :users_organizations is not loaded>,
        },
        user_id: 2
      }
    ],
    users: [
      %User{
        __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
        id: 1,
        name: "Rick",
        organizations: #Ecto.Association.NotLoaded<association :organizations is not loaded>,
        users_organizations: #Ecto.Association.NotLoaded<association :users_organizations is not loaded>,
      }
    ]
  }
]
```

### Expected behavior

The `users` attribute above should be filled with both of the users instead of just the first one.

Happy to work on a fix for this but need to confirm that we want to  
**(a)** fix the code to load all through structs  
instead of   
**(b)** throw an error if a `has_many(_, through: [_, _])` relationship do not have a primary key

### Work Around

Adding `primary_key: true` to both of the `belongs_to()` gives the expected preload result.

**Comment by josevalim** [comment]
I would like to understand why this happens. What is going on with the code so that it loads only part of the data? Most likely it is loading it all but it thinks it is the same somehow? Can you put up a minimal app with a failing test case so we can take a deeper look? Thank you! :heart:

**Comment by dallincrane** [comment]
@josevalim 

minimal app: https://github.com/dallincrane/ecto_check

All the data needed from from the db is loaded. Haven't looked super close at it but I believe the issue is here in the `Repo.Preloader.recur_through` function
```
{children, _} =
  Enum.reduce(structs, {[], %{}}, fn struct, acc ->
    children = struct |> Map.fetch!(field) |> List.wrap

    Enum.reduce children, acc, fn child, {fresh, set} ->
      keys =
        child
        |> through_pks(pks, assoc)
        |> validate_non_null_pk!(child, pks, assoc)

      case set do
        %{^keys => true} ->
          {fresh, set}
        _ ->
          {[child|fresh], Map.put(set, keys, true)}
      end
    end
  end)
```

where it is only added to the list of `children` if the primary_key values do not exist as a key in the `set` map. Because the primary_key values in this scenario will always be an empty list `[]`, only the first struct is added as a child.

**Comment by josevalim** [comment]
Thanks for the PR. after look at the fix and the code, i don't think it can work without primary keys. I mean, we could if we assume the records are unique, but that may have its own issues too, so I think going with an error is the way to go! :+1:
