### ISSUE TITLE
Getting Started guide - deleting records does not require a fetch

### ISSUE THREAD

**Issue by mred** [elixir-ecto/ecto#2875]
The getting started guide states that "we must first fetch a record from the database and then call Friends.Repo.delete to delete that record", but the documentation for Ecto.Repo.delete specifies that a struct or changeset may be used, so there is no need to first fetch the record when a struct is used.

**Comment by josevalim** [comment]
If you already have the struct, then you don't need to fetch it, but most usually you do need to fetch it, yes. We will update it accordingly, thank you!
