### ISSUE TITLE
The task "ecto.gen.migration" could not be found

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#2876]
Ecto 3.0.3

```
mix ecto.gen.migration create_table1
** (Mix) The task "ecto.gen.migration" could not be found
```

**Comment by koushikaccionlabs** [comment]
Same problem I am facing today when i was trying to generate db migration file. It gives error "(Mix) The task "ecto.gen.migration" could not be found".
Any help will be appreciated.

**Comment by wojtekmach** [comment]
Do you have ecto_sql dependency installed? This mix task was moved there in v3.0.

**Comment by koushikaccionlabs** [comment]
@wojtekmach you are right. But for my case it was my mistake as I tried the command from wrong place.  Thanks for the help.
