### ISSUE TITLE
Warning Inspect.Algebra.surround_many/5 is deprecated on Elixir 1.8.0-otp-21.2.2

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-ecto/ecto#2884]
### Environment

* Elixir version (elixir -v):
    ```elixir
    Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
    
    Elixir 1.8.0 (compiled with Erlang/OTP 21)
    ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): `ecto 3.0.6 (Hex package) (mix)`
* Database adapter and version (mix deps):  N/A
* Operating system: RedHat Linux

### Current behavior

Fresh compile with the dependency of `{:ecto, "~> 3.0.6"},` results in:
```elixir
==> ecto
Compiling 54 files (.ex)
warning: Inspect.Algebra.surround_many/5 is deprecated. Use Inspect.Algebra.container_doc/6 instead
Found at 3 locations:
  lib/ecto/changeset.ex:2755
  lib/ecto/query/inspect.ex:16
  lib/ecto/query/inspect.ex:30

Generated ecto app
```

### Expected behavior

Clean compile.

**Comment by OvermindDL1** [comment]
Conditional code generation perhaps?  ^.^
Related to:  https://github.com/elixir-plug/plug/issues/811

**Comment by josevalim** [comment]
Yup, that should work here!

**Comment by OvermindDL1** [comment]
PR's welcome I hope?  If so should this be reopened so there is something to link to?  :-)

**Comment by josevalim** [comment]
Yes, PR please!

**Comment by OvermindDL1** [comment]
Just to verify because this looks too easy, `surround_many/5` and `container_doc/5` have identical specs it seems, so it's just a simple call swap dependent on version?

**Comment by josevalim** [comment]
```elixir
  @deprecated "Use Inspect.Algebra.container_doc/6 instead"
  def surround_many(
        left,
        docs,
        right,
        %Inspect.Opts{} = inspect,
        fun,
        separator \\ @container_separator
      )
      when is_doc(left) and is_list(docs) and is_doc(right) and is_function(fun, 2) do
    container_doc(left, docs, right, inspect, fun, separator: separator)
  end
```

There is a difference regarding the separator.

**Comment by OvermindDL1** [comment]
> There is a difference regarding the separator.

Ah yes, just caught that as well, incoming.  :-)

**Comment by OvermindDL1** [comment]
Should I leave a `TODO: Replace unquote with just `container_doc` when Elixir < 1.8.0 is no longer supported` or so?

**Comment by josevalim** [comment]
Yes.

**Comment by augnustin** [comment]
Hey!  
What's the fix here? Should we set a version of `ecto` in `mix.exs` which removes the warning?
Thanks

**Comment by wojtekmach** [comment]
I believe this warning is taken care of in Ecto 3.0.7. What's your version?

**Comment by augnustin** [comment]
```
  "ecto": {:hex, :ecto, "2.2.12", "ce7f619c1451daad0f59e8f01fd8e2584226171dc273e3346444446a13d93943", [:mix], [{:db_connection, "~> 1.1", [hex: :db_connection, repo: "hexpm", optional: true]}, {:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.8.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, repo: "hexpm", optional: true]}], "hexpm"},
```

Seems like I'm quite behind.
