### ISSUE TITLE
How to prevent it from creating a record with non-nil "updated_at"?

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#2893]
1. What's the logic behind making updated_at = inserted_at  when a record is  *inserted*? this is the default behaviour of Ecto

2. How to insert a record with updated_at = nil ?

**Comment by GildedHonour** [comment]
Now I'll have to find all the places where "Repo.insert" is used and call "put_change" after it

**Comment by GildedHonour** [comment]
up

**Comment by josevalim** [comment]
It is non null because we always fill it in. timestamps are a convenience,
you don’t have to use them. You can always declare them yourself if you
don’t like the default behavior.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
