### ISSUE TITLE
Problem with Changeset and boolean fields

### ISSUE THREAD

**Issue by archimondain** [elixir-ecto/ecto#2894]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10
* Ecto version (mix deps): 3.0.5
* Database adapter and version (mix deps): ecto_sql 3.0.3
* Operating system: Bash subsystem of windows 10

### Current behavior

Suppose I have:

    def changeset(%MyTable{} = table, attrs) do
        table
        |> change(attrs)
    end

Then the following 

    %MyTable{id: id}
    |> MyTable.changeset({my_boolean?: true})

produces a valid `changeset` where the field `my_boolean?` is set to true. But the following:

    %MyTable{id: id}
    |> MyTable.changeset({my_boolean?: false})

produces a valid empty `changeset`. 

Like that I would say that it seems to be a bug. Maybe `if map[field] ...` is used somewhere in the code to check if `field` is a field of `map` (instead of using `if map[field] != nil`).

### Expected behavior

I expect 

    %MyTable{id: id}
    |> MyTable.changeset({my_boolean?: false})

to produce a valid `changeset` with `my_boolean?` set to `false`

**Comment by wojtekmach** [comment]
Could you show how you define `my_boolean?` in MyTable schema? If it has `default: false` then building a changeset with false value will have empty changes, otherwise there should be a change indeed.

**Comment by archimondain** [comment]
Yes, it has `default: false`. I guess I misunderstood how `Changesets` are suppose to work. Thanks a lot.
