### ISSUE TITLE
Improvement: lazy `Ecto.Changeset.unsafe_validate_unique/4`

### ISSUE THREAD

**Issue by juulSme** [elixir-ecto/ecto#2901]
While working on a project I noticed that `Ecto.Changeset.unsafe_validate_unique/4` executes a uniqueness check on my repo even when the field(s) specified are not present in the changeset's changes. Perhaps I've missed something, but I think this could be done lazily by comparing the changeset's changes with the specified fields and save a database query if it is not necessary.

### Environment

* Elixir version (elixir -v): 1.8.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11
* Ecto version (mix deps): 3.0.6
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system: Ubuntu 18.04

### Current behavior

As part of my `User` schema:
```Elixir
def general(user, attrs) do
    user
    |> cast(attrs, [:name, :email])
    |> unsafe_validate_unique([:email], MyApp.Repo)
    |> unique_constraint(:email)
end
```

IEx:
```Elixir
alias MyApp.Accounts.User
%User{email: "dave@domain.tld", name: "Dave"} |> User.changeset(%{"name" => "Peter"})
[debug] QUERY OK source="users" db=3.4ms
SELECT TRUE FROM "users" AS u0 WHERE (u0."email" = $1) LIMIT 1 ["dave@domain.tld"]
#Ecto.Changeset<
  action: nil,
  changes: %{name: "Peter"},
  errors: [],
  data: #MyApp.Accounts.User<>,
  valid?: true
>
```
So a query is executed for the email field while it would not be changed by applying the resulting changeset.

### Expected behavior
```Elixir
alias MyApp.Accounts.User
%User{email: "dave@domain.tld", name: "Dave"} |> User.changeset(%{"name" => "Peter"})
#Ecto.Changeset<
  action: nil,
  changes: %{name: "Peter"},
  errors: [],
  data: #MyApp.Accounts.User<>,
  valid?: true
>
```

### Proposal

Perhaps it could be improved by wrapping `unsafe_validate_unique/4` in a change-checker, something like:
```Elixir
def lazy_unsafe_validate_unique(changeset, fields, repo, opts \\ []) do
    changed_fields =
      changeset.changes
      |> Map.keys()
      |> MapSet.new()
      |> MapSet.intersection(fields |> MapSet.new())

    if MapSet.new() != changed_fields do
      unsafe_validate_unique(changeset, fields, repo, opts)
    else
      changeset
    end
  end
```
Or something more performant along the same lines, if somebody can come up with something :)

**Comment by josevalim** [comment]
@nathanl any considerations on this? Do you think this would be a good behaviour?

**Comment by nathanl** [comment]
Makes sense to me. Although the logic needs to be "do the validation if *any* of the fields have changed". Eg, if the combination of body + title must be unique, then we need to do the validation if either of those changes.

**Comment by nathanl** [comment]
@juulSme Check out https://github.com/elixir-ecto/ecto/pull/2905

**Comment by nathanl** [comment]
Nice catch of this problem by the way @juulSme, and excellent job writing it up clearly. :smile: :100: The behavior comparisons and the proposed code helped me understand more quickly.

**Comment by josevalim** [comment]
Closing this in favor of the PR! :D

**Comment by juulSme** [comment]
:+1:

**Comment by slashmili** [comment]
sorry for digging and old issue but do you think that this `unsafe_validate_unique` should be run only if there is no error on this specific field?

e.g
```elixir
def general(user, attrs) do
    user
    |> cast(attrs, [:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unsafe_validate_unique([:email], MyApp.Repo)
    |> unsafe_validate_unique(:email)
end
```

in this example if the email doesn't contain `@` there is no point to query the database for uniques of that field.  Another practical example is the username, usually if it's less than 3 chars, we don't need to query database. 


For my own use case, I've created a wrapper around `unsafe_validate_unique` 

```elixir
defp lazy_unsafe_validate_unique(changeset, field, repo) do
  case Enum.find(changeset.errors, & elem(&1, 0) == field) do
    nil -> unsafe_validate_unique(changeset, field, repo, [])
    _ -> changeset
  end
end
```

I understand though, if you don't think this feature is necessary!

**Comment by josevalim** [comment]
We should not run it if there are errors. I thought this is was implemented but, if not, a PR is very welcome!
