### ISSUE TITLE
Upgrading to Ecto 3: Error Postgrex expected an integer got DateTime and vice versa

### ISSUE THREAD

**Issue by Brianvdb** [elixir-ecto/ecto#2920]
### Environment

* Elixir version (elixir -v): Elixir 1.7.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.4
* Ecto version (mix deps): ecto_sql 3.0.2
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system: Linux

### Current behavior

I am composing a query with a dynamic amount of select rows.

In Ecto 2 I had this working code:

```
def user_transaction_graph_analytics(user_id, ranges) do
    query = (
      from q in Transaction,
      join: p in assoc(q, :program), on: q.program_id == p.id and p.user_id == ^user_id,
      select: %{}
    ) |> append_select(ranges)

    result = query |> Repo.one!
  end

  def append_select(query, [%{"start" => start_date, "end" => end_date, "name" => name}|ranges]) do
    date_start = Timex.from_unix(start_date, :milliseconds)
    date_end = Timex.from_unix(end_date, :milliseconds)
    query = query |> select_merge([q], %{name: fragment("SUM(CASE WHEN ? > ? AND ? < ? THEN 1 ELSE 0 END)", field(q, :inserted_at), ^date_start, field(q, :inserted_at), ^date_end)})
    append_select(query, ranges)
  end

  def append_select(query, []), do: query
```

Now when I upgraded to Ecto 3 this gives the following error (on the `select_merge` line):
```
Postgrex expected an integer in -9223372036854775808..9223372036854775807, got #DateTime<2019-02-02 00:00:00.000000Z>
```
So then I tried to pass the `^date_start` and `^date_end` as an integer and this resulted in this error:
```
Postgrex expected %DateTime{} or %NaiveDateTime{}, got 1548979200000
```
I then tried to cast my dates like this:
```
type(^date_start, :utc_datetime)
```
But this resulted in the first error. I also tried the other types (usec)

I also defined the timestamp opts in my Schema (Transaction)
`
@timestamps_opts [type: :utc_datetime_usec]
`
and also tried
`@timestamps_opts [type: :utc_datetime]`
But this changed nothing.

### Expected behavior
I should be able to pass my parsed dates in my select_merge query.

For now, I have made below workaround which does work in Ecto 3, but this executes a query for every range.

```
def user_transaction_graph_analytics(user_id, ranges) do
    new_ranges = Enum.map(ranges, fn range ->
      date_start = Timex.from_unix(range["start"], :milliseconds)
      date_end = Timex.from_unix(range["end"], :milliseconds)

      query = (
        from q in Transaction,
        join: p in assoc(q, :program), on: q.program_id == p.id and p.user_id == ^user_id,
        select: %{hello: sum(fragment("CASE WHEN ? > ? AND ? < ? THEN 1 ELSE 0 END", field(q, :inserted_at), ^date_start, field(q, :inserted_at), ^date_end))}
      )

      (query |> Repo.one!).hello
    end)

    new_ranges
  end
```
Strange that i can pass my dates now without it throwing an error.

Extra information:
`inserted_at` was created in my schema with `timestamps()` function. 
`inserted_at` is in Postgres of type: `timestamp without time zone`

**Comment by josevalim** [comment]
Can you please paste the query logged to console in Ecto 2 and in Ecto 3? I wonder if they are the same or if there are differences.

Also, if you change the query to this:

```elixir
%{name: field(q, :inserted_at) > ^date_start and field(q, :inserted_at) < date_end}
```

Does it fix the issue? In a nutshell, i am trying to figure out if the error is in postgres, postsgrex or Ecto.

Thanks!

**Comment by Brianvdb** [comment]
This is the query which is being logged/executed with Ecto 3:
```SELECT SUM(CASE WHEN t0."inserted_at" > $1 AND t0."inserted_at" < $2 THEN 1 ELSE 0 END) FROM "transactions" AS t0 INNER JOIN "programs" AS p1 ON (p1."id" = t0."program_id") AND ((t0."program_id" = p1."id") AND (p1."user_id" = $3)) [#DateTime<2019-02-01 00:00:00.000Z>, #DateTime<2019-02-01 23:59:59.000Z>, #DateTime<2019-02-02 00:00:00.000Z>, #DateTime<2019-02-02 23:59:59.000Z>, #DateTime<2019-02-03 00:00:00.000Z>, #DateTime<2019-02-03 23:59:59.000Z>, #DateTime<2019-02-04 00:00:00.000Z>, #DateTime<2019-02-04 23:59:59.000Z>, #DateTime<2019-02-05 00:00:00.000Z>, #DateTime<2019-02-05 23:59:59.000Z>, #DateTime<2019-02-06 00:00:00.000Z>, #DateTime<2019-02-06 23:59:59.000Z>, #DateTime<2019-02-07 00:00:00.000Z>, #DateTime<2019-02-07 23:59:59.000Z>, #DateTime<2019-02-08 00:00:00.000Z>, #DateTime<2019-02-08 23:59:59.000Z>, #DateTime<2019-02-09 00:00:00.000Z>, #DateTime<2019-02-09 23:59:59.000Z>, #DateTime<2019-02-10 00:00:00.000Z>, #DateTime<2019-02-10 23:59:59.000Z>, #DateTime<2019-02-11 00:00:00.000Z>, #DateTime<2019-02-11 23:59:59.000Z>, #DateTime<2019-02-12 00:00:00.000Z>, #DateTime<2019-02-12 23:59:59.000Z>, #DateTime<2019-02-13 00:00:00.000Z>, #DateTime<2019-02-13 23:59:59.000Z>, #DateTime<2019-02-14 00:00:00.000Z>, #DateTime<2019-02-14 23:59:59.000Z>, #DateTime<2019-02-15 00:00:00.000Z>, #DateTime<2019-02-15 23:59:59.000Z>, #DateTime<2019-02-16 00:00:00.000Z>, #DateTime<2019-02-16 23:59:59.000Z>, #DateTime<2019-02-17 00:00:00.000Z>, #DateTime<2019-02-17 23:59:59.000Z>, #DateTime<2019-02-18 00:00:00.000Z>, #DateTime<2019-02-18 23:59:59.000Z>, #DateTime<2019-02-19 00:00:00.000Z>, #DateTime<2019-02-19 23:59:59.000Z>, #DateTime<2019-02-20 00:00:00.000Z>, #DateTime<2019-02-20 23:59:59.000Z>, #DateTime<2019-02-21 00:00:00.000Z>, #DateTime<2019-02-21 23:59:59.000Z>, #DateTime<2019-02-22 00:00:00.000Z>, #DateTime<2019-02-22 23:59:59.000Z>, #DateTime<2019-02-23 00:00:00.000Z>, #DateTime<2019-02-23 23:59:59.000Z>, #DateTime<2019-02-24 00:00:00.000Z>, #DateTime<2019-02-24 23:59:59.000Z>, #DateTime<2019-02-25 00:00:00.000Z>, #DateTime<2019-02-25 23:59:59.000Z>, ...]```

I'll get back on the query which is executed on Ecto 2.

**Comment by Brianvdb** [comment]
Okay I downgraded back to Ecto 2 but got the same error. So the error might happen now because I also upgraded Postgrex.

I managed to get it all working by applying my old mix.lock version. With these versions:
Postgrex 0.13.5
and
Ecto 2.2.11

Following query is executed now:

```
SELECT SUM(CASE WHEN t0."inserted_at" > $1 AND t0."inserted_at" < $2 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $3 AND t0."inserted_at" < $4 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $5 AND t0."inserted_at" < $6 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $7 AND t0."inserted_at" < $8 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $9 AND t0."inserted_at" < $10 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $11 AND t0."inserted_at" < $12 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $13 AND t0."inserted_at" < $14 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $15 AND t0."inserted_at" < $16 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $17 AND t0."inserted_at" < $18 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $19 AND t0."inserted_at" < $20 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $21 AND t0."inserted_at" < $22 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $23 AND t0."inserted_at" < $24 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $25 AND t0."inserted_at" < $26 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $27 AND t0."inserted_at" < $28 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $29 AND t0."inserted_at" < $30 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $31 AND t0."inserted_at" < $32 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $33 AND t0."inserted_at" < $34 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $35 AND t0."inserted_at" < $36 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $37 AND t0."inserted_at" < $38 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $39 AND t0."inserted_at" < $40 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $41 AND t0."inserted_at" < $42 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $43 AND t0."inserted_at" < $44 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $45 AND t0."inserted_at" < $46 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $47 AND t0."inserted_at" < $48 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $49 AND t0."inserted_at" < $50 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $51 AND t0."inserted_at" < $52 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $53 AND t0."inserted_at" < $54 THEN 1 ELSE 0 END), SUM(CASE WHEN t0."inserted_at" > $55 AND t0."inserted_at" < $56 THEN 1 ELSE 0 END) FROM "transactions" AS t0 INNER JOIN "programs" AS p1 ON (p1."id" = t0."program_id") AND ((t0."program_id" = p1."id") AND (p1."user_id" = $57)) [{{2019, 2, 1}, {0, 0, 0, 0}}, {{2019, 2, 1}, {23, 59, 59, 0}}, {{2019, 2, 2}, {0, 0, 0, 0}}, {{2019, 2, 2}, {23, 59, 59, 0}}, {{2019, 2, 3}, {0, 0, 0, 0}}, {{2019, 2, 3}, {23, 59, 59, 0}}, {{2019, 2, 4}, {0, 0, 0, 0}}, {{2019, 2, 4}, {23, 59, 59, 0}}, {{2019, 2, 5}, {0, 0, 0, 0}}, {{2019, 2, 5}, {23, 59, 59, 0}}, {{2019, 2, 6}, {0, 0, 0, 0}}, {{2019, 2, 6}, {23, 59, 59, 0}}, {{2019, 2, 7}, {0, 0, 0, 0}}, {{2019, 2, 7}, {23, 59, 59, 0}}, {{2019, 2, 8}, {0, 0, 0, 0}}, {{2019, 2, 8}, {23, 59, 59, 0}}, {{2019, 2, 9}, {0, 0, 0, 0}}, {{2019, 2, 9}, {23, 59, 59, 0}}, {{2019, 2, 10}, {0, 0, 0, 0}}, {{2019, 2, 10}, {23, 59, 59, 0}}, {{2019, 2, 11}, {0, 0, 0, 0}}, {{2019, 2, 11}, {23, 59, 59, 0}}, {{2019, 2, 12}, {0, 0, 0, 0}}, {{2019, 2, 12}, {23, 59, 59, 0}}, {{2019, 2, 13}, {0, 0, 0, 0}}, {{2019, 2, 13}, {23, 59, 59, 0}}, {{2019, 2, 14}, {0, 0, 0, 0}}, {{2019, 2, 14}, {23, 59, 59, 0}}, {{2019, 2, 15}, {0, 0, 0, 0}}, {{2019, 2, 15}, {23, 59, 59, 0}}, {{2019, 2, 16}, {0, 0, 0, 0}}, {{2019, 2, 16}, {23, 59, 59, 0}}, {{2019, 2, 17}, {0, 0, 0, 0}}, {{2019, 2, 17}, {23, 59, 59, 0}}, {{2019, 2, 18}, {0, 0, 0, 0}}, {{2019, 2, 18}, {23, 59, 59, 0}}, {{2019, 2, 19}, {0, 0, 0, 0}}, {{2019, 2, 19}, {23, 59, 59, 0}}, {{2019, 2, 20}, {0, 0, 0, 0}}, {{2019, 2, 20}, {23, 59, 59, 0}}, {{2019, 2, 21}, {0, 0, 0, 0}}, {{2019, 2, 21}, {23, 59, 59, 0}}, {{2019, 2, 22}, {0, 0, 0, 0}}, {{2019, 2, 22}, {23, 59, 59, 0}}, {{2019, 2, 23}, {0, 0, 0, ...}}, {{2019, 2, 23}, {23, 59, ...}}, {{2019, 2, ...}, {0, ...}}, {{2019, ...}, {...}}, {{...}, ...}, {...}, ...]
```

**Comment by josevalim** [comment]
Thanks @Brianvdb! The queries seem to be the same, it just seems that postgrex would convert timestamps to integers automatically before? In any case, it seems that PG is expecting integers so we need to tell it is receiving otherwise? Have you tried this fragment:

    "CASE WHEN ? > ?::timestamp AND ? < ?::timestamp THEN 1 ELSE 0 END"

?

**Comment by Brianvdb** [comment]
Now I have :)

But still receiving the same error:

Executed query:
```
SELECT SUM(CASE WHEN t0."inserted_at" > $1::timestamp AND t0."inserted_at" < $2::timestamp THEN 1 ELSE 0 END) FROM "transactions" AS t0 INNER JOIN "programs" AS p1 ON (p1."id" = t0."program_id") AND ((t0."program_id" = p1."id") AND (p1."user_id" = $3)) [#DateTime<2019-02-01 00:00:00.000Z>, #DateTime<2019-02-01 23:59:59.000Z>, #DateTime<2019-02-02 00:00:00.000Z>, #DateTime<2019-02-02 23:59:59.000Z>, #DateTime<2019-02-03 00:00:00.000Z>, #DateTime<2019-02-03 23:59:59.000Z>, #DateTime<2019-02-04 00:00:00.000Z>, #DateTime<2019-02-04 23:59:59.000Z>, #DateTime<2019-02-05 00:00:00.000Z>, #DateTime<2019-02-05 23:59:59.000Z>, #DateTime<2019-02-06 00:00:00.000Z>, #DateTime<2019-02-06 23:59:59.000Z>, #DateTime<2019-02-07 00:00:00.000Z>, #DateTime<2019-02-07 23:59:59.000Z>, #DateTime<2019-02-08 00:00:00.000Z>, #DateTime<2019-02-08 23:59:59.000Z>, #DateTime<2019-02-09 00:00:00.000Z>, #DateTime<2019-02-09 23:59:59.000Z>, #DateTime<2019-02-10 00:00:00.000Z>, #DateTime<2019-02-10 23:59:59.000Z>, #DateTime<2019-02-11 00:00:00.000Z>, #DateTime<2019-02-11 23:59:59.000Z>, #DateTime<2019-02-12 00:00:00.000Z>, #DateTime<2019-02-12 23:59:59.000Z>, #DateTime<2019-02-13 00:00:00.000Z>, #DateTime<2019-02-13 23:59:59.000Z>, #DateTime<2019-02-14 00:00:00.000Z>, #DateTime<2019-02-14 23:59:59.000Z>, #DateTime<2019-02-15 00:00:00.000Z>, #DateTime<2019-02-15 23:59:59.000Z>, #DateTime<2019-02-16 00:00:00.000Z>, #DateTime<2019-02-16 23:59:59.000Z>, #DateTime<2019-02-17 00:00:00.000Z>, #DateTime<2019-02-17 23:59:59.000Z>, #DateTime<2019-02-18 00:00:00.000Z>, #DateTime<2019-02-18 23:59:59.000Z>, #DateTime<2019-02-19 00:00:00.000Z>, #DateTime<2019-02-19 23:59:59.000Z>, #DateTime<2019-02-20 00:00:00.000Z>, #DateTime<2019-02-20 23:59:59.000Z>, #DateTime<2019-02-21 00:00:00.000Z>, #DateTime<2019-02-21 23:59:59.000Z>, #DateTime<2019-02-22 00:00:00.000Z>, #DateTime<2019-02-22 23:59:59.000Z>, #DateTime<2019-02-23 00:00:00.000Z>, #DateTime<2019-02-23 23:59:59.000Z>, #DateTime<2019-02-24 00:00:00.000Z>, #DateTime<2019-02-24 23:59:59.000Z>, #DateTime<2019-02-25 00:00:00.000Z>, #DateTime<2019-02-25 23:59:59.000Z>, ...]
```

Stacktrace:
```
 ** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got #DateTime<2019-02-02 00:00:00.000Z>. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
        (postgrex) lib/postgrex/type_module.ex:713: Postgrex.DefaultTypes.encode_params/3
        (postgrex) lib/postgrex/query.ex:62: DBConnection.Query.Postgrex.Query.encode/3
```

**Comment by josevalim** [comment]
Ok, thanks. Still not sure why this is happening then, I will need a way to look deeper into this. Can you perhaps isolate this into an app that reproduces this error?

**Comment by Brianvdb** [comment]
Sure, i'll get back to this ASAP and provide a sample project in the next following days.

**Comment by josevalim** [comment]
Ping!

**Comment by josevalim** [comment]
Closing, please let us know if you have more information and we will gladly reopen it, thank you.
