### ISSUE TITLE
Embedded schema reference to UUIDs casts to wrong type

### ISSUE THREAD

**Issue by timbuchwaldt** [elixir-ecto/ecto#2922]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.1
* Ecto version (mix deps): 3.0.7
* Database adapter and version (mix deps): postgrex 0.14.1
* Operating system: macOS

### Current behavior

When setting up a `belongs_to` reference in an embedded schema to a `binary_id` (normal) schema the following error occurs when `cast`-ing the `user_id` field:

```** (ArgumentError) cannot load `"f8fd18d2-f294-450b-baf4-a56df4cc62ad"` as type :id for field `user_id` in schema Demeter.Accounts.Permission```

This can be fixed by setting the `type` option on `belongs_to` to either `Ecto.UUID` or `:binary_id`

### Expected behavior

Ecto automatically detects the usage of `:binary_id` and doesn't try to cast to `:id`

**Comment by josevalim** [comment]
Can you please provide some code samples? How is your schemes defined?
Which function are you calling that raises the error? What is the complete
stacktrace? Thanks!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by thomasweingardt** [comment]
permission.ex:
```
defmodule Demeter.Accounts.Permission do
  @moduledoc """
  Permission schema
  """
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :name, :string

    belongs_to :user, Demeter.Accounts.User
  end

  @doc false
  def changeset(permission, attrs) do
    permission
    |> cast(attrs, [:name])
    |> cast_assoc(:user)
    |> validate_required([:name])
  end
end
```

user.ex:
```
defmodule Demeter.Accounts.User do
  @moduledoc """
  User schema
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "users" do
    field :external_id, Ecto.UUID
    field :name, :string

    belongs_to :group, Demeter.Accounts.Group

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:external_id, :name])
    |> validate_required([:external_id, :name])
    |> unique_constraint(:name)
    |> unique_constraint(:external_id)
  end
end
```

test.exs:
```
    test "add user to permission" do
      {:ok, user} = Accounts.create_user(@valid_user_attrs)

      {:ok, group} = Accounts.create_group(%{name: "root"})

      permission = %Demeter.Accounts.Permission{name: "Admin", user_id: user.id}

      group
      |> Ecto.Changeset.change(permissions: [permission])
      |> Repo.update!()

      group = Repo.get(Group, group.id)

      assert length(group.permissions) == 1
      assert group.permissions
             |> List.first()
             |> fn(perm) -> perm.user_id end.() == user.id
    end
```

Stacktrace:
```
 ** (ArgumentError) cannot load `"3a9d82e7-1655-4ac9-93a5-1599457d946b"` as type :id for field `user_id` in schema Demeter.Accounts.Permission
     code: group = Repo.get(Group, group.id)
     stacktrace:
       (ecto) lib/ecto/schema/loader.ex:108: Ecto.Schema.Loader.bad_load!/4
       (ecto) lib/ecto/schema/loader.ex:103: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
       (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (ecto) lib/ecto/type.ex:593: Ecto.Type.load_embed/3
       (ecto) lib/ecto/type.ex:799: Ecto.Type.process_loaders/3
       (ecto) lib/ecto/schema/loader.ex:94: Ecto.Schema.Loader.adapter_load/6
       (ecto) lib/ecto/repo/queryable.ex:193: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (ecto) lib/ecto/repo/queryable.ex:152: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
       (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
       test/demeter/accounts/accounts_test.exs:148: (test)

```

**Comment by josevalim** [comment]
@thomasweingardt what happens if you set the foreign_key_type to `:binary_id` in belongs_to?

    belongs_to :user, Demeter.Accounts.User, foreign_key_type: :binary_id

?

**Comment by thomasweingardt** [comment]
@josevalim It works this way (originally described as quick fix by @timbuchwaldt):
```
belongs_to :user, Demeter.Accounts.User, type: :binary_id
```
as well as this way:
```
@foreign_key_type :binary_id
  embedded_schema do
  ...
```

**Comment by josevalim** [comment]
Right. It has to be done explicitly. We cannot detect automatically because that would cause cyclic dependencies in the compiler. For example, if you do `Post.has_many(Comment)` and `Comment.belongs_to(Post)`,  that would be cyclical and the compiler would deadlock. There isn't anything we can do here.

**Comment by johannesE** [comment]
I think those foreign key constraints should be added to the documentation on https://hexdocs.pm/phoenix/1.3.0-rc.2/custom_primary_key.html

It works for me with
Country
```
  @primary_key {:code, :string, []}
  @derive {Phoenix.Param, key: :code}
  @foreign_key_type :string
  schema "countries" do
    field :name, :string

    timestamps()
  end
```

User
```
    belongs_to :country, Databaum.Countries.Country, foreign_key: :country_code, type: :string
```

But I'm not sure I'm doing anything right at this point... 😅
