### ISSUE TITLE
Improve documentation on Elixir.Adapter.checkout/3 behaviour callback

### ISSUE THREAD

**Issue by Qqwy** [elixir-ecto/ecto#2935]
Currently, it is very difficult to understand how [Ecto.Adapter.checkout/3](https://hexdocs.pm/ecto/Ecto.Adapter.html#c:checkout/3) should be implemented by an adapter.
Furthermore, it is difficult to see what is going on in the reference adapter implementations of  MySQL and Postgres because [the implementation in ecto_sql](https://github.com/elixir-ecto/ecto_sql/blob/04d9b75e491021dc3e2d5850ab65ae5573f26c68/lib/ecto/adapters/sql.ex#L478) [redirects in a roundabout, undocumented way to](https://github.com/elixir-ecto/ecto_sql/blob/04d9b75e491021dc3e2d5850ab65ae5573f26c68/lib/ecto/adapters/sql.ex#L869) [DBConnection.run](https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection.ex#L706)(?)

Adapter-implementers would be greatly helped if:

- There is more information on the kind of input/output that is expected for `checkout/3`.
- There is an explanation on how `checkout/3` is expected to make the handle of a pool that was checked out available to the inner function.
- There are some examples for `checkout/3`.
- There is an explanation of how to implement it if you do not (or cannot) use a pool.

**Comment by josevalim** [comment]
> There is more information on the kind of input/output that is expected for checkout/3.

The only argument is a function. The `opts` is the shared options all repo/adapter operations receieve. It returns the result of the function.

> There is an explanation on how checkout/3 is expected to make the handle of a pool that was checked out available to the inner function.

You need to make it so the code inside the function always uses the same connection. If you don't have the idea of connections or a pool, then just executing the given function is fine. The main goal here is performance (i.e. many database have caches based per connection).

> There are some examples for checkout/3.

We can add to `Repo.checkout/2` an example like:

```elixir
Repo.checkout(fn ->
  for _ <- 100 do
    Repo.insert!(%Post{})
  end
end)
```

> There is an explanation of how to implement it if you do not (or cannot) use a pool.

As mentioned above, the main goal is to share caches and performance. If you don't have a pool or anything to share, just invoking the fun is fine! :+1:

-----

Do the replies above help? Can you send a PR based on them?

**Comment by Qqwy** [comment]
Yes, this helps a lot! I'll make a PR for it.

There's only one question remaining:

> You need to make it so the code inside the function always uses the same connection.

I we _do_ have a pool, how is this done? The function that is passed in has no parameters so we do not pass the connection as an argument (which would be the stateless/pure approach). 
Lacking that, there has to be some stateful way to keep track of which connection is the ''checked out' connection.
Is this stateful approach bound to any rules, or something that is completely up to the adapter? And how do the Postgres and MySQL adapters do it? (probably some implementation detail of DBConnection?)

**Comment by josevalim** [comment]
> I we do have a pool, how is this done?

Either by process tracking or using pdict. DBConnection did the latter but IIRC it does the former now. There are not many rules. Just remember the goal is to avoid using different connections for performance or beacuse of something semantic at the data store level. It is left "empty" on purpose.
