### ISSUE TITLE
Document how Ecto.Adapter.Queryable should be implemented

### ISSUE THREAD

**Issue by Qqwy** [elixir-ecto/ecto#2936]
The documentation of [Ecto.Adapter.Queryable](https://hexdocs.pm/ecto/Ecto.Adapter.Queryable.html) is unclear of what is expected by the callbacks.

Especially if we have datastores for which only some types of queries make sense (like for instance simple key-value stores that only expose `get` and `insert`), it is not clear how this should be done using the given behaviour callbacks.

**Comment by josevalim** [comment]
It is a module to handle queries. If you can process a full Ecto.Query,
then we cannot so much for you. I.E it wouldn’t fit a simple key value
store.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Qqwy** [comment]
:thinking: So if I would want to e.g. expose/allow only `Repo.get` when people use my Ecto adapter, how would one go about it?

**Comment by josevalim** [comment]
Use before_compile to generate a custom function inside the repo. The
functionality you want to expose is not part of Ecto default.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Qqwy** [comment]
I see. For posterity: All calls that are done directly on a Repo are injected using `before_compile`. Ecto itself injects `get/get_by/all/stream/etc...` [iff the adapter implements `Ecto.Queryable`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L227).
This means that you can instead manually create your own implementations of (some of) these functions.

**Comment by josevalim** [comment]
@Qqwy Ecto.Schema.Loader is private API. You can probably use Repo.load though.
