### ISSUE TITLE
Performing an adapter-specific dump

### ISSUE THREAD

**Issue by Qqwy** [elixir-ecto/ecto#2943]
I'm in the process of writing (attempting to write...) a Riak Ecto3 adapter.

Since it cannot rely on ecto_sql and has no proper way to implement most of `Ecto.Adapter.Queryable` and `Ecto.Adapter.Schema` the few calls like `get` and `update` will be implemented directly by the adapter.

Loading results after fetching them from the datastore can be done by using `Repo.load`, which is injected by Ecto, directly. However, there is no similar `dump` being injected.

As far as I am able to find, Ecto itself (When you are able to implement `Ecto.Adapter.Schema`) uses `Ecto.Type.adapter_dump(adapter_module, type, value)` for this. However, [this is a private API](https://github.com/elixir-ecto/ecto/blob/b1819d48e32f1ea68e3abc738bcd4b0758e3fdeb/lib/ecto/type.ex#L805).

So my question:

- Is there another proper way that uses a public API to let Ecto dump a `schema`-struct's fields into the format supported by the particular adapter (which will call the adapter's `dumpers` under the hood)?
- And if there is not, I think a method to do this should be added, such that it is possible for adapters to be implemented without depending on either `Queryable`/`Schema` or a private API. :slightly_smiling_face:

**Comment by josevalim** [comment]
Use `Ecto.Type.adapter_dump`, we will make it public.
