### ISSUE TITLE
Ecto.Repo.Schema.insert should wrap changeset with actual Repo not pid

### ISSUE THREAD

**Issue by bartekupartek** [elixir-ecto/ecto#2952]
### Current behavior

Current `Ecto.Repo.Schema.insert!(pid, struct, opts)` puts `pid` as `repo`

```elixir
    # On insert, we always merge the whole struct into the
    # changeset as changes, except the primary key if it is nil.
    changeset = put_repo_and_action(changeset, :insert, name)
```
in results `prepare_changes` has `changeset.repo` with `pid` and `update_all` doesn't work
```elixir
def create_comment(comment, params) do
  comment
  |> cast(params, [:body, :post_id])
  |> prepare_changes(fn changeset ->
       if post_id = get_change(changeset, :post_id) do
         query = from Post, where: [id: ^post_id]
         changeset.repo.update_all(query, inc: [comment_count: 1])
       end
       changeset
     end)
end
```
### Expected behavior

`Ecto.Repo.Schema.insert` should return `Repo` not `pid`

**Comment by josevalim** [comment]
I tried it quickly locally and I could not reproduce it. Do you have a sample app or a failing test that reproduces the issue? Thank you!

**Comment by bartekupartek** [comment]
sorry for not giving right example, I've following scenario on my app: https://github.com/bartekupartek/ecto/commit/c704588004df7d512688fee467eed26b3caebd5c#diff-122d0a4bbce6a65cc1523584a00193aaR1170

**Comment by bartekupartek** [comment]
```elixir
Ecto.TestRepo.start_link(name: :tenant_db)

defmodule Ecto.TestDynamicRepo do
  def insert!(pid, struct, opts \\ []) do
    Ecto.Repo.Schema.insert!(pid, struct, opts)
  end

  def update_all(pid, queryable, updates, opts \\ []) do
    Ecto.Repo.Queryable.update_all(pid, queryable, updates, opts)
  end
end

changeset =
  %MySchema{id: 1}
  |> Ecto.Changeset.cast(%{x: "one"}, [:x])
  |> Ecto.Changeset.prepare_changes(fn %{repo: repo} = changeset ->
    Process.put(:ecto_repo, repo)
    # repo it's pid of :tenant_db process,
    # instead of repo.update_all 
    # workaround it by Ecto.TestDynamicRepo.update_all(repo, cs, updates)
    changeset
  end)

pid = Process.whereis(:tenant_db)
Ecto.TestDynamicRepo.insert!(pid, changeset)
assert Process.get(:ecto_repo) == pid # shouldn't it be reusable Ecto.TestDynamicRepo?
```
I can workaround it but I'm thinking if there is not too much workarounds with using provided repo `:name` option :(

**Comment by josevalim** [comment]
That should be also fixed on master. Isn’t it? If not, please provide a
failing test and I will fix it.

I wouldn’t say those are work-arounds. In my opinion they are legitimate
bugs for a feature we have been slowing working towards to but never
finished. So your help is very appreciated! :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by bartekupartek** [comment]
It still doesn't work with DynamicRepo module, but it's working with Repo, if only Repo would work with custom pids or repo names it would work at all, thanks :)
