### ISSUE TITLE
Passing sigils to select in from fails to compile

### ISSUE THREAD

**Issue by jegaxd26** [elixir-ecto/ecto#2958]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): none
* Ecto version (mix deps): 3.0.8
* Database adapter and version (mix deps): none
* Operating system: os x Mojave 10.14.3

### Current behavior

Passing list sigils to select (like ~w(id name url)a) fails to compile with error `:id is not a valid query expression` I have created an example repo [here](https://github.com/jegaxd26/ecto_sigils) . I've commented the functions that break compilation, if you uncomment them, mix fails to compile the project.

### Expected behavior

I would expect sigils to work just as lists

**Comment by wojtekmach** [comment]
You need to escape all non-literals in queries, instead of:

```elixir
from(u in __MODULE__, select: @fields)
from(u in __MODULE__, select: ~w(name)a)
```

do:

```elixir
from(u in __MODULE__, select: ^@fields)
from(u in __MODULE__, select: ^~w(name)a)
```

PS thanks for the sample app, it was very helpful to reproduce it!
