### ISSUE TITLE
Jason not an optional dependency anymore

### ISSUE THREAD

**Issue by DianaOlympos** [elixir-ecto/ecto#2968]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version: PostgreSQL 11.0
* Ecto version (mix deps): 

```
ecto (Hex package) (mix)
  locked at 3.1.0 (ecto) 42e669e1
```

* Database adapter and version (mix deps):
```
postgrex (Hex package) (mix)
  locked at 0.14.1 (postgrex) 63247d4a
```
* Operating system:
Linux (Fedora)
### Current behavior

Compilation fail with error
```
==> ecto
Compiling 54 files (.ex)

== Compilation error in file lib/ecto/json.ex ==
** (ArgumentError) Jason.Encoder is not available
    (elixir) lib/protocol.ex:69: Protocol.assert_protocol!/2
    lib/ecto/json.ex:1: (file)
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Expected behavior

Compilation pass without Jason as it is an optional dependency that we do not use.

I wonder if this is not linked to https://github.com/elixir-ecto/ecto/commit/6f01b8bc35f731f9289bb13e4e223e29ff9214cb#diff-a0582039f639774aae33fa16c83f4538

**Comment by DianaOlympos** [comment]
Far too fast @josevalim :heart: :blue_heart: :purple_heart: :yellow_heart: :green_heart:

**Comment by Sebisnow** [comment]
Impressively fast. Hex still holds the version 3.1.0 without your change. Publishing the fix via hex would be great!
