### ISSUE TITLE
3.1 Migrator hangs on concurrent index creation

### ISSUE THREAD

**Issue by novaugust** [elixir-ecto/ecto#2977]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  11.2
* Ecto version (mix deps):  3.1.1
* Database adapter and version (mix deps):  ecto_sql 3.1.1
* Operating system: macos

### Current behavior

In trialing ecto 3.1 from 3.0.8, rebuilding my database stops on any migration with a concurrent index being built. Removing the `concurrent: true` option from the migration allows it to succeed and continues until tripping over the next instance.

I built a minimal reproduction repro here: https://github.com/novaugust/ecto-concurrent-index-bug

This migration, in that repo, will cause the migrator to hang.
```ex
defmodule Hello.Repo.Migrations.AddIndex do
  use Ecto.Migration
  @disable_ddl_transaction true

  def change do
    create index(:widgets, :foo, concurrently: true)
  end
end
```

Clone it and run the following to see the hang:
```
mix do deps.get, ecto.create, ecto.migrate
```

### Expected behavior

Migrations should run =)

**Comment by josevalim** [comment]
I will improve the CHANGELOG but you also need to disable the migration lock:

    config :app, App.Repo, migration_lock: nil

(which is Ecto 2.x behaviour).

**Comment by novaugust** [comment]
Thanks, I can confirm that fixes it.
