### ISSUE TITLE
Changeset mistakes association change from `[]` to `[]` as a change

### ISSUE THREAD

**Issue by princemaple** [elixir-ecto/ecto#2994]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): pg 11
* Ecto version (mix deps): 3.1.3
* Database adapter and version (mix deps): postgrex 0.14.2
* Operating system: alpine docker on windows hyper-v

### Current behavior

A many_to_many  B, load A with B's preloaded (should be `[]`), get the changeset, put_assoc `[]`, and changeset.changes includes the B list

### Expected behavior

With the above operation, changeset should identify the B list as not changed.

### Note

If A does have one or more B, the changeset works as expected, when no connections to B have been added or removed, the field does not show up in changes, despite having called put_assoc

**Comment by princemaple** [comment]
Thanks a lot. Will be able to remove a few function clauses once this is out.

**Comment by JonRowe** [comment]
I think this is causing validations on associations not to run when they are empty lists. I want to validate newly created schemas to ensure they always have one member, and as it was `[]` and now is `[]` it's considered valid, despite the fact that I have `validate_length`...

**Comment by josevalim** [comment]
Can you please open up a new issue? If you can provide a small app that
reproduces it, even better!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
