### ISSUE TITLE
Can't access elixir-ecto Google Group

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [elixir-ecto/ecto#2999]
Hello, whatever I try (incognito window or logged in), I can't access the Google Group. Should it be removed from `README.md`?

**Comment by wojtekmach** [comment]
The google group url in README [1] is correct and still active, seems you might be having some connectivity issues.

[1] https://groups.google.com/forum/#!forum/elixir-ecto

**Comment by Fire-Dragon-DoL** [comment]
Apologize for reiterating this, are you sure it's not some kind of permission issue (e.g. people can view it if they are already logged in/joined but external can't)?

My connection is fine, I can join the elixir-lang-core but not the ecto group. Tested with a pristine browser too (Firefox):

![permission_issue](https://user-images.githubusercontent.com/1329559/57562079-a84b7a80-7344-11e9-94a5-e79a052399bd.png)

**Comment by wojtekmach** [comment]
Hmm, I just noticed that in incognito window it says the group doesn’t exist, so it seems we need to be logged in to view the group even though it’s public. I saw that on the left screenshot you’re logged in but not on the right screenshot, so I guess that’s the issue?

**Comment by Fire-Dragon-DoL** [comment]
Mh no unfortunately it's not that:

![group_not_exists](https://user-images.githubusercontent.com/1329559/57564408-ef933480-735f-11e9-8966-5f1e2ae039d1.png)

**Comment by Fire-Dragon-DoL** [comment]
Oh it looks like I can see everything if I log in firefox.
Must be some bugged cookies.

The mailing list is not public though (weird), thanks!

![firefox_logged_in](https://user-images.githubusercontent.com/1329559/57564443-692b2280-7360-11e9-80aa-43556d03e269.png)

**Comment by Fire-Dragon-DoL** [comment]
This just happened on the Phoenix slack channel:

```
styles [14:49]
I'm having the exact problem asked here: https://elixirforum.com/t/one-form-multiple-models-stored-in-database/2420/3 but I didn't see any resolution on the referenced threads. I also noticed you can't access the mailing list anymore. Does anyone have any information on this?
Elixir Forum
One form, multiple models stored in database
Btw, we just went through an example in the mailing list too: https://groups.google.com/forum/#!topic/elixir-ecto/_QHS-IY-sQY Please write about such examples (articles, blogs, docs, etc) if you find they are useful so it helps people doing similar in the future.
Nov 16th, 2016
```
