### ISSUE TITLE
Ecto.Type.dump, `type(value, type)` and function signature alignement

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [elixir-ecto/ecto#3000]
Hello!
I've been dealing with casting lately and I found extremely confusing that `type(value, type)` (macro when you use `from` in Ecto.Query) and `Ecto.Type.dump` use arguments in opposite order:

```elixir
Ecto.Type.dump(type, value)
type(value, type)
```

Ideally the arguments are "aligned" to follow the same order.
Since I'm here, may I suggest an Ecto.Type.dump! function so that using `Repo.query!("...", [Type.dump!(arg1), Type.dump!(arg2)]` doesn't require to manually unwrap each argument?

Apologize if I'm posting this here, but as I reported in another issue, I can't access elixir-ecto in any way, I've been try to do so the last 2 days.

**Comment by josevalim** [comment]
I am personally not bothered by it. They are used in different contexts. It
is like the Regex and String module that have similar functions but with
different argument others. In any case, “fixing” this would be a breaking
change and we have declared that Ecto’s API is stable. So there is no
chance it will happen. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by wojtekmach** [comment]
Yeah it's a bit unfortunate but we can't do anything about it anymore as not to break API.

> Type.dump!(arg1)

Did you mean to write `Ecto.Type.dump!(type, arg1)` or did you have something else in mind?

**Comment by wojtekmach** [comment]
I re-read the first post and I'm pretty sure you had Ecto.Type.dump!(type, arg1) in mind but please correct me if I'm wrong! We do need to pass the type argument explicitly because otherwise we don't know what to typecast to.

Personally I'd be ok with having `Ecto.Type.dump!/2` that under the hood calls `Ecto.Type.dump/2` as a convenience, but this is pretty low-level API that vast majority of users probably don't use directly (instead use it through changesets and schemas) so not 100% sure about adding this.

**Comment by Fire-Dragon-DoL** [comment]
Yes @wojtekmach , I meant `Ecto.Type.dump!(type, arg)`.

Main reason for me is when you use `Repo.query!`, you have to cast all arguments.
Ecto doesn't support table-less queries, so if I want to run `select set_limit(?)` I'm forced to use `Repo.query!`, so the `dump!` reduces the pain a bit, otherwise I have to dump everything upfront , then pass as arguments.

Aside from that, isn't counter productive to declare an API as stable? It seems like "forcing" a stop on software evolution.

Thanks everyone, for now, I'll create my wrapper module for Ecto.Type, cheers!

**Comment by josevalim** [comment]
There is a discussion on the ElixirForum about being stable, so I won't rehash the points here, but forcing applications and libraries to go through version cycles also has its cons.
