### ISSUE TITLE
Ecto.Adapters.SQL.to_sql does not add preloads to the result query string

### ISSUE THREAD

**Issue by ayrat555** [elixir-ecto/ecto#3002]
### Current behavior

the ecto query is 
```
#Ecto.Query<from b0 in Explorer.Chain.Block, where: b0.consensus == true,
 order_by: [desc: b0.number], limit: ^4,
 preload: [:rewards, :transactions, {:miner, :names}]>
```

generated sql string is 
```
{"SELECT b0.\"hash\", b0.\"consensus\", b0.\"difficulty\", b0.\"gas_limit\", b0.\"gas_used\", b0.\"nonce\", b0.\"number\", b0.\"size\", b0.\"timestamp\", b0.\"total_difficulty\", b0.\"internal_transactions_indexed_at\", b0.\"inserted_at\", b0.\"updated_at\", b0.\"miner_hash\", b0.\"parent_hash\" FROM \"blocks\" AS b0 WHERE (b0.\"consensus\" = TRUE) ORDER BY b0.\"number\" DESC LIMIT $1",
 [4]}
```

### Expected behavior

sql query should include preloads

**Comment by josevalim** [comment]
The preloads are executed as separate queries, to avoid the number of data being sent over the wire. For example, if you are bring posts with all comments and you have M posts and N comments, if we did in a single query, it would return `M * N` rows. With separate queries, it returns `M + N`, reducing the amount of date to transfer and decode.
