### ISSUE TITLE
Multi.insert does not validate structs

### ISSUE THREAD

**Issue by turion** [elixir-ecto/ecto#3004]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): cockroach 19.1.0
* Ecto version (mix deps): 2.2.11
* Operating system: NixOS

### Current behavior

Assume I've defined a schema in a module `MyStruct` and a corresponding `changeset` function.
Then `Ecto.Multi.insert(MyStruct{foo: "invalid})` does not perform any validations. It simply calls `Ecto.Changeset.change(MyStruct{foo: "invalid})`, which doesn't perform validations, and loads that into the database

### Expected behavior

It validates in the same way as `Ecto.Repo.insert`.

**Comment by josevalim** [comment]
Yes. Structs are always inserted as is. If you want validation, you need to call the appropriate changeset function. Otherwise Ecto doesn't know how to convert a strucct to a changeset, we wouldn't know where the changeset is defined, as there is no coupling to "main changeset function".
