### ISSUE TITLE
Migrating from Ecto 2.0 to Ecto 3.0 disallows loading of decimal types.

### ISSUE THREAD

**Issue by jekku** [elixir-ecto/ecto#3009]
### Environment

* Elixir version: 1.8.0
* Database and version: Postgres 10.x
* Ecto version: 3.0
* Database adapter and version: Ecto.Adapters.Postgres (ecto_sql 3.1.4)
* Operating system:

### Current behavior

Precontext:

I have moved an app from Ecto 2.0 to Ecto 3.0. My decimal types could not be dumped out properly anymore after the move. This is an error message similar to what I encountered:

```
cannot load `%{"coef" => 1000, "exp" => -1, "sign" => 1}` as type :decimal for field `:some_field` in schema App.Schema.MySchema
```

This is the stacktrace if it helps:

```
             (ecto) lib/ecto/schema/loader.ex:76: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
             (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
             (ecto) lib/ecto/type.ex:586: Ecto.Type.load_embed/3
             (ecto) lib/ecto/schema/loader.ex:71: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
             (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
             (ecto) lib/ecto/type.ex:586: Ecto.Type.load_embed/3
             (ecto) lib/ecto/type.ex:800: Ecto.Type.process_loaders/3
             (ecto) lib/ecto/repo/queryable.ex:339: Ecto.Repo.Queryable.struct_load!/6
             (ecto) lib/ecto/repo/queryable.ex:201: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
             (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
             (ecto) lib/ecto/repo/queryable.ex:158: Ecto.Repo.Queryable.execute/4
             (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
             (ecto) lib/ecto/repo/preloader.ex:189: Ecto.Repo.Preloader.fetch_query/8
             (ecto) lib/ecto/repo/preloader.ex:120: Ecto.Repo.Preloader.preload_assoc/10
             (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
             (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior

The decimal type used in Ecto 2.0 should have been forwards compatible to Ecto 3.0. If there is any technique I could use to migrate the old struct / embed, that would be great too!

**Comment by josevalim** [comment]
Hi @jekku. Ecto 3.0 is a new major version, so we can break compatibility with previous versions. In particular, I believe the format you showed was supported by accident, so we don't have plans to support it in Ecto 3. Luckily, you can always define a custom Ecto.Type that supports any format you want: https://hexdocs.pm/ecto/Ecto.Type.html

**Comment by jekku** [comment]
Thanks @josevalim . That helps a lot. I would like to add a little more detail into it, just in case somebody else bumps into the same problem.

The problem I mentioned above occurs when the `Decimal` type is inside an Embedded Schema only. If it's in a regular schema drawn directly from a regular table, the compatibility works just fine.

When it's drawn from a table directly, the keys are atoms, which is dump-compatible with the Decimal library.

```ex
# example
%{coef: 5, sign: 0, exp: -1}
```

When it's inside an embedded schema, it is dumped as a map with stringified keys, which is dump-incompatible with the Decimal library.

```ex
#example
%SomeStruct{amount: %{"coef" => 5, "sign" => 0, "exp" => -1}}
```

In order to avoid this problem, I used your suggestion and created a custom Ecto.Type that converts the map with string keys into a Decimal struct that looks like:

```ex
defmodule MyApp.CustomTypes.EmbeddedDecimal do
  @behaviour Ecto.Type

   def type, do: :decimal

   def cast(value) when is_integer(value) do
    {:ok, Decimal.new(value)}
  end

   def cast(value) when is_float(value) do
    {:ok, Decimal.from_float(value)}
  end

   def cast(%Decimal{} = value) do
    {:ok, value}
  end

   def cast(%{"coef" => coef, "exp" => exp, "sign" => sign}) do
    {:ok, Decimal.new(sign, coef, exp)}
  end

   def cast(_), do: :error

   def load(value) when is_integer(value) do
    {:ok, Decimal.new(value)}
  end

   def load(%Decimal{} = value) do
    {:ok, value}
  end

   def load(%{"coef" => coef, "exp" => exp, "sign" => sign}) do
    {:ok, Decimal.new(sign, coef, exp)}
  end

   def load(_), do: :error

   def dump(%Decimal{} = value) do
    {:ok, value}
  end

   def dump(%{"coef" => coef, "exp" => exp, "sign" => sign}) do
    {:ok, Decimal.new(sign, coef, exp)}
  end

   def dump(_), do: :error
end
```

**Comment by jekku** [comment]
Weirdly enough this only happens when MIX_ENV=test in my case. In any other envs it works just fine. But this will do and is a sure way to avoid any bad accidents. Tests are boss.
