### ISSUE TITLE
Missing 3.1.5 tag

### ISSUE THREAD

**Issue by m1ome** [elixir-ecto/ecto#3013]
### Current behavior
Ecto have a `3.1.5` on https://hexdocs.pm/ecto/Ecto.html but missing in https://github.com/elixir-ecto/ecto/tags and https://github.com/elixir-ecto/ecto/releases.

Jumping from hexdocs to code may be broken.

### Expected behavior
`3.1.5` should be in `tags` and `releases`

**Comment by josevalim** [comment]
Thanks, fixed!
