### ISSUE TITLE
embeds_one requires id field on cast_embed

### ISSUE THREAD

**Issue by Hermanverschooten** [elixir-ecto/ecto#3017]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version: PostgreSQL 11.3
* Ecto version (mix deps): 3.1.4
* Database adapter and version (mix deps): postgrex 0.14.3
* Operating system: OSX 10.14.5

### Current behavior
I have this schema:

```
schema "suppliers" do
  field :name, string
  embeds_one :info, Info, on_replace: :delete do
    field :account, :string
  end
end

def changeset(supplier, attrs) do
  supplier
  |> cast(attrs, [:name])
  |> cast_embed(:info, with: &info_changeset/2)
end

def info_changeset(schema, attrs) do
  schema
  |> cast(attrs, [:account])
end
attrs = %{ "name" => "Herman", "info" => %{ "account" => "1234" }}

%Supplier
|> Suppliers.Supplier.changeset(attrs)
|> Repo.insert()
```
fails with
```
** (Ecto.NoPrimaryKeyValueError) struct `%Suppliers.Supplier.Info{account: nil, id: nil}` is missing primary key value
```

### Expected behavior

It should insert the record, not complain about a missing id.

if I  add an `id` field to the embedded `info`, it works, uses a generated `id` though.
Or if I force the primary_key to false in the `embeds_one`'s options then it works.

I see 2 issues with this:

1.  Why should I need to add an `id` field to my `info` to make it work out of the box. I do not need to do this with `embeds_many`
2. Why is there an `id` in `embeds_one` in the first place, there can be only one.

**Comment by josevalim** [comment]
Can you provide the complete stacktrace? Is it raising in the insert line?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Hermanverschooten** [comment]
```
[error] #PID<0.1069.0> running OvlInvWeb.Endpoint (connection #PID<0.1068.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: PUT /api/suppliers/12
** (exit) an exception was raised:
    ** (Ecto.NoPrimaryKeyValueError) struct `%OvlInv.Suppliers.Supplier.Info{account: nil, client_ref: nil, id: nil}` is missing primary key value
        (ecto) lib/ecto/embedded.ex:156: anonymous fn/3 in Ecto.Embedded.autogenerate_id/5
        (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/embedded.ex:155: Ecto.Embedded.autogenerate_id/5
        (ecto) lib/ecto/embedded.ex:111: Ecto.Embedded.to_struct/4
        (ecto) lib/ecto/embedded.ex:62: anonymous fn/6 in Ecto.Embedded.prepare/5
        (stdlib) maps.erl:257: :maps.fold_1/3
        (ecto) lib/ecto/repo/schema.ex:332: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
        (ecto) lib/ecto/repo/schema.ex:914: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
        (ovl_inv) lib/ovl_inv_web/controllers/supplier_controller.ex:31: OvlInvWeb.SupplierController.update/2
        (ovl_inv) lib/ovl_inv_web/controllers/supplier_controller.ex:1: OvlInvWeb.SupplierController.action/2
        (ovl_inv) lib/ovl_inv_web/controllers/supplier_controller.ex:1: OvlInvWeb.SupplierController.phoenix_controller_pipeline/2
        (ovl_inv) lib/ovl_inv_web/endpoint.ex:1: OvlInvWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (ovl_inv) lib/ovl_inv_web/endpoint.ex:1: OvlInvWeb.Endpoint.plug_builder_call/2
        (ovl_inv) lib/plug/debugger.ex:122: OvlInvWeb.Endpoint."call (overridable 3)"/2
        (ovl_inv) lib/ovl_inv_web/endpoint.ex:1: OvlInvWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/herman/Projects/ovl_inv/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
```

**Comment by Hermanverschooten** [comment]
I am sorry, upon reflection, the error was on `update` not create. But even then the issue still stands, I believe, with regards to the necessity of the primary for an `embeds_one`.

**Comment by josevalim** [comment]
Can you please post the whole schema module? Do you have @primary_key set
anywhere?

The reason why we require the ID is to know when you are replacing or
keeping the same embed. In any case, it is not something we can change, as
it would be a breaking change. But the ID should be generated by default. I
am surprised that it isn’t. Or you should explicitly disable it as you
mentioned.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
```elixir
defmodule OvlInv.Suppliers.Supplier do
  use Ecto.Schema
  import Ecto.Changeset

  schema "suppliers" do
    field :city, :string
    field :email, :string
    field :name, :string
    field :street, :string
    field :tel, :string
    field :vat, :string
    field :supplier, :boolean, default: true, load_in_query: false
    field :supplier, :boolean, default: false, load_in_query: false
    field :volunteer, :boolean, default: false, load_in_query: false

    embeds_one :info, Info, on_replace: :delete do
      field :account, :string
      field :client_ref, :string
    end

    timestamps()
  end

  @doc false
  def changeset(supplier, attrs) do
    IO.inspect(attrs)

    supplier
    |> IO.inspect()
    |> cast(attrs, [:name, :street, :city, :vat, :email, :tel])
    |> cast_embed(:info, with: &info_changeset/2)
    |> validate_required([:name, :street, :city])
  end

  def info_changeset(schema, attrs) do
    schema
    |> cast(attrs, [:account, :client_ref])
  end
end
```

**Comment by Hermanverschooten** [comment]
hah, I noticed a bug with posting it here, I have the field `suppliers` double, one should be `customer`.

**Comment by josevalim** [comment]
Yeah, I double checked the docs and it does generate a primary key by
default, with autogenerated values, so you have to opt out. Can you tell me
if it is complaining that the new embed doesn’t have a primary key or is it
the one being replaced?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
Looking at the stack trace, I would think the one being replaced, as it shows all fields as `nil` and has `id: nil` in it.

**Comment by Hermanverschooten** [comment]
Definitely the one being replaced, I tested it. So if your embedded field has no id, you MUST set `primary_key` to false or it will blow up, or you need to supply a dummy key field in your changes.

**Comment by josevalim** [comment]
So it seems there is a dummy value in there where everything is nil? How is
this value getting in there in the first place? :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
I think it comes from here, https://github.com/elixir-ecto/ecto/blob/32677929ccbb02d619d3205ab7bc0a445107125b/lib/ecto/embedded.ex#L110

**Comment by josevalim** [comment]
I see, can you isolate this in a minimal app or a failing test case to this repo so we can take a further look? Thanks.

**Comment by Hermanverschooten** [comment]
ok, I'll try

**Comment by Hermanverschooten** [comment]
I have create a test in a fork, do I make a PR for it?

**Comment by josevalim** [comment]
@Hermanverschooten yes please!

**Comment by Hermanverschooten** [comment]
done #3020

**Comment by josevalim** [comment]
Thanks @Hermanverschooten. I understand how you can trigger the failure by directly calling into the `Ecto.Embedded` private API but I still cannot reproduce it via the Repo API. If I call `Ecto.TestRepo.insert(...)` with the changeset in the test you  provided, it will fail because the parent changeset is an insert and the embedded is updating, which is not logically possible. But it won't fail due to the reason you mentioned above.

I can reproduce the error on `update`, but only if I **directly change** the embedded field to contain an invalid or non-persisted embedded before calling `update`.

So can you please describe why your code is trying to *update* an embedded that was not persisted? Are you directly setting the field? Or are you calling some public API that is causing it?

If you can update the example to contain the full workflow, without calling private APIs, it would be very useful. Thank you.

**Comment by Hermanverschooten** [comment]
@josevalim I am going to try to rollback my app to the version I had then, see If it still behaves the same and give you access.

**Comment by josevalim** [comment]
Thanks, that’s very appreciated but I would prefer to not get access to the
app unless really necessary. I believe this can be isolated, we just need a
bit more context around it. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
I have got the error again.  Ok, so what happens is this, the database contains a record in which the `info` jsonb-field has no `id`. When I read this back from the `id` is filled in as `nil`, when I then try to update it, it throws the error. I updated the test without using the internal api. But it would be better if I could simulate the reading first.

**Comment by Hermanverschooten** [comment]
The `put_meta` make no difference, I thought they might be the trigger, but without the error also appears.

**Comment by Hermanverschooten** [comment]
To show you the sequence
```elixir
iex(29)> OvlInv.Suppliers.create_supplier(%{name: "CJ", street: "Lam", city: "Deurne"})
[debug] QUERY OK db=8.4ms queue=0.7ms
INSERT INTO "suppliers" ("city","customer","name","street","supplier","volunteer","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id" ["Deurne", false, "CJ", "Lam", true, false, ~N[2019-06-11 15:16:20], ~N[2019-06-11 15:16:20]]
{:ok,
 %OvlInv.Suppliers.Supplier{
   __meta__: #Ecto.Schema.Metadata<:loaded, "suppliers">,
   city: "Deurne",
   customer: false,
   email: nil,
   id: 5,
   info: nil,
   inserted_at: ~N[2019-06-11 15:16:20],
   name: "CJ",
   street: "Lam",
   supplier: true,
   tel: nil,
   updated_at: ~N[2019-06-11 15:16:20],
   vat: nil,
   volunteer: false
 }}
iex(30)> s = OvlInv.Suppliers.get_supplier! 5
[debug] QUERY OK source="suppliers" db=0.7ms
SELECT s0."id", s0."city", s0."email", s0."name", s0."street", s0."tel", s0."vat", s0."info", s0."inserted_at", s0."updated_at" FROM "suppliers" AS s0 WHERE (s0."id" = $1) [5]
%OvlInv.Suppliers.Supplier{
  __meta__: #Ecto.Schema.Metadata<:loaded, "suppliers">,
  city: "Deurne",
  customer: false,
  email: nil,
  id: 5,
  info: %OvlInv.Suppliers.Supplier.Info{account: nil, client_ref: nil, id: nil},
  inserted_at: ~N[2019-06-11 15:16:20],
  name: "CJ",
  street: "Lam",
  supplier: true,
  tel: nil,
  updated_at: ~N[2019-06-11 15:16:20],
  vat: nil,
  volunteer: false
}
iex(31)> OvlInv.Suppliers.update_supplier(s, %{ id: 2, name: "CJ", street: "Lam", city: "Deurne", info: %{ account: "1234"}})
[debug] QUERY OK db=0.2ms
begin []
[debug] QUERY OK db=0.2ms
rollback []
** (Ecto.NoPrimaryKeyValueError) struct `%OvlInv.Suppliers.Supplier.Info{account: nil, client_ref: nil, id: nil}` is missing primary key value
    (ecto) lib/ecto/embedded.ex:156: anonymous fn/3 in Ecto.Embedded.autogenerate_id/5
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/embedded.ex:155: Ecto.Embedded.autogenerate_id/5
    (ecto) lib/ecto/embedded.ex:111: Ecto.Embedded.to_struct/4
    (ecto) lib/ecto/embedded.ex:62: anonymous fn/6 in Ecto.Embedded.prepare/5
    (stdlib) maps.erl:257: :maps.fold_1/3
    (ecto) lib/ecto/repo/schema.ex:332: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (ecto) lib/ecto/repo/schema.ex:914: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
    (ecto_sql) lib/ecto/adapters/sql.ex:887: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
```

**Comment by josevalim** [comment]
Thanks! This puts us on a tough spot. We could remove the exception here,
but from ecto perspective you have invalid data and now we will stop
detecting such cases. It would be important to know how the bad data got
there in the first place but I would update the database to add a random ID
if none is there.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
that's what I initially detected, just adding a random id to your new data, solves the issue.
But wouldn't it be better if the `id` was set on read?  We know the `id` is necessary, and in combination with `on_update: :delete` is going to be replaced, so instead of `nil` and auto-generated `id`. It would solve this case. Just a thought.

**Comment by Hermanverschooten** [comment]
But the bad data is created by ecto... if you have no information in the embedded, it will be written as `nil` to the database, and up read `id` is nil, and ....

**Comment by josevalim** [comment]
> But the bad data is created by ecto...

Can you show how this is happening? Ecto will generate the ID on insertion
and Ecto should not allow an embed with nil ID to be inserted. If this is
happening, then that’s the bug.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hermanverschooten** [comment]
if you look at the code I posted 3 hours ago (5 posts up), you see exactly this.
And this is the schema that was used:
```elixir
defmodule OvlInv.Suppliers.Supplier do
  use Ecto.Schema
  import Ecto.Changeset

  schema "suppliers" do
    field :city, :string
    field :email, :string
    field :name, :string
    field :street, :string
    field :tel, :string
    field :vat, :string
    field :supplier, :boolean, default: true, load_in_query: false
    field :customer, :boolean, default: false, load_in_query: false
    field :volunteer, :boolean, default: false, load_in_query: false

    embeds_one :info, Info, on_replace: :delete do
      field :account, :string
      field :client_ref, :string
    end

    timestamps()
  end

  @doc false
  def changeset(customer, attrs) do
    customer
    |> cast(attrs, [:name, :street, :city, :vat, :email, :tel])
    |> cast_embed(:info, with: &info_changeset/2)
    |> validate_required([:name, :street, :city])
  end

  def info_changeset(schema, attrs) do
    schema
    |> cast(attrs, [:account, :client_ref])
  end
end
```
and this the create/update functions:
```elixir
def create_supplier(attrs \\ %{}) do
    %Supplier{}
    |> Supplier.changeset(attrs)
    |> Repo.insert()
  end

def update_supplier(%Supplier{} = supplier, attrs) do
    supplier
    |> Supplier.changeset(attrs)
    |> Repo.update()
  end
```

**Comment by Hermanverschooten** [comment]
It is not allowing an insert with a `nil` `id`, it is inserting the whole embedded as `nil`

**Comment by josevalim** [comment]
Thanks for updating #3020. You are still explicitly  marking the data as loaded and adding a schema without an ID. So Ecto is correct (so far) in complaining. In other words, if you are directly changing the struct state, you need to do so consistently.

What I would like to see is: a way to insert a schema with an embedded in the database in a way that the IDs of the embedded are not properly set (i.e. they remain `nil`). Otherwise, based on all of the examples given so far, there is something directly bypassing Ecto's behaviour, which means it is not an Ecto bug. Thank you.

**Comment by josevalim** [comment]
Reading back from your replies, I see this:

```
iex(30)> s = OvlInv.Suppliers.get_supplier! 5
[debug] QUERY OK source="suppliers" db=0.7ms
SELECT s0."id", s0."city", s0."email", s0."name", s0."street", s0."tel", s0."vat", s0."info", s0."inserted_at", s0."updated_at" FROM "suppliers" AS s0 WHERE (s0."id" = $1) [5]
%OvlInv.Suppliers.Supplier{
  __meta__: #Ecto.Schema.Metadata<:loaded, "suppliers">,
  city: "Deurne",
  customer: false,
  email: nil,
  id: 5,
  info: %OvlInv.Suppliers.Supplier.Info{account: nil, client_ref: nil, id: nil},
  inserted_at: ~N[2019-06-11 15:16:20],
  name: "CJ",
  street: "Lam",
  supplier: true,
  tel: nil,
  updated_at: ~N[2019-06-11 15:16:20],
  vat: nil,
  volunteer: false
}
```

`get_supplier!` is returning an empty "info" embed instead of simply returning `nil` for `info`. Are you doing something in `get_supplier` that is potentially setting a default value?

**Comment by josevalim** [comment]
And here is a test that shows that embeds written as nil are loaded as nil: b0baf80cb2afe90a22615c451582f7bbd16f01fd

**Comment by josevalim** [comment]
Ping. :)

**Comment by josevalim** [comment]
If you have more information, please let us know, thanks!

**Comment by brucepom** [comment]
For reference, I have run into this issue when changing a field definition in an Ecto schema, from one that does not expect a primary key, to one that does expect a primary key. While the schema field was not expecting a primary key, it allowed data with no primary key to be inserted. After I changed the schema definition to expect a primary key for that field, a `Ecto.NoPrimaryKeyValueError` was raised when trying to update old data that did not have a primary key.

I think this is ok and to be expected, we shouldn't expect to necessarily be able to change an Ecto schema field's definition without migrating existing data to comply with the new definition. I have tripped myself up on this more than once though, so I hope this note may be useful.

There are two common cases that can cause this:
1. Changing a field's definition from `:map` to `embeds_one` without updating existing data to ensure it contains primary keys.
2. Removing `@primary_key false` from an `embeds_one` without updating existing data to ensure it contains primary keys.

If you end up in this situation, a simple approach is to find records with no primary key and set them to null (will cause data loss of course). `UPDATE my_table SET my_col = NULL WHERE my_col -> 'id' IS NULL;`. Alternatively you could update the json values, adding ids where they were missing.

**Comment by FeeJai** [comment]
I just ran into the same issue as described by @brucepom because of a migration `add :params, :map, default: %{}`, having lots of empty json values that are not considered as non-existent by ecto.

@josevalim 
- What would be the best place to document this behaviour? I would like to draft some text and send a suggestion
- Would it maybe be possible to treat an empty json value the same as a non-existent embedded value (null) ?
