### ISSUE TITLE
Give compilation error for cycle in through associations

### ISSUE THREAD

**Issue by mguimas** [elixir-ecto/ecto#3025]
### Environment

Elixir 1.8.1
Ecto 3.1.4
Ecto_SQL 3.1.1

### Current behavior

Given these two files

```
defmodule A do
  use Ecto.Schema
  schema "as" do
    field :name
    belongs_to :b, B
    has_many :ax, through: [:b, :bs]
  end
end
```
and

```
defmodule B do
  use Ecto.Schema
  schema "bs" do
    field :name
    has_many :as, A
    has_many :bs, through: [:as, :ax]
  end
end
```
executing the following hangs the VM:
```
Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %A{id: 1, b_id: 10} |> Ecto.put_meta(state: :loaded) |> Repo.preload(:ax)

20:00:47.638 [debug] QUERY OK source="bs" db=1.3ms decode=14.2ms queue=1.5ms
SELECT b0."id", b0."name", b0."id" FROM "bs" AS b0 WHERE (b0."id" = $1) [10]

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C^C
```
While the example is an artificial one, the problem here reported may happen, for example, due to a typo.

### Expected behavior

Ecto should detect when two through associations form a cycle, and give a proper compilation error. This is preferable than the current behaviour, avoids an error that can happen only later, e.g., at production, and it will be easier for the developer to spot the problem given the compilation error.

**Comment by mguimas** [comment]
Moreover, note that the reported cycle cannot occur between through associations of the same schema because Ecto already complains that it cannot define one of those associations based on a field that was not yet defined. In such case, Ecto complains with

```
** (ArgumentError) schema does not have the association :xxxx used by association :yyyy, please ensure the association exists and is defined before the :through one
    lib/ecto/association.ex:749: Ecto.Association.HasThrough.struct/3
    lib/ecto/schema.ex:1689: Ecto.Schema.association/5
```

**Comment by josevalim** [comment]
If someone wants to submit a pull request for this, it would be appreciated. The validation should happen here: https://github.com/elixir-ecto/ecto/blob/68e55692ec5526332866b3547f5348e06d473765/lib/ecto/association.ex#L737

At the moment I only have time to focus on bug fixes but I will be glad to review any contribution (if someone wants to argue this is a bug, focus that energy on a PR instead, because arguing won't change the outcome that I don't have enough time).

**Comment by qcam** [comment]
I can give it a try if it hasn't been taken.

**Comment by wojtekmach** [comment]
Go for it!

**Comment by mkaravaev** [comment]
@qcam Have you managed to make PR for the issue? If you don't mind I'll take it? In fact, I've already had a solution for this.

**Comment by qcam** [comment]
@mkaravaev please go for it :).

**Comment by wojtekmach** [comment]
Closing in favour of a PR!
