### ISSUE TITLE
Repo prefix is not being respected in union queries

### ISSUE THREAD

**Issue by eraf2135** [elixir-ecto/ecto#3028]
### Environment

* Elixir version: 1.7.3 (compiled with Erlang/OTP 21)
* Database and version: (PostgreSQL) 10.6
* Ecto version: 3.1.5 
* Database adapter and version: postgrex 0.14.3 
* Operating system: MacOS 10.14.4 

### Current behavior

Repo prefix is not being respected in union queries. e.g. given a query like:
```
from c in query,
    union: ^union_query
```
the prefix will be applied to the `query` portion but not to the `union_query` portion.
It works if I pass in a prefix to each join in `union_query` but this is only appropriate for compile time strings and my prefix is dynamic.

### Expected behavior
I expect it to prefix all of the tables in union subqueries with the prefix I specify in my Repo.all().

**Comment by josevalim** [comment]
Closing in favor of #3039.
