### ISSUE TITLE
put_assoc/4 doesn't take into account the :foreign_key option

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3033]
### Environment

* Elixir version (elixir -v): 1.8.2 (compiled with Erlang/OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11
* Ecto version (mix deps): 3.1.5
* Database adapter and version (mix deps): postgrex 0.14.3
* Operating system: Windows 10

### Current behavior

These are two minimal schema's to reproduce the error:

```
schema "foo" do
  has_many(:bar, Bar)
end

schema "bar" do
  field(:some_field, :string)

  belongs_to(:foo, Foo,
    source: :my_custom_db_field_name,
    foreign_key: :my_custom_struct_field_name
  )
end
```

Note that the name of the foreign key in the database is "**my_custom_db_field_name**" and that the name of the struct field is "**my_custom_struct_field_name**".

When I get Bar structs, it shows correctly that the "my_custom_struct_field_name" field is used in the struct as expected:

```
from(Bar)
|> Repo.all()
|> IO.inspect()

[
  %MyApp.Test.Bar{
    __meta__: #Ecto.Schema.Metadata<:loaded, "bar">,
    foo: #Ecto.Association.NotLoaded<association :foo is not loaded>,
    id: "1fbd5f0f-5e15-4196-92b2-d12a7e868b2a",
    my_custom_struct_field_name: "a9510805-9935-4859-968a-de97e6026d1a",
    some_field: "hello"
  }
]
```

But when I use `put_assoc/4`, it will try to look for "foo_id", which doesn't exist:

```
changeset =
  %Foo{}
  |> change()
  |> put_assoc(:bar, [%{some_field: "hi!"}])
```

> ** (ArgumentError) unknown field `foo_id` in %MyApp.Test.Bar{__meta__: #Ecto.Schema.Metadata<:built, "bar">, foo: #Ecto.Association.NotLoaded<association :foo is not loaded>, id: nil, my_custom_struct_field_name: nil, some_field: nil}
>     (ecto) lib/ecto/changeset.ex:1138: Ecto.Changeset.put_change/7
>     (ecto) lib/ecto/changeset.ex:1119: Ecto.Changeset.put_change/3
>     (ecto) lib/ecto/association.ex:659: Ecto.Association.Has.on_repo_change/5
>     (ecto) lib/ecto/association.ex:432: anonymous fn/8 in Ecto.Association.on_repo_change/7
>     (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/association.ex:428: Ecto.Association.on_repo_change/7
>     (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
>     (ecto) lib/ecto/association.ex:392: Ecto.Association.on_repo_change/4

### Expected behavior

I did not expect that `put_assoc/4` would try to look for a "foo_id" field as I specified via the :foreign_key option that I want the name of the field to be named differently (my_custom_struct_field_name).

If I try to update an existing Foo, then in the SQL log I also see "foo_id", and is not using the value from the :source option (my_custom_db_field_name).

**Comment by josevalim** [comment]
Can you please provide a minimal app that reproduces the issue? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michalmuskala** [comment]
The `put_assoc` call is made from the foo side, where the `bar` association is not annotated with the foreign key - it therefore uses the default field names it inferred (we can't detect those automatically due to some compile-time deadlock reasons). Providing proper `foreign_key` option on the `has_many` definition in `foo` should fix the issue.

**Comment by thojanssens** [comment]
Thank you michal. Shouldn't it then be strongly advised in the docs that if such a custom struct key is needed, to systematically add the foreign_key: option on both sides? Otherwise it will lead to these errors when using put_assoc/4 and other related functions. Therefore it seems to me it should really always be added both sides.

**Comment by josevalim** [comment]
It is not related to the `:source` key though, it is only about foreign key: it has to be added on both sides. But if you are setting the source, there is theoretically no reason to also set the :foreign_key. if you are using `:source`, you should stay within Ecto's convention.

**Comment by thojanssens** [comment]
Yes it is not related to `:source`.

I am changing the `:foreign_key` option to do some kind polymorphism. In my real app I set the value of `:foreign_key` to "entity_id" for a set of specific schemas. (If you want I can give you all the details). So that later on, I can use entity_id on any of these schemas, and implement some generic function to work on any of these structs/entities.

BUT by changing the `:foreign_key` option, Ecto also changes the name of the database field (the source). That's why I reset also the source. Typically I have something like:

`belongs_to(:foo, Foo, foreign_key: :entity_id, source: :foo_id)`

So I change `foo_id` to `entity_id` for the struct, but then I have to specify `foo_id` for the source (database field name).

**Comment by michalmuskala** [comment]
We can probably improve the documentation of the `foreign_key` option to say that the two sides should be in sync when it's used. PRs welcome!

**Comment by thojanssens** [comment]
Should one create a branch or fork the repository to make a PR? Sorry don't know about the flow.

**Comment by josevalim** [comment]
You have to fork the project. You can also do it via GitHub's UI by pressing edit on the page you want to change.

**Comment by thojanssens** [comment]
I want to help and add text, but I'm very confused. If I go here:
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L1150
It shows the doc for `belongs_to` and then below it I read something unrelated about many-to-many relations with example using `many_to_many` field.

**Comment by mfrasca** [comment]
if I am not very mistaken, you're missing a grammar point: documentation strings **precede** the function they document.  if you look for the text to edit, you first locate the function (you did that), then [scroll back](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L958) (you scrolled forward).

**Comment by thojanssens** [comment]
Thanks bro. Let me know if I did anything wrong, I have no experience with pull requests.

**Comment by josevalim** [comment]
Hi @thojanssens, the commit looks good, now you  only need to submit it as a pull request. You can do so by doing here: https://github.com/elixir-ecto/ecto/pulls and clicking the pull request button!

**Comment by mfrasca** [comment]
An easier way to produce a pull request is by starting at a different end: instead of first forking and editing in your fork, you would go straight to the file you would edit, in the repository you would fork, and do as if you could edit it.  github will [produce your fork if you didn't do that before,] create a branch in it, and you would be two clicks away from your pull request submission.

**Comment by thojanssens** [comment]
Btw I added the title "Small doc improvement for Ecto.Schema.belongs_to/3" (as you can see above) when making my pull request, however I see that the commit message ended up being "Update schema.ex (#3040)" which is way too vague (I guess that was the title of my commit, not sure). I thought that the final commit message would be the text I entered into the pull request's title.

I guess I have to close the issue now.
