### ISSUE TITLE
Is there a way to load an initial database ?

### ISSUE THREAD

**Issue by FlyersWeb** [elixir-ecto/ecto#3035]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres:9.6
* Ecto version (mix deps): ecto 2.2.12
* Database adapter and version (mix deps): phoenix_ecto 3.6.0
* Operating system: alpine

### Current behavior

I'm working on a big Elixir/Phoenix project and I want to clean up my migration scripts because I now have almost a hundred of them.

### Expected behavior

Is there a way to load a database schema at startup in order to avoid to have to launch all the migrations to have the system up and running ? As of Spring Boot schema.sql script : https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

Thanks.

**Comment by josevalim** [comment]
`mix ecto.load` is what you want. Also, please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
