### ISSUE TITLE
Shared Options no longer in documentation?

### ISSUE THREAD

**Issue by mnussbaumer** [elixir-ecto/ecto#3037]
On the documentation for Ecto.Repo, most functions, just before the examples say:

> See the "Shared options" section at the module documentation for remaining options.

Which was where they were before, but now they're at: 

[repository api](https://hexdocs.pm/ecto/Ecto.Repo.html#module-the-repository-api)
> The Repository API

So searching for "+shared +options" for instance won't yield any relevant result. Should this be changed to "See 'The Repository API' section on this module documentation for the remaining options"? (perhaps with the link to navigate directly there?)

**Comment by josevalim** [comment]
Good catch, I reverted the title change, thanks!
