### ISSUE TITLE
Microseconds on `:utc_datetime` probably should tolerate `{0, _}`

### ISSUE THREAD

**Issue by schnittchen** [elixir-ecto/ecto#3048]
Updating a `:utc_datetime` field like this

```
change(%{field: DateTime.utc_now |> Timex.beginning_of_day})
```

will raise `(ArgumentError) :utc_datetime expects microseconds to be empty, got: #DateTime<2019-07-02 00:00:00.000000Z>`

The reason is that Timex truncates the (correct, I suppose) fields of the DateTime, while keeping the 2nd elem of the microseconds field as-is. This "precision" value bears no meaning when the first tuple value is zero.

I hope I got that right!

**Comment by josevalim** [comment]
> This "precision" value bears no meaning when the first tuple value is zero

That's not true. If I saw the digit is 0 with precision of 1, i am implying I know it is 1.0 within a range of 0.05. For a precision of 6, that's your guarantee is much higher. You have to use `_usec` types or you have to truncate it. :)

**Comment by schnittchen** [comment]
From the typespec doc (https://github.com/elixir-lang/elixir/blob/v1.9.0/lib/elixir/lib/calendar.ex#L55) I have a different understanding. It does not talk about ranges (intervals), but about numbers of digits.

For %{seconds: 0, microseconds: {500_001, 1}} I interpreted that a representation is allowed as "0.5", but not as "0.500001".

Is that typespec documentation wrong?

**Comment by josevalim** [comment]
I would say the documentation is imprecise because I have a different understanding than yours.

**Comment by schnittchen** [comment]
That would probably imply that the implementation of `Timex.beginning_of_day` is wrong.

**Comment by wojtekmach** [comment]
> `change(%{field: DateTime.utc_now |> Timex.beginning_of_day})`

with `DateTime.utc_now` you got microsecond precision, I'd expect that without `|> Timex.beginning_of_day` you'd get the same error you had. If not, that's unexpected and in that case:  what's your ecto and timex version?

**Comment by schnittchen** [comment]
WIth Timex 3.4.1 I did not see the error. It appeared when  upgrading to 3.6.0

My ecto version is 3.0.6.

**Comment by wojtekmach** [comment]
My point was with:

    change(%{field: DateTime.utc_now})

you should have been getting the error already. You do, right? So I dont think the issue is with Timex per se. If anything, its seems like newer Timex maintains precision (as opposed to possible truncating) which is good.

**Comment by schnittchen** [comment]
I never did something similar to `change(%{field: DateTime.utc_now})`.

I expected `Timex.beginning_of_day` to, semantically, erase milliseconds, so using this with `change` should not be a problem.

It looks very much like bitwalker interpreted the :milliseconds field like I did above, and changed the implementation recently to leave the second tuple position ("precision") unchanged. This breaks my expectation just stated.

The question is, what exactly is the meaning of the two tuple positions? The Elixir documentation, the Timex implementation and the casting exception in Ecto are at odds with this.
