### ISSUE TITLE
Ecto.Repo.query() doesn't honour dynamic repo

### ISSUE THREAD

**Issue by Jansemon** [elixir-ecto/ecto#3050]
### Environment
* Elixir version (elixir -v):
 Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
 Elixir 1.9.0 (compiled with Erlang/OTP 21)

* Database and version:
 PostgreSQL 11.4

* Ecto version (mix deps):
 ecto 3.1.7

* Database adapter and version (mix deps):
 postgrex 0.14.3

* Operating system:
 Linux Mint 19.1 Tessa, 5.0.0-17-generic

### Current behavior
```elixir
iex(1)> DBRepo.start_link(name: :admin, username: "admin", database: "db", hostname: "localhost")
{:ok, #PID<0.247.0>}
iex(2)> DBRepo.put_dynamic_repo(:admin)
DBRepo
iex(3)> DBRepo.get_dynamic_repo        
:admin
iex(4)> DBRepo.query("select * from users")
** (RuntimeError) could not lookup DBRepo because it was not started or it does not exist
    (ecto) lib/ecto/repo/registry.ex:18: Ecto.Repo.Registry.lookup/1
    (ecto) lib/ecto/adapter.ex:127: Ecto.Adapter.lookup_meta/1
    (ecto_sql) lib/ecto/adapters/sql.ex:334: Ecto.Adapters.SQL.query/4
```

**Comment by josevalim** [comment]
Fixed in `ecto_sql` master, thank you!
