### ISSUE TITLE
Custom type doesn't work as the inner type of a map.

### ISSUE THREAD

**Issue by mrcnkoba** [elixir-ecto/ecto#3062]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5
* Ecto version (mix deps): 3.1.7
* Database adapter and version (mix deps): postgrex 0.15.0
* Operating system: MacOS 10.14

### Current behavior

When I migrated our project from Ecto 2 to 3 I ran into one issue. I can't use a custom Ecto type as the `inner_type` of a map in `{:map, inner_type}`. It used to work well with Ecto 2 and I think it _might_ be a regression bug. The custom type that I made stupidly gets rid of NULL bytes from string inputs. I created a small application with tests that reproduces it: https://github.com/mrcnkoba/ecto_3_maybe_bug. In order to reproduce it please:

```
git clone git@github.com:mrcnkoba/ecto_3_maybe_bug.git
cd ecto_3_maybe_bug
mix deps.get
mix test
```

My custom type is here: https://github.com/mrcnkoba/ecto_3_maybe_bug/blob/master/lib/ecto3customtypemap/pgstring.ex

As a result I'm getting: 
```
Ecto3customtypemap.Test.BlogPosts
  * test custom type in maps doesn't work (53.3ms)

  1) test custom type in maps doesn't work (Ecto3customtypemap.Test.BlogPosts)
     test/ecto3customtypemap_web/controllers/blog_post_test.exs:6
     ** (Postgrex.Error) ERROR 22P05 (untranslatable_character) unsupported Unicode escape sequence

     \u0000 cannot be converted to text.
     code: Ecto3customtypemap.Repo.insert(c)
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       test/ecto3customtypemap_web/controllers/blog_post_test.exs:11: (test)
```

### Expected behavior
Record should be inserted into the database without a NULL byte.

**Comment by michalmuskala** [comment]
Unfortunately this is expected behaviour. Map types are serialized using the JSON encoder directly - they don't go through the regular `dump/load` cycle other types go through. This is started explicitly for the embedded schemas, but I couldn't find it for maps. We could definitely improve documentation in that area, but changes in behaviour are unlikely to happen here.

https://github.com/elixir-ecto/ecto/blob/854d58e1fc9525e85ebc7b7da02986e7bd4b85d4/lib/ecto/schema.ex#L1473-L1484

**Comment by josevalim** [comment]
@lucasmazza has also requested this feature and it is also an issue here: https://github.com/danielberkompas/cloak/issues/84

My proposed solution is to introduce a new `embed_as(format) :: :dump | :self` function in the type behaviour.

**Comment by josevalim** [comment]
This is now in master.
