### ISSUE TITLE
put_assoc + on_replace: :delete does insert new record before deleting the old one

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#3065]
### Environment

* Elixir version (elixir -v): 1.9
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql 10
* Ecto version (mix deps): 
* Database adapter and version (mix deps): 

  * ecto 3.1.7 (Hex package) (mix)
  locked at 3.1.7 (ecto) fa21d06e
  ok
  * postgrex 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (postgrex) dd534916
  ok
  * ecto_sql 3.1.6 (Hex package) (mix)
  locked at 3.1.6 (ecto_sql) 1e80e30d
  ok

* Operating system:

### Current behavior

I have a location, which has one address. I also added a unique constraint on the foreign key of addresses, to ensure there's only ever one address per location. But this blows up when using `put_assoc(cs, :address, new_address)` on the location changeset as the new address is inserted before the old one is deleted.

Reproduction: https://github.com/LostKobrakai/ecto_assoc_constraint

### Expected behavior

The old address should be deleted before the new one is inserted.

**Comment by LostKobrakai** [comment]
I'm wondering if this change can be released soon or if I need to remove my unique constaints in the meantime.

**Comment by josevalim** [comment]
We don't plan to backport it, so it would be made part of 3.2, which may still be a month or two away. Use master meanwhile.
