### ISSUE TITLE
updated_at field not updated when using update all

### ISSUE THREAD

**Issue by gVolop** [elixir-ecto/ecto#3069]
### Environment

* Elixir version (elixir -v): 1.6.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql (PostgreSQL) 11.3
* Ecto version (mix deps): 3.0.8
* Database adapter and version (mix deps): 
* Operating system: macOS Mojave 10.14.4

### Current behavior
when i using update_all, the updated_at field not updated with the current time.

### Expected behavior
the updated_at field of each record that update by the update_all - should be updated to the current time.

**Comment by qcam** [comment]
I think that's a documented behavior: https://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3.

**Comment by wojtekmach** [comment]
This is by design and is [documented as such](https://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3). See https://github.com/elixir-ecto/ecto/issues/1932 for a discussion on insert_all.
