### ISSUE TITLE
The function put_embed(changeset,:field, nil) does not work, is keeping the previous value

### ISSUE THREAD

**Issue by jhonathas** [elixir-ecto/ecto#3071]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

Postgres 10.4

* Ecto version (mix deps):

ecto 3.1.7 
ecto_sql 3.1.6

* Database adapter and version (mix deps):

* postgrex (Hex package) (mix)
  locked at 0.15.0 (postgrex) dd534916

* Operating system:

macOS High Sierra

### Current behavior

When updating the ecto, this code snippet that worked, stopped working:

```
changeset
|> put_embed(:location, nil)
|> put_change(:location_accuracy, nil)
|> put_change(:location_info, nil)
```
the location field has an embed, and I want to set it to nil. It used to work normally, now it doesn't work anymore.

In this link I verified that there is a test for this case, but it seems that it only worked because the embed field was created with nil

https://github.com/elixir-ecto/ecto/commit/18c0373e0577eeed2f45a14648e2490073052221#diff-42554520b76127438f8d5d47052a0cb2L762

### Expected behavior

When I make a put_embed setting nil, the value is really null, today is keeping the previous value.

It worked until version Ecto 3.1.5

**Comment by josevalim** [comment]
Can you please try out the v3.1 branch? I can do a new release afterwards. Thanks!

**Comment by jhonathas** [comment]
I will test and give a return until monday.

**Comment by josevalim** [comment]
Ok, please let me know and we can ship a fix.
