### ISSUE TITLE
Ecto Type: having load/1 equivalent to embed_as/1 for using dump/1

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#3073]
### Current behavior

https://github.com/elixir-ecto/ecto/commit/5a05dd9784f3cc5654c1c905fb79e2c86840bcc2 added the `embed_as` callback, but ecto is still using `cast` when loading embedded data from the db.

### Expected behavior

Have a similar option to make use of the load callback to load data instead of using cast. A common use-case for custom ecto types is encrypting data at rest and I personally really don't think having cast do the encoding logic is a good idea, because this essentially means I might give people the option to encode data if I'm not additionally cautious about what user input is accepted before casting it.

**Comment by josevalim** [comment]
This change is actually done here: https://github.com/elixir-ecto/ecto_sql/commit/0464becc640dcb9b830b56cca5affa060d893704

If you see the reported issue, someone already tried it in the encryption case and it works.

**Comment by LostKobrakai** [comment]
Should this line then be removed: https://github.com/elixir-ecto/ecto/commit/5a05dd9784f3cc5654c1c905fb79e2c86840bcc2#diff-7375c641be4f618fc345203d0134064fR18 It's what made me not look further.
