### ISSUE TITLE
Selecting literal values causes UNION mismatch

### ISSUE THREAD

**Issue by isaacsanders** [elixir-ecto/ecto#3074]
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

  Elixir 1.9.1 (compiled with Erlang/OTP 20)
  ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.3
* Ecto version (mix deps): 3.1.7
* Database adapter and version (mix deps): Postgrex 0.15.0
* Operating system: macOS High Sierra 10.13.6

### Current behavior

```elixir
first_query = from(first in Example.First, select: %{left: first.left, right: first.right})
second_query = from(second in Example.Second, select: %{left: "placeholder", right: second.right})

first_query |> union_all(^second_query)

** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42601 (syntax_error) each UNION query must have the same number of columns
```

### Expected behavior

I would expect the literal to be pushed down and counted as a column in the query.

### Related

This seems related to #2827

**Comment by josevalim** [comment]
Yes, it seems the opposite solution was taken. We need to change it accordingly.

**Comment by isaacsanders** [comment]
I just updated to the commit ref above, and started getting this error:

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Ecto.Query.Planner.plan_ctes/2
        (ecto) lib/ecto/repo/queryable.ex:138: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one/3
```

**Comment by josevalim** [comment]
Can you provide any information to reproduce the error? I can't guess anything from a stacktrace.

**Comment by isaacsanders** [comment]
Sure.

I just updated my version to point to the ref you committed. I think there is something wrong with the `Ecto.Query` struct that I am compiling somewhere. I think it is a case of needing to `mix clean`.

**Comment by isaacsanders** [comment]
Carry on. Upon cleaning, everything sorted itself out.
