### ISSUE TITLE
MatchError when using select_merge in subquery

### ISSUE THREAD

**Issue by sascha-wolf** [elixir-ecto/ecto#3079]
### Environment

* Elixir version: __1.9.0 (compiled with Erlang/OTP 22)__
* Database and version: __PostgreSQL 11.3__
* Ecto version: __3.1.7 (ecto_sql 3.1.6)__
* Database adapter and version: __postgrex 0.14.3__
* Operating system: __macOS Mojave 10.14.5__

### Current behavior

See the following query:

```elixir
query =
  MySchema
  |> select_merge([m], %{m | name: "some name"})
  |> subquery()

MyRepo.all(query)
```

This leads to the following error at runtime:

```
** (exit) an exception was raised:
    ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (MatchError) no match of right hand side value: {MySchema, [id: {{:., [], [{:&, [], [0]}, :id]}, [], []}, name: {{:., [], [{:&, [], [0]}, :name]}, [], []}, inserted_at: {{:., [], [{:&, [], [0]}, :inserted_at]}, [], []}, updated_at: {{:., [], [{:&, [], [0]}, :updated_at]}, [], []}, name: "some name"]}

The subquery originated from the following query:

from m0 in subquery(from m0 in MySchema,
  select: merge(m0, %{m0 | name: "some name"})),
  select: m0

        (ecto) lib/ecto/repo/queryable.ex:138: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (my_app) ...
```

#### Actual Use-Case

My real query is obviously far more complex but I was able to reproduce it with the simple setup seen above. In our application it's a rather complex query joining over multiple tables and excluding certain records. For this query I would like to set a certain field to a certain value.

As a workaround I'm currently specifying this value in each `select` clauses of the queries used in the "exclude".

### Expected behavior

Using `select_merge` in a subquery does not raise a `MatchError` at runtime. Or at least raises a more descriptive error if this turns out to be impossible.

**Comment by josevalim** [comment]
Thanks @sascha-wolf. Can you please try master quickly and let us know if the issue is still there?

**Comment by sascha-wolf** [comment]
@josevalim I was able to reproduce the issue with the current `ecto_sql` and `ecto` `master` versions. So yes, the problem persists.

**Comment by josevalim** [comment]
Btw, wouldn't this achieve the result that you want?

```elixir
query =
  MySchema
  |> select_merge([m], %{name: "some name"})
  |> subquery()
```

In any case, we would have to at least improve the error message.
