### ISSUE TITLE
Introduce prepare_query/3 Ecto.Repo callback

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#3083]
Sometimes developers want to perform filtering or assert security restrictions before performing queries. Today this requires overriding all queryably functions in Ecto.Repo, which is error prone. My proposal is to introduce a `prepare_query/3` callback:

    prepare_query(:all | :update_all | :delete_all, query, opts) :: {query, opts}

This will provide a general entry point to add this behaviour.

Thoughts?

**Comment by mbuhot** [comment]
Could this be used to set a query prefix based on some out-of-band information, eg the current HTTP request?

Ideally I'd like to attach some arbitrary metadata (similar to `Plug.Conn.assigns`) to the query and use that in the `prepare_query` callback to set a prefix or add some filters.

**Comment by josevalim** [comment]
That would be one of the uses, yes!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Btw, in case someone wants send a PR for this, it would be very appreciated. Thank you!

**Comment by josevalim** [comment]
In master!
