### ISSUE TITLE
Proposing a new feature

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3085]
From the issue template:
```
* For proposing a new feature, please start a discussion on [elixir-ecto](https://groups.google.com/forum/#!forum/elixir-ecto).
```
^^ this discussion doesn't exist

**Comment by josevalim** [comment]
What do you mean? https://groups.google.com/forum/#!forum/elixir-ecto is a valid forum and I can access it without issues from here.

**Comment by styx** [comment]
I see the same
```
This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.
```

**Comment by josevalim** [comment]
Seems to be an issue with the Google then, as it works locally both in regular mode and incognito mode. :'( I also double checked that the forum is indeed public and everyone can access it.

**Comment by fuelen** [comment]
Hmm, very strange.
10 minutes ago I saw the group, but now I don't see it again (the same error as @styx has posted above)

**Comment by OvermindDL1** [comment]
This happens sometimes with Google Groups, I'm unsure why.  Clearing the cache fixes it for me.

**Comment by fuelen** [comment]
I joined to the group and now I can see topics. Weird behavior.
