### ISSUE TITLE
Timestamps incorrect in Docker

### ISSUE THREAD

**Issue by Lazarus404** [elixir-ecto/ecto#3086]
### Environment

* Elixir version (elixir -v): 1.9.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.3
* Ecto version (mix deps): 3.1
* Database adapter and version (mix deps): EctoSQL 3.1
* Operating system: Linux

### Current behavior

I insert a record into the PG instance in another Docker container. I then send my machine to sleep. After 10 minutes, I wake my machine up and insert another record.  While the first record had correct timestamps, the new record timestamps are wrong (by the duration that my machine was asleep).  If I insert a value using PG's `now()`, the datetime is correct, so the issue is in Elixir / Ecto.

### Expected behavior

Expected the timestamp to be the correct date and time.

**Comment by Lazarus404** [comment]
So, is this a `you placed the issue in the wrong place`, `you're an idiot and this isn't a thing` or `it's an issue but I'm not dealing with it` situation?  :)

**Comment by gjaldon** [comment]
@Lazarus404 this issue was closed because it was address in this commit https://github.com/elixir-ecto/ecto/commit/74cd77e6ec8b9f6e3832c061b571e296e2b48c8a. So this issue is fixed :)

**Comment by Lazarus404** [comment]
@gjaldon thanks!  I felt like I was being fobbed off :D
