### ISSUE TITLE
Incorrect documentation on Ecto.Multi name 

### ISSUE THREAD

**Issue by cpjolicoeur** [elixir-ecto/ecto#3090]
This is a placeholder issue, as I don't have time today to formally create and submit a pull request.  [The documentation on `Ecto.Multi` includes the following snippet](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/multi.ex#L101):

```
  The name of each operation does not have to be an atom. This can be particularly
  useful when you wish to update a collection of changesets at once, and track their
  errors individually:
      accounts = [%Account{id: 1}, %Account{id: 2}]
      Enum.reduce(accounts, Multi.new(), fn account, multi ->
        Multi.update(
          multi,
          {:account, account.id},
          Account.password_reset_changeset(account, params)
        )
      end)
```

This code currently does not work however as the `String.Chars` protocol has not been implemented at all for tuples.  The documentation perhaps should be updated to give a better example for this use case.  Perhaps something like the following?

```
      Enum.reduce(accounts, Multi.new(), fn account, multi ->
        Multi.update(
          multi,
          ["account", account.id],
          Account.password_reset_changeset(account, params)
        )
      end)
```

Thoughts on what a better example might be for this use case?

**Comment by josevalim** [comment]
What Ecto version you are using? Previous versions required something that converts to strings, but the newer versions do not.

**Comment by cpjolicoeur** [comment]
Ahh, yes could be I'm looking at mismatched documentation. 

I'm currently on ecto 3.1.4.  The docs for 3.1.4 use the same example syntax though as the current documentation, so I'm not sure that is the discrepency.

I'm also on elixir 1.8.1 just for reference.
