### ISSUE TITLE
Upsert does return invalid inserted_at, which is always current timestamp

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-ecto/ecto#3091]
I have a bit of a problem, and I created very crude integration test on ecto_sql repository to demonstrate the problem with.

In short, if do upsert, with `:replace` and a list of columns to replace on conflict, the returned struct from insert is has, in addition to replaced column, updated `inserted_at` field.

The field in database does *not* get updated, which is correct. The only problem is that the value in struct returned to user from upsert is invalid.

Please have a look at this test, which currently fails on my master: 
```
  test "should perform upsert without touching inserted_at timestamp and return correct value" do
    {:ok, u1} = PoolRepo.insert(Upsert.changeset(%Upsert{}, %{note: "Hey there"}))
    :timer.sleep(2000)
    {:ok, u2} = PoolRepo.insert(Upsert.changeset(%Upsert{}, %{note: "Hey there"}),
                                on_conflict: {:replace, [:note]},
                                conflict_target: :note)

    assert u1.id == u2.id
    assert u1.inserted_at == PoolRepo.get!(Upsert, u1.id).inserted_at
    assert u1.inserted_at == u2.inserted_at
```
Link to my commit containing the test:
https://github.com/hubertlepicki/ecto_sql/commit/7cc6f30968d176d68c56147e6f8fef3c86696a21#diff-88da18ae2b478a00be1c0fe60fdfcfd0R47

this test fails with:
```
  1) test should perform upsert without touching inserted_at timestamp and return correct value (Ecto.Integration.UpsertTest)
     integration_test/pg/upsert_test.exs:47
     Assertion with == failed
     code:  assert u1.inserted_at() == u2.inserted_at()
     left:  ~N[2019-08-22 15:23:39]
     right: ~N[2019-08-22 15:23:41]
     stacktrace:
       integration_test/pg/upsert_test.exs:56: (test)
```
That's the last assertion which is failing.

In my application code, whenever I do upsert I have to reload the record from database, to have correct timestamps on them. So what I do is:

```
{:ok, record} = Repo.insert(....)
record = Repo.get(MyStruct, record.id)
```
That is temporary measure I take, but I think it's a bug in Ecto.

**Comment by josevalim** [comment]
There is not much we can do. In case of upserts, databases do not tell us what went wrong and what failed, so you have to depend on heuristics to figure out what happened or, in the worst case scenario, reload the data exactly as you are doing. :(

**Comment by chulkilee** [comment]
@hubertlepicki can you test `returning: true` option? From the doc, it should set the struct with up-to-date value from database.

**Comment by hubertlepicki** [comment]
@chulkilee genius. This solves the issue. I saw the option but was like 'meh, it already returns the inserted struct, wouldn't do much'. And indeed if used with `:replace_all` it does work as expected.

Maybe `:on_conflict`, or - `:on_conflict` + `:replace` should trigger `returning: true` option to be set behind the scenes for the user, what do you think?

**Comment by josevalim** [comment]
> Maybe :on_conflict, or - :on_conflict + :replace should trigger returning: true option to be set behind the scenes for the user, what do you think?

Unfortunately it doesn't work for all DBs and that's not the only solution to the problem. For example, if you have associated data, maybe you want to load the whole record anyway. Also note these options (and the problem you originally described) are all documented in docs for Repo.insert/2. :)

**Comment by hubertlepicki** [comment]
/me feels stupid/

Yes it's very nicely documented indeed. Alright, I'm going to keep doing `return: true` as this solves the issue for me since I'm on PostgreSQL. Thank you both for all your help!

**Comment by josevalim** [comment]
Don't feel like that because I was the one who wrote the docs and I couldn't remember about returning: true either. :P

**Comment by hubertlepicki** [comment]
I don't want to scare you but I think it gets worse with age...

I mostly write blog posts / forum answers to be able to find a solution to problem I just resolved in 6 months or so. The next time I have the same problem, I will find my post in Google search and bang, solution found.

I am more than sure this is going to happen with the above issue and this very thread.
