### ISSUE TITLE
Children assoc inserts failing in v3.1.7, assoc_opts should also take `:returning`

### ISSUE THREAD

**Issue by ntilwalli** [elixir-ecto/ecto#3094]
Ecto v3.0.5 properly applies parent ids into `cast_assoc` children inserts but v3.1.7 does not in all situations causing a database-level `not_null_violation` in my formerly working tests. I believe I've tracked the issue to the `assoc_opts` function which was recently introduced in the `Ecto.Repo.Schema` module.

To fix, I believe the line below should include `:returning` as one of the `opts` that's taken
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L808

* Elixir version: 1.9.1
* Database and version: Postgres 10.6
* Ecto version: 3.1.7
* Database adapter and version: Postgrex 0.14.3
* Operating system: MacOS 10.14.6

### Current behavior
```
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "coordinate_id" violates not-null constraint

    table: listing_coordinate_rules
    column: coordinate_id

Failing row contains (10, null, weekly, 1, monday, null, null, {sunday}, null, 2019-08-30, 18:00:00, null, null, null, null, 2019-08-30 20:17:10, 2019-08-30 20:17:10)
```
### Expected behavior
Insert should take place with parent id in place of the `null` in the second column.

**Comment by josevalim** [comment]
Thanks @ntilwalli. Can you please provide more information? Are you by any chance passing the `:returning` option? Can you please include your schemas as well or even a sample app that reproduces the issue?

We won't be able to fix the issue if we can't effectively reproduce it. Thank you.

**Comment by ntilwalli** [comment]
@josevalim I do pass the `returning` option in my app. I'm of the understanding that passing the `returning` option is a requirement when trying to do multi-tier-inserts via `cast_assoc`. I don't have a stripped down sample app that replicates the issue as of now.  I however did solve the issue locally by manually recompiling the `ecto` dependency with the source code change mentioned above... adding `returning` to the list of keys that get passed to associated inserts...  If you need a repo that replicates the issue I could spend time stripping my app down to isolate this issue... but it would take some time

A stripped down version of the schema is posted below.

The issue is exposed via a listing insert via a changeset where the params include a new associated coordinate which itself includes one new associated rule so it's a multi-tier set of associated inserts... `listing -> coordinates -> rules`  The rules insert fails because the insert associated with the coordinate happens with an empty `read_after_writes` list so when the coordinate_id is to be applied to the associated rule it comes back as `nil` and the rule insertion fails.  By passing the `returning` opt from the original opts list to the assoc_opts the `read_after_writes` list includes the `id` field and thus record for the associated rule insert has the `coordinate_id` properly filled in...
```
defmodule Shared.Listing do
  require Logger
  use Shared.Lib, :model
  use Shared.CommonModuleStrings

  @primary_key {:id, :id, autogenerate: true}
   
  schema "listings" do
    field :sort_id, :id
    field :type, :string
    field :grouping_type, :string
    field :handle, :string
    field :release, :string
    field :visibility, :string
    field :status, :string
    field :cuando, :map
    field :donde, :map
    field :normalized_tags, {:array, :string}
    embeds_one :meta, Model.Listing.Meta, on_replace: :update
    field :modules, {:array, :map}
    embeds_one :settings, Model.Listing.Settings, on_replace: :update
    field :source, :string
    field :version, :string
    timestamps()

    has_many :coordinates, Coordinate.Model, on_replace: :delete
  end

  @allowed_fields [
    :id, :parent_id,
    :user_id, :creator_id, :updater_id, 
    :type, :grouping_type, :release, :visibility, :status,
    :cuando, :donde, 
    :normalized_tags,
    :handle, :source, :version, :modules,
    :inserted_at, :updated_at
  ]

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @allowed_fields)
    |> cast_assoc(:coordinates)
  end
end

defmodule Coordinate.Model do
  use Shared.Lib, :model 
  use Shared.CommonModuleStrings

  @primary_key {:id, :id, autoincrement: true}
   
  schema "listing_coordinates" do
    
    field :where_type, :string
    field :when_type, :string
    field :geom, Geo.PostGIS.Geometry
    embeds_one :lng_lat, Shared.Model.LngLat, on_replace: :delete
    field :dtstart, :utc_datetime_usec
    field :until, :utc_datetime_usec
    field :date_start, :date
    field :time_start, :time_usec
    field :date_until, :date
    field :time_until, :time_usec
    field :door, :integer
    field :duration, :integer
    has_many :rdates, RDate.Model, foreign_key: :coordinate_id #, on_replace: :delete
    field :data, :map
    embeds_one :search_region, Coordinate.SearchRegion, on_replace: :delete 
    has_many :rules, Rule.Model, foreign_key: :coordinate_id #, on_replace: :delete
    timestamps()

    belongs_to :parent_coordinate, Coordinate.Model
    belongs_to :venue, Shared.Venue
    belongs_to :listing, Shared.Listing
    field :delete, :boolean, virtual: true
  end

  @allowed_fields [
    :id, :where_type, :when_type, :venue_id, :parent_coordinate_id,
    :date_start, 
    :time_start, 
    :date_until, 
    :time_until, 
    :door, :duration, 
    :data, :inserted_at, :updated_at, :delete
  ]

  def changeset(schema, params \\ :empty) do

    schema
    |> cast(params, @allowed_fields)
    |> cast_embed(:lng_lat)
    |> cast_assoc(:rules)
    |> cast_assoc(:rdates)
    |> cast_embed(:search_region, required: true)
    |> add_venue_id()
    |> assoc_constraint(:venue)
    |> assoc_constraint(:parent_coordinate)
    |> add_dtstart_until()
    |> add_geom()
    |> Shared.Helpers.mark_for_deletion()

  end
end

defmodule Rule.Model do
  use Shared.Lib, :model

  @primary_key {:id, :id, autoincrement: true}
   
  schema "listing_coordinate_rules" do
    field :freq, :string, null: false
    field :interval, :integer
    field :wkst, :string, default: "monday"
    field :count, :integer
    field :bysetpos, {:array, :integer}
    field :byweekday, {:array, :string}
    field :exdates, {:array, :date}

    field :date_start, :date
    field :time_start, :time_usec
    field :date_until, :date
    field :time_until, :time_usec
    field :duration, :integer
    field :door, :integer

    belongs_to :coordinate, Coordinate.Model
    timestamps()

    field :delete, :boolean, virtual: true
  end

  @allowed_fields [
    :coordinate_id, :freq, :interval, :wkst, :count, :bysetpos, :byweekday,
    :date_start, :time_start, :date_until, :time_until,
    :duration, :door, :inserted_at, :updated_at, :delete
  ]

  def changeset(schema, params \\ :empty) do
    schema
    |> cast(params, @allowed_fields)
    |> assoc_constraint(:coordinate)
    |> Shared.Helpers.mark_for_deletion()
  end
end
```

**Comment by ntilwalli** [comment]
To be clear, the fix I'm suggesting is that the line:
```
|> Keyword.take([:timeout, :log, :telemetry_event, :prefix])
```
be changed to
```
|> Keyword.take([:timeout, :log, :telemetry_event, :prefix, :returning])
```

**Comment by josevalim** [comment]
Just to be clear, the issue is that we are not passing read_after_writes
downstream? And coordinate_id is generated at the database?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ntilwalli** [comment]
Yeah, I believe that's right, and I solved that by including `:returning` in the list of keywords that are taken...

**Comment by ntilwalli** [comment]
Yes coordinate_id is generated at the database...

**Comment by ntilwalli** [comment]
I should add, I created a super simple multi-tier schema to test if it was a general non-passing `read_after_writes` downstream and it didn't demo the issue.  But in my schema which is much more complicated it does demonstrate the issue.  So it demos the issue in some situations and not others and I've yet to isolate the distinction.  When I found `read_after_writes` was not being passed downstream in my specific scenario and adding `:returning` to the list of taken keywords in `assoc_opts` fixed my issue I posted the report.

**Comment by josevalim** [comment]
Maybe I am missing something obvious, but where is read_after_writes being used in the schema you posted?

**Comment by ntilwalli** [comment]
I've answered the question in two ways, hopefully one of them addresses your question...

1) If you mean, "In the three Ecto Schemas y pasted above (Listing, Coordinate, Rule) where are you calling insert with the `returning: true` opt set?": I didn't post the code from my app that actually does the insert I just posted the schema/changeset code that is used to construct the record applied on insert, but I definitely am calling insert with `returning: true` set...

2) If you mean, "Where in `Ecto.Repo.Schema` code is the `read_after_writes` call made that I'm referring to?": I've been using the term `read_after_writes` interchangeably with `return_sources` in my above messages, but the actual call is here: 
https://github.com/elixir-ecto/ecto/blob/c0bcfb538f062340a3e4a4a922693fc7ee0e7d49/lib/ecto/repo/schema.ex#L225

My analysis indicated that `return_sources` was not being set properly for assoc inserts here: https://github.com/elixir-ecto/ecto/blob/c0bcfb538f062340a3e4a4a922693fc7ee0e7d49/lib/ecto/repo/schema.ex#L222

The reason being that the `assoc_opts` in  `args` sent to `apply` for associations was being set improperly:
https://github.com/elixir-ecto/ecto/blob/c0bcfb538f062340a3e4a4a922693fc7ee0e7d49/lib/ecto/repo/schema.ex#L260

The `assoc_opts` is set a bit above that line here: 
https://github.com/elixir-ecto/ecto/blob/c0bcfb538f062340a3e4a4a922693fc7ee0e7d49/lib/ecto/repo/schema.ex#L260

**Comment by josevalim** [comment]
Thank you. My point is that you can solve this problem by passing `read_after_writes: true` to the coordinate_id field. The reason we don't pass `:returning` forward is because it actually breaks things, especially when returning is a list. Alternatively, you can put `returning: true` on repo_opts for the changeset for the child associations. Any of those should solve the problems you are seeing.

**Comment by ntilwalli** [comment]
@josevalim Thanks for taking the time, but I don't understand the recommendations.  

1) These are `@primary_key` `:id` fields which are configured using `autogenerate: true`.  When I add the `read_after_writes` option, I get an error saying that I `cannot mark the same field as autogenerate and read_after_writes`

2) What are "repo_opts" I don't see the term in the documentation.  Can you show me an example of where I can apply a `returning: true` opt within the context of a changeset function.  I was under the impression it's an option that's associated with an insert/update query only...

**Comment by josevalim** [comment]
1. Right, auto generated primary keys are always read after write, so based on your description the issue has to be elsewhere.

2. There is a repo_opts field inside the Ecto.Changeset which are options that will be used in the repo operations.

If you feel that still won’t solve the issue, then I am afraid we will need a way to reproduce the issue.

**Comment by ntilwalli** [comment]
I found the bug, it was on my side.  I was using `autoincrement: true` in my schema files and not `autogenerate: true`, that mistake meant the automatic :read_on_writes was not being applied probaby and the fist moving away from passing `returning` to associations in 3.1 exposed the bug on my side...  Thanks!
