### ISSUE TITLE
Filter clause with type conversion generates malformed SQL statement

### ISSUE THREAD

**Issue by jknipp** [elixir-ecto/ecto#3099]
### Environment

* Elixir version: 1.9.1 (compiled with Erlang/OTP 22)
* Database and version: PostgreSQL 11
* Ecto version: 3.1.7
* Database adapter and version: postgrex 0.15.0
* Operating system: macOS 10.14.6

### Current behavior

In Ecto, when trying to use a `filter` clause, a `sum` aggregation function, and `type` conversion, I’m encountering a SQL error. Combining the filter clause with a type conversion is generating a malformed SQL statement. 

#### Example:
```
from(
    c in my_table,
    select: %{
    counts: 
        sum(c.count)
        |> type(:integer)
        |> filter(fragment("split_part(?, '.', 1)", c.three_ds_version) == "2")
    }
    }
)

# SQL Output
SELECT sum(p0."count")::bigint FILTER (WHERE split_part(p0."version", '.', 1) = '2') FROM "my_table"
```

The type conversion is applied in the incorrect position, resulting in the error: `ERROR 42601 (syntax_error) syntax error at or near "FILTER"`

Rearranging the order of the `filter` and `type` functions in an attempt to apply the type based on the results in: 

```
** (Ecto.Query.CompileError) the first argument of type/2 must be one of:

  * interpolations, such as ^value
  * fields, such as p.foo or field(p)
  * fragments, such fragment("foo(?)", value)
  * an arithmetic expression (+, -, *, /)
  * an aggregation or window expression (avg, count, min, max, sum, over)

Got: filter(sum(c.count()), fragment("split_part(?, '.', 1)", c.version()) == "2")

    expanding macro: Ecto.Query.select/3
```

### Expected behavior

Using the `filter` function in conjunction with `type`, should produce a well-formed SQL statement:

```
SELECT sum(p0."count") FILTER (WHERE split_part(p0."version", '.', 1) = '2')::bigint FROM "my_table"
```

**Comment by josevalim** [comment]
I think we should allow the order to be rearranged. Can you please look into a PR? It should be around Ecto.Query.Builder. Thanks!
