### ISSUE TITLE
replace default incremeter in optimistic_lock to avoid exception raised when it exceeds integer limit

### ISSUE THREAD

**Issue by bruteforcecat** [elixir-ecto/ecto#3103]
https://github.com/elixir-ecto/ecto/blob/d8ae5564a17f5b0a40962d81ef71360560210f12/lib/ecto/changeset.ex#L2235

If the lock_version is specified as :integer in the migration, it will throw exception when the lock_version exceed its db limit(2147483647 for both Postgres and MySQL). So should we change the default incrementer to cycle it back to default(1) when it reaches `2147483647`?

I can create a PR for this if most of you think it's a good idea.

**Comment by josevalim** [comment]
I would love to see a PR for this, yes, thank you.

**Comment by josevalim** [comment]
Closing in favor of PR.
