### ISSUE TITLE
Ecto 3.2 caches OIDs differently(?), causing mix tasks to fail

### ISSUE THREAD

**Issue by jamesvl** [elixir-ecto/ecto#3106]
### Environment

* Elixir version (elixir -v): 1.9.1 (Erlang 22 / erts-10.4.4)
* Database and version: Postgres 9.4
* Ecto version: 3.2.0
* Database adapter and version: postgrex 0.15.0
* Operating system: Fedora 30

### Current behavior

Running the following command causes a failure:

`$MIX_ENV=test mix do ecto.drop, ecto.create, ecto.migrate, run priv/repo/seeds.exs`

```
... uses unknown oid(s) 144289 causing bootstrap
... uses unknown oid(s) 144622, 144634 causing bootstrap
```

### Expected behavior

Running the `seeds` script separately works fine:

```shell
$MIX_ENV=test mix do ecto.drop, ecto.create, ecto.migrate
$MIX_ENV=test mix do run priv/repo/seeds.exs
```

The `mix do` command given above does not fail if I revert to Ecto 3.1.7

**Comment by josevalim** [comment]
Btw, this small app most likely needss to have only your migrations, in particular anything that is playing with extensions!

**Comment by jamesvl** [comment]
Working on that app... I created a basic one but it didn't repro the issue. I'll see if I can isolate what it is in my existing app that causes it.

**Comment by josevalim** [comment]
Postgrex v0.15.1 is released with the warning moved to debug. Thank you!
