### ISSUE TITLE
put_assoc and on_replace: :update option doesn't update the associated parent

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3109]
The `:on_replace` option with value `:update` don't seem to update the associated parent:

```
child_attrs = %{
  "text" => "child text",
  "parent_id" => 1
}

%Child{}
|> Child.changeset(child_attrs)
|> Ecto.Changeset.put_assoc(
   :parent,
   %{id: 1, text: "updated parent text"} # <- will attempt to insert, results in primary key constraint violation
   # %{text: "updated parent text"} # <- will create a new parent
   # %{parent | text: "updated parent text"} # <- won't insert nor update the association
 )
|> Repo.insert!()
```

```
schema "child" do
  field :text, :string
  belongs_to :parent, MyApp.Parent, on_replace: :update
end
```

Is it normal that I am not able in any way to update the parent association even though the docs seem to say for the `on_replace: :update` option that it allows updates?

**Comment by josevalim** [comment]
Ecto is not going to automatically load the parent because you passed the parent id. Ecto only works with the things it can see, so even if there is a parent for such ID in the DB, Ecto knows nothing about it.

Your third example should work, as long as you use changeset to update the parent. Again, if you just update the record in place, Ecto has no idea you changed something g, you have to go through Ecto. :)

**Comment by thojanssens** [comment]
Thank you. I thought `on_replace: :update` allowed the update of the **fields of the associated schema**. But actually, this option just means that it allows to update the foreign key, and nothing more, if I'm not wrong. To update the fields of the association, I just need to add my changes in the changeset as you suggested and it has nothing to do with this option.

If I got this correctly, I think the docs needs to be a little adjusted for this option value:

> This option will update all the fields given to the changeset including the id for the association

=> why do we mention that the fields given in the changeset will be updated? Of course they will, they always do in any case

to 

> This option allows updating the id for the association

**Comment by josevalim** [comment]
No, it works for updating, but you Need to be updating the parent too. We can’t replace something if nothing was there all along.
