### ISSUE TITLE
Document that the function passed to prepare_changes/2 only runs when changeset is valid?

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3111]
Isn't it worth mentioning in the docs that the function passed to Changeset.prepare_changes/2 only runs when the changeset is valid?

https://hexdocs.pm/ecto/Ecto.Changeset.html#prepare_changes/2

**Comment by josevalim** [comment]
Definitely, good catch! Can you please submit a PR?

**Comment by thojanssens** [comment]
Yep, done.
https://github.com/elixir-ecto/ecto/pull/3114
