### ISSUE TITLE
Bang-functions for get_change/3 and get_field/3?

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3116]
Ecto provides:
- fetch_change/2
- fetch_field/2
- get_change/3
- get_field/3

But it doesn't provide the equivalent "bang-functions", i.e. raise an error when the given key is not found.

The consequence is that I will get `nil` or `:error` if given key is not found, and I will have an unclear error while trying to manipulate these values in a later instruction.

Example case: a function is given a changeset and expects a key to be present in the changeset; if not, this would be a programming bug, thus raise an error.

What do you think about that?

**Comment by thojanssens** [comment]
Actually I should post this on google groups but I have the message:
> This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.

Tried to open in Incognito, still didn't work. So I'm sorry to post that here because it is actually a request for feature. I will try the Google Groups again later...

**Comment by josevalim** [comment]
Yes, please send a PR!

> Actually I should post this on google groups but I have the message:

Yes, the group exists but it is frequently misbehaving. See #2999.
