### ISSUE TITLE
updating assoc on delete

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3119]
When a changeset is passed to `Repo.delete/2`, association changes that are marked as :update are not being updated in the database.

`Repo.delete/2` should work like `Repo.insert/2`, where associations are updated if there are changes for the association in the changeset.

Example case: change something in the parent association (belongs_to) when deleting a struct.

**Comment by josevalim** [comment]
I am not sure I agree with this. It feels slightly weird that deleting a node from the association tree can cause its subtree to be updated. Can you please tell us a bit more about your case?

**Comment by thojanssens** [comment]
E.g. when a node gets deleted, update the parent node's child counter.

You will mention `prepare_changes/2` for this kind of stuff. But it seems to me that doing this through adding a change in the changeset is also a valid way to achieve that.

- If not, then why do we allow for example to **edit** a **parent** node when performing an insert? If my concern is weird, then this is on the same level of weirdness and it is allowed. I guess accidentally as adding **new** child nodes should be a very common case for an insert.

- When changes on the changeset cannot be fulfilled, shouldn't that raise an error?

I thought the rule should be: apply all changes in the changeset. If not, raise an error if Ecto can't apply a change. Because having a change in the changeset that cannot be fulfilled is an application bug that currently would go undetected.

**Comment by josevalim** [comment]
> You will mention prepare_changes/2 for this kind of stuff. But it seems to me that doing this through adding a change in the changeset is also a valid way to achieve that.

The reason we mention prepare_changes is because doing the way you are proposing is incorrect and it will lead to data races an invalid counters.

**Comment by thojanssens** [comment]
I see now. I have no valid case.

In theory, without thinking about real cases: I have a change in the changeset that neither gets fulfilled nor raises an error.

But if I understand, the approach is to stay pragmatic, and justify a change on practical cases.

**Comment by josevalim** [comment]
Yes, in theory we could support this but I would like to know the use cases to be sure we are doing the correct thing. We do support updates on inserts and that was most likely driven by a use case (perhaps a has_one/belongs_to thing, which would also be ok for deletes).
