### ISSUE TITLE
Mailinglist

### ISSUE THREAD

**Issue by NobbZ** [elixir-ecto/ecto#3120]
The current `README` links to a mailinglist at Google Groups. Gougle Groups web UI though tells that the group is either inexistent or privat.

If either is true and this has happened consciously, then the link should be removed, if though it got privat by accident, its probably time to re-open it.

https://github.com/elixir-ecto/ecto/blob/master/README.md#L131

**Comment by josevalim** [comment]
The group is the same as it has always been but users are reporting on and off issues with the group. Some say clearing cookies is enough to get it working. Please see other previously reported issues.
