### ISSUE TITLE
Repo.insert!(.., on_conflict: :nothing, returning: true) on conflict does not populate the id

### ISSUE THREAD

**Issue by PragTob** [elixir-ecto/ecto#3132]
Hello there and thanks as always for your great work. Working with ecto is such a nice experience, the only reason I'm reporting an issue is basically because I want to do extra nice things that (for instance in AR) I probably wouldn't even have tried if ecto wasn't so nice :green_heart: 

### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.4
* Ecto version (mix deps): ecto 3.2.2, ecto_sql 3.2.0
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: Linux Mint 19.1 (Ubuntu 18.04 base)

### Current behavior

Basically I'm implementing `get_or_insert` with `on_conflict: :nothing, returning: true` as suggested in some places.

Right now if the insert is successful the id of the returned struct is populated, which is great. However, if something was inserted before/on conflict the id is not populated (which hinders me as I need it as a reference).

```
# currency didn't exist before, id is returned successfully
iex(5)> Repo.insert!(%Currency{currency_iso: :XAU}, on_conflict: :nothing, returning: true)
[debug] QUERY OK db=10.5ms queue=4.1ms
INSERT INTO "currencies" ("currency_iso","inserted_at","updated_at") VALUES ($1,$2,$3) ON CONFLICT DO NOTHING RETURNING "id", "updated_at", "inserted_at", "currency_iso" ["XAU", ~N[2019-10-01 12:49:39], ~N[2019-10-01 12:49:39]]
%PricingEngine.Pricing.Currency{
  __meta__: #Ecto.Schema.Metadata<:loaded, "currencies">,
  currency_iso: :XAU,
  id: 12,
  inserted_at: ~N[2019-10-01 12:49:39],
  updated_at: ~N[2019-10-01 12:49:39]
}

# currency now exists, but id is not populated although it shows up in RETURNING
iex(6)> Repo.insert!(%Currency{currency_iso: :XAU}, on_conflict: :nothing, returning: true)
[debug] QUERY OK db=27.8ms queue=0.8ms
INSERT INTO "currencies" ("currency_iso","inserted_at","updated_at") VALUES ($1,$2,$3) ON CONFLICT DO NOTHING RETURNING "id", "updated_at", "inserted_at", "currency_iso" ["XAU", ~N[2019-10-01 12:50:00], ~N[2019-10-01 12:50:00]]
%PricingEngine.Pricing.Currency{
  __meta__: #Ecto.Schema.Metadata<:loaded, "currencies">,
  currency_iso: :XAU,
  id: nil,
  inserted_at: ~N[2019-10-01 12:50:00],
  updated_at: ~N[2019-10-01 12:50:00]
}

# specifying id explicitly on returning also does not seem to help:

iex(10)> Repo.insert!(%Currency{currency_iso: :XAU}, on_conflict: :nothing, returning: [:id])
[debug] QUERY OK db=2.7ms queue=2.0ms
INSERT INTO "currencies" ("currency_iso","inserted_at","updated_at") VALUES ($1,$2,$3) ON CONFLICT DO NOTHING RETURNING "id" ["XAU", ~N[2019-10-01 13:00:24], ~N[2019-10-01 13:00:24]]
%PricingEngine.Pricing.Currency{
  __meta__: #Ecto.Schema.Metadata<:loaded, "currencies">,
  currency_iso: :XAU,
  id: nil,
  inserted_at: ~N[2019-10-01 13:00:24],
  updated_at: ~N[2019-10-01 13:00:24]
}

```

The docs made me believe this would work:

> When true, returns all fields in the given schema. May be a list of fields, where a struct is still returned but only with the given fields. 

### Expected behavior

I expect it to return the id/populate the id field on the struct. Or if that's for some reason not possible/not intended then for the docs to state that this is possible for everything but id (happy to send a PR patching it up)

Not sure if this is a regression of #1966 I skimmed it but wasn't sure and it was long ago :thinking: 

Thanks! :heart:

**Comment by josevalim** [comment]
Hi @PragTob!

I believe we outlined all of this in the docs already: https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts

We should cross reference this with Upsert docs though. I will add a reference to it.

**Comment by PragTob** [comment]
I see, thanks a ton!
