### ISSUE TITLE
Ecto.Changeset.validate_subset enumerates on the wrong variable

### ISSUE THREAD

**Issue by mindreader** [elixir-ecto/ecto#3138]
Elixir version: 1.9.0
Ecto version: 3.1.7 (but the code is the same in master)

This line in deps/ecto/lib/ecto/changeset.ex looks really wrong to me.
```
case Enum.any?(value, fn(x) -> not(x in data) end) do
```

It should be
```
case value not in data do
```

Which fixes the error.  This code has been this way a long time.  I'm surprised that I'm the first to discover this, maybe I'm doing something wrong, but it doesn't seem like it.

```
defmodule Marker do
  schema "markers" do  
    field(:type, :string)
  end
end

%Marker{}
 |> Ecto.Changeset.cast(%{type: "pre"}, [:type])
 |> Ecto.Changeset.validate_subset(:type, ["pre", "post", "mid"])
```

### Current behavior

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for "pre" of type BitString. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Stream, List, Range, MapSet, Date.Range, IO.Stream, HashDict, File.Stream, HashSet, GenEvent.Stream, Map, Function
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:366: Enum.any?/2
    (ecto) deps/ecto/lib/ecto/changeset.ex:1860: anonymous fn/5 in Ecto.Changeset.validate_subset/4
    (ecto) deps/ecto/lib/ecto/changeset.ex:1578: Ecto.Changeset.validate_change/3
```

### Expected behavior
```
#Ecto.Changeset<
  action: nil,
  changes: %{type: "pre"},
  errors: [],
  data: #Simple.Schema.Marker<>,
  valid?: true
>
```

**Comment by wojtekmach** [comment]
> ```elixir
> defmodule Marker do
>   schema "markers" do  
>     field(:type, :string)
>   end
> end
>
> %Marker{}
>  |> Ecto.Changeset.cast(%{type: "pre"}, [:type])
>  |> Ecto.Changeset.validate_subset(:type, ["pre", "post", "mid"])
> ```

`validate_subset/2` is used to check whether one _enumerable_ is a subset of another one. So in this case you'd instead have:

1. `field :types, {:array, :string}`
2. `cast(%{types: ["pre"]})`
3. `validate_subset(:types, ["pre", "post", "mid"])`

If all you need to do is validate if given _value_ is in a given enumerable, use `validate_inclusion/2` instead.

**Comment by mindreader** [comment]
I saw the enum type in the docs for `validate_subset/2`, but it wasn't clear to me what that it meant to be an "of type enum".

**Comment by wojtekmach** [comment]
Agreed, it's not super clear. If you'd like giving a shot at a PR updating the docs that'd be very appreciated!

**Comment by gbenga504** [comment]
This isn't clear at all, just spent so much time googling because I thought inclusion wasn't meant for enums. Need to update the docs
