### ISSUE TITLE
@schema_prefix tag has no effect

### ISSUE THREAD

**Issue by alaadahmed** [elixir-ecto/ecto#3147]
### Environment

* Elixir version (elixir -v): 1.9.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.5
* Ecto version (mix deps): 3.2.3
* Database adapter and version (mix deps): 0.15.1
* Operating system: macOS Catalina 10.15

### Current behavior
I was following [Multi tenancy with query guide](https://hexdocs.pm/ecto/multi-tenancy-with-query-prefixes.html#schema-prefixes)

I wrote in `dev.exs`
```
query_args = ["SET search_path TO connection_prefix", []]

# Configure your database
config :multitenant, Multitenant.Repo,
  ...
  after_connect: {Postgrex, :query!, query_args}
```
I created _mapping schema_ using `mix phx.gen.schema Mapping mappings client_id:integer db_prefix` and in `mapping.ex` file I added `@schema_prefix "main"` like so:
```
@schema_prefix "main"  <<<<<
schema "mappings" do
  field :client_id, :integer
  field :db_prefix, :string

  timestamps()
end
```
I run `mix ecto.migrate` and found __mapping__ table went under `connection_prefix`. I didn't find `main` created automatically so I created it using `psql -d multitenant_dev -c "CREATE SCHEMA main"` and dropped database and recreated it and made migration and got error:
```
11:48:18.117 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :multitenant, Multitenant.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:716: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migrator.ex:633: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql) lib/ecto/migrator.ex:477: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:401: Ecto.Migrator.run/4
    (ecto_sql) lib/ecto/migrator.ex:142: Ecto.Migrator.with_repo/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:118: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:106: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:813: Code.require_file/2
```
when I run `psql -d multitenant_dev -c "CREATE SCHEMA connection_prefix"` and rerun migration, it worked but __mapping__ table was not under `main` and was under `connection_prefix`.

### Expected behavior
I expected that __mapping__ table should be under `main` prefix as guide tells but it was not and I don't know if I missed something or more configs I should make, so I see `@schema_prefix` tag had no effect over `after_connect` callback that I added in `dev.exs`.

**Comment by wojtekmach** [comment]
Setting a prefix on your Ecto schema does not mean that prefix will be used when creating the corresponding table, schemas and migrations are totally independent. You can set a prefix in migration like this:

```elixir
def change do
  create table("weather", prefix: "north_america") do
    ...
  end
end
```

**Comment by josevalim** [comment]
Closed per @wojtekmach's comment. if you think the guides could be clearer, please send a PR, that would be very welcome. thank you!

**Comment by alaadahmed** [comment]
@wojtekmach in guides it's written:

> Now running MyApp.Repo.all MyApp.Mapping will by default run on the "main" prefix, regardless of the value configured for the connection on the :after_connect callback. Similar will happen to insert, update, and similar operations, the @schema_prefix is used unless the :prefix is explicitly changed via Ecto.put_meta/2 or by passing the :prefix option to the repository operation.

so it implies that I don't have to configure anything else, but your solution means everytime I create new schema I should speicify which prefix to use in both _migration_ file and _schema_ file, and I still see @schema_prefix has no effect except as tag for me?

**Comment by josevalim** [comment]
You have to configure both, yes. And the `@schema_prefix` option should have an effect.

**Comment by alaadahmed** [comment]
<img width="294" alt="Screen Shot 2019-10-21 at 11 23 46 AM" src="https://user-images.githubusercontent.com/14099508/67199372-6188a300-f401-11e9-9bb5-e50d4c7ba282.png">
Both scheams `public` and `main` are empty after I ran migrations.

**Comment by alaadahmed** [comment]
So what I understood now, if I want to make multitenant app that uses prefixes I should do the following:
- I should configure `config/config.exs`
- I should __manually__ make schema in database by using `psql -d <DATABASE> -c "CREATE SCHEMA <SCHEMA>"
- I should __manually__ specify in each migration file which schema to use regardless what I speicified in `config.exs` or schema file.
- I should write `@schema_prefix` tag in the schema file that I want to use specific schema for.
is that right?!

**Comment by josevalim** [comment]
Yes. Generally everything you do in your migration you have to mirror in
your schema.
