### ISSUE TITLE
Changed behavior of ecto.gen.repo mix task in Elixir 1.9

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#3148]
Hi, originally I wanted to place it in mailing lists as proposition, but found that's more like bug, because it does not work as same as before `Elixir` release `1.9.0`.

First of all this does not produces any compile-time warning:
https://github.com/elixir-ecto/ecto/blob/c0d39069cdc92dcf34f1a528bd8eaf52f328d263/lib/mix/tasks/ecto.gen.repo.ex#L85-L93
I believe that typical beginner may not even correct this. Just btw. I would like to ask if we should add warning in `Mix.Config.__using__/1` macro.

The bigger problem is here:
https://github.com/elixir-ecto/ecto/blob/c0d39069cdc92dcf34f1a528bd8eaf52f328d263/lib/mix/tasks/ecto.gen.repo.ex#L54-L55
If we would have `import Config` then repo configuration would just not be added - this part looks like a bug for me as general behavior (adding config) is changed (not working as expected).

I suggest to add check like:
```elixir
Version.match? "1.9.0", Mix.Project.config()[:elixir]
```
and store first config line in a variable.

Is it ok to make PR for this one right now or it should be discussed on mailing lists before it?

**Comment by wojtekmach** [comment]
Thank you for starting discussion on this!

> `use Mix.Config`
>
> First of all this does not produces any compile-time warning
> I would like to ask if we should add warning in `Mix.Config.__using__/1` macro.

This is because as of v1.9 `Mix.Config` is soft-deprecated (no warning emitted). I don't remember the exact policy but I believe after 1 or 2 minor versions a soft-deprecations is supposed to turn into a warning.

> `String.replace(contents, "use Mix.Config\n", config_template(opts))`
>
> If we would have import Config then repo configuration would just not be added

Good catch!

I like your idea of pushing people towards new config. However, instead of assuming that in v1.9 they use `import Config`, I believe a more robust solution would be to check whether user's existing config has one or the other and make sure to preserve it.

I think it's fine to keep the discussion on the issue.

**Comment by Eiji7** [comment]
@wojtekmach 

> I don't remember the exact policy but I believe after 1 or 2 minor versions a soft-deprecations is supposed to turn into a warning.

Ah, in that case there was no question. :smiley:

> I like your idea of pushing people towards new config. However, instead of assuming that in v1.9 they use import Config, I believe a more robust solution would be to check whether user's existing config has one or the other and make sure to preserve it.

Ok, that makes sense for me. Please notice that after 1 or 2 minor versions in such case we would still keep old `use Mix.Config`, so maybe we should merge both ideas, so how about:

Instead of match for `1.9.0` we would check `1.10.0` or `1.11.0` (depends on soft-deprecation plans). If match succeed then we would force `import Config`. Otherwise we would follow user config.

**Comment by wojtekmach** [comment]
I’d rather not force the choice on the user. So if they don’t have a config file and use 1.9+ we’d use the new config module, but if they do, we’d preserve their choice.

I like the idea of automatically overwriting people’s code but I strongly believe it should be a separate tool (like eg go fix)
