### ISSUE TITLE
could not checkout the connection when there is a db call inside a genserver handled_call and it's wrapped in a transaction in caller process

### ISSUE THREAD

**Issue by bruteforcecat** [elixir-ecto/ecto#3152]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
`psql (PostgreSQL) 11.5`
* Ecto version (mix deps): 3.1.7
* Database adapter and version (mix deps): 0.15.0
* Operating system: macOS Mojave 10.14.6

### Current behavior
I created the test repo containing the minimal code to reproduce the bug(potential). Please checkout the test case.

https://github.com/bruteforcecat/Ecto-Sandbox-Bug-Demo/blob/master/test/ecto_sandbox_bug_demo_test.exs (test "shared mode" and `test "manual mode"` fail. Please checkout README to run the test case which should be very standard way of running test suite in mix project)

So I was getting the below error `DBConnection.ConnectionError` only when there is a function call wrapped in `Repo.transaction` and the function call will invoke another GenServer which will perform a db operation that inside `handle_call`. And I was using `shared` mode for sandbox.
```
08:08:19.966 [error] GenServer EctoSandboxBugDemo.TodoWorker terminating
** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.247.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 998ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto_sandbox_bug_demo) lib/ecto_sandbox_bug_demo/todo_worker.ex:26: EctoSandboxBugDemo.TodoWorker.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.247.0>): :create_todo
State: %{}
Client #PID<0.247.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:1007: GenServer.call/3
    (ecto_sql) lib/ecto/adapters/sql.ex:890: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
    test/ecto_sandbox_bug_demo_test.exs:29: EctoSandboxBugDemoTest."test shared mode"/1
    (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

And then I tried to use `manual` mode to allow that Genserver to have access to the DB connection process but then I got another `DBConnection.ConnectionError`

```
 ** (exit) exited in: GenServer.call(EctoSandboxBugDemo.TodoWorker, :create_todo, :infinity)
         ** (EXIT) an exception was raised:
             ** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.247.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 998ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
                 (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
                 (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
                 (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
                 (ecto_sandbox_bug_demo) lib/ecto_sandbox_bug_demo/todo_worker.ex:26: EctoSandboxBugDemo.TodoWorker.handle_call/3
                 (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior
I would expect the db oepration inside the genserver shouldn't fail in both `shared` mode or `manual` mode with explicit `allow` call.

**Comment by josevalim** [comment]
Yes, correct. The test sandbox has a single connection that is shared between processes (that's how we ensure data doesn't leak) and if you need to use it at the same time across two processes, then it won't work, there is nothing we can do about it.

Your best option, if you can't change the code since I am not sure how recommended generally speaking it is to have a transaction waiting on another process do something with another connection, is to not use the sandbox at all for those specific test cases and clean up the database after.

**Comment by josevalim** [comment]
Also, to be very clear, if the caller process is in a transaction, and the genserver checks out a connetion, **they are not the same database connection**. I.e. whatever the GenServer does won't happen inside the transaction. The transaction is always per process.

**Comment by bruteforcecat** [comment]
Thank you so much for letting me know. I guess then the only way to do this in Sandbox is using `auto` mode and manually cleaning up data?

**Comment by josevalim** [comment]
@bruteforcecat ah yes, you are correct. I think auto will work too.
