### ISSUE TITLE
Repo.aggregate/3 does not typecast the result

### ISSUE THREAD

**Issue by kipcole9** [elixir-ecto/ecto#3153]
### Environment

* Elixir version: 1.9.2 and 1.10.0-dev
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 9.6.3
* Ecto version (mix deps): 3.1.x, 3.2.0
* Database adapter and version (mix deps): Postgres 0.15.1
* Operating system: MacOS X Mojave

### Current behavior

`Repo.aggregate/3` does not support type casting the result.  In my example, the `ex_money_sql` package supports serialising a `Money` type to Postgres as a composite type. For example these are returned as `{"USD",#Decimal<100>}` from Postgrex. 

It also includes a custom aggregate function to sum money types. The following example illustrates the error:
```elixir
# Correct value is returned but it is not typecast event though `:payroll` is defined as a `:money_with_currency` type
iex> Repo.aggregate(Organization, :sum, :payroll)
{"USD", #Decimal<300>}

# Now try forced typecasting
iex> Repo.aggregate(Organization, :sum, type(:payroll, :money_with_currency))
== Compilation error in file test/db_test.exs ==
** (CompileError) test/db_test.exs:17: undefined function type/2
```
### Expected behavior

`Ecto.aggregate/3` to support typecasting the result as the other `ecto_sql` macros/function do. This is preferably done automatically since the type is known at compile time. Otherwise support the `type/2` macro.

**Comment by josevalim** [comment]
Fixed on master. Now you don't need the type in any situation. Thanks for the discussion!
