### ISSUE TITLE
`order_by` on virtual fields

### ISSUE THREAD

**Issue by lleger** [elixir-ecto/ecto#3155]
Is it possible to `order_by` a virtual/computed field in an Ecto query? The field is present in the query and the right data is being returned, but every way I try to use it in `order_by` I run into a snag.

Here's an example:

```elixir
defmodule MyApp.User do
  use Ecto.Schema

  schema "users" do
    field(:days_in, :integer, virtual: true)
  end
end

query = MyApp.User
|> select_merge(
  [u],
  %{
    days_in:
      fragment(
        "(date_part('day', now() - join_date))::bigint AS days_in"
      )
  }
)
```

The use case here is allowing for dynamic sorting in a table based on the computed column. It is being queried successfully and displays as expected. 

Here's what I tried and the errors I ran into:

**Using a string**
Tried: `order_by(query, {^sort_direction, ^sort_column})`
Error: ``** (ArgumentError) expected a field as an atom in `order_by`, got: "days_in"``

**Changing the field to an atom**
Tried: `order_by(query, {^sort_direction, ^String.to_existing_atom(sort_column)})`
Error: `** (Postgrex.Error) ERROR 42703 (undefined_column) column u0.days_in does not exist`

**Using a fragment**
Tried: `order_by(query, {^sort_direction, ^fragment(sort_column)})`
Error: ``** (Ecto.Query.CompileError) to prevent SQL injection attacks, fragment(...) does not allow strings to be interpolated as the first argument via the `^` operator, got: `sort_column` ``

Here's the only thing that *does* work for this:

```elixir
case sort_column do
  "days_in" ->
    query
    |> order_by({sort_direction, fragment("days_in"))
  
  column ->
    query
    |> order_by({sort_direction, field(u, ^column)})
end
```

I'm not sure if this is a bug report or a feature request, as I'm not 100% certain there's not some way of doing this already that I just haven't figured out yet. Happy to close/repost elsewhere if this is a bad place for this!

### Environment

* Elixir version (elixir -v): 1.9.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.2
* Ecto version (mix deps): 3.2.3
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: macOS 10.14.6

**Comment by hauleth** [comment]
[My proposal for solution from mailing list](https://groups.google.com/forum/#!topic/elixir-ecto/L1J9cWatvdI).

**Comment by jeregrine** [comment]
sorry for bumping an old topic but I'm bumping into this yet again and am motivated to improve this situation :) 

Could a solution be for select_merge to always name the column to the key name?

```
MyApp.User
|> select_merge(
  [u],
  %{
    days_in:
      fragment(
        "(date_part('day', now() - join_date))::bigint"
      )
  }
)
```

generates:

```
select (date_part('day', now() - join_date))::bigint AS u."days_in" from users as u
```

And we make note in select_merge that if you want to reference the fields from a select merge you need to treat those columns as dynamic and use the "field" macro?
```
MyApp.User
|> select_merge(
  [u],
  %{
    days_in:
      fragment(
        "(date_part('day', now() - join_date))::bigint"
      )
  }
)
|> where([u], field(u, ^:days_in) > 1)
```

We'd need to remove the [error](https://github.com/elixir-ecto/ecto/blob/v3.7.2/lib/ecto/query/planner.ex#L1736) in the field for using virtual types. 

_**Actually**_ if we removed the virtual check and let it die at the sql layer we could do this today:
```
MyApp.User
|> select_merge(
  [u],
  %{
    days_in:
      fragment(
        "(date_part('day', now() - join_date))::bigint AS ?", field(u, :days_in)
      )
  }
)
|> where([u], field(u, ^:days_in) > 1)
``` 

We might require the virtual field have a type in this case but we could error that way "if you plan on using a virtual field in a it requires a type and can't be any"

**Comment by jeregrine** [comment]
Also for posterity: a solution is to add an empty named column to the table and ship it.

**Comment by rparcus** [comment]
for posteriority 2:
In my case, I solved this with [selected_as](https://hexdocs.pm/ecto/Ecto.Query.API.html#selected_as/2).

I had to use `selected_as` both in the outmost select of my query AND in the order_by clause.

**Comment by thiagomajesk** [comment]
Just want to echo what @rparcus said, using `selected_as` is an excellent option for this.
I'm leaving an example based on something I had to do recently for people who might need it in the future:

```elixir
from q in "my-table",
  order_by: fragment("CASE WHEN name IS NULL THEN false ELSE true END desc, computed DESC"),
  select: %{
    name: selected_as(q.other_name, :name),
    computed: selected_as(q.value + q.value1 + q.value2, :computed)
  }
```

Using `selected_as` allows Ecto to properly reference the column names in the fragment.
