### ISSUE TITLE
Allow module to define own `__struct__/1` functions.

### ISSUE THREAD

**Issue by erlandsona** [elixir-ecto/ecto#3158]
Here ecto `schema` calls the [defstruct](https://github.com/elixir-ecto/ecto/blob/82389d98001c98e3c5257e4a71cc3c8ac9169f47/lib/ecto/schema.ex#L530) macro.

We're working on a large elixir code base and would like to be able to define our own `__struct__/1` functions to create stronger contracts between data structures and calling code. Along the lines of Opaque Types but with more idiomatic Elixir syntax.

Curious what thoughts / alternatives there are about these ideas.

**Comment by josevalim** [comment]
We could accept an option that makes the `defstruct` macro that we call configurable, but that's probably as far as we can go. If you are interested, a PR is welcome, but not something that we plan to tackle ourselves!

**Comment by wojtekmach** [comment]
You can also make `__struct__/1` overridable to customise it:

```elixir
defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field :name, :string
  end

  defoverridable [__struct__: 1]

  def __struct__(kv) do
    if kv[:name] && not is_binary(kv[:name]) do
      raise ArgumentError, "expected :name to be string, got: #{inspect(kv[:name])}"
    end

    super(kv)
  end
end

defmodule EctoExampleTest do
  use ExUnit.Case, async: true

  test "greets the world" do
    %Post{name: 1}
  end
end
```

```
== Compilation error in file test/ecto_example_test.exs ==
** (ArgumentError) expected :name to be string, got: 1
```

**Comment by erlandsona** [comment]
Any ideas why this breaks on variables?

**Comment by wojtekmach** [comment]
it's because we're running at compile-time and there we don't "see" the value of a variable.

**Comment by erlandsona** [comment]
Alright, wrapping my brain around the consequences of that. Thanks

**Comment by erlandsona** [comment]
Okay, we're lost trying to figure out how to unquote the keyword list?... or really at what point `__struct__/1` is being called?
Or how to write code like
```
  @spec __struct__(Keyword.t()) :: t | no_return
  def __struct__(kv) do
    str = kv[:reason]
    if String.contains?(str, "@") do
      %{__struct__: __MODULE__, reason: str}
    else
      raise(ArgumentError, "bad reason")
    end
  end
```
Because a value being built at runtime like `%MyThing{name: name} |> Repo.insert()` is super common...

**Comment by josevalim** [comment]
@erlandsona that's not an Ecto issue but it is how `__struct__/1` works. It is called both at runtime and compile time, and when called at compile time, you won't have the values, but their ASTs. To solve this, we would need to split `__struct__/1` into two functions, but that's a large change in Elixir that would need to be carefully discussed.

**Comment by erlandsona** [comment]
Ah! Okay, that's why it wasn't behaving as expected.
We're workin' up a solution to allow optionally overriding the macro Ecto calls, and will PR if we figure that out.
👍
