### ISSUE TITLE
Possible to update an empty string "" in an integer field using JSON on Postgres

### ISSUE THREAD

**Issue by chrism2671** [elixir-ecto/ecto#3163]
### Environment

* Elixir version (elixir -v): 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.10
* Ecto version (mix deps): 3.2.5
* Database adapter and version (mix deps): 3.2.1 ecto_sql & phoenix_ecto 4.1.0
* Operating system: Ubuntu 18.04 LTS

### Current behavior

Using Postgres JSON format, `Link` has an embedded field of `Rules`.

```
defmodule Shortr.LinkContext.Link do
  use Ecto.Schema
  import Ecto.Changeset

  schema "links" do
    belongs_to :workspace, Workspace
    has_many :clicks, Click
    has_many :conversions, Shortr.LinkContext.Conversion
    embeds_many :rules, Rule, on_replace: :delete
    timestamps()
  end

  def changeset(link, attrs) do
    IO.inspect link
    link
    |> cast(attrs, [:lots, :of, :fields])
    |> cast_embed(:rules, with: {Shortr.LinkContext.Rule, :changeset, []})
    |> validate_required([:url])
  end
end

```

```
defmodule Shortr.LinkContext.Rule do
  use Ecto.Schema
  import Ecto.Changeset
  embedded_schema do
    field :what, :string                
    field :matches, :string          
    field :url, :string                    
    field :percentage, :integer, default: 0
  end

  def changeset(rule, attrs) do
    IO.inspect attrs
    rule
    |> cast(attrs, [:what, :matches, :url, :percentage])
    |> validate_required([:what, :url])
  end
end 

```

The issue is it's possible for `:percentage` to be updated to `""` rather than `0`.

Steps to reproduce:

1. Create a valid record with valid `Rule`s.
2. Update the `Link`, this time removing a percentage from one of the `Rule`s (by removing the :percentage field altogether).

```
[debug] QUERY OK db=0.6ms
UPDATE "links" SET "rules" = $1, "updated_at" = $2 WHERE "id" = $3 [[%{id: "a75aed9f-31af-4576-998a-846d7c43474f", matches: nil, percentage: 50, url: "https://linklyhq.com", what: "rotator"}, %{id: "630696df-1576-4f45-8c05-9cad5130913f", matches: nil, percentage: "", url: "https://linklyhq.com", what: "rotator"}], ~N[2019-11-15 18:58:38], 2587]

```

3. Try reloading `Link`. It's impossible to load it as `:percentage` was saved as `""`.

This results in:
```
 ** (ArgumentError) cannot load `""` as type :integer for field `percentage` in schema Shortr.LinkContext.Rule
        (ecto) lib/ecto/schema/loader.ex:76: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4

```

### Expected behavior

I believe it should save `0` as per the schema.

**Comment by chrism2671** [comment]
Just to follow up, on inspecting the changeset:

```
Rule.changeset(%Rule{}, %{:what=>"asdf", :matches => "jkl", :url=>"qwer", :percentage => 0})
%{matches: "jkl", percentage: 0, url: "qwer", what: "asdf"}
#Ecto.Changeset<
  action: nil,
  changes: %{matches: "jkl", url: "qwer", what: "asdf"},
  errors: [],
  data: #Shortr.LinkContext.Rule<>,
  valid?: true
>

```

it appears that it isn't possible to set `:percentage =>0`; in this case it's removed from the `Rule`.

**Comment by wojtekmach** [comment]
> 2. Update the Link, this time removing a percentage from one of the Rules (by removing the :percentage field altogether).

How exactly are you doing this step?

**Comment by chrism2671** [comment]
Oh dear, you spotted it. I had:

```
    def update_link(%Link{} = link, attrs) do
    link_changeset = Link.changeset(link, attrs)
    link_changeset = 
      if attrs["rules"] do
        Ecto.Changeset.put_embed(link_changeset, :rules, attrs["rules"])
      else
        link_changeset
      end
    Repo.update(link_changeset)
  end

```

I'm pretty sure I don't need the `put_embed()`, without it everything seems to be OK.

I'm sorry for wasting your time. I think we can close this issue.

**Comment by wojtekmach** [comment]
Yeah it Link.changeset already calls `|> cast_embed(:rules)`, then the additional `|> put_embed(:rules)` calls may mess things up.

And no worries, glad it's fixed!
