### ISSUE TITLE
invalid join on when when building a new assoc to a query

### ISSUE THREAD

**Issue by gullitmiranda** [elixir-ecto/ecto#3165]
### Environment

* Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql (PostgreSQL) 11.2
* Ecto version (mix deps): 3.2.5
* Database adapter and version (mix deps):
```
* postgrex 0.15.1 (Hex package) (mix)
  locked at 0.15.1 (postgrex) 23ce3417
  ok
* ecto_sql 3.2.1 (Hex package) (mix)
  locked at 3.2.1 (ecto_sql) 4eed4100
  ok
```
* Operating system: macOS Catalina 10.15.1 (19B88)

### Current behavior

when i try to apply a assoc in a query using `Ecto.Association.assoc_query/4` i have a unexpected behavior. 

the test code is:

```elixir
iex > viewer
%Hive.Accounts.User{
  id: "eb2033cb-43d5-4bea-aa2c-afc5c8a03157",
  # ...
}

iex> viewer_assoc = Hive.Acquisitions.Invite.__schema__(:association, :viewers)
%Ecto.Association.HasThrough{
  cardinality: :many,
  field: :viewers,
  on_cast: nil,
  ordered: false,
  owner: Hive.Acquisitions.Invite,
  owner_key: :person_company_id,
  relationship: :child,
  through: [:groups, :users],
  unique: true
}

iex> clean_query = Hive.Acquisitions.Invite |> Ecto.Queryable.to_query

iex> Ecto.Association.assoc_query(viewer_assoc, [], clean_query, [viewer.id])
#Ecto.Query<from i0 in Hive.Acquisitions.Invite,
 join: p1 in Hive.Acquisitions.PersonCompany,
 on: p1.id == ^"eb2033cb-43d5-4bea-aa2c-afc5c8a03157",
 join: c2 in Hive.Workspaces.Company, on: c2.id == p1.company_id,
 join: c4 in Hive.Permissions.CompanyGroup, on: c4.company_id == c2.id,
 join: g3 in Hive.Workspaces.Group, on: u5.group_id == g3.id,
 join: u5 in Hive.Permissions.UserGroup, on: u5.group_id == g3.id,
 where: u5.user_id == i0.id, distinct: true>
```
like you can see, the join on check is invalid, since the value and assoc is related to the `User` instead of `PersonCompany`.

### Expected behavior

I hope the `join on` check is for the user, not `PersonCompany` id, like in 

```elixir
pry(25)> assoc
%Ecto.Association.HasThrough{
  cardinality: :many,
  field: :invites,
  on_cast: nil,
  ordered: false,
  owner: Hive.Workspaces.Company,
  owner_key: :id,
  relationship: :child,
  through: [:people_companies, :invites],
  unique: true
}
pry(26)> new_query = Ecto.Association.assoc_query(assoc, [], nil, [assoc_value])
#Ecto.Query<from i0 in Hive.Acquisitions.Invite,
 join: p1 in Hive.Acquisitions.PersonCompany,
 on: p1.company_id == ^"1d5b22c2-411a-49c0-aec7-0a551c63faea",
 where: i0.person_company_id == p1.id, distinct: true>
```

**Comment by josevalim** [comment]
Hi @gullitmiranda. Can you update the bug report to not use private APIs? `Ecto.Association.assoc_query` is not documented, so it should not be accessed directly. Maybe you isolated the bug already to that function (which is appreciated) but when writing a test we would likely test the whole operation, and for that we need the complete use case. Thank you.

**Comment by gullitmiranda** [comment]
hi @josevalim , the problem is that I use exactly this method because it was the way easier I found to attach the assoc to the query dynamically

**Comment by josevalim** [comment]
It is private API. We reserve the right to change it at any time. Also,
private APIs do not have documented behavior, so it is impossible for you
to say it is not working as expected, because you are not supposed to use
it. :)

If you want, you can describe your problem and we can figure out an API to
achieve what you want, but unless the behavior you describe is affecting a
public API, there is nothing to be changed here.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
