### ISSUE TITLE
adding key when insert.

### ISSUE THREAD

**Issue by inderjit23** [elixir-ecto/ecto#3166]
is it possible to add key to list (embaded_many)

eg :  this is my json i am trying to add as it is in database but need to validate first

`{
	"address": [{
            "address1": "old hamilton road",
            "address2": "11",
            "address3": "",
            "city": "new york",
            "town": "",
            "state": "",
            "zipcode": "458770"
        }]
}`

but when inserting to db field as json ecto insert without address key
`[{“address1”:“address1”,“address2”:null,“address3”:null,“city”:“city”,“country”:“country”,“desc”:null,“inserted_at”:“2019-11-17T21:31:52”,“party_id”:null,“state”:“hidd”,“town”:“hidd”,“type”:“P”,“updated_at”:“2019-11-17T21:31:52”,“zipcode”:“458770”}]`

how can i change or add key to changeset like this.

`{“address”: [{“address1”:“address1”,“address2”:null,“address3”:null,“city”:“city”,“country”:“country”,“desc”:null,“inserted_at”:“2019-11-17T21:31:52”,“party_id”:null,“state”:“hidd”,“town”:“hidd”,“type”:“P”,“updated_at”:“2019-11-17T21:31:52”,“zipcode”:"458770”}]}`

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
