### ISSUE TITLE
Improve docs by adding example for unique_constraint suffix option

### ISSUE THREAD

**Issue by aryzle** [elixir-ecto/ecto#3168]
### Environment

* Elixir version (elixir -v): 1.9.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 12
* Ecto version (mix deps): 3.1.7
* Database adapter and version (mix deps): 3.1.6
* Operating system: macOS Mojave 10.14.6

### Docs suggestion

This is more of a documentation improvement...

I just spent a while looking for why my `unique_constraint` on my model wasn't working. Figured out it was because my tables are partitioned and the key I was using didn't include the p0, p1 that gets added to the unique constraint key.

first attempt:
```
def changeset(dicom_sec, attrs) do
    dicom_sec
    |> cast(attrs, @mutable_attributes)
    |> validate_required(@required_attributes)
    |> unique_constraint(:dicom_aguid)
end
```
result:
```
changeset defined: dicom_anon_dicom_aguid_index

actual: dicom_anon_p94_dicom_aguid_key
```
works:
```
def changeset(dicom_anon, attrs) do
    dicom_anon
    |> cast(attrs, @mutable_attributes)
    |> validate_required(@required_attributes)
    |> unique_constraint(:dicom_aguid, name: :dicom_aguid_key, match: :suffix)
  end
```

Hoping this example can help improve the docs, show a usecase for the suffix option, and help someone else get to the answer quicker 😄

**Comment by josevalim** [comment]
Thanks @aryzle! Can you please send a PR?

**Comment by aryzle** [comment]
@josevalim done!

**Comment by josevalim** [comment]
Closing in favor of the PR!
