### ISSUE TITLE
Should I update the :returning documentation?

### ISSUE THREAD

**Issue by Olshansk** [elixir-ecto/ecto#3172]
I'm looking at [the changelog](https://github.com/elixir-ecto/ecto/blob/3423c6363dfd57114faa991ad3672283e6f5341f/CHANGELOG.md) and found the following statement:

> [Ecto.Repo] The :returning option for update_all and delete_all has been deprecated as those statements now support select clauses.

However, when I look at [the docs](https://hexdocs.pm/ecto/Ecto.Repo.html), it's still in place.

The discrepancy is that returning is shown as an option only for update/insert statements, but not delete statements. My question is, should I:

1. Add `:returning` as option in delete_all?
2. Remove `:returning` from the docs altogether?

**Comment by josevalim** [comment]
I think there is a confusion.

`:returning` is no longer supported on `update_all` and `delete_all`. It is supported on `insert_all`, `insert` and `update`. It is not currently supported on `delete` (perhaps it could but it certainly isn't). So the docs seem up to date?

**Comment by Olshansk** [comment]
Thanks for the explanation. The documentation reflects the status quo, and I was simply confused.

Thank you!
