### ISSUE TITLE
Allow passing `:*` as a column name in the `Repo.aggregate/{3,4}`

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#3175]
Reasoning the same as in #2595.

**Comment by josevalim** [comment]
Cool, PR is welcome, please! We can use a fragment to do `count(fragment("*"))`.

**Comment by michalmuskala** [comment]
What do you think about providing `aggregare/2` for this instead? I think this would mirror the `count/0` API better

**Comment by hauleth** [comment]
@michalmuskala I didn't do so to provide a way to pass an options to the call as for me it would be weird to have `Repo.aggregate/3` to work differently depending on 3rd argument.
