### ISSUE TITLE
validate_format/4 is not very useful

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3177]
### Current behavior

Currently [Ecto.Changeset](https://hexdocs.pm/ecto/Ecto.Changeset.html) provides a [`validate_format/4`](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_format/4) method for asserting that the contents of a field match a regular expression. An example is given to match that an email address contains an `@` character. However, in the more common case (at least in my experience), it is desirable to check if a field does _not_ match a regular expression. You can of course invert the regular expression to some extent like so:
```elixir
defmodule User do
  use Ecto.Schema

  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email])
    |> validate_length(:name, max: 50)
    |> validate_format(:name, ~r/\A((?!admin|moderator|\p{C}).)*\z/iu)
  end
end
```

But that is nowhere near as clear (or convenient) as being able to exclude a format.
```rb
class User < ApplicationRecord
  validates :name, length: { maximum: 50 }, format: { without: /admin|moderator|\p{C}/i }
end
```

### Expected behavior
Ecto.Changeset should provide a `validate_format/3` that accepts keyword arguments to either `require` or `forbid` a particular regular expression from matching.

**Comment by josevalim** [comment]
Hi @liamwhite! Your example in particular would be better written using validate_inclusion. At the same time I understand not all cases can be solved with validate_format, but whenever Ecto validations are not enough, you can always roll your own validation and use `add_error` to add further errors. Thanks!

**Comment by josevalim** [comment]
Actually, I was wrong, you want to make sure admin/moderator do not appear anywhere in your string, so validate_inclusion would not be enough. Still, I think in this case, it is probably best to use add_error anyway, as you need to craft a proper error message anyway.

**Comment by liamwhite** [comment]
The proper error message being something you could use in the `message` key to the hypothetical `validate_format/3`.

**Comment by pmarreck** [comment]
It wouldn't be that hard to write your own `validate_not_format`, looking at the source for `validate_format`:

```
  @spec validate_format(t, atom, Regex.t, Keyword.t) :: t
  def validate_format(changeset, field, format, opts \\ []) do
    validate_change changeset, field, {:format, format}, fn _, value ->
      if value =~ format, do: [], else: [{field, {message(opts, "has invalid format"), [validation: :format]}}]
    end
  end
```
Based on this one could easily write:
```
  @spec validate_not_format(t, atom, Regex.t, Keyword.t) :: t
  def validate_not_format(changeset, field, format, opts \\ []) do
    validate_change changeset, field, {:format, format}, fn _, value ->
      if !(value =~ format), do: [], else: [{field, {message(opts, "has invalid format"), [validation: :format]}}]
    end
  end
```
  
I should note that I believe there is a semantic difference between "negating a regex match" and "negative-lookahead'ing a regex match", so this may be necessary to get the behavior you need. Needless to say, (cover any use of this validation with some test cases!)
