### ISSUE TITLE
checkout does parallel preloads

### ISSUE THREAD

**Issue by hkrutzer** [elixir-ecto/ecto#3180]
### Environment

* Elixir version (elixir -v): 1.9.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.7
* Ecto version (mix deps): 3.2.5
* Database adapter and version (mix deps): MyXQL based on v0.2.10
* Operating system: MacOS

### Current behavior

I am using `Repo.checkout` for load shedding (if no connection is available before the queue target timeout, I will drop the message). However, in one of the queries I perform there is a preload. The preload is performed in parallel (by default) and therefore on a different connection. If I have maxed out all my connections (and start dropping messages), I get DBConnection errors on the requests that _have_ a checked out connection, because besides the one that is checked out additional connections are needed for the preload. This results in serving no requests being served during overload, instead of some requests being served and others dropped.

When I use `Repo.transaction` instead of `checkout`, only a single connection is used (as is written in the docs). However, I only perform read queries so this would be an unnecessary transaction. I feel `checkout` should act like `transaction` with respect to preloads.

### Expected behavior

Ecto does not do parallel preloading on a different connection when using a checkout, because when I have a connection checked out, I expect to be ensured that I have a usable connection for all queries using that repo for the duration of the checkout.

**Comment by josevalim** [comment]
The reason we MUST NOT start for transactions is because we can break transactional guarantees but spawning parallel preloads in a checkout can be desired or undesired (as you mentioned). In your case, I think it is best to explicitly opt-out by passing `in_parallel: false`. Thank you!

**Comment by hkrutzer** [comment]
Is it possible to disable preloads for the entire repo?

**Comment by wojtekmach** [comment]
I don't think there's an option to globally disable it, but you can override Repo.preload/3 to set the default option value for your particular repo.

```elixir
defmodule MyRepo do
  use Ecto.Repo

  defoverridable [preload: 3]

  @impl true
  def preload(struct_or_structs_or_nil, preloads, opts \\ []) do
    opts = Keyword.put_new(opts, :in_parallel, false)
    super(struct_or_structs_or_nil, preloads, opts)
  end
end
```
