### ISSUE TITLE
Allow the use of the association names for bindings

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3183]
Currently there are two ways to specify the bindings when using Ecto.Query functions:

* Positional binding
`where(query, [x, y], ...`

* Named binding
`join(query, ..., as: :some_name, ... # must be known at compile time`

It would be nice to have an option so that one can specify the association names as the bindings:
`where(query, [:posts, :comments], ...`

I think the reason that Ecto currently doesn't allow that, is because an association can be joined multiple times. But in that case, it can simply be a documented known limit for that functionality, and someone willing to join an association multiple times would need to use the positional or named binding only.

The reason why I come up with this, is because it is not trivial to build dynamic composable queries with bindings based on position. The named binding was introduced, but the `:as` needs to be specified at compile time.

**Comment by josevalim** [comment]
So I implemented this in master and I got failures in some apps because they were already setting that association to something else, and the conflict lead to failures. So unfortunately there is no way we can introduce this behaviour without breaking changes, sorry.
