### ISSUE TITLE
Preload documentation - inconsistencies?

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3185]
The docs shows this example for preloading nested associations:

```
# Returns all posts, their associated comments, and the associated
# likes for those comments.
from(p in Post,
  preload: [:comments, comments: :likes],
  select: p)
```

So in order to preload the `:likes`, it seems that we have to preload the `:comments` beforehand as well.

However earlier in the docs, we saw this example:
```
Repo.all from p in Post,
  preload: [comments: :likes]
```

Why in the latter snippet, we do not have to specify `:comments` before `comments: :likes` as in the snippet above?

Second point of confusion, the following snippet in the docs:

```
Post
|> join(:left, [p], c in assoc(p, :comments))
|> preload([p, c], [:user, comments: c])
|> select([p], p)
```

Why don't we join with `:user` before preload? I think without the join it will execute an additional query? No reason for this as we can simply join and it will generate only a single query?

**Comment by josevalim** [comment]
> So in order to preload the :likes, it seems that we have to preload the :comments beforehand as well.

Yes, this is wrong. Good catch.

> Why don't we join with :user before preload? I think without the join it will execute an additional query? No reason for this as we can simply join and it will generate only a single query?

It is best to avoid using joins because joins return M x N rows, while preloads return M + N. Of course, if you have a one to one relationship, then a join is simpler, but in almost all other cases the joins are actually more expensive because the DB has to return more data, which we then need to parse and decode.

**Comment by thojanssens** [comment]
> Of course, if you have a one to one relationship, then a join is simpler, but in almost all other cases the joins are actually more expensive because the DB has to return more data, which we then need to parse and decode.

I think not only _one-to-one_ but also if I want to load the data of the belongs_to association (many-to-one), as that should return only one row, and which is much more common than a one-to-one. In that case I guess a join is cheaper.

**Comment by josevalim** [comment]
Yes, correct!

**Comment by thojanssens** [comment]
José sorry to bring this once again up, I have been further experimenting with the `:preload` option, and I think I found a limitation which has not been documented.

In the snippet below from the docs, we have joined on both the `:comments` and `:likes`, so we use the bindings in the preload option:

```
query =
  Query.from(p in Post,
    join: c in assoc(p, :comments),
    join: l in assoc(c, :likes),
    where: l.inserted_at > c.updated_at,
    preload: [comments: {c, likes: l}]
  )
```

However, what if we only join on `:comments` and want to preload the `:likes`?
I tried the following:

```
query =
  Query.from(p in Post,
    join: c in assoc(p, :comments),
    where: c.inserted_at > p.updated_at,
    preload: [comments: {c, :likes}]
  )
```

You can see above I only joined on `:comments`, so I have a binding for `:comments` but not for `:likes` (which I then expect to be retrieved by an additional query).

But it generates something weird:

> from p0 in QueryBuilder.Post,
>   join: c1 in assoc(p0, :comments),
>   where: c1.inserted_at > p0.updated_at,
>   preload: [comments: [:likes]],
>   preload: [comments: c1]

Doesn't look good?

Is there a limitation in that if I preload an association with a binding, all the nested associations must have a binding though join?

Or I wrote a wrong syntax?

Or is the query as string above correct?

**Comment by josevalim** [comment]
This syntax is definitely correct:

```
query =
  Query.from(p in Post,
    join: c in assoc(p, :comments),
    where: c.inserted_at > p.updated_at,
    preload: [comments: {c, :likes}]
  )
```

Maybe the syntax we inspect is also correct... but if not, we have a bug on inspecting.

**Comment by thojanssens** [comment]
Ok I will test it thoroughly tomorrow with data; I think the string output looks weird though for that last case.
