### ISSUE TITLE
Inspected queries to return normalized preload values

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3188]
Inspecting the following query:
```
query
|> preload([articles: a, user: u, role: r], [articles: {a, [user: {u, [role: r]}]}])
|> preload([articles: a, comments: c, comment_stars: s], [articles: {a, [comments: {c, [comment_stars: s]}]}])
|> preload([articles: a, comments: c, comment_likes: l], [articles: {a, [comments: {c, [comment_likes: l]}]}])
```
returns for the preload part:
```
preload: [articles: {a2, [user: {u0, [role: r1]}]}, articles: {a2, [comments: {c3, [comment_stars: c5]}]}, articles: {a2, [comments: {c3, [comment_likes: c4]}]}]
```

Why isn't it normalized as a tool is already doing that in the tests:
https://github.com/elixir-ecto/ecto/blob/v3.3.0/test/ecto/query/planner_test.exs#L991

Worse for preload values without binds:

```
query
|> preload([articles: :article_likes])
|> preload([articles: :article_stars])
```
prints:
```
preload: [articles: [:article_likes], articles: [:article_stars], articles: [:article_likes]]
```

```
query
|> preload([articles: :article_likes])
|> preload([articles: :article_stars])
|> preload([articles: [comments: :comment_likes]])
```
prints:
```
preload: [articles: [:article_likes], articles: [:article_stars], articles: [comments: [:comment_likes]], articles: [:article_likes]]
```

Also, do we have the guarantee through the tests that these accumulated preload values will always work? Should a test be added against a query with accumulated preload values without binds, just as this one with binds? https://github.com/elixir-ecto/ecto/blob/v3.3.0/test/ecto/query/planner_test.exs#L991
Just worried because I rely on that for some library 😅

Note that to print a query I execute:
`IO.puts Inspect.Ecto.Query.to_string(query)`

**Comment by josevalim** [comment]
The behaviour is for sure tested, you don't have to worry about it. This is just a visual representation concern.

**Comment by josevalim** [comment]
So I tried exploring this and all of the fields are not joined by default - wheres, preloads, order_by, etc. So we either change all of them or only one of them. Since this is a larger effort, we don't plan to tackle it, but if someone is interested, please let us know.
