### ISSUE TITLE
`validate_length/3` not working on a `Struct` that has `non empty string` field.

### ISSUE THREAD

**Issue by Guang1234567** [elixir-ecto/ecto#3189]
Hello dev:

As title said, i just test in ` iex` like below:

Could you give me some suggestion, thanks.

```bash
iex [10:37 :: 60] > %Character{name: ""} |> change() |> validate_length(:name, min: 3) |> validate_required([:name])
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [name: {"can't be blank", [validation: :required]}],
  data: #Friends.Character<>,
  valid?: false
>
```

It’s expected, because `validate_required`.

But

```bash
iex [10:37 :: 59] > %Character{name: "12"} |> change() |> validate_length(:name, min: 3) |> validate_required([:name])
#Ecto.Changeset<action: nil, changes: %{}, errors: [],
 data: #Friends.Character<>, valid?: true>
```

It’s not expect, because ` validate_length(:name, min: 3)` is `3`, but `name`’s length is 2.

**Comment by josevalim** [comment]
The changeset only validated what was given as change. It doesn’t validate fields currently in. The struct. So if you do `change(name: “ab”)` instead of setting it in the struct directly, then it should work.

**Comment by feliperenan** [comment]
Hi @josevalim 👋🏻 

I've faced something this issue today using default values in the Ecto schema. Something like:

```Elixir
defmodule Foo do
  use Ecto.Schema
  
  import Ecto.Changeset
  
  @primary_key false
  schema "foo" do
    field :list, {:array, :string}, default: []
  end
  
  def changeset(changeset, params) do
    changeset
    |> cast(params, [:list])
    |> validate_length(:list, min: 1)
  end
end
```

Then, the validation does not work properly for this case.

```Elixir
Foo.changeset(%Foo{}, %{list: []})
# => #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Foo<>,valid?: true>
```

I end up just removing the default value from the schema. Should we at least document this behaviour? I'd suggest something like that in here:

https://hexdocs.pm/ecto/Ecto.Schema.html#field/3-options

> Once a default value is set, if you send changes to the changeset and these changes contains the same value as defined as default, validations will not be performed since there are changes after all.

**Comment by josevalim** [comment]
Sounds great to me, PR is welcome!
