### ISSUE TITLE
Selecting maps using constants other than binary literals raises an error

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3190]
## Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12
* Ecto version (mix deps): ecto 3.2.5 (Hex package) (mix)
* Database adapter and version (mix deps): postgrex 0.15.1 (Hex package) (mix)
* Operating system: Linux amd64

### Current behavior

This doesn't work [(schema reference)](https://github.com/derpibooru/philomena/blob/master/lib/philomena/images/tagging.ex):
```elixir
# Let target = %{id: 5}

Tagging
|> where(image_id: ^source.id)
|> select([t], %{image_id: ^target.id, tag_id: t.tag_id})
|> Repo.all()

# ** (DBConnection.EncodeError) Postgrex expected a binary, got 5.
```

In order to work around it, I do this:
```elixir
Tagging
|> where(image_id: ^source.id)
|> select([t], %{image_id: ^to_string(target.id), tag_id: t.tag_id})
|> Repo.all()
|> Enum.map(&%{&1 | image_id: String.to_integer(&1.image_id)})
```

### Expected behavior
You should be allowed to select whatever you want in a query (assuming it can be casted to a database type) as an interpolated literal and expect it to come back as the same thing.

**Comment by josevalim** [comment]
The issue here is that when you are using a map, we don't actually know the type of `image_id`. So your schema does not matter. Postgres does infer the type later as a binary - which is a weird choice but one that is out of our control.

Luckily, you can also fix this by explicitly telling Postgres the expected type:

    Tagging
    |> where(image_id: ^source.id)
    |> select([t], %{image_id: type(^target.id, :integer), tag_id: t.tag_id})
    |> Repo.all()

**Comment by x-ji** [comment]
Thanks @josevalim . Exactly the problem I faced and I solved it using your advice :)
