### ISSUE TITLE
Crash when loading row containing NaN

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3192]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12
* Ecto version (mix deps): ecto 3.2.5 (Hex package) (mix)
* Database adapter and version (mix deps): postgrex 0.15.1 (Hex package) (mix)
* Operating system: Linux amd64

### Current behavior
[Relevant schema](https://github.com/derpibooru/philomena/blob/master/lib/philomena/images/image.ex)

```
philomena_dev=# update images set image_aspect_ratio='NaN'::double precision where id=7;
UPDATE 1
```
```
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Repo.get(Image, 7)
** (ArgumentError) cannot load `:NaN` as type :float for field :image_aspect_ratio in %Philomena.Images.Image{...}
    (ecto) lib/ecto/repo/queryable.ex:364: Ecto.Repo.Queryable.struct_load!/6
    (ecto) lib/ecto/repo/queryable.ex:191: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/queryable.ex:182: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:97: Ecto.Repo.Queryable.one/3
iex(1)> 
```
### Expected behavior
No crash should occur

**Comment by josevalim** [comment]
Ecto doesn’t support NaN on purpose. However, you can always define a custom type that allows so. See Ecto.Type for more information. Thanks!

**Comment by liamwhite** [comment]
I understand that there is a reasonable argument against not being able to insert new NaN values into the database, but it doesn't make sense to me why Ecto is against the idea of being able to _load_ it, given that floats and double precisions are loaded as a [Decimal](https://hexdocs.pm/decimal/Decimal.html), and that type does support NaN:
```elixir
iex(1)> Decimal.new("NaN")
#Decimal<NaN>
```
If this is decision that has been made, and it's final, would it be acceptable to add an IEEE754Float type to Ecto directly to handle these types of values, including other edge cases like +/-Inf, +/-0, etc., so that it wouldn't have to be needlessly reimplemented in every downstream application that wants this behavior?

**Comment by josevalim** [comment]
If the concern is duplication, then it can be provided as a separate package. In fact, said package may already exist, as I remember having this discussion once in the past (which shows it is not a frequently asked feature either).
