### ISSUE TITLE
Replacement for :replace_all_except_primary_key option is not documented

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3193]
[This code](https://github.com/derpibooru/philomena/blob/c14d0b6f340b1a6919826e9a586755662e61ad08/lib/philomena/galleries.ex#L265-L270)
```elixir
  Repo.insert_all(
    Interaction,
    changes,
    on_conflict: :replace_all_except_primary_key,
    conflict_target: [:id]
  )
```
issues the following warning
```
iex(philomena@127.0.0.1)1> warning: :replace_all_except_primary_key is deprecated, please use {:replace_all_except, [...]} instead
  (ecto) lib/ecto/repo/schema.ex:600: Ecto.Repo.Schema.on_conflict/5
  (ecto) lib/ecto/repo/schema.ex:51: Ecto.Repo.Schema.do_insert_all/6
  (philomena) lib/philomena/galleries.ex:265: anonymous fn/2 in Philomena.Galleries.reorder_gallery/2
```
However this is not stated in the documentation for the callback, nor is the replacement documented anywhere I could find at a glance
https://github.com/elixir-ecto/ecto/blob/6b4b6d3eba18d6d44484bc5b636e36a52bd7eafa/lib/ecto/repo.ex#L988-L1092

**Comment by josevalim** [comment]
Oh, good call! :on_conflict is supported in two places and I changed only
one. I will update everything accordingly.
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D
