### ISSUE TITLE
I can't delete a database because of the pool of active users

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#3194]
**Issue**: I can't delete a database because there's always a pool of active users/sessions.

I have a phoenix app which is the only app on a server which uses Postgres. 

Normaly it runs as a daemon. I've stopped it:

        /usr/local/my_app/app1/bin/app1 stop

Indeed, in the list of the processes it doesn't appear.

Despite of this, there're still 15 active sessions. As if the app was still active. I can't kill the sessions. 

I've tried 

1) restarting Postgresq service

2) killing the sessions manually:

```
REVOKE CONNECT ON DATABASE db1 FROM public; 


SELECT pid, pg_terminate_backend(pid) 
FROM pg_stat_activity
WHERE datname = current_database() AND pid <> pg_backend_pid();

```
3) restarting a server

To no avail. There're always 15 sessions in the idle state. And thus I can't delete a database.

I suspect that Ecto or some other library related to it is the reason.

**Comment by josevalim** [comment]
I cannot reproduce the issue. I created a new Phoenix app, started and stopped it, and then PG reported no open connections afterwards.

However, note that when using TCP connections, the time for the other side to notice the connection was closed will pretty much depend on the OS. There is nothing Ecto can do about it.

If you have an app that consistently reproduces the error, then please let us know and we can give it a try but until I find it unlikely to be an Ecto issue.

PS: Also please follow the issues template when reporting an issue the next time. Thank you.
