### ISSUE TITLE
Failed typecasts don't raise Ecto.CastError

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3196]
### Environment

* Elixir version (elixir -v): 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12
* Ecto version (mix deps): 3.3.0
* Database adapter and version (mix deps): ecto_sql 3.3.2, postgrex 0.15.3
* Operating system: Linux

### Current behavior

[This code](https://github.com/derpibooru/philomena/blob/f8f34c82454934cea7772340dca8602e4412f559/lib/philomena_web/plugs/load_post_plug.ex#L16-L19)
```elixir
    Post
    |> where(topic_id: ^topic.id, id: ^to_string(conn.params[param]))
    |> preload([topic: :forum, user: [awards: :badge]])
    |> Repo.one()
```
does not raise a cast error when the string represents an integer in base 10 which is greater than 2\*\*31-1 or less than -2\*\*31
```
iex(2)> Repo.get_by(Post, id: "2147483648") 
** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got -2147483649. Please make sure the value you are p
iex(3)> Repo.get_by(Post, id: "-2147483649") 
** (DBConnection.EncodeError) Postgrex expected an integer in -2147483648..2147483647, got -2147483649. Please make sure the value you are p
```
### Expected behavior
This should raise a cast error like other invalid queries
```
** (Ecto.Query.CastError) deps/ecto/lib/ecto/repo/queryable.ex:410: value `"2147483649aaaaa"` in `where` cannot be cast to type :id in query:

from p0 in Philomena.Posts.Post,
  where: p0.id == ^"2147483649aaaaa",
  select: p0

```

I can't tell from the [documentation on Ecto.Schema](https://hexdocs.pm/ecto/Ecto.Schema.html#schema/2) how it is intended to make the `id` casting force the required range for int4s. Do I have to migrate my schema to use bigints for all surrogate keys?

**Comment by josevalim** [comment]
Correct. That is not a casting error since we can cast it to integer just fine and we don't have a built-in Ecto type that represents int4 exclusively. Is there a particular reason why you would want those to raise a cast error? In my opinion, I wouldn't worry about it, but if you really want to, you can always implement your own Int4 type that checks the boundaries too.

**Comment by liamwhite** [comment]
The reasoning for this to be an Ecto.CastError is primarily with the intent to take advantage of [Phoenix's default handling of CastError](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/plug.ex).

**Comment by josevalim** [comment]
You can do the same for DBConnection.EncodeErrorr too if you want. None of it is hardcoded to Ecto or Phoenix. :)
