### ISSUE TITLE
belongs_to prevents use of names same as foreign_key

### ISSUE THREAD

**Issue by foobarto** [elixir-ecto/ecto#3198]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.9.2 (compiled with Erlang/OTP 22)

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
Postgres 12

* Ecto version (mix deps):

  ecto 3.2.5 (Hex package) (mix)

* Database adapter and version (mix deps):

  ecto_sql 3.2.2 (Hex package) (mix)
  phoenix_ecto 4.1.0 (Hex package) (mix)
  
* Operating system:
  Linux/Manjaro

### Current behavior

I'm working with a legacy db with schema that does not follow Ecto's expectation. In this particular case a  field `actor` which is a foreign key. `belongs_to` automagically adds suffix `_id` when specifying name (first argument). So naturally I tried

```elixir
belongs_to :actor, Actor, foreign_key: :actor
``` 

I expected to still have the variable named `actor` and use the field with name `actor` to prevent Ecto suffixing it with `_id`.

However what I've got is this exception:

```
(ArgumentError) foreign_key :actor must be distinct from corresponding association name
    lib/ecto/schema.ex:1815: Ecto.Schema.__belongs_to__/4
``` 

### Expected behavior

Be able to set same field name with `belongs_to` as `foreign_key` value.

**Comment by josevalim** [comment]
Unfortunately there is no way this can work, as the association and the field are two distinct fields on the struct, and they need to have different names.

What you can try to do is this:

    belongs_to :actor, Actor, source: "actor"

Or

    field :actor_id, :integer, source: "actor"
    belongs_to :actor, Actor, define_field: false

**Comment by josevalim** [comment]
Or, to avoid confusion, use a distinct name for `belongs_to`, such as `:actor_data` or similar.

**Comment by foobarto** [comment]
Thanks for clarifying this @josevalim indeed `source: :actor` is what I was looking for.
