### ISSUE TITLE
 Ecto fragments with MySQL fulltext search does not work properly in Ecto.Adapters.SQL.Sandbox

### ISSUE THREAD

**Issue by bigardone** [elixir-ecto/ecto#3208]
### Environment

* Elixir version (elixir -v): 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8.0.17
* Ecto version (mix deps): 3.3.1
* Database adapter and version (mix deps): myxql 0.3.1
* Operating system: macOS Catalina

### Current behavior

I have set up a repo to replicate the issue, which contains an expanded description of the problem with all the details :)
https://github.com/bigardone/ecto_mysql_fulltext_issue

TL;DR

Using Ecto fragments with MySQL `fulltext` search does not work properly on tests using `Ecto.Adapters.SQL.Sandbox`, although it works correctly in any other env. This makes the tests fail incorrectly.

From iex:

![image](https://user-images.githubusercontent.com/1090272/72596329-20befe00-390c-11ea-940f-291940a3bb83.png)

Running the test:

![image](https://user-images.githubusercontent.com/1090272/72596355-2b799300-390c-11ea-8416-85c22953ac55.png)

### Expected behavior

The query should return the same results as in `dev`, making the tests pass.

**Comment by josevalim** [comment]
Unfortunately there is nothing we can do here. The sandbox runs tests inside a transaction but rows are only indexed when the transaction is committed. You need to fully disable the sandbox for those tests (setting it to auto mode) or at least define a separate repo in your test helper, that is not in sandbox mode, and use that repo for the tests that handle full text search. Something like this:

```elixir
Application.put_env(:my_app, MyApp.BareRepo, MyApp.Repo.config() |> Keyword.delete(:pool))
defmodule MyApp.BareRepo do
  use Ecto.Repo, otp_app: :my_app, adapters: Ecto.Adapters.MyXQL
end
```

Then in the tests, you can set the actual repo to use MyApp.Repo:

```elixir
MyApp.Repo.put_dynamic_repo(MyApp.BareRepo)
```

or similar.
