### ISSUE TITLE
In optimistic locking, lock is incremented upon update error: is this correct?

### ISSUE THREAD

**Issue by marick** [elixir-ecto/ecto#3210]
I may misunderstand correct use of `Changeset.optimistic_lock`. (I've asked on the Elixir Forum, but got no reply.) If I misunderstand, I'll try to help with the documentation. Less likely, I have a change request for the feature's behavior. 

### Environment

* Elixir version (elixir -v): Elixir 1.9.2 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql (PostgreSQL) 11.3
* Ecto version (mix deps): ecto 3.2.3 
* Database adapter and version (mix deps): postgrex 0.15.1
* Operating system: OSX 10.14

### Explanation

I assume that optimistic locking should be used like this, given an HTML form:
1. The version presented for update is saved in a hidden field.
2. When the form is submitted, the newest version of the table row is read.
3. Then the just-read struct and the submitted parameters are given to a changeset-creation function. 

Let's consider the case where there was no problem with the lock value, but an error elsewhere in the form. In a trial I just made, 

1. The "lock_version" parameter is 3.
2. The loaded struct's `:lock_version` is also 3. (No one else changed the value.)
3. When the two are combined into a changeset, the lock version is incremented: `changes: %{lock_version: 4, name: "bossie"}`
4. The name change is incorrect because there's already a record with that name. (This is a constraint error, but the following steps also happen for a validation error.)
5. `Repo.update` returns a changeset including the updated lock version. That changeset will be used to populate another form, annotated with errors, intended to give the user another try. 
6. That means the hidden form field will contain "4" **if** you use `hidden_input` to populate it.
7. When that next form is submitted, the hidden field's "4" will be combined with the database version's 3, yielding a changeset with `changes: %{lock_version: 4, name: "ok"},`
8. However, when that changeset is passed through `optimistic_lock`, the resulting changeset looks like this: `changes: %{lock_version: 5, name: "ok"}`. 
9. The resulting SQL command is `UPDATE "demo"."animals" SET "lock_version" = $1, "name" = $2, "updated_at" = $3 WHERE "id" = $4 AND "lock_version" = $5 [5, "ok", ~N[2020-01-20 23:22:02], 1, 4]`.
10. The result is an error: `errors: [optimistic_lock_error: {"is stale", [stale: true]}],`

That is: the first error has made it impossible for the user to successfully edit the record.

My solution was to delete the `optimistic_lock` key from `changeset.changes` upon error. Would it make sense for that to be done automatically? Because the idea that the lock version has been incremented is a lie. 

```elixir
  def update(animal, attrs, institution) do
    case try_update(animal, attrs, institution) do
      {:error, %{errors: [{:optimistic_lock_error, _}]}} ->
        {:error, changeset_for_lock_error(animal.id, institution)}

      {:error, partial_changeset} ->
        changeset =
          partial_changeset
          |> ChangesetX.flush_lock_version  ## <<<<<<<<<<<
          |> changeset_for_other_error
        {:error, changeset}
...


  def flush_lock_version(changeset),
    do: Ecto.Changeset.delete_change(changeset, :lock_version)

```

**Comment by josevalim** [comment]
@marick I want to confirm this is a bug. It was used to work but then [we changed the priority of params/changes lookup](https://github.com/phoenixframework/phoenix_ecto/issues/71). I think to solve this we will need to add a new field to the changeset that keeps fields that must be removed on failures (or we automatically do so for all filters).

**Comment by josevalim** [comment]
Also, thank you for the detailed report! To me it is an actual pleasure to look at and reply to well reported bugs!
