### ISSUE TITLE
:autogenerate in `Ecto.Schema.timestamps/1`

### ISSUE THREAD

**Issue by jbcaprell** [elixir-ecto/ecto#3228]
https://github.com/elixir-ecto/ecto/blob/60ba8fb2a6c000171cd16003dbf8110a311d661e/lib/ecto/schema.ex#L637

The documentation for the macro seems to indicate that the automatic generation of timestamps can be turned off—not the fields, but the data that populates the fields, as with setting `autogenerate: false` on `@primary_key`. Setting `@timestamps_opts [autogenerate: false]` in an Ecto.Schema, however, doesn’t stop the generation of timestamps.

**Comment by josevalim** [comment]
@jbcaprell can you please show where in the docs we say that autogeneration can be turned off? We currently say:

>     * `:autogenerate` - a module-function-args tuple used for generating
>      both `inserted_at` and `updated_at` timestamps

`autogenerate: false` indeed is not supported. :)

**Comment by jbcaprell** [comment]
@josevalim I think it’s actually that I’ve read too much into the `@doc` for this macro, where `:autogenerate` is listed as an “option,” amongst “all options.” If it’s not intended that anything be done with the `:autogenerate` tuple by end-users, *maybe* it’s a just a matter of the clarity of “all options” in the doc, coupled with an assumption on my part of parity between instances of `:autogenerate`. I might well be alone in my misunderstanding, though!

The thought, if this is helpful, was whether it was possible to allow the database to handle the filling of `inserted_at` and `updated_at` through the use of defaults and trigger functions, with a mind toward multiple applications hitting the same database while disagreeing about what “time” it is.

A person can just always not use the macro and pass the columns to the Schema outright, so nothing is really being lost here!

https://github.com/elixir-ecto/ecto/blob/60ba8fb2a6c000171cd16003dbf8110a311d661e/lib/ecto/schema.ex#L632-L635

**Comment by josevalim** [comment]
`@timestamp_opts` does accept all options. It is just that nowhere says that `:autogenerate` can be `false` in this case. :)

> A person can just always not use the macro and pass the columns to the Schema outright, so nothing is really being lost here!

Yes exactly. Then at this point `timestamps` is not being anything and listing it explicitly is better, IMO.

If you feel the docs could be better though, a PR is welcome! Thanks!
