### ISSUE TITLE
Can't inject table name in a lock - "FOR UPDATE OF <table>" with Ecto 3

### ISSUE THREAD

**Issue by msramos** [elixir-ecto/ecto#3229]
### Environment

* Elixir version (elixir -v):

    Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
    Elixir 1.10.0 (compiled with Erlang/OTP 21)

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

    PostgreSQL 9.6

* Ecto version (mix deps):

    ecto 3.3.2 (Hex package) (mix)

* Database adapter and version (mix deps):

    ecto_sql 3.3.3 (Hex package) (mix)
    phoenix_ecto 4.1.0 (Hex package) (mix)

* Operating system:
    MacOS Mojave 10.14.6

### Current behavior

When configuring the the `lock` option in a query with several joins, it's not possible to inject the table name (which is required in this case), since the `lock` option [only accepts binaries](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder/lock.ex#L18).

### Expected behavior

It was possible to use [Ecto.Query.API.fragment/1](https://hexdocs.pm/ecto/Ecto.Query.API.html#fragment/1) in this option before Ecto 3. I expect either this feature being re-enabled or another way to inject the table's name here.

**Comment by josevalim** [comment]
Hi @msramos! There is a PR here: https://github.com/elixir-ecto/ecto_sql/pull/189

You can try it out with:

    {:ecto_sql, github: "elixir-ecto/ecto_sql", branch: "jv-fragment-lock", override: true},
    {:ecto, github: "elixir-ecto/ecto", override: true},

If it works, please let us know and we will ship a new release.

**Comment by msramos** [comment]
Hey, @josevalim, I just tested it and it's working as expected!

**Comment by josevalim** [comment]
New versions have been released.
