### ISSUE TITLE
Aggregate count of rows

### ISSUE THREAD

**Issue by optikfluffel** [elixir-ecto/ecto#323]
Hi, I'm trying to count the number of existing users in a small petproject of mine and currently came up with

``` elixir
number_of_users = Repo.all(from u in User, select: u.id) |> Enum.count
```

Is there a way to use something like

``` SQL
SELECT COUNT(*)   
FROM users;
```

with ecto?

Thanks in advance

**Comment by hickscorp** [comment]
@optikfluffel I like very much to use the `Repo.aggregate/2` function. In your case:

```elixir
count = User |> Repo.aggregate(:count, :id)
```

**Comment by BenMorganIO** [comment]
merci @hickscorp
