### ISSUE TITLE
:serial is not in the docs

### ISSUE THREAD

**Issue by chrism2671** [elixir-ecto/ecto#3243]
I'm trying to set up a migration to create an autogenerated primary key with a field name of `:account_id` instead of `:id`, using Postgres.

In the end, I had to set it up as follows:

 ```
 def change do
    create table(:accounts, primary_key: false) do
      add :account_id, :serial, primary_key: true
      add :email, :string
      timestamps()
    end
  end
```

The issue is that `:serial` isn't mentioned anywhere in the documentation (I checked Ecto.Schema, Ecto.Migration, 

I'm not sure if this is by design (if so, please close), but thought I should raise it just in case.

**Comment by chrism2671** [comment]
I've just found `:bigserial`. I guess this isn't obvious but it's probably OK to close this issue.

**Comment by josevalim** [comment]
That's because any type that is not an Ecto Type is passed to the database as is. So anything that your database supports is allowed there. This should be mentioned in the docs. :) Thanks!
