### ISSUE TITLE
ecto.migrate is not actually creating the tables in the postgresql db

### ISSUE THREAD

**Issue by blackfulcan** [elixir-ecto/ecto#3248]
my repo migration file contains

```
defmodule Discuss.Repo.Migrations.AddTopics do
  use Ecto.Migration

  def change do
    create table(:topics) do
      add :title, :string
    end
  end
end
```

### Environment

* Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Phoenix v1.3.4
* postgresql 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
* ecto 2.2.12 (Hex package)
* db_connection 1.1.3 (Hex package)
* Operating system: ubuntu0.18.04.1

### Current behavior

when I run `mix ecto.migrate` the output says that the table is created, "create table topics", but when I look in the DB nothing has been created. I have rolled back and migrated again, I have reset the db as well. Not sure what else to try. The database does not contain schema_migrations either.

```
# mix ecto.reset
warning: found quoted keyword "test" but the quotes are not required. Note that keywords are always atoms, even when quoted. Similar to atoms, keywords made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  mix.exs:58

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.11.2) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.11.2) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.11.2) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.11.2) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.11.2) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.11.2) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.11.2) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.2) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.2) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.11.2) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.11.2) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.11.2) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.11.2) supervisor.erl:1157: :supervisor.children_map/4
  (stdlib 3.11.2) supervisor.erl:315: :supervisor.init_children/2
  (stdlib 3.11.2) gen_server.erl:374: :gen_server.init_it/2
  (stdlib 3.11.2) gen_server.erl:342: :gen_server.init_it/6
  (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

The database for Discuss.Repo has already been dropped
The database for Discuss.Repo has been created
[info] == Running Discuss.Repo.Migrations.AddTopics.change/0 forward
[info] create table topics
[info] == Migrated in 0.0s
```
when I check the contents of the database after the reset I get:

```
db_name=# \dt
Did not find any relations.
db_name=#
```

I am able to add the tables manually and remotely with Postico on my mac machine without issue. The database credentials being used in Postico are the same as the ones being added into the dev.exs file. If I add the tables manually, then run `mix ecto.drop` the table does not delete.

**Comment by josevalim** [comment]
@blackfulcan have you checked if the table exists when you try to look it up *inside Elixir*? It could be that something else is not matching with Postico. Otherwise, please provide a sample application that reproduces the error. Thanks.

**Comment by josevalim** [comment]
Please let us know if you have more information on the above and how we can reproduce  the issue and we will gladly reopen it. Thanks!

**Comment by ekarak** [comment]
this happened to me just now, the root cause was that the migration scripts had a *whitespace* as the first char in the filenames (unsure how this happened). Once the whitespace was removed, the migration scripts were executed just fine.
