### ISSUE TITLE
select with map acts as alias in sub-query but not in top query

### ISSUE THREAD

**Issue by jmnsf** [elixir-ecto/ecto#3249]
### Environment

* Elixir version: Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Database and version: PostgreSQL 11.2
* Ecto version (mix deps): 3.2.5
* Database adapter and version (mix deps): postgrex 0.15.3
* Operating system: Windows 10

### Current behavior

When using `select: %{}` in a subquery, map keys are used as aliases, but the same doesn't happen in top-level queries. An example.

The following query:

```elixir
from(
  m in Message, 
  select: %{
    user_id: m.from_id,
    week_start: fragment("date_trunc('week', ?)", m.timestamp)
  },
  group_by: [fragment("date_trunc('week', ?)", m.timestamp), m.from_id]
)
|> Repo.all()
```

Generates this SQL:

```sql
SELECT m0."from_id", date_trunc('week', m0."timestamp") 
FROM "messages" AS m0 
GROUP BY date_trunc('week', m0."timestamp"), m0."from_id"
```

No aliases anywhere. Lets use it as a sub-query though:

```elixir
sub =
  from(
    m in Message, 
    select: %{
      user_id: m.from_id,
      week_start: fragment("date_trunc('week', ?)", m.timestamp)
    },
    group_by: [fragment("date_trunc('week', ?)", m.timestamp), m.from_id]
  )

from(
  u in User,
  left_join: mc in subquery(sub), on: mc.user_id == u.id,
  select: %{
    week_start: mc.week_start,
    id: u.id
  },
  group_by: [fragment("week_start"), u.id]
)
|> Repo.all()
```

Yields this SQL:

```sql
SELECT s1."week_start", u0."id" 
FROM "users" AS u0 LEFT OUTER JOIN (
  SELECT m0."from_id" AS "user_id", 
  date_trunc('week', m0."timestamp") AS "week_start" 
  FROM "messages" AS m0 
  GROUP BY date_trunc('week', m0."timestamp"), m0."from_id"
) AS s1 ON s1."user_id" = u0."id" 
GROUP BY week_start, u0."id"
```

The sub-query now has aliases defined from the map keys. This is actually pretty nice because we can now use said aliases in fragments in the `group_by` part of the query; however, it's inconsistent and misleading.

### Expected behavior

Either no aliases should be generated at all (boo) or all aliases should be generated (yay). The latter is obviously more useful, but to be really great we should be able to:

```elixir
from(
  m in Message, 
  select: %{
    user_id: m.from_id,
    week_start: fragment("date_trunc('week', ?)", m.timestamp)
  },
  group_by: [:week_start, :user_id]
)
```

Without worrying about aliases at all.

**Comment by josevalim** [comment]
The issue with aliases is that we don't know how to refer to aliased values. For example, the syntax you propose is ambiguous. atoms in `group_by` refer to the source. So what if we had this:

```
from(
  p in Post, 
  c in Comment,
  select: %{body: c.body},
  group_by: [:body]
)
```

It is unclear about what it means, so the issue is a bit more complex than one would think. So there are other complexities in here which is why we don't plan to tackle this, unless someone submits a solid proposal plus a PR. Note aliases in subqueries are also meant to be an implementation detail and you can't rely on them.

**Comment by jmnsf** [comment]
> Note aliases in subqueries are also meant to be an implementation detail and you can't rely on them.

@josevalim There are two issues with this: the first is that it is deducible when you find them _not_ being set in top-queries (what happened here) but not if you don't. In other words, it's easy to assume this is expected behavior if one only uses them in a sub-query. You'll then be none the wiser and likely to be bit in the butt at some point in the future when you try to use it in a top-query.

The second is that this implementation detail actually needs to be relied upon if you're using aliases. An example:

```elixir
from(
  m in Message, 
  select: %{
    user_id: m.from_id,
    week_start: fragment("date_trunc('week', ?) as week_start", m.timestamp)
  },
  group_by: [fragment("week_start"), m.from_id]
)
|> Repo.all()
```

This works great as a top level query, generates the following SQL:

```sql
SELECT m0."from_id", date_trunc('week', m0."timestamp") as week_start 
FROM "messages" AS m0 
GROUP BY week_start, m0."from_id"
```

Put it in a subquery though:

```elixir
from(
  u in User,
  right_join: mc in subquery(sub), on: mc.user_id == u.id,
  select: %{
    week_start: mc.week_start,
    id: mc.user_id
  }
)
|> Repo.all()
```

And out comes:

```sql
SELECT s1."week_start", s1."user_id" 
FROM "users" AS u0 
RIGHT OUTER JOIN (
  SELECT m0."from_id" AS "user_id", date_trunc('week', m0."timestamp") as something AS "week_start" 
  FROM "messages" AS m0 
  GROUP BY something, m0."from_id"
) AS s1 ON s1."user_id" = u0."id"
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "AS"
```

Speaking of bit in the butt :)

<hr>

PS: Definitely understand the challenges of coming up with a nice API, and the ambiguity with what I proposed. Nonetheless I believe APIs should be friendly and unsurprising and was only proposing what I would expect to "just work".

**Comment by josevalim** [comment]
Yes, fragments are escape hatches and they may break in certain occasions. To me the most important is to maintain the correctness in Ecto's own APIs.

Again, I am not opposed to the idea, but someone needs to do the proposal, considering all pros and cons, and provide a reference implementation. :)
