### ISSUE TITLE
Improve reflection in builtin validations

### ISSUE THREAD

**Issue by seivan** [elixir-ecto/ecto#3252]
### Environment
* Ecto version (mix deps): `3.3.4`

### Current behavior
`Changeset.validations/1` doesn't return all expected validations

### Expected behavior
`Changeset.validations/2` should return validations that are: 

- `validate_acceptance`
- ~~`validate_confirmation`~~
- `validate_required`

It seems like they aren't using `Changeset.validate_change/4` for their implementation.
However, it is documented for `validation_required` that its actual "reflection" mechanism is stored under `changeset.required` 

I am aware that `validate_acceptance` & `validate_confirmation` just looks at the cast/param and not actual fields, and also that `validate_required` will be ok with no params, as long as the existing field is non-empty. 
Essentially that's an implementation detail of the actual validation running and not their metadata

Though I am not 100% certain how `Changeset.validate_change/4` works, I am wondering if I there is room for improvement here. 

* Normalize builtin validations to use `validate_change/4`
* Keep reflection mechanism for validations in a central key. 

There might be a need to tweak to how `Changeset.validate_change/4` works internally but I think it's for the better if it would let us get actual validation requirements from a changeset to further improve codegen based on metadata. 

Use case now is sending that metadata to clients to build their forms with client side validations and to make sure to keep the source of truth for magic numbers and requirements in one place. 

I don't mind doing the change but was hoping to get some feedback and wonder if there is anything wrong with this idea? 

Also wondering if I was mistaken about needing tweaks to `Changeset.validate_change/4` and I could use that to wrap these instead of reimplementing them. 

- `validate_acceptance`
- `validate_confirmation`
- ~~`validate_required`~~

Edit: Turns out `validate_confirmation` actually does add the metadata, my bad. 
```elixir
changeset | validations: [{field, {:confirmation, opts}} | changeset.validations]
```

**Comment by josevalim** [comment]
I don't think we should make validate_change more complex than it is. If acceptance and confirmation is not attaching the proper validations metadata, then we can improve them and a PR is welcome. `validate_required` should remain as is for legacy reasons.

**Comment by seivan** [comment]
@josevalim 
While I am technically requesting for a refactor its internals (to keep tests green) so it becomes less complex, I am just as **happy** to do a PR that makes sure the proper validation metadata is applied inline in those other functions, if that's what you want.  Either way I'm game. 

Regarding `validate_required`, I am not asking to remove the `changeset.required` field, but also to make sure its metadata is part of `Changeset.validations/1` like the rest. 

or did you mean there are legacy reasons why `Changeset.validations/1` does not contain `validate_required`? 
The hypothetical user of the metadata will either create a new object, in which case it will require a value, or edit an existing one, in which case it would already have a value.

**Comment by josevalim** [comment]
> I am just as happy to do a PR that makes sure the proper validation metadata is applied inline in those other functions

Yes, this is the best way to go. Maybe they could share a common path internally, but I wouldn't try to associate it with the existing validate_change.

Btw, I just took a quick look at validate_confirmation, and it seems to attach the proper metadata. Acceptance does not, however.

> Regarding validate_required, I am not asking to remove the changeset.required field, but also to make sure its metadata is part of Changeset.validations/1 like the rest.

I understand. We tried this in the past though and it caused bugs because some system would somehow account for them twice. Ecto is one of the oldest Elixir projects, so even small changes may cause breakage.

**Comment by seivan** [comment]
@josevalim You're right, I missed it.
```elixir
changeset | validations: [{field, {:confirmation, opts}} | changeset.validations]
```

Regarding `validate_required`, would it be dangerous to to add its validation [here](https://github.com/elixir-ecto/ecto/blob/e5908c0ed7b988c8c230502d31e278a85f3d2a68/lib/ecto/changeset.ex#L1753-L1759) 

What kind if issues did you guys experience? 

I am guessing it would be on the templates, so looking at https://github.com/phoenixframework/phoenix_html/search?q=input_validations&unscoped_q=input_validations I can't seem to find any implementations. 


Either way glad to add `validate_acceptance` metadata, and see if I can tweak in required on my end instead.

**Comment by josevalim** [comment]
> Either way glad to add validate_acceptance metadata, and see if I can tweak in required on my end instead.

Please do! It should be a one liner like above. :)

**Comment by seivan** [comment]
@josevalim I'm writing a test case to make sure out of a set of validations, I get them all out when asked for. 

Just to clarify, that's a no on adding validate_required under `validations/1`?

**Comment by josevalim** [comment]
> Just to clarify, that's a no on adding validate_required under validations/1?

Correct. I will try to dig the problems we had in the past, but that may not be easy.

**Comment by josevalim** [comment]
Hi @seivan! I went ahead and submitted a PR since we are release v3.4 and I wanted to make sure this was in. Thanks!

**Comment by seivan** [comment]
@josevalim Thank you! Appreciate it!
