### ISSUE TITLE
Upgraded to Ecto 3.4 and getting problem with dialyzer and Ecto.Migrator.run

### ISSUE THREAD

**Issue by zacksiri** [elixir-ecto/ecto#3261]
### Environment

* Elixir version (elixir -v): 1.9.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.2
* Ecto version (mix deps): 3.2 - 3.4
* Database adapter and version (mix deps): postgrex
* Operating system: MacOS catalina

### Current behavior

Dialyzer is giving me the following error after I upgraded to ecto 3.4

```elixir
lib/ticket_booth/release/tasks.ex:54:no_return
Function run_migrations_for/1 has no local return.
________________________________________________________________________________
lib/ticket_booth/release/tasks.ex:58:call
The function call will not succeed.

Ecto.Migrator.run(_repo :: atom(), _migrations_path :: binary(), :up, [{:all, true}])

breaks the contract
(Ecto.Repo.t(), [String.t()] | [{integer(), module()}], atom(), Keyword.t()) :: [integer()]

________________________________________________________________________________
```

### Expected behavior

Dialyzer should pass

**Comment by wojtekmach** [comment]
This is because we're soft-deprecating passing a single migration path (a binary) in favour of a list of migrations paths (list of binaries) and we've updated specs accordingly.
