### ISSUE TITLE
Support where in (subquery)  

### ISSUE THREAD

**Issue by thenrio** [elixir-ecto/ecto#3263]
Summary
---

New expression `where([t], t.id in subquery(s))`, that yield sql like `where id in (s)`. 

> syntax MAY change.

Motivation
---
Main driver is `where x in (subquery)` MAY perform better than `join (select distinct x from subquery) s`, on postgres at least.
With this change, we can choose to build an expression that performs better on database.

Detailed design
---
Build a new expression in `Ecto.Queries.wheres`.
Make a PR and have feedback?

See [discussion](https://groups.google.com/forum/#!topic/elixir-ecto/ZRinU3ElLmg) for details and figures.

Drawbacks
---
Need to change ecto_sql also, to act on new expression and output desired sql.
See https://github.com/elixir-ecto/ecto_sql/issues/218.

**Comment by azizk** [comment]
I would love to see this accepted. Is there a good reason why the subquery function is necessary? I would prefer `where([t], t.id in ^query)`.

Besides being a cool feature, in my case it would tremendously ease a pain point I have with filtering and paginating/sorting queries which I haven't solved properly yet. If I use 1:n-joins, I get duplicate rows. Using :distinct prevents sorting and forces ordering by id. Using :group_by becomes awkward fast and I have to give up. Last option I see may be a CTE which selects the filtered rows first and then I continue with that result set... Anyway, this feature would elegantly solve my issues I think.

**Comment by thenrio** [comment]
I chose `subquery(s)` because:

* subquery is a term in postgres and mysql documentation in this context. It's "where x in (subquery)" rather than "where x in (query)". (see syntaxes on https://github.com/elixir-ecto/ecto_sql/issues/218).
* `in subquery(s)` is already a valid ecto expression for join (see https://github.com/elixir-ecto/ecto/blob/5e5662babc05853c1fdaf8a61f6590e4891b8974/lib/ecto/query.ex#L887).
* change in builder was minimal? (YMMV)

**Comment by azizk** [comment]
Okay, I see what you mean. But I'm not sure if it should automatically apply to "ecto's language". In the docs for `join()` you'll see an example where a query is interpolated directly in the join clause without the `subquery()` function.
```elixir
posts =
  if params["drafts"] do
    from p in Post, where: [drafts: true]
  else
    from p in Post, where: [public: true]
  end

from c in Comment,
  join: p in ^posts, on: [id: c.post_id],
  select: {p.title, c.text}
```
It seems inconsistent when looking at this. Can't comment on the implementation. Didn't dive too deep into the code yet.

**Comment by josevalim** [comment]
@azizk your example though does not use a subquery, it simply merges `where` into the `joins`' `on`. So if you want a subquery in your example, you need the `subquery` call, and a subquery is a requirement in this case, so I think the most consistent approach is to indeed require you to wrap it in a `subquery` call.

**Comment by azizk** [comment]
@josevalim Thanks for clarifying. I understand now. :+1:

**Comment by josevalim** [comment]
Closing in favor of PR!
