### ISSUE TITLE
Repo.preload/2 does not support assocs inside embeds

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#3265]
Imagine the following simplified schema:
```
schema "messages" do
    embeds_many :ui_attachments, UIAttachment do
        has_one :media_attachment, Attachment
    end
  end
```

When the message is inserted it's returned with `:media_attachment` assoc not loaded, but it's not possible to preload it:
```
message = Repo.preload(message, ui_attachments: [:media_attachment])
** (ArgumentError) schema TalkInto.Domain.Messaging.Message does not have association :ui_attachments
```

I guess Ecto should not raise when part of preload path is embed and keep looking only in the case when there are no assocs inside.

**Comment by josevalim** [comment]
Hi @AndrewDryga! 👋 

There is a lot of work in supporting this, so we don't plan to tackle this ourselves. For our purposes, the error message is correct. Preload is about associations an ui_attachments are not associations.  But if someone wants to submit a pull request, we will gladly accept it!

Thanks!

**Comment by AndrewDryga** [comment]
@josevalim would it be right to say that assocs within embeds are not supported at all? I've noticed that they are not inserted even though casted. I think we should then warn or raise when `has_many` or `has_one` is used within `embeds_one` or `embeds_many`.

**Comment by josevalim** [comment]
I think raising would be a good call, maybe someone is accidentally relying on them after all. :)
