### ISSUE TITLE
Submit a telemetry event upon Repo start

### ISSUE THREAD

**Issue by binaryseed** [elixir-ecto/ecto#3266]
One of the challenges for an auto-instrumentation library like New Relic is providing a zero-configuration APM experience.

To do that, the agent currently has to do some gymnastics to discover Repos as they start, then detect their configuration & `telemetry` event name. Right now this is done via erlang tracers & reading Application config.

This could be achieved in a much friendlier way if Ecto itself submitted a `telemetry` event whenever a Repo is started that contained all the configuration, including the `telemetry` event prefix that it will use. An event handler could then trigger the subscription to further events. The only thing we'd need is to make sure the event name for the "start" events is known up front!

Something roughly like this:

```elixir
:telemetry.execute(
  [:ecto, :repo, :start],
  %{system_time: System.system_time()},
  %{
    repo: MyRepo,
    config: %{
      telemetry_prefix: [:my_repo, :query],
      hostname: hostname,
      # ...
    }
  }
)
```

Is this something we might be able to add?

**Comment by josevalim** [comment]
@binaryseed I like this approach a lot. Yes, please do send a PR!

**Comment by binaryseed** [comment]
PR sent!

**Comment by josevalim** [comment]
Closing in favor of PR!
