### ISSUE TITLE
Support lateral join subqueries

### ISSUE THREAD

**Issue by jjl** [elixir-ecto/ecto#3272]
Currently, ecto supports lateral joins for fragments, but not for subqueries.

To steal an example from [the original lateral join thread](https://github.com/elixir-ecto/ecto/issues/1425):

```elixir
post = Repo.one(
  from p in Post,
  where: p.id == 123,
  lateral_join: cs in subquery(
    from c in Comment,
    order_by: [desc: c.inserted_at],
    where: c.post_id == p.id,
    limit: 5
  ),
  preload: [comments: cs]
)
```

The primary difficulty seems to come from the nested invocation of `from` (or to look at it another way, informing the subquery of some parent bindings.

I would be willing to put some work towards this, but I'd need guidance as I'm not very familiar with the ecto codebase. And we'd also have to decide what the solution would be.

**Comment by josevalim** [comment]
Unfortunately I don't think there is an easy solution to this problem. Even though we have subqueries there is no way to pass bindings from the parent query to the child query and this would take a lot of effort to implement. It is something we would accept if someone puts the effort, but it is not something the Ecto team can help with, as we are time constrained.

**Comment by jjl** [comment]
The new `as` and `parent_as` facilities in ecto master seem to be working out pretty well, so I'm inclined to consider this fixed.

Thanks Jose!
