### ISSUE TITLE
Pass multiple fields to unique_constraint/3

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#3275]
Let's say we have this index:

```elixir
create unique_index(:memberships, [:org_id, :member_id])
```

To handle the unique constraint we need to do:

```elixir
|> unique_constraint(:org_id, name: :memberships_org_id_member_id_index)
```

However, we can also do:

```elixir
|> unsafe_validate_unique([:org_id, :member_id], Repo)
```

and the validation error would be put on the first field, `:org_id`.

Should we allow:

```elixir
|> unique_constraint([:org_id, :member_id])
```

and thus automatically infer the index name?

**Comment by josevalim** [comment]
That would be great, :+1:.

**Comment by wojtekmach** [comment]
Closing in favour of PR.
