### ISSUE TITLE
Ecto preload breaks when preloading after update that sets association key to nil

### ISSUE THREAD

**Issue by michaelst** [elixir-ecto/ecto#3283]
This broke when we updated from 3.3.3 -> 3.4.2, I'm not seeing anything in the changelog about this so I'm not sure if there is a best practice we are missing here.

### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11
* Ecto version (mix deps): 3.4.2
* Database adapter and version (mix deps): Postgrex 0.15.3
* Operating system: MacOS

### Current behavior
Pass in params with `%{project_id: nil}`

```
time_entry
    |> Repo.preload([:contact, :project, :user, :line_item])
    |> TimeEntry.changeset(params)
    |> Repo.update()
    |> case do
      {:ok, time_entry} ->
        time_entry =
          time_entry
          |> Repo.preload([:contact, :project, :user, :line_item], force: true)
```

When we do the force preload at the end we get this error
```
(RuntimeError) association `project` for `ZB.TimeEntry` has a loaded value but its association key `project_id` is nil. This usually means `project_id` was not selected in a query
```

### Expected behavior
The preload should set project equal to nil.

**Comment by josevalim** [comment]
Thanks for reporting. Fixed in master!
