### ISSUE TITLE
`select` should accept single atom 

### ISSUE THREAD

**Issue by jjl** [elixir-ecto/ecto#3297]
Example use:

```elixir
from q in Qwerty, select: :id
```

16:36 < josevalim> both `u.id` or `[:id]` will work
16:36 < josevalim> so the question is if we should support `select: :id` or raise
16:37 < josevalim> given we allow `order_by: :title`, i don't see a reason to now allow `select: :id`
16:37 < josevalim> *not allow

**Comment by qcam** [comment]
After the discussion in this thread: https://github.com/elixir-ecto/ecto/pull/3301#discussion_r426138168, we think that it's better to raise on selecting single atom.
