### ISSUE TITLE
Ecto interpolating select_merge keys into query

### ISSUE THREAD

**Issue by apcomplete** [elixir-ecto/ecto#3298]
### Environment

* Elixir version (elixir -v): 1.10.2 
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):  PostgreSQL 12.2
* Ecto version (mix deps):  3.3.4
* Database adapter and version (mix deps): postgrex 0.15.3
* Operating system: Ubuntu 20.04

### Current behavior
The issue is outlined in [this elixirforum post](https://elixirforum.com/t/ecto-interpolating-select-merge-keys-into-query/28281) in a bit more detail, but the gist is that when I try to inject a dynamic key into a `select_merge` call for a subquery, the quoted expression is escaped incorrectly, and throws an error.

Example, when composing a subquery using a dynamic key for the select:
```elixir
x = "play_id"
q = from p in Galaxy.Dimension.Play, select: %{}, select_merge: %{^x => p.id}, limit: 10
Galaxy.Repo.all(from x in subquery(q))

** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (Ecto.QueryError) only atom keys are allowed when selecting a map in subquery, got: `%{^0 => &0.id()}` in query:

    from p0 in Galaxy.Dimension.Play,
      limit: 10,
      select: %{^"play_id" => p0.id}

The subquery originated from the following query:

from p0 in subquery(from p0 in Galaxy.Dimension.Play,
  limit: 10,
  select: %{^"play_id" => p0.id}),
  select: p0

    (ecto) lib/ecto/repo/queryable.ex:161: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

### Expected behavior

Expected behavior is basically just that the key gets escaped correctly, and I can use variables to compose subquery select statements.  I managed to write workaround using `Macro.prewalk` where I just inject the atom directly into the quoted expression held at `query.select.expr`.  I have a basic understanding of what's going on here, but not enough to pinpoint exactly where a change would fix this in ecto.

```elixir
key = "play_id"

expr =
  Macro.prewalk(query.select.expr, fn
    {{:^, [], [0]}, {{:., [], [table_ref, ^col]}, [], []}} ->
      {key, {{:., [], [table_ref, col]}, [], []}}
    expr -> expr
  end)

select =
  query.select
  |> Map.put(:expr, expr)
  |> Map.put(:params, Keyword.drop(query.select.params, [key])) 

Map.put(query, :select, select)
```

Appreciate all the work you all put into this project!  Ecto has enabled us to do some pretty incredible things wrt composing queries dynamically.

**Comment by josevalim** [comment]
This is intentional. :) We need to know the names of fields in subqueries so we can select and perform type checking in the parent. An interpolated name does not allow us to do so. I recommend for you to return a map such as `%{field: ^x, value: p.id}`. I do not recommend mangling the query by hand, it is private API and you can even expose yourself to issues such as SQL injection. In any case, thanks for the report!

**Comment by apcomplete** [comment]
Thanks for the response!  For my own understanding, can you expand a bit on the type checking portion?  In the live use case the interpolated key is an existing atom, and as part of mangling the query we're removing it from the params keyword list.  How does the type checking piece fit in there?  It might add some clarity to this if I provide the live code we're using to dynamically allow group-bys for our system.  `column` in this case is a compile-time generated module/struct that references a single field in a schema to construct a dynamic query off of.  So `model_key` in this case is a reference to the atom used for the named join on the query.  Hopefully this makes sense:

```elixir
defimpl Ultimate.Domain.Groupable, for: Any do
  import Ecto.Query

  def group(nil, key, _query) do
    raise "Groupable not available for: #{key}"
  end

  def group(column, key, query) do
    %{model_key: model_key} = column # get the name for the column's join
    join = Ultimate.Domain.Joinable.join(column, key, true, query)  # joins in the schema needed
    col = Ultimate.Domain.Column.field(column) # get the specific field on the referenced schema 

    from(join)
    |> group_by([{^model_key, x}], field(x, ^col))
    |> select_merge([{^model_key, x}], %{^key => field(x, ^col)})
    |> inject_key(key, col)
  end

  def group_context(nil, key, _query) do
    raise "Groupable not available for: #{key}"
  end

  def group_context(_column, key, query) do
    query
    |> from()
    |> select_merge([totals], %{^key => field(totals, ^key)})
    |> inject_key(key, key)
  end

  defp inject_key(qry, key, col) do
    expr =
      Macro.prewalk(qry.select.expr, fn
        {{:^, [], [0]}, {{:., [], [table_ref, ^col]}, [], []}} ->
          {key, {{:., [], [table_ref, col]}, [], []}}
        expr -> expr
      end)

    select =
      qry.select
      |> Map.put(:expr, expr)
      |> Map.put(:params, Keyword.drop(qry.select.params, [key]))

    Map.put(qry, :select, select)
  end
end
```

I understand that this is a little risky with respect to it being a private API and would be at risk for sql injection if this ended up as a user input.  I'm just curious where the type checking portion comes into place such that an (existing) atom held in a variable could not be a valid key for the `select_merge`.  Thanks again for taking the time to look at this :)

**Comment by josevalim** [comment]
You can do things like this:

    from s in subquery(query), where: s.field == ^param

And we need to know the field information to check/cast the param. This requires knowing the fields names, which is hard with the interpolation.
