### ISSUE TITLE
`validate_confirmation` default message could be better

### ISSUE THREAD

**Issue by happycollision** [elixir-ecto/ecto#3304]
### Precheck

This lives somewhere between bug and feature request. I'll be happy to close and repost in a forum if that is the desired place. My apologies in advance if this is not the right place.

### Environment

n/a

### Summary

The default of "does not match confirmation" should either be "does not match" or "does not match #{field}"

### Details

original change:
https://github.com/elixir-ecto/ecto/commit/209890de21b42733d4eafce48291f07325f24a2b#diff-9495d20c8803917c695d397ba72de489R974

This original change seemed to tie the confirmation field's error directly to the parent field, such that the parent field would get an error saying that it did not match its confirmation. You can see in the test file that this was fairly clear:

https://github.com/elixir-ecto/ecto/blob/209890de21b42733d4eafce48291f07325f24a2b/test/ecto/changeset_test.exs#L754

"Title does not match confirmation"

This made sense at the time, but the default error message has not been updated in the years since when the error message was no longer tied to the parent field. Here is what we see today:

https://github.com/elixir-ecto/ecto/blob/722d1c932e61cea3d8d86fe3b1dec53c12608c77/test/ecto/changeset_test.exs#L1261

"Title confirmation does not match confirmation"

This has had at least one ripple effect in another package: The whole reason I dug into this was because [POW uses the same default message in the same scenario](https://github.com/danschultzer/pow/pull/380). (Unfortunately there, it is not as easy to override, and I'd argue they had a better message before they understandably decided to match Ecto.)

I see three paths forward:

1. Do nothing. Defaults can be overridden.
2. Remove the word "confirmation" from "does not match confirmation"
3. Interpolate the parent field so the message would read "does not match ${field}"

This is obviously something that is not essential since the message can be overridden, but I contend that if this change is made, far fewer developers will a) change the message at all or b) live with a default they don't like (whatever their reasons). If there is ever a possibility that a default can serve most people's needs, that is what the default should be. 

Changing it would also be helpful in situations like mine where I am depending on a package that mimics the default messaging from Ecto, but changing that message is not as straightforward.

I'd be happy to give this a go and create a PR, but would defer to the maintainers of this package on which option they prefer.

Cheers, and thanks for this fantastic software ecosystem. I am _very_ new to Elixir and I am loving the possibilities that it brings to the table.

**Comment by josevalim** [comment]
Yes, I have noticed this recently when working on an app and unfortunately I am not sure there is a straight-forward answer because of backwards compatibility.

I would like to avoid having dynamic fields, because it makes it harder to apply i18n. So our option is to leave it as is and remove "confirmation". Is removing "does not match" clear enough though? Although the current message is vague, if we are going to fix it, we should make sure we get the wording right.

**Comment by happycollision** [comment]
Other options:

- "confirmation does not match": This is arguably clearer since "confirmation" would be the subject rather than the object, but might be the only error message that refers to itself (?)
- "does not match original": Closer syntax to what we'd get with interpolation

----------

A point of clarification: Are you avoiding interpolation because of some kind of variability within a single confirmation or because you'd prefer that _every_ confirmation validation return the exact same message?

I have never done the work to internationalize an application, so I am not sure if it would be beneficial for these validations to actually produce different strings or not. In relative ignorance, I'd imagine being able to target "does not match password" and "does not match title" independently would be helpful.

**Comment by happycollision** [comment]
(Personally, I do think that "does not match" all by itself is clear enough, considering some of the other defaults that haven't been problematic at this point. But that is purely a gut feeling.)

**Comment by josevalim** [comment]
In a new Phoenix app, we generate a file with all default error messages so they can be translated. Making it dynamic would make this operation extremely hard - so it is best if custom messages are opted-in.

"confirmation does not match" is clearer but it is inconsistent as we don't have the subject in any other message. Perhaps the best option for now is to keep this open so we can further collect feedback.

**Comment by michalmuskala** [comment]
I would be very careful about changing the messages. For applications that do use Gettext for i18n it would break translations in a way that might be hard to notice. 

It's definitely possible to change the messages, but IMO the bar for doing that should be relatively high.

**Comment by happycollision** [comment]
Perhaps this should be targeted at a major release?

Another option that I could not undertake on my own would be something in config that allows you to opt in to the new messages until the next major release, at which point we'd remove the old ones. Deprecation notice plus a way to opt in would allow developers to have time testing the new functionality before it is mandatory.

That's a fair amount of work for an overridable field, though, if such a system is not already in place.

**Comment by josevalim** [comment]
> Perhaps this should be targeted at a major release?

That's the issue. We don't plan to release a new major version. :S

**Comment by happycollision** [comment]
Interesting. That seems like a bigger discussion, indeed. Perhaps I'll look for that topic in the forums.

Assuming there will never be a 4.x branch, I guess the best way to move forward is to close this issue, or add an opt in for newer defaults somehow with no intent of removing the opt-in logic?

Adding "feature flags" is certainly one way to keep software moving forward without a new major release.

**Comment by josevalim** [comment]
The issue is that feature flags are global and we want to avoid global configuration due to the coupling. In this case is exactly what you want but I would like to avoid to precedent. :(

**Comment by josevalim** [comment]
Hi @happycollision! Thank you for the report. I agree there is a better message somewhere here but unfortunately I cannot see a way to move forward without breaking applications or without introducing opt-in globals that very few people would use. You can pass the message option or use `gettext` to "translate" all occurrences to something better. :) Have a good weekend!
