### ISSUE TITLE
Add config :ecto, :filter_changes, [:password]

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#3307]
Those changes will be filtered whenever the changeset is inspected or an error that shows fields is raised. The default will be the password field given above.

**Comment by josevalim** [comment]
Another option is to do it per schema. Something like `field :foo, :bar, redacted: true`. This means we could automatically derive the inspect protocol if one was not derived yet - but I am worried about the coupling (what if you don't want to derive it?).

**Comment by TMSCH** [comment]
I prefer the proposal of defining it within the schema.

And to note: we can implement the `Inspect` protocol on the `Ecto.Schema` and only filter the keys we want to be visible, and when using library such as [`Jason`](https://github.com/michalmuskala/jason) there is a similar mechanism. However the issue we're facing is that an `Ecto.Changeset` struct, when logged, will display the full content of the `:changes` key which may contain the sensitive data. For this reason, we need to implement the redaction in `Ecto`

**Comment by TMSCH** [comment]
Another instance where the default Ecto behavior can leak sensitive data, are with some exceptions such as:

```
%Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:
from c0 in Data.Model,
  where: c0.sensitive_field == ^\"SENSITIVE_DATA\"
"
```

We need to be able to redact all by default.
