### ISSUE TITLE
Use the name of unique index in conflict_target to match custom sql query

### ISSUE THREAD

**Issue by bartekupartek** [elixir-ecto/ecto#3315]
### Environment
* Database and version: PostgreSQL 9.6
* Ecto version (mix deps): 3.4.4

### Current behavior
In migrations I've added following unique index:
```
def up do
  create(
    unique_index(:library, ["lower(name), type"],
      name: :unique_library_name_in_type
    )
  )
end
```
the problem occurs with `on_conflict: {:replace, fields}` or `{:replace_all_except, fields}` combined with unique index. 
Without `conflict_target` specified I'm getting:
```
** (Postgrex.Error) ERROR 42601 (syntax_error) ON CONFLICT DO UPDATE requires inference specification or constraint name
```
I found in documentation that `on_conflict` required `conflict_target`:
> replace only specific columns. This option requires conflict_target
the only way I found to match my unique index in `conflict_target` is to use `unsafe_fragment`, so I've prepared following query:
```
Repo.insert_all(
  MyApp.Library,
  immunizations,
  on_conflict: {:replace_all_except, [:id, :inserted_at]},
  conflict_target: {:unsafe_fragment, "(lower(name), type)"}
)
```
but now I'm getting following error:
```
** (Postgrex.Error) ERROR 21000 (cardinality_violation) ON CONFLICT DO UPDATE command cannot affect row a second time

    hint: Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
            (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql) lib/ecto/adapters/sql.ex:502: Ecto.Adapters.SQL.insert_all/8
            (ecto) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
            (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
            (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
            (elixir) src/elixir.erl:275: :elixir.eval_forms/4
            (elixir) lib/code.ex:240: Code.eval_string/3
```
### Expected behavior
It should upsert the same row using the unique index specified in migrations or use index name as `conflict_target`

**Comment by josevalim** [comment]
You can pass the constraint option as part of the unsafe fragment too but beware there are pitfalls as INDEX != CONSTRAINT. See the discussion in #3258 and the linked discussions.
