### ISSUE TITLE
Add returning option to Repo.update

### ISSUE THREAD

**Issue by c-spencer** [elixir-ecto/ecto#332]
Would be good to be able to specify either the whole row, or selected columns for efficiency, where you're expecting certain columns to be set or modified by the database (through triggers or what-have-you).

Proposal:

``` elixir
# Same return as an update/get pair at present:
Repo.update(post, returning: :row)

# Returns post with selected fields updated with RETURNING
Repo.update(post, returning: [:last_modified])
```

Currently `update/2` returns `:ok | no_return`, so that would change to `Ecto.Model.t | :ok | no_return`, dependent upon the presence of the `returning` option.

Thoughts? Happy to look at implementing, will need to familiarise myself with the code.

**Comment by donileo** [comment]
Not sure if the changes from this issue ended up being added to Repo.update but I am making a call as such below and the returning keyword list is not being applied. 

```
result =
        %Schema.User{id: id_int}
        |> cast(conn.params, valid_keys)
        |> Schema.User.validate_changeset()
        |> Repo.update(returning: [:username, :gender, :photo1_url])
```
I can see in the log output that the Ecto is applying the 'returning' based on the fields in the schema that have `read_after_writes: true`. I would expect that if you specify a returning clause here that it that the setting here would take precedence.

**Comment by josevalim** [comment]
`update` does not support the `:returning` option (it is not documented as such either). I will push this feature to master in a sec.

**Comment by donileo** [comment]
Hi @josevalim Thanks for the quick reply. I agree that it is not documented as having that feature but given the other update functions had it left me wondering why updating through a changeset didn't have it. Thanks!
