### ISSUE TITLE
Can't insert an empty list in a `jsonb` column via `embeds_many`

### ISSUE THREAD

**Issue by dorian-marchal** [elixir-ecto/ecto#3324]
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
   
  Elixir 1.10.3 (compiled with Erlang/OTP 22)
  ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 
  ```
  psql (PostgreSQL) 12.3 (Debian 12.3-1.pgdg100+1)
  ```
* Ecto version (mix deps):
  ```
  * ecto 3.4.4 (Hex package) (mix)
  locked at 3.4.4 (ecto) cc4bd3ad
  * ecto_sql 3.4.4 (Hex package) (mix)
  locked at 3.4.4 (ecto_sql) edb49af7
  * phoenix_ecto 4.1.0 (Hex package) (mix)
  locked at 4.1.0 (phoenix_ecto) c5e666a3
   ```
* Database adapter and version (mix deps): 
  ```
  * postgrex 0.15.5 (Hex package) (mix)
  locked at 0.15.5 (postgrex) ed90c81e
  ```
* Operating system:
  ```
  Linux 29a00083a2bd 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
  ```

### Current behavior

Repro here: https://github.com/dorian-marchal/repro-empty-list-jsonb/blob/master/README.md

Migration:
```elixir
defmodule App.Repo.Migrations.Foo do
  use Ecto.Migration

  def change do
    create table(:foo) do
      add(:bars, :map, null: false)
    end
  end
end
```

Resulting table:
```
app_dev=# \d foo
                            Table "public.foo"
 Column |  Type  | Collation | Nullable |             Default
--------+--------+-----------+----------+---------------------------------
 id     | bigint |           | not null | nextval('foo_id_seq'::regclass)
 bars   | jsonb  |           | not null |
```

Schema:
```elixir
defmodule App.Foo do
  use Ecto.Schema

  schema "foo" do
    embeds_many(:bars, __MODULE__.Bar, on_replace: :delete)
  end
end

defmodule App.Foo.Bar do
  use Ecto.Schema

  embedded_schema do
    field(:bar, :string)
  end
end
```

Result:

```elixir
iex(3)> %App.Foo{bars: []} |> App.Repo.insert()
[debug] QUERY ERROR db=5.5ms queue=1.0ms idle=1938.1ms
INSERT INTO "foo" VALUES (DEFAULT) RETURNING "id" []
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "bars" violates not-null constraint

    table: foo
    column: bars

Failing row contains (1, null).
```

### Expected behavior

I expect the row to be saved in the database (`bars` should be an empty list).

### Additional information

- I tried to change my migration type to `{:array, :map}` but it doesn’t work either.
- I can get around this by allowing null values and setting a default, like that `add(:bars, :map, default: "[]")` but it doesn’t seem right.
- It does work for non-empty lists.

**Comment by josevalim** [comment]
I believe we can fix it by simply ignoring all values that have not been loaded on `Ecto.Repo.Schema.surface_changes`. However, because some apps may be relying on the current broken behaviour, we will probably have to do it on v3.5.

**Comment by josevalim** [comment]
Here is the fix for it:

```elixir
          {%{^field => value}, _, %{^field => {tag, embed_or_assoc}}} when tag in [:assoc, :embed] ->
            if value != nil and not match?(%NotLoaded{}, value) do
              case change(embed_or_assoc, value, empty(embed_or_assoc)) do
                {:ok, change, _} ->
                  {Map.put(changes, field, change), errors}
                {:error, error} ->
                  {changes, [{field, error}]}
                :ignore ->
                  {changes, errors}
              end
            else
              {changes, errors}
            end
```

Although I won't change this part of the code for now until we are done with the current refactoring. :)

**Comment by josevalim** [comment]
Unfortunately the fix is not enough because we default to [] at the schema too, so Ecto doesn't pick up the change and I am afraid we cannot reliably make it so it does. Therefore you either have to use a changeset with force_change (instead of changing the default struct) or set the default at the database level in your migration too.

**Comment by Deepwalker** [comment]
I'm not sure it is ok to use this issue for question, but it has all context.
So, to resolve this I tried to use `force_change` but it does not work for embeds. `put_embed` will not put any changes for `[]`. To resolve this I used `put_in changeset.changes[key], []`.
Does it make sense to add `force_embed` function? I will create PR if you think this is ok.

**Comment by greg-rychlewski** [comment]
Hi @Deepwalker,

Could you please elaborate what you mean by `put_embed will not put any changes for []`? It works when I try it. Maybe you didn't set the `on_replace` option?

If you have `on_replace` set properly and it's still not working could you please give us a minimal reproducible app?

**Comment by DavidRawk-Blake** [comment]
fields with [] get ignored and aren't included in the `changed` map
