### ISSUE TITLE
Documentation for possible query interval values

### ISSUE THREAD

**Issue by palerdot** [elixir-ecto/ecto#3329]
Hi Ecto Team,

There is **no documentation** on possible values that an `interval` might take for an **Ecto Query**. For example, a typical usage for `ago` is documented [here](https://hexdocs.pm/ecto/Ecto.Query.API.html#ago/2) as 
```elixir
ago(count, interval)

# with following usage
# There is no list of what are the possible values of interval
from p in Post, where: p.published_at > ago(3, "month")
```
There is no list of what are the possible values of interval. The documentation is incomplete and inadequate, especially for beginners. Though we can guess something like it might take stuffs like `day/week/month`, there is no way to confirm and there is no information on how far the granularity can be achieved (like for eg, does it take `nanosecond`?)

### Environment

* Ecto version (mix deps): `v3 (latest)`

### Current behavior
Only one possible value is documented like 
```elixir
from p in Post, where: p.published_at > ago(3, "month")
```

### Expected behavior
There should be a place in documentation where all possible values are documented. For eg, maybe something like this
```elixir
# possible values for interval
interval: "second/minute/day/week/month/year"

# or something like type definitions of statically typed languages
type interval {
   "day"
   "week"
   "month"
   ...
}
```

**Comment by josevalim** [comment]
Good catch. Can you please send a PR? I think `Ecto.Query.API` is a good place for such. The supported values are:

    @interval ~w(year month week day hour minute second millisecond microsecond)

**Comment by palerdot** [comment]
@josevalim Thanks for the reply.  I have few queries for raising PR for this documentation.

 - [Is this the right place to add this information?](https://github.com/elixir-ecto/ecto/blob/v3.4.4/lib/ecto/query/api.ex#L14). If this is the place, then should we be adding similar to other information (instead of word sigil)? for eg:
```elixir
* General: `fragment/1`, `field/2`, `type/2`, `as/1`, `parent_as/1`
# should this information be added here?
* interval values: `year`, `month` ... etc?
```
 - I think it would be better if this information should be cross-linked (hyperlinked) whereever `interval` is referred in documentation. I'm not sure how this can be achieved since there is no way to hyperlink text inside doc string (which I guess is displayed in documentation).

Please let me know if this queries makes sense. I'm new to Ecto documentation and would like to get necessary context for raising a PR.

**Comment by josevalim** [comment]
I think we can introduce a new section about intervals and then refer to this section on each function. WDYT?

**Comment by palerdot** [comment]
> I think we can introduce a new section about intervals and then refer to this section on each function.
That will be helpful. Let me try and create a PR with these suggestions. From there, we can see how to take it forward.

**Comment by palerdot** [comment]
@josevalim Here is the [PR](https://github.com/elixir-ecto/ecto/pull/3330) for this issue.

#### Overview of changes:
 - Created new section `Intervals`. Added supported `interval` values in this section.
 - Hyperlinked `Intervals` section for following functions: `date_add/3`, `from_now/2`, `ago/2`
 - Removed existing `interval` values information from `datetime_add/3` and replaced with link for `Intervals` section to maintain uniformity.

I noticed that documentation of function [datetime_add/3](https://hexdocs.pm/ecto/Ecto.Query.API.html#datetime_add/3) already has information for supported `interval` values. But this information is not replicated for other functions. So I **removed** existing information and **replaced with a hyperlink** for `Intervals` section. I think having this information in one place(`Intervals` section) will be easier to maintain and update.

I locally built the docs and verified the `Intervals` sections and the hyperlinks. 

Let me know if this PR looks ok.
