### ISSUE TITLE
`ago(integer, String.t())` not workin' in more complex query...

### ISSUE THREAD

**Issue by erlandsona** [elixir-ecto/ecto#3340]
When I stumbled on the [ago](https://github.com/elixir-ecto/ecto/blob/4333aa0a2aac28a1dd3d9cb32bb29eda8548a197/lib/ecto/query/api.ex#L287) helper I was excited to be able to delete my manual construction of a `%Postgrex.Interval{}` struct and a helper to construct them for months. But when I substituted my usage of the raw values for the `ago(-3, "month")` in my query I got this error...
```
** (Postgrex.Error) ERROR 42804 (datatype_mismatch) COALESCE types interval and timestamp without time zone cannot be matched

    query: SELECT ...
WHERE (a0."ownerid" = $1) AND (age(greatest(a1."initial_active_date__pc", a1."date_reinstated__pc", NULL, NULL, NULL, NULL, NULL)) > coalesce(f7."column2", $2::timestamp + ($3::numeric * interval '1 year'))) AND (coalesce(age(s6."latest") > coalesce(f7."column3", $4::timestamp + ($5::numeric * interval '1 month')), TRUE)) AND (NOT (coalesce((a1."discharge_date__pc" = greatest(a1."discharge_date__pc", a1."initial_active_date__pc", a1."date_reinstated__pc", NULL, NULL, NULL, NULL)) OR (a1."date_of_death__pc" = greatest(a1."date_of_death__pc", a1."initial_active_date__pc", a1."date_reinstated__pc", NULL, NULL, NULL, NULL)), FALSE)))
```
Which I believe points to this snippet in the query `$3::timestamp + (-5::decimal::numeric * interval '1 month');` which if you replace the `$3` with an interval EG: `select interval '0 month'::timestamp + (-5::decimal::numeric * interval '1 month');` you get the same error message from Postgres.

From the docs for the function apparently that `$3` is supposed to be a `DateTime.utc_now` but I can't find the implementation for the `ago` function.

**Comment by josevalim** [comment]
Can you please fully describe how you are invoking this helper from Ecto? I will provide some references soon.

**Comment by erlandsona** [comment]
Ah yup... sorry forgot to add that to this... here we go :)
```elixir
      # NOTE: This left_join on review_cadence may be irrelevant
      # unless a particular HP wants patients reviewed
      # sooner than "after 1 year on service".
      left_join:
        review_cadence in fragment(
          # Healthplan, Initial review cadence, Follow up review cadence
          """
          (values
            ('Aetna', interval '1 year', interval '3 months'),
            ('Anthem', interval '1 year', interval '1 month')
          )
          """
        ),
      on: review_cadence.column1 == health_plan.label,
      as: :rc,
      where:
        age(
          greatest(
            discharge_info.initial_active_date,
            discharge_info.reinstatement_date
          )
        ) > coalesce(review_cadence.column2, ago(1, "year")),
      where: ^not_reviewed_since_last_cadence(),
...

defp not_reviewed_since_last_cadence do
    dynamic(
      [r: review, rc: cadence],
      coalesce(age(review.latest) > coalesce(cadence.column3, ago(3, "month")), true)
    )
end
```
There's more to the query but it compiles down to the sql I mentioned earlier and the issue is replicable via the raw sql snippet.

**Comment by josevalim** [comment]
If cadence.column3 is an interval it indeed won't work, as ago() will always return a timestamp and not an interval. :)

**Comment by erlandsona** [comment]
Ah!!! Thanks! makes sense!
