### ISSUE TITLE
Invalid doc or implementation for  "Preload functions" - case with has_many :through

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3342]
https://github.com/elixir-ecto/ecto/blob/761d8a3ac2a3e2d309d69b10046252d1a9cd9ea3/lib/ecto/query.ex#L1925-L1934
In terms of the schemas in docs, running this
```
Repo.all(from p in Post, preload: [comments_authors: ^&IO.inspect/1])
```
raises an exception, of course, but also prints ids of the... authors. Am I missing something?

**Comment by josevalim** [comment]
What is the exception that you get?

**Comment by josevalim** [comment]
What, the function that you give must execute a query. So if you are only inspecting and not return the query results, then it won’t work.

**Comment by fuelen** [comment]
yes, but documentation says that `function will receive the IDs of the comments and not of the 
       posts`. But I got ids of the users.

**Comment by josevalim** [comment]
Can you please fill in the issues template then and provide an app or a test that reproduces The error? Thanks!
