### ISSUE TITLE
"Preload functions" - case with has_many :through

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3343]
### Environment

* Elixir version: 1.9.1
* Database and version: PostgreSQL 11.4
* Ecto version: 3.4.5
* Database adapter and version (mix deps): postgrex 0.15.5
* Operating system: Linux

### Current behavior
This issue continues https://github.com/elixir-ecto/ecto/issues/3342
According to docs, a function passed to preload receives parent ids, but I got children ids.
Here is a test
https://github.com/fuelen/ecto/commit/1bd6f7ccb97b0edb3acb9bd10f47966758d344ef
which fails with
```
 Assertion with == failed
     code:  assert id == cid
     left:  64
     right: 127
```

### Expected behavior
Fix docs or implementation.

**Comment by josevalim** [comment]
Good catch, thank you for the test. I have gone back to the original report #2534 and tried the same app and the behaviour back then was the same as today, which means we simply documented the wrong behaviour. I will push a fix soon.
