### ISSUE TITLE
High idle_time for queries

### ISSUE THREAD

**Issue by alexbezhan** [elixir-ecto/ecto#3345]
### Environment

Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.3 (compiled with Erlang/OTP 22)
PostgreSQL 11.8
Ecto 3.4.5
Ecto SQL 3.4.4
Postrgex 0.15.5
MacOS Catalina 10.15.4

### Current behavior

My schemas:
```
schema "orders" do
    field :asin, :string
    field :purchase_date, :date
    field :review_deadline_date, :date
    field :review_link, :string
    belongs_to :owner, User
    belongs_to :reviewer, User
    belongs_to :status, OrderStatus
    belongs_to :problem, OrderProblem
    belongs_to :type, OrderType

    timestamps()
  end

schema "users" do
    pow_user_fields()
    has_many :owner_orders, Order, foreign_key: :owner_id
    has_many :reviewer_orders, Order, foreign_key: :reviewer_id

    timestamps()
  end
```

My query code:
```
Repo.all(from o in Order, preload: [:owner, :reviewer])
```

Query log:
```
[debug] QUERY OK source="orders" db=2.3ms idle=1384.0ms
SELECT o0."id", o0."asin", o0."purchase_date", o0."review_deadline_date", o0."review_link", o0."owner_id", o0."reviewer_id", o0."status_id", o0."problem_id", o0."type_id", o0."inserted_at", o0."updated_at" FROM "orders" AS o0 []
[debug] QUERY OK source="users" db=1.2ms idle=1386.5ms
SELECT u0."id", u0."password_hash", u0."email", u0."inserted_at", u0."updated_at", u0."id" FROM "users" AS u0 WHERE (u0."id" = $1) [1]
```

It takes 3s(sometimes 4s) to execute two queries. Database has 2 order records and 1 user record.

### Expected behavior

I expect these two queries to run under 100ms.

**Comment by alexbezhan** [comment]
I made even simpler example:
```
Repo.all(Ecto.Query.from("orders", select: [:id]))
```
Produces:
```
[debug] QUERY OK source="orders" db=0.8ms queue=0.6ms idle=551.6ms
SELECT o0."id" FROM "orders" AS o0 []
```

The idle time is very long

**Comment by josevalim** [comment]
Hi @alexbezhan,

To make sure we are all on the same page, having a high `idle_time` is ok, it means that nobody was using that connection. It doesn't mean the query is slow. if the query is slow, you should be seeing high-db and checkout times, but they seem to be low as well. If you think this is indeed an Ecto issue, please post an application that reproduces the error, then we can gladly reopen this and take a look at it. Thanks!

**Comment by alexbezhan** [comment]
@josevalim Here I posted the application https://github.com/alexbezhan/slow-query-app
Run it and open http://localhost:4000/orders

**Comment by alexbezhan** [comment]
Also, you will need to do `mix ecto.migrate` and then when you open the app, click Sign Up, because `/orders` requires athenticated user

**Comment by alexbezhan** [comment]
After that I found an old IP pointing to localhost in my `/etc/hosts` that was no longer accessible. Deleted this and all is fine now. Thanks everyone for the help.
