### ISSUE TITLE
Unable to cast count to float

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3346]
### Environment

* Elixir version: 1.10.3
* Database and version: PostgreSQL 11.4
* Ecto version: 3.4.5
* Database adapter and version (mix deps): postgrex 0.15.5
* Operating system: Linux

### Current behavior
I want to calculate percentage of some value. In raw SQL:
```sql
select count(*) FILTER (WHERE users.status = 'active') :: float * 100 / count(*) from users
```
and while writing this in Ecto DSL I've encountered into a couple of issues:
```elixir
> from u in "users", select: type(count(), :float)  
** (Ecto.Query.CompileError) the first argument of type/2 must be one of:

  * interpolations, such as ^value
  * fields, such as p.foo or field(p)
  * fragments, such fragment("foo(?)", value)
  * an arithmetic expression (+, -, *, /)
  * an aggregation or window expression (avg, count, min, max, sum, over, filter)

Got: count()

    (ecto) expanding macro: Ecto.Query.select/3
    iex:2: (file)
    (ecto) expanding macro: Ecto.Query.from/2
    iex:2: (file)
```
 count/1 fixes this issue, but produces another:
```elixir
> from u in "users", select: type(count(u.id), :float)
** (Ecto.Query.CompileError) expression `count(u.id())` does not type check. It returns a value of type :integer but a value of type :float is expected
    (ecto) expanding macro: Ecto.Query.select/3
    iex:2: (file)
    (ecto) expanding macro: Ecto.Query.from/2
    iex:2: (file)
```
### Expected behavior
compile this query
```elixir
from u in "users", select: type(filter(count(), u.status == "active"), :float) / count()
```
for now I use this
```elixir
from u in "users", select: fragment("? :: float", filter(count(), u.status == "active")) / count() * 100
```

**Comment by fuelen** [comment]
@josevalim I tried examples above in fresh master, and they still do not work.

**Comment by josevalim** [comment]
There is one bug here, which is `type(count(), ...)` did not work, but otherwise the error is correct when trying to type integer as float. Use `* 1.0` or similar for a float conversion rather than a type conversion. Or use the fragment.

**Comment by fuelen** [comment]
Thanks for the tip with `* 1.0`!
