### ISSUE TITLE
Make ECTO_EDITOR similar to ELIXIR_EDITOR and PLUG_EDITOR

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#3355]
If we happen to use all these variables, we might have this:

```
export ELIXIR_EDITOR="vim +__LINE__ __FILE__"
export PLUG_EDITOR=$ELIXIR_EDITOR
export ECTO_EDITOR="vim"
```

I think it would be good to unify, so we could do:

```
export ECTO_EDITOR=$ELIXIR_EDITOR
```

and we can do it in a backwards compatible way. Besides unification, a minor side benefit is we could set the `__LINE__` so e.g. when generating the migration we put the cursor below `def change`.

**Comment by josevalim** [comment]
Sounds good!
