### ISSUE TITLE
Changeset.traverse_errors/2 disregards higher-level errors for lower-level errors on relationship fields

### ISSUE THREAD

**Issue by JayAndCatchFire** [elixir-ecto/ecto#3357]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.3
* Ecto version (mix deps): 3.2.5
* Database adapter and version (mix deps): ecto_sql 3.2.2
* Operating system: macOS Catalina 10.15.5 (19F101)

### Current behavior
I've got a module that looks like this:
```elixir
defmodule Author do
  schema "author" do
    has_many(:books, Book, on_replace: :delete)
  end

  def changeset(author, attrs) do
    author
    |> cast(attrs, allowed_attrs())
    |> cast_assoc(:books)
    |> validate_delete_books()
  end

  defp validate_delete_books(changeset) do
    validate_change(changeset, :books, fn field, books_changesets ->
      books_changesets
      |> Enum.filter(&Enum.member?([:delete, :replace], &1.action))
      |> Enum.any?(&Book.special_validation(&1.data))
      |> if do
        [
          {field,
           "cannot be deleted if they fail my special validation"}
        ]
      else
        []
      end
    end)
  end
end
```
As you can see, I've added a special kind of validation so that implicit deletion of books via `cast_assoc` is prevented in specific cases.  The error is added to the `:books` field on the Author changeset.  However, Books themselves also have certain validations that can fail.

Now imagine a changeset comes in that due to `cast_assoc` causes both an invalid deletion attempt resulting in an error on the Author changeset on the `:books` field as well as either updates to existing Books or the attempted creation of new Books that also have validation errors.

When I call `Changeset.traverse_errors` on the changeset to report the errors, because of how `traverse_errors` works, the error at the Author level on the `:books` field is overwritten by the subsequent errors in the Book changesets themselves.  I believe this is caused by https://github.com/elixir-ecto/ecto/blob/fa0305655e2e0979f6e9e2eba20fa1e1d59a871a/lib/ecto/changeset.ex#L2909 which overwrites any previous values.

### Expected behavior
I'd expect `traverse_errors` to allow me a way to report errors at the Author-Book relationship level as well as any errors at the Book level.

**Comment by josevalim** [comment]
This is pretty much intentional behaviour. That's because the :books key of the errors is a list and there is no place we can inject that in the list without causing confusion. You need to either pick a book to add the validation too (it can be the first one) or add it to another field that you will check for elsewhere. In Rails apps, they would pick something like "base".
