### ISSUE TITLE
Missed `InvalidChangesetError` errors on `apply_action!/2` because they got transformed into `:debug` messages

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3359]
In my application, an error gets raised because I tried to call `Ecto.Changeset.apply_action!/2` on an invalid changeset.

> ** (Ecto.InvalidChangesetError) could not perform update because changeset is invalid.\n\nErrors\n\n %{\n […]

The problem is that I missed those errors because the error got transformed into a `:debug` message.

It happens because Phoenix Ecto considers that Changeset errors are only user errors and mark them as 4xx:

https://github.com/phoenixframework/phoenix_ecto/blob/v4.1.0/lib/phoenix_ecto/plug.ex#L6

and Plug Debugger converts 4xx errors to `:debug` logs:

https://github.com/elixir-plug/plug/blob/v1.10.3/lib/plug/debugger.ex#L165

Let me also please just stress that missed errors are terrible and scary.

Applying an action on an invalid changeset is a server error, not a user error. And devs need to be notified for such errors through error logs.

**Comment by josevalim** [comment]
Please open up an issue on `phoenix_ecto`.
