### ISSUE TITLE
The schema validation type for `{:array, inner_type} `  is not working as the query one

### ISSUE THREAD

**Issue by amandasposito** [elixir-ecto/ecto#3371]
### Environment

* Elixir version: 1.10.1

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres (PostgreSQL) 12.2

* Ecto version: 3.4.4

* Database adapter and version (mix deps): Postgrex 0.15.5

* Operating system: Mac OS and Alpine Linux

### Current behavior

The schema check for `{:array, inner_type} `  is not working as the query one.

### Expected behavior

The schema validation for types for `{:array, inner_type} ` is not working as the query one.

When we create a field with `{:array, :jsonb}`  in the schema and this column is empty in the database we don't receive any error on compilation time. 

But when we run a query in the table that has this column and has a value we receive an exception telling us that the `:jsonb` does not have a type definition.

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :jsonb.type/0 is undefined (module :jsonb is not available)
        :jsonb.type()
        (ecto 3.4.4) lib/ecto/type.ex:307: Ecto.Type.type/1
        (ecto 3.4.4) lib/ecto/type.ex:916: Ecto.Type.adapter_load/3
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:381: Ecto.Repo.Queryable.struct_load!/6
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:213: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
        (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:200: Ecto.Repo.Queryable.execute/4
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

I would expect to have the exception also on compilation time, but it is not happening because we are checking it differently. 
At the Schema level, we check a tuple, and at the Query level, we check only the type.

```
iex(1)> Ecto.Type.primitive?(:jsonb)
false
iex(2)> Ecto.Type.primitive?({:array, :jsonb})
true
```

**Schema**

[https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L2050-L2051](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L2050-L2051)

**Query**

[https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L300-L311](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L300-L311)

### Application Example

[ecto_bug.zip](https://github.com/elixir-ecto/ecto/files/5044145/ecto_bug.zip)

**Comment by Eiji7** [comment]
@amandasposito `ecto` does not support `:jsonb` type as it's `PostgreSQL` naming. You should use `:map` instead:

> In order to support maps, different databases may employ different techniques. For example, PostgreSQL will store those values in jsonb fields, allowing you to just query parts of it. MSSQL, on the other hand, does not yet provide a JSON type, so the value will be stored in a text field.
> ```elixir
> # In your migration
> create table(:users) do
>   add :data, :map
> end
> 
> # In your schema
> field :data, :map
> 
> # Now in your code
> user = Repo.insert! %User{data: %{"foo" => "bar"}}
> ```
Source: https://hexdocs.pm/ecto/Ecto.Schema.html#module-the-map-type

**Comment by amandasposito** [comment]
@Eiji7 I'm not saying it should support, I'm saying it should raise an error when I try to use it in the schema.

**Comment by Eiji7** [comment]
@amandasposito Ah, right - sorry now I can see the problem

**Comment by Eiji7** [comment]
@amandasposito I have created PR - in one test I have added 2 checks for `:jsonb` and `{:array, :jsonb` types. Let me know what you think about it.

**Comment by josevalim** [comment]
Closing in favor of PR!

**Comment by amandasposito** [comment]
@Eiji7 Thank you!
