### ISSUE TITLE
JSON shortcut does not correctly deal with NULL

### ISSUE THREAD

**Issue by princemaple** [elixir-ecto/ecto#3375]
### Environment

* Elixir version (elixir -v): 1.10.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): pg11
* Ecto version (mix deps): 3.4.5
* Database adapter and version (mix deps): 0.15.5
* Operating system: Alpine in docker

### Given

`A` embeds one `B` as `:b`, `B.x` can be `null`
There is one record `a` only, and `a.b.x` is `null`.

### Current behavior

```elixir
Repo.all(from a in A, where: fragment("?->>? is NULL", a.b, "x"))
```
Returns one record

```elixir
Repo.all(from a in A, where: is_nil(a.b["x"]))
```
Returns no records

### Expected behavior

The two return the same result

### Investigation

`is_nil(a.b["x"])` expands to `(a0.\"b\"#>'{\"x\"}') IS NULL`
So I tried this, `fragment("?#>>'{\"x\"}' is NULL", a.b)`, it seems to work as expected.

Now I'm just wondering, is it a bug or the shortcut is doing something different from what I expected?

**Comment by josevalim** [comment]
I cannot reproduce the issue. In my tests `Repo.all(from a in A, where: is_nil(a.b["x"]))` is behaving correctly and returning all null entries. Can you provide a sample application or a failing test case to Ecto that fully reproduces the issue? Thanks!

**Comment by princemaple** [comment]
Will do

**Comment by michalmuskala** [comment]
Could this be an issue caused by JSON null not being the same as regular SQL null? i.e. `'null'::json IS NULL` is `false` in postgres.

**Comment by princemaple** [comment]
Repo: https://github.com/princemaple/ecto-json-null-repro

### Setup

```
docker-compose build
docker-compose up -d db
docker-compose run --rm -e MIX_ENV=test app mix ecto.create
docker-compose run --rm -e MIX_ENV=test app mix ecto.migrate
```

### Repro
```
▶ docker-compose run --rm app mix test
Starting ecto_json_db_1 ... done
.
07:40:20.358 [debug] QUERY OK db=5.2ms decode=0.5ms queue=0.4ms idle=57.6ms
INSERT INTO "posts" ("content","meta","subject") VALUES ($1,$2,$3) RETURNING "id" ["test", %{nothing: nil}, "test"]

07:40:20.362 [debug] QUERY OK source="posts" db=0.4ms queue=0.6ms idle=69.3ms
SELECT p0."id", p0."subject", p0."content", p0."meta" FROM "posts" AS p0 WHERE ((p0."meta"#>'{"nothing"}') IS NULL) []
.

Finished in 0.07 seconds
1 doctest, 1 test, 0 failures

Randomized with seed 276503
```

The test should fail. I expected the test asserts to return the same value.

**Comment by josevalim** [comment]
Thanks @princemaple!

@michalmuskala got it right, the value returned by JSON is not the same as SQL's null. Here is a snippet from psql:

```
live_demo_dev=# SELECT ('{"a":{"b":[4,5,6]}}'::jsonb#>'{"a","c"}') IS NULL;
 ?column?
----------
 t
(1 row)

live_demo_dev=# SELECT ('{"a":{"b":[4,5,6],"c":null}}'::jsonb#>'{"a","c"}') IS NULL;
 ?column?
----------
 f
(1 row)
```

I am not sure what to do here, to be honest. This behaviour is actually consistent across databases. The reason why it works with `->>` is because it actually casts stuff to text but that's not what we generally want from the `o.meta["nothing"]` syntax. Perhaps the best choice is to document it.

FWIW, this works:

```sql
SELECT ('{"a":{"b":[4,5,6],"c":null}}'::jsonb#>'{"a","c"}') = 'null'::jsonb;
```

**Comment by princemaple** [comment]
I probably had some false expectations. Now I test it, many things I thought would work actually doesn't. I should revise my expectations about `JSONB` in `where`.

Thanks @josevalim and @michalmuskala !
