### ISSUE TITLE
Ecto.delete_all with returning not returning anything

### ISSUE THREAD

**Issue by quantumpotato** [elixir-ecto/ecto#3379]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2
* Database and version (PostgreSQL 9.5.1,
* Ecto version (mix deps): (ecto 3.4.4
* Database adapter and version (mix deps):  postgrex 0.15.4
* Operating system: OSX

### Current behavior

Multi.new()
|> Multi.delete_all(:delete_all_restaurants, query, returning: [:identifier])
 |> Multi.run(:delete_events, fn _repo, so_far = %{delete_all_restaurants: {_, restaurants_deleted}} ->
        IO.inspect(so_far, label: "hey biscuit")

Include code samples, errors and stacktraces if appropriate.

### Expected behavior

I get a list of %{} with the identifiers of restaurants deleted

Actual result:

I get hey biscuit: %{delete_all_restaurants: {2, nil}}

identifier is a field in my Restaurant model.

Is this the correct use of Ecto.delete_all returning?

**Comment by josevalim** [comment]
`returning: ...` has been deprecated in Ecto 3. Instead pass a `select` in your query. For example: `select: table.identifier`.
