### ISSUE TITLE
Query by Inner jsonb

### ISSUE THREAD

**Issue by ferigis** [elixir-ecto/ecto#3383]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 12
* Ecto version (mix deps): 3.4.5
* Operating system: Mac

### Current behavior

Hi!

I have a jsonb column called `column1` and I want to query by inner field, for example:

```
{
  "field1": "value1",
  "field2": {
     "field3": "value3"
  }
}
```

if I do

```
from(q in query, where: fragment("? @> '{\"field2\": {\"field3\": \"value3\"}}'", q.column1))
```

it works but if I run

```
from(q in query, where: fragment("? @> ?", q.column1, ^"{\"field2\": {\"field3\": \"value3\"}}"))
```

it doesn't work

### Expected behavior

I think the second one should work same as first fragment. I assume this is an escape issue but I can't find the way to make it work.

**Comment by wojtekmach** [comment]
could you try casting the right hand side to jsonb like this?

```
from(q in query, where: fragment("? @> ?::jsonb", q.column1, ^"{\"field2\": {\"field3\": \"value3\"}}"))
```

does this help?

**Comment by ferigis** [comment]
hi! @wojtekmach , thanks for the tip but unfortunately it seems do not work :(

**Comment by josevalim** [comment]
Hi @ferigis! This is most likely not an Ecto issue but a Postgres ones. Postgres behaves slightly differently when data is passed as parameter compared to text. In other words, it is not guarantee in PG syntax that:

    p.column @> '{\"field2\": {\"field3\": \"value3\"}}'

will behave the same as:

    p.column @> $1

To check this out, my suggestion is for you to try writing your query directly with Repo.query:

    Repo.query("SELECT ... WHERE p.column @> '{\"field2\": {\"field3\": \"value3\"}}'", [])

And then try it as:

    Repo.query("SELECT ... WHERE p.column @> $1", ["{\"field2\": {\"field3\": \"value3\"}}"])

Once you find the variant that works (which may require typecasting as suggested by @wojtekmach), then you can write the fragment.

**Comment by ferigis** [comment]
thanks @wojtekmach and @josevalim for the tips/suggestions. I am going to play with that!

**Comment by ferigis** [comment]
just for the record if someone has a similar issue. I could fix it like this:

```elixir
from(q in query, where: fragment("(?->'field2')->>'field3' LIKE ?", q.column1, ^"value3"))
```
