### ISSUE TITLE
Add Repo.reload and Repo.reload!

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#3389]
It receives a schema (or a list of schemas) and uses the meta information + primary key to reload the same entry from the database. The non bang variant returns nil (or removes the element from the list), the bang variant raises.

**Comment by michalmuskala** [comment]
What's the behaviour or associations? Are they unloaded?

**Comment by josevalim** [comment]
@michalmuskala good call, I would unload them and if you want, you can preload/copy the ones you want afterwards.

**Comment by prihandi** [comment]
If implemented, it'be nice too if `insert` and `update` given option to reload the entity also
e.g
I have table `users` , having fields : id, name, email, active, that default value for field `active` is true
I create a new user with required field only (name and email) , the return of `insert/1` would have field `active` with value nil, instead true

**Comment by josevalim** [comment]
@prihandi we already support that by using the `returning` option or configuring read_after_writes.

**Comment by v0idpwn** [comment]
Can I take this one?

**Comment by josevalim** [comment]
Yes please!

**Comment by v0idpwn** [comment]
@josevalim do you think this belongs to `Ecto.Repo.Queryable` or `Ecto.Repo.Schema`? I was thinking it should be on schema because it expects schemas only (and not any queryable), but so does `Repo.get/2`, which is on `Ecto.Repo.Queryable` and is very similar to `Repo.reload`.

**Comment by josevalim** [comment]
Yes, let's go with `Ecto.Repo.Queryable` since it is similar to `Repo.get` (and will most likely rely on it).
