### ISSUE TITLE
Repo.update_all should accept a map

### ISSUE THREAD

**Issue by kuon** [elixir-ecto/ecto#3391]
At present `Repo.insert_all` accept either a map or a keyword list, for example, we can do:

```elixir
attrs = %{"col" => "data"}
Repo.insert_all("some_table", [attrs])
```

But, we cannot do:

```elixir
attrs = %{"col" => "newdata"}
id = 1

from(row in "some_table", where: row.id == ^id) 
|> Repo.update_all(set: attrs)
```

This is enforced by https://github.com/elixir-ecto/ecto/blob/a33f79fb577ac765f5b6c70b7f4be9fab94c9ebb/lib/ecto/query/builder/update.ex#L90

This is an issue with dynamic table mapping. I have an app with dynamic tables where each user can create its own schema, and I don't want to convert all user defined column name to atoms. This is a minor issue, but I think it's good hygiene to not `to_atom` user data.

**Comment by josevalim** [comment]
Sounds good! PR is welcome!

**Comment by v0idpwn** [comment]
Can I take this one?

**Comment by kuon** [comment]
I did work around it, and I don't have time to make a PR, so I would appreciate.

**Comment by josevalim** [comment]
We have decided to not support this after all, see #3411 for a compete discussion. Thanks!
