### ISSUE TITLE
Fragment Encode Error

### ISSUE THREAD

**Issue by Adzz** [elixir-ecto/ecto#3392]
### Precheck
✅
### Environment

* Elixir version (elixir -v): 1.10.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgresSQL 11
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps): Postgrex 0.15.5
* Operating system: unix

### Current behavior

I don't know if this is a bug or misuse but when using fragments 

This works:
```elixir
where: fragment("start_date - 10 > '2020-08-31'"),
```
This works:
```elixir
where: fragment("start_date - 10 > ?", "2020-08-31"),
```
as does this:
```elixir
where: fragment("start_date - 10 > ?", ^~D[2020-08-31]),
```
As does this:
```elixir
where: fragment("start_date - ? > ?", 10, ^~D[2020-08-31]),
```
But this does not:
```elixir
args = %{thing: 10}
...
where: fragment("start_date - ? > ?", ^args.thing, ^~D[2020-08-31]),
...
```
Nor this:
```elixir
where: fragment("start_date - ? > ?", ^10, ^~D[2020-08-31]),
```

The error I get is

```
*** (DBConnection.EncodeError) Postgrex expected %Date{}, got 10.
```

It seems like if I pin the integer it doesn't work. Which is really confusing to me.

### Expected behavior

Given that this is valid SQL:

```sql
SELECT * FROM weeks WHERE start_date - 10 > '2020-08-31';
```

I would expect this to be valid:
```elixir
where: fragment("start_date - ? > ?", ^args.thing, ^~D[2020-08-31]),
```

**Comment by josevalim** [comment]
This is  not an Ecto bug but PostgreSQL behaviour. When you write "start_date - 10", PostgreSQL knows it is an integer and can work things out. However, when you just write `?`, PostgreSQL has to make a choice and it chooses a `Date`. There is nothing Ecto can do fix this chance. You can, however, tell PostgreSQL which type you are expecting or use a more precise function rather than the general `-`:

    where: fragment("start_date - ?::integer > ?", ^args.thing, ^~D[2020-08-31]),

**Comment by Adzz** [comment]
Ah thank you so much. I tried this:
```
where: fragment("(start_date - ?)::date > ?", ^args.thing, ^~D[2020-08-31]),
```
which also failed, which is why I thought it wasn't a sql thing. That makes so much sense though
