### ISSUE TITLE
Field with type {:array, MyStruct} raises compilation error in 3.5

### ISSUE THREAD

**Issue by aaronrenner** [elixir-ecto/ecto#3396]
### Environment

* Elixir version (elixir -v): 1.10
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 3.5.0-rc.0
* Database adapter and version (mix deps): N/A
* Operating system: Mac OS 10.15.6

### Current behavior

When upgrading an application with the field
```elixir
field :comments, {:array, BrokenSchema.Comment}
```

a compilation error is raised in Ecto 3.5

```
== Compilation error in file lib/broken_schema/blog.ex ==
** (ArgumentError) schema BrokenSchema.Comment is not a valid type for field :comments. Did you mean to use belongs_to, has_one, has_many, embeds_one, or embeds_many instead?
    lib/ecto/schema.ex:2090: Ecto.Schema.check_field_type!/4
    lib/ecto/schema.ex:2078: Ecto.Schema.check_field_type!/4
    lib/ecto/schema.ex:1796: Ecto.Schema.__field__/4
    lib/broken_schema/blog.ex:5: (module)
```

An example project is available here: https://github.com/aaronrenner/broken_schema

This project will recreate the compilation error when it's upgraded to 3.5.0-rc.0.

### Expected behavior

This code should continue to compile as it did with Ecto 3.4.

**Comment by josevalim** [comment]
The error message is correct, as `Comment` is not an Ecto.Type. I am actually surprised to how it worked before... did it just accept all values as is? Did it do any casting/dump/loading?

**Comment by aaronrenner** [comment]
Upon examining the code further, the child schemas (`Comment` in this case) were being manually cast and then assigned as a list to the parent (`Post` in this case). Looks like this new compiler error uncovered some incorrect code in the codebase.

Thanks!

**Comment by alg** [comment]
I had this in my schema and pre-loaded `linked_users` manually when necessary, so I had access to full linked users, not just ID's.

```
    field :linked_user_ids, {:array, :integer}
    field :linked_users, {:array, User}, virtual: true
```

@josevalim I don't see anything bad with having arbitrary type of an array element as long as it's a virtual field. Of course, I can work it around by saying `{:array, :string}` while actually storing User structures in there, but why do we need these hacks?

**Comment by wojtekmach** [comment]
@alg if you don't care about the type, the way to go is using `{:array, :any}`.

**Comment by alg** [comment]
Oh, man. I missed this important bit:

> Finally, schemas can also have virtual fields by passing the virtual: true option. These fields are not persisted to the database and can optionally not be type checked by declaring type :any.

Thanks @wojtekmach!
