### ISSUE TITLE
Repo.insert_all should accept a query

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#3400]
Right now there is already some primitive support for this via elixir-ecto/ecto_sql#39, in the following form:
```elixir
Repo.insert_all(Comment, [[text: "Yo!", user_id: user_id_query]])
```

I would like to be able to use an `INSERT INTO ... SELECT ...` statement to copy arbitrary rows from a select statement to a destination table (in my case, it's actually the same table, but that shouldn't matter for the implementation).
```elixir
def migrate_interactions(source, target) do
  new_hides =
    from i in ImageHide,
      where: i.image_id == ^source.id
      select: %{image_id: type(^target.id, :integer), user_id: i.user_id}
      
  Repo.insert_all(ImageHide, [new_hides], on_conflict: :nothing)
end
```

**Comment by josevalim** [comment]
Unfortunately this feature is too complex if we are to consider all the possible options and combinations allowed in Repo.all + Repo.insert, so for now I will suggest to either hand-write the query or use Repo.to_sql to compose the select and build the overall insert with it that you pipe into Repo.query. Thanks!

**Comment by tmock12** [comment]
**UPDATE:** It's landing soon -> https://github.com/elixir-ecto/ecto/pull/3574 🎉
