### ISSUE TITLE
3.5.0-rc.0: calling build_assoc w/ Ecto.Enum on table doesn't work w/ Phoenix params

### ISSUE THREAD

**Issue by garlandcrow** [elixir-ecto/ecto#3401]
My tables to demonstrate the error
```elixir
 schema "quotations" do
    field :currency, Ecto.Enum, values: [:usd, :jpy, :eur, :cny], default: :jpy
    belongs_to :customer, Customer
  end

 schema "customer" do
    field :name, :string
    has_many :quotations, Quotation
  end
```
In my Phoenix route, I get some params on post to create a quotation containing the currency, which comes as ` %{"currency" => "cny"}` and I pass to `build_assoc` I get an error.

```elixir
quotation = customer |> build_assoc(:quotations, params) |> Repo.insert!

 ** (Ecto.ChangeError) value `"cny"` for `Schema.Quotation.currency` in `insert` does not match type {:parameterized, Ecto.Enum, %{on_dump: %{cny: "cny", eur: "eur", jpy: "jpy", usd: "usd"}, on_load: %{"cny" => :cny, "eur" => :eur, "jpy" => :jpy, "usd" => :usd}}}
```

Should you handle converting the params manually? Or should `build_assoc` be able to the conversion for the Ecto.Enum when you call this?

**Comment by josevalim** [comment]
You want to use `Ecto.Changeset.cast`, so the parameters are properly cast to their types. `build_assoc` assumes the data has been properly validated and handled, which is not the case if you are passing controller params. I will improve the docs. :)
