### ISSUE TITLE
Recursive CTEs not allowing direct selection into struct

### ISSUE THREAD

**Issue by D4no0** [elixir-ecto/ecto#3403]
Currently there is no way to explicitly use the recursive selection and select directly in a struct.

The only workaround I could accomplish is to inner join with the same table and extract the values from that join:

```
category_tree_initial_query =
  Category
  |> where([c], c.id == 1)

category_tree_recursion_query =
  Category
  |> join(:inner, [c], ct in "category_tree", on: c.parent_id == ct.id)

category_tree_query =
  category_tree_initial_query
  |> union_all(^category_tree_recursion_query)

"custom_cte"
|> recursive_ctes(true)
|> with_cte("custom_cte", as: ^category_tree_query)
|> join(:inner, [c], c1 in Category, on: c.id == c1.id, as: :cat)
|> select([cat: cat], cat)
```

**Comment by josevalim** [comment]
The issue here is that you are not starting the query with a schema, you are using `"custom_cte"`. You can attach a schema to it by using a tuple `{"custom_cte", Category} |> with_cte(...) |> ...`.

**Comment by D4no0** [comment]
Thank you! The example in documentation is a little misleading, I thought the syntax is for selecting a touple.
