### ISSUE TITLE
autogenerate for ParameterizedType

### ISSUE THREAD

**Issue by elielhaouzi** [elixir-ecto/ecto#3408]
### Environment

* Elixir version (elixir -v): 1.10.4
* Ecto version (mix deps): 3.5.0-rc.0
* Database adapter and version (mix deps): postgrex 0.15.5
* Operating system: ubuntu

### Current behavior
I just implemented a parameterizedType for a primary key field and I cannot set the autogenerate to true, I get an exception
`field :id does not support :autogenerate because it uses a primitive type {:parameterized, Shortcode.Ecto.ID, %{autogenerate: true, field: :id, prefix: "cus", primary_key: true, schema: Payments.Customers.Customer}}`

I think the problem is since all parameterizedType are considered `primitive`, (found here [Ecto.Type](https://github.com/elixir-ecto/ecto/blob/v3.5.0-rc.0/lib/ecto/type.ex#L208)), 
in Ecto.Schema the function [store_type_autogenerate!](https://github.com/elixir-ecto/ecto/blob/v3.5.0-rc.0/lib/ecto/schema.ex#L2119) that call the `autogenerate_id` function for getting the field type sends nil despite the fact that the type of the parameterizeType is :id or :binary. (the function autogenerate_id call the type function of the ecto type only for non-primitive type)

BUT, even if I success to bypass this problem by setting manually the `ecto_atuogenerate_id` attribute and autogenerate to false, I have the same problem described #2615, when I insert I get the integer and when I load from the db I get the shortcode.
(i know i'm not supposed to set the ecto_atuogenerate_id attribute manually but it was just for the test)

This is my implementation of the [ParameterizedType](https://github.com/elielhaouzi/shortcode/blob/master/lib/ecto/types/id.ex)
```elixir
 defmodule Shortcode.Ecto.ID do
    use Ecto.ParameterizedType

    @spec type(any) :: :id
    def type(_), do: :id

    @spec init(keyword()) :: map()
    def init(opts) do
      validate_opts!(opts)

      Enum.into(opts, %{})
    end

    @spec cast(binary, map) :: {:ok, integer}
    def cast(integer, _) when is_integer(integer) and integer >= 0, do: {:ok, integer}

    def cast(shortcode, _) when is_binary(shortcode) and byte_size(shortcode) > 0 do
      {:ok, Shortcode.to_integer(shortcode)}
    end

    def cast(_, _), do: :error

    @spec load(integer, any, map) :: {:ok, binary}
    def load(integer, _, params) when is_integer(integer) and integer >= 0 do
      prefix = Map.get(params, :prefix)

      {:ok, Shortcode.to_shortcode(integer, prefix)}
    end

    def load(_, _, _), do: :error

    @spec dump(binary, any, map) :: {:ok, integer}
    def dump(integer, _, _) when is_integer(integer) and integer >= 0, do: {:ok, integer}

    def dump(shortcode, _, _) when is_binary(shortcode) and byte_size(shortcode) > 0 do
      {:ok, Shortcode.to_integer(shortcode)}
    end

    def dump(_, _, _), do: :error

    defp validate_opts!(opts) do
      prefix = opts |> Keyword.get(:prefix)

      if not is_nil(prefix) and String.contains?(prefix, Shortcode.prefix_separator()) do
        raise ArgumentError, "prefix cannot contain \"#{Shortcode.prefix_separator()}\""
      end
    end
  end
```
implementation of the schema (with the ecto_autogenerate_id)
```elixir
defmodule Payments.Customers.Customer do
  use Ecto.Schema

  @primary_key {:id, Shortcode.Ecto.ID, prefix: "cus", autogenerate: false}
  @ecto_autogenerate_id {:id, :id, :id}
  schema "customers" do
  end
end
```
let's say the next autoincrement id is 10
```elixir
iex> Shortcode.to_shortcode(10, "cus")
"cus_a"
iex> %Payments.Customers.Customer{} |> Ecto.Changeset.change(%{}) |> Payments.Repo.insert!()
%Payments.Customers.Customer{
  __meta__: #Ecto.Schema.Metadata<:loaded, "customers">,
  id: 10
}
```

### Expected behavior

```elixir
defmodule Payments.Customers.Customer do
  use Ecto.Schema

  @primary_key {:id, Shortcode.Ecto.ID, prefix: "cus", autogenerate: true}
  schema "customers" do
  end
end
```

```elixir
iex> %Payments.Customers.Customer{} |> Ecto.Changeset.change(%{}) |> Payments.Repo.insert!()
%Payments.Customers.Customer{
  __meta__: #Ecto.Schema.Metadata<:loaded, "customers">,
  id: "cus_a"
}
```

**Comment by josevalim** [comment]
Yes, we need to support autogenerate for them. A PR is very welcome!
