### ISSUE TITLE
Querying a Ecto.Enum without a pin operator in the last rc

### ISSUE THREAD

**Issue by sabiwara** [elixir-ecto/ecto#3412]
### Environment

* Elixir version (elixir -v): 1.10.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.1
* Ecto version (mix deps): `3.5.0-rc.0`
```
      {:phoenix_ecto, "~> 4.1", override: true},
      {:ecto, "~> 3.5.0-rc.0", override: true},
      {:ecto_sql, "~> 3.5.0-rc.0", override: true},
      {:postgrex, ">= 0.0.0"},
```
* Operating system: Ubuntu 18.04

### Current behavior

Reproduced a mininal example:

Schema:
```elixir
  schema "my_resources" do
    field :barbaz, Ecto.Enum, values: [:bar, :baz]

    timestamps()
  end
```

Failing example 1:

```elixir
Ecto.Query.where(MyResource, barbaz: :bar)
```

fails with a compilation error:
```
== Compilation error in file lib/foo/my_context/my_resource.ex ==
** (Ecto.Query.CompileError) `:bar` is not a valid query expression
    (ecto 3.5.0-rc.0) expanding macro: Ecto.Query.where/2
    (foo 0.1.0) lib/foo/my_context/my_resource.ex:26: Foo.MyContext.MyResource.atom_query/0
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Failing example 2:

```elixir
Ecto.Query.where(MyResource, barbaz: "bar")
```
Compiles but fails at runtime (which is understandable) with:
```
** (Ecto.QueryError) lib/foo/my_context/my_resource.ex:22: value `"bar"` cannot be dumped to type {:parameterized, Ecto.Enum, %{on_dump: %{bar: "bar", baz: "baz"}, on_load: %{"bar" => :bar, "baz" => :baz}}}. Or the value is incompatible or it must be interpolated (using ^) so it may be cast accordingly in query:
```

Working example (pinning the atom):

```elixir
Ecto.Query.where(MyResource, barbaz: ^:bar)
```

### Expected behavior

Either one of the following would be great:
- modify the `where` macro to be able to query directly with an atom, given it is now a legit value (example 1. above)
- if not possible, maybe complete `Ecto.Enum`'s documentation with examples how they should be queried?

What do you think? I'm happy to try open a PR for either if you think I can help with it.

PS: Really loving the new Enums, great feature :purple_heart:

**Comment by sabiwara** [comment]
Sorry I wasn't done filling it :bow:

**Comment by josevalim** [comment]
@sabiwara no worries! You can also keep it open and edit it. :) Your call!

**Comment by sabiwara** [comment]
Edited, thanks :)

**Comment by josevalim** [comment]
Btw, a PR is welcome! I think the first step is to allow atoms in the query/builder.ex and then we need two tests:

    where(p.some_string_column == :atom) #=> will raise
    where(p.some_enum_column == :atom) #=> will work

**Comment by sabiwara** [comment]
Sounds great, will give it a try!
