### ISSUE TITLE
Still cannot run mix gen repo from umbrella project

### ISSUE THREAD

**Issue by hiraqdev** [elixir-ecto/ecto#3413]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps):  ecto_sql 3.4.5
* Operating system: linux ubuntu 20.04

### Current behavior

When i run `mix ecto.gen.repo -r User.Repo`

```
** (Mix) Cannot run task "ecto.gen.repo" from umbrella application
```

### Expected behavior

Should be able to generate repo from umbrella application

---

I've checked the source inside `master` branch and also `3.4.6` tag version at: https://github.com/elixir-ecto/ecto/blob/v3.4.6/lib/mix/tasks/ecto.gen.repo.ex#L38 , there is sill using `no_umbrella!` 

```elixir
@doc false
  def run(args) do
    no_umbrella!("ecto.gen.repo")
    {opts, _} = OptionParser.parse!(args, strict: @switches, aliases: @aliases)

    repo =
      case Keyword.get_values(opts, :repo) do
        [] -> Mix.raise "ecto.gen.repo expects the repository to be given as -r MyApp.Repo"
        [repo] -> Module.concat([repo])
        [_ | _] -> Mix.raise "ecto.gen.repo expects a single repository to be given"
      end
```

from the `master` branch (in the same file and same line): https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.gen.repo.ex#L38 also still using `no_umbrella!` 

I though before that maybe this issue relate with https://github.com/elixir-ecto/ecto/issues/3202 , but i've checked that issue was fixed and also merged to `master` .

Is it expected behavior that current version still using `no_umbrella!` ? I'm still confuse why ecto prevent generation from umbrella ?

**Comment by Eiji7** [comment]
@hiraqdev #3202 was about calling this task from any `app` inside `apps` directory - i.e. not from `root` of `umbrealla`. The `no_umbrella!/1` call is still unchanged from earliest release `v.0.16.0`.

I may only guess why it's done right that, but I think that authors did not want to complicate `task` and did not add option like `--app` for which repo should be generated. For me it looks like:
> `run as expected` (inside specific application) **or** `let if fail` (with error you have) otherwise".

**Comment by hiraqdev** [comment]
Yeah, i think you're right @Eiji7 , the issue https://github.com/elixir-ecto/ecto/issues/3202 is different with mine here, so is it mean, that ecto will not run (forever) from the umbrella project ?

**Comment by josevalim** [comment]
You cannot run it from root because we don’t know on which app in the umbrella we should actually add the repo. Just pick one and add it inside that child. I will improve the error message.
