### ISSUE TITLE
Documentation bug in "Dynamic queries -> Dynamic and joins"

### ISSUE THREAD

**Issue by stiang** [elixir-ecto/ecto#3417]
In [/guides/howtos/Dynamic%20queries.md](https://github.com/elixir-ecto/ecto/blob/v3.4.6/guides/howtos/Dynamic%20queries.md), there’s the following code block:

```elixir
def filter(params) do
  Post
  # 1. Add named join binding
  |> join([p], assoc(p, :authors), as: :authors)
  |> order_by(^filter_order_by(params["order_by"]))
  |> where(^filter_where(params))
end
```

However, it seems there’s (currently) no version of [Ecto.Query.join](https://hexdocs.pm/ecto/Ecto.Query.html#join/5) that permits the `qual` argument to be omitted, so as written that code block produces the following error:

```
** (ArgumentError) invalid binding passed to Ecto.Query.join/5, should be list of variables, got: assoc(p, :authors)
    (ecto 3.4.4) lib/ecto/query.ex:1037: Ecto.Query."MACRO-join"/6
    (ecto 3.4.4) expanding macro: Ecto.Query.join/4
    [...]
```

I believe the code block should instead be:

```elixir
def filter(params) do
  Post
  # 1. Add named join binding
  |> join(:inner, [p], assoc(p, :authors), as: :authors)
  |> order_by(^filter_order_by(params["order_by"]))
  |> where(^filter_where(params))
end
```

Note the addition of `:inner` in the `join/5` invokation.

Also, [the documentation](https://hexdocs.pm/ecto/Ecto.Query.html#join/5) for `Ecto.Query.join` mentions that `:inner` is the default, but I don’t think it makes sense to talk about a default if the `qual` argument is mandatory.

I could take a stab at a PR if you agree that this could be improved.

**Comment by josevalim** [comment]
Agreed! A PR will be very appreciated!

**Comment by stiang** [comment]
Sorry about the delay, thanks for fixing it 👍
