### ISSUE TITLE
Duplicate query alias generated with nested subqueries

### ISSUE THREAD

**Issue by hoyon** [elixir-ecto/ecto#3419]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 12.4
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps): postgrex 0.15.5
* Operating system: Arch linux

### Current behavior

When nesting subqueries, the same alias can be generated twice which can cause unexpected results.

Example:

```elixir
  # insert 4 cohorts each with 1 cohort_company

  query =
    from c in "cohorts", as: :cohort,
    inner_lateral_join: sub in subquery(
      from cc in "cohort_companies",
      where: cc.cohort_id == parent_as(:cohort).id,
      select: cc.id,
      limit: 1
    ),
    select: %{id: c.id, sub_id: sub.id}

  Ecto.Adapters.SQL.to_sql(:all, Repo, query)
  |> IO.inspect(label: :all_query)

  count_query = query |> subquery() |> select(count("*"))
  Ecto.Adapters.SQL.to_sql(:all, Repo, count_query)
  |> IO.inspect(label: :count_query)

  Repo.all(query) |> IO.inspect(label: :all_result)
  Repo.one(count_query) |> IO.inspect(label: :count_result)
```

This generates the output:

```
all_query: {"SELECT c0.\"id\", s1.\"id\" FROM \"cohorts\" AS c0 INNER JOIN LATERAL (SELECT sc0.\"id\" AS \"id\" FROM \"cohort_companies\" AS sc0 WHERE (sc0.\"cohort_id\" = c0.\"id\") LIMIT 1) AS s1 ON TRUE",
 []}
count_query: {"SELECT count() FROM (SELECT sc0.\"id\" AS \"id\", ss1.\"id\" AS \"sub_id\" FROM \"cohorts\" AS sc0 INNER JOIN LATERAL (SELECT sc0.\"id\" AS \"id\" FROM \"cohort_companies\" AS sc0 WHERE (sc0.\"cohort_id\" = sc0.\"id\") LIMIT 1) AS ss1 ON TRUE) AS s0",
 []}
all_result: [
  %{id: 12362, sub_id: 14259},
  %{id: 12363, sub_id: 14260},
  %{id: 12364, sub_id: 14261},
  %{id: 12365, sub_id: 14262}
]
count_result: 0
```

The alias `sc0` has been generated twice, once for `cohorts` in the middle query and again for `cohort_companies` in the inner query. This only works if the two tables start with the same letter, as otherwise a different alias would be generated and would return the expected result.

### Expected behavior

The count query returns 4 not 0.

**Comment by mjquinlan2000** [comment]
Hi, I noticed this when trying to do nested subqueries with lateral joins so I set up a test project displaying the error. I can currently circumvent the problem by making the innermost join a fragment, but it's not very friendly.

Here is the project https://github.com/mjquinlan2000/ecto-lateral-subquery-aliasing-test

Let me know if there are any questions

**Comment by josevalim** [comment]
Fixed here: https://github.com/elixir-ecto/ecto_sql/commit/babc5542d729c7e6b8cecc70cd095cbc740f21e8
