### ISSUE TITLE
Support for subquery with window?

### ISSUE THREAD

**Issue by D4no0** [elixir-ecto/ecto#3420]
Is there a updated version that doesn't require a fragment for windowed subquery?

The currently working version is this:
https://elixirforum.com/t/problem-with-window-function/9453/16

**Comment by josevalim** [comment]
It may be doable using the `over` helpers added in Ecto.Query.API and the general window functions. Also, please use the forum for questions, as a wider community will be available to help you. Thanks.

**Comment by D4no0** [comment]
Ok, it seems I managed to do this using the [merge/2](https://hexdocs.pm/ecto/Ecto.Query.API.html#merge/2) helper and a virtual field.
Thanks for the help.
