### ISSUE TITLE
Repo.preload on a list that has the same register twice duplicates the assocs that were already preloaded

### ISSUE THREAD

**Issue by kelvinst** [elixir-ecto/ecto#3421]
# Environment

* Elixir version (elixir -v):

$ elixir -v
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 21)

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):

PostgreSQL 12.1

* Ecto version (mix deps):

Tested on master, the issue still there

* Database adapter and version (mix deps):
* Operating system:

### Current behavior

So, I guess this code explains better than words:

```elixir
    p1 = TestRepo.insert!(%Post{title: "1"})
    # We use the same text to expose bugs in preload sorting
    %Comment{id: cid1} = TestRepo.insert!(%Comment{text: "1", post_id: p1.id})
    %Comment{id: cid2} = TestRepo.insert!(%Comment{text: "2", post_id: p1.id})

    assert %Ecto.Association.NotLoaded{} = p1.comments

    [p1, p1] = TestRepo.preload([p1, p1], :comments)
    assert [%Comment{id: ^cid1}, %Comment{id: ^cid2}] = p1.comments |> sort_by_id

    [p1, p1] = TestRepo.preload([p1, p1], :comments)
    assert [%Comment{id: ^cid1}, %Comment{id: ^cid2}] = p1.comments |> sort_by_id
```

I actually implemented this integration test in my fork: https://github.com/kelvinst/ecto/blob/repeated-preload-fix/integration_test/cases/preload.exs#L27-L55

### Expected behavior

The test mentioned should pass, but it actually fail with this message:

<img width="1022" alt="Captura de Tela 2020-09-24 às 18 07 56" src="https://user-images.githubusercontent.com/2791965/94200492-e2151680-fe90-11ea-8311-80c53e98b31d.png">

As you can see in the print, it duplicates the associations that were preloaded for the second time. 

Some more details I got from my investigations:

1. It actually duplicates by the amount of repeated resources on the preload list, so if I do `TestRepo.preload([p1, p1, p1], :comments)` for example, it would load 3 instances of the same association on the preloaded field
2. It just happens if it is already preloaded
3. If you run it again, it will duplicate the instances once more

**Comment by kelvinst** [comment]
Also `force: true` helps as a workaround, but I kind of don't want to force a reload when it is not needed

**Comment by kelvinst** [comment]
Will happily work on it when I get time, as it affects our production code.

**Comment by josevalim** [comment]
Thanks! Is it a regression? Was it working on v3.4.x?

**Comment by kelvinst** [comment]
Oh, sorry, the versions I'm on in prod:

```
  ecto 3.2.5
  ecto_sql 3.2.2
 ```

**Comment by kelvinst** [comment]
@josevalim thanks for the quick fix! Any idea when is this going to be released? Will it be included in the next patch, or just the next minor?

**Comment by josevalim** [comment]
It will be included in the v3.5 final.

**Comment by kelvinst** [comment]
Any date for that? Just to know if I wait the release to update, or I do cherry-pick the commit on top of the last stable release on my fork (as the error is on a beta feature I can wait a bit)

**Comment by kelvinst** [comment]
PS.: No pressure, your work pace is pretty crazy to me already 😂, I have no problem on waiting

**Comment by josevalim** [comment]
As most releases, it will be out when it will be out. :)
