### ISSUE TITLE
`dynamic/3` with subquery giving compile errors

### ISSUE THREAD

**Issue by mjquinlan2000** [elixir-ecto/ecto#3422]
### Environment

* Elixir version (elixir -v): Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
    Elixir 1.10.3 (compiled with Erlang/OTP 22)

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres (PostgreSQL) 11.0
* Ecto version (mix deps): ecto 3.4.6 (Hex package) (mix)
* Database adapter and version (mix deps): postgrex 0.15.5 (Hex package) (mix)
* Operating system: macOS Catalina 10.15.6

### Current behavior

I have a use case for a very dynamic query builder that converts a custom query language I support through an API and it helps to build database queries. I am trying to build a SQL query to do a dynamically built `WHERE table.any_column IN ([SUB SELECT])` statement from the information provided and I am not able to do it with the `dynamic/3` macro.

A very simple way to reproduce this is

```elixir
sub = from(m in MyModel, select: m.foreign_key, where: m.thing == "stuff")
dynamic([q], q.id in subquery(sub))
```

It returns the stacktrace when compiling:

```
== Compilation error in file lib/project/common_query/compiler.ex ==
** (ArgumentError) argument error
    :erlang.length(:acc)
    lib/ecto/query/builder.ex:456: Ecto.Query.Builder.escape_subquery/5
    lib/ecto/query/builder.ex:321: Ecto.Query.Builder.escape/5
    lib/ecto/query/builder/dynamic.ex:14: Ecto.Query.Builder.Dynamic.build/3
    expanding macro: Ecto.Query.dynamic/2
    lib/gigsmart/common_query/compiler.ex:285: MyApp.CommonQuery.Compiler.dynamic_expression_for_definition/3
    (elixir 1.10.3) expanding macro: Kernel.if/2
    lib/gigsmart/common_query/compiler.ex:281: MyApp.CommonQuery.Compiler.dynamic_expression_for_definition/3
```

### Expected behavior

I expect it to be able to handle subqueries. I don't know if this is possible or not so please let me know. 

I'm going to dive into the source code to try and figure it out, but to be honest, this project confuses the hell out of me so I don't know how helpful I can be.

Thank you!

**Comment by mjquinlan2000** [comment]
Thank you @josevalim

**Comment by mjquinlan2000** [comment]
Hi, I'm still seeing an issue with binding variables in the subqueries. If I do this:

```elixir
ids = [1, 2, 3]
query =  from(p in "posts", select: p.id)
sub = from(c in "comments", where: c.user_id in ^ids, select: c.post_id)
dyn = dynamic([q], q.id in subquery(sub))
bound =  where(query, ^dyn)

Ecto.Adapters.SQL.to_sql(:all, Repo, bound)

# iex> {"SELECT p0.\"id\" FROM \"posts\" AS p0 WHERE (p0.\"id\" IN (SELECT sc0.\"post_id\" FROM \"comments\" AS sc0 WHERE (sc0.\"user_id\" = ANY($1))))", []}
```

You can see that the `ids` variable is not present in the list of query parameters passed. The parameters are just an empty list.

**Comment by josevalim** [comment]
@mjquinlan2000 just as a sanity check, does it work if you don't use dynamic?

**Comment by mjquinlan2000** [comment]
Yes so if I do

```elixir
q = from(p in "posts", select: p.id)
ids = [1, 2, 3]
sq = from(c in "comments", where: c.user_id in ^ids, select: c.post_id)
bound = where(q, [q], q.id in subquery(sq))

Ecto.Adapters.SQL.to_sql(:all, Repo, bound)

# iex> {"SELECT p0.\"id\" FROM \"posts\" AS p0 WHERE (p0.\"id\" IN (SELECT sc0.\"post_id\" FROM \"comments\" AS sc0 WHERE (sc0.\"user_id\" = ANY($1))))", [[1, 2, 3]]}

You can see that `ids` is passed as a parameter to the query.
