### ISSUE TITLE
The Pool not being fully available when application starts

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-ecto/ecto#3428]
Please excuse me if this is not considered a bug, or it may be more of a Phoenix issue than Ecto and I am posting in wrong place (I am unsure what's best). It may be even more of a DBConnection issue... or totally our fault because we're doing something wrong.

I have a production Elixir / Phoenix application that is being deployed on Gigalixir that does receive heavy traffic. It's  Phoenix umbrella application, with Ecto being a dependency on one of the apps, and not the user interface Phoenix app itself.

When the app starts, it starts the "db" aplication that has Ecto dependency first, then starts some other apps, and then at the end it starts "ui" app that is a Phoenix user interface.

At the very moment when the "ui" app starts, we are having traffic being redirected to the new pod started on Gigalixir. This pod receives the traffic after "db" and "ui" instances completely started.

But, for several seconds we are seeing hundreds if not thousands of errors like:

```
connection not available and request was dropped from queue after 104ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. By tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allow requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information
```

After something that is usually up to 5 seconds, the errors are gone.

What I think is happening is that "db" app starts Ecto/dbconnection synchronously, and it starts connecting to the database and fills up the pool with newly created connections. But their number is zero or very small at first, and it takes several seconds to fill it up to the levels that the application actually needs.

Now, I have implemented the workaround in the app in a form where I inserted a DyamicSupervisor between the "ui" app supervisor and UI.Endpoint, and I have health check GenServer that starts with the "ui" app and performs some simple SQL quueries at 1s intervals, and only if they succeed instructs the DynamicSupervisor to start the Endpoint.

The question is: is that solution necessary and it's expected thing from programmer to do if they have need to, or should the Phoenix actually wait for the pool of connections to be ready to use when it opens the port? 

### Environment

* Elixir version (elixir -v):
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11
* Ecto version (mix deps): 3.4.6
* Database adapter and version (mix deps): postgrex 0.15.5
* Operating system: Ubuntu Linux 20.04

**Comment by josevalim** [comment]
Postgrex is asynchronous when it connects to the database. So when the repo starts, you may not have a connection yet. If your database is loaded with extensions, this bootstrap time can be high.

My suggestion is to have a single process immediately after Ecto.Repo in the supervision tree that is responsible for checking for the repository availability:

```
defmodule MyApp.Warmup do
  use GenServer

  def start_link(_) do
    GenServer.start_link(__MODULE__, :ok)
  end

  @impl true
  def init(:ok) do
    MyRepo.query("SELECT 1")
    :ignore
  end
end
```

As you said, the query above can fail, so you may want to safe guard that. Probably give it some time or a number of retries and if then does not become available by them, you abort starting it up. There is a good article by Fred about the guarantees you may want to provide: https://ferd.ca/it-s-about-the-guarantees.html

**Comment by hubertlepicki** [comment]
@josevalim that's a very simplistic version of what I came up with, yes. In fact I even do "Select 1" lol. Alright, I'll continue with the approach then. Note: it may not be enough to check for only one successful execution. The app starts 40 connections and does really need them, so the warmup check had to take that into consideration.

**Comment by josevalim** [comment]
@hubertlepicki do you do it 40 times to guarantee all 40 have been warmed up? Could you please share your code? Also, do you really need the DynamicSupervisor? :) 

In any case, I think we should at least talk about this more. I was planning a blog post on Dashbit website about cache warmup and the technique is the same as in here, so I could complement it with this information. Perhaps we deserve a guide in the docs too.

**Comment by hubertlepicki** [comment]
Alright I'll extract it out so it doesn't reference anything internal to the app and post a link for you here to the repo. It may not be today however. Will keep that issue open then?

**Comment by josevalim** [comment]
Oh, so the app starts, but health-check fails. And the proxy only redirects to it once health-check succeeds?

**Comment by hubertlepicki** [comment]
Yes, so the idea is:

- application fully starts but doesn't open the port
- application starts performing health check
- when it starts succeeding the application starts Endpoint and opens up the port
- Gigalixir at this moment starts redirecting traffic to the fully warmed up app

**Comment by josevalim** [comment]
Yeah, so i think you can skip the dynamic supervisor in favor of the GenServer above. Just put it in the tree in a way that blocks only the Endpoint stuff.

**Comment by hubertlepicki** [comment]
@josevalim here is the gist of it ;)

https://gist.github.com/hubertlepicki/8cc78b8167ef738eed9fc10b8ae1dcf3

**Comment by hubertlepicki** [comment]
My main thinking ref. not blocking application startup was, where I may be wrong too, is that it will block graceful shutdown. The app at the same time as starting db / endpoint does connect to cluster and can have processes migrated to it in the meantime already and can hold some state in memory.

I think if the app fully hasn't started, calling Application.stop() on it will also hang and eventually the infrastructure will kill off the pod and it won't be a clean shutdown, meaning there is a chance state in memory can be lost.

It's not like super super important but the supervisor + watchdog tandem was added to handle it.

**Comment by josevalim** [comment]
If the app doesn't boot because of a child error, children in the tree should still be shutdown orderly, so the graceful shutdown should still be in place!

**Comment by hubertlepicki** [comment]
Right, so you are suggesting only blocking the application start up for limited amount of time, several seconds, and give up if it doesn't happen and we were unable to start the Endpoint. That'd make the app not started and Gigalixir will boot new pod that will try the same process from the start. Yes, that could work too, possibly better possibly worse depending on if the time we give it to fully start is always enough and we are not stuck in a boot loop.

On the other hand I can see in my implementation possiblity to never start fully and be in a boot lop if error happens and the polling in genserver I do stops working, But that's fixable too.

**Comment by josevalim** [comment]
Exactly. I think we can close this for now. I will probably have a blog post out in a month or two. Thanks for sharing! <3

**Comment by hubertlepicki** [comment]
Yeah thanks. I need to ponder about the implications of simpler solution. I *think* we'll stay with the current one but have to confirm what's happening if the app is abruptly shut down versus gracefully.
