### ISSUE TITLE
Empty struct being returned from LEFT LATERAL JOIN where I'd expect a nil

### ISSUE THREAD

**Issue by tomtaylor** [elixir-ecto/ecto#3430]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 12.4
* Ecto version (mix deps):
  * ecto: 3.4.6
  * ecto_sql: 3.4.5
* Database adapter and version (mix deps): postgrex 0.15.6
* Operating system: MacOS 10.15.6

### Current behavior

I'm performing this query:

```elixir
    rules_sq =
      from(r in Rule,
        where:
          (r.match_type == "exact" and r.match_string == parent_as(:job_titles).job_title) or
            (r.match_type == "broad" and
               like(parent_as(:job_titles).job_title, fragment("'%' || ? || '%'", r.match_string))),
        order_by: [
          fragment(
            "CASE WHEN ? = ? THEN 0 ELSE levenshtein(?, ?) END ASC",
            r.match_type,
            "exact",
            r.match_string,
            parent_as(:job_titles).job_title
          )
        ],
        limit: 1
      )

    "job_titles"
    |> with_cte("job_titles",
      as:
        fragment(
          "SELECT job_title FROM unnest(?) job_title",
          type(^job_titles, {:array, :string})
        )
    )
    |> from(as: :job_titles)
    |> join(:left_lateral, [jt], subquery(rules_sq))
    |> join(:left, [jt, r], o in Occupation, on: r.occupation_id == o.id)
    |> select([jt, r, o], {jt.job_title, o, r})
    |> Repo.all()
```

The `Rule` schema looks like this:

```elixir
  schema "occupation_matching_rules" do
    field :match_string, :string
    field :occupation_id, :id
    field :match_type, :string
  end
```

The details of the `Occupation` schema are probably irrelevant for this query.

This query works fine when one of the rules matches one of the job titles passed in, resulting in:

```elixir
[{"customer assistant", %Occupation{id: 1, name: "foo", etc...}, %Rule{id: 1, etc...}}]
```

But when one of the job titles doesn't match a rule I get:

```elixir
[{"customer assistant", nil, %Rule{id: nil}}]
```

An empty `Rule` struct is returned.

### Expected behavior

I'd expect to see something more like the below, with a `nil` in place of the empty `Rule` struct.

```elixir
[{"customer assistant", nil, nil}]
```

**Comment by josevalim** [comment]
Thank you for the report! Can you please provide a small application or a failing test case that reproduces the error? We have limited time and I want to make sure our time is spent on fixing the bug rather than reproducing it. Thanks!

**Comment by tomtaylor** [comment]
Sure thing, here's a patch file with a failing integration test attached:

https://gist.github.com/tomtaylor/0f6f18225b518bb2c60b2f10666681cf

**Comment by josevalim** [comment]
Those are the best, thank you! <3

**Comment by tomtaylor** [comment]
Thanks @josevalim!
