### ISSUE TITLE
Unexpected behavior with nested embedded schemas and cast_embed

### ISSUE THREAD

**Issue by rhamorim** [elixir-ecto/ecto#3432]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 22), running on OTP 23
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): embedded schemas, so not dependant on DB; otherwise, PostgreSQL 12
* Ecto version (mix deps): ecto 3.5.0, also happens on 3.4.6
* Database adapter and version (mix deps): again, embedded schemas, so not relevant; but it's postgrex 0.15.6
* Operating system: Linux (Mint 19)

### Current behavior

An example repository showing the described behavior can be found on https://github.com/rhamorim/ecto_weird (instructions on how to reproduce are in the README).

Consider the following embedded schemas:

```elixir
defmodule EctoWeirdWeb.Inner do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :description, :string
    field :value, :string
  end

  def changeset(inner, params \\ %{}) do
    inner
    |> cast(params, [:value])
    |> validate_required([:value])
  end
end

defmodule EctoWeirdWeb.Outer do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :description, :string
    field :value, :string

    embeds_many :items, EctoWeirdWeb.Inner
  end

  def changeset(outer, params \\ %{}) do
    outer
    |> cast(params, [:value])
    |> cast_embed(:items)
    |> validate_required([:value])
  end
end
```

If the changeset is created like this:

```elixir
    params = %{}
    data =
      %Outer{
        description: "Outer changeset",
        items: [
          %Inner{description: "Item 1"},
          %Inner{description: "Item 2"},
          %Inner{description: "Item 3"},
        ]
      }
    changeset = Outer.changeset(data, params)
```

It shows the three items correctly, with the appropriate descriptions.

However, if params is (simulating the submission of a blank form generated from that changeset):
```elixir
%{
  "items" => %{
    "0" => %{"value" => ""},
    "1" => %{"value" => ""},
    "2" => %{"value" => ""}
  },
  "value" => ""
}
```

Then the first item in the item list of the resulting changeset will be item 3, and the other two are nil. First item is also marked with `action: :update`, while the others are `insert`.

By the way, it seems to work as expected if there is only one item.

### Expected behavior

What I expected is that the resulting changeset would have the items with the "pre-filled" data correctly, in the original order. Having the last item show up as the first one was also unexpected; if anything, if this was expected behavior, I'd expect them all to be nil, even though it seems to me that they should show something corresponding to the actual data - which, in the resulting changeset (changeset.data), is correct, even if the nested changesets are not. This odd behavior (IMO) is what prompted me to open the issue.

**Comment by josevalim** [comment]
`cast_embed` works on IDs. This will make it work:

```elixir
params = %{
  "items" => %{
    "0" => %{"id" => "1", "value" => "a"},
    "1" => %{"id" => "2", "value" => "b"},
    "2" => %{"id" => "3", "value" => "c"}
  },
  "value" => ""
}
    data =
      %Outer{
        description: "Outer changeset",
        items: [
          %Inner{id: 1, description: "Item 1"},
          %Inner{id: 2, description: "Item 2"},
          %Inner{id: 3, description: "Item 3"},
        ]
      }
    changeset = Outer.changeset(data, params)
    IO.inspect changeset
```

maybe we can raise an error or improve the behaviour a bit (like discarding all existing keys if they are not nil) but I don't think it will ever work as you expect unless you add IDs.

**Comment by rhamorim** [comment]
I tried with the ids, but not only it requires `on_replace: :delete` on embeds_many to work at all, but also descriptions disappear from the result changeset. I'll submit a branch to the example repository with this version as well.

**Comment by josevalim** [comment]
It doesn’t require on_replace: :delete if you send the same IDs. In any case, cast_assoc is about replacing existing data based on IDs, without them, it won’t work.

**Comment by rhamorim** [comment]
I get exceptions if I try without specifying on_replace, or if on_replace is :update.

```
** (RuntimeError) you are attempting to change relation :items of
EctoWeirdWeb.Outer but the `:on_replace` option of
this relation is set to `:raise`.
```
Is this expected?

**Comment by rhamorim** [comment]
BTW, I checked with other people on the Elixir Discord before bringing the issue here. Other people found it odd.

I created the branch with_ids on the original project I posted in the issue.

**Comment by josevalim** [comment]
The IDs worked fine for me. Make sure the form is sending them, it may not send them if the data was not persisted. It may be best to consider another approach, as cast_assoc is really about replacing existing data.

**Comment by rhamorim** [comment]
I triple checked and the params are exactly equal to what you posted (only different is that values are not filled, which triggers a validation error, which might be related to the behavior I described?):
```elixir
%{
  "items" => %{
    "0" => %{"id" => "1", "value" => ""},
    "1" => %{"id" => "2", "value" => ""},
    "2" => %{"id" => "3", "value" => ""}
  },
  "value" => ""
}
```

So are the items. And I get a runtime exception if the on_replace option is not set, and empty descriptions if it is :delete.

**Comment by josevalim** [comment]
In your example, you can see that the first three are marked as `:replace`, that's because they are scheduled for being replaced (removed in your case). That's because the IDs are not matching. This was a bad copy and paste in my example, make sure they the IDs are all strings.

**Comment by rhamorim** [comment]
Ah, the string IDs did work. I had tried with ids but they were integer ids, and I completely forgot that the default ids in embedded schemas are by default binary. That explains what was going on.

Obrigado pela ajuda!
