### ISSUE TITLE
When upserting on_replace doesn't seem to get called.

### ISSUE THREAD

**Issue by Adzz** [elixir-ecto/ecto#3433]
### Environment

* Elixir version (elixir -v):  Elixir 1.10.2 (compiled with Erlang/OTP 22)
* Ecto version (mix deps): 3.4.6
* Operating system: unix
* Db: postgres 11

### Current behavior

Say I have posts with unique titles. If I have an existing post with comments, I know I can do this:

```elixir
Repo.get_by(Post, title: "a unique title)
|> Repo.preload([:comments])
|> Ecto.Changeset.cast(%{title: "another one"}, [:title])
|> Ecto.Changeset.put_assoc(:comments, [])
|> Repo.update!
```
And the `on_replace` will be triggered for comments. But when I try the same thing with an upsert it doesn't seem to work:

```elixir
%Post{}
|> Ecto.Changeset.cast(%{title: "a unique title"}, [:title])
|> Ecto.Changeset.put_assoc(:comments, [])
|> Repo.insert(
  on_conflict: {:replace_all_except, [:id]},
  conflict_target: [:title],
  returning: true
)
```
In that case, on_replace is not triggered, even though the change is in the changeset. Nothing is replaced.

### Expected behavior

I think I would expect the comments to be replaced when I upsert with whatever put_assoc put into the changeset.

**Comment by josevalim** [comment]
Correct and there isn’t much we can do. put_assoc works by comparing data in memory, in this case, we don’t have a before to compare and know we can delete data. You will have to model this differently, using transactions or so to clear the data based on the upsert results.

**Comment by Adzz** [comment]
What happens to the data in this case then, are the associations put there via put_assoc just ignored? I'm wondering if a warning would be useful as it seems to silently work, until you check the results. 

Or could we make it so that in this case whatever relations are in the changeset fully replace whatever is in the db? I.e. force on_replace to trigger.

**Comment by josevalim** [comment]
They are not ignored. If you had put_assoc, then you would have the data from before and after, assuming the ID is the same - which could be a legitimate use case too, it just isn't the use case you desire in this occasion.
