### ISSUE TITLE
belongs_to with Ecto.ParameterizedType

### ISSUE THREAD

**Issue by elielhaouzi** [elixir-ecto/ecto#3434]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 
* Ecto version (mix deps): 3.5
* Database adapter and version (mix deps): postgrex
* Operating system: ubuntu

### Current behavior

```elixir
  defmodule MyParameterizedType do
    use Ecto.ParameterizedType

    def params(embed), do: %{embed: embed}
    def init([some_opt: :some_opt_value, field: :my_type, schema: _]), do: :init
    def type(_), do: :id
    def load(_, _, _), do: {:ok, :load}
    def dump( _, _, _),  do: {:ok, :dump}
    def cast( _, _),  do: {:ok, :cast}
    def equal?(true, _, _), do: true
    def equal?(_, _, _), do: false
    def embed_as(_, %{embed: embed}), do: embed
  end

  defmodule Schema1 do
    use Ecto.Schema

    @primary_key {:id, MyParameterizedType, some_opt: :some_opt_value, autogenerate: true}
    schema "" do
    end
  end

  defmodule Schema2 do
    use Ecto.Schema

    schema "" do
      belongs_to(:schema_1, Schema1, type: MyParameterizedType, some_opt: :some_opt_value)
    end
  end
```
(ArgumentError) invalid option :some_opt for belongs_to/3

In principle, the code support the parameterized type and init it right with the options received ([here](https://github.com/elixir-ecto/ecto/blob/v3.5.0/lib/ecto/schema.ex#L2086)) the problem is the belongs_to function limit the options to its keywords ([here](https://github.com/elixir-ecto/ecto/blob/v3.5.0/lib/ecto/schema.ex#L1881)) via the `@valid_belongs_to_options`

**Comment by elielhaouzi** [comment]
After reflexion, the problem with my solution is that we need to re-write in the belonged field all the options. 
Maybe is it a way to get the options of the `related_key` via the the `related` module ?
The question is is there a way to get the `related` module attribute from the current module ?

**Comment by josevalim** [comment]
In this case, it is better for you to manually define the field and pass `define_field: false` to `belongs_to`. Although I would be careful with using both belongs_to and parameterized types, as each of those may make different assumptions about how the type should behave.
