### ISSUE TITLE
Inconsistent timestamp type returned when selected from subquery

### ISSUE THREAD

**Issue by validere-ben** [elixir-ecto/ecto#3438]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.6
* Ecto version (mix deps): 3.5.0
* Database adapter and version (mix deps):  postgrex 0.15.6
* Operating system: macOS 10.15.6

### Current behavior

As of 3.5.0 it appears that the timestamp type of the source Schema in a subquery is not respected when selected explicitly.

i.e.

```elixir
# in user Ecto Schema and migration
# timestamps(type: :utc_datetime_usec)

base_query = User

Repo.one(
  from(u in subquery(base_query),
    select: u.updated_at
  )
)
# returns a `NaiveDateTime`

# returns `DateTime` when a subquery is not used i.e. `from u in User, select: u.updated_at`
# returns `DateTime` in timestamp fields without an explicit select i.e. `from u in subquey(base_query)`
```

I have reproduced the behaviour in a minimal application here: https://github.com/validere-ben/subquery_bug

Included is also an example of inconsistencies in query behaviour when comparing a `binary_id` schema field from a subquery to a `t:String.t/0` between 3.4.3 and 3.5.0 (same issue?)

### Expected behavior
The field types should respect the subquery source schema field type (`:utc_datetime_usec` in the above example)

**Comment by josevalim** [comment]
Awesome find @validere-ben! I will take a look at this tomorrow (latest). :)

**Comment by josevalim** [comment]
v3.5.1 is out!
