### ISSUE TITLE
`limit: 1` + `order_by` is returning '\n'

### ISSUE THREAD

**Issue by bruno-b-martins** [elixir-ecto/ecto#3447]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.4 (compiled with Erlang/OTP 23)
```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
```
SELECT version();
PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```
* Ecto version (mix deps): `"ecto": {:hex, :ecto, "3.5.1", ...`
* Database adapter and version (mix deps): `"postgrex": {:hex, :postgrex, "0.15.6", ...`
* Operating system: macOS Catalina v10.15.7

### Current behavior

I have a query which returns me a `'\n'` when I revert its' `order_by` and `limit: 1`.

Example query:
```
iex(17)> from(r in Review, where: r.restaurant_id == 1, order_by: [asc: :rating, desc: :id], select: r.id) |> Repo.all             
[debug] QUERY OK source="reviews" db=3.8ms decode=0.5ms queue=4.6ms idle=1432.1ms
SELECT r0."id" FROM "reviews" AS r0 WHERE (r0."restaurant_id" = 1) ORDER BY r0."rating", r0."id" DESC []
[6, 1, 7, 2, 16, 15, 14, 13, 12, 11, 8, 3, 9, 4, 10, 5]
```

Same query with `limit: 1`:
```
iex(18)> from(r in Review, where: r.restaurant_id == 1, order_by: [asc: :rating, desc: :id], select: r.id, limit: 1) |> Repo.all
[debug] QUERY OK source="reviews" db=8.4ms idle=1996.8ms
SELECT r0."id" FROM "reviews" AS r0 WHERE (r0."restaurant_id" = 1) ORDER BY r0."rating", r0."id" DESC LIMIT 1 []
[6]
```

Same query with reverted `order_by`:
```
iex(19)> from(r in Review, where: r.restaurant_id == 1, order_by: [desc: :rating, desc: :id], select: r.id) |> Repo.all          
[debug] QUERY OK source="reviews" db=8.1ms idle=1671.5ms
SELECT r0."id" FROM "reviews" AS r0 WHERE (r0."restaurant_id" = 1) ORDER BY r0."rating" DESC, r0."id" DESC []
[10, 5, 9, 4, 16, 15, 14, 13, 12, 11, 8, 3, 7, 2, 6, 1]
```

Same query with `limit: 1` and reverted `order_by`:
```
iex(20)> from(r in Review, where: r.restaurant_id == 1, order_by: [desc: :rating, desc: :id], select: r.id, limit: 1) |> Repo.all
[debug] QUERY OK source="reviews" db=5.0ms idle=1823.1ms
SELECT r0."id" FROM "reviews" AS r0 WHERE (r0."restaurant_id" = 1) ORDER BY r0."rating" DESC, r0."id" DESC LIMIT 1 []
'\n'
```

### Expected behavior

I was expecting to have `[10]` in the last query.

### Additional info

I was able to reproduce this in a similar query in both directions when applying the `limit: 1`.

```
iex(21)> from(r in Restaurant, order_by: [asc: :average_rating, desc: :id], select: r.id) |> Repo.all                            
[debug] QUERY OK source="restaurants" db=12.1ms idle=1077.0ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating", r0."id" DESC []
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

iex(22)> from(r in Restaurant, order_by: [desc: :average_rating, desc: :id], select: r.id) |> Repo.all
[debug] QUERY OK source="restaurants" db=4.1ms queue=4.2ms idle=1686.5ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating" DESC, r0."id" DESC []
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

iex(23)> from(r in Restaurant, order_by: [asc: :average_rating, desc: :id], select: r.id, limit: 1) |> Repo.all
[debug] QUERY OK source="restaurants" db=7.2ms idle=1923.7ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating", r0."id" DESC LIMIT 1 []
'\n'

iex(24)> from(r in Restaurant, order_by: [desc: :average_rating, desc: :id], select: r.id, limit: 1) |> Repo.all
[debug] QUERY OK source="restaurants" db=5.9ms idle=1786.1ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating" DESC, r0."id" DESC LIMIT 1 []
'\n'
```

Please let me know if I can help somehow.

**Comment by bruno-b-martins** [comment]
I played around a bit more with the query in the Additional info section of the issue and got the following which might help debug the issue:
```
iex(28)> from(r in Restaurant, order_by: [desc: :average_rating, desc: :id], select: r.id, limit: 4) |> Repo.all
[debug] QUERY OK source="restaurants" db=3.2ms queue=6.4ms idle=1372.2ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating" DESC, r0."id" DESC LIMIT 4 []
'\n\t\b\a'

iex(29)> from(r in Restaurant, order_by: [desc: :average_rating, desc: :id], select: r.id, limit: 5) |> Repo.all
[debug] QUERY OK source="restaurants" db=3.2ms queue=7.5ms idle=1595.1ms
SELECT r0."id" FROM "restaurants" AS r0 ORDER BY r0."average_rating" DESC, r0."id" DESC LIMIT 5 []
[10, 9, 8, 7, 6]
```

**Comment by Eiji7** [comment]
@bruno-b-martins Everything works as expected. Please remember that not every `Elixir` term is inspected in `raw` mode. This is made like that to improve readability.

`List` of **positive** integers where each integer is code point of a printable character is called `charlist`. This works similar to keywords for example:
```elixir
[key: :value]
```
as "raw" `Elixir` term is:
```elixir
[{:key, :value}]
```
Look that extra `Tuple` notation decreases readability.

With `charlist` you may want to write for example:
```elixir
'bruno-b-martins'
```
which is:
```elixir
[98, 114, 117, 110, 111, 45, 98, 45, 109, 97, 114, 116, 105, 110, 115]
```

Obviously there is no "ultimate" solution to magically detect the source of data or what developer have in mind, so we simply apply those rules on every case even if that would be a list of ids returned from `Ecto` query.

Please try:
```elixir
iex> i 'bruno-b-martins'
iex> IO.inspect('bruno-b-martins', charlists: :as_lists)
iex> h Inspect.Opts
```

Also please use `Elixir` official forum for asking questions:
https://elixirforum.com/

**Comment by bruno-b-martins** [comment]
Thanks for clarifying @Eiji7.

Still, I raise the question, if we're querying ids which are of type `:id`, can you please explain me why do we receive a list of chars and not a list of ids?
Is there a way to cast to integer the result of the query in the `select` option for example?

My use case is that I'm looking for the best and worst records based on an integer column and storing those `ids` in a separate record.
Since I'm doing that in 2 steps (first get the ids then update the other record) having these `charList` instead of `id` is a bit bothersome.

Finally, I'm sorry if I posted this in the wrong place. I've searched the forum, google and github for this and couldn't find anything conclusive (probably search with the wrong keywords). Therefore, I really thought it was some nasty bug.

**Comment by Eiji7** [comment]
@bruno-b-martins 

> Still, I raise the question, if we're querying ids which are of type :id, can you please explain me why do we receive a list of chars and not a list of ids?

In `Elixir` we don't have anything like `:id`. `ID` is a `PostgreSQL` builtin type which by `ecto` is translated from and to `integer`.

> Is there a way to cast the result of the query to integer? In the select option for example...

Please use `MyApp.Repo.one/1` instead of `MyApp.Repo.all/1`. If for some reason you still needs a list you have many ways of fetching a first element regardless if it's normal list, charlist or keyword - all of them in `raw` representations are just lists.

> Since I'm doing that in 2 steps (first get the ids then update the other record) having these charList instead of id is a bit bothersome because my changeset becomes invalid saying that '\n' is not an :id.

That's because you are trying to `cast` **list of integers** (with 1 element) into `ID`. You need to `cast` **integer** instead.

> Finally, I'm sorry if I posted this in the wrong place. I've searched the forum, google and github for this and couldn't find anything conclusive (probably searched with the wrong keywords). Therefore, I really thought it was some nasty bug.

There are many topics about this. Anyway new `Elixir` developers should firstly write a topic on `forum`. Don't worry even I sometimes don't know if something is a bug/expected or not. Feel free to ask. We prefer questions on forum to avoid mess of mixed bug reports and help questions in one place.

Useful resources:
https://elixirforum.com/t/elixirs-biggest-gotchas/796?u=eiji
https://elixirforum.com/t/is-there-a-way-to-inspect-a-list-of-integers-without-accidentally-ending-up-with-a-charlist/26504?u=eiji
https://elixirforum.com/t/how-to-use-a-list-with-non-negative-integers-without-making-it-a-charlist/26082?u=eiji
https://elixirforum.com/t/weird-behaviour-of-enum-chunk-every/24485?u=eiji
https://elixirforum.com/t/unexpected-keyword-merge-behavior-elixir-1-9-4/27596?u=eiji
https://elixirforum.com/t/keyword-get-values-performing-ascii-translation-on-values-for-certain-numbers/31506?u=eiji
https://elixirforum.com/t/list-decoding/23120?u=eiji
https://elixirforum.com/t/why-does-io-inspect-print-escape-characters/10077?u=eiji

and many more …

**Comment by bruno-b-martins** [comment]
Thanks for explaining all this.
I'm closing the issue now.
