### ISSUE TITLE
Ecto 3.5.2 seems backward incompatible with 3.5.0 and 3.5.1.

### ISSUE THREAD

**Issue by hickscorp** [elixir-ecto/ecto#3448]
### Environment

* Elixir version: Erlang/OTP 22 with Elixir 1.10.4.
* Ecto version: 3.5.2, regression from 3.5.0 and 3.5.1.

### Current behavior

When `ecto_poly` tries to call `dump/3` with a first argument being `{:embed, %Ecto.Embedded{...}}`, Ecto doesn't match anymore.

### Expected behavior

Ecto should match the same as it was in 3.5.0 or 3.5.1.
Alternatively, there should be a clear path for the developer to understand how the cast of the `{:embed, ...}` tuple that used to work with `3.5.0 / 3.5.1` should be migrated.

EDIT1: Original issue with `ecto_poly` here: https://github.com/greenboxal/ecto_poly/issues/4
EDIT2: A kind user on the Elixir Slack pointed out that the breakage was for sure since 3.5 - and they're right - we updated from 3.4.6, not 3.5.x. I think the function being called is an internal function so it is OK for it to have changed. I'm closing this issue as I thought a public function part of Ecto's API had changed. Sorry!

**Comment by josevalim** [comment]
Yes, I think they were using a private functionality. Ecto.Type is public but the `{:embed, _}` type is not publicly documented. :)

**Comment by hickscorp** [comment]
Yes, my bad really @josevalim for the noise. It seems that the `:parameterized` new way is designed to allow libraries to do this kind of things, so I'm reassured that it won't break as easily, or at least that it will have workarounds. Now I'll just try to amend `ecto_poly` so that it checks the version of Ecto and chooses accordingly which version of the function to call.

Thanks for the help!
