### ISSUE TITLE
Support same-named joins of different ecto schema's with the same base tables.

### ISSUE THREAD

**Issue by erlandsona** [elixir-ecto/ecto#3450]
Sorry to necro bump, but curious if this has been implemented since 2018? https://github.com/elixir-ecto/ecto/issues/2389#issuecomment-379813551

# The Problem

Currently I've got a use case where we point multiple Ecto schemas at the same underlying base table (100+ column table) as a simple pre-refactoring to enable us to write server code referencing nicer 'model' names and smaller subsections of the underlying data but when we join the ecto schemas together the output SQL shows the same table being joined on itself multiple times. Which if you're writing a heavy query with any more than I believe the default 8 joins then the developer has to be aware of the JOIN order w/ resp. to query performance.
https://www.postgresql.org/docs/8.3/runtime-config-query.html#GUC-JOIN-COLLAPSE-LIMIT

# Solution

That said, in my case given the schema's all point to the same underlying table and I'm not using any specific ON clauses in any of them EG: `join: info_table in assoc(base, :info)` 
I'd like to be able to alias each of the joins with the same `as: :info` and have the underlying ecto NOT spit out duplicate joins.

This actually leads to a 10x performance increase in my particular use case.

Happy to be totally missing something too!

**Comment by fuelen** [comment]
Maybe `Ecto.Query.has_named_binding/2` can help you? With this function you can join a table only if it is not joined yet.

**Comment by erlandsona** [comment]
@fuelen unfortunately no... the issue isn't whether the binding already exists... it's that I've got separate ecto schemas that point to different properties on the same table so when I join them in an ecto query it spits out SQL that joins the same base table.
Today, if I try to `as: :common` on multiple joins with the same underlying base table it won't compile. This is the current expected behavior if I'm not mistaken, although I hope I am.

It seems like this was flushed out in the issue I referenced but ultimately left unimplemented.
But that was almost two years ago so wanted to check in to see if I missed something.

**Comment by josevalim** [comment]
Can you please provide an example of the Ecto query you want to write and the SQL you want to be emitted.

**Comment by erlandsona** [comment]
Here's what I want to be able to write
```
    from(user in User,
      where: user.id == ^user_id,
      join: user_info in assoc(user, :info),
      as: :info,
      join: more_user_info in assoc(user, :more_info),
      as: :info,
      join: demographics in assoc(user, :demographics),
      as: :info
```

Currently this doesn't compile and throws on the `as: :info` but the base tables for each of the assocs is for example `mycompany.user`
And the SQL output without `as: ` merging is something like the following...

```
FROM "mycompany"."user" AS u0
          INNER JOIN "mycompany"."user" AS u1 ON u1."id" = u0."id"
          INNER JOIN "mycompany"."user" AS u2 ON u2."id" = u0."id"
```

Where the actual base table has all of the properties and the performance of this query is dramatically improved by removing the extra joins.
I would expect the ecto to spit out something along the lines of

```
FROM "mycompany"."user" AS u0
```

But I realize this might not be a reasonable request just from what I read in the other issue chain.

**Comment by josevalim** [comment]
I have to ask: why are you using joins in the first place then? :) I don't think it would be logical for Ecto to simply disappear with a `join` that you wrote because you used the same alias. In fact, it is more likely for that to cause bugs (even security issues perhaps) then to be a feature.

We try to keep as close to SQL as possible and having this kind of behaviour would be very counter intuitive to me.

**Comment by erlandsona** [comment]
So the only alternative is to add the properties being accessed on each of the intermediary representations to the base ecto schema just to avoid ecto spitting out multiple joins or pay the cost of refactoring the underlying table into multiple tables (which is on the docket, we just haven't been able to prioritize it cause it's a pretty big structural change affecting lots of dependent db code :/)
Fortunately it's not the end of the world but was hoping there was something simple I could do on the ecto side to fix the performance issue related to this table being joined to itself a bunch :/
🤷‍♂️ I guess.

**Comment by josevalim** [comment]
>  just to avoid ecto spitting out multiple joins

To be fair, Ecto is only doing what you are asking it to do. Note you can bypass the schema if you want and access the raw table by doing: `from u in "my_table"` and that will give access to all fields. You can also define a schema with all fields. Those can be temporary solutions for those expensive queries but ultimately it sounds like a design issue that you shouldn't really expect Ecto to fix for you.

**Comment by erlandsona** [comment]
Ah I forgot about the raw table thing! Yah that'd do it! And you're definitely right about expecting Ecto to fix the DB schema issues. We're working though it slowly but surely.
