### ISSUE TITLE
Guides for implementing an Ecto adapter

### ISSUE THREAD

**Issue by dunyakirkali** [elixir-ecto/ecto#3454]
Hi,

I have a several DB clients (for Google Firestore and Google Spanner) for which I'd like to create an ecto adapter.

I have been looking around for some guides and managed to find very little info. on how to build an ecto adapter ground up.

Could someone help me get my hands on some instructions, some best practices, etc?

Any help would be much appreciated

**Comment by josevalim** [comment]
Unfortunately we don’t have any guides and there is no plan at the moment. The best you can do is to look at the existing adapters and use that as a starting point. The etso adapter is relatively small, so it can be a good starting point.

However, I make myself available to answer any questions. I will close this, but feel free to post further comments here and I will reply. Also feel free to reach me on IRC.
