### ISSUE TITLE
Transaction connection fails if Repo.insert fails

### ISSUE THREAD

**Issue by Adzz** [elixir-ecto/ecto#3455]
### Environment

* Elixir version (elixir -v): 1.10
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11
* Ecto version (mix deps): 3.5.2
* Database adapter and version (mix deps): Postgrex 0.15.6
* Operating system: unix

### Current behavior

If I do this:
```elixir
Repo.transaction(fn -> 
  Ecto.Changeset.change(%MySchema{}, %{name: "1"})
  |> Ecto.Changeset.unique_constraint(:name)
  |> Repo.insert()

  Ecto.Changeset.change(%MySchema{}, %{name: "1"})
  |> Ecto.Changeset.unique_constraint(:name)
  |> Repo.insert()

  Ecto.Changeset.change(%MySchema{}, %{name: "2"})
  |> Repo.insert()
end)
```
I get:
```
ERROR 25P02 (in_failed_sql_transaction) current transaction is aborted, commands ignored until end of transaction block
```
Because the second insert fails the transaction seems to abort.

The docs for `transaction/1` say 
> If an unhandled error occurs the transaction will be rolled back and the error will bubble up from the transaction function

But to my mind I've handled the exception by using `unique_constraint/3`

### Expected behaviour

I'm sure there is a good reason this happens, but I'm iterating through a list of inserts I need to be able to not worry about ones that fail the constraint and continue with the rest.

**Comment by josevalim** [comment]
There is nothing we can do here, this is literally database behaviour that Ecto is just surfacing up. If one insert fails, all other operations in there will fail too. If you really want to ignore the unique constraint, then you need to use `on_conflict` and let the database know of your intentions.
