### ISSUE TITLE
Issue in guide / mismatch between migrating automatic primary key vs. custom one.

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#3459]
The following instructions doesn't seem to create the same instructions

https://github.com/elixir-ecto/ecto/blob/923dfd85bd7ad0b8fd1fafaa3e59abe96534cef8/guides/howtos/Multi%20tenancy%20with%20foreign%20keys.md#L145-L146

as

```elixir
create table(:orgs) do 
```

would do with the primary key column being named `:id`. It doesn't seem to set the needed default of an integer sequence in postgres and the type doesn't match as well `bigint` vs. `integer`. Therefore one does get the following errors when creating an organization:

```
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "org_id" violates not-null constraint

    table: orgs
    column: org_id
```

I'm not sure exactly if this is an issue with ecto/ecto_sql or just some missing instructions for setting up the default.

**Comment by josevalim** [comment]
You are correct, type should be "bigserial". Fix incoming.
