### ISSUE TITLE
prepare_query guide breaks migrations

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#3460]
https://github.com/elixir-ecto/ecto/blob/923dfd85bd7ad0b8fd1fafaa3e59abe96534cef8/guides/howtos/Multi%20tenancy%20with%20foreign%20keys.md

The documented way of implementing `prepare_query` affects migrations including queries for "schema_migrations. This therefore breaks all the ecto mix tasks for managing migrations.

**Comment by josevalim** [comment]
I have changed ecto_sql so it passes `schema_migration: true` as an option, so now we can check it. Please see changes on 8d26706. Note you will need EctoSQL from the v3.5 branch. Can you please give it a try and let me know? If it works I will release a new ecto_sql version. Thanks!

**Comment by LostKobrakai** [comment]
Seems to work fine with the new opts value being available.

**Comment by josevalim** [comment]
ecto_sql 3.5.3 is out.
