### ISSUE TITLE
Ecto.Enum in embedded schema can't load nil correctly

### ISSUE THREAD

**Issue by smartepsh** [elixir-ecto/ecto#3466]
### Environment

* Elixir version (elixir -v): Elixir 1.11.1 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgresql: stable 13.0 (bottled), HEAD
* Ecto version (mix deps): 3.5.4
* Database adapter and version (mix deps): postgrex 0.15.6
* Operating system: macOS Catalina

### Current behavior

If the value of enum field in embedded schema is null, it will raise `ArgumentError` when I load data.

```elixir
** (ArgumentError) cannot load `nil` as type {:parameterized, Ecto.Enum, ......} for field `xxx` in schema
``` 

But it works fine in normal schema.

### Expected behavior

Load `nil` correctly in embedded schema.

**Comment by v0idpwn** [comment]
Hi, @smartepsh. I tried to reproduce this [in this patch](https://gist.github.com/v0idpwn/bf96155e243f70ee2320d50e34bda109), but wasn't able to. Could you provide more info?

**Comment by smartepsh** [comment]
@v0idpwn I wrote a [sample project](https://github.com/smartepsh/ecto_bug) that can raise normally.
