### ISSUE TITLE
prepare_query/3 for Repo.one()

### ISSUE THREAD

**Issue by dbi1** [elixir-ecto/ecto#3469]
Hello,

I just noticed that `prepare_query/3` does not support `Repo.one()`.

Is there a reason for this? Is this something that could be supported?

Thank you for your very valuable work on Ecto!

**Comment by josevalim** [comment]
Hi @dbi1. prepare_query should definitely be invoked for `Repo.one`. Can you please tell us why you think it does not and provide a way to reproduce the issue alongside your Ecto versions? Thank you!

**Comment by josevalim** [comment]
Just tried this locally:

```
defmodule Bytepack.Repo do
  use Ecto.Repo,
    otp_app: :bytepack,
    adapter: Ecto.Adapters.Postgres

  def prepare_query(op, query, opts) do
    IO.inspect {op, query, opts}
    {query, opts}
  end
end


```
iex(1)> Bytepack.Repo.one Bytepack.Accounts.User
{:all, #Ecto.Query<from u0 in Bytepack.Accounts.User, select: u0>, []}
```

So it is working, please make sure you are on latest. :)

**Comment by dbi1** [comment]
Ah, great, thanks :)

My question came from reading the [documentation](https://github.com/elixir-ecto/ecto/blob/v3.5.4/lib/ecto/repo.ex#L934), and seeing this:

"when operation: :all | :update_all | :delete_all | :stream"

I assumed there was a limit to which Repo.xxx operations were allowed for `prepare_query/3`.

Would it be reasonable to assume that `prepare_query/3` should work with all Repo.xxx operations that take a queryable as the first argument?

**Comment by dbi1** [comment]
Hmm, I guess I misunderstood, my apologies.

Further down it says: "This callback is invoked for all query APIs, including the stream function, but it is not invoked for insert_all nor any of the schema functions."

**Comment by josevalim** [comment]
`Repo.one` is ultimately a `Repo.all`. perhaps it is more intuitive to think about :all being the same as SELECT. :)

**Comment by dbi1** [comment]
Ah, got it, thanks for the patient explanation :)
