### ISSUE TITLE
ArgumentError: only virtual fields can have type :any

### ISSUE THREAD

**Issue by azizk** [elixir-ecto/ecto#3474]
Hi!

I curiously couldn't find a bug report or a post on elixirforum.com regarding this. Guess I'm the first to encounter the issue.

### Environment

* Elixir version: 1.11.0
* Database and version: PostgreSQL 12
* Ecto version: 3.5.4
* Database adapter and version (mix deps): 0.15.7
* Operating system: Docker image hexpm/elixir:1.11.0-erlang-23.1.1-alpine-3.12.0

### Current behavior

This used to work with ecto 3.4.6:

```elixir
defmodule MyApp.Thing do
  use Ecto.Schema

  schema "things" do
    # jpath is a :jsonb column
    field :jpath, {:array, :any}
  end
end
```
But now it raises an ArgumentError:
```
** (ArgumentError) only virtual fields can have type :any, invalid type for field :jpath
    (ecto 3.5.4) lib/ecto/schema.ex:2079: Ecto.Schema.check_field_type!/4
    (ecto 3.5.4) lib/ecto/schema.ex:2084: Ecto.Schema.check_field_type!/4
    (ecto 3.5.4) lib/ecto/schema.ex:1796: Ecto.Schema.__field__/4
    lib/myapp/things.ex:6: (module)
```
I think it's because of the `composite?(type, name)` condition where the type is unpacked and `check_field_type!/4` is called recursively.
### Expected behavior
It should compile and be able to cast the value to an array of JSON values.
If this error should remain even if it's a composite then I'm not sure how to accomplish this easily. I'd have to write a parametrized type maybe.

**Comment by josevalim** [comment]
We should address this. Could you please submit a PR?

**Comment by azizk** [comment]
Sure thing. My idea atm would be the following:
```elixir
      type == :any and !opts[:virtual] and !opts[:composite?] ->
        raise ArgumentError, "only virtual fields can have type :any, " <>
                             "invalid type for field #{inspect name}"

      composite?(type, name) ->
        {outer_type, inner_type} = type
        opts = put_in(opts[:composite?], true)
        {outer_type, check_field_type!(mod, name, inner_type, opts)}
```

**Comment by azizk** [comment]
I'm wondering something. Why is `:any` not allowed as a type for non-virtual fields? How would you define a field that can have any value if it's a `:jsonb` column?

**Comment by josevalim** [comment]
@azizk you would need a custom type for that, which is fine, it is not very common.

Regarding the fix, it is probably simpler to move the `type == :any and !opts[:virtual]` check to the `__field__` function.

**Comment by v0idpwn** [comment]
I believe :any is allowed in virtual only because they may be not be able to be encoded. For instance, %MyStruct{} is accepted in :any, but if you try to encode it to store on a jsonb, you'll get a runtime error unless it implements an encoding protocol.

**Comment by v0idpwn** [comment]
If you want something like that, I'd go for a parameterized type for `serializable'.

**Comment by azizk** [comment]
@v0idpwn That sounds reasonable, however consider that you will still be able to do that once we fix this bug. So with my example schema you would be able to assign a non-serializable value in an array to `jpath` and the Ecto changeset would be valid. It would only fail when it's time to encode I think.
