### ISSUE TITLE
(BadMapError) expected a map, got: nil

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3477]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version: PostgreSQL 11.8
* Ecto version (mix deps):   ecto 3.5.4,  ecto_sql 3.5.3
* Database adapter and version (mix deps): postgrex 0.15.7
* Operating system: Linux

### Current behavior
After updating
```
  ecto 3.4.6 => 3.5.5
  ecto_sql 3.4.5 => 3.5.3
```
one of my queries now raises an error
```
** (BadMapError) expected a map, got: nil
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:391: anonymous fn/2 in Ecto.Repo.Queryable.process_update/5
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:391: Ecto.Repo.Queryable.process_update/5
    (elixir 1.10.4) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.10.4) lib/enum.ex:1520: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3 
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:372: Ecto.Repo.Queryable.process/4
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:283: anonymous fn/3 in Ecto.Repo.Queryable.postprocessor/4
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:235: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```
simplified query sample:
```elixir
query = from p in Profile,
          left_join: u in assoc(p, :user),
          select: {p.id, %{u | email: p.email}},
          where: p.id == ^"332e9c25-2266-4a01-aac4-942625cfbea8",
          limit: 1
query |> Repo.all()
```
This error raises when there is no record in joined table.

### Expected behavior
previous version of Ecto returns `[{"some profile id", %User{id: nil, email: "some email"}}]`

**Comment by fuelen** [comment]
@josevalim now my query returns `[{"some profile id", nil}]` instead of `[{"some profile id", %User{id: nil, email: "some email"}}]`.
To solve my issue I have to explicitly write all fields
```elixir
query = from p in Profile,
          left_join: u in assoc(p, :user),
          select: {p.id, %User{id: u.id, email: p.email, field_a: u.field_a, field_b: u.field_b}},
          where: p.id == ^"332e9c25-2266-4a01-aac4-942625cfbea8",
          limit: 1
```
Is this expected design?

**Comment by josevalim** [comment]
I see. Then I am not sure if there is something we can do about it. You can see the original issue that made us return nil: #3430 and I agree with the conclusion of that issue. I will revert master and you will have to merge the e-mail in a separate pass after the query.
