### ISSUE TITLE
Ecto Result Command in Telemetry

### ISSUE THREAD

**Issue by UnderFenex** [elixir-ecto/ecto#3484]
Hi, it seems that ecto: does not include the command parameter un the result atom when using telemetry according to this article https://elixirschool.com/blog/instrumenting_phoenix_with_telemetry_part_three/:

```
def metrics do
  [
    summary(
      "quantum.repo.query.total_time",
      unit: {:native, :millisecond},
      tag_values: &__MODULE__.query_metadata/1,
      tags: [:source, :command]
    )
  ]
end

def query_metadata(%{source: source, result: {_, %{command: command}}}) do
  %{source: source, command: command}
end
```

I am currently using:
```
      {:phoenix_ecto, "~> 4.1"},
      {:ecto_sql, "~> 3.4"},
      {:myxql, ">= 0.0.0"},
```

**Comment by josevalim** [comment]
The parameter will be in the metadata. You can see it in the logs and the logs are using the same metadata to log.

**Comment by UnderFenex** [comment]
Hi @josevalim using the Telemetry.Metrics.ConsoleReporter, I'm no able to see the command value, nor in the metadata, nor anywhere. Could it be because I'm using the MyXQL connector?

**Comment by josevalim** [comment]
Here is the metadata: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L892-L900

make sure you have all the correct keys :)

**Comment by UnderFenex** [comment]
Yes, I get the keys, however it seems that the command (INSERT, UPDATE, DELETE) is not provided anymore. 
Thnx!
