### ISSUE TITLE
`Ecto.Multi.insert_all/5` doesn't autogenerate UUID

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3486]
### Environment

* Elixir version (elixir -v): 1.10.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12
* Ecto version (mix deps): 3.1
* Database adapter and version (mix deps): 0.15.7
* Operating system: Windows 10

### Current behavior

**This will work:**

```
Repo.insert!(
  %Vote{
    user_id: user_id,
    input_id: hd(input_ids)
  },
  prefix: Triplex.to_prefix(tenant)
)
```

Query generated:
> INSERT INTO "localhost"."votes" ("input_id","user_id","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5)

**This won't:**

```
new_votes =
 [
   %{
     input_id: "2c92c315-b81f-413e-8014-b7a0ab2038a6",
     user_id: "2dd65dcd-9741-4075-943c-c372c8a2ae97"
   }
 ]

Ecto.Multi.new()
|> Ecto.Multi.delete_all(:delete_votes, delete_votes_query, prefix: Triplex.to_prefix(tenant))
|> Ecto.Multi.insert_all(:insert_all, Vote, new_votes, prefix: Triplex.to_prefix(tenant))
|> Repo.transaction()
```

Error:

> ** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "id" violates not-null constraint
     table: votes
     column: id

Query generated:
> INSERT INTO "localhost"."votes" ("input_id","user_id") VALUES ($1,$2)

I do not understand why `Ecto.Multi.insert_all` doesn't generate `id` column like `Repo.insert!` does.

In the `Vote` schema we have:
`@primary_key {:id, Ecto.UUID, autogenerate: true}`

### Expected behavior

Expecting the ID to generate.

**Comment by josevalim** [comment]
This is by design. `insert_all` won't generate ID or timestamps, as it is meant to be low-level. The docs are clearer about this regarding timestamps but not UUID, I will make it clearer. You can call Ecto.UUID.generate or similar. Thanks!

**Comment by thojanssens** [comment]
Should I generate IDs and timestamps and use `insert_all`, or rather iterate over the "votes" and insert them one by one with `Repo.insert`?

Both have drawbacks, not sure which is best. Which way would you recommend?

**Comment by thojanssens** [comment]
But jose see in `Repo.insert_all` docs:

> When a schema module is given, the entries given will be properly dumped before being sent to the database. If the schema contains an autogenerated ID field, it will be handled either at the adapter or the storage layer. However any other autogenerated value, like timestamps, won't be autogenerated when using insert_all/3.

`autogenerate` is set to `true`. Doesn't that contradict what you said for the ID?

**Comment by josevalim** [comment]
Please see updated docs. It only applies to the ones generated by the database/adapter and Ecto.UUID isn’t.
