### ISSUE TITLE
Ecto.Enum and schemaless changesets

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3493]
### Environment

* Elixir version (elixir -v): 1.11.2
* Ecto version (mix deps): 3.5.5

### Current behavior
It is not covered in docs. I tried this, but without success
```elixir
iex> {%{}, %{p: {:parameterized, Ecto.Enum, %{values: [:a]}}}} |> cast(%{p: "a"}, [:p])  
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [
    p: {"is invalid",
     [type: {:parameterized, Ecto.Enum, %{values: [:a]}}, validation: :cast]}
  ],
  data: %{},
  valid?: false
>
```

### Expected behavior
support this if possible and document how to use

**Comment by josevalim** [comment]
Hvae you tried calling `Ecto.Enum.init(...)` when setting up the type instead of hardcoding the values directly?

**Comment by v0idpwn** [comment]
Ecto.Enum.cast relies on the `on_dump` option. It is defined based on the values when initializing the field:

`` `
iex(9)> Ecto.Enum.init(values: [:a, :b, :c])
%{
  on_dump: %{a: "a", b: "b", c: "c"},
  on_load: %{"a" => :a, "b" => :b, "c" => :c},
  values: [:a, :b, :c]
}
```

```
iex(10)> Ecto.Type.cast({:parameterized, Ecto.Enum, %{values: [:a, :b, :c], on_dump: ["a" => :a, "b" => :b, "c" => c]}}, "a")
```

So, I believe your example could be:
```
iex(11 > {%{}, %{p: {:parameterized, Ecto.Enum, Ecto.Enum.init(values: [:a]}}} |> Ecto.Changeset.cast(%{p: "a"}, [:p])   
```

**Comment by fuelen** [comment]
Ah, thank you! Didn't know about `init`.

**Comment by wojtekmach** [comment]
For posterity it's not

```elixir
{:parameterized, Ecto.Enum, Ecto.Enum.init(...)}
```

but:

```elixir
{:parameterized, {Ecto.Enum, Ecto.Enum.init(...)}
```

For example:

```elixir
iex> types = %{color: {:parameterized, {Ecto.Enum, Ecto.Enum.init(values: ~w[red green blue]a)}}}
iex> Ecto.Changeset.cast({%{}, types}, %{color: :red}, ~w[color]a)
#Ecto.Changeset<
  action: nil,
  changes: %{color: :red},
  errors: [],
  data: %{},
  valid?: true,
  ...
>
```
