### ISSUE TITLE
dynamic ORDER BY in WINDOW function

### ISSUE THREAD

**Issue by mjquinlan2000** [elixir-ecto/ecto#3498]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.5
* Ecto version (mix deps): 3.5.4
* Database adapter and version (mix deps): postgrex 0.15.7
* Operating system: macOS Catalina 10.15.7

### Current behavior

I am dynamically constructing window functions for an API and I need to be able to use `dynamic/3` within the `windows/3` function to partition the result set correctly. Here is a simplified example:

```elixir
  comments_query = select("comments", [c], %{
    id: c.id,
    author_id: c.author_id,
    body: c.body,
    post_id: c.post_id
  })

  sort = [desc: dynamic([post_author: u], u.name)]

  "posts"
  |> join(:inner, [p], c in subquery(comments_query),
    on: c.post_id == p.id,
    as: :comment
  )
  |> join(:inner, [p], u in "users", on: u.id == p.author_id, as: :post_author)
  |> select([p, comment: c], %{
    id: c.id,
    post_id: p.id,
    post_author_id: p.id,
    comment_author_id: c.author_id,
    body: c.body,
    row_number: over(row_number(), :window)
  })
  # The next line causes the issue
  |> windows([comment: c], window: [partition_by: c.author_id, order_by: ^sort])
```

Gives me this error:

```
** (FunctionClauseError) no function clause matching in Ecto.Query.Builder.count_alias!/2

    The following arguments were given to Ecto.Query.Builder.count_alias!/2:

        # 1
        "comments"

        # 2
        :comment

    Attempted function clauses (showing 1 out of 1):

        def count_alias!(%{aliases: aliases} = query, name)

    (ecto 3.5.4) lib/ecto/query/builder.ex:800: Ecto.Query.Builder.count_alias!/2
```

I believe that the bind aliases from `dynamic/3` are not playing well with the bind aliases from `window/3`

By using a fragment on the `row_number` I can generate valid sql:

```elixir
row_number: fragment("row_number() OVER (PARTITION BY ? ORDER BY ? DESC)", c.author_id, a.name)
```

However, this approach removes my ability to dynamically build the order expressions

### Expected behavior

I expect that dynamic sorting in `window/3` should work.

Please let me know of any potential problems you see with this. Thanks

**Comment by josevalim** [comment]
The docs for dynamic does not list windows as a possible place, so this feature is simply not supported. You will have to conditionally define the window based on the arguments instead of using dynamic, sorry. :(

**Comment by mjquinlan2000** [comment]
@josevalim Thank you for the quick response. I somehow missed that in the docs. I will look for another solution
