### ISSUE TITLE
Adding a subquery to join's `:on` option returns cryptic error

### ISSUE THREAD

**Issue by mathieuprog** [elixir-ecto/ecto#3500]
### Environment

* Elixir version (elixir -v): 1.10.2 (OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 11
* Ecto version (mix deps): 3.5.5
* Database adapter and version (mix deps): postgrex, 0.15.7
* Operating system: Windows 10

### Current behavior

A subquery in a join's `:on` option returns a cryptic error. Example:

```
subset =
  from acl in Acl,
    where: acl.grantor_id == parent_as(:users).id,
    where: acl.grantee_id == ^100,
    select: acl.grantor_id

query =
  from users in User, as: :users,
    left_join: articles in Article, on: articles.author_id == users.id and users.id in subquery(subset),
    preload: [:authored_articles]
```

Error:

> == Compilation error in file test/foo_test.exs ==
** (MatchError) no match of right hand side value: {{:{}, [], [:and, [], [{:{}, [], [:==, [], [{:{}, [], [{:{}, [], [:., [], [{:{}, [], [:&, [], [1]]}, :author_id]]}, [], []]}, {:{}, [], [{:{}, [], [:., [], [{:{}, [], [:&, [], [0]]}, :id]]}, [], []]}]]}, {:{}, [], [:in, [], [{:{}, [], [{:{}, [], [:., [], [{:{}, [], [:&, [], [0]]}, :id]]}, [], []]}, {:subquery, 0}]]}]]}, {[subquery: 0], [{{:., [], [{:__aliases__, [alias: false], [:Ecto, :Query]}, :subquery]}, [], [{:subset, [line: 132], nil}]}]}}
    (ecto 3.5.5) lib/ecto/query/builder/join.ex:206: Ecto.Query.Builder.Join.build_on/7
    (ecto 3.5.5) lib/ecto/query/builder/join.ex:185: Ecto.Query.Builder.Join.build/10
    (ecto 3.5.5) lib/ecto/query.ex:844: Ecto.Query.from/5
    (ecto 3.5.5) expanding macro: Ecto.Query.from/2

**Comment by v0idpwn** [comment]
Are we supposed to support this? Or just throw a better error? I'm not sure.

**Comment by mathieuprog** [comment]
On IRC jose said 
> it should work but that error message is disturbing. please open up an issue so we can improve it

In any case, I don't see why this wouldn't be supported.

**Comment by josevalim** [comment]
Let's just improve the error message for now.

It could be supported but I believe it is a non-trivial amount of work.

@v0idpwn would you like to send a PR for improving the error? :heart:

**Comment by mathieuprog** [comment]
Hah it's particularly needed for LEFT JOINs; for INNER JOINs the `:on` clause could be just expressed in a `:where` clause.

Not even sure how to change the SQL query below into an SQL version that would work with Ecto.

```
SELECT users.*, articles.*
FROM users
LEFT OUTER JOIN articles ON articles.author_id = users.id
AND users.id IN (
  SELECT acl.grantor_id
  FROM acl
  WHERE acl.grantor_id = users.id
    AND acl.grantee_id = $1
)
```

**Comment by v0idpwn** [comment]
Sure, @josevalim! I'll take a better look at this today.

**Comment by v0idpwn** [comment]
I was checking it out and it seems pretty complex to implement. I think Ecto.Query.JoinExpr would have to be modified, and then ecto_sql (?) so it would be able to work with it. That's 100% gray area for me. Implementing a better error, OTOH, seems trivial. What do you think?

**Comment by josevalim** [comment]
Let's start with the error, yes. :)

**Comment by jbsf2** [comment]
I ran into this today as well. Was very happy to find this issue to confirm that I'm not crazy! Thank you. Just adding +1 to confirm that there is a use-case :-)
