### ISSUE TITLE
New Repo methods proposal 'first' and 'last' 

### ISSUE THREAD

**Issue by pawurb** [elixir-ecto/ecto#3506]
I would like to propose adding the following methods to `Repo`

- `first`
- `first!`
- `last`
- `last!`

I’m just starting to play around with Phoenix and I miss those simple helper methods from Rails. 

I propose the following API and resulting SQL execution:

```
Repo.last(User) => SELECT * FROM USERS ORDER BY ID DESC LIMIT 1;
Repo.first(User) => SELECT * FROM USERS ORDER BY ID ASC LIMIT 1;
Repo.last(from u in User, where: u.status == "active") => SELECT * FROM USERS WHERE status = 'active' ORDER BY ID DESC LIMIT 1;
Repo.last(from u User, order_by: u.inserted_at) => SELECT * FROM USERS WHERE status = 'active' ORDER BY inserted_at DESC LIMIT 1;
```

`!` bang versions will work just like `one!` raising error if object is not found.  

The same calls can be implemented with `Repo.one` but I’d prefer a more concise API for common usage scenarios:

```
Repo.last(User)

# vs

Repo.one(from u in User, limit: 1, order_by: [desc: u.id])
```

Optionally we could leave out the implicit ordering by primary key but I find it handy for easily fetching the newest object e.g. in tests. 

I’m looking forward to implementing the change, but before I would like to get the green light that this API would be accepted.

**Comment by josevalim** [comment]
There is already Ecto.Query.first and Ecto.Query.last that you can pipe into `Repo.one` or `Repo.one!`: https://hexdocs.pm/ecto/Ecto.Query.html#first/2

:)
