### ISSUE TITLE
Support `order_by` in associations

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#3509]
Given PostgreSQL is not ordered by default, it would be convenient if we could easily specify how we want to order all our associations. The feature should be fairly straight-forward, the biggest issue here is the naming. `order_by` is not going to work with `assoc(parent, :association)` in queries. Only with preloaded queries and Ecto.assoc queries. We could call it `preload_order_by` but that doesn't encompass the `Ecto.assoc` case. Suggestions?

**Comment by Madddogg314** [comment]
So what am i supposed to do?
Please tell me exactly what i can do to make sure you are pleased well...??

**Comment by v0idpwn** [comment]
How would this behave with multiple preloads?

**Comment by thiamsantos** [comment]
Would be nice if we could set a default order_by directly on the schema. 
Something like `has_many :association, Association, order_by: {:desc, :inserted_at}`

**Comment by josevalim** [comment]
@thiamsantos that's exactly what I have in mind, except it would be a keyword list. :) So it should just work with multiple preloads too.

**Comment by josevalim** [comment]
All we need to do is figure out a name. @wojtekmach @michalmuskala - any ideas?

**Comment by thiamsantos** [comment]
Something like `default_order_by` would make sense?

**Comment by josevalim** [comment]
My concern is a name that makes it clear it applies on preload/Ecto.assoc but not when you use it as a join. For example, we could name it “non_join_order_by”.

**Comment by dvic** [comment]
Not sure if it makes sense, but what about `assoc_order_by`?

**Comment by Eiji7** [comment]
@josevalim For me `preload_order` as an option name is short and looks much better. I understand why we use `_by` suffix for DSL/function names, but it does not look as important for an option key.

```elixir
has_many :users, User, preload_order: [:last_name, :first_name, {:desc, :age}]
```

I would think about  `Ecto.assoc/2` (and also `assoc/2` DSL) separately … Can't we just add a **third** argument for passing `query` options? This would be definitely useful in many cases … The reason behind this is to not force to write a separate `Ecto.Query` just for one or two options.

```elixir
# instead of
Repo.all from p in Post,
           join: c in subquery(…), on: …
           where: c.published_at > p.updated_at,
           preload: [comments: c]
# use
Repo.all from p in Post,
           join: c in assoc(p, :comments, order_by: [{:desc, :date}]),
           where: c.published_at > p.updated_at,
           preload: [comments: c]
```
We may want to support many other options like `assoc(p, :comments, where: [reviewed: true])` and so on …

**Comment by josevalim** [comment]
Sounds good. Let's go with `preload_order` then! There is an issue in that both preload and Ecto.assoc use the same Ecto.assoc_query, but we can solve this internally.

> I would think about Ecto.assoc/2 (and also assoc/2 DSL) separately … Can't we just add a third argument for passing query options? 

`Ecto.assoc` returns a query, so if you want to filter it, you can simply pipe to `from` (or `where`, etc) next.

**Comment by michalmuskala** [comment]
I think it could also be possible to make it "just work" on joins by translating them to a subquery, e.g.

```elixir
has_many :widgets, order_by: :name
```

```elixir
from f in Foo,
  join: w in assoc(f, :widget),
  select: {f.id, w.id}
```

would translate to:
```sql
SELECT f.id, w.id
FROM foo AS f
JOIN (SELECT * FROM widgets AS w ORDER BY w.name) AS w
```

**Comment by josevalim** [comment]
@michalmuskala that's a good point... do we want to do it though? Perhaps we can leave it open for the future, especially if we call this one `preload_order`.

**Comment by michalmuskala** [comment]
Yeah, I'm not sure it's a good idea either -- especially if it has some serious performance implications.

On the other hand, having it behave differently in different settings also seems kind of weird (even if the name is explicit), so I'm torn.

**Comment by thiamsantos** [comment]
I don't know if someone is already working on this, but I would like to give it a try.

- We would support this only for `many_to_many` and `has_many`?
- We should accept the same options as [`order_by/3`](https://hexdocs.pm/ecto/Ecto.Query.html#order_by/3)
- We can go with `preload_order` as @Eiji7 suggested?

> @michalmuskala that's a good point... do we want to do it though? Perhaps we can leave it open for the future, especially if we call this one preload_order.

About using the order on join, seems to be a good approach to leave it open for the future, specially if it could introduces performance issues as @michalmuskala mentioned.

@josevalim Could you provider a little guidance on where to work to include the `order_by` option?

I could find where it seems to be the place where the preload query is built https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L222, it seems to use the foreign key as order by default. Would be necessary to use `Ecto.Query.Builder.OrderBy` to build the query?

**Comment by josevalim** [comment]
> We would support this only for many_to_many and has_many?

Yes.

> We should accept the same options as order_by/3

Not quite. We accept only a keyword list with asc|desc as keys and fields as atoms as values.

> We can go with preload_order as @Eiji7 suggested?

Yes!

> I could find where it seems to be the place where the preload query is built https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L222, 

Yes, that's the place. You still want to order by foreign key first with the additional order_by coming next. You will probably need to return the order_by as part of [preload_info](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L486).

**Comment by michalmuskala** [comment]
How would this work with through associations? In particular, if one of the intermediaries has a `preload_order`. Does that impact the order of the final association?

**Comment by josevalim** [comment]
Through should not accept this option. Given through just depends on other preloads, it will follow the order of other preloads.

**Comment by v0idpwn** [comment]
I was wondering today if maybe we should support any query in a preload.

This could be done in subqueries, as pointed by @michalmuskala. but I think it could be optional rather than the default.

For instance. one could write:
```elixir
defmodule MySchema do
  alias ChildSchema

  schema "my_schema" do
    has_many :children, ChildSchema
    has_many :alive_children, {:query. from c in ChildSchema, where: c.alive}
    has_one :last_children, {:query. from c in ChildSchema, order_by: [{c.born_at, :desc}], limit: 1}
   end
end
```

I think it would allow us to build more expressive relations.

**Comment by josevalim** [comment]
This generates compile-time dependencies, which can lead to compilation deadlocks, which is why we have historically not allowed this approach

**Comment by enkr1** [comment]
> This generates compile-time dependencies, which can lead to compilation deadlocks, which is why we have historically not allowed this approach

Does anybody know how can I preload many_to_many relationship with condition like order_by?

I am trying to achieve: 
```ex
many_to_many(:tags, Tag, join_through: FileTag, preload_order: [asc: ^ft.inserted_at]) # i want to do something like this
```
