### ISSUE TITLE
Query formatter doesn't show parentheses for grouped and/or clauses

### ISSUE THREAD

**Issue by thojanssens** [elixir-ecto/ecto#3512]
I build a query using `Ecto.Query.dynamic` in order to have grouped AND and OR clauses.

Inspecting the query outputs:

```
#Ecto.Query<from u0 in Foo.User, as: Foo.User,
 where: u0.deleted == ^false and u0.name == ^"Bob" or u0.deleted == ^false and u0.name == ^"Alice">
```

(the query doesn't make much sense but just ignore that)

SQL executed:

```
SELECT u0."id", u0."name", u0."deleted", u0."inserted_at", u0."updated_at" 
FROM "users" AS u0 
WHERE (
  ((u0."deleted" = $1) AND (u0."name" = $2)) OR
  ((u0."deleted" = $3) AND (u0."name" = $4))
)
```

It is hard to debug when the parenthesis are omitted in the formatted query. Looking at the query at first glance, we could assume the query is wrong. I'm only able to know how clauses are grouped through executing the query and checking the SQL logs.

**Comment by josevalim** [comment]
We are using Macro.to_string which simply relies on Elixir's rule precedence and and has higher precedence than or. We would most likely need to add our own Macro.to_string, to change this, which would be too complicated. For now, a double check on Elixir operator page is enough to answer the question. Thank you!
