### ISSUE TITLE
__schema__(:type, field) changed behavior for embeds since ecto 3.5 release

### ISSUE THREAD

**Issue by k-cross** [elixir-ecto/ecto#3516]
### Environment

* Elixir version (elixir -v): 1.11.2 otp-23.1.4
* Database and version: MySQL 5.7
* Ecto version (mix deps): 3.5.5 from 3.4.6
* Database adapter and version (mix deps): MyXQL
* Operating system: MacOS 10.7

### Current behavior

Failure to compile with this error:
```
** (RuntimeError) casting embeds with cast/4 for :foo field is not supported, use cast_embed/3 instead
    (ecto 3.5.5) lib/ecto/changeset.ex:541: Ecto.Changeset.cast_type!/2
    (ecto 3.5.5) lib/ecto/changeset.ex:515: Ecto.Changeset.process_param/7
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.5) lib/ecto/changeset.ex:501: Ecto.Changeset.cast/6
```

Digging into the function we're using `__schema__(:type, field)` to find out if the field is embedded or not, I dug into documentation to see an example and only found some test cases relevant. Seems like there is a new `:parameterized` type or something along the lines here that's breaking behavior.

Neither test here
https://github.com/elixir-ecto/ecto/blob/master/test/ecto/parameterized_type_test.exs#L42

and here
https://github.com/elixir-ecto/ecto/blob/master/test/ecto/schema_test.exs#L38

protect against changes in this function wrt `embedded_schema`.

### Expected behavior

Compilation succeeds.

I fixed this internally by changing our behavior to match, but having a test to prevent this in the future might be nice.

before
```
{:embed,
 %Ecto.Embedded{
   cardinality: :many,
   field: :posts,
   on_cast: nil,
   on_replace: :delete,
   ordered: true,
   owner: Ecto.EmbeddedTest.Author,
   related: Post,
   unique: true
 }}
```

after
```
{:parameterized, Ecto.Embedded,
 %Ecto.Embedded{
   cardinality: :many,
   field: :posts,
   on_cast: nil,
   on_replace: :delete,
   ordered: true,
   owner: Ecto.EmbeddedTest.Author,
   related: Ecto.EmbeddedTest.Post,
   unique: true
 }}
```

I don't really know where to make that change, but I hope this gives you enough info to help test for it in the future. Happy holidays and thanks for all the effort and work y'all put into this!

**Comment by josevalim** [comment]
To see if a fields is an embed, prefer using the :embeds and (:embed, name) reflection functions. Those will work regardless of version, as the actual type may indeed change.

**Comment by k-cross** [comment]
Thanks for the response. Is it not at least worth documenting in the `CHANGELOG` when this changes? This is a public function which did cause a breaking change which would have been much quicker to resolve looking through it. We were using `:type` to do analysis on more than just `:embeds` so `:type` was the more appropriate approach for how we're using it since we're scanning all fields. We can definitely use the suggestion to make it always work, it's just not intuitive as to why we'd do that.

**Comment by josevalim** [comment]
Good call, changelog updated!
