### ISSUE TITLE
Can't use order_by in except query

### ISSUE THREAD

**Issue by smartepsh** [elixir-ecto/ecto#3526]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 13.1
* Ecto version (mix deps): 3.5.5
* Database adapter and version (mix deps): 0.15.7
* Operating system: MacOS BigSur 11.1

### Current behavior

`order_by` can not use in `EXCEPT`/`EXCEPT_ALL`/`UNION`/`UNION_ALL`/`INTERSECT`/`INTERSECT_ALL` queries.

```elixir
supplier_query = from s in Supplier, select: s.city

from c in Customer, select: c.city, except: ^supplier_query, order_by: c.city
```

Tables for Supplier and Customer are both exist. But it will throw the following exception:

```
** (Postgrex.Error) ERROR 42P01 (undefined_table) missing FROM-clause entry for table "a0"
```

### Expected behavior

The query works.

**Comment by wojtekmach** [comment]
Thank you for the report.

We generate the following query:

```sql
SELECT c0."city" FROM "customers" AS c0 EXCEPT (SELECT s0."city" FROM "suppliers" AS s0) ORDER BY c0."city"
```

and for this to work we would have to generate:

```sql
SELECT c0."city" as city FROM "customers" AS c0 EXCEPT (SELECT s0."city" FROM "suppliers" AS s0) ORDER BY city
# or by position
SELECT c0."city" as city FROM "customers" AS c0 EXCEPT (SELECT s0."city" FROM "suppliers" AS s0) ORDER BY 1
```

This is because per [1] [2] 

> A limitation of this feature is that an ORDER BY clause applying to the result of a UNION, INTERSECT, or EXCEPT clause can only specify an output column name or number, not an expression.

[1] https://www.postgresql.org/docs/current/sql-select.html#SQL-ORDERBY
[2] https://www.postgresql.org/message-id/499E0B4E.9020201@dunslane.net

**Comment by wojtekmach** [comment]
In the meantime one can also do this:

```elixir
supplier_query = from(s in Supplier, select: s.city)
q = from(c in Customer, select: c.city, except: ^supplier_query)
from(e in subquery(q), order_by: :city)
```

**Comment by smartepsh** [comment]
Thanks for the reply. 

The description about this in the document:

> Note that the operations order_by, limit and offset of the current query apply to the result of the set difference.

It makes me think that it can use `order by` in `except` directly...

**Comment by josevalim** [comment]
I believe you can if you refer to city and not a particular instance of city, such as `order_by: fragment("city")`. But I think the subquery approach is clearer. :)
