### ISSUE TITLE
Different behavior for {:map, :string} in Repo.load between 3.4 and 3.5 versions.

### ISSUE THREAD

**Issue by mrcnkoba** [elixir-ecto/ecto#3532]
### Environment

* Elixir version (elixir -v): 1.11.2
* Ecto version (mix deps): 3.5.5
* Operating system: MacOS 11.1

### Current behavior

After updating Ecto from 3.4.6 to 3.5.5, I've noticed a change in behavior for the schema below. When you try to `Repo.load` such schema with a map that one of the values is `nil` it throws in Ecto 3.5.5.
Note: I feel like this change is actually a bugfix! Maybe it just needs a new test in "repo_test". https://github.com/elixir-ecto/ecto/blob/756bb5d7f5f839397d09060748836422c940d29e/test/ecto/repo_test.exs which I'd be willing to take. 

```
defmodule MapStringInvalid.MySchema do
  use Ecto.Schema
  import Ecto.Changeset

  schema "my_schema" do
    field :x, {:map, :string}
  end
end
```

I've isolated it to the `Repo.load` function. The following code works well in 3.4 branch, but throws in 3.5 branch.

3.5.5:
```
iex(1)> MapStringInvalid.Repo.load(MapStringInvalid.MySchema, %{x: %{a: nil}})
** (ArgumentError) cannot load `%{a: nil}` as type {:map, :string} for field `x` in schema MapStringInvalid.MySchema
    (ecto 3.5.5) lib/ecto/schema/loader.ex:76: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
    (elixir 1.11.2) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
```

3.4.6
```
iex(1)> MapStringInvalid.Repo.load(MapStringInvalid.MySchema, %{x: %{a: nil}})
%MapStringInvalid.MySchema{
  __meta__: #Ecto.Schema.Metadata<:loaded, "my_schema">,
  id: nil,
  inserted_at: nil,
  updated_at: nil,
  x: %{a: nil}
}
```

### Expected behavior
I actually feel like this is how it's supposed to be. However it would be great to have a type `{:map, :string | nil}`.

**Comment by josevalim** [comment]
We currently allow nils for arrays, so we should allow them for maps too:

https://github.com/elixir-ecto/ecto/blob/v3.5.5/test/ecto/type_test.exs#L102

**Comment by v0idpwn** [comment]
Type.cast also doesn't seem to work for `nil` values while using  {:map, type}.

**Comment by v0idpwn** [comment]
I didn't manage to reproduce your issue on master. I created a patch with my attempt:
https://gist.github.com/v0idpwn/0039b430ff2371a8366a0886400b8527

**Comment by josevalim** [comment]
@v0idpwn this fails for me:

```diff
diff --git a/test/ecto/type_test.exs b/test/ecto/type_test.exs
index ef568194..8c642786 100644
--- a/test/ecto/type_test.exs
+++ b/test/ecto/type_test.exs
@@ -81,8 +81,11 @@ defmodule Ecto.TypeTest do
 
   test "typed maps" do
     assert load({:map, :integer}, %{"a" => 1, "b" => 2}) == {:ok, %{"a" => 1, "b" => 2}}
+    assert load({:map, :integer}, %{"a" => 1, "b" => nil}) == {:ok, %{"a" => 1, "b" => nil}}
     assert dump({:map, :integer}, %{"a" => 1, "b" => 2}) == {:ok, %{"a" => 1, "b" => 2}}
+    assert dump({:map, :integer}, %{"a" => 1, "b" => nil}) == {:ok, %{"a" => 1, "b" => nil}}
     assert cast({:map, :integer}, %{"a" => "1", "b" => "2"}) == {:ok, %{"a" => 1, "b" => 2}}
+    assert cast({:map, :integer}, %{"a" => "1", "b" => nil}) == {:ok, %{"a" => 1, "b" => nil}}
 
     assert load({:map, {:array, :integer}}, %{"a" => [0, 0], "b" => [1, 1]}) == {:ok, %{"a" => [0, 0], "b" => [1, 1]}}
     assert dump({:map, {:array, :integer}}, %{"a" => [0, 0], "b" => [1, 1]}) == {:ok, %{"a" => [0, 0], "b" => [1, 1]}}
```

**Comment by v0idpwn** [comment]
This also fails for me, @josevalim, but on cast, not on load, as reported in the issue

**Comment by v0idpwn** [comment]
Just opened #3533, which solves the cast problem. This issue stays open, as I didn't manage to reproduce the Repo.load/2 problem.
