### ISSUE TITLE
The exception DBConnection.ConnectionError gives a misleading error message

### ISSUE THREAD

**Issue by kuroda** [elixir-ecto/ecto#3541]
I was bothered by the exception `DBConnection.ConnectionError` for a long time while trying to run my Phoenix application in a production environment.

This exception gave the following error message.

> ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2343ms. This means requests are coming in and your connection pool cannot serve them fast enough. 

Then, it offers three solutions:

1. Tracking down slow queries and making sure they are running fast enough
2. Increasing the pool_size (albeit it increases resource consumption)
3. Allowing requests to wait longer by increasing :queue_target and :queue_interval

But these messages were misleading. Because, in my case, the exception was just because the database wasn't created. In fact, once I created the database, I no longer got this exception.

### Environment

* Elixir 1.11.3
* PostgreSQL 12
* Ecto 3.5.5
* Ubuntu 20.04

**Comment by josevalim** [comment]
Fixed in DBConnection master, thank you!
