### ISSUE TITLE
Ecto.StaleEntryError with assoc `on_replace: :delete` option

### ISSUE THREAD

**Issue by validere-ben** [elixir-ecto/ecto#3544]
### Environment

* Elixir version (elixir -v): Elixir 1.11.1 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.6
* Ecto version (mix deps): 3.5.5
* Database adapter and version (mix deps):  postgrex 0.15.7
* Operating system: macOS 10.15.6

### Current behavior

An `Ecto.StaleEntryError` can be raised when concurrent updates are made with a changeset including assocs with `on_replace: :delete` when using `{cast|put}_assoc`.

A minimal application reproducing this behaviour can be found here: https://github.com/validere-ben/stale_assoc

i.e. (From the example application above)
```elixir
14:19:21.668 [debug] QUERY OK source="users" db=1.4ms queue=2.2ms idle=856.9ms
SELECT u0."id", u0."email" FROM "users" AS u0 WHERE (u0."email" = 'foo@example.com') []

14:19:21.668 [debug] QUERY OK source="users" db=1.0ms decode=1.2ms queue=1.3ms idle=856.9ms
SELECT u0."id", u0."email" FROM "users" AS u0 WHERE (u0."email" = 'foo@example.com') []

14:19:21.696 [debug] QUERY OK source="permissions" db=3.1ms queue=1.9ms idle=885.3ms
SELECT p0."id", p0."scope", p0."actions", p0."user_id", p0."user_id" FROM "permissions" AS p0 WHERE (p0."user_id" = $1) ORDER BY p0."user_id" [<<89, 101, 235, 57, 14, 164, 71, 80, 145, 48, 126, 79, 43, 208, 178, 175>>]

14:19:21.696 [debug] QUERY OK source="permissions" db=3.0ms queue=2.0ms idle=885.3ms
SELECT p0."id", p0."scope", p0."actions", p0."user_id", p0."user_id" FROM "permissions" AS p0 WHERE (p0."user_id" = $1) ORDER BY p0."user_id" [<<89, 101, 235, 57, 14, 164, 71, 80, 145, 48, 126, 79, 43, 208, 178, 175>>]

14:19:21.704 [debug] QUERY OK db=0.3ms idle=899.7ms
begin []

14:19:21.704 [debug] QUERY OK db=0.2ms queue=0.1ms idle=899.7ms
begin []

14:19:21.709 [debug] QUERY OK db=1.3ms
DELETE FROM "permissions" WHERE "id" = $1 [<<64, 121, 80, 189, 237, 221, 66, 223, 151, 244, 207, 229, 43, 209, 183, 164>>]

14:19:21.719 [debug] QUERY OK db=1.3ms
INSERT INTO "permissions" ("actions","scope","user_id","id") VALUES ($1,$2,$3,$4) [["read"], "posts", <<89, 101, 235, 57, 14, 164, 71, 80, 145, 48, 126, 79, 43, 208, 178, 175>>, <<244, 70, 218, 41, 203, 94, 65, 140, 149, 64, 47, 169, 124, 41, 43, 236>>]

14:19:21.719 [debug] QUERY OK db=0.5ms
commit []

14:19:21.719 [debug] QUERY OK db=11.7ms
DELETE FROM "permissions" WHERE "id" = $1 [<<64, 121, 80, 189, 237, 221, 66, 223, 151, 244, 207, 229, 43, 209, 183, 164>>]

14:19:21.725 [debug] QUERY OK db=0.3ms
rollback []

14:19:21.725 [error] Task #PID<0.254.0> started from #PID<0.248.0> terminating
** (Ecto.StaleEntryError) attempted to delete a stale struct:

%StaleAssoc.Permission{__meta__: #Ecto.Schema.Metadata<:loaded, "permissions">, actions: ["read"], id: "407950bd-eddd-42df-97f4-cfe52bd1b7a4", scope: "posts", user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: "5965eb39-0ea4-4750-9130-7e4f2bd0b2af"}

    (ecto 3.5.5) lib/ecto/repo/schema.ex:666: Ecto.Repo.Schema.apply/4
    (ecto 3.5.5) lib/ecto/repo/schema.ex:437: anonymous fn/10 in Ecto.Repo.Schema.do_delete/4
    (ecto 3.5.5) lib/ecto/association.ex:706: Ecto.Association.Has.on_repo_change/5
    (ecto 3.5.5) lib/ecto/association.ex:692: Ecto.Association.Has.on_repo_change/5
    (ecto 3.5.5) lib/ecto/association.ex:476: anonymous fn/8 in Ecto.Association.on_repo_change/7
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.5.5) lib/ecto/association.ex:472: Ecto.Association.on_repo_change/7
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
Function: #Function<0.82167722/0 in StaleAssoc.update_user/0>
    Args: []
```

### Expected behavior
One may expect the update to happen idempotently with this option, or to allow configuration for the delete/replacement of assocs to happen idempotently.

**Comment by josevalim** [comment]
Hi @validere-ben, i pushed a `:delete_if_exists` option in the v3.5 branch. Can you please give it a try? If it works I will ship a new v3.5 version. Thank you!

**Comment by validere-ben** [comment]
> Hi @validere-ben, i pushed a `:delete_if_exists` option in the v3.5 branch. Can you please give it a try? If it works I will ship a new v3.5 version. Thank you!

@josevalim Excellent! Works great!

A side question somewhat related to the usage of assocs and this new option: is the ability to have upsert behaviour supported with`on_conflict/conflict_target` options for through `{cast|put}_assoc` something that would ever make sense? 

i.e. if the identity used for diffing to determine if a given assoc 'exists' was not based on `id` but rather a custom primary key.  For example if we have a `user` with `notification_settings` with a primary key of `(user_id, notification_type)` or a unique constraint with a separate id primary key that would normally be used with `on_conflict: {:replace_all_except, [:id]}`.

user_id | notification_type | is_enabled |
------- | ----------------- | -----------|
1           | email                     | true            |
2           | sms                       | false          |

Or would this complicate the philosophy of `{cast|put}_assoc` and the recommendation for more involved assoc management to be to always manage them explicitly/separately in a Multi/Transaction.

**Comment by josevalim** [comment]
I don't think that's easily achievable with cast/put_assoc because if you don't give an entry, we will always try to delete (or nillify or update them). And since you want to upsert them, we cannot do any of that, so we would need to know we should not touch those entries based on this unique reference, which today we don't track at all. So I think it is unfortunately out of scope.

**Comment by validere-ben** [comment]
> I don't think that's easily achievable with cast/put_assoc because if you don't give an entry, we will always try to delete (or nillify or update them). And since you want to upsert them, we cannot do any of that, so we would need to know we should not touch those entries based on this unique reference, which today we don't track at all. So I think it is unfortunately out of scope.

👍  Thanks José!
