### ISSUE TITLE
Ecto.Enum allows nil values

### ISSUE THREAD

**Issue by christophweegen** [elixir-ecto/ecto#3547]
Hello,

the current implementation for `Ecto.Enum` (`3.5.6`) allows for `nil` values given, which is a bit counter-intuitive since one would think, only values in the given list would be allowed.

```elixir
field :status, Ecto.Enum, values: [:foo, :bar, :baz] # <- Allows for nil
```

This info would maybe be a useful addition to the docs https://hexdocs.pm/ecto/Ecto.Enum.html

I would suggest to optionally disallow `nil` while keeping things backward-compatible with a `null: false` option:

```elixir
field :status, Ecto.Enum, values: [:foo, :bar, :baz], null: false
```

Greetings

**Comment by wojtekmach** [comment]
Thanks for the report. Nil had always special handling in changesets, even if you define a field to be eg :string, nil is an acceptable value. I believe we carry over this logic to enums ad other parameterized types. If you don’t want to allow nil, prevent it with validate_required.
