### ISSUE TITLE
`Ecto.assoc/2` returns incorrect query for `many_to_many` with `through`

### ISSUE THREAD

**Issue by parallel588** [elixir-ecto/ecto#3559]
### Environment

* Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
* Elixir 1.11.3 (compiled with Erlang/OTP 23)
* PostgreSQL 12.5
* Ecto version (mix deps): elixir-ecto/ecto {:ecto, github: "elixir-ecto/ecto", override: true}
* Database adapter and version (mix deps): postgrex "0.15.8"
* Operating system: Ubuntu 20.04.2 LTS

### Current behavior

exist the following schemas
```elixir

defmodule EctoDemo.Device do
  use Ecto.Schema
  schema "devices" do
    field(:name, :string)
    many_to_many(
      :interruptions,
      EctoDemo.Interruption,
      join_through: EctoDemo.InterruptionDevice,
      join_keys: [device_id: :id, interruption_id: :id],
      on_replace: :delete
    )

    has_many(:interruption_logs, through: [:interruptions, :interruption_logs])

    timestamps()
  end
end


defmodule EctoDemo.Interruption do
  use Ecto.Schema
  schema "interruptions" do
    field(:name, :string)
    has_many(:device_interruptions, EctoDemo.InterruptionDevice)
    has_many(:interruption_logs, EctoDemo.InterruptionLog)
    timestamps()
  end
end

defmodule EctoDemo.InterruptionDevice do
  use Ecto.Schema
  schema "device_interruptions" do
    belongs_to(:device, EctoDemo.Device)
    belongs_to(:interruption, EctoDemo.Interruption)
  end
end

defmodule EctoDemo.InterruptionLog do
  use Ecto.Schema
  schema "interruption_logs" do
    field(:name, :string)
    belongs_to(:interruption, EctoDemo.Interruption, on_replace: :nilify)
    timestamps()
  end
end

```

and trying to get an interruption_logs via `Repo.all(Ecto.assoc(device, [:interruption_logs]))` we will have error of sql:

```
   ** (Postgrex.Error) ERROR 42P01 (undefined_table) missing FROM-clause entry for table "i2"
     
         query: SELECT DISTINCT i0."id", i0."name", i0."interruption_id", i0."inserted_at", i0."updated_at" FROM "interruption_logs" AS i0 INNER JOIN "device_interruptions" AS d1 ON i2."id" = d1."interruption_id" INNER JOIN "interruptions" AS i2 ON d1."device_id" = ANY($1) WHERE (i0."interruption_id" = i2."id")

```

I found that error appear after this commit: https://github.com/elixir-ecto/ecto/commit/9fabc769cfd74b6227488facb1c59cfc0eca532a (https://github.com/elixir-ecto/ecto/pull/3481)

here simple app for reproduce error:  
https://github.com/parallel588/ecto_demo1
https://github.com/parallel588/ecto_demo1/blob/main/test/assoc_test.exs

**Comment by josevalim** [comment]
Thanks for the report!

@GabrielAlacchi, would you like to look into this? Otherwise we will have to revert the previous patch. :) Thank you!

**Comment by GabrielAlacchi** [comment]
Sure I can look into this in the next day or two. I can also write an integration test for this situation as well so we avoid this regression in the future.
