### ISSUE TITLE
Ecto.Changeset.put_change unexpected behaviour when trying to set to zero

### ISSUE THREAD

**Issue by tomdmaguire** [elixir-ecto/ecto#3583]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): n/a
* Ecto version (mix deps): 3.5.6
* Database adapter and version (mix deps): ecto_sql 3.5.4
* Operating system: OSX 10.15

### Current behavior

Give the following code:

```elixir
defmodule Test do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field(:amount, :integer, default: 0)
  end

  def changeset(%Test{} = test, attrs) do
    test
    |> cast(attrs, [:amount])
    |> validate_required([:amount])
  end
end

changeset = Test.changeset(%Test{}, %{amount: 10})

Ecto.Changeset.put_change(changeset, :amount, 0)
```

I would expect that the `put_change` call would result in a changeset with `changes` set to `%{amount: 0}`.

However, the result is:

```
#Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Test<>,
 valid?: true>
```

i.e. the `amount` attribute seems to have been removed.

### Expected behavior

Resulting changeset to be:

```
#Ecto.Changeset<
  action: nil,
  changes: %{amount: 0},
  errors: [],
  data: #Test<>,
  valid?: true
>
```

**Comment by Eiji7** [comment]
The default `amount` is `0`, so there is nothing to change. Everything works as expected.

**Comment by tomdmaguire** [comment]
ah yes. makes sense. thanks
