### ISSUE TITLE
Replace gender example in validate_inclusion

### ISSUE THREAD

**Issue by bitboxer** [elixir-ecto/ecto#3590]
I would propose to change the example of `validate_inclusion` ([see here](https://github.com/elixir-ecto/ecto/blob/v3.5.8/lib/ecto/changeset.ex#L1956)) to a more neutral one. Using a gender and having it set to a default set of values advertises a way that will for sure discriminate against some people. There are so many other more neutral examples:

* Cardinal direction
* List of colors
* Preferred interface Languages
* And some more

I also would create a PR for this if this is wanted, and we decided what example is more neutral.

**Comment by josevalim** [comment]
Yes please! List of colors and cardinal dimensions are great!

**Comment by bitboxer** [comment]
I created a PR. This is my first PR in ecto. If there is anything missing I should do, please point it out, and I will fix it ASAP. Thanks for your willingness to change the example 👍.
