### ISSUE TITLE
Make ecto work with ipv6 by default?

### ISSUE THREAD

**Issue by mrkurt** [elixir-ecto/ecto#3593]
We run IPv6 private networks (for [reasons](https://fly.io/blog/ipv6-wireguard-peering/)!), which means Elixir apps using Ecto need to connect to their databases over IPv6.

Ecto doesn't allow IPv6 by default, to get a Phoenix app working with its DB we have to ask users to change their Repo config to something like:

```elixir
config :web_app, WebApp.Repo,
  url: System.get_env("POOL_SIZE") ,
  socket_options: [:inet6]
```

Are you all cool with enabling IPv6 by default for Ecto? Cowboy (and by extension, Phoenix) default to `:inet6` so it would be more consistent for Phoenix apps, at least.

I haven't been able to find the default `socket_options` that ecto uses but if you can point me in the right direction I can make a PR!

**Comment by josevalim** [comment]
Hi @mrkurt! Those configurations would be specific to each adapter. Perhaps we should generate on the config/runtime.exs of new Phoenix apps? WDYT @chrismccord?

**Comment by josevalim** [comment]
To be clear, Phoenix and Plug.Cowboy set inet6 on config/runtime.exs. So changing Phoenix would go along the same lines. :)

**Comment by mrkurt** [comment]
I am still learning to spelunk through Elixir apps, but I can't find where that gets set in Phoenix. I thought that was the default for Cowboy socket_options!

**Comment by Eiji7** [comment]
I have no idea how it looks like in remote database services like `AWS`, but I would pay attention here. Many network providers do not even support `IPv6` (at least in `Poland`). Therefore making it by default could affect many projects and force many developers to change it in `dev.exs`.

**Comment by josevalim** [comment]
@mrkurt in [Phoenix master](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/config/runtime.exs#L23). In [Phoenix v1.5](https://github.com/phoenixframework/phoenix/blob/v1.5/installer/templates/phx_single/config/prod.secret.exs#L17).

@Eiji7 inet6 should work for both inet4 and inet6 (in theory).

**Comment by mrkurt** [comment]
Oh nice, that got me (I think) what I needed for a Phoenix PR: https://github.com/phoenixframework/phoenix/pull/4289
