### ISSUE TITLE
Variable interpolation in nested preloads for Ecto.Query.Preload

### ISSUE THREAD

**Issue by mveytsman** [elixir-ecto/ecto#3596]
### Environment

* Elixir version (elixir -v): 1.11.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): N/A
* Ecto version (mix deps): 3.5.8
* Database adapter and version (mix deps): postgrex 0.15.8
* Operating system: MacOS

### Current behavior

There's definitely a documentation bug, I would have made a PR fixing it but I think maybe there's an ecto bug as well.

I tried to implement the example with nested preload queries from here: https://hexdocs.pm/ecto/Ecto.Query.html#preload/3-preload-queries
> When specifying a preload query, you can still preload the associations of those records. For instance, you could preload an author's published posts and the comments on those posts:
> ```elixir
> posts_query = from p in Post, where: p.state == :published
> Repo.all from a in Author, preload: [posts: {posts_query, [:comments]}]
> ```
The above code gives me a compiler error:
```
** (Ecto.Query.CompileError) unbound variable `posts_query ` in query. If you are attempting to interpolate a value, use ^var
```

What's strange is that putting a ^ in front of `posts_query` also errors out:

```elixir
Repo.all from a in Author, preload: [posts: {^posts_query, [:comments]}]
```

```
** (Ecto.Query.CompileError) `{^posts_query, [:comments]}` is not a valid preload expression. preload expects an atom, a list of atoms or a keyword list with more preloads as values. Use ^ on the outermost preload to interpolate a value
```

The correct form is:
```elixir
Repo.all from a in Author, preload: [posts: ^{posts_query, [:comments]}]
```

The documentation is incorrect on this, and I'm surprised/confused that I had to put the ^ outside of the tuple not inside it as I would have expected. Is this a bug or something I'm missing about how ^'s behave?

**Comment by josevalim** [comment]
That’s because we don’t allow you to do this:

    {query, foo: assoc}

which would be complex to implement. So you either replace the whole tuple or nothing at all. The error messages are correct, the docs are wrong. A PR is welcome! :)

**Comment by mveytsman** [comment]
Ah! 

The error is 
>  preload expects an atom, a list of atoms or a keyword list with more preloads as values. Use ^ on the outermost preload to interpolate a value

The second sentence is telling me to put the ^ outside the tuple, but the first sentence of the error threw me off because it doesn't capture that you can include a query or a tuple with a query and nested preloads

**Comment by josevalim** [comment]
If you think the error message can be clearer, improvements there are also welcome!

**Comment by mveytsman** [comment]
@josevalim I think it can be clearer but I couldn't come up with a better wording -- I don't understand what's under the hood well enough to describe it clearly yet :)
