### ISSUE TITLE
Querying by custom type behaves differently for `in` queries than `==`

### ISSUE THREAD

**Issue by coladarci** [elixir-ecto/ecto#3598]
### Current behavior

We have a custom type `TypedRefid` (which in the db is stored as `{type, id}`) which implements `@behaviour Ecto.Type`.

Our schema includes a parent field using this type: `field :parent, TypedRefid`

Our goal is to be able to query for records by their parent.

To query for records w/ a specific parent this correctly returns records whose parent matches what was provided:

```
  def filter(query, :parent, value) do
    where(query, [a], a.parent == type(^value, TypedRefid))
  end
```

But if we want to return records whose parent is one of many parents provided:

```
  def filter(query, :parent, values) when is_list(values),
    do: where(query, [a], a.parent in type(^values, {:array, TypedRefid}))
```

This raises an error:

```
     ** (DBConnection.EncodeError) cannot encode anonymous tuple {"our_type_name", "our_record_id"}. Please define a custom Postgrex extension that matches on its underlying type:
     
         use Postgrex.BinaryExtension, type: "typeinthedb"
```

### Expected behavior

I'd expect them to behave the same regardless of if I'm querying by one or many.

❤️ ❤️   for any eyes or advice!

```
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.4 (compiled with Erlang/OTP 23)
PostgreSQL
Ecto 3.5.8
```

**Comment by josevalim** [comment]
can you try:

    def filter(query, :parent, values) when is_list(values),
      do: where(query, [a], a.parent in type(^values, {:in, TypedRefid}))

We treat `:in` as a special type internally, so I wonder if you need to do the same.

**Comment by josevalim** [comment]
If it works, can you please send a PR that updates the docs? We can improve the docs for `type/2` and `in/2`. Thank you.

**Comment by coladarci** [comment]
As always, thanks for the quick reply. Sadly it doesn't fix it:

```
  def filter(query, :parent, values) when is_list(values),
    do: where(query, [a], a.parent in type(^values, {:in, TypedRefid}))
```

Results in:

```
     ** (DBConnection.EncodeError) cannot encode anonymous tuple {"our_type_name", "our_record_id"}. Please define a custom Postgrex extension that matches on its underlying type:
     
         use Postgrex.BinaryExtension, type: "typeinthedb"
```

**Comment by coladarci** [comment]
`type/0` returns `:typed_refid`

```
defmodule Utils.Ecto.Types.TypedRefid do
  @moduledoc false

  alias Utils.Types.TypedRefid

  @behaviour Ecto.Type

  @type t :: TypedRefid.t()

  @underlying_type :typed_refid

  # Casting in changesets
  @impl Ecto.Type
  def cast(term), do: TypedRefid.cast(term)

  # Dumping to the database
  @impl Ecto.Type
  def dump(%TypedRefid{refid: refid, type: type}),
    do: {:ok, {Atom.to_string(type), refid}}

  def dump(_invalid), do: :error

  @impl Ecto.Type
  def embed_as(_format), do: :self

  @impl Ecto.Type
  def equal?(term1, term2), do: term1 === term2

  # Loading from the database.
  @impl Ecto.Type
  def load(term), do: TypedRefid.cast(term)

  @impl Ecto.Type
  def type, do: @underlying_type
end
```

**Comment by josevalim** [comment]
Is that an actual PostgreSQL type understood by Postgrex?

**Comment by coladarci** [comment]
No, it's a custom type we created:

```
execute "CREATE TYPE typed_refid AS (type text, refid text);"
```

**Comment by josevalim** [comment]
And have you defined a custom extension to encode it as the error message proposes?

the error message is correct, you need extension to use custom types in many occasions.

**Comment by coladarci** [comment]
I guess I'm curious why the extension would be needed when doing an `in` but not when doing an `==`...

**Comment by josevalim** [comment]
In is a composite type (it is sent as an array), so we cannot infer as much when sending the data. The correct is to define the extension, the fact it works without is a convenience to help the simplest of cases. :)
