### ISSUE TITLE
Integer should be allowed as schema default for float type? 

### ISSUE THREAD

**Issue by tmock12** [elixir-ecto/ecto#3603]
### Environment

* Elixir version (elixir -v): _Elixir 1.10.2 (compiled with Erlang/OTP 22)_
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.6
* Ecto version (mix deps): 3.6.0
* Operating system: Mac Big Sur

### Current behavior

https://github.com/elixir-ecto/ecto/pull/3487 introduced an ArgumentError when the default of a field has an invalid type. This causes a default of type `:integer` to raise an error when the field type is `:float`. 

This illustrates the current behavior:
```elixir
  test "default of invalid type" do
    assert_raise ArgumentError, ~s/value 0 is invalid for type :float, can't set default/, fn ->
      defmodule SchemaInvalidDefault do
        use Ecto.Schema

        schema "invalid_default" do
          field :count, :float, default: 0
        end
      end
    end
  end
```

My question is, Is this expected? is this too strict? Should we allow an integer as the default for a type of float? 

### Expected behavior

I guess I'd expect to be able to set a default of type `:float` to a type of `:integer` 🤷 ,  ie:

```elixir
schema "valid_default" do
  field :count, :float, default: 0
end
```

Happy to take a crack at fixing this if desired, but wanted to open it for discussion first. Thanks!

**Comment by josevalim** [comment]
This is expected. The error is coming because we can't dump the value, which means you may have error later on. :)
