### ISSUE TITLE
Queries on reflexive many_to_many relation via join_through schema no longer work

### ISSUE THREAD

**Issue by tcrossland** [elixir-ecto/ecto#3606]
### Environment

* Elixir version (elixir -v): elixir 1.12.0-rc.0 (compiled with Erlang/OTP 24 RC2)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL
* Ecto version (mix deps): 3.6.0
* Database adapter and version (mix deps): postgrex 0.15.8
* Operating system: MacOS Big Sur

### Current behavior

Changes introduced in https://github.com/elixir-ecto/ecto/pull/3481 break expression queries on schemas with a reflexive `many_to_many` relation via a `join_through` schema. For example:

```elixir
defmodule Ecto.Integration.Post do
  use Ecto.Integration.Schema

  schema "posts" do
    # ...
    many_to_many :children, Ecto.Integration.Post,
      join_through: Ecto.Integration.PostRelation,
      join_keys: [parent_id: :id, child_id: :id]
  end
end

defmodule Ecto.Integration.PostRelation do
  use Ecto.Integration.Schema

  schema "post_relations" do
    field :type, :string
    belongs_to :parent, Ecto.Integration.Post
    belongs_to :child, Ecto.Integration.Post
  end
end
```

```elixir
test "many_to_many with self using join_through schema" do
  p1 = TestRepo.insert!(%Post{title: "1"})
  p2 = TestRepo.insert!(%Post{title: "2"})
  _pr = TestRepo.insert!(%PostRelation{parent_id: p1.id, child_id: p2.id, type: "foo"})

  query =
    p1
    |> Ecto.assoc(:children)
    |> join(:inner, [child], child in assoc(child, :children))
    |> where([_parent, _child, rel, _grandchild], rel.type == "foo")

  assert [] = TestRepo.all(query)
end
```

```
** (Ecto.QueryError) .../src/github/ecto/integration_test/cases/assoc.exs:244: 
     field `type` in `where` does not exist in schema Ecto.Integration.Post in query:
     
from p0 in Ecto.Integration.Post,
  join: p1 in Ecto.Integration.PostRelation,
  on: p0.id == p1.child_id,
  join: p3 in Ecto.Integration.PostRelation,
  on: p3.parent_id == p0.id,
  join: p2 in Ecto.Integration.Post,
  on: p3.child_id == p2.id,
  where: p1.parent_id in ^[1],
  where: p2.type == "foo",
  select: p0
```

### Expected behavior

The query should work correctly.

**Comment by tcrossland** [comment]
I've created an integration test that reproduces the issue:

https://github.com/tcrossland/ecto/tree/many_to_many_issue

I used git bisect to identify the breaking change, the query works correctly previous to #3481.

**Comment by josevalim** [comment]
Thanks @tcrossland for reproducing the issue.

@GabrielAlacchi, is this something you could look into please, if you have the time? Thank you! :heart:

**Comment by GabrielAlacchi** [comment]
Thanks @tcrossland for creating an integration test! I'll be able to take a look most likely this weekend but I may be able to find a few hours before then.

**Comment by tcrossland** [comment]
I've had a quick look and I think that as things stand it's not possible to determine whether a positional binding is supposed to reference the `join_through` schema or the `many_to_many` association itself, unless we resort to adding an option to the join expression to conditionally exclude the `join_through` binding.

**Comment by tcrossland** [comment]
Also, the use of positional bindings to reference the `join_through` relation isn't particularly explicit in the documentation... @josevalim if you're happy with the change of the behaviour, an alternative "fix" might be a breaking change notice and an example of how to refactor expression queries affected by the change.

**Comment by josevalim** [comment]
@tcrossland Good point. If you want to access the join_through, it sounds to me you should not be using a many_to_many but instead a has_many through? 🤔

**Comment by tcrossland** [comment]
The schema used in the real-world query actually has both associations (has_many :child_relations/:parent_relations and many_to_many :children/:parents with the join_through). The positional binding on the join_through simplified the expression queries as it avoided an additional (explicit) join.

Refactoring the query is fairly straight forward, my concern is that it's a breaking change on a minor version and it might bite other users.

If you like I could try to put together a PR documenting the changed behaviour and an example of how to refactor the query?

**Comment by josevalim** [comment]
Agreed on the concerns. Let's wait for @GabrielAlacchi's input and we can make a decision. Thanks for discussing the options!

**Comment by GabrielAlacchi** [comment]
Hey @josevalim and @tcrossland, I've taken a look and I believe I understand the issue. I'll refer to the example @tcrossland used in the failing integration test. 

```
query =
  p1
  |> Ecto.assoc(:children)
  |> join(:inner, [child], child in assoc(child, :children))
```

Prior to #3481 the bind order for this query would be `[child, parent, rel (between child and parent), grandchild, rel2 (between child and grandchild)]`. Since the change removed the unnecessary join of the parent table the query no longer binds `parent` and thus the bind order has changed to `[child, rel (between child and parent), grandchild, rel2 (between child and grandchild)]`. The query can hence be refactored to
```
query =
  p1
  |> Ecto.assoc(:children)
  |> join(:inner, [child], child in assoc(child, :children))
  |> where([_child, rel, _grandchild], rel.type == "foo")
```
and it'll achieve the desired result. 

I did not anticipate #3481 introducing a breaking change, but seeing as we removed a table, queries with positional binds have been affected. Thus I agree we should likely add explicit documentation / examples and add a breaking change notice as @tcrossland suggested.

> I've had a quick look and I think that as things stand it's not possible to determine whether a positional binding is supposed to reference the `join_through` schema or the `many_to_many` association itself, unless we resort to adding an option to the join expression to conditionally exclude the `join_through` binding.

As far as I can tell join through binding should be consistently available as the 2nd positional binding in an `Ecto.assoc/2` query, likewise when using `join` with `assoc/2` on a bound table. For example, if one would like to add an additional condition to the relationship between child and grandchild in this example, then they can use the 4th positional bind:

```
where([_child, rel, _grandchild, rel2], rel.type == "foo" and rel2.type == "bar")
```
Please let me know if this makes sense and how we should proceed to remedy this issue.

**Comment by josevalim** [comment]
Thanks @GabrielAlacchi for the updates!

Note there is a version that will work in both previous and current Ecto versions which is to use: `...`

    where([..., rel, _grandchild], rel.type == "foo")

My suggestion is to update the docs and the release notes. I will work on that. But it is probably best to never relying on the middle table appearing in the bindings.

**Comment by tcrossland** [comment]
Thanks @josevalim and @GabrielAlacchi , looks good to me
