### ISSUE TITLE
prepare_query/3 for Repo.insert_all()

### ISSUE THREAD

**Issue by spinettaro** [elixir-ecto/ecto#3608]
Hello,

I just noticed that prepare_query/3 it is not invoked when I call a Repo.insert_all() or Repo.Insert.

I receive the callback for ` def default_options( operation) do ` but not for `def prepare_query( operation, query, opts) do` 

It is ok when I face a SELECT query. 

In addition I have updated ecto to version 3.6.0
Elixir version 1.11.2

**Comment by josevalim** [comment]
Correct. Prepare_query is only invoked when we have a Ecto.Query struct and insert/insert_all do not.

**Comment by spinettaro** [comment]
@josevalim  is there a callback to identify if a query is an insert, update or select, before the execution?

**Comment by josevalim** [comment]
default_options is the only way you can customize those without overriding them.

**Comment by spinettaro** [comment]
@josevalim ok but if I cannot intercept it on the prepare_query callback how can I read/interpreter what I have just set?

**Comment by josevalim** [comment]
You can't do much in this case, besides setting existing options. You can always create higher-level abstractions around the Repo that does the normalization that you want/need.

**Comment by spinettaro** [comment]
@josevalim ok it makes sense :) thanks a lot for the quick replies! much appreciated
