### ISSUE TITLE
Force interpolations for json_extract_path

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#3609]
We need to either always send values as params or force users to always interpolate them, otherwise we'll generate the wrong query on Postgres and possibly on other adapters. (Strictly speaking, Postgres cannot handle the generated query as it doesn't know the type of the value sent as is)

```elixir
Mix.install([
  :jason,
  :ecto_sql,
  :postgrex
])

defmodule Repo do
  use Ecto.Repo, adapter: Ecto.Adapters.Postgres, otp_app: :foo
end

defmodule Post do
  use Ecto.Schema

  schema "posts" do
    embeds_one(:author, Author)
  end
end

defmodule Author do
  use Ecto.Schema

  @primary_key false
  embedded_schema do
    field(:name, :string)
  end
end

defmodule Main do
  import Ecto.Query

  def main do
    {:ok, _} = Repo.start_link(database: "")

    Repo.query!("DROP TABLE IF EXISTS posts")
    Repo.query!("CREATE TABLE posts (id serial primary key, author JSONB)")

    Repo.insert!(%Post{author: %Author{name: "Alice"}})
    Repo.insert!(%Post{})

    # this works

    from(i in Post, where: i.author["name"] == ^"Alice")
    |> Repo.all()

    # and this is because we send "Alice" as _param_:
    #
    # SELECT p0."id", p0."author" FROM "posts" AS p0 WHERE ((p0."author"#>'{"name"}') = $1)

    # this does not work

    from(i in Post, where: i.author["name"] == "Alice")
    |> Repo.all()

    # ** (Postgrex.Error) ERROR 22P02 (invalid_text_representation) invalid input syntax for type json

    #     query: SELECT p0."id", p0."author" FROM "posts" AS p0 WHERE ((p0."author"#>'{"name"}') = 'Alice')

    # Token "Alice" is invalid.
  end
end

Main.main()
```

**Comment by kelvinst** [comment]
I think the preferable would be to always send values as params, as I think people do not interpolate plain values as much, so it would require a considerable amount of change when upgrading Ecto.

Any downside of doing it that way?

**Comment by wojtekmach** [comment]
> so it would require a considerable amount of change when upgrading Ecto.

it would _not_ because if you don't interpolate yourself your code is broken :) I can't think of downsides of always interpolating but maybe it should be left to the adapter, will look into it.

**Comment by aegatlin** [comment]
As an individual who has made this mistake both in the Embedded Intro doc with a toy example, and in my prod app storing JSONB blobs in Postgres, I will say from a UX perspective that the latter option of "pass by interpolation" seems so intuitive to me that I keep forgetting to pin the value. And the error of `Token "Alice" is invalid` I assumed was a syntax error being reflected from Postgres up through Ecto, which led me down the path of reading postgres docs on jsonpath syntax, etc. 

I'm naive to the pros and cons of eliminating one or the other option, but, if Ecto keep both, maybe we could at least include a suggestion in the latters' error output suggesting pinning as a solution?

**Comment by josevalim** [comment]
> I'm naive to the pros and cons of eliminating one or the other option, but, if Ecto keeps both, maybe we could include a suggestion in the latters' error output suggesting pinning as a solution?

I like this. We already get the exceptions with statuses codes and we can trivially add this.

**Comment by josevalim** [comment]
Improved warning added to Ecto.SQL.
