### ISSUE TITLE
changing the base query of unsafe_validate_unique

### ISSUE THREAD

**Issue by dvic** [elixir-ecto/ecto#3610]
I'm thinking of creating a `unsafe_validate_unique` that accepts an option that changes the base query. Our usecase is the use of soft deletes, we want to exclude rows that are marked as `deleted`. I think it's a relatively small change and I can create a PR if needed.

**Comment by josevalim** [comment]
A `:query` option that defaults to the schema sounds good to us! PR is welcome!
