### ISSUE TITLE
undefined function first/1

### ISSUE THREAD

**Issue by conradwt** [elixir-ecto/ecto#3617]
### Environment

* Elixir version (elixir -v):  Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.2
* Ecto version (mix deps): 3.6.1
* Database adapter and version (mix deps): postgrex 0.15.8
* Operating system: macOS 11.2.3

### Current behavior

```text
** (CompileError) test/zero_phoenix_web/schema/query/person_test.exs:24: undefined function first/1
    (elixir 1.11.4) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.14.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.4) lib/kernel/parallel_compiler.ex:416: Kernel.ParallelCompiler.require_file/2
    (elixir 1.11.4) lib/kernel/parallel_compiler.ex:316: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

Note:  I have the following defined at the top of the module:

```elixir
import Ecto.Query, only: [first: 2]
```

and things appear to work when I change the above to

```elixir
import Ecto.Query, only: [first: 1]
```

### Expected behavior

I expected to have not gotten a compilation for an undefined function here.

**Comment by josevalim** [comment]
The behaviour is correct, we can't know you meant first/1 if you haven't imported it. :) So we can't even compile. I will improve the error message in master though, thank you!
