### ISSUE TITLE
Multiple identical rows in a has_many :through association

### ISSUE THREAD

**Issue by spatrik** [elixir-ecto/ecto#3621]
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.11.1 (compiled with Erlang/OTP 21)
  ```
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.1
* Ecto version (mix deps): 
  ```
  * ecto 3.6.1 (Hex package) (mix)
    locked at 3.6.1 (ecto) cbb3294a
    ok
  * ecto_sql 3.6.1 (Hex package) (mix)
    locked at 3.6.1 (ecto_sql) 66f35c3f
    ok
  * postgrex 0.15.8 (Hex package) (mix)
    locked at 0.15.8 (postgrex) 698fbfac
    ok
  ```
* Database adapter and version (mix deps):
  ```
  * postgrex 0.15.8 (Hex package) (mix)
    locked at 0.15.8 (postgrex) 698fbfac
    ok
  ```
* Operating system: MacOS 11.2

### Current behavior

I have a `has_many :through` defined like this

```
  schema "customers" do
    has_many :attachments, VariantAttachment
    has_many :variants, through: [:attachments, :variant]
  end

  schema "variant_attachments" do
    belongs_to :customer, Customer
    belongs_to :variant, Variant
  end

  schema "variants" do
  end
```

Taken from an [example project](https://github.com/spatrik/ecto-bug-maybe).

When I insert multiple `VariantAttachment`s with the `variant_id` set to the same one in each `VariantAttachment`, the `has_many :through` association just returns it once. 

I expected that `customer.variants` would returned the same  `Variant` twice. 

However, when  I'm thinking about it, I'm not entirely sure that makes sense. I could change my code to keep a `quantity` on the `variant_attachment` table and then use that instead. Or just use the `attachments` association directly. But the code reads very nice when I just get a list of variants.

Anyway, there is an minimal reproduction repo at https://github.com/spatrik/ecto-bug-maybe. If you consider this a weird abuse of `has_many :through` I'll just use one of the other approaches.

**Comment by josevalim** [comment]
Yes, there are no duplicates because we are querying the variants table directly matching on the parent ids - if they point to the same place - then that's still a single entry. You can change how your query is written or how you query the data, but the behaviour you see is expected. Thanks.

**Comment by spatrik** [comment]
Ah, I see. Thanks for the quick reply!
