### ISSUE TITLE
Subquery joins omit `nil` fields

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#3623]
### Environment

* Elixir version (elixir -v): `Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] Elixir 1.11.4 (compiled with Erlang/OTP 23)`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `postgres (PostgreSQL) 13.2`
* Ecto version (mix deps): `3.6.1`
* Database adapter and version (mix deps): `0.15.8`
* Operating system: `Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,2 Darwin`

### Current behavior

Minimal example query:

```elixir
Repo.all(
  from s in "stories",
  join: v in subquery(from v in "votes", select: %{a: nil}),
  select: %{a: v.a}
)
```

Results with:

```
[debug] QUERY ERROR source="stories" db=0.0ms queue=0.9ms idle=1966.5ms
SELECT s1."a" FROM "stories" AS s0 INNER JOIN (SELECT TRUE FROM "votes" AS sv0) AS s1 ON TRUE []
** (Postgrex.Error) ERROR 42703 (undefined_column) column s1.a does not exist

    query: SELECT s1."a" FROM "stories" AS s0 INNER JOIN (SELECT TRUE FROM "votes" AS sv0) AS s1 ON TRUE
    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:749: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.6.0) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5
    (ecto 3.6.0) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.0) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

If I replace `nil` with `fragment("NULL")` it works as expected:

```elixir
Repo.all(
  from s in "stories",
  join: v in subquery(from v in "votes", select: %{a: fragment("NULL")}),
  select: %{a: v.a}
)
# => [%{a: nil}, ...]
```

### Expected behavior

The query should always return `[%{a: nil}, ...]` as these two queries should be treated as equivalent.

**Comment by josevalim** [comment]
Good find. PR is welcome!
