### ISSUE TITLE
`nil` goes undetected when multiple map-values are passed

### ISSUE THREAD

**Issue by tverlaan** [elixir-ecto/ecto#3626]
I had an interesting hunt after refactoring a query that suddenly reported `nil`-values. In my case I found out that the values in question were already `nil`, but the order of how the values were accessed determined if it would get a `raise`. It happens when you access multiple values from the same map and the first key from the map you access is not a `nil` value, but any subsequent value can be `nil`.

To simplify the case to a minimum I wrote two tests to demonstrate the issue. (I have them in `test/ecto/query/builder/filter_test.exs` locally).

This test passes, `ArgumentError` is raised. ✅
```elixir
  test "raises on nil when a map-value is accessed" do
    f = fn arg ->
      from(p in "posts", where: p.foo == ^arg.x and p.bar == ^arg.val)
    end
    assert_raise ArgumentError, fn ->
      f.(%{x: nil, val: "x"})
    end
  end
```

This test fails, no `ArgumentError` is raised. 🛑
```elixir
  test "raises on nil when a map-value is accessed as second clause" do
    f = fn arg ->
      from(p in "posts", where: p.foo == ^arg.x and p.bar == ^arg.val)
    end
    assert_raise ArgumentError, fn ->
      f.(%{x: "x", val: nil})
    end
  end
```

I assume that in the second case I should also get an ArgumentError. Is that correct?

**Comment by josevalim** [comment]
Does it raise when you actually run the query? There is no guarantee Ecto will raise when it builds the query, but it should not send it to the adapter.

**Comment by tverlaan** [comment]
It doesn't raise when running the query either. The query just runs until I put the key that has the `nil` value as first where-clause.
