### ISSUE TITLE
`aggregate` repo test case can't pass

### ISSUE THREAD

**Issue by scottmessinger** [elixir-ecto/ecto#3628]
Hi! I'm working on updating the MongoDB adapter to be compatible with Ecto 3.6 (it's on 2.1 right now). 

In the process, I'm running into this test [case: ](https://github.com/elixir-ecto/ecto/blob/f6324ebc14f849fa4cc189cb263b5603c8bd1c19/integration_test/cases/repo.exs#L797)

```elixir
    assert TestRepo.aggregate(Post, :max, :visits) == nil
```

However, [based on the implementation](https://github.com/elixir-ecto/ecto/blob/f6324ebc14f849fa4cc189cb263b5603c8bd1c19/lib/ecto/repo/queryable.ex#L116-L122) for `aggregate`, it doesn't look like it can ever return `nil` if there are no results. 

```elixir
  def aggregate(name, queryable, aggregate, opts) do
    one!(name, query_for_aggregate(queryable, aggregate), opts)
  end


  def aggregate(name, queryable, aggregate, field, opts) do
    one!(name, query_for_aggregate(queryable, aggregate, field), opts)
  end
```

and `one!` is [implemented here](https://github.com/elixir-ecto/ecto/blob/f6324ebc14f849fa4cc189cb263b5603c8bd1c19/lib/ecto/repo/queryable.ex#L158-L164):

```elixir
  def one!(name, queryable, opts) do
    case all(name, queryable, opts) do
      [one] -> one
      [] -> raise Ecto.NoResultsError, queryable: queryable
      other -> raise Ecto.MultipleResultsError, queryable: queryable, count: length(other)
    end
  end
```

as you can see, if there are no results, `aggregate` returns an error instead of nil. It is `one` not `one!` that returns nil if there are no results. 

Am I looking at this wrong or is the current test case incorrect?

**Comment by josevalim** [comment]
If there are results but the columns are NULL, then we will get nil back.

**Comment by josevalim** [comment]
Sorry, I submitted accidentally.

 It will also be the case when there are no entries. Aggregation will always return a single row. An aggregation of nothing is still a row saying that nothing was aggregated. In the same way the count of nothing is a result, which is zero. :)

**Comment by scottmessinger** [comment]
Ahh, so you're saying this part should match: 

```
 [one] -> one
```

with 

```
[nil] -> nil
```

Is that right? If so, this might be an issue with how results are handled with the Mongo driver. The driver returns an empty array, matching the `[] -> raise Error` case.

**Comment by josevalim** [comment]
Exactly. Can you detect aggregation queries in the Mongo driver? Because an aggregation should always return *something*.

**Comment by scottmessinger** [comment]
@josevalim I think I might be able to do that. I'll check and let you know. Thanks!!

**Comment by josevalim** [comment]
I will close this for now, as I believe this is not an Ecto issue, feel free to ping or open up a new one if you want to continue this discussion. :)
