### ISSUE TITLE
Proposal: store extra meta data

### ISSUE THREAD

**Issue by revati** [elixir-ecto/ecto#3631]
Currently `field`, `has_many`, `has_one` and so on macros accept undefined amount/structure of options so fallowing line will work fine `field :temp_lo, :integer, foo: :bar`. There are few options keys that in different contexts are used `:default`, `: through`, `:virtual` and so on. But any other option will be discarded/ignored.

Proposal is to store those extra values as well.
```elixir
defmodule Sample.Weather do
  use Ecto.Schema

  # Provide allowed meta data
  @store_extra_meta_values [:foo, :default]

  schema "weather" do
    field :city     # Defaults to type :string
    field :temp_lo, :integer, foo: "foo indeed"
    field :temp_hi, :integer, bar: "will be discarded"
    field :prcp,    :float, default: 0.0
  end
end

=> Sample.Weather.__schema__(:meta)
[city: [], temp_lo: [foo: "foo indeed"], temp_hi: [], prcp: [default: 0.0]]
```
Depending on how defensive library wants to be regards this, but it might be just 
- `@store_extra_meta_values true` # to just store everything
- `@store_extra_meta_values [:foo, :default]` # to store just specified options
- `@store_extra_meta_values [:foo, :default, validate: &is_list/1]` # to even compile time check that provided options have correct value

It has 100% backwards compatibility, and at the same time opens up extensibility options. If it is possible to do without changes in ecto lib it self, please let me know, but i tried and failed. I also believe (maybe wrongly) that extra maintenance cost for this feature will be tiny.

# Explicit use case

```elixir
defmodule Sample.ChangeUserPassword do
  use Ecto.Schema

  # Provide allowed meta data
  @store_extra_meta_values [:validate, :from_session, :ui_type, :type, :normalize]

  def validate_user_current_password(value, params) do
    user = Repo.get_user_by_id(params.user_id)
    PasswordValidator.is_correct_password?(user.hashed_password, value)
  end

  embedded_schema do
    field :user_id, :binary_id, validate: [:required], from_session: true
    field :old_password, :string, validate: [:required, &validate_user_current_password/1], normalize: &Password.hash_password/1
    field :new_password, :string, validate: [:required, format: ~r/^\w+:\s/], ui_type: :password_strength_input, normalize: &Password.hash_password/1
  end
end

=> Sample.ChangeUserPassword.__schema__(:meta)
[
  user_id: [validate: [:required], from_session: true, type: :binary_id], 
  old_password: [validate: [:required, &validate_user_current_password/2], type: :string, normalize: &Password.hash_password/1],
  new_password: [validate: [:required, format: ~r/^\w+:\s/], ui_type: :password_strength_input, type: :string, normalize: &Password.hash_password/1]
]
```

With specific tooling i can run all validations using ecto as validator, i can dynamically build ui form, based on this meta data and so on. This would open possibilities for different kind of libraries to extend and build on top of ecto schemas, and let them describe schema in more detail for different contexts as well.

**Comment by michalmuskala** [comment]
Not addressing the proposal itself, it wouldn't be possible to pass references to local anonymous functions like that - e.g. `&validate_user_current_password/1` - the schema is evaluated at compile-time before the module is actually compiled and at this point the function does not exist yet (since it wasn't compiled). The utility of this might be therefore limited

**Comment by josevalim** [comment]
The downside of this approach is that it leads to a path where all of the definitions are happening at the scheme level, instead of inside functions. For example, it is by explicit design choice that Ecto pushes validations to be functions, instead of schema macros. All of your use cases could be built on top functions instead of directly on top of the schema, so I recommend exploring this route instead. Thanks!
