### ISSUE TITLE
Clarify the possibility of using `init/2` from `Ecto.Repo` to subscribe to the event of repository becoming operational

### ISSUE THREAD

**Issue by serokellcao** [elixir-ecto/ecto#3637]
From current [documentation](https://github.com/elixir-ecto/ecto/blob/2035faedfc70e8ee9584d750fb692a63197bb855/lib/ecto/repo.ex#L404) it is not clear how to use a custom `init/2` in a project's `Repo` module (the one that `use`s `Ecto.Repo`) to subscribe to the event of repository becoming operational and if it is possible at all.

**Comment by josevalim** [comment]
What do you mean by "the event of repository becoming operational". Which event are you talking about? The telemetry one? If so, the init/2 callback does not apply any restrictions or considerations to said callback, so you should simply fall the instructions in the telemetry docs.

**Comment by serokellcao** [comment]
Again, sorry for not being clear.

What I'm having in my project is the need to make sure that mission-critical data exists in the data base at app start.

Currently I'm one-shotting a [transient Task](https://git.sr.ht/~doma/do-auth/commit/49b87f70abe369b7cf027367b6ebe194286cfdf1#lib/do_auth/persistence.ex-1-18) that retries `GenServer.whereis`s a bunch, until it can check for existance of said mission-critical data.

Here's [how I currently insert the data](https://git.sr.ht/~doma/do-auth/commit/49b87f70abe369b7cf027367b6ebe194286cfdf1#lib/do_auth/persistence.ex-2-79), but I'd like to put `populate` logic in [DoAuth.Repo module](https://git.sr.ht/~doma/do-auth/tree/main/item/lib/do_auth/repo.ex).

**Comment by josevalim** [comment]
It is best to have a GenServer that runs in your supervision tree after the repo starts and does the required work on its `init` callback, returning :ignore afterwards.

**Comment by serokellcao** [comment]
Jose, thank you very much for clarification.
Do I understand correctly that it is guaranteed that if there is a child after Repo in the same supervisor, when it `init`s, Repo is already operational?
If so, this issue can be closed because the feature I'm asking for is not needed.

**Comment by josevalim** [comment]
Yes, correct. Closing as requested!
