### ISSUE TITLE
`Ecto.Telemetry` stops sending metrics after a db connection error

### ISSUE THREAD

**Issue by Dvogiatz** [elixir-ecto/ecto#3639]
### Environment

* Elixir version (elixir -v): Elixir 1.11.3 (compiled with Erlang/OTP 23)   
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.2
* Ecto version (mix deps): ecto 3.5.7
* Database adapter and version (mix deps): postgrex 0.15.8
* Operating system: Linux

### Current behavior
In our app, we have a query counter using Ecto Telemetry. 

Whenever the following error occurs: 
```elixir
(DBConnection.ConnectionError connection not available and request was dropped from queue after 1997ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information
)
```
Ecto.Telemetry stops sending metrics until we restart the container.

We are currently working on fixing the connection error so it won't happen, but in case this error occurs, we wouldn't want to stop gathering the metrics of the inserted queries. 

### Expected behavior
When a `DBConnection.ConnectionError` occurs, Ecto.Telemetry shouldn't require an application restart in order to send metrics again.

**Comment by josevalim** [comment]
Are you attaching your own handler to telemetry? And if so, is your handler the one crashing in case of errors? That's not an Ecto behaviour but rather a telemetry behaviour: any attached handler will be removed in case of errors. Also note there is no such module `Ecto.Telemetry` in Ecto. Could it perhaps be coming from another package?

**Comment by Dvogiatz** [comment]
@josevalim Hello, Yes I'm sorry I wasn't precise enough.
In our application, we have many repos. What we noticed is that after a `DBConnection.ConnectionError` on one of the repos, we stop receiving Ecto telemetry events from that repo.  The handler continues to receive Ecto Telemetry Events from the other repos, as well as events from other packages (e.g. broadway)

**Comment by josevalim** [comment]
Thanks @Dvogiatz for the additional context. There is one part that is unclear:

> we stop receiving Ecto telemetry events from that repo

Events are emitted by subscribing specific handlers. Ecto doesn't subscribe a handler for you. The connection error is likely causing your own handler to crash and your handler should cope with that. I don't think this is an Ecto bug. :)

**Comment by Dvogiatz** [comment]
Thank you for the quick responses @josevalim. 
We are using `telemetry_metrics_prometheus` , and we have configured a metric as following:
```
counter(
        "repo.query.count",
        description: "Counter of executed queries",
        tag_values: &__MODULE__.query_metadata/1,
        tags: [:command, :repo]
      )
 ```
 What I don't understand is how a `DB.connection.ConnectionError` detaches the handler since it's not related. 
 Feel free to close the issue since this is not Ecto related. Thanks again.

**Comment by josevalim** [comment]
If a handler is removed, it should log the reason. So you see such reports? Also, what query_metadata do?

**Comment by Dvogiatz** [comment]
@josevalim Sorry for the late response, tried to reproduce the bug in dev environment. It did throw a detach log, which was hard to spot on production level because of other continuous logs.  The issue was indeed inside query_metadata (which was extracting the name of the repo).

Thank you very much,  you were really helpful!!  Closing the issue, have a nice day! :)
