### ISSUE TITLE
Does tracing(telemetry) the execution of parallel preloads work now?

### ISSUE THREAD

**Issue by anildigital** [elixir-ecto/ecto#3644]
spandex_ecto (https://github.com/spandex-project/spandex_ecto ) project has following in README 

"Due to some recent changes in Ecto, we can no longer effectively trace the execution of parallel preloads. All other queries work fine, but until we figure something out that leverages either telemetry or until the task feature listed here is added to the language, we won't be able to support tracing parallel preloads."

Some related issues.
https://github.com/spandex-project/spandex_ecto/issues/12
https://github.com/elixir-lang/elixir/issues/7995
https://github.com/elixir-ecto/ecto/issues/2843

I would like to know if that spandex_ecto issue got resolved in ecto or not? Thanks!

**Comment by josevalim** [comment]
I am not familiar with spandex internals, so you will have to ask the spandex team. I will be glad to provide info to them in case we need to improve Ecto. Thanks!
