### ISSUE TITLE
Ecto can't order_by aggregate key without using `fragment`

### ISSUE THREAD

**Issue by mathiasose** [elixir-ecto/ecto#3645]
### Environment

* Elixir version (elixir -v): 1.12.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 11.12
* Ecto version (mix deps): 3.6.1
* Database adapter and version (mix deps): Postgrex 0.15.9
* Operating system: Docker `elixir:1.12.0-alpine`

### Current behavior
I have some table with an foreign ID column and an integer column. I want to aggregate (sum) rows that share ID and sort descending. This is possible like this:

```elixir
from x in SomeTable,
  select: %{
    foreign_id: x.foreign_id,
    agg_sum: x.integer_col |> sum()
  },
  group_by: [x.foreign_id],
  order_by: [desc: x.integer_col |> sum()]
```

However, I have to copy `x.integer_col |> sum()` from the `select` clause and paste it into `order_by`. If I then later find that I need to change something (maybe add `coalesce(0)`?) in the aggregation, I might suddenly be sorting by something slightly different than the values that are returned.

This is what I would like to work:
```elixir
from x in SomeTable,
  select: %{
    foreign_id: x.foreign_id,
    agg_sum: x.integer_col |> sum()
  },
  group_by: [x.foreign_id],
  order_by: [desc: :agg_sum]
```
But this just gives `(Postgrex.Error) ERROR 42703 (undefined_column) column m0.agg_sum does not exist`.

However, if I were to use `fragment`s, this _does_ work if I throw in an `AS`:
```elixir
from x in SomeTable,
  select: %{
    foreign_id: x.foreign_id,
    agg_sum: fragment("SUM(integer_col) AS agg_sum")
  },
  group_by: [x.foreign_id],
  order_by: fragment("agg_sum DESC")
```
This is functionally equivalent to the first code block, but I don't need to repeat myself, I can refer to the aggregated value by key.

### Expected behavior
Ecto should add the aggregate alias (or let me control aliases more precisely myself) and let me order by it without the need to use `fragment`. Code block #2 above should generate the same SQL as code block #3 and all three code blocks should be functionally equivalent.

**Comment by josevalim** [comment]
This is pretty much the same issue as #3159. So I will close in favor of that one. Feel free to join the discussion there!
