### ISSUE TITLE
Allow addition of macros in with_cte/3 as: option.

### ISSUE THREAD

**Issue by D4no0** [elixir-ecto/ecto#3646]
### Environment

* Elixir version (elixir -v): 1.12
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 12.1
* Ecto version (mix deps): 3.6.1
* Database adapter and version (mix deps): postgrex 0.15.9
* Operating system: ubuntu 20.04

### Current behavior

Suppose we have macro that generates fragments:
```

  defmacro select_cte(statement1, statement2) do
    quote do
      fragment("select ?, ?", unquote(statement1), unquote(statement2))
    end
  end
```

Now when we call:

```
query
|> with_cte("bounds", as: select_cte(...))
```

It outputs:

> ** (Ecto.Query.CompileError) `select_cte(..)` is not a valid CTE (named: "bounds"). The CTE must be an interpolated query, such as ^existing_query or a fragment.

The only way I could get it working is the following:
```
query
|> with_cte("bounds", as: fragment(?, select_cte(...)))
```

### Expected behavior
I am not sure, however I think this behavior happens because the macro is not expanded before as: checks for validity of query/fragment.

**Comment by josevalim** [comment]
Yes, a PR that expands the argument is welcome!

**Comment by josevalim** [comment]
I am working on a PR.

**Comment by D4no0** [comment]
Thanks!
