### ISSUE TITLE
Remove unique constraint 

### ISSUE THREAD

**Issue by spinettaro** [elixir-ecto/ecto#3655]
Hi, 

is there a way to remove only the unique constraint of an index? Not removing the index but just the constraint. 

Thanks

**Comment by josevalim** [comment]
Not in Ecto but you can always consult your database and execute SQL commands directly by calling `execute`. 
Btw, please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/support, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
