### ISSUE TITLE
`parse_url/1` fails with misleading error message when URL contains unencoded `#` or `?`

### ISSUE THREAD

**Issue by Lucasnar** [elixir-ecto/ecto#3656]
<details><summary><strong>Environment</strong></summary>

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `PostgreSQL 13:1`

* Ecto version (mix deps):
```
* ecto 3.6.1 (Hex package) (mix)
  locked at 3.6.1 (ecto) cbb3294a
  ok
* ecto_sql 3.6.1 (Hex package) (mix)
  locked at 3.6.1 (ecto_sql) 66f35c3f
  ok
```
* Database adapter and version (mix deps):
```
* postgrex 0.15.9 (Hex package) (mix)
  locked at 0.15.9 (postgrex) 61071910
  ok
```
* Operating system: macOS Catalina

</details>

### Current behavior

This is related to this older issue: https://github.com/elixir-ecto/ecto/issues/3588.

I'm sorry if what I'm proposing was already discussed and discarded in the past, or isn't feasible. I haven't found a previous issue suggesting what I thought.

So, I came across this error after we defined a database password that contained the character `#` and the character `?`, and then trying to connect to it using the URL way of connecting. I think there might be ways of solving this on Ecto's side; however, even if it is decided that the user should deal with it (encode the URL before trying to connect to the database), I think at least the error message could change, as it is misleading. There is also a possibility that something could be done on the URI module for solving this.

If we have a database password - but this happens to the username and possibly other fields too - that contains either `#` or `?`, and we try to connect to Ecto using the database URL, we get a message error in the following format:

```
** (Ecto.InvalidURLError) invalid url ecto://eric:p?ass#word@host:12345/mydb, path should be a database name
```

But `path` is correctly defined and `mydb` is a database name.

This also happens with non-English characters that I tried. `URI.encode(url)` was enough to fix it for the non-English chars, but for the characters above (`#` and `?`), we have to be more specific, using something like `URI.encode(url, &(&1 != ?# && &1 != ??))`. `#` and `?` are the only characters I found that we need to test in `URI.encode`'s second argument. For instance, all other reserved characters from the [URI Elixir module](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/uri.ex#L36) work without being explicitly mentioned in the `encode` function.

### Expected behavior

I see two possible options:

- The error message reflects that the issue isn't the `path`. Maybe some docs also reflect the need for encoding, including `#` and `?` (not sure which docs).
- Ecto itself encodes the URL string before parsing. From my own tests tweaking with `Supervisor.parse_url`, `URI.encode(url, &(&1 != ?# && &1 != ??))` _looks like_ enough to fix it, but I'm not 100% sure if it is really enough, and I'm probably not aware of all the implications of doing this.

Of course, there is also the option that the current behavior is the expected one and this was already a decision.

**Comment by josevalim** [comment]
The error message is actually correct because, with an unencoded ? and #, then it is actually missing the path:

```elixir
URI.parse "ecto://eric:p?ass#word@host:12345/mydb"
%URI{
  authority: "eric:p",
  fragment: "word@host:12345/mydb",
  host: "eric",
  path: nil,
  port: nil,
  query: "ass",
  scheme: "ecto",
  userinfo: nil
}
```

I will change the error to show the parsed URI. I think that will make it clearer what went wrong (although the solution may not be immediately clear, it should at least be a better indicator).

**Comment by Lucasnar** [comment]
Thank you, @josevalim!
