### ISSUE TITLE
Possible breaking change around 3.6.2

### ISSUE THREAD

**Issue by princemaple** [elixir-ecto/ecto#3659]
### Environment

* Elixir version (elixir -v): 1.12.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PG11
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): postgrex 0.15.9
* Operating system: docker alpine

### Current behavior

before 3.6.2 something like this, when `a` is `nil`, would not raise:

```elixir
Repo.update_all((from x in App.X, where: x.a == ^a), set: [b: b])
```

it raises now

### Expected behavior

Not sure what to expect. I think the error is good, but it seems to be a breaking change.

I have updated my own code to avoid injecting `nil`

**Comment by wojtekmach** [comment]
Yeah given this prevents nil injections we consider this a security fix and so not under compatibility promise. Thanks!

**Comment by princemaple** [comment]
Thanks for the quick response!
