### ISSUE TITLE
How to declare a enum in a migration?

### ISSUE THREAD

**Issue by naddika** [elixir-ecto/ecto#3661]
There're examples of how to use Ecto.Enum, but they're all for data-modules
```

defmodule MyApp.Accounts.User do
  use Ecto.Schema

  schema "users" do
    field :role, Ecto.Enum, values: [:admin, :moderator, :seller, :buyer]
  end
end
```

There're no examples and mention of how to declare an enum in a migration. 
```

defmodule MyApp.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users) do
      add :role # ?????


```

How?

**Comment by josevalim** [comment]
By default they are strings on the database level, so you will say it is a string. Although you can also declare them as an enum in the database. I will push some docs.
