### ISSUE TITLE
Custom error message doesn't appear in `errors.po`

### ISSUE THREAD

**Issue by alaadahmed** [elixir-ecto/ecto#3665]
### Environment

* Elixir version (elixir -v): `1.12.1`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL `13.3`, MariaDB `10.5.9`
* Ecto version (mix deps): `3.6.2`
* Database adapter and version (mix deps): Postgrex `0.15.9`
* Operating system: macOS `11.4`

### Current behavior
I have application with multi languages __(3 langs)__
In schema file, I used `unique_constraint` function in `changeset` with custom error message. I thought it will appear automatically inside the `errors.po` file at least in the default language `en/LC_MESSAGES/errors.po`, but it __didn't__, so I thought it is only located inside the schema file, and because I wanted that message to be translated to 2 other languages, I used `dgettext("errors", "message content here..")` and it appeared already in `errors.po` file in all languages, but when there is errors violate the unique_constraint, it shows only the `ar` __(Arabic)__ version of that message and I think it picked only the Arabic because alphabetically it comes first before `en` or `de` __(German)__. Other default error messages that generated by default inside `errors.po` files work as expected, but when use custom error message they don't show up in these files _UNLESS_ I use `dgettext`, __BUT__ they don't show correctly depending on current locale, just the `ar` version appears whatever current locale is.

```elixir
def changeset(candidate, attrs) do
    candidate
    |> cast(attrs, @all_fields)
    |> put_embed(:timeline, %{})
    |> put_embed(:notes, [%{}])
    |> validate_required(@required)
    |> validate_format(:email, ~r/(\w+)@([\w.]+)\.([a-z]{2,4}|\d+)$/)
    |> unique_constraint([:email, :job_id],
      name: :index_candidate_applied_for_the_job,
      message: dgettext("errors", "this email address applied already for that job")
    )
    |> validate_format(:phone, @phone_format, message: "must be a valid phone number")
  end
```
Now when I removed the domain `"errors"` and I used normal `gettext("this email address...")`, and then `mix gettext.extract --merge`, they of course disappear from all `errors.po` files, and appear in `default.po` files in all languages and when there is error of unique_constraint violation, they appear correctly depending on current locale.

### Expected behavior
I think the expected behavior, if I used custom error message other than the default ones coded in `Ecto.Changeset` module, they should reflect automatically in all `errors.po` files without using `dgettext` likewise, as happened with the default messages of `Ecto.Changeset` module because it doesn't make sense that all _custom error messages_ located in `default.po` files!!. And if this should not be the default behavior then if I used `dgettext` with `"errors"` domain, they of course appear there in these files, but most important, they appear right in the application depending on the current locale.

**Comment by wojtekmach** [comment]
I tried reproducing this on a new Phoenix project and I couldn't, everything seems to work well. 

Please use the [ElixirForum](https://elixirforum.com) or StackOverflow for questions/support, where a wider community will be able to help you. If you do so, I'd attach a sample repo that reproduces the problem. We reserve the issues tracker for issues only. Thank you!

**Comment by josevalim** [comment]
I couldn’t reproduce this either. If you can provide a small application that reproduces the issue, then we will gladly reopen and take a look. But if there is something here, it is most likely Gettext related and not Ecto related. Thanks!

**Comment by alaadahmed** [comment]
When I write it like this

```elixir
|> unique_constraint([:email, :job_id],
      name: :index_candidate_applied_for_the_job,
      message: "this email address applied already for that job"
    )
```
Nothing appear in any `errors.po` file in any language, I can confirm this. And I think this is wrong, it should go to all `errors.po` files automatically because it is at the end an error message.

If I used it like this
```elixir
|> unique_constraint([:email, :job_id],
      name: :index_candidate_applied_for_the_job,
      message: dgettext("errors", "this email address applied already for that job")
    )
```
Message appear in all `errors.po` files in all languages, but it doesn't show up correctly depending on locale, on application when there is constraint violation. And I speak about custom messages __ONLY__, but rest of messages work fine. I also confirm this.

If I used it like this
```elixir
|> unique_constraint([:email, :job_id],
      name: :index_candidate_applied_for_the_job,
      message: gettext("this email address applied already for that job")
    )
```
Of course it doesn't appear in any `errors.po` file because I didn't specify here any domain so it appears in `default.po` files in all languages and it works as expected when there is constraint violation. If this is the normal behavior that custom error messages should not go to `errors.po` files then there is no issue and I will have to use mixed `default.po` files contain normal text and errors text.

**Comment by josevalim** [comment]
> Nothing appear in any errors.po file in any language, I can confirm this. And I think this is wrong, it should go to all errors.po files automatically because it is at the end an error message.

The current behaviour is correct. The entries in errors.pot were manually added by Phoenix generator, because those messages come from inside Ecto. You can even see the entries themselves in the .pot file do not have the gettext comment/annotation saying they were extracted. So it is expected they don't automatically show up. You could add it manually though or use dgettext/gettext.

> Message appear in all errors.po files in all languages, but it doesn't show up correctly depending on locale, on application when there is constraint violation, only shows ARABIC version

As mentioned above, I could not reproduce this behaviour. So we would need a sample application that does it.

> Of course it doesn't appear in any errors.po file because I didn't specify here any domain so it appears in default.po files in all languages and it works as expected when there is constraint violation. 

Yes, if you don't use dgettext, then it goes to default. This is also expected. So your options are:

1. add it manually to errors.pot
2. reproduce the error
3. use gettext

We understand the issue. We are saying we can't reproduce it though.

**Comment by alaadahmed** [comment]
OK my mistake then, I didn't know that these error messages in `errors.po` files generated by __Phoenix__ I thought they are generated whenever I add any custom error message inside any `validation` function. This clarify everything. I appreciate your time to explain me. Thanks a lot @josevalim

**Comment by josevalim** [comment]
Glad to help!
