### ISSUE TITLE
mixed keys check in `Ecto.Changeset.cast` not working for params which has more than 32 keys

### ISSUE THREAD

**Issue by Ljzn** [elixir-ecto/ecto#3666]
### Environment

* Ecto version (mix deps): ~> 3.5.8

### Current behavior

When iterating a map, the keys are ordered only when map size not larger than 32.

```ex
iex(2)>   mixed_map = fn size ->
...(2)>     for x <- 1..size, into: %{} do
...(2)>       if x == 18 do
...(2)>         {:atom, x}
...(2)>       else
...(2)>         {"#{x}", x}
...(2)>       end
...(2)>     end
...(2)>   end
#Function<44.79398840/1 in :erl_eval.expr/5>
iex(3)> mixed_map.(32) |> :maps.iterator() |> :maps.next() |> elem(0)
:atom
iex(4)> mixed_map.(33) |> :maps.iterator() |> :maps.next() |> elem(0)
"33"
iex(5)> mixed_map.(34) |> :maps.iterator() |> :maps.next() |> elem(0)
"33"
iex(6)> mixed_map.(35) |> :maps.iterator() |> :maps.next() |> elem(0)
"33"
```

So the mixed keys check here won't work when `params` has more than 32 keys https://github.com/elixir-ecto/ecto/blob/2c88eb4bdf91a6bb3121d63b66163878e61ab702/lib/ecto/changeset.ex#L589-L631 
 

### Expected behavior

Mixed key check works as expected when `params` has more than 32 keys.

**Comment by josevalim** [comment]
The mixed keys check is just a safety to help users catch mistakes, but it is not guaranteed to raise. In this case, making sure the check applies to all keys would be too expensive and it had appeared in profiling code before, so we don't intend to change it. I will add a note to the source, thanks!

**Comment by josevalim** [comment]
@zorbash I don't think we raise on "potentially invalid data". Mixed keys are invalid, period. We may not raise, but if we raise, we have invalid data for sure.

**Comment by zorbash** [comment]
@josevalim Thank you for your quick reply. The part about "potentially invalid data" I copied directly from the [doc](https://github.com/elixir-ecto/ecto/commit/faac9e082b89ef426b685528ee70a94140487822#diff-edb6c9aaeb40387eb81c6b238954c0b4d813876d18805c6ae00d7ccc4d78e3f1R415-R416) I wasn't trying to imply anything with the quotes 😅.

If mixed keys are not potentially invalid data but certainly invalid, then it might be a good idea to explain why in the doc and the tests.

The changeset tests won't fail if we stop raising the mixed keys exception.

```diff
diff --git a/lib/ecto/changeset.ex b/lib/ecto/changeset.ex
index 228aa452..ce4d4654 100644
--- a/lib/ecto/changeset.ex
+++ b/lib/ecto/changeset.ex
@@ -882,9 +882,7 @@ defmodule Ecto.Changeset do
           if is_atom(key) do
             {Atom.to_string(key), value}
           else
-            raise Ecto.CastError, type: :map, value: params,
-              message: "expected params to be a map with atoms or string keys, " <>
-                         "got a map with mixed keys: #{inspect params}"
+            {key, value}
           end
         end
 
diff --git a/test/ecto/changeset_test.exs b/test/ecto/changeset_test.exs
index 02090496..420b9248 100644
--- a/test/ecto/changeset_test.exs
+++ b/test/ecto/changeset_test.exs
@@ -459,9 +459,10 @@ defmodule Ecto.ChangesetTest do
       cast(%Post{}, "foo", ~w(unknown)a)
     end
 
-    assert_raise Ecto.CastError, ~r"mixed keys", fn ->
-      cast(%Post{}, %{"title" => "foo", title: "foo"}, ~w())
-    end
+    changeset = cast(%Post{}, %{"title" => "foo", title: "bar"}, ~w(title)a)
+
+    assert changeset.valid?
+    assert changeset.changes ==  %{title: "foo"}
 
     assert_raise FunctionClauseError, fn ->
       cast(%Post{}, %{}, %{})
```

The case which would signify potentially invalid data, an input like `%{"title" => "foo", title: "bar"}` does not cause any exceptions and the first occurrence of the key makes the changes. 

Should we perhaps consider replacing the mixed keys exception with a more targeted explicit warning when there are duplicate keys?

In our Phoenix / Ecto apps we are occasionally seeing mixed key exceptions for inputs we consider valid. Our flow is the following:

* Cast parameters against a known schema into a map where known and expected properties become atom keys and unknown ones string keys
* We then down the line call `Ecto.Changeset.cast/4` permitting only the known and expected properties. What we see is that cast may still raise when there are mixed keys no matter whether the offending keys are permitted. So a key which would be ignored according to "All parameters that are not explicitly permitted are ignored." can nuke a request with data that our validations consider valid.

**Comment by josevalim** [comment]
The "potentially invalid data" there means something else: it means the values are potentially invalid, not that mixed keys are _potentially_ invalid. Mixed keys are 100% invalid. It is not about duplicate keys nor anything. You should not have a mixture of strings and atoms. If you have mixed keys, it is because something somewhere in your app is making them mixed.

So I don't think I will be convinced about removing the error. However, we can go one "why?" level higher: why do you have mixed keys? What are you trying to achieve? And maybe we can improve the UX/error message.
