### ISSUE TITLE
Casting an embedded schema with a default ends up with action :update instead of :insert

### ISSUE THREAD

**Issue by ccapndave** [elixir-ecto/ecto#3679]
### Environment

* Elixir version (elixir -v): Elixir 1.12.0 (compiled with Erlang/OTP 24)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8
* Ecto version (mix deps): ecto 3.6.2
* Database adapter and version (mix deps): myxql 0.5.1
* Operating system: MacOS 11.4

### Current behavior

When casting an embedded schema with `embed_one`, Ecto does not properly detect the action as `:insert` if there is a default value for the embed.

### Expected behavior

I think the action of the cast should take into account whether or not the embedded schema's PK is `nil`; if so the action should stay as `:insert`.

I have added a unit test to reproduce this error at https://github.com/ccapndave/ecto/commit/5317ab0b2d90473b271822010aeaea2109fecfc9 but I'm afraid I'm not really sure how to fix it :)

**Comment by josevalim** [comment]
It is complicated to guess scenarios like this because what happens if there was already an embed, not because of the default, but because you put it there as part of the changeset? Are you sure you want to discard it?

So in my mind you should either replace it by using the on_replace config or fix the problem at the root: which is to not have a default value, because Ecto will treat any data currently in the struct as data that actually belongs to the struct (and trying to guess otherwise can be surprising).

**Comment by josevalim** [comment]
Oh, additionally note that embeds are not required to have primary keys either, so any heuristic based on it can fail in order circumstances.

**Comment by ccapndave** [comment]
My issue is that in my use case the parent conceptually *does* have a default value - the parent is `Account` and it contains a single `Settings` embed, so when creating a new account it comes with a bunch of default settings (defined by the defaults in the `Settings` schema) - I did that based on https://github.com/elixir-ecto/ecto/issues/2634

> It is complicated to guess scenarios like this because what happens if there was already an embed, not because of the default, but because you put it there as part of the changeset? Are you sure you want to discard it?

In any case, if the whole struct has not yes been persisted and has a PK of `nil` wouldn't it still remain an `:insert`?  Could the logic simply be _if the embedded schema has a PK, and if its `nil` then the action has to be :insert_?

> Oh, additionally note that embeds are not required to have primary keys either, so any heuristic based on it can fail in order circumstances.

Absolutely - if the embedded schema has no PK then Ecto of course can't figure this out.  This is specifically for embedded schemas with PKs.

**Comment by ccapndave** [comment]
As a temporary workaround I can use this to generate the correct action:

```
%Account{}
|> Ecto.Changeset.change(settings: %Settings{})
|> Account.changeset(params)
... etc ...
```
```
