### ISSUE TITLE
Error in insert_all/3 docs

### ISSUE THREAD

**Issue by icecapp** [elixir-ecto/ecto#3684]
`Repo.insert_all/3`'s first argument should be a schema module? 

`insert_all(schema_or_source, entries_or_query, opts)`

```js
placeholders = %{blob: large_blob_of_text(...)}

entries = [
  %{title: "v1", body: {:placeholder, :blob}},
  %{title: "v2", body: {:placeholder, :blob}}
]

Repo.insert_all(entries, placeholders: placeholders)
```

https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert_all/3-placeholders

**Comment by josevalim** [comment]
Corerct. It has been fixed on master already!
