### ISSUE TITLE
Ecto docs insert/2 upsert clarification

### ISSUE THREAD

**Issue by icecapp** [elixir-ecto/ecto#3689]
https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts

`insert/2`

> an Ecto.Query that will act as an UPDATE statement, such as the one given to update_all/3

Perhaps it would help to clarify directly _in this bullet point_ that Ecto will not autogen values here either, rather than having to implicitly infer that it won't based on docs in `update_all/3`

> Keep in mind this update_all will not update autogenerated fields like the updated_at columns.

from `update_all/3`

Perhaps a verbatim copy would be clearer ? 

> an Ecto.Query that will act as an UPDATE statement, such as the one given to update_all/3. Keep in mind `insert/2` with an Ecto.Query for `on_conflict` will not update autogenerated fields like the updated_at columns.

**Comment by josevalim** [comment]
Definitely! A PR is welcome!
