### ISSUE TITLE
Transactions not working as expected

### ISSUE THREAD

**Issue by pontaoski** [elixir-ecto/ecto#3693]
### Environment

* Elixir version (elixir -v): Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgresql 13.2
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): postgrex 0.15.9

### Bug

```elixir
@spec new_local_user(Arpeggio.LocalUser.t(), Arpeggio.User.t()) :: {:ok, any} | {:error, any}
def new_local_user(local_user, user) do
  Repo.transaction(fn ->
    Repo.insert!(user |> Arpeggio.User.changeset)
    Repo.insert!(%{local_user | user_id: user.id} |> Arpeggio.LocalUser.changeset)
  end)
end
```

schemae:
```elixir
defmodule Arpeggio.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    has_one :local_user, Arpeggio.LocalUser
    has_one :remote_user, Arpeggio.RemoteUser
  end

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:id])
    |> unique_constraint(:id, name: :users_pkey)
  end
end
```
```elixir
defmodule Arpeggio.LocalUser do
  use Ecto.Schema
  import Ecto.Changeset

  schema "local_users" do
    field :username, :string
    field :email, :string
    field :password, :string
    belongs_to :user, Arpeggio.User
  end

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:username, :email, :password, :user_id])
    |> validate_required([:username, :email, :password, :user_id])
    |> unique_constraint(:username)
    |> unique_constraint(:email)
    |> unique_constraint(:user_id)
    |> assoc_constraint(:user)
  end
end
```

whenever i pass in a user with a duplicate ID to `new_local_user`, the transaction call throws an exception instead of returning an `{:error, ...}` tuple.

```
     ** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.
     
     Errors
     
         %{
           id: [
             {"has already been taken",
              [constraint: :unique, constraint_name: "users_pkey"]}
           ]
         }
     
     Applied changes
     
         %{id: 1234}
     
     Params
     
         %{}
     
     Changeset
     
         #Ecto.Changeset<
           action: :insert,
           changes: %{id: 1234},
           errors: [
             id: {"has already been taken",
              [constraint: :unique, constraint_name: "users_pkey"]}
           ],
           data: #Arpeggio.User<>,
           valid?: false
         >
```

refactoring this code to use a multi works without throwing an exception, confirming that something seems to be screwed in the imperative function impl
```elixir
def new_local_user(local_user, user) do # local_user and #user are now maps
  Ecto.Multi.new()
  |> Ecto.Multi.insert(:user, Arpeggio.User.changeset(%Arpeggio.User{}, user))
  |> Ecto.Multi.insert(:local_user, fn %{user: %{id: user_id}} ->
    %Arpeggio.LocalUser{}
    |> Arpeggio.LocalUser.changeset(%{local_user | user_id: user_id})
  end)
  |> Repo.transaction()
end
```

**Comment by josevalim** [comment]
Those versions are not equivalent. You would need to do this in the transaction version to get the same result:

    user = Repo.insert!(user |> Arpeggio.User.changeset)
    Repo.insert!(%{local_user | user_id: user.id} |> Arpeggio.LocalUser.changeset)

**Comment by pontaoski** [comment]
That's not really the problem I was pointing out, and your suggested code doesn't fix it.

The issue is, the constraint error leaks from the transaction call as an exception instead of an `{:error, ...}` tuple.

**Comment by josevalim** [comment]
That’s also expected. Any constraint failure corrupts the transaction and any further operation will fail. This is a database semantics.

What multi is doing is something like this:

     with {:ok, user} <- Repo.insert(…),
          …

if you handle the errors properly, you get the same behavior as multi.
