### ISSUE TITLE
`select` should accept non-literal atom

### ISSUE THREAD

**Issue by marcandre** [elixir-ecto/ecto#3694]
### Current behavior

```elixir
# ok:
from(p in model, select: [:id, :data]) |> Repo.all

# error:
@data :data
from(p in model, select: [:id, ^@data]) |> Repo.all

# => ** (DBConnection.EncodeError) Postgrex expected a binary, got :data. Please make sure the value you are  passing matches the definition in your table or in your query or convert the value accordingly.
```

### Expected behavior

I expect both forms to give the same result. I understand I can convert my `@data` to string, but I believe that having `literal` or `^variable_containing_same_literal` should have the same effect.

Let me know if I should make a PR.

### Environment

```
$ elixir -v
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
$ psql --version
psql (PostgreSQL) 13.3
```

**Comment by marcandre** [comment]
Argh, I should be using `^[:id, @data]`, sorry for the noise.

Is it expected that `select: [:anything, :here, :will, :be, :ignored, ^"only_one"]` will select only "only_one" field?

**Comment by josevalim** [comment]
I have to investigate. We should either raise or return all fields.

**Comment by mbramson** [comment]
I have another fun situation that I think is related:
```elixir
query = from user in User, select: ^an_integer
all_records = Repo.all(query)
** (ArgumentError) expected a list of fields in `select/2` inside `select`, got: `270313`
```

Why would I ever want to do this? This is useful when passing a query to [`Repo.insert_all/2`](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert_all/3) where I might not have that id from within the query.

**Comment by v0idpwn** [comment]
@mbramson when trying to reproduce the bug you pointed out, I got another error:

```
  1) test select with non-binary non-literals (Ecto.Integration.RepoTest)
     /Users/felipe.stival/personal/ecto/integration_test/cases/repo.exs:17
     ** (DBConnection.EncodeError) Postgrex expected a binary, got 250. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
     code: |> TestRepo.all()
     stacktrace:
       (postgrex 0.15.5) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.encode_params/3
       (postgrex 0.15.5) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
       (db_connection 2.3.1) lib/db_connection.ex:1165: DBConnection.encode/5
       (db_connection 2.3.1) lib/db_connection.ex:1263: DBConnection.run_prepare_execute/5
       (db_connection 2.3.1) lib/db_connection.ex:1359: DBConnection.run/6
       (db_connection 2.3.1) lib/db_connection.ex:557: DBConnection.parsed_prepare_execute/5
       (db_connection 2.3.1) lib/db_connection.ex:550: DBConnection.prepare_execute/4
       (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:697: Ecto.Adapters.SQL.execute!/4
       (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5
       (ecto 3.6.2) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
       (ecto 3.6.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

I'm trying to get a solution for it, but probably its on ecto_sql

**Comment by v0idpwn** [comment]
Currently, ecto/postgrex doesn't set the types when preparing a statement. This leaves postgres to infer the types. It gives us 25 (text), which makes postgrex deny other types when the query will be run, making it work for binaries only.

I'm not sure if there are solutions other than sending the types for the statement (which is probably undesirable). I tried patching to allow sending non-binaries but they will be cast to binaries in the way back from the database :)

If I'm wrong or you think there's a solid way to fix that, please let me know.

**Comment by josevalim** [comment]
The behaviour you are seeing is expected @v0idpwn. PG will default to binaries for parameterized selects. You need to do `type(^value, :integer)` or similar instead.

**Comment by v0idpwn** [comment]
Thats perfect, then @mbramson can just use `type` and it shall work out of the box (I just tested and can confirm :))
