### ISSUE TITLE
Multi Tenancy Guide with foreign keys use of default_options is wrong for WRITE operations

### ISSUE THREAD

**Issue by MMore** [elixir-ecto/ecto#3702]
I am refering to the guide at https://hexdocs.pm/ecto/multi-tenancy-with-foreign-keys.html which is very helpful. Thanks a lot for this nice documentation!

### Environment

* Elixir version (elixir -v): 1.11.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 13.2
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): 0.15.9
* Operating system: MacOS 10.15.7 

### Current behavior

It's mentioned there that `default_options/1` always sets the `org_id` for all queries.

```elixir
defmodule MyApp.Repo do
  ...

  @impl true
  def default_options(_operation) do
    [org_id: get_org_id()]
  end
end
```

> With these changes, we will always set the org_id fields in our queries, unless we explicitly set skip_org_id: true when calling the repository.

While this is true for READ operations, it's not true for WRITE operations. 

So using the code mentioned in the guide (including `prepare_query/3`), the following example code (taken from a generated Phoenix context) just works and returns orders for the given org:

```elixir
MyApp.Orders.list_orders()
```

This code does not:

```elixir
MyApp.Order.create_order(%{item: "whatever"})
```

```
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "org_id" of relation "orders" violates not-null constraint

    table: orders
    column: org_id
```

### Expected behavior

My expectation was that when I set the `org_id` with `MyApp.Repo.put_org_id/1` READs and WRITEs are covered.
Maybe I just didn't understood it correctly and it's intended that this only works for READ operations. Then we should point that out better probably. 

### Reason

Looks like that `prepare_query/3` is only used for READs but not for WRITEs. So setting the `org_id` with `default_options/1` has no effect on the query itself.

**Comment by josevalim** [comment]
This is a subtle detail that we need to make it clearer: when we refer to queries, we refer to Ecto queries, not database queries. So it covers `all`, `update_all` and `delete_all` operations. I will update it, thanks!
