### ISSUE TITLE
validate_inclusion should use Ecto.Type.equal?

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3706]
### Environment

* Elixir version (elixir -v): 1.12.2
* Ecto version (mix deps):  3.6.2

### Current behavior
Complex data structures like Decimal or DateTime are not compared using appropriate interfaces.
https://github.com/elixir-ecto/ecto/blob/9e2d6e05aad145ef37a57a213c11c7be8257ca03/lib/ecto/changeset.ex#L2003

Here is an example with Decimal:
```elixir
> {%{}, %{value: :decimal}} |> Ecto.Changeset.cast(%{value: 0}, [:value]) |> validate_inclusion(:value, Enum.map([0.0, 0.1, 0.2], &Decimal.from_float/1))    
#Ecto.Changeset<
  action: nil,
  changes: %{value: #Decimal<0>},
  errors: [
    value: {"is invalid",
     [
       validation: :inclusion,
       enum: [#Decimal<0.0>, #Decimal<0.1>, #Decimal<0.2>]
     ]}
  ],
  data: %{},
  valid?: false
>
```

### Expected behavior
Values in Ecto.Changeset.validate_inclusion function must be compared using Ecto.Type.equal?

**Comment by josevalim** [comment]
A PR is welcome. :)
