### ISSUE TITLE
Documentation for `Ecto.Embedded`

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3719]
I found, that `Ecto.Embedded` is not documented https://github.com/elixir-ecto/ecto/blob/144ea32a6da43f2f2c30af29b642a244e74d5767/lib/ecto/embedded.ex#L2, while documentation for `Ecto.Association.*` is present.
Documentation was removed explicitly in this commit https://github.com/elixir-ecto/ecto/commit/ac98aa555edecf81c6897d2a231e8c9ef57d524e, when the feature was experimental.

Is this still relevant? Could we add documentation back to the module and make it public?

**Comment by josevalim** [comment]
What is the rationale? The association documents only the struct fields. Do you have a similar need to access the embedded fields? If so, we can do it, but all other functionality in it has to be private. :)

**Comment by fuelen** [comment]
> The association documents only the struct fields. 

This is exactly what I need :)

I work on a tool that could build ERD for Ecto schemas and just found, that `__schema__(:embed, field)` returns structs which are not documented. IMO, if there is a public function, then the returned data structure has to be documented.

**Comment by josevalim** [comment]
A PR is welcome then. :) Please run `mix docs` and make sure no function appears under the module. If they do, `@doc false` them and move the current docs to code comments. Thanks! :heart:
