### ISSUE TITLE
Different error messages for the same query in iex

### ISSUE THREAD

**Issue by kayuapi** [elixir-ecto/ecto#3721]
### Environment

* Elixir version (elixir -v): 1.12.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.18
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): ecto_sql 3.6.2, postgrex 0.15.10
* Operating system: Ubuntu 20.04.2 LTS

### Current behavior

![Screenshot from 2021-08-22 12-44-14](https://user-images.githubusercontent.com/10304328/130342626-5f1c4237-98fc-4ba1-a56b-f0e4aad95e60.png)

### Expected behavior
Same error message when running `Ecto.Query.from(p in Friends.Person, where: p.last_name == ^last_name)` in iex

**Comment by josevalim** [comment]
This would be an Elixir bug. It seems we are accidentally loading the module between failures. I have fixed it on Elixir master. :) Thanks!
