### ISSUE TITLE
Second preload in query causes Ecto.Query.CastError to not be rescuable

### ISSUE THREAD

**Issue by ngeraedts** [elixir-ecto/ecto#3729]
### Environment

* Elixir version (elixir -v): 1.12.2-otp-23 
* Database and version: PostgreSQL 9.6
* Ecto version (mix deps): 3.7.0
* Database adapter and version (mix deps): postgrex 0.15.10
* Operating system: MacOS and CentOS7

### Current behavior

I am trying to handle cast errors within a query by using a rescue block. This works as expected if I only have a single preload, but when I add a second preload to the query the `Ecto.Query.CastError` that gets raised somehow escapes the rescue block I have defined.

I have created a MWE for this error, see `MyApp.get_person/1` and tests in the following repo:
https://github.com/ngeraedts/ecto-preload-error-example

If I run the above application via `iex` and call `MyApp.get_person("a")` it crashes the IEx shell process itself, restarting the expression counter back to 1. 

### Expected behavior

Adding a second preload should not cause `Ecto.Query.CastError` to bypass `rescue` blocks.

**Comment by josevalim** [comment]
Multiple preloads run in parallel. You can disable it by passing in_parallel: false. Although I would recommend validating the parameters explicitly before if that matters. :)
