### ISSUE TITLE
parent_as in assoc

### ISSUE THREAD

**Issue by dvic** [elixir-ecto/ecto#3732]
I have a question regarding a possible feature (a PR I could work on):

I sometimes have a query filter that needs to do an "exists" joined on a parent, it would be great if I could do something like:

```elixir
    query
    |> where(
      exists(
        from(
          c in assoc(parent_as(:foo), :category),
          where: c.id == ^category_id,
          select: true
        )
      )
    )
```

But now I have to manually join because I can't use `parent_as` inside `assoc`:

```elixir
    query
    |> where(
      exists(
        from(
          c in "foo_category",
          where: c.foo_id == parent_as(:foo).id and c.id == ^category_id,
          select: true
        )
      )
    )
```

Would it be easy to add support for the former? (I could work on that)

Ideally I would also like this to work (but I'm not sure how hard this is):

```elixir
    query
    |> where(
      [foo: f],
      exists(
        from(
          c in assoc(f, :category),
          where: c.id == ^category_id,
          select: true
        )
      )
    )
```

**Comment by josevalim** [comment]
Closing this. If still interested, a PR is welcome!
