### ISSUE TITLE
Schema as params

### ISSUE THREAD

**Issue by deby22** [elixir-ecto/ecto#3735]
https://github.com/elixir-ecto/ecto/blob/7ea6f0ec8882f904503156a02d47108b406dc5cf/lib/ecto/changeset.ex#L473-L476
Suggestion:
```elixir
  def cast(data, %{__struct__: _} = params, permitted, opts) do
    params = Map.from_struct(params)
     cast(data, params, permitted, opts)
  end
```

---

I tried use Ecto.Schema as DTO for communicate between services. Example below
```elixir
# user.ex
defmodule User do
  schema "user" do
    field :first_name, :string
    field :last_name, :string
    # .. other fields
  end
end

# dto.user.ex
defmodule DTO.User do
  embedded_schema
    field :first_name, :string
    field :last_name, :string
    # .. other fields
  end
end
```

Now if i have to map `User` to eg. `Employee` i have to map it before cast

```elixir
# dto.user.ex
defmodule Employee do
  schema "employee" do
    # only first_name
    field :first_name, :string
  end
end

# accounts.ex
def import_employee(user_attrs) do
  user_attrs
  |> DTO.User.validate()
  |> Map.from_struct()
  |> Employee.create()
end
```

Another solution is add changeset and catch it by pattern matching
```elixir

defmodule Employee do
 ...
   def changeset(%{__struct__: _} = params) do
       params |> Map.from_struct() |> changeset()
   end
   def changeset(params) do
     %__MODULE__{}
     |> cast(params, ...)
     # ...
   end   
 end
```

---

It will be much easier if this solution will be applied to `cast` function.

It isn't also clear because of documentation. 
https://elixir-lang.org/getting-started/structs.html#structs-are-bare-maps-underneath
Struct are bare maps underneath, but i don't know why its forbiden to use struct as params and maps are allowed.

**Comment by josevalim** [comment]
This is pretty much intentional. `cast` is about working with external data, in your case, I think you are much safer with explicit mapping from one to the other:

    %User |> Ecto.Changeset.change(%{field1: other.field1, ...})

If you want, you can create your conveniences on top of it, but i don't think it is the job of cast. Thanks!
