### ISSUE TITLE
Missing documentation for some schema reflection APIs

### ISSUE THREAD

**Issue by joeapearson** [elixir-ecto/ecto#3736]
### Environment

* Ecto version (mix deps): latest (master branch)

### Current behavior

Some of the `Ecto.Schema` reflection APIs are not publicly documented.

Here's the existing docs:  https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L399
And here is the implementation to which I'm referring: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L602

Examples of documented APIs:

* `__schema__(:fields)`
* `__schema__(:source)`
* …etc

Examples of undocumented APIs:

* `__schema__(:autogenerate)`
* `__schema__(:query)`

### Expected behavior

There should be clear documentation for all APIs which are intended to be publicly consumed.

I'm happy to provide  PR but before I do so, I wonder whether some of the APIs remain intentionally undocumented, perhaps because they're intended to be private?

**Comment by josevalim** [comment]
Yes, they are intentionally private. We can always make them public if there are use cases. :)

**Comment by joeapearson** [comment]
Fair enough!

One use case we have for `__schema__(:autogenerate)` is to be able to use the referenced MFA generator to automatically generate values during `insert_all`.

**Comment by josevalim** [comment]
With the new placeholders feature in Ecto's insert_all, it probably makes more sense to rely on that instead. Not sure if the autogenerate helps much then?

**Comment by joeapearson** [comment]
Thanks @josevalim - we can use the placeholders feature I think yes, but for auto-generated values we would still like to be able to refer to the original generating function so that we can generate new ones.  (And then subsequently if someone needs to change or extend the schema, new auto-generated values should "just work").

**Comment by josevalim** [comment]
@joeapearson in this case, perhaps a better API would be `__schema__(:autogenerate, field)`, and it autogenerates a value for you, so we are not tied to the particular storage detail of it. WDYT? Do you want to send a PR? :)
