### ISSUE TITLE
unsafe_validate_unique/4 adds an incorrect validation entry

### ISSUE THREAD

**Issue by mathieuprog** [elixir-ecto/ecto#3752]
My code fails as I assumed that keys returned by `validations/1` are field names, as mentioned here:
https://hexdocs.pm/ecto/Ecto.Changeset.html#validations/1
> The keys in the list are the names of fields, and the values are a validation associated with the field. A field may occur multiple times in the list.

However this is not always the case, for example:
```elixir
[
  unsafe_unique: [:email],
  email: {:length, [max: 160]},
  email: {:format, ~r/^[^\s]+@[^\s]+$/}
]
```

`unsafe_unique` is not a field name.

Should it rather be `email: :unsafe_unique` ?

**Comment by wojtekmach** [comment]
Good find, please send a PR!

**Comment by mathieuprog** [comment]
I just don't know which one it should be
* `email: :unsafe_unique`
* `email: {:unsafe_unique, []}`

I'm investigating. But let me know if you know it, in case you know that part really well:)

**Comment by wojtekmach** [comment]
I'd choose the latter, `email: {:unsafe_unique, []}`, given it allows us to grow it in the future.

One of the examples from the docs is:

```elixir
unsafe_validate_unique(changeset, [:city_name, :state_name], repo, message: "city must be unique within state")
```

perhaps we should save it as the following?

```elixir
city_name: {:unsafe_unique, fields: [:city_name, :state_name]}
```

it is a bit redundant but maybe that is ok. Otherwise, we have `extra_fields: [:state_name]`?

**Comment by mathieuprog** [comment]
I would avoid redundancy until someone expresses the need for that data.

**Comment by v0idpwn** [comment]
What about changing the function contract and returning `{[:a, b], :unsafe_unique}`?

**Comment by mathieuprog** [comment]
@v0idpwn My opinion, it's more simple if we know that the keys are field names. if an entry has a list of field names (instead of a field name), that adds like an extra edge case to handle.

**Comment by wojtekmach** [comment]
> `{[:a, b], :unsafe_unique}`

not sure about that. `unsafe_validate_unique` takes an `:error_key` option, defaults to the first in the list of fields, to store the error under. So I think whatever the error key is, we'd use as key in the validations/1 result.

**Comment by josevalim** [comment]
Agreed with `{error_key, {:unsafe_unique, fields: [...], ...}}`.

**Comment by mathieuprog** [comment]
Don't we want `[email: {:unsafe_unique, []}, username: {:unsafe_unique, []}]`?

Then we have the field names as keys, and is consistent with the other entries in `: validations`.

**Comment by josevalim** [comment]
@mathieuprog that also works for me but I would add `fields: all_fields` as part of keywords too (otherwise it can be ambiguous with a validation on username exclusively, for example).

At the end though, I am not sure which approach is better. I think adding only one field is easier? Also validations exist mostly for metadata on client side validations and similar and unsafe_unique is useless for said use case anyway. :)

**Comment by mathieuprog** [comment]
See PR https://github.com/elixir-ecto/ecto/pull/3753
(please can you run the test because I'm full of "(column 24, code point U+000D)t:" errors 😥)

By having the field name as a key we don't even have to update the docs and it is consistent with the other validations entries.
