### ISSUE TITLE
Embeds_many defining submodule without access to parent module functions

### ISSUE THREAD

**Issue by eliasdarruda** [elixir-ecto/ecto#3759]
### Current behavior

If I define a schema that contains a child schema and try to use a function defined in the parent module, it cant reach the parent module and throws a compilation error:

`(UndefinedFunctionError) function Foo.types/0 is undefined (function not available) 
`
```elixir
defmodule Foo do
  use Ecto.Schema

  @types [:a, :b]
  def types, do: @types

  schema "foo" do
    embeds_many :bar, Bar do
      field :subtype, Ecto.Enum, values: Foo.types()
    end
  end
end
```

However if I create a submodule that contains the same function, I can access it in the sub schema and it doesn't throw compilation error

```elixir
defmodule Foo do
  use Ecto.Schema

  defmodule Constants do
    @types [:a, :b]
    def types, do: @types
  end

  schema "foo" do
    embeds_many :bar, Bar do
      field :subtype, Ecto.Enum, values: Foo.Constants.types()
    end
  end
end
```

### Expected behavior

It should work without having to define another module to access a function, only like the first code example

**Comment by josevalim** [comment]
```
    embeds_many :bar, Bar do
      field :subtype, Ecto.Enum, values: Foo.Constants.types()
    end
```

`embeds_many :bar, Bar` is also a separate module, which means you can't access the attributes of it either. You need to either move the constants to another module or move the embeds_many schema to a separate file.
