### ISSUE TITLE
Bug when using `except` together with `order_by`

### ISSUE THREAD

**Issue by spapas** [elixir-ecto/ecto#3766]
### Environment

* Elixir version (elixir -v): IEx 1.12.1 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.1
* Ecto version (mix deps): ecto 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.11
* Operating system: Windows 10

### Current behavior

When `except` is used together with `order_by` an exception is thrown. For example, here's my queries:

```
    excluded = (from a1 in Asset,
    join: t in assoc(a1, :tags),
    where: t.id in ^excluded_tags,
    order_by: a1.name,
    preload: [:tags])

    Repo.all(from a in Asset,
    join: t in assoc(a, :tags),
    where: t.id in ^included_tags,
    except: ^excluded,
    order_by: a.name,
    preload: [:tags])
```

This throws the following exception: `ERROR 42P01 (undefined_table) missing FROM-clause entry for table "a0"`.

The problem is that ecto generates the following query:

```
SELECT a0."id", a0."name" 
FROM "assets" AS a0 INNER JOIN "assets_tags" AS a2 ON a2."asset_id" = a0."id"
INNER JOIN "tags" AS t1 ON a2."tag_id" = t1."id" WHERE (t1."id" = ANY(array[1,2,3])) except
(SELECT a0."id", a0."name" 
FROM "assets" AS a0 INNER JOIN "assets_tags" AS a2 ON a2."asset_id" = a0."id" 
INNER JOIN "tags" AS t1 ON a2."tag_id" = t1."id" WHERE (t1."id" = ANY(array[1,2,3])) ORDER BY a0."name") 
ORDER BY a0."name"
```

and specifically the `ORDER BY a0."name"` in the end. Postgres does not allow using table aliases there when operators like except (or union) are used. If you change `ORDER BY a0."name"` to `ORDER BY "name"` or `ORDER BY 2` it works fine.

I was able to make it work by changing my ecto query like this:

```
    Repo.all(from a in Asset,
    join: t in assoc(a, :tags),
    where: t.id in ^included_tags,
    except: ^excluded,
    order_by: 2,
    preload: [:tags])
```

This works but I don't like using `2` there and I would prefer to use the proper name of the column.

### Expected behavior

I was expecting the query to work.

TIA and kind regards,
Serafeim

**Comment by josevalim** [comment]
The solution in this case is to use a fragment too: `order_by: fragment("name")`. We currently have no plans to emit queries without the table prefix. In any case, thanks for the report!

**Comment by spapas** [comment]
Hello @josevalim yes it works fine using the fragment hack. Maybe you should notice that somewhere in the docs? Thank you!
