### ISSUE TITLE
`validate_subset/3` broken on custom Ecto types with `type = {:array, _}`

### ISSUE THREAD

**Issue by patrickbiermann** [elixir-ecto/ecto#3768]
Hi there, I'm pretty sure https://github.com/elixir-ecto/ecto/pull/3764 and related PRs broke `validate_subset/3` with custom Ecto types with `type = {:array, _}`.

To reproduce:
```
defmodule StringListType do
  @moduledoc """
  An Ecto type that wraps {:array, :string}.
  """

  use Ecto.Type

  def type, do: {:array, :string}

  def cast(params) when is_list(params) do
    {:ok, Enum.reject(params, fn item -> item == "" end)}
  end

  def cast(_), do: :error

  def dump(params) when is_list(params) do
    {:ok, params}
  end

  def dump(_), do: :error

  def load(data) when is_list(data) do
    {:ok, data}
  end
end
```

And validate a field of this type by `validate_subset :string_list_field, ["foo"]`. Previous behavior was working as intended, now it crashes with `no match of right hand side value: StringListType` around https://github.com/elixir-ecto/ecto/pull/3764/files#diff-edb6c9aaeb40387eb81c6b238954c0b4d813876d18805c6ae00d7ccc4d78e3f1L2042

Is there are a reason forcing us to drop the `Ecto.Type.type()` step there? Otherwise I'm guessing this would be the root cause here.

_Originally posted by @patrickbiermann in https://github.com/elixir-ecto/ecto/issues/3764#issuecomment-962427506_

**Comment by josevalim** [comment]
I think what we can do in subset is: we get the type, if it is not an array, then we call Ecto.Type.type and see if at least that is an array? And if so, we proceed with the first type. What do you think @v0idpwn?

**Comment by v0idpwn** [comment]
This PR wasn't released yet, otherwise you'd get a nicer error. The version you're running is from even before the PR that added this feature :). I believe I should've added more info about why I reverted it totally.

I think that this is expected behaviour, and believe assuming otherwise is what led to https://github.com/elixir-ecto/ecto/pull/3742#issuecomment-948320014 as well.

If you define a custom type, **we shouldn't make strong assumptions** about how it works (as assuming that inclusion operation is the same of the underlying type), because not all types are shallow. For example:

```elixir
defmodule IntegerArray do
  use Ecto.Type
  def type, do: {:array, :integer}
  def cast(value) when is_list(value), do: {:ok, :array.from_list(value)}
  def cast(_), do: :error
  def dump(value), do: :array.to_list(value)
  def load(value), do: :array.from_list(value)
end

defmodule IntegerTuple do
   use Ecto.Type
  def type, do: {:array, :integer}
  def cast({a, b}), do: {:ok, {a, b}}
  def load([a, b]), do: {a, b}
  def dump({a, b}), do: [a, b]
end
```

For these two, you will simply get an error later on in the pipeline (because they're not enumerables). But we could assume a type that has different semantics, for example:

```elixir
defmodule AdHocRange do
   use Ecto.Type
  def type, do: {:array, :integer}
  def cast([a, b]), do: {:ok, [a, b]}
  def load([a, b]), do: [a, b]
  def dump([a, b]), do: [a, b]  
end
```

(Lets just ignore that Range exists). If we look at the underlying type, we're gonna compare a list of integers. But in reality the list just represents a pair, and [5, 10] is a subset of [0, 20].

**Comment by patrickbiermann** [comment]
I sort of buy the point that custom types may not support subset operations, and the existence of non-shallow custom types calls into question whether subset validation should look at the type in the first place. Perhaps it'd be more reasonable to validate compatibility when doing the enumerable operations later in the pipeline, as @v0idpwn mentions.

Dropping support for custom types -- and doing so in a minor version -- does not seem like the right move in my view.

**Comment by josevalim** [comment]
> Dropping support for custom types -- and doing so in a minor version -- does not seem like the right move in my view.

The PR that you have linked above has not been released though, so nothing has been broken yet. Are you sure you are not using master?

**Comment by patrickbiermann** [comment]
Thanks for the quick response @josevalim! This reproduces for us on Ecto 3.7.1, my impression is that the culprit commit is https://github.com/elixir-ecto/ecto/commit/742abe047dfc50f6765f1cf39d5408a19f290615#diff-edb6c9aaeb40387eb81c6b238954c0b4d813876d18805c6ae00d7ccc4d78e3f1R2031 (line includes the match clause that crashes for us).

**Comment by josevalim** [comment]
@patrickbiermann I see. That was intended to be a bug fix but apparently it broke other cases too. :(

**Comment by josevalim** [comment]
Unfortunately I don't think there is a way out: we can't revert the breakage without breaking the fix that the PR you linked meant to address. So the question is to decide what is the correct behaviour.

**Comment by v0idpwn** [comment]
I'm a bit curious, though: why use a custom type for string lists when theres `{:array, :string}`?

**Comment by v0idpwn** [comment]
Sorry for taking so long. Took me a while to realise it indeed broke backwards compatibility. Though most of https://github.com/elixir-ecto/ecto/issues/3768#issuecomment-962518888 stand still, if it worked, it should keep working.
