### ISSUE TITLE
Combining select_merge with subquery prevents query prefix from being added to struct meta

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#3777]
### Environment

* Elixir version (elixir -v): Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.1
* Ecto version (mix deps): ecto 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.10

### Current behavior

With a plain schema for a table with at least one row:

```
MyApp.Schema |> select_merge([e], %{attr: 0}) |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)
# => "schema"
```

and

```
MyApp.Schema |> subquery() |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)
# => "schema"
```

but 

```
MyApp.Schema |> select_merge([e], %{attr: 0}) |> subquery() |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)
# => nil
```

As a result preloading associations on the returned structs _without_ providing a prefix returns no results erroneously. 

Currently can workaround the issue by resupplying the prefix option to the preload function.

### Expected behavior

Docs:

> One interesting aspect of prefixes in Ecto is that the prefix information is carried along each struct returned by a query

No exceptions are mentioned, so I would expect it to be present in every case above.

**Comment by v0idpwn** [comment]
Hello, thanks for the report!
It seems to me that this is indeed faulty behaviour (so it shouldn't be documented, but fixed). I managed to trace the difference in behaviour, but I'm still probably a bit far from a fix. If you manage to get something, prs are welcome :)

**Comment by tfwright** [comment]
If you document what you were able to trace here, I'll see if I can investigate further. :purple_heart:

**Comment by v0idpwn** [comment]
Sure!

So, with the following examples:
`MyApp.Schema |> subquery() |> select_merge([e], %{attr: 0}) |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)`
`MyApp.Schema |> subquery() |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)`
`MyApp.Schema |> select_merge([e], %{attr: 0})  |> MyApp.Repo.all(prefix: "schema") |> List.first |> Ecto.get_meta(:prefix)`

We get the correct prefix. What is in common between them?

They fall in this clause here: https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/repo/queryable.ex#L229
While the glitched one falls here: https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/repo/queryable.ex#L238

There, a function is built and it is applied later, on loading the fields. The function built for the second clause will call: https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/repo/queryable.ex#L334, and there, you can see that metadata struct is built without prefix. But there's no info about prefix there anyway.

So, the thing is:
1. Is it going through the expected flow there? If yes, we need to add prefix support. The prefix information is available when the preprocessor function is built (in query.prefix).
2. If we do (1), is there any corner-case we should be aware of?

Perhaps @josevalim can give some insight on why it works this way and how should we proceed?

**Comment by tfwright** [comment]
@v0idpwn thanks! I'm not very experienced with Ecto internals so I'm still getting my bearings and this helped orient me a bit.

Looking further, it looks like the important part of the match clause is determined by the object at `query_meta.select.from` returned by `Planner.query`:

https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/repo/queryable.ex#L203

The prefix is added to the query in a pretty straightforward way here: https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/repo/queryable.ex#L202

so the problem must be in how the source is planned here:

https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/query/planner.ex#L238-L258

From what I can tell the relevant difference is that when a subquery is the source the prefix attached is not returned again (although I'm not sure why that is only a problem when the original query is not the result of a `select_merge`). The problem can also be solved by passing the prefix option to the _subquery_ opts so that it is returned again with the result. This leads me to believe that the problem might be solvable by merging the prefix back into the subquery before it is passed back here: https://github.com/elixir-ecto/ecto/blob/0b49098f769a3a36ca16677cbee9fdb92db78f02/lib/ecto/query/planner.ex#L240

I'll see if I can open a PR with test to prove that while we wait for input from maintainers.

**Comment by tfwright** [comment]
Actually, looks like I was mistaken about passing the prefix option to subquery fixing the issue :disappointed:

**Comment by tfwright** [comment]
I was able to poke around a bit more and write a new integration test that demonstrates the bug: https://github.com/elixir-ecto/ecto/pull/3787

Unfortunately I didn't get much further than that because I couldn't isolate the prefix loading logic from the rest of the planning logic, which is quite complex. In very general terms it seems like rather than depending on the result of the planner to determine the prefix to be added to the loaded struct, the queryable module itself could be able to add it directly, since the fact that the prefix can be set at the query level implies it should be agnostic about any of the particular query operations. But even that will require substantial refactoring of the pre/post processing logic there, since there are multiple places where the prefix is read off the `from` result and added to the struct. 

I'm not sure I'm the best person to attempt that at this point, but if any experienced maintainers chime in and confirm that is the right approach, or know a better one, I would be willing to give it a shot.

**Comment by josevalim** [comment]
I played with this today and I can totally reproduce the issue. Unfortunately fixing it requires relatively large changes to the planner, so I plan to look at them tomorrow.
