### ISSUE TITLE
optimistic_lock/3 documentation or behavior incorrect

### ISSUE THREAD

**Issue by dmarkow** [elixir-ecto/ecto#3779]
### Environment

* Elixir version (elixir -v): 1.13.0-rc.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 14
* Ecto version (mix deps): 3.7.1
* Database adapter and version (mix deps): ecto_sql 3.7.1, postgrex 0.15.13
* Operating system: macOS 12.0.1

### Current behavior

The [documentation for `optimistic_lock/3`](https://hexdocs.pm/ecto/Ecto.Changeset.html#optimistic_lock/3) includes a sample schema where the `:lock_version` field has a default value of 1. The example code below it shows that creating a new Post returns an item with `lock_version: 1`, and then updating it increments it to 2. However, in actual usage, it seems that this default value gets incremented on the initial save:

```elixir
iex> post = Repo.insert!(%Post{title: "foo"})
%Post{id: 1, title: "foo", lock_version: 2}
```

### Expected behavior

Either the documentation should say to set the default value to 0 so that the value is incremented to 1 when the record is created, or the behavior of `optimistic_lock/3` should be changed to know not to increment when inserting a new record?

**Comment by josevalim** [comment]
The documentation is correct. The lock is not applied on insert, as in your example, it is applied on the changeset call, and the example does not call the changeset on insert. In fact, the changeset function is tagged for updating the struct:

```elixir
        def changeset(:update, struct, params \\ %{}) do
          struct
          |> Ecto.Changeset.cast(params, [:title])
          |> Ecto.Changeset.optimistic_lock(:lock_version)
        end
```

So you have two options: set it to zero as you said or only call it on update. The number itself doesn't matter, so whatever is more convenient to you!
