### ISSUE TITLE
ParameterizedType in `type/2`

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3784]
### Environment

* Elixir version (elixir -v): 1.12
* Database and version: PostgreSQL 11.8
* Ecto version (mix deps): 3.8.0-dev
* Database adapter and version (mix deps): "0.15.13"

Initially I was trying to do this:

```elixir
"users"
|> select([u], fragment("CASE WHEN ? THEN ? ELSE ? END", is_nil(u.joined_at), :pending, :active))
|> limit(1)
|> Repo.all()
```
<details>
  <summary> Error</summary>

_The error is a bit cryptic, is it possible to improve it?_
```
** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.Connection.expr/3    
    
    The following arguments were given to Ecto.Adapters.Postgres.Connection.expr/3:
    
        # 1
        :pending
    
        # 2
        {{[34, "users", 34], [117 | "0"], nil}, []}
    
        # 3
        #Ecto.Query<from u0 in "users", limit: 1,
         select: fragment("CASE WHEN ? THEN ? ELSE ? END", is_nil(u0.joined_at), :pending, :active)>

    (ecto_sql 3.7.1) lib/ecto/adapters/postgres/connection.ex:590: Ecto.Adapters.Postgres.Connection.expr/3
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.7.1) lib/ecto/adapters/postgres/connection.ex:648: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.7.1) lib/ecto/adapters/postgres/connection.ex:1282: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.7.1) lib/ecto/adapters/postgres/connection.ex:340: Ecto.Adapters.Postgres.Connection.select/3
    (ecto_sql 3.7.1) lib/ecto/adapters/postgres/connection.ex:113: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.7.1) lib/ecto/adapters/postgres.ex:102: Ecto.Adapters.Postgres.prepare/2
    (ecto 3.7.1) lib/ecto/query/planner.ex:180: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.7.1) lib/ecto/query/planner.ex:150: Ecto.Query.Planner.query_prepare/6
    (ecto 3.7.1) lib/ecto/query/planner.ex:125: Ecto.Query.Planner.query_with_cache/7
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:203: Ecto.Repo.Queryable.execute/4
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

</details>

### Current behavior

```elixir
"users"
|> select(
  [u],
  type(
    fragment("CASE WHEN ? THEN ? ELSE ? END", is_nil(u.joined_at), "pending", "active"),
    {:parameterized, Ecto.Enum, Ecto.Enum.init(values: [:active, :pending])}
  )
)
```
error:
```
** (Ecto.Query.CompileError) type/2 expects an alias, atom or source.field as second argument, got: `{:parameterized, Ecto.Enum, Ecto.Enum.init(values: [:active, :pending])}`
    (ecto 3.8.0-dev) expanding macro: Ecto.Query.select/3
    iex:8: (file)
    (elixir 1.10.4) expanding macro: Kernel.|>/2
    iex:8: (file)
```
### Expected behavior
Support parameterized types in `Ecto.Query.API.type/2`

**Comment by josevalim** [comment]
You should use the type of the column instead:

    type(fragment, t.column_with_type_enum)

Other than that, we should indeed raise for atoms in fragments (or anywhere in a query really, unless they have been cast to a parameterized type).

**Comment by fuelen** [comment]
Ah, I see, there is a similar issue https://github.com/elixir-ecto/ecto/issues/3767, so virtual field is a solution.

> Other than that, we should indeed raise for atoms in fragments (or anywhere in a query really, unless they have been cast to a parameterized type).

Should current issue be used for that? Feel free to close if not.

**Comment by v0idpwn** [comment]
I think there is value in supporting parameterized types on type/2, as I pointed in the comment at #3767. I'm just not sure about how can we do it. Perhaps adding `type/3`? I just wouldn't like to expose the `{:parameterized, type, params}` to the user.

**Comment by josevalim** [comment]
Closing this. Either refer to a field or use `@my_type Ecto.ParameterizedType.init(Ecto.Enum, values: ...)` to instantiate the type that you can pass as second argument. :)
