### ISSUE TITLE
Placeholder functionality of `insert_all/3` does not work with queries

### ISSUE THREAD

**Issue by jaminthorns** [elixir-ecto/ecto#3793]
### Environment

* Elixir version: 1.12.3
* Database and version: PostgreSQL 13.4
* Ecto version: 3.7.1
* Database adapter and version: `Ecto.Adapters.Postgres`, 3.7.0
* Operating system: macOS 11.6.1

### Current behavior

The documentation for `Ecto.Repo.insert_all/3` shows the placeholders functionality with the following code example:

```elixir
placeholders = %{blob: large_blob_of_text(...)}

entries = [
  %{title: "v1", body: {:placeholder, :blob}},
  %{title: "v2", body: {:placeholder, :blob}}
]

Repo.insert_all(Post, entries, placeholders: placeholders)
```

Another, recently added feature of `insert_all/3` is the ability to pass a query as the 2nd arg instead of a list of entries. The placeholder functionality does not work as expected when using a query. If attempting to use placeholders with a query, you'll get the following error message:

```
** (Postgrex.Error) ERROR 42601 (syntax_error) INSERT has more target columns than expressions
```

It seems like `Ecto.Query` understands to not select the columns for which `{:placeholder, _}` was provided, but `insert_all/3` still expects all columns to be provided.

### Expected behavior

I'm guessing this functionality should be possible by passing the placeholders as interpolated query params (`$1`, `$2`, etc.) to be added to the `SELECT`, so ideally this functionality should be supported. If for some reason it's not possible, though, it should be documented that the placeholders functionality is incompatible with using a query for `insert_all/3`.

**Comment by josevalim** [comment]
Correct, placeholders only work with values. The biggest benefit is sending the value once but with queries we will have to inline the query multiple times, so there is no much benefit in using placeholders (plus it would be considerably more complex). :)

**Comment by jaminthorns** [comment]
I just realized shortly after submitting this issue that they're completely unnecessary with queries because you can already interpolate params. 🤦‍♂️ Thank you for the prompt response!
