### ISSUE TITLE
Passing sigils to Ecto.Query.from's select option produces subtly different query and nonsense results

### ISSUE THREAD

**Issue by zimmydev** [elixir-ecto/ecto#3800]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres (PostgreSQL) 14.1
* Ecto version (mix deps): ecto 3.7.1
* Database adapter and version (mix deps): postgrex 0.15.13
* Operating system: macOS Catalina 10.15.7

### Current behavior

Passing in a words-sigil with an atom modifier to the `select` option produces a different result than passing in an identical list with no syntactic sugar, and it is a very subtle and hard-to-find bug.

Specifically, the queries `from a in "artists", select: [:id, :name]` and `from a in "artists", select: ~w(id name)a` both produce similar-looking queries via the `Inspect` protocol (i.e. `#Ecto.Query<from a0 in "artists", select: [:id, :name]>`). However, when run on the repository, they produce completely different results. More specifically, running `Repo.all/1` on the former in my test database results in `[%{id: 1, name: "Miles Davis"}]` and the latter results in `[[:id, :name]]`.

### Expected behavior

`from a in "artists", select: [:id, :name]` and `from a in "artists", select: ~w(id name)a` should return identical queries since `[:id, :name] == ~w(id name)a`.

**Comment by aegatlin** [comment]
I was able to reproduce this behavior (shown below). I think the root cause is you are passing a `~w` sigil macro into another macro, `Ecto.Query.from`. Macros receive the representation of code instead of the results of code (see near the end of the [intro section here](https://hexdocs.pm/elixir/1.12/Macro.html). `quote do: ~w(a b)a` shows a different representation to `quote do: [:a, :b]`.

If you assign the sigil to a variable and then pin that variable to the query, it will work as desired (see below).

The first query is standard with expected output. The second using the sigil with unexpected output. The third uses a pinned variable of the sigil with expected output.

```elixir
iex(61)> q = Ecto.Query.from Artist, select: [:id, :name] 
#Ecto.Query<from a0 in Friends.Artist, select: [:id, :name]>
iex(62)> q |> Repo.all                                    

13:57:16.130 [debug] QUERY OK source="artists" db=0.6ms idle=1586.3ms
SELECT a0."id", a0."name" FROM "artists" AS a0 []
[
  %Friends.Artist{
    __meta__: #Ecto.Schema.Metadata<:loaded, "artists">,
    id: 1,
    name: "alice"
  },
  %Friends.Artist{
    __meta__: #Ecto.Schema.Metadata<:loaded, "artists">,
    id: 2,
    name: "bob"
  }
]
```

```elixir
iex(63)> q = Ecto.Query.from Artist, select: ~w(id name)a 
#Ecto.Query<from a0 in Friends.Artist, select: [:id, :name]>
iex(64)> q |> Repo.all                                   

13:57:27.459 [debug] QUERY OK source="artists" db=0.2ms queue=0.4ms idle=1915.2ms
SELECT TRUE FROM "artists" AS a0 []
[[:id, :name], [:id, :name]]
```

```elixir
iex(65)> s = ~w(id name)a
[:id, :name]
iex(66)> q = Ecto.Query.from Artist, select: ^s          
#Ecto.Query<from a0 in Friends.Artist, select: [:id, :name]>
iex(67)> q |> Repo.all                         

13:57:51.867 [debug] QUERY OK source="artists" db=1.4ms idle=1322.6ms
SELECT a0."id", a0."name" FROM "artists" AS a0 []
[
  %Friends.Artist{
    __meta__: #Ecto.Schema.Metadata<:loaded, "artists">,
    id: 1,
    name: "alice"
  },
  %Friends.Artist{
    __meta__: #Ecto.Schema.Metadata<:loaded, "artists">,
    id: 2,
    name: "bob"
  }
]
```

**Comment by aegatlin** [comment]
related to #2958

**Comment by v0idpwn** [comment]
Thanks for the very detailed explanation, @aegatlin!
This discrepancy in behaviour is still a bug, though. I opened a PR that fixes it, but until it gets released, the pin workaround should work perfectly :)
