### ISSUE TITLE
How can I add "comments" to "columns" via Ecto.Migration.CreateTable.add?

### ISSUE THREAD

**Issue by mrjbj** [elixir-ecto/ecto#3810]
I'm trying to add column comments to the metadata in my postgres database as part of the create_table function executed by Ecto migrations.  I understand there are options on the add function for things like :null, :references, etc., but not one for :comment, which would be nice.   For now, I'm handling this via the "execute()" function, but am wondering if this is best way or if would make sense to add a :comments option directly to add() to make this easier.    

(I'm new to GitHub so hope that posting this question as an "issue" is acceptable. Thank you for your time to respond and I hope to be skilled enough to contribute to this awesome project directly someday).

**Comment by josevalim** [comment]
Welcome!

According to the docs, you can pass it as an option to add: https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-comments

Let me know if it works and, generally speaking, use ElixirForum for general questions :)

**Comment by josevalim** [comment]
Ah, apparently it is not documented on each individual function. If you want, you can submit a PR here: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/migration.ex#L927 - but the module docs should cover it!

**Comment by mrjbj** [comment]
that's perfect.  Thank you.  I'll post to eilixir forum in the future.
