### ISSUE TITLE
Error casting values in some cases

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#3813]
### Environment

* Elixir version (elixir -v): 1.11
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgresql 13
* Ecto version (mix deps): 3.7
* Database adapter and version (mix deps): Postgres 0.15.10
* Operating system: Ubuntu 20.04

### Current behavior

I have a bigint column (pk) in my db. 

```
SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'canvassers' AND column_name = 'id' and table_schema = 'prefix';
 column_name | data_type 
-------------+-----------
 id          | bigint
(1 row)
```

*I don't think the schema is relevant but I'm including it just in case*

The following two query raised an unexpected error:

```
 (Turfs.Turf
      |> join(:inner, [t], assoc(t, :canvassers))
      |> where([..., c], c.id == coalesce(^Changeset.get_field(changeset, :canvasser_id), 0))
      |> Repo.one(prefix: "prefix"))
```

```
 (Turfs.Turf
      |> join(:inner, [t], assoc(t, :canvassers))
      |> where([..., c], c.id == ^5000000341)
      |> Repo.one(prefix: "prefix"))
```

```
Postgrex expected an integer in -2147483648..2147483647, got 5000000341. Please make sure the value you are passing matches the definition in your table or in your query or convert the value according
```

The following queries do **not** throw the error:

```
 (Turfs.Turf
      |> join(:inner, [t], assoc(t, :canvassers))
      |> where([..., c], c.id == ^Changeset.get_field(changeset, :canvasser_id, 0))
      |> Repo.one(prefix: "prefix"))
```

```
 (Turfs.Turf
      |> join(:inner, [t], assoc(t, :canvassers))
      |> where([..., c], c.id == coalesce(5000000341, 0))
      |> Repo.one(prefix: "prefix"))
```

```
Canvassing.Canvasser |> where(id: ^5000000341) |> Repo.one(prefix: "prefix")
```

### Expected behavior

I would expect all these queries to work (despite some of them being arguably suboptimal) since the db column type does in fact match the passed value in all cases.

**Comment by josevalim** [comment]
This is unexpected. Can you please provide a simple app (or a failure in ecto_sql/postgrex test suite) that reproduces this error for us to take a futher look?

**Comment by v0idpwn** [comment]
I managed to reproduce the `coalesce/2` situation. It happens because the prepared statements expects int4 (32 bits). Postgres infers that it should receive int4, as the second argument is an int4 (0). Then postgrex will crash when it sees that the value is not an int4.

I didn't manage to reproduce the other one.

**Comment by josevalim** [comment]
Hrm, nothing we can do in this case then, you need to tell Postgres that it is a int8. Does `type(0, :bigint)` work? Or you need to wrap coalesce in the type call?

**Comment by tfwright** [comment]
Can confirm that I can't reproduce the second error case above now. Seems to only affect coalesce when pinning the first value and not the second.

Errors:

```
Canvassing.Canvasser |> where([c], c.id == coalesce(^5000000341, 0)) |> Repo.one()
```

Doesn't error:

```
Canvassing.Canvasser |> where([c], c.id == coalesce(^5000000341, 5000000341)) |> Repo.one()
```

```
Canvassing.Canvasser |> where([c], c.id == coalesce(5000000341, 0)) |> Repo.one()
```

I couldn't figure out how to use type to mitigate the situation.

**Comment by josevalim** [comment]
`c.id == type(coalesce(5000000341, 0), :bigint)`. If that doesn't work, you may need to use the main/master branch!

**Comment by josevalim** [comment]
Ah, I see. You should also be able to cast the default value too then. I assume Postgres treats 0 as int4 or similar by default, hence the issue. In any case, it is not an Ecto bug, that’s how parameterized queries in PG work!
