### ISSUE TITLE
Type Caching Errors on Insert

### ISSUE THREAD

**Issue by mmmries** [elixir-ecto/ecto#3820]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11
* Ecto version (mix deps): `~>3.5` (specifically using 3.5.8 in mix.lock)
* Database adapter and version (mix deps): `{:postgrex, "~> 0.15"}` (0.15.6 in mix.lock)
* Operating system: MacOS and Linux

### Current behavior

Include code samples, errors and stacktraces if appropriate.

* create a new table with an bigint field (using `Ecto.Adapters.SQL.execute_ddl(...)`)
* insert data into table (using `Repo.insert_all(...)`)
* drop and re-create a table with the same name, but with a text field (using `Ecto.Adapters.SQL.execute_ddl(...)` again)
* insert data into table (using `Repo.insert_all(...)` again)
* Get a type error from Postgrex

```
** (DBConnection.EncodeError) Postgrex expected an integer in -9223372036854775808..9223372036854775807, got "1". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.15.6) lib/postgrex/type_module.ex:897: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.15.6) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.2.2) lib/db_connection.ex:1148: DBConnection.encode/5
    (db_connection 2.2.2) lib/db_connection.ex:1246: DBConnection.run_prepare_execute/5
    (db_connection 2.2.2) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection 2.2.2) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
    (db_connection 2.2.2) lib/db_connection.ex:532: DBConnection.prepare_execute/4
    (postgrex 0.15.6) lib/postgrex.ex:214: Postgrex.query/4
    (ecto_sql 3.5.1) lib/ecto/adapters/sql.ex:371: Ecto.Adapters.SQL.query!/4
    (ecto_sql 3.5.1) lib/ecto/adapters/sql.ex:660: Ecto.Adapters.SQL.insert_all/8
    (ecto 3.5.8) lib/ecto/repo/schema.ex:54: Ecto.Repo.Schema.do_insert_all/6
    (peg 0.1.0) lib/ce/derived_database.ex:338: CE.DerivedDatabase.paginate_through/3
    (peg 0.1.0) lib/ce/derived_database.ex:351: CE.DerivedDatabase.populate_table/1
```

> I can setup a minimal reproducible as a github repo, but I think this might be a known issue or it may be outside of the scope of Ecto to work with dynamic schemas, so I didn't set this up yet. Please. let me know if you'd like me to build this minimal reproducible

It might also be useful to note that when I started our app with a connection pool with a single connection, this error did not occur. But if I have multiple connections in the pool, then the issue occurs.

### Expected behavior

I *suspect* that this relates to caching of prepared statements, or maybe caching column types, and I am hoping that there is either an API that our system can call when we need to clear the cache, or that the cache would automatically clear when we execute a DDL that changes the schema.

I'm not sure if this use-case is within the scope of Ecto as a project and I totally understand if it's not worth addressing for the whole community. Thanks for all you do to make such a great ecosystem of tools ❤️ 💛 💙 💚 💜

**Comment by josevalim** [comment]
We do have provisions for when a field is missing but you are correct that the field changing type is very unlikely to happen dynamically. We could handle this but it would make all type errors potentially very expensive if it forces us to recompute the types.

In your case, you have a couple options: disable prepared queries by setting `prepare: :unnamed`. Or force a disconnect, there is a new API to do so here: https://github.com/elixir-ecto/db_connection/issues/99#issuecomment-968304864

I will close this but feel free to ask if you have questions :)

**Comment by mmmries** [comment]
Thanks @josevalim, thanks for the pointer to the new `disconnect_all` API. I'll check into that and/or using `prepare: :unnamed`
