### ISSUE TITLE
Saving nested records with prefixed multitenancy

### ISSUE THREAD

**Issue by Valian** [elixir-ecto/ecto#3827]
### Environment

* Elixir version (elixir -v): `Elixir 1.13.2 (compiled with Erlang/OTP 24)` 
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `PostgreSQL 14.1`
* Ecto version (mix deps): `ecto 3.7.1` 
* Database adapter and version (mix deps):  ` 0.15.13`
* Operating system: Docker image (debian)

### Current behavior

`Repo.insert!(prefix: prefix)` overrides association prefixes set through `@schema_prefix` or `Ecto.put_meta`. 

I’m building a multi-tenant application. Some tables are in a public schema, and some are in tenant-specific schemas. In tests I’m using factory pattern described [here](https://hexdocs.pm/ecto/test-factories.html). Currently it's hard to write nested factories for multi-tenant application. Here is a simplified example where I have a tenant-specific `GameSession` table and shared `Game` table. I'd like to create tenant-specific and shared records in one go, but currently it doesn't work.

```elixir
defmodule MyApp.Factories do
  def build(:game) do 
    # Game has @schema_prefix "public"
    # Ecto.put_meta(prefix: prefix) also doesn't work
    %Myapp.Game{name: "test"}  
  end
   
  def build(:game_session) do
    # no @schema_prefix, should be saved in a tenant schema
    %Myapp.GameSession{game: build(:game)}  
  end
end
```

```elixir
test "game session factory works correctly", %{tenant: tenant} do
  MyApp.Factories.build(:game_session)
  |> MyApp.Repo.insert!(prefix: tenant.prefix)
end
```

Error
```
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "tenant.game" does not exist
```

### Expected behavior

I think `prefix` in Repo commands shouldn't override prefixes in associations set through `@schema_prefix` or `Ecto.put_meta`.

I believe it's the way how prefix-based multitenancy should work. Developers mark shared tables with `@schema_prefix "public"` and do not mark tenant-specific tables (since we can't really mark them, schema is determined at runtime). Repo operations should only update associated records prefixes if they doesn't have any prefix set. 

Current workaround is not really easy, since it can't use `insert!(prefix: prefix)`.

```elixir
defmodule MyApp.Factories do
  def build(:game) do
    %Myapp.Game{name: "test"}  
  end
   
  def build(:game_session, tenant) do
    # no @schema_prefix, should be saved in a tenant schema
    %Myapp.GameSession{game: build(:game)} |> Ecto.put_meta(prefix: tenant.prefix)
  end
end
```

```elixir
test "game session factory works correctly", %{tenant: tenant} do
  MyApp.Factories.build(:game_session, tenant)
  |> MyApp.Repo.insert!()
end
```

It's even more important for me since I'm using process dict to keep active tenant around, adding it automatically to each repo operation. If I'm correct, it's impossible to **unset** prefix set through `default_options` in `Repo.insert!`? 
 
 ```elixir
 defmodule MyApp.Repo do
  @tenant_schema {__MODULE__, :tenant_id}

  def set_active_schema(schema) do
    Process.put(@tenant_schema, schema)
  end

  def get_active_schema() do
    Process.get(@tenant_schema)
  end

  @impl true
  def default_options(_operation) do
    [prefix: get_active_schema() || "public"]
  end
end
 ```
 
I believe it would be a breaking change, though... Do you think my use case is valid? Are there any better approaches that might work?

**Comment by josevalim** [comment]
It is a bug and we need to address it because it is documented to work in the way you described. Here is most likely the line causing an issue: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/schema.ex#L644

it should be `prefix || opts[:prefix]`.

**Comment by josevalim** [comment]
I have taken a further look at this:

1. Insert across prefixes may not necessarily work in a transaction since prefixes may be different databases

2. `insert(..., prefix: "foo")` was added to override all prefixes because we wanted it to cascade to associations (especially given 1 above)

I will update the docs and guides for now. I recommend changing your default options to set the prefix based on the operation.

**Comment by josevalim** [comment]
Further updates: the guides were wrong but the docs were correct. I have fixed the guides. Thank you.

**Comment by Valian** [comment]
Thank you @josevalim, it's clear now 🤓 I was not paying attention how prefix works in MySQL so issue with transactions never came to my mind. 

I'll skip prefix for inserts in default options in tests and in factories I'll explicitly set prefix for associations 👍
