### ISSUE TITLE
Arguments to `timestamps()` are not passed to overridden `autogenerate` MFA

### ISSUE THREAD

**Issue by tshakah** [elixir-ecto/ecto#3836]
If you override the `autogenerate` function in `@timestamps_opts`:

```
@timestamps_opts [
  autogenerate: {Some.Module, :utc_now, []},
  type: :utc_datetime_usec
]
```

If in a schema you set `type` manually:

```
  schema "some_schema" do
    timestamps(type: :utc_datetime)
  end
```

The `type` (or opts in general) are not passed to `Some.Module.utc_now`. Is there a recommended way to do this?

The code above leads to error messages about unexpected precision: `** (ArgumentError) :utc_datetime expects microseconds to be empty`, so clearly the `type` opt is being used elsewhere.

I can see in the [source](https://github.com/elixir-ecto/ecto/blob/a1309eecc0e3931f6602ce7c544936954539b1d5/lib/ecto/schema.ex#L749) that nothing is passed - is it possible to have an autogenerate function that defaults to millisecond-precision, but allows second-precision to be set (or takes opts in general), or am I going about this the wrong way?

For context, I was implementing something [like this blog post outlines](https://codeincomplete.com/articles/testing-dates-in-elixir), as it seems like a nice way of overriding dates in tests, but some of my schemas require usec, and others sec.

**Comment by josevalim** [comment]
You need to either set a whole new `@timestamp_opts` or pass the autogen to `timestamp` too, as the options are merged.

But at this point, perhaps what makes the most sense is for you to define your own timestamp macro:

```elixir
defmodule MyApp.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      import Ecto.Schema, except: [timestamp: 0]
      import MyApp.Schema
    end
  end

  defmacro timestamp() do
    ... do anything you want here ...
  end
end

**Comment by tshakah** [comment]
Ah, I can't use the custom `timestamps` definition as using `Ecto.Schema` [imports it as well](https://github.com/elixir-ecto/ecto/blob/2c16cf65b4d9758c9b2031c452a6aff74e7eb597/lib/ecto/schema.ex#L591).

I'll go with passing in the autogen to `timestamps/1`, thanks for your help 😃

**Comment by tshakah** [comment]
I don't need to set it in too many places, so it's a little verbose to add `timestamps(autogenerate: {}, type: :utc_datetime)` but really not that bad
