### ISSUE TITLE
Skip redefining the module for inline schema when embeds_one and embeds_many is used with same data structure.

### ISSUE THREAD

**Issue by AlexandruCD** [elixir-ecto/ecto#3838]
### Environment

* Elixir version (elixir -v): Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Ecto version (mix deps): 3.7.1

### Current behavior

If using inline embedded schema, there is no way to bypass redefining the module(in parent namespace) if using embed_one and embed_many with the same structure.
```
 schema "item" do
    
    embeds_many :details, Detail, primary_key: false do
      field(:item_detail_type, :map)
    end

    embeds_one :last_detail, Detail, primary_key: false do
      field(:item_detail_type, :map)
    end
  end
```

The obvious warning: `redefining module A.B.C.Detail`
### Expected behavior
A way to skip redefining the module for inline schemas.

**Comment by v0idpwn** [comment]
My suggestion is doing something like

```elixir
defmodule Parent 
  defmodule Child
    embedded_schema do
     # ...
    end
  end

  embedded_schema do
    has_one :favorite_child, Child
    has_many :ordinary_children, Child
  end
end
```

**Comment by josevalim** [comment]
Yes, in this case you need to define the child separately. :)
