### ISSUE TITLE
Select fields do not match when using a union in a preload

### ISSUE THREAD

**Issue by MarcusHoile** [elixir-ecto/ecto#3839]
### Environment

* Elixir version: 1.13.0
* Database and version: PostgreSQL 12.3
* Ecto version: 3.7.1
* Database adapter and version: postgrex 0.16.2
* Operating system: MacOS 10.15.7

### Current behavior

```elixir
defmodule MyApp do
  def query do
    from(u in User, preload: [posts: ^user_posts()])
    |> Repo.all()
  end

  def user_posts do
    posts_with_comments()
    |> union(^posts_with_tags())
  end

  def posts_with_comments do
    from(p in Post, join: c in assoc(p, :comments))
  end

  def posts_with_tags do
    from(p in Post, join: t in assoc(p, :tags))
  end
end
```

`MyApp.query()` will raise an error as the select fields do not match. The left query, `post_with_comments`, has posts.user_id selected twice and the right query, `post_with_tags` has the select fields you would expect.

```
** (Postgrex.Error) ERROR 42601 (syntax_error) each UNION query must have the same number of columns

         query: SELECT p0."id", p0."title", p0."user_id", p0."inserted_at", p0."updated_at", p0."user_id" FROM "posts" AS p0 INNER JOIN "comments" AS c1 ON c1."post_id" = p0."id" WHERE (p0."user_id" = ANY($1)) UNION (SELECT p0."id", p0."title", p0."user_id", p0."inserted_at", p0."updated_at" FROM "posts" AS p0 INNER JOIN "tags" AS t1 ON t1."post_id" = p0."id") ORDER BY p0."user_id"
```

I have an example app with failing test that shows the issue https://github.com/MarcusHoile/union_query_select_fields

### Expected behavior

I'd expect the select fields to match by default

**Comment by josevalim** [comment]
This is expected. It is your responsibility to make sure both sides of the union select the same fields, have the same preloads, and so on. :)

**Comment by MarcusHoile** [comment]
no worries. So my workaround to the example above is to match the dupe field selected which doesn't sound so crazy an idea now

```
def posts_with_tags do
  fields = Post.__schema__(:fields__) ++ [:user_id]
  from(p in Post, join: t in assoc(p, :tags), select: map(p, ^fields))

**Comment by josevalim** [comment]
I think you should use preloads on both sides, especially because we can't really preload only one side of the union.

**Comment by MarcusHoile** [comment]
I might be missing something, im not preloading on either side of the union. The union query is used as the query to preload posts

**Comment by MarcusHoile** [comment]
the union query by itself works fine `user_posts() |> Repo.all()`. the error only happens when i use the same union in a preload. I assume it is something to do with the preload builder adding the dupe select `posts.user_id`. Is that expected?

**Comment by josevalim** [comment]
Ah, yes, exactly.
