### ISSUE TITLE
valid? changeset boolean stays false, even though errors are empty

### ISSUE THREAD

**Issue by mbernerslee** [elixir-ecto/ecto#3841]
### Environment

* Elixir version (elixir -v): 1.13.2
* Ecto version (mix deps): {:phoenix_ecto, "~> 4.0"}

### Unexpected Changeset Behaviour

```
 def qualifications_changeset(candidate_or_changeset, params \\ %{})

 def qualifications_changeset(%Changeset{valid?: false} = changeset, params) do
   qualifications_changeset(%{changeset | valid?: true}, params)
 end

 def qualifications_changeset(candidate_or_changeset, params) do
   candidate_or_changeset
   |> Changeset.cast(params, [])
   |> Changeset.cast_assoc(:qualifications)
   |> Changeset.cast_assoc(:university_qualifications)
 end
```

If I didn't have the function-head that puts `valid?: false` to `valid?: true`
then when I
- call this function with a struct and invalid qualification parameters (in the assoc)
- call the function again with the result from the above function call (a changeset with errors in `:qualifications` assoc) and params that would fix the error

Then I get this

```
#Ecto.Changeset<
  action: nil,
  changes: %{
    qualifications: [
      #Ecto.Changeset<
        action: :update,
        changes: %{level: 2},
        errors: [],
        data: #Platform.EditQualifications.Qualification<>,
        valid?: true
      >,
      #Ecto.Changeset<
        action: :update,
        changes: %{level: 3, title: "hello"},
        errors: [],
        data: #Platform.EditQualifications.Qualification<>,
        valid?: true
      >
    ]
  },
  errors: [],
  data: #Platform.EditQualifications.Candidate<>,
  valid?: false
>
```

... a changeset that's invalid according to `valid?`, but that has no `:errors` anywhere
is this the intended behaviour?

Maybe the idea is that additional validation shouldn't reset the `valid?` because changesets are meant to be composable & chained together, so overriding the `valid?` bool wouldn't work?

Apologies if this is an intentional design choice, or has been fixed it a recent version.

I did a cursory search for an existing closed issue on this, but didn't find anything

**Comment by josevalim** [comment]
> Maybe the idea is that additional validation shouldn't reset the valid? because changesets are meant to be composable & chained together, so overriding the valid? bool wouldn't work?

Exactly. :) And it is actually hard to guarantee that all of the previous validations are now valid. Usually you do so by "restarting" the process, now with valid parameters. :)
