### ISSUE TITLE
cast_assoc(..., required: true) does not work as expected

### ISSUE THREAD

**Issue by mbernerslee** [elixir-ecto/ecto#3848]
### Environment

* Elixir version (elixir -v): 1.13.2
* Ecto version (mix deps): `{:phoenix_ecto, "~> 4.0"}`

### The Problem
I have a `%Struct{}` with an associated `%ChildStruct{}` and
casting the associated child_struct with its changeset is required.

See my commented test in the `@doc` below
It looks like.. if I delete my child_struct's parameters, from the parameters
then `Changeset.cast_assoc(..., required: true)` will decide that there's nothing to cast, so it won't even call `ChildStructModule.changeset/3`....
but calling it is required.. it's a must
So I'm forced to write my weird-looking `validate_child_struct_required/2`.. to invalidate the changeset to deal with this instance.

Surely there is (or should be) a better way?

I expected `Changeset.cast_assoc(..., required: true)` to deal with this issue for me.

```
  def create_changeset(struct, some_arg, attrs \\ %{}) do
    struct
    |> Changeset.cast(attrs, some_list_of_fields)
    |> validate_child_struct_required(attrs)
    |> Changeset.cast_assoc(:child_struct_name,
      with: {ChildStructModule, :changeset, [some_arg]},
      required: true
    )
  end

  @doc """
  This test was failing without the function below...

      params = Map.delete(valid_params(), "child_struct_name")

      changeset =
        create_changeset(
          %Struct{child_struct_name: %ChildStruct{}},
         some_arg,
          params
        )

      refute changeset.valid?
  """
  defp validate_child_struct_required(changeset, %{"child_struct_name" => _}) do
    changeset
  end

  defp validate_child_struct_required(changeset, _) do
    Changeset.add_error(changeset, :child_struct_name, "cannot be blank")
  end
```

I ask for forgiveness if I should / could have known better by reading the docs more thoroughly!
Cheers

**Comment by josevalim** [comment]
If there is no params, there is nothing to cast. And if there is a struct in the field, then it won’t consider it as missing. You can either force the parameter to always be there or remove the default value, but this is expected. :)
