### ISSUE TITLE
(FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.Connection.expr/3

### ISSUE THREAD

**Issue by alvarocallero** [elixir-ecto/ecto#3853]
Hi everyone,

I have an Elixir app that uses Ecto in order to execute queries in Postgres.
I have this Ecto schema:

    defmodule Person do
    
      use Ecto.Schema
    
      schema "person" do
        field :name, :string
      end
    
    end

I'm trying to make a simple select in Elixir:

    query = from Person
    result = Repo.all(query)

but after executing that code, I see this:

    ** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.Connection.expr/3

    The following arguments were given to Ecto.Adapters.Postgres.Connection.expr/3:

        # 1
        {{:., [], [{:&, [], [0]}, "name"]}, [], []}

        # 2
        {{[34, "Person", 34], [84 | "0"],
          Person}, []}

        # 3
        #Ecto.Query<from c0 in Person,
         select: c0>

    Attempted function clauses (showing 10 out of 33):

        defp expr(-{:^, [], [ix]}-, _sources, _query)
        defp expr(-{{:., _, [{:parent_as, _, [as]}, field]}, _, []}-, _sources, query) when -is_atom(field)-
        defp expr({{:., _, [{:&, _, [idx]}, field]}, _, []}, sources, _query) when -is_atom(field)-
        defp expr(-{:&, _, [idx]}-, sources, _query)
        defp expr(-{:in, _, [_left, []]}-, _sources, _query)
        defp expr(-{:in, _, [left, right]}-, sources, query) when -is_list(right)-
        defp expr(-{:in, _, [left, {:^, _, [ix, _]}]}-, sources, query)
        defp expr(-{:in, _, [left, %Ecto.SubQuery{} = subquery]}-, sources, query)
        defp expr(-{:in, _, [left, right]}-, sources, query)
        defp expr(-{:is_nil, _, [arg]}-, sources, query)
        ...
        (23 clauses not shown)

    (ecto_sql 3.7.2) lib/ecto/adapters/postgres/connection.ex:590: Ecto.Adapters.Postgres.Connection.expr/3
    (ecto_sql 3.7.2) lib/ecto/adapters/postgres/connection.ex:1284: Ecto.Adapters.Postgres.Connection.intersperse_map/4
    (ecto_sql 3.7.2) lib/ecto/adapters/postgres/connection.ex:340: Ecto.Adapters.Postgres.Connection.select/3
    (ecto_sql 3.7.2) lib/ecto/adapters/postgres/connection.ex:113: Ecto.Adapters.Postgres.Connection.all/2
    (ecto_sql 3.7.2) lib/ecto/adapters/postgres.ex:102: Ecto.Adapters.Postgres.prepare/2
    (ecto 3.7.2) lib/ecto/query/planner.ex:180: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.7.2) lib/ecto/query/planner.ex:150: Ecto.Query.Planner.query_prepare/6
    (ecto 3.7.2) lib/ecto/query/planner.ex:125: Ecto.Query.Planner.query_with_cache/7

Also same result with Repo.all.

This are the versions that I'm using:
Elixir: 1.13
ecto_sql: 3.7.2
postgrex: 0.16.2

Does anyone has any idea what is making this error?

Thanks

**Comment by josevalim** [comment]
Does it work if you do:

    query = from p in Person
    result = Repo.all(query)

Or just:

    query = Person
    result = Repo.all(query)

?

**Comment by alvarocallero** [comment]
@josevalim I just tried with your 2 suggestions, but same result.
Looks like that for some reason, when trying to call `Repo.all` or `Repo.one`, those 2 functions are not being found

**Comment by josevalim** [comment]
This is very weird. Can you provide a small app that reproduces this issue? :)

**Comment by josevalim** [comment]
Make sure to provide an actual Ecto.Repo as `Repo`. I just used `Repo` as a shortcut.

**Comment by alvarocallero** [comment]
> Make sure to provide an actual Ecto.Repo as `Repo`. I just used `Repo` as a shortcut.

Yes exactly, I put an example but in my code, I´m referencing the full path of the module

**Comment by alvarocallero** [comment]
> This is very weird. Can you provide a small app that reproduces this issue? :)

Here is an example:

```
 defmodule Repo do

   use Ecto.Repo,
      otp_app: :my_app,
      adapter: Ecto.Adapters.Postgres

  import Ecto.Query

  alias Schema.Person

  def my_function() do
     query = from p in Person
     a = Repo.all(query) #in this lines the error appears
  end

end
```

Thanks!

**Comment by josevalim** [comment]
I mean, a separate app that I can clone. :)

**Comment by alvarocallero** [comment]
@josevalim Sorry for the delay, I figured out the problem:
I have a table in a Postgres database, that contains two fields:
**person_age_123** and **person_name_123**
So on my schema on Elixir, I was trying to map those database column names to a more "friendly" field names, like **age** and **name**.

So my Elixir schema was the following:

defmodule EctoApp.Person do

  use Ecto.Schema

  schema "person" do
    field :name, :string, [source: "person_name_123"]
    field :age, :integer, [source: "person_age_123"]
  end

end

and the error was because I was using " instead of :, so I think that the idea is to incluide atoms and not strings.
If you want, I can share a repo with the whole code, but with that, you can reproduce the issue.

Let me know if you want the app anyway :)

**Comment by josevalim** [comment]
Thanks. This is great and enough! We should validate this somewhere and raise early instead of late.
