### ISSUE TITLE
Wrong result when referencing association on preload

### ISSUE THREAD

**Issue by pmargreff** [elixir-ecto/ecto#3855]
### Environment

- Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 22)
- Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres:13.5-alpine  (docker image)
- Ecto version (mix deps): ecto 3.7.2
- Database adapter and version (mix deps): postgrex 0.16.2 
- Operating system: Ubuntu 20.04

### Current behavior

When doing a join and using a preload to reference the field I want to preload, `Repo.all` always brings only one result, even when I have multiple results in the table representing the schema `Foo`.

```elixir
query = (from f in Foo,
  left_join: b in ^(from Bar),
  on: f.a == b.a and f.b == b.b
  preload: [bars: b])

  Repo.all(query)
```

The interesting part is that `Repo.aggregate(query, :count)` gives me the counter result that I expect. 

Running the SQL that Ecto creates directly in the database also gives me the expected amount of results for the query. If I pass the preload as a query (`preload: [bars: query]`) it also works as expected. So I think that Ecto is failing to send the entire set of results back to the users.

### Expected behavior

When referencing the join value in the preload the result set has multiple entries if my query has multiple results. 

### Sample repository

A working sample of the issue can be found at: https://github.com/pmargreff/ecto_preload_bug/blob/main/test/preload_bugs_test.exs

**Comment by dvic** [comment]
You could do a 

```elixir
{q, args} = Ecto.Adapters.SQL.to_sql(:all, Repo, query)
IO.puts(q)
IO.inspect(args)
```

to see what kind of query is being produced?

**Comment by pmargreff** [comment]
@dvic I've added a sample repository with the issue to lower the friction. Testing that should be as easy as a `git clone` + `mix deps.get`.  Let me know if you need any other info about the problem.

**Comment by greg-rychlewski** [comment]
If you define the primary key on the schema from the `has_many` side of the association it will work. i.e change this:

```elixir
@primary_key false
schema "pull_requests" do
  field :repo, :string
  field :number, :integer
  field :title, :string

  has_many :commits, PreloadBugs.Commit, references: :number
end
```

to this

```elixir
@primary_key {:number, :integer, autogenerate: false}
schema "pull_requests" do
  field :repo, :string
  field :title, :string

  has_many :commits, PreloadBugs.Commit, references: :number, foreign_key: :pr_number
end
```

Looking at the source code this seems like it's by design but I'm not familiar enough with it to be 100% sure.

One other thing you should do is use `belongs_to` when setting foreign keys. i.e. change this

```elixir
@primary_key false
schema "commits" do
  field :repo, :string
  field :pr_number, :integer
  field :hash, :string
end
```

to this

```elixir
@primary_key false
schema "commits" do
  field :repo, :string
  field :hash, :string
  belongs_to :pull_request, PreloadBugs.PullRequest, references: :number, foreign_key: :pr_number
end
```

**Comment by greg-rychlewski** [comment]
It happens here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/assoc.ex#L53

If you don't have a primary key then this branch won't be entered after setting it for the first time and it won't add anymore of the associations to the dictionary:

```elixir
if struct && parent_key && not Map.get(cache, cache_key, false) do
    cache = Map.put(cache, cache_key, true)
    item = {child_key, struct}

    # If we have a list, we are at the root, so we also store the sub structs
    dict = update_dict(dict, parent_key, item, sub_structs)

    {{primary_keys, cache, dict, sub_dicts}, sub_structs}
else
  ...
```

It seems like maybe another error should be raised here if `primary_keys` is an empty list:

```elixir
child_key =
      if struct do
        for primary_key <- primary_keys do
          case Map.get(struct, primary_key) do
            nil -> raise Ecto.NoPrimaryKeyValueError, struct: struct
            value -> value
          end
        end
      end
```

**Comment by josevalim** [comment]
> It seems like maybe another error should be raised here if primary_keys is an empty list:

Agreed. PR please? :)

**Comment by greg-rychlewski** [comment]
Hi @pmargreff,

Thanks for reporting this. The issue is that when using associations the schemas must have primary keys defined on them. This is how Ecto internally keeps track things when doing joins.  

This MR fixed it so that an error will be raised instead of returning erroneous results: https://github.com/elixir-ecto/ecto/pull/3867.

**Comment by pmargreff** [comment]
Hey @greg-rychlewski, thanks for the answers and the pull request. I think that explains why it works when passing a query but not referencing the own query in the preload!

Once the real joins multiple conditions (a composite key). I think the only way to have it working with this preload format is awaiting #3638, is that correct?

**Comment by josevalim** [comment]
You can pass a function to preload that does whatever you want to preload the results for you. Even talk to an external service!
