### ISSUE TITLE
Have `validate_required/3` raise when used on has_many/embed_many?

### ISSUE THREAD

**Issue by sabiwara** [elixir-ecto/ecto#3861]
### Environment

* Elixir version (elixir -v): 1.13.3
* Ecto version (mix deps): `master` branch

### Current behavior

The following would work both with embedded schemas or regular `has_many` associations:

```elixir
defmodule Post do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :text, :string
  end

  def changeset(pets, attrs) do
    pets
    |> cast(attrs, [:text])
    |> validate_required([:text])
  end
end

defmodule Author do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :name, :string

    embeds_many :posts, Posts
  end

  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name])
    |> cast_embed(:posts)  # should actually be `required: true`
    |> validate_required([:name, :posts])  # no effect
  end
end
```

The following will be considered valid:

```elixir
iex> Author.changeset(%Author{}, %{name: "John"})
#Ecto.Changeset<
  action: nil,
  changes: %{name: "John"},
  errors: [],
  data: #Author<>,
  valid?: true
>
```

The [doc for validate_required/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_required/3) points out to the actual solution, which is to add `required: true` to `cast_embed` or `cast_assoc`.
But unlike we write a unit-test to check this scenario, it is really easy to have this mistake remain unnoticed and makes it a bit of a footgun.

### Suggested behavior

Since the use of validate_required on `has_many`/`embed_many` is most likely a mistake in every possible case, maybe we could raise with an helpful message to remove, e.g.

```
attempting to validate has_many association :posts with validate_required/3 which has no effect.
You can pass the :required option to Ecto.Changeset.cast_assoc/3 to achieve this.
```

What do you think? If this issue is accepted, I have a PR ready to go.

**Comment by josevalim** [comment]
Great, can you please open up a PR then? However I think we should start with a warning to avoid breaking people's code.
