### ISSUE TITLE
Changeset constraint docs for the :match option are inconsistent

### ISSUE THREAD

**Issue by anthonator** [elixir-ecto/ecto#3863]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 14.2
* Ecto version (mix deps): ecto 3.7.2
* Database adapter and version (mix deps): postgrex 0.16.2
* Operating system: Alpine 3.15.4

### Current behavior

The `:match` option for the constraint functions on `Ecto.Changeset` are inconsistent.

For example, the documentation for `check_constraint/3`:

> `:match` - how the changeset constraint name is matched against the
      repo constraint, may be `:exact`, `:suffix` or `:prefix`. Defaults to `:exact`.
      `:suffix` matches any repo constraint which `ends_with?` `:name`
       to this changeset constraint.
      `:prefix` matches any repo constraint which `starts_with?` `:name`
       to this changeset constraint.

Notice how it provides an explanation for the `:exact`, `:suffix` and `:prefix` options.

Here is the documentation for `unique_constraint/3`:

> `:match` - how the changeset constraint name is matched against the
      repo constraint, may be `:exact` or `:suffix`. Defaults to `:exact`.
      `:suffix` matches any repo constraint which `ends_with?` `:name`
       to this changeset constraint.

Notice how there is no mention of the `:prefix` option although it is supported.

A quick skim of the source shows `check_constraint/3`, `exclusion_constraint/3` and `unique_constraint/3` should all have the same options for `:match`.

### Expected behavior

Ensure the `:match` option is properly documented for all changeset constraint functions.

**Comment by josevalim** [comment]
Good find! A Pull request is welcome!
