### ISSUE TITLE
`subquery`ing a query that `select`s a literal atom value is broken

### ISSUE THREAD

**Issue by jaminthorns** [elixir-ecto/ecto#3870]
### Environment

* Elixir version: `1.13.1`
* Database and version: PostgreSQL `13.4`
* Ecto version: Ecto `3.7.2`, Ecto SQL `3.7.2`
* Database adapter and version: Postgrex `0.16.2`
* Operating system: macOS `12.2.1 (21D62)`

### Current behavior

Looking back at the Ecto changelog from release `3.5.0`, it looks like the ability to have literal atom values within queries was added in Ecto 3.5:

> [Ecto.Query] Allow atoms in query without interpolation in order to support Ecto.Enum

I seem to have found a case where this doesn't work correctly. If I select from a table with a literal atom value:

```elixir
from tt in "test_table", select: %{test: tt.test_column, literal_value: :value}
```

The generated query looks like this:

```sql
SELECT t0."test_column" FROM "test_table" AS t0
```

It looks like `literal_value` select is excluded, which I assume is because it will later be merged back into the results, since running the query yields rows with atom values as expected. The issue comes when this query is passed to `subquery`:

```elixir
subquery(from tt in "test_table", select: %{test: tt.test_column, literal_value: :value})
```

The generated SQL attempts to select the literal atom value as a field from the subquery:

```sql
SELECT s0."test", s0."literal_value" FROM (SELECT st0."test_column" AS "test" FROM "test_table" AS st0) AS s0
```

Which breaks when trying to run the query:

```
** (Postgrex.Error) ERROR 42703 (undefined_column) column s0.literal_value does not exist
```

### Expected behavior

Either:

- Querying with a literal atom values should work in all circumstances, even within a subquery. (Preferable)
- Querying with a literal atom values should be banned in subqueries (like maps, lists, tuples and sources).

**Comment by josevalim** [comment]
Can you please try master? I remember tackling some related issues recently.

**Comment by jaminthorns** [comment]
I changed my `mix.exs` to use the `master` branch for both `ecto` and `ecto_sql`:

```elixir
# ...
{:ecto, git: "git@github.com:elixir-ecto/ecto.git", branch: "master", override: true},
{:ecto_sql, git: "git@github.com:elixir-ecto/ecto_sql.git", branch: "master", override: true},
# ...
```

And I confirmed that `ecto` and `ecto_sql` both resolved to the latest commit in both repos in my `mix.lock` (https://github.com/elixir-ecto/ecto/commit/5537422e567a100bb5e5dc60ff4a10865c7cfc16 and https://github.com/elixir-ecto/ecto_sql/commit/5a2d7e00dc140996b543cdc55c587f0dd93bbac4). The issue still occurs in exactly the same way.
