### ISSUE TITLE
Query generated with `Ecto.assoc/2` doesn't automatically set query prefix

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#3871]
### Current behavior

When a struct is loaded with a prefix via `Repo.get` with the prefix option, calling `Ecto.assoc(struct, :some_assoc)` tries to load the association from the default schema.

### Expected behavior

If multiple structs are provided, there is no logical way to infer a prefix for the query. But if a single struct is provided and has a prefix set, it would be more ergonomic to automatically add the prefix to the query, similar to `Repo.update`.

I may be missing something obvious here, but this has bitten me a couple of times because it seems intuitive that since the provided struct was already leaded with a prefix via `Repo.get`, I shouldn't need to provide that same prefix again when I call `Repo.all` on the assoc query.

**Comment by josevalim** [comment]
What happens with preload? Does it respect the prefix? We should mirror whatever preload does. :)

**Comment by josevalim** [comment]
From the docs, it looks like preload respects the prefix. If so, a pull request is welcome!
