### ISSUE TITLE
put_assoc/3 with many to many assoc does not respect prefix on parent or association structs

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#3876]
### Environment

* Ecto version (mix deps): 3.7.2
* Database adapter and version (mix deps): postgrex 0.15.10

### Current behavior

```
ParentSchema
|> Repo.get!(1, prefix: "tenant")
|> Repo.preload(:teams) |> Ecto.Changeset.change()
|> Ecto.Changeset.put_assoc(:assoc, [Repo.get!(ChildSchema, 1, prefix: "tenant")]) 
|> Repo.update()
```

`INSERT INTO "join_table" ("parent_schema_id","child_schema_id") VALUES ($1,$2) [1, 1]`

### Expected behavior

`INSERT INTO "tenant.join_table" ("parent_schema_id","child_schema_id") VALUES ($1,$2) [1, 1]`

Note: `Repo.update(prefix: prefix)` produces the desired query, but is inconsistent with how prefixes are handled in other places.

**Comment by josevalim** [comment]
Is this only for many to many?

**Comment by tfwright** [comment]
Sorry yes I've only observed this on many to many associations
