### ISSUE TITLE
`update_all` not working when query contains join in 3.8

### ISSUE THREAD

**Issue by pierot** [elixir-ecto/ecto#3881]
### Environment

* Elixir version (elixir -v): 1.13.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 8.0.23
* Ecto version (mix deps): 3.8
* Database adapter and version (mix deps): myxql 0.6.1
* Operating system: Mac OS 12.3

### Current behavior

```elixir
from(
  c in Case,
  inner_join: cl in assoc(c, :client),
  on: cl.client_group_id == ^client_group.id,
  where: c.state_name in ^[:in_progress]
)
|> Repo.update_all(set: [plan_type_id: 1])
```

Result: `{0, nil}`

### Expected behavior

Result: `{1, nil}`

### Extra

So, we use `update_all` in a lot of places. But the code that fails after updating Ecto to `3.8` is the one with the `inner_join`. We can fix it by reversing to `3.7.2`.

**Comment by josevalim** [comment]
@pierot can you please compare the SQL query being emitted?

**Comment by pierot** [comment]
@josevalim 

3.7.2

```
UPDATE `cases` AS c0, `clients` AS c1 SET c0.`plan_type_id` = 1750 WHERE ((c1.`id` = c0.`client_id`) AND (c1.`client_group_id` = 9206)) AND (c0.`state_name` IN ('in_progress','suspended','new'))
```

3.8

```
UPDATE `cases` AS c0, `clients` AS c1 SET c0.`plan_type_id` = 9215 WHERE ((c1.`id` = c0.`client_id`) AND (c1.`client_group_id` = 1752)) AND (c0.`state_name` IN ('in_progress','suspended','new'))
```

The value for `plan_type_id` (9215) is switched with the one in the condition for `client_group_id` (1752).

**Comment by josevalim** [comment]
@pierot can you please try ecto_sql master? Then if it works I will cut a new release ASAP.

**Comment by pierot** [comment]
It now returns `** (MyXQL.Error) (1054) Unknown column 'c1.id' in 'where clause'`.

**Comment by josevalim** [comment]
@pierot you are right. That was not the correct fix. Can you please try `ecto` master instead? (not `ecto_sql`).

**Comment by pierot** [comment]
@josevalim 

```elixir
{:ecto_sql, "~> 3.7"},
{:ecto, git: "https://github.com/elixir-ecto/ecto.git", branch: "master", override: true},
```

Using this fixes the issue. Thanks!

**Comment by josevalim** [comment]
v3.8.1 is out.
