### ISSUE TITLE
In a `many_to_many` relationship, updates do not consider `join_where`

### ISSUE THREAD

**Issue by thiagopromano** [elixir-ecto/ecto#3882]
### Environment

* Elixir version (elixir -v): 1.13.0
* Ecto version (mix deps): 3.8.0
* Database adapter and version (mix deps): postgrex 0.16.2

### Current behavior

Given a Many to Many table with the following association fields:

```elixir
    many_to_many :public_tags, ManyToManyTest.Core.Tag,
      join_through: ManyToManyTest.Core.ProductTag,
      join_defaults: [public: true],
      join_where: [public: true],
      on_replace: :delete

    many_to_many :private_tags, ManyToManyTest.Core.Tag,
      join_through: ManyToManyTest.Core.ProductTag,
      join_defaults: [public: false],
      join_where: [public: false],
      on_replace: :delete
```

When updating tags, the following happens:

We start with a product with no tags:

`Product: [private_tags: [], public_tags[]]`

Then we add a private tag called tag1:

`Product: [private_tags: [tag1], public_tags[]]`

Then we add the same tag as public:

`Product: [private_tags: [tag1], public_tags[tag1]]`

Everything up to here works fine.

Finally, we ask to remove the private tag:

`Product: [private_tags: [], public_tags[tag1]]`

Ecto executes this query, ignoring the `join_where`:

DELETE FROM "products_tags" AS p0 WHERE ((p0."product_id" = $1) AND (p0."tag_id" = $2))

So the resulting product is:

`Product: [private_tags: [], public_tags[]]`

### Expected behavior

The Ecto follows the `join_where` and run the following query:

`DELETE FROM "products_tags" AS p0 WHERE ((p0."product_id" = $1) AND (p0."tag_id" = $2) AND (p0."private" = false))`

## Notes

I have created a simple repo that shows this bug here: https://github.com/thiagopromano/many_to_many_test

The test that shows this happening is here: https://github.com/thiagopromano/many_to_many_test/blob/main/test/many_to_many_test/core_test.exs

Note that this bug does not depend on having two different associations using the same intermediate table. For example the `join_where` could have been `available_for_pro_users: true`.

**Comment by thiagopromano** [comment]
Ecto could also use the `primary_key` of the association table if it exists for deletions.

**Comment by josevalim** [comment]
We should use the `join_where`. We may not have the primary key and we would need to do additional queries to fetch it.
