### ISSUE TITLE
(ArgumentError) invalid option :null for `field/3`

### ISSUE THREAD

**Issue by alaadahmed** [elixir-ecto/ecto#3889]
### Environment

* Elixir version (elixir -v): `1.13.4`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `PostgreSQL 14.2`
* Ecto version (mix deps): `3.8.1`
* Database adapter and version (mix deps): `0.16.3`
* Operating system: `macOS 11.6.5`

### Current behavior
Since updating ecto from `3.7.2` to `3.8.1` and I get compilation errors, any where in my schema files I used `null: false`, or `size: {some number}` as options for `field` macro. I checked __CHANGELOG__ maybe they are not supported any more but didn't find any thing that helped.

Even the auto generated file of `phx.gen.auth` -> `user.ex` has `field :email, :string, null: false` now gives compile error: 
```
== Compilation error in file lib/ahram_school/accounts/user.ex ==
** (ArgumentError) invalid option :null for field/3
    (ecto 3.8.1) lib/ecto/schema.ex:2214: Ecto.Schema.check_options!/3
    (ecto 3.8.1) lib/ecto/schema.ex:1911: Ecto.Schema.__field__/4
    lib/ahram_school/accounts/user.ex:12: (module)
```

### Expected behavior
I expect that all these options that were supported for `field` macro still work as it used to be.

**Comment by josevalim** [comment]
Those options were never supported, they were silently infinites before. If Phoenix is generating them, it should no longer do so.

**Comment by josevalim** [comment]
I can confirm that Phoenix does not add those fields. They were probably added later. But yes, they were never supported and we started raising as devs could expect them to do something. :)
