### ISSUE TITLE
Support preloading associations in embedded schemas from the parent schema

### ISSUE THREAD

**Issue by nallwhy** [elixir-ecto/ecto#3890]
### Current behavior

```elixir
defmodule Child do
  use Ecto.Schema

  schema "children" do
  end
end

defmodule Parent do
  use Ecto.Schema

  schema "parents" do
    embeds_many(:details, Detail, primary_key: false, on_replace: :delete) do
      belongs_to(:child, Child)
    end
  end
end

Parent
|> preload(details: :child)
|> Repo.all()
```

```
** (ArgumentError) schema Parent does not have association :details
...
```

By #3368, `Ecto.Repo.c:preload/3` works from the embedded schema, but not from the parent schema yet.

**Comment by josevalim** [comment]
Good find. We should probably "allow" embeds in preload as long as they are loading an association inside.

**Comment by josevalim** [comment]
A pull request to address this is welcome!

**Comment by Sleepful** [comment]
Working on a pull request for this

**Comment by wakeless** [comment]
Thanks for doing this @Sleepful so nice.

I've been working on this as well and hadn't seen you'd been working along on it. My approach is a little more naive but thought I'd link it here in case there's something useful. https://github.com/elixir-ecto/ecto/compare/master...wakeless:ecto:allow-preloading-within-nested-schemas

**Comment by greg-rychlewski** [comment]
Closed by https://github.com/elixir-ecto/ecto/pull/3967
