### ISSUE TITLE
Ecto IN operator performance

### ISSUE THREAD

**Issue by spinettaro** [elixir-ecto/ecto#3892]
### Environment

* Elixir version (elixir -v): 1.12.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostregSQL 12
* Ecto version (mix deps): 3.6.2
* Database adapter and version (mix deps): 
* Operating system: Windows

Hi, just as a question/improvement  why Ecto transforms the `IN` operator in `ANY` ?

Basically if you write ` from( record in RecordStore, where: ( record.values in ^values)` it generates an SQL query that uses `ANY` operator

if you have a look to this thread https://dba.stackexchange.com/questions/91247/optimizing-a-postgres-query-with-a-large-in , it might be better to use the `IN` operator and use the `VALUES` or `UNNEST` in order to increase performance. 

I tried it and it actually works! performance are better of 33% in my case. 

Am I using it wrong or is there room for enhancement/optimization?

**Comment by josevalim** [comment]
IN would require us to build a different query for every different length of the interpolated list. So we wouldn’t be able to cache the query efficiently. So it is a different set of trade-offs. With ANY, it is always the same query.
