### ISSUE TITLE
Another breaking change that I've noticed is that this code now doesn't put the error "can't be blank" into changeset

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#3893]
Another breaking change that I've noticed is that this code now doesn't put the error "can't be blank" into changeset:

```elixir
{%{}, %{uris: {:array, :string}}}
|> Ecto.Changeset.cast(%{uris: []}, [:uris], empty_values: ["", []])
|> Ecto.Changeset.validate_required(:uris)
```

but it was there in Ecto. 3.7.2

_Originally posted by @fuelen in https://github.com/elixir-ecto/ecto/issues/3840#issuecomment-1117155628_

**Comment by josevalim** [comment]
@greg-rychlewski should a list of `["", ""]` also be considered empty if the empty values are `[[], ""]`?

**Comment by greg-rychlewski** [comment]
oh good catch...I would say yes. otherwise they are letting an empty value pass through without changing it to the default. I can submit a PR if you agree.

**Comment by josevalim** [comment]
PR is VERY welcome :)
