### ISSUE TITLE
Defect: Null: False used to define NOT NULL Column is throwing compilation error in 3.8 ECTO Version

### ISSUE THREAD

**Issue by vasumur** [elixir-ecto/ecto#3898]
### Precheck

Running into an issue while upgrading to Ecto 3.8 and the details below. Appreciate your help with this.

### Environment

* Elixir version (elixir -v): 1.12.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23), 64-bit
* Ecto version (mix deps): Working version 3.5, breaking in 3.8
* Database adapter and version (mix deps):
* Operating system: MacOS

### Current behavior

When using Ecto 3.5.x version if we define a Ecto Model as below.

  @primary_key {:id, :string, autogenerate: false, source: :acct_group_id}
  schema "oneoff_acct_group" do
    field(:acct_group_id, :string, primary_key: true)
    field(:acct_group_nm, :string, null: false)
    field(:entity_id, :string)
    field(:owner, :string)

    timestamps()
  end

It creates the acct_group_nm as NOT NULL field in the database. We use the "null: false" option to create this definition.

But in 3.8 version, this option itself is not valid and the code provides compilation level error.

== Compilation error in file lib/tradeserf/model/oneoff_acct_group.ex ==
** (ArgumentError) invalid option :null for field/3
    (ecto 3.8.2) lib/ecto/schema.ex:2214: Ecto.Schema.check_options!/3
    (ecto 3.8.2) lib/ecto/schema.ex:1911: Ecto.Schema.__field__/4
    lib/tradeserf/model/oneoff_acct_group.ex:9: (module)
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

### Expected behavior

Backward compatibility if possible with 3.5 version. Other acceptable work arounds are to have an option (say for e.g. required: true) something like that will help define this table as NOT NULL in database.

Please note: We do use insert_all option for performance reasons, so validating each record by validate_required may not work in our cases, unless that is enforced when we do insert_all.

**Comment by wojtekmach** [comment]
You are setting `null: false` on your Ecto schema and it doesn’t do anything, the option is silently ignored. The option is only useful in a migration.
