### ISSUE TITLE
Inspect.Ecto.Query don't allow another defimpl

### ISSUE THREAD

**Issue by LucasPaszinski** [elixir-ecto/ecto#3901]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres SQL 13.4
* Ecto version (mix deps): 3.7.1 (but still possible on current version)
* Database adapter and version (mix deps):
* Operating system: Mac OS

### Current behavior

Current implementation of  `Inspect, for: Ecto.Query` add the function `to_string/1`, which is not part of the protocol, but expected to be part of by ecto, this presents a problem when trying to redact a field

If I don't redact, my users personal info it's leaked.

```elixir
insert(:user, first_name: "Jerry", last_name: "Seinfield")
insert(:user, first_name: "Jerry", last_name: "Mouse")

query =
     User
      |> where([u], u.first_name == "Jerry")
      |> Repo.one

** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
    
     from u0 in User,
       where: u0.first_name == "Jerry"
```

if I do redact with the protocol

```elixir
redacted_fields = [:ssn, first_name, last_name]

defimpl Inspect, for: Ecto.Query do
  def inspect(data, opts) do
          data
          |> redact_fields(redacted_fields)
          |> Inspect.Any.inspect(opts)
  end
end
```

```elixir
insert(:user, first_name: "Jerry", last_name: "Seinfield")
insert(:user, first_name: "Jerry", last_name: "Mouse")

query =
     User
      |> where([u], u.first_name == "Jerry")
      |> Repo.one

** (UndefinedFunctionError) function Inspect.Ecto.Query.to_string/1 is undefined or private
```

It will break because expected function added by the protocol, that it's removed when I reimplement the protocol
https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/exceptions.ex#L36

### Expected behavior

Allow the programmer to use it's  own protocol if chooses to do so.

**Comment by LucasPaszinski** [comment]
I see some ways around this, not formatting the exception with `Inspect.Ecto.Query.to_string`, or making it two different protocols so the function don't get overwritten and this can be expanded and changed by the programer

**Comment by josevalim** [comment]
@LucasPaszinski overwriting protocol definitions is not really an Elixir feature though and, if you try to do it, you will get conflicts.

In this particular case though, we support `field :password, redact: true`. Maybe we should try redacting it when building the inspect? Maybe there is enough metadata on the query, such as the field type, or even looking in the AST, to tell you the field and then you can check if the field is redacted or not.

**Comment by LucasPaszinski** [comment]
Yeah apparently the query does not have the required information for this.

I end-up using  this, I don't think it's ideal but other alternatives would require a lot more work.

```elixir
use Ecto.Repo

def one(query) do
  super(query)
rescue 
  Ecto.MultipleResultsError -> reraise My.MultipleResultsError, "my message", __STACKTRACE__
end
```

**Comment by LucasPaszinski** [comment]
Thanks for the help!
