### ISSUE TITLE
Upgrade 3.7.2 → 3.8.2 causes "@behaviour ... does not exist" compilation warning

### ISSUE THREAD

**Issue by angelikatyborska** [elixir-ecto/ecto#3902]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Not relevant (bug can be reproduced without starting a database server)
* Ecto version (mix deps): 3.8.2 (and also [current state of master at the time of opening the issue](https://github.com/elixir-ecto/ecto/commit/26a1e8e2d0c4c8dbb6d15a60ad5e4360a04ca2fd))
* Database adapter and version (mix deps): Not relevant
* Operating system: Reproduced on my computer (macOS 12.3.1) as well as in a Docker container on CI (Ubuntu 18.04)

### Current behavior

In our project, we use `mix compile --warnings-as-errors --force` on CI to ensure no compilation warnings in production code. An upgrade of Ecto from 3.7.2 to 3.8.2 fails that check and we don't really understand why.

I created a repository that reproduces the bug: https://github.com/angelikatyborska/ecto_bug

I also created a branch with the older Ecto 3.7.2 ([compare view](https://github.com/angelikatyborska/ecto_bug/compare/before-upgrade), [tree view](https://github.com/angelikatyborska/ecto_bug/tree/before-upgrade)) where this problem does not appear.

I figured out after a while that the cause of the problem is the behaviour's callback using one of the Ecto schemas as a type as a struct (`%EctoBug.SomeSchema{}`). Changing it to use a custom type defined in the schema module instead (`EctoBug.SomeSchema.t()`) fixes the problem. I also created a branch with the fix ([compare view](https://github.com/angelikatyborska/ecto_bug/compare/fix), [tree view](https://github.com/angelikatyborska/ecto_bug/tree/fix)).

### Expected behavior

I expect it to be possible to use Ecto schemas as a type as a struct without causing any compilation warnings.

**Comment by wojtekmach** [comment]
Thank you for the report and a sample project, really appreciated!

FWIW, I was able to strip it down even further:

```elixir
# lib/ecto_bug/behaviour_usage.ex
defmodule EctoBug.BehaviourUsage do
  @behaviour EctoBug.SomeBehaviour

  @impl true
  def foo(_), do: :ok
end
```

```elixir
# lib/ecto_bug/some_behaviour.ex
defmodule EctoBug.SomeBehaviour do
  @callback foo(%EctoBug.SomeSchema{}) :: :ok
end
```

```elixir
# lib/ecto_bug/some_schema.ex
defmodule EctoBug.SomeSchema do
  use Ecto.Schema

  schema "things" do
  end
end
```

**Comment by wojtekmach** [comment]
could be! fwiw commit 99b8a69e is the culprit.

**Comment by josevalim** [comment]
Ah, perfect. I know how to fix it.

**Comment by josevalim** [comment]
v3.8.3 is out!

**Comment by angelikatyborska** [comment]
That was amazingly fast, thank you 💜
