### ISSUE TITLE
`Repo.insert` with `on_conflict: :nothing` option returns non-null `id` on conflict (postgres)

### ISSUE THREAD

**Issue by chakeresa** [elixir-ecto/ecto#3910]
### Environment

* Elixir version (elixir -v): Elixir 1.13.3 (compiled with Erlang/OTP 24)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 14.2
* Ecto version (mix deps): ecto 3.8.3
* Database adapter and version (mix deps): ecto_sql 3.8.1
* Operating system: macOS Monterey version 12.2.1

### Expected behavior

Based on Ecto's [upsert docs](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts), we expected `Repo.insert` with the `on_conflict: :nothing` option to return a schema struct with an `id` of `nil` when a unique constraint is violated. 

> Because we used `on_conflict: :nothing`, instead of getting an error, we got `{:ok, struct}`. However the returned struct does not reflect the data in the database. One possible mechanism to detect if an insert or nothing happened in case of `on_conflict: :nothing` is by checking the `id` field. `id` will be nil if the field is autogenerated by the database and no insert happened.

### Current behavior

When the unique constraint was violated, a non-null `id` (**not** matching the database value for the record with the conflicting parameter) was returned.

The first time a user with this combination of partner & partner_identifier was find-or-created:

```elixir
iex(2)> Persistence.find_or_create_user(%FindOrCreateUser.Input{partner_identifier: "42", partner: "company"})
[debug] QUERY OK db=0.3ms idle=134.2ms
begin []
[debug] QUERY OK source="users" db=2.4ms
SELECT u0."id", u0."partner", u0."partner_identifier", u0."phone", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE ((u0."partner" = $1) AND (u0."partner_identifier" = $2)) ["company", "42"]
[debug] QUERY OK db=3.8ms
INSERT INTO "users" ("partner","partner_identifier","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5) ["company", "42", ~N[2022-05-24 22:09:30], ~N[2022-05-24 22:09:30], <<75, 249, 66, 162, 178, 110, 70, 6, 157, 123, 32, 178, 84, 207, 237, 61>>]
[debug] QUERY OK db=0.6ms
commit []
%Entities.User{
  id: "4bf942a2-b26e-4606-9d7b-20b254cfed3d",
  inserted_at: ~N[2022-05-24 22:09:30],
  partner: "company",
  partner_identifier: "42",
  updated_at: ~N[2022-05-24 22:09:30]
}
```

FYI, this was the result when the changeset's uniqueness check was removed (to simulate the race condition for find-or-create), while we were still using `Repo.insert` *without* any options.

```elixir
iex(5)> Persistence.find_or_create_user(%FindOrCreateUser.Input{partner_identifier: "42", partner: "company"})
[debug] QUERY OK db=0.3ms idle=1748.8ms
begin []
[debug] QUERY ERROR db=11.8ms
INSERT INTO "users" ("partner","partner_identifier","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5) ["company", "42", ~N[2022-05-24 22:11:00], ~N[2022-05-24 22:11:00], <<19, 43, 164, 163, 127, 15, 77, 62, 139, 99, 250, 253, 189, 102, 89, 126>>]
[debug] QUERY OK db=0.2ms
rollback []
** (Ecto.ConstraintError) constraint error when attempting to insert struct:

    * users_partner_partner_identifier_index (unique_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `unique_constraint/3` on your changeset with the constraint
`:name` as an option.

The changeset has not defined any constraint.
```

On subsequent find-or-create attempts with the same combination of partner/partner_identifier, this time using the `on_conflict: :nothing` option for `Repo.insert`. Notice that the `id` is *not* null (and not equal to the value in the database). Similarly, the `inserted_at` and `updated_at` values are not equal to the database values.

```elixir
iex(6)> Persistence.find_or_create_user(%FindOrCreateUser.Input{partner_identifier: "42", partner: "company"})
[debug] QUERY OK db=0.4ms idle=413.4ms
begin []
[debug] QUERY OK db=0.8ms
INSERT INTO "users" ("partner","partner_identifier","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING ["company", "42", ~N[2022-05-24 22:11:36], ~N[2022-05-24 22:11:36], <<202, 2, 222, 243, 152, 238, 78, 112, 180, 92, 151, 35, 231, 87, 94, 53>>]
[debug] QUERY OK db=0.3ms
commit []
%Entities.User{
  id: "ca02def3-98ee-4e70-b45c-9723e7575e35",
  inserted_at: ~N[2022-05-24 22:11:36],
  partner: "company",
  partner_identifier: "42",
  updated_at: ~N[2022-05-24 22:11:36]
}
iex(7)> Persistence.Repo.get_by(Persistence.Schemas.User, partner_identifier: "42")
[debug] QUERY OK source="users" db=1.1ms queue=1.6ms idle=1812.2ms
SELECT u0."id", u0."partner", u0."partner_identifier", u0."phone", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."partner_identifier" = $1) ["42"]
%Persistence.Schemas.User{
  __meta__: #Ecto.Schema.Metadata<:loaded, "users">,
  id: "4bf942a2-b26e-4606-9d7b-20b254cfed3d",
  inserted_at: ~N[2022-05-24 22:09:30],
  partner: "company",
  partner_identifier: "42",
  updated_at: ~N[2022-05-24 22:09:30]
}
```

So when we tried following the docs' advice to match on an `id` of `nil`, we failed to detect the conflict / data that didn't match the actual database values.

**Conclusion: I'm not sure if this is a postgres-specific failure, something that can be fixed, or if the docs just need to be updated so they don't mislead people into thinking that a non-null `id` indicates a successful insert + params matching the database values.**

FYI: to do our find-or-create operation, we ended up using the following options. Without `returning: true`, we had a similar issue (id/inserted_at/updated_at not matching the database values).
```elixir
%{partner: partner, partner_identifier: partner_identifier}
|> User.changeset()
|> repo.insert(
  returning: true,
  on_conflict: {:replace, [:partner, :partner_identifier]},
  conflict_target: [:partner, :partner_identifier]
)
```

cc @mackshkatz who was troubleshooting this race condition with me

**Comment by josevalim** [comment]
Thanks for the detailed write up! I see that you are using UUID. Are they generated by Ecto or on the database? In any case, I think that the root cause for the difference in behaviour, so a PR to amend the docs will be very welcome!

**Comment by chakeresa** [comment]
We do have this in the module defining our schema `@primary_key {:id, :binary_id, autogenerate: true}`.

**Comment by josevalim** [comment]
That's the reason then! Would you like to send a PR to amend the docs to say that the paragraph only applies to "auto-incrementing primary keys"? If you have other types of primary keys, such as UUID, then you have to use other approaches listed in the document, such as explicitly generating a UUID before insertion and then use returning: true to compare the UUIDs before and after writing. :)

**Comment by v0idpwn** [comment]
>Would you like to send a PR to amend the docs to say that the paragraph only applies to "auto-incrementing primary keys"? 
It probably would be more precise to point that it applies only to primary keys generated in the database. For example, it is (somewhat) common to use a postgres extension to generate uuids on postgres side, and for this case it would return the PK as `nil`.
