### ISSUE TITLE
Validation on schema fields option is too strict

### ISSUE THREAD

**Issue by h-yon** [elixir-ecto/ecto#3913]
### Environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MariaDB 10.5.1
* Ecto version (mix deps): 3.8.3
* Database adapter and version (mix deps): ecto_sql 3.8.2
* Operating system: Debian 11 (on Docker on Windows 10)

### Current behavior

I have Enum type fields in schemas like `field(:action, Ecto.Enum, values: [:get, :post])`.
I get the following error on the schema file.
```
** (ArgumentError) invalid option :values for field/3
    (ecto 3.8.3) lib/ecto/schema.ex:2201: Ecto.Schema.check_options!/3
    (ecto 3.8.3) lib/ecto/schema.ex:1908: Ecto.Schema.__field__/4
```

### Expected behavior

Accepts `:values` option.

**Comment by josevalim** [comment]
I can't reproduce this error. Here is what I tried:

```
Mix.install [:ecto]

defmodule Example do
  use Ecto.Schema

  schema "hello" do
    field :example, Ecto.Enum, values: [:foo, :bar, :baz]
  end
end
```

And it executes correctly.

**Comment by josevalim** [comment]
Please let me know if you have a way to reproduce it and I will gladly take a look!
