### ISSUE TITLE
View Table and not work @primary_key false in version 3.8.4

### ISSUE THREAD

**Issue by DarkCobalt** [elixir-ecto/ecto#3924]
### Elixir version

Erlang/OTP 24 Elixir 1.13.2

### Database and Version

PostgreSQL 14.3-1

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.3

### Current behavior

Hello

When I updated the package version from 3.7.2 to 3.8.4, I have a error `(Ecto.NoPrimaryKeyFieldError) schema App.Stat has no primary key`

I have schema 
```
defmodule App.Stat do

  use Ecto.Schema

  @primary_key false
  schema "stat" do
    field :xxx_uuid, :binary_id
    field :zzz_uuid, :binary_id
    field :count, :integer
    field :sum, :decimal
  end
end
```

And I have created a **View** in a Postgre that does not have primary_key. 

On version 3.7.2 works fine but on the latest version has error.

Can you check whats happend? :)

### Expected behavior

It will start working as in the previous version

**Comment by greg-rychlewski** [comment]
Hi @DarkCobalt,

Could you please give a bit more detail: what operation are you performing when the error occurs and what is the stacktrace?

Or even better if you can provide a small reproducible example like this: https://github.com/wojtekmach/mix_install_examples/blob/main/ecto_sql.exs

**Comment by josevalim** [comment]
Closing this for now, please let us know if there is something we can act on, thank you!
