### ISSUE TITLE
Repo.insert return value not always correct when using replace_all_except

### ISSUE THREAD

**Issue by spctrlth** [elixir-ecto/ecto#3949]
### Elixir version

1.13.0

### Database and Version

PostgreSQL 12.11

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.3

### Current behavior

I have the following piece of code

```elixir
  def create(relationship_type, %User{} = source, %User{} = target) do
    %UserRelationship{}
    |> changeset(%{
      relationship_type: relationship_type,
      source_id: source.id,
      target_id: target.id
    })
    |> Repo.insert(
      on_conflict: {:replace_all_except, [:id, :inserted_at]},
      conflict_target: [:source_id, :relationship_type, :target_id]
    )
  end
```

I run the following test

```elixir
    test "if record already exists, returns it", %{users: [user1, user2]} do
      {:ok, user_block} =
        UserRelationship.create_block(user1, user2) |> IO.inspect(label: "user_block")

      :timer.sleep(1000)

      {:ok, new_block} =
        UserRelationship.create_block(user1, user2) |> IO.inspect(label: "new_block")

      :timer.sleep(1000)

      assert user_block.id == new_block.id
      :timer.sleep(1000)

      [^user_block] =
        UserRelationship
        |> where(relationship_type: :block)
        |> where(source_id: ^user1.id)
        |> where(target_id: ^user2.id)
        |> Repo.all()
        |> IO.inspect(label: "Repo")
    end
  end
```

Which gives me the following output

```
user_block: {:ok,
 %Pleroma.UserRelationship{
   __meta__: #Ecto.Schema.Metadata<:loaded, "user_relationships">,
   id: 32594,
   inserted_at: ~N[2022-07-17 13:01:54],
   relationship_type: :block,
   source: #Ecto.Association.NotLoaded<association :source is not loaded>,
   source_id: "ALaDrpdX2N4HYpbAmm",
   target: #Ecto.Association.NotLoaded<association :target is not loaded>,
   target_id: "ALaDrphmmYTFm1aZPs"
 }}
new_block: {:ok,
 %Pleroma.UserRelationship{
   __meta__: #Ecto.Schema.Metadata<:loaded, "user_relationships">,
   id: 32594,
   inserted_at: ~N[2022-07-17 13:01:55],
   relationship_type: :block,
   source: #Ecto.Association.NotLoaded<association :source is not loaded>,
   source_id: "ALaDrpdX2N4HYpbAmm",
   target: #Ecto.Association.NotLoaded<association :target is not loaded>,
   target_id: "ALaDrphmmYTFm1aZPs"
 }}
Repo: [
  %Pleroma.UserRelationship{
    __meta__: #Ecto.Schema.Metadata<:loaded, "user_relationships">,
    id: 32594,
    inserted_at: ~N[2022-07-17 13:01:54],
    relationship_type: :block,
    source: #Ecto.Association.NotLoaded<association :source is not loaded>,
    source_id: "ALaDrpdX2N4HYpbAmm",
    target: #Ecto.Association.NotLoaded<association :target is not loaded>,
    target_id: "ALaDrphmmYTFm1aZPs"
  }
]
```

See also <https://git.pleroma.social/pleroma/pleroma/-/merge_requests/3697#note_92387>

### Expected behavior

I expect Repo.insert to return the value I'll find in the database. The second time I insert a record, there's a conflict and it should update the existing record, while keeping the `id` and `inserted_at`.

When we check the `id`, we see that it's the same id in all three cases. This is as I expect.

However, when we check the `inserted_at` after the second insert, it looks from the return value that it was updated. This is not what I expect. I expect the value to not have been updated.

When we then check the database, we see that the `inserted_at` wasn't updated after all. That's good and what I expect from the code, but it shows that the return value after conflict isn't what we find in the database.

**Comment by spctrlth** [comment]
Come to think of it :thinking: I wonder if the inserted_at should even update. I'm unsure if I should consider this an actual insert (in which case it makes sense to update the inserted_at), or rather an update of an existing record (in which case it doesn't make sense to change the inserted_at).

I guess I'm expecting the second case here, that it's actually an update.

**Comment by josevalim** [comment]
You need to explicitly say which values you want back, by passing the `:returning` key or setting `:read_after_writes` in your field definition of your schema.

**Comment by josevalim** [comment]
More info the docs: https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts

**Comment by spctrlth** [comment]
Yes, this works. It was a bit unexpected, but I think I understand why it is now. Thk you! :heart:
