### ISSUE TITLE
Test fails: test fully_expand/2 with subquery and dynamic interpolation

### ISSUE THREAD

**Issue by Sleepful** [elixir-ecto/ecto#3957]
### Elixir version

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Database and Version

none

### Ecto Versions

master branch

### Database Adapter and Versions (postgrex, myxql, etc)

none

### Current behavior

`mix test` fails on 5 test cases, submitting this issue only for 1 test case first in case I am doing something wrong. 
This is the first case it fails on:
```
1) test fully_expand/2 with subquery and dynamic interpolation (Ecto.Query.Builder.DynamicTest)
     test/ecto/query/builder/dynamic_test.exs:51
     Assertion with == failed
     code:  assert Macro.to_string(expr) ==
              "&0.foo() == ^0 and (&0.bar1() == ^1 or &0.sq() in {:subquery, 0} or &0.bar3() == ^3) and &0.baz() == ^4"
     left:  "&0.foo() == ^0 and (&0.bar1() == ^1 or &0.sq() in {:subquery, 0} or &0.bar3() == ^3) and\n  &0.baz() == ^4"
     right: "&0.foo() == ^0 and (&0.bar1() == ^1 or &0.sq() in {:subquery, 0} or &0.bar3() == ^3) and &0.baz() == ^4"
     stacktrace:
       test/ecto/query/builder/dynamic_test.exs:57: (test)
```

### Expected behavior

Does not fail

**Comment by josevalim** [comment]
Yes! That's because `Macro.to_string/2` is adding newlines on Elixir v1.13. We should add a if/else branch to those particular tests, similar to other places in the codebase (search for `if Version.match?(System.version(), ">= 1.13.0-dev") do`).

**Comment by josevalim** [comment]
PRs welcome!
