### ISSUE TITLE
Improve documenation about using custom functions (fragments)

### ISSUE THREAD

**Issue by andrhua** [elixir-ecto/ecto#3961]
### Elixir version

-

### Database and Version

-

### Ecto Versions

-

### Database Adapter and Versions (postgrex, myxql, etc)

-

### Current behavior

From my (perhaps deceptive) perspective, these are interchageable ways to call a macro defined in another module:
```elixir
require Foo
Foo.my_macro(...)
```
```elixir
import Foo
my_macro(...)
```

However docs for defining [custom fragments](https://hexdocs.pm/ecto/Ecto.Query.API.html#fragment/1-defining-custom-functions-using-macros-and-fragment) doesn't caution user that such custom functions should be `import`ed, not `require`d. I've been burnt by this couple of times, but I don't really get why you can't have `require`. I was once told this is due to remote calls to `require`d module vs (I guess) direct call to `import`ed function, but I think it would be better to make it explicitly stated in the docs.

### Expected behavior

Docs stating `import` usage is required, not just presented as example. Explanation how are `require` and `import` different here would be also nice.

**Comment by josevalim** [comment]
Require should be fine. Can you please fill in the issues template with the code that is failing and the relevant versions? Thank you.
