### ISSUE TITLE
Documentation example on `Ecto.Multi.update_all`

### ISSUE THREAD

**Issue by rafaelbiten** [elixir-ecto/ecto#3975]
### Elixir version

1.12.2

### Database and Version

psql (PostgreSQL) 14.3

### Ecto Versions

{:ecto_sql, "~> 3.6"}

### Database Adapter and Versions (postgrex, myxql, etc)

{:postgrex, ">= 0.0.0"}

### Current behavior

When trying to follow the examples we have in the **[Composing with data structures](https://hexdocs.pm/ecto/composable-transactions-with-multi.html#composing-with-data-structures)** section of the Ecto docs, we have the following example:

```elixir
mary_update =
  from Account,
    where: [id: ^mary.id],
    update: [inc: [balance: +10]]

john_update =
  from Account,
    where: [id: ^john.id],
    update: [inc: [balance: -10]]

Ecto.Multi.new()
|> Ecto.Multi.update_all(:mary, mary_update)
|> Ecto.Multi.update_all(:john, john_update)
```

But that gives us an arity error, related to both calls to `Ecto.Multi.update_all`.

### Expected behavior

Checking the definition of `Ecto.Multi.update_all` we have:

```
def update_all(multi, name, queryable_or_fun, updates, opts \\ [])       
```

So we're indeed missing an argument in the examples.

I believe the docs should instead have something like:

```elixir
mary_account = from Account, where: [id: ^mary.id]
john_account = from Account, where: [id: ^john.id]

Ecto.Multi.new()
    |> Ecto.Multi.update_all(:mary, mary_account, inc: [balance: -10])
    |> Ecto.Multi.update_all(:john, john_account, inc: [balance: 10])
```

I'd love to contribute to the docs, but since I'm learning this myself, I wouldn't know what to suggest in terms of documentation / best practices. The possible fix I'm suggesting above has its limitations too, ie.: if one of the accounts does not exist, the call to `Ecto.Multi` will still succeed, but that would be an error, and I couldn't figure out yet a simple way to enforce that both accounts should exist within the calls to `Ecto.Multi`.

**Comment by rafaelbiten** [comment]
After reading more on `Ecto.Multi` and seeing more examples, I finally understood that we can `run` checks and tap into what has been done so far within `Ecto.Multi`, ie.:

```elixir
mary_account = from Account, where: [id: ^mary.id]
john_account = from Account, where: [id: ^john.id]

Ecto.Multi.new()
    |> Ecto.Multi.update_all(:mary, mary_account, inc: [balance: -10])
    |> Ecto.Multi.update_all(:john, john_account, inc: [balance: 10])
    |> Multi.run(:check_transaction, &check_transaction/2)
    |> Repo.transaction()
    |> case do
    {:ok, %{check_transaction: nil} = result} ->
      # Handle success case
      {:ok, result}

    {:error, action, _error, _changes_so_far} ->
      # Handle failure case, ie.:
      # {:error, :check_transaction, "Transfer failed", %{deposit: {0, nil}, withdraw: {1, nil}}}
      {:error, "Failed #{action}"}
  end
end

defp check_transaction(_repo, %{mary: {1, nil}, john: {1, nil}}), do: {:ok, nil}
defp check_transaction(_repo, _changes_so_far), do: {:error, "Failed transaction check"}
```

Having something like that in the docs would have been helpful to me, but I also see value in avoiding too much complexity/details in the docs, so I don't know if adding more to the examples would actually be beneficial.

**Comment by greg-rychlewski** [comment]
Normally you'd want to abort the transaction as soon as possible. For instance if Mary doesn't exist you don't want to perform the John query. I think the best you can do with `update_all` is to put `:mary` and `:john` into their own run functions and call `Repo.update_all` within them.
