### ISSUE TITLE
Ecto parsing database URL is broken

### ISSUE THREAD

**Issue by amitavaghosh1** [elixir-ecto/ecto#3977]
### Elixir version

1.13.4

### Database and Version

Mysql 8

### Ecto Versions

ecto 3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.6.2 

### Current behavior

This is how my DB_URL looks like:

```
DB_URL="mysql://user:password@dev-rds.us-west-2.rds.amazonaws.com:3306/db_name?charset=utf8&parseTime=True&loc=Local"
```

```
defmodule Nefarious.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    config = Vapor.load!(Nefarious.Config)
  
    children = [
      {Nefarious.Metadata.Repo, [url: config.db.url]} # tried, `protocol: :tcp` here as well
    ]

    opts = [strategy: :one_for_one, name: Nefarious.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

`iex -S mix`

I have tried all kinds of URL's but nothing works and there is no documentation. 

Most of the libraries in elixir are not documented given the application setup in mind. Just some random writeup to use it in isolation.

I keep getting this error:

```
** (Ecto.InvalidURLError) invalid url "mysql://user:password@dev-rds.us-west-2.rds.amazonaws.com:3306/db_name?charset=utf8&parseTime=True&loc=Local", host is not present. The parsed URL is: %URI{authority: nil, fragment: nil, host: nil, path: "\"mysql://user:password@dev-rds.us-west-2.rds.amazonaws.com:3306/db_name", port: nil, query: "charset=utf8&parseTime=True&loc=Local&pool_size=10\"", scheme: nil, userinfo: nil}
            (ecto 3.8.4) lib/ecto/repo/supervisor.ex:92: Ecto.Repo.Supervisor.parse_url/1
```

I have tried `ecto://`, `ecto:mysql://` nothing works. even I put nothing.

### Expected behavior

To connect properly

**Comment by josevalim** [comment]
I cannot reproduce it:

```
iex(1)> Ecto.Repo.Supervisor.parse_url "mysql://user:password@dev-rds.us-west-2.rds.amazonaws.com:3306/db_name?charset=utf8&parseTime=True&loc=Local"
[
  hostname: "dev-rds.us-west-2.rds.amazonaws.com",
  username: "user",
  password: "password",
  database: "db_name",
  port: 3306,
  loc: "Local",
  parseTime: "True",
  charset: "utf8"
]
```

Do you have any warnings when you start the VM?

**Comment by amitavaghosh1** [comment]
no, only the error message. right at the start.

**Comment by josevalim** [comment]
If you try the same call as above from within your project `iex -S mix`, does it raise or does it work?

**Comment by amitavaghosh1** [comment]
When I try with this: `Ecto.Repo.Supervisor.parse_url ` it works. But with this:
```
def start(_type, _args) do
    config = Vapor.load!(Nefarious.Config)
  
    children = [
      {
        Nefarious.Metadata.Repo, [url: config.db.url]
      }
    ]

    opts = [strategy: :one_for_one, name: Nefarious.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

when I do `iex -S mix` , it doesn't work. saying invalid url, host not present.

**Comment by amitavaghosh1** [comment]
Hmm, looks. like after 7 hours, From the remote config the DB URL is coming as a quoted string. Probably that's why it's not working.

**Comment by amitavaghosh1** [comment]
Yeah, stripping the quotes made it work. Thanks for the quick help.
