### ISSUE TITLE
Inconsistent behavior with Ecto.Enum and jsonb

### ISSUE THREAD

**Issue by maxsalven** [elixir-ecto/ecto#3981]
### Elixir version

1.13.4

### Database and Version

Postgres 14.4

### Ecto Versions

ecto 3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.4

### Current behavior

Migration:
```elixir
  def change do
    create table(:users) do
      add(:status, :string)
      add(:preferences, :jsonb)
    end
  end
```

Schema:
```elixir
defmodule MyApp.Users.User do
  use MyApp.ModelBase
  require Ecto.Changeset

  schema "users" do
    field :status, Ecto.Enum,
      values: [active: "ACTIVE", inactive: "INACTIVE"],
      default: :active

    embeds_one :preferences, Preferences, primary_key: false, on_replace: :update do
      field :theme, Ecto.Enum, values: [light: "LIGHT", dark: "DARK"]
    end
  end

  def changeset(user, attrs) do
    user
    |> cast(attrs, [:status])
    |> cast_embed(:preferences, with: &preferences_changeset/2)
  end

  defp preferences_changeset(schema, params) do
    schema
    |> cast(params, [:theme])
  end
end
```

`iex -S mix`
```elixir
MyApp.Repo.insert(MyApp.Users.User.changeset(%MyApp.Users.User{}, %{status: :active, preferences: %{theme: :light}}))
```

Record created in DB:
`1 | ACTIVE | {"theme": "light"}`

### Expected behavior

I expect the JSONB value to be capitalized:
`1 | ACTIVE | {"theme": "LIGHT"}`

**Comment by maxsalven** [comment]
I've also just noticed that if you use `values: [light: 1, dark: 2]`, then it still stores `"light"` in the JSONB object

**Comment by josevalim** [comment]
We have an option for custom types that controls if the type is stored as the loaded or dumped value in JSONB. We should probably make this option customizable for enum types.

**Comment by josevalim** [comment]
You would like to send a PR that makes the return of the `embed_as` function in `Ecto.Enum` customizable? I think changing that is what you need. :)
