### ISSUE TITLE
When trying to cast a list of empty values for an array field it is ignored after casting

### ISSUE THREAD

**Issue by hassanshaikley** [elixir-ecto/ecto#3983]
### Elixir version

1.12.3

### Database and Version

Postgres 14.4

### Ecto Versions

3.8.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex  0.16.4

### Current behavior

In the schema:

`field :field_of_thing, {:array, :string}, default: List.duplicate(nil, 5)`

In the migration:

`add :field_of_thing, {:array, :string}, default: List.duplicate(nil, 5)`

And in the changeset function when I want to reset the values back to nil:

`Ecto.Changeset.cast(thing, %{field_of_thing:  List.duplicate(nil, 5) }, [:field_of_thing])`

Now after I update one of the array values to something that isn't nil and then try to set it back to nil again the change is dropped. It isn't seen in `changeset.changes` so the database isn't updated.
  

### Expected behavior

I expect the field to go back to a list of nils. I do not expect the changes to be dropped.

**Comment by greg-rychlewski** [comment]
Are you able to provide a minimal reproducible example? 

Changes should be registered unless `thing` in `Ecto.Changeset.cast(thing, %{field_of_thing: List.duplicate(nil, 5) }, [:field_of_thing])` has the same value as the change you are making. It sounds like you might be using an outdated `thing` that doesn't have the `something that isn't nil` in it. But would need a reproducible example to confirm.

**Comment by hassanshaikley** [comment]
https://github.com/hassanshaikley/broken

Try running `mix test --only only `

`test/example_broken/broken_test.exs`

Is failing when I don't believe it should be.

**Comment by greg-rychlewski** [comment]
Thanks that makes it clear. Since you want to keep empty strings, you have to add `empty_values: []` to your `cast` calls. By By default `empty_values` is `[""]` and your empty strings will be filtered out. There is more background context in this PR:  https://github.com/elixir-ecto/ecto/pull/3840

**Comment by hassanshaikley** [comment]
So for whatever reason that isn't working in my repo but it does work in the reproduction repo.

🤔

**Comment by hassanshaikley** [comment]
It works when I test it but not when I actually use the app which is extremely bizzarre.

**Comment by hassanshaikley** [comment]
@greg-rychlewski ☝️

**Comment by greg-rychlewski** [comment]
There must be some difference between how the code is being called in the app and how it is being tested, but it's hard to know what's happening without being familiar with the application.

I would suggest adding logs to see how the data is being transformed and see if something unexpected is happening.

**Comment by hassanshaikley** [comment]
It's working now. I didn't change anything. I had already nuked build. So... I don't know what happened. But it appears to be happy now.

**Comment by hassanshaikley** [comment]
The bug reappeared. This is so bizarre. Sigh.
