### ISSUE TITLE
Pass error metadata to changeset validation for interpolation into custom error messages

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-ecto/ecto#3986]
### Elixir version

1.12.2

### Database and Version

Postgres 14

### Ecto Versions

3.7.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 1.2.2

### Current behavior

When using a custom validation message with interpolation on `Ecto.Changeset` validations – e.g. `"is not linked to a %{relation}"` – there's no way to pass the `relation` key to be included in the error metadata.

### Expected behavior

Allow something like:

```elixir
validate_inclusion(changeset_a, :id, meter_ids,
  message: "is not linked to a %{relation}",
  relation: "customer"
)

validate_inclusion(changeset_b, :id, customer_ids,
  message: "is not linked to a %{relation}",
  relation: "meter"
)
```

Looking at the code this seems already supported for cast errors of custom types, but not for plain old validations provided by `Ecto.Changeset`.

**Comment by josevalim** [comment]
Is there a reason why you can’t have the value directly?

**Comment by LostKobrakai** [comment]
I use it multiple times and I had gathered this to be best practice. I'm not using it in the instance, which lead to this, but generally I tend to use interpolation to allow for it to be translated easily/once.

**Comment by josevalim** [comment]
The issue with interpolation is that you can't translate the interpolated values unless you translate them before calling `add_error`, which partially defeats the point. But if you want it, we would accept a PR that adds `message_options` or something of sorts. :)

**Comment by josevalim** [comment]
Closing this. It is your call if PR or not. :)
