### ISSUE TITLE
select_merge with a list of atoms does not add those fields to the query

### ISSUE THREAD

**Issue by markquezada** [elixir-ecto/ecto#3987]
### Elixir version

Elixir 1.13.4 (compiled with Erlang/OTP 24)

### Database and Version

mssql 2008 😅

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

tds 2.3.1

### Current behavior

I am interfacing with a legacy database that has a lot of columns on a single table. Since most of them are not needed most of the time, I have `load_in_query` set to false on many of the fields, e.g.:

```elixir
schema "tblStudents" do
# snip
    field :class_standing, :integer, source: :ClassStanding, load_in_query: false
    field :class_total, :integer, source: :ClassTotal, load_in_query: false
# snip
end
```

When I need to access those fields, I'd like to do this:

```elixir
fields = ~w(class_standing class_total)a

from s in Student,
  where: s.id == ^student_id,
  select_merge: ^fields
```

This doesn't seem to work as those fields are not added to the query and no error is reported. I just get back all the fields where `load_in_query` is not `false`.

### Expected behavior

If I use a map as described in the docs, it does work:

```elixir
query = from s in Student,
  where: s.id == ^student_id,
  select_merge: %{class_standing: s.class_standing, class_total: s.class_total}
```
But this leads to a ton of duplicate code where I am mapping the key to the same binding key.

Since some of the tests in the elixir repo use the list of atoms syntax, it seemed reasonable that I could use that here but it is unclear where that works and where it doesn't.

Of note, if I add an explicit select, the fields in the `select_merge` do in fact get added to the query:

```elixir
fields = ~w(class_standing class_total)a
from s in Student,
  where: s.id == ^student_id,
   select: map(s, [:id])
   select_merge: ^fields
```

Results in:

```elixir
%{class_standing: 15, class_total: 206, id: 50371}
```

If no explicit select is added to the query, I'd expect this same behavior but with all of the default fields in the schema loaded in addition to the fields defined in `select_merge`.

I can't tell if this is a bug or expected behavior.

**Comment by josevalim** [comment]
It is a bug. Likely an optimization that avoids keeping merged fields when the whole struct is selected (which therefore breaks with load_in_query).

**Comment by markquezada** [comment]
That makes sense, thanks for the quick reply Jose! Happy to help address this any way I can. I can attempt to dig into the ecto internals a bit and/or provide a test case.

Beyond fixing the behavior as it relates to `load_in_query`, I suppose it's worth asking the question: Is this a sane approach or is there another method of dealing with rarely used/extra fields you think would make more sense?

**Comment by josevalim** [comment]
@markquezada a unit test case will be a great starting point that can reused by both you and us. :)

> Is this a sane approach or is there another method of dealing with rarely used/extra fields you think would make more sense?

I think this is a bug but... is it sane?

I am not sure. The downside of what you are doing is that now you need to be aware that sometimes this field will be set, sometimes it won't, and it will likely be hard to know when reading the code which one is which. I would most likely consider loading those fields as additional data that you pass in addition to the original struct. That adds more book keeping but also adds clarity.

**Comment by Indever2** [comment]
There are two points:
1. `select_merge` with no prior select defaults to a struct
2. `take` is ignored when binding is not a filtered source

Based on the test cases:
```elixir
  query = from p in "posts", select: p, select_merge: [:title] # A
  # is interpreted identically to the line above
  query = from p in "posts", select_merge: [:title] # B
  
  assert Macro.to_string(query.select.expr) == "&0"
  assert query.select.params == []
  # Ignore take because [p] is not a filtered source
  assert query.select.take == %{}
```

I'm not sure that in statement `A` to ignore take is the expected behavior actually. But if it is, according to point `1` (defaults to a struct), the whole struct with all the fields as a result of statement `B` is correct.
