### ISSUE TITLE
Repeating a field in `validate_required` will generate duplicate errors for the field

### ISSUE THREAD

**Issue by lkarthee** [elixir-ecto/ecto#3993]
### Elixir version

Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [hipe]  Elixir 1.13.0 (compiled with Erlang/OTP 22)

### Database and Version

Postgres 14.1

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.3

### Current behavior

Repeating a field in `validate_required` will generate duplicate errors for the same field. This is cascading to view layer like duplicate error tags being generated for the same field.
``` elixir
row
|> cast(attrs, [:id, :name])
|> validate_required([:id, :name, :name])
```

```
#Ecto.Changeset<
  action: :validate, 
  changes: %{id: 1}, 
  errors: [
    name: {"can't be blank", [validation: :required]}, 
    name: {"can't be blank", [validation: :required]}
  ], 
  data: #ExampleSchema<>, 
  valid?: false
>
```
![image](https://user-images.githubusercontent.com/2712395/187587946-1f1d9f0c-30ea-43dd-b6ae-0f44f331802d.png)

### Expected behavior

Generate one error per field for validate_required.

**Comment by greg-rychlewski** [comment]
How come you are validating `:name` twice?

**Comment by lkarthee** [comment]
I was not trying to validate the list twice. In a schema with long list of fields - i had included the same field twice and i discovered this bug.

https://github.com/elixir-ecto/ecto/blob/fa35655eb56db97698c6b7f0af4c7fad70d04811/lib/ecto/changeset.ex#L1816

should be 
``` elixir
fields = fields |> List.wrap() |> Enum.uniq()
```

If same field is validated twice, it wont generate duplicate errors.
```
row
|> cast(attrs, [:id, :name])
|> validate_required([:id, :name])
|> validate_required([:id, :name])
```

For this reason, I feel this is a bug and fix is quite simple.

**Comment by greg-rychlewski** [comment]
I'm not too sure about this but will let the others weigh in. By your own examples/explanation the problem is the user mistakenly specifying the same fields more than once when they don't want to. It seems reasonable to generate the message as many times as the user asks.

**Comment by josevalim** [comment]
Yes, for now I am more inclined to say it is a user error too. We can always change it later if it a common mistake for osme reason.

**Comment by lkarthee** [comment]
Just to be clear - i am not expecting any fix. 

Few observations:
- `changeset.required` is supposed to be a uniq list or a list? 
 - `changeset.errors` and `changeset.required` are deduped using `Enum.uniq`  in changeset `cast_merge`:
  https://github.com/elixir-ecto/ecto/blob/fa35655eb56db97698c6b7f0af4c7fad70d04811/lib/ecto/changeset.ex#L968-L972
 - in `validate_required` it is quite opposite - no such checks exists and fields are just appended.
 - when there is an error on the field - further validations for the field are not done in validate_required, except this scenario.
 https://github.com/elixir-ecto/ecto/blob/fa35655eb56db97698c6b7f0af4c7fad70d04811/lib/ecto/changeset.ex#L1818-L1824

**Comment by greg-rychlewski** [comment]
The expectations of a merge operation are quite different than handling a list of user-provided atoms. Merge means roughly "insert new information AND update existing information on conflict". So for error messages that are the same they would be ignored instead of inserting a duplicate.

**Comment by lkarthee** [comment]
any thoughts on whether changeset.required is uniq or a list?

**Comment by greg-rychlewski** [comment]
It's a list and not a set, if that's what you mean by 'uniq'.
