### ISSUE TITLE
`cast_assoc` and `on_replace: :delete` does not delete association if the data is missing in params

### ISSUE THREAD

**Issue by dsimon-dev** [elixir-ecto/ecto#3994]
### Elixir version

1.13.4

### Database and Version

PostgreSQL 14.5

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.4

### Current behavior

The documentation for `on_replace` (https://hexdocs.pm/ecto/Ecto.Changeset.html#module-the-on_replace-option) states:

> The `:delete` and `:delete_if_exists` options must be used carefully as they allow users to delete any associated data by simply not sending the associated data.

However, through my testing I have found that the associated data is only deleted when explicitly set to `[]` or `nil` in params. The association is not touched if the field does not exist in the params map.

Is this a bug or just a documentation issue?

### Expected behavior

The documentation matches the current behavior.

**Comment by josevalim** [comment]
The documentation is correct. If you allow this data to be set via `cast_assoc`, then the user themselves can set `[]`, therefore erasing data.

**Comment by dsimon-dev** [comment]
Thanks for your quick reply, but this seems to be a misunderstanding. I will try to be more clear, sorry for not including this information in the first place.

This issue is about data **not** being deleted when it actually should be, according to the documentation.

Considering the classic "post has many comments" scenario with `Post` being

```elixir
schema "posts" do
  field :body, :text
  has_many :comments, Comment, on_replace: :delete
end
```

and `Comment` being

```elixir
schema "comments" do
  field :body, :text
  belongs_to :post, Post
end
```

And the changeset functions:

```elixir
def post_changeset(post, params) do
  post
  |> cast(params, [:body])
  |> cast_assoc(:comments, with: &comment_changeset/2)
end

def comment_changeset(comment, params) do
  cast(comment, params, [:body])
end
```

Then the comments of a post will **not** be deleted on update if `"comments"` does not exist in the params, for example if they are just `%{"body" => "Test"}`, even though the documentation states that "[...] delete any associated data by simply not sending the associated data". The comments are only deleted when the params include `%{"comments" => []}` or `%{"comments" => nil}`.

I personally prefer the current behavior of not implicitly deleting data, and changing it would be very dangerous, but the docs should be updated, unless I am missing something.

**Comment by josevalim** [comment]
Yes, you are 100% correct. A PR to update the docs is very welcome :)
