### ISSUE TITLE
validate_length with default value does not work

### ISSUE THREAD

**Issue by dvic** [elixir-ecto/ecto#4005]
### Elixir version

1.14

### Database and Version

not applicable

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

not applicable

### Current behavior

```elixir
defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field(:user_ids0, {:array, :string}, default: [])
    field(:user_ids1, {:array, :string})
  end
end

%Post{}
|> Ecto.Changeset.cast(%{user_ids0: [], user_ids1: []}, [:user_ids0, :user_ids1])
|> Ecto.Changeset.validate_length(:user_ids0, min: 1)
|> Ecto.Changeset.validate_length(:user_ids1, min: 1)
```

```
#Ecto.Changeset<
  action: nil,
  changes: %{user_ids1: []},
  errors: [
    user_ids1: {"should have at least %{count} item(s)",
     [count: 1, validation: :length, kind: :min, type: :list]}
  ],
  data: #Post<>,
  valid?: false
>
```

### Expected behavior

`user_ids0` should also not be valid. This is a bug right?

**Comment by josevalim** [comment]
Changeset only validates changes. If the value is the same as default, it won't change, hence no validation.

**Comment by josevalim** [comment]
`validate_required` is exceptional in this regards and documented as such:

> If a field is given to [validate_required/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_required/3) but it has not been passed as parameter during [cast/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/3) (i.e. it has not been changed), then [validate_required/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_required/3) will check for its current value in the data.

If your default is invalid, then it is most likely not a good default. :)

**Comment by dvic** [comment]
> `validate_required` is exceptional in this regards and documented as such:
> 
> > If a field is given to [validate_required/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_required/3) but it has not been passed as parameter during [cast/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast/3) (i.e. it has not been changed), then [validate_required/3](https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_required/3) will check for its current value in the data.

Ahh clear.

> If your default is invalid, then it is most likely not a good default. :)

I agree :) I encountered this example (`default: []`) on the slack channel, someone asked about it and I couldn't explain why it wasn't working :)

**Comment by josevalim** [comment]
In that case, thank you very much for helping and proxying the concern here! :)
