### ISSUE TITLE
allow to use unsafe_validate_unique with schemaless changeset if query option is provided

### ISSUE THREAD

**Issue by revati** [elixir-ecto/ecto#4012]
### Elixir version

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]  Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Database and Version

N/A

### Ecto Versions

3.9.0

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

```elixir
defmodule Name do
  ...
  embedded_schema do
    field :some_field, :text
  end

  def base_query(params) do
    # build_query here
  end
end

%Name{}
|> cast(params, [:some_field])
|> unsafe_validate_unique(:some_field, Repo, query: Name.base_query(), message: "duplicate some field")
```
raises error: `unsafe_validate_unique/4 does not work with schemaless changesets or embedded schemas, data received: #{inspect(data)}`

### Expected behavior

Allow to use `unsafe_validate_unique/4` with schemaless/embedded changesets if query option is provided

**Comment by greg-rychlewski** [comment]
@revati Thanks for the report. It's a bug :). I see what's wrong and will push a fix soon.

**Comment by josevalim** [comment]
Reverted in master. Thank you!

**Comment by revati** [comment]
It works 👍🏼
