### ISSUE TITLE
Please release 3.9.1 version with recent bug fixes for unsafe_validation_unique and selected_as

### ISSUE THREAD

**Issue by revati** [elixir-ecto/ecto#4016]
### Elixir version

N/A

### Database and Version

N/A

### Ecto Versions

3.9.0

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

Have to use defined dep as:
`{:ecto, github: "elixir-ecto/ecto", branch: "master", override: true}`

### Expected behavior

Define dep as: 
`{:ecto, "~> 3.9", override: true}`

P.S. I don't know where one should communicate such things. I hope this is ok. Im greatly grateful for work you all have done. Its great library and i don't want to sound arrogant. Maybe i'm missing some protocols how/when such releases are made. If so i'm sorry.

**Comment by josevalim** [comment]
Please ping me in a week. I am waiting a bit to see if we get new reports and then we will ship. :)

**Comment by joerichsen** [comment]
Just another data point. We got bit by this bug too and using the same workaround as described in this issue (I found this issue when looking for a 3.9.1 release :-)

**Comment by revati** [comment]
@josevalim ping. It has been 6 days.

**Comment by josevalim** [comment]
Done!
