### ISSUE TITLE
A query with `timeout` still returns valid list after timeout

### ISSUE THREAD

**Issue by nichita-pasecinic** [elixir-ecto/ecto#4017]
### Elixir version

1.14.0 

### Database and Version

PostreSQL 9.4

### Ecto Versions

{:ecto_sql, "~> 3.6"} {:phoenix_ecto, "~> 4.4"}

### Database Adapter and Versions (postgrex, myxql, etc)

{:postgrex, ">= 0.0.0"}

### Current behavior

I used suggested and documented [Shared Options](https://hexdocs.pm/ecto/Ecto.Repo.html#module-shared-options) timeout property on a `Repo.all(query, timeout: 1)` and still got the query response, a valid list of records, even though in console I have a postgrex timeout error:
```
[error] Postgrex.Protocol (#PID<0.435.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3518.0> timed out because it queued and checked out the connection for longer than 0ms

#PID<0.3518.0> was at location:
```

The query obviously timeouted, but I've still got the query response, shouldn't I receive a timeout response or something, or how otherwise I would understand that the query just timeout. 

### Expected behavior

To receive an error response, something like 

```elixir
{:error, :timeout} = Repo.all(query, [timeout: 1])
```

**Comment by greg-rychlewski** [comment]
Your timeout is really small so you are running into a race condition. 

The process that calls `query` is not the same process that manages the connection pool. So what's happening is you can't check the connection back into the pool before the pool gets the timeout message.

Probably you don't want `{:error, :timeout}` instead of the actual query results if they are given to you.

**Comment by josevalim** [comment]
Yes, exactly. The connection pool is saying "oops, you timed out, time to kill the connection" but between timing out and killing it, it gave you the results in time. So you lost the connection, the log is correct, but you were lucky to get the results _just_ before.

**Comment by nichita-pasecinic** [comment]
Thanks, hopefully I understand it right, will try to have a more time intensive query with a small but reasonable timeout 😄
