### ISSUE TITLE
selected_as with type/2

### ISSUE THREAD

**Issue by ak-14** [elixir-ecto/ecto#4018]
### Elixir version

1.14.0

### Database and Version

PostgreSQL 14

### Ecto Versions

3.9

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5 

### Current behavior

Calling selected_as after type/2 with custom types does not enforce the type throughout.
```
from(p in Post, 
  select: %{
    title: p.title |> type(CustomType) |> selected_as(:title)
  },
  order_by: selected_as(:title)
)

iex()> %{title: "title"}
```

### Expected behavior

```
iex()> %{title: %CustomType{}}
```

**Comment by greg-rychlewski** [comment]
Thanks for the report @ak-14. It should be fixed now in master. Please let us know if the issue persists.

**Comment by ak-14** [comment]
Thank you @greg-rychlewski for fixing this issue. I can confirm that it's working as expected now.
