### ISSUE TITLE
Fragments Not Supported in From Macro

### ISSUE THREAD

**Issue by allenwyma** [elixir-ecto/ecto#4024]
### Elixir version

1.14.0

### Database and Version

Postgres 14.2

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.4

### Current behavior

According to my understanding of the documentation on Ecto.Query.from/2, I should be able to use Postgres's generate series using the following:

`from(f in fragment("generate_series(?, ?) as x", ^0, ^100000), select f.x)`

But I haven't been able to make this work:

```
from(f in "generate_series(0, 100)", select: f)
|> Repo.all()
```

```
** (Ecto.QueryError) PostgreSQL does not support selecting all fields from "generate_series(0, 100)" without a schema. Please specify a schema or specify exactly which fields you want to select in query:
```

Using this:
```
from(f in fragment("generate_series(?, ?) as x", ^0, ^100000), select: f.x)
|> Repo.all()
```

Gives me:
```
** (CompileError) lib/sericin/inventory.ex:1671: cannot use ^0 outside of match clauses
    (ecto 3.8.4) expanding macro: Ecto.Query.select/3
```

### Expected behavior

I'm expecting there to be a list of integers generated from Postgresql's generate_series:
`[1,2,3,....]`

**Comment by greg-rychlewski** [comment]
Hi @allenwyma, thanks for the report. Fragment sources only work for Ecto 3.9+. But also there is a mistake in the docs. Fragment sources need a select statement. Please see here for the correct way to write the query: https://github.com/elixir-ecto/ecto/pull/4025/files.

**Comment by allenwyma** [comment]
confirmed works great in 3.9.1 👍
