### ISSUE TITLE
BadMapError when preloading nested associations more than once

### ISSUE THREAD

**Issue by briefjudofox** [elixir-ecto/ecto#4029]
### Elixir version

1.13.1

### Database and Version

PostgreSQL 10 & 13.1

### Ecto Versions

3.7.2 & latest

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.2 & 0.16.5

### Current behavior

Preloading nested associations on a list of items more than once when one of the items has a nil top-level association results in a `BadMapError`.

Here's a test that can reproduce:
```
  test "preload nested multiple times" do
    user = TestRepo.insert!(%User{name: "Gabriel"})

    pl1 = TestRepo.insert!(%Permalink{user_id: user.id, url: "zzz"})
    pl2 = TestRepo.insert!(%Permalink{url: "aaa"})

    post1 = TestRepo.insert!(%Post{title: "p1"})

    TestRepo.insert!(%Comment{author_id: user.id, text: "c1", post_id: post1.id})

    permalinks = TestRepo.preload([pl1, pl2], user: [:co_commenters])
    assert [%Permalink{}, %Permalink{}] = permalinks
    assert [%Permalink{}, %Permalink{}] = TestRepo.preload(permalinks, user: [:co_commenters])
  end
```

Fails on the second preload with:
```
  2) test preload nested multiple times (Ecto.Integration.PreloadTest)
     deps/ecto/integration_test/cases/preload.exs:538
     ** (BadMapError) expected a map, got: nil
     code: assert [%Permalink{}, %Permalink{}] = TestRepo.preload(permalinks, user: [:co_commenters])
     stacktrace:
       :erlang.map_get(:comments, nil)
       (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       deps/ecto/integration_test/cases/preload.exs:550: (test)
```

### Expected behavior

This is kind of a contrived example, but it's modeled after something we encountered.  I _think_ the expectation would be that the second preload would just return the same 2 Permalink structs.  Please let me know if I can help provide any additional info.  Thanks!

**Comment by greg-rychlewski** [comment]
Thanks for the report @briefjudofox. It should be fixed on master now. If the issue persists please let us know.

**Comment by briefjudofox** [comment]
Thanks for the super quick turn-around @greg-rychlewski!  I really appreciate it.
