### ISSUE TITLE
Error in documenation `from` clause.

### ISSUE THREAD

**Issue by franckstifler** [elixir-ecto/ecto#4032]
### Elixir version

1.13.4

### Database and Version

PostgreSQL 13.5

### Ecto Versions

3.9

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

`query = from f in fragment("generate_series(?, ?) as x", ^0, ^100_000), select: f.x`

 `Repo.all(query)`

### Expected behavior

This is found in documentation of Ecto 3.9.
The first issue is a typo, a missing `:` after the select keyword.
Secondly we have an error:
`** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "AS"

    query: SELECT f0."x" FROM generate_series($1, $2) as x AS f0
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:905: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.0) lib/ecto/adapters/sql.ex:820: Ecto.Adapters.SQL.execute/6
    (ecto 3.9.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3`

**Comment by franckstifler** [comment]
The `as` alias in fragment seems not to work

**Comment by greg-rychlewski** [comment]
Thanks for the report. This mistake in the docs was noticed a few days ago and fixed here: https://github.com/elixir-ecto/ecto/pull/4025

The docs were also improved one more time here: https://github.com/elixir-ecto/ecto/pull/4027.
