### ISSUE TITLE
Using `selected_as` in a scope of subquery fails

### ISSUE THREAD

**Issue by andrhua** [elixir-ecto/ecto#4033]
### Elixir version

Elixir 1.13.4 (compiled with Erlang/OTP 24)

### Database and Version

Postgres 13.5-1

### Ecto Versions

ecto 3.9.1, ecto_sql 3.9.0

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.5

### Current behavior

I have following query:
```elixir
def foo_query(...) do
  Ecto.Query.from(m in Model,
    ...,
    select: %{
      ...,
      bar: column |> complex_fragment() |> selected_as(:foo)
    },
    group_by: [selected_as(:foo), ...]
  )
end
```
which is then used as a subquery:
```elixir
Ecto.Query.from(os in subquery(other_query()),
  join: s in subquery(foo_query(...)),
  on:  os.bar == s.bar
  ...
)
```
This returns a runtime error
```
`selected_as/2` can only be used in the outer most `select` expression. If you are attempting to alias a field from a subquery or cte, it is not allowed because the fields are automatically aliased by the corresponding map/struct key. The following field aliases were specified: [:foo].
```
as if I was joining on `selected_as(:foo)` in outer query, and that's fair, because you could just use key of a struct

### Expected behavior

I think there's should no problems for properly scoped usage of `selected_as`, which doesn't "leak" between nested queries

**Comment by greg-rychlewski** [comment]
Hi @andrhua, 

If you use `selected_as` inside of a subquery then the SQL that is eventually generated would produce a double alias and the query would be invalid. Something like this:

```elixir
postgres=# select 1 as foo as bar;
ERROR:  syntax error at or near "as"
LINE 1: select 1 as foo as bar;
```

Could you elaborate, which valid SQL would you expect to be produced from your example above?

**Comment by andrhua** [comment]
```sql
select complex_transform(column) as foo
...
group by foo, ...
```
in other words I don't wanna to copy `complex_transform(column)` in GROUP BY clause

**Comment by greg-rychlewski** [comment]
Sorry not sure I understand. When you put it in a map with the key `bar` it will create the alias bar automatically. So what I mean is when you are already creating that alias and then on top of it use `selected_as` what behaviour are you expecting with 2 aliases?

**Comment by andrhua** [comment]
> When you put it in a map with the key bar inside of a subquery it will create the alias bar automatically
right, but there's no way to use it in `group_by: ...` if I'm not mistaken
> what behaviour are you expecting with 2 aliases?
I assumed `selected_as` was some sort of internal Ecto mechanism for aliasing columns, so it wouldn't collide with SQL `as`

**Comment by andrhua** [comment]
now I'm also confused about resulting query of example from docs
```elixir
from p in Post,
  select: %{
    posted: selected_as(p.posted, :date),
    sum_visits: p.visits |> coalesce(0) |> sum() |> selected_as(:sum_visits)
  },
  group_by: selected_as(:date),
  order_by: selected_as(:sum_visits)
```
here `posted` is a key in a map, but at the same time it's assigned `:date` alias

**Comment by greg-rychlewski** [comment]
Oh yes the alias is only automatically applied when it is used inside a subquery. This is because you need some way to reference the subquery fields from the outer query.

So if I understand you right, it would make sense for the `selected_as` alias to overwrite the automatic map alias inside of the subquery. I think this makes sense because if you're going out of your way to create the alias then you shouldn't want to use the map key.

I could look to see if this is possible. Or if you're interested I could leave it to you?

**Comment by andrhua** [comment]
I'd like to take a look if you point me in a right direction :smiley:

**Comment by greg-rychlewski** [comment]
Thanks!

So this change should all be in the planner: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/planner.ex.

The way the adapters know to alias a field is that the planner transforms them into tuples `{key, value}` where the key will be the alias and the value is your select expression.

This is where `selected_as` fields are transformed: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/planner.ex#L1331

This is where cte fields are transformed: https://github.com/greg-rychlewski/ecto/blob/1c7e232312820dcbd62fdbb8cb90c94fa746d1fa/lib/ecto/query/planner.ex#L1010

This is where subquery fields are transformed: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/planner.ex#L1108

So the trick would be making sure the `selected_as` tuple overwrites the other ones.

**Comment by andrhua** [comment]
finally I was able to have a look, and discovered a few things about how ecto works:

```elixir
from(q in queryable, select: %{foo: q.field}
```
is converted to
```sql
select q.field from queryable as q
```
whereas
```elixir
inner = from(q in queryable, select: %{id: q.id, foo: q.field})

from(aq in another_queryable, 
  join: i in subquery(inner), 
  on: aq.id == i.id,
  select: %{bar: aq.bar, foo: i.foo}
)
```

is amounts to
```sql
select aq.bar, i.foo
from another_queryable as aq
join (select q.id as id, q.field as foo from queryable as q) as i
on aq.id = i.id
```
I guess that's what you meant by automatic aliasing in subqueries.

now, if we'd imagine that auto aliasing happened for outer queries too, then there won't be a need for `selected_as`. I assume there are some reasons for that, but I haven't found a related discussion in https://github.com/elixir-ecto/ecto/pull/3966.

regarding your proposed solution, "overriding" aliases in an outer query is harmless because map keys aren't aliases in a result SQL query anyway. however for subqueries, outer queries should be referencing `selected_as` atom, not map/kw key, and I can see how this may be a point of confusion - `selected_as` aliases will be "internal" for outer query, but very much real for subqueries (on other side everybody will become versed about auto aliasing :smiley:) 

from this perspective I don't really see how we can workaround this cleanly with a modification of `selected_as`, more I look at it, more it looms as a leakage of implementation detail of a planner/whatever

**Comment by greg-rychlewski** [comment]
Thank you for investigating. I'll close it for now and will re-open if anyone else has an idea for tackling it.

>now, if we'd imagine that auto aliasing happened for outer queries too, then there won't be a need for selected_as.
It doesn't work for all scenarios, consider:

```elixir
from p in Post, select: p.visits |> coalesce(0) |> sum() , where: p.visits |> coalesce(0) |> sum() 
```

What would be the alias?

**Comment by greg-rychlewski** [comment]
Hey @andrhua,

We ended up adding this functionality here: https://github.com/elixir-ecto/ecto/pull/4040. It can be used in master. There's some discussion in there if you're interested in why that particular solution was chosen.

Hope this helps. Thanks for bringing this to our attention, I didn't think about this use-case.
