### ISSUE TITLE
Ecto.Changeset.validate_number not validating

### ISSUE THREAD

**Issue by haimiyahya** [elixir-ecto/ecto#4061]
### Elixir version

1.14.1

### Database and Version

None

### Ecto Versions

3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

None

### Current behavior

iex(1)> types = %{age: :integer, username: :string}
%{age: :integer, username: :string}
iex(2)> attrs = %{username: "player2", age: 1}
%{age: 1, username: "player2"}
iex(3)> {attrs, types} |> Ecto.Changeset.cast(attrs, Map.keys(types)) |> Ecto.Changeset.validate_number(:age, greater_than: 16) 
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [],
  data: %{age: 1, username: "player2"},
  valid?: true
>

### Expected behavior

valid?: false

**Comment by greg-rychlewski** [comment]
It's because there is no change so the validation doesn't happen. Try this:

```elixir
types =  %{age: :integer, username: :string}
attrs = %{username: "player2", age: 1}
changes = %{age: 2}
Ecto.Changeset.cast({type, attrs}, changes, Map.keys(types) |> Ecto.Changeset.validate_number(:age, greater_than: 16)
```

**Comment by haimiyahya** [comment]
Thank you @greg-rychlewski, really appreciate it.

Now I understand how it works.

{%{}, types} |> Ecto.Changeset.cast(attrs, Map.keys(types)) |> Ecto.Changeset.validate_number(:age, greater_than: 16)

**Comment by greg-rychlewski** [comment]
Yes exactly :). The first argument is your current data and the second is the changes you want to make to that data.
