### ISSUE TITLE
Change with_cte representation to {map, query}

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4067]
### Elixir version

Any

### Database and Version

Any

### Ecto Versions

master

### Database Adapter and Versions (postgrex, myxql, etc)

Postgres

### Current behavior

We changed the internal representation of with_cte to be:

    {string, materialized, query}

And that's a breaking change for adapters, so it should be removed from v3.9.

### Expected behavior

In order to avoid future breaking changes, I propose we change the format to be `{map, query}`, and we store both `:as` (and :materialized if any is given) in the map.

Thoughts?

**Comment by greg-rychlewski** [comment]
+1

**Comment by josevalim** [comment]
@maartenvanvliet, would you like to send a PR to amend this too? Thank you!

**Comment by maartenvanvliet** [comment]
Sure!
