### ISSUE TITLE
`preload/2` ends up with error if nested bindings

### ISSUE THREAD

**Issue by vshev4enko** [elixir-ecto/ecto#4069]
### Elixir version

1.14.1

### Database and Version

PostgreSQL 14.5

### Ecto Versions

v3.9.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

When i do preload with `^` operator and nested bindings Ecto checking `field2` association on `Schema2` which doesn't have one, looks like in case with `^` we have wrong preload expanding
```elixir
Schema1
|> preload(^[:field1, :field2, schema2: [:field1]])
|> Repo.all()

** (ArgumentError) schema App.Schemas.Schema2 does not have association or embed :field2
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.9.3) lib/ecto/repo/queryable.ex:235: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    iex:27: (file)
```

Actually expand has a bug

```elixir
iex(11)> Ecto.Query.Builder.Preload.expand([:field1, :field2, schema2: [:field1]], [])        
{[{:schema2, [:field1, :field2, :field1]}, :field2, :field1], []}
```

### Expected behavior

Should work like without `^`

**Comment by josevalim** [comment]
Does it work on v3.9.2 by any chance? :)

**Comment by vshev4enko** [comment]
Yes. it works on v3.9.2. Actually this new clause leads to wrong expanding https://github.com/elixir-ecto/ecto/blob/9561024c0ae494b7c1d3d9822fa079f00b127fdd/lib/ecto/query/builder/preload.ex#L138

**Comment by josevalim** [comment]
Hi @zachallaun, can you please take a look into this? It my affect you too. :)

**Comment by zachallaun** [comment]
On it o7
