### ISSUE TITLE
from/2 doesn't support fragments wrapped in a macro

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-ecto/ecto#4072]
### Elixir version

1.14.2

### Database and Version

PG 15

### Ecto Versions

3.9.2 (sql 3.9.1)

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

```elixir
import Ecto.Query

# this works
from(f in fragment("select generate_series(?::integer, ?::integer) as x", ^0, ^10), select: f.x)

# this doesnt
defmacro generate_series(range_start, range_end) do
  quote do
    fragment("select generate_series(?::integer, ?::integer) as x", unquote(range_start), unquote(range_end))
  end
end

from(f in generate_series(^0, ^10), select: f.x)

== Compilation error in file .../query.ex ==
** (CompileError) .../query.ex:59: cannot use ^0 outside of match clauses

from(f in generate_series(0, 10), select: f.x)

== Compilation error in file .../query.ex ==
** (CompileError) ..../query.ex:59: undefined function fragment/3 (expected XXX.Query to define such a function or for it to be imported, but none are available)
```

### Expected behavior

Should we be able to wrap complex fragments into a macro without compilation errors?

**Comment by AndrewDryga** [comment]
The same thing happens when fragment macro is used in `select/3`. I now feel like I'm doing something wrong?

**Comment by josevalim** [comment]
I believe we should support fragment in those places. This usually happens because we are trying to detect fragments inside `Select.escape` and `From.escape`, but we should let them happen recursively inside Builder.escape and validate if it is a fragment or not afterwards.

**Comment by josevalim** [comment]
@AndrewDryga can you provide code for the select one?

**Comment by AndrewDryga** [comment]
Hmm. I can't reproduce it for select anymore, my bad. Probably I made a typo somewhere. Initial issue is still value (double checked).

**Comment by AndrewDryga** [comment]
Omg, @josevalim you are such a 🚀. Thank you!

❤️ ❤️ ❤️
