### ISSUE TITLE
warning about field not present in invalid association, but field is present

### ISSUE THREAD

**Issue by Sleepful** [elixir-ecto/ecto#4078]
### Elixir version

1.14.4

### Database and Version

Yes

### Ecto Versions

3.9.1

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.5

### Current behavior

```elixir
defmodule A do 
	defmodule C do
		schema "table_a" do
			field :"company_#{:id}"
		end
	end
end

defmodule B do
	schema "table_b" do
		has_many :table_as, A.C, foreign_key: :"company_#{:id}"
	end
end
```

results in warning during compile time:

```
warning: invalid association `table_as` in schema B: associated schema A.C does not have field `company_id`
```

### Expected behavior

should work fine, right?

**Comment by josevalim** [comment]
Can you provide a small app that reproduces the error?

**Comment by greg-rychlewski** [comment]
fwiw I tried this out and can't reproduce

```elixir
Mix.install([
  {:ecto, "~> 3.9"}
])

defmodule A do
  defmodule C do
    use Ecto.Schema

    schema "table_a" do
      field :"company_#{:id}"
    end
  end
end

defmodule B do
  use Ecto.Schema

  schema "table_b" do
    has_many :table_as, A.C, foreign_key: :"company_#{:id}"
  end
end

defmodule Main do
  def main do
    IO.inspect(%B{})
  end
end

Main.main()

#%B{
#  __meta__: #Ecto.Schema.Metadata<:built, "table_b">,
#  id: nil,
# table_as: #Ecto.Association.NotLoaded<association :table_as is not loaded>
#}
```

```
% elixir -v
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.13.2 (compiled with Erlang/OTP 24
```

**Comment by Sleepful** [comment]
I need to take some time to try and re-create it in a repo that I can share. I can see it happen in my own larger project but I need to make it into a smaller example. I promise to come back to this when I have time, if I can't reproduce it in a small example I will let you know.

**Comment by Sleepful** [comment]
I can't reproduce the error and it stopped showing up in my code, must have been my mistake, sorry!
