### ISSUE TITLE
Improve error message for Ecto.Enum

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/ecto#4093]
This code:

```elixir
defmodule User do
  use Ecto.Schema

  schema "users" do
    field :email, :string
    field :role, Ecto.Enum, values: [:admin, :editor], default: :editor

    timestamps()
  end
end

Repo.insert!(%User{email: "alice@example.com", role: "admin"})
```

raises this error:

```
** (Ecto.ChangeError) value `"admin"` for `User.role` in `insert` does not match type
{:parameterized, Ecto.Enum, %{embed_as: :self, mappings: [admin: "admin", editor: "editor"],
on_cast: %{"admin" => :admin, "editor" => :editor}, on_dump: %{admin: "admin", editor:
"editor"}, on_load: %{"admin" => :admin, "editor" => :editor}, type: :string}}
```

Tested on Ecto 3.9.4.

The message has everything we need but I feel like we could improve it still:

```
** (Ecto.ChangeError) value `"admin"` for `User.role` in `insert` is invalid for Ecto.Enum. The allowed values are `:admin` and `:editor`.
```

Thoughts?

**Comment by josevalim** [comment]
Yes, we should improve it but also make it extensible so the logic is in the parameterized type and not in Ecto. Perhaps an optional `to_string` callback that defaults to `inspect`?

**Comment by wojtekmach** [comment]
Yup!

**Comment by v0idpwn** [comment]
Perhaps this could be possible for regular types as well?

**Comment by wojtekmach** [comment]
@v0idpwn we should look into that for sure but I'd assume it'd be something like this:

```
** (Ecto.ChangeError) value `"admin"` for `User.role` in `insert` does not match type :atom
```

which is pretty good. The problem was showing the internal structure of parameterised types which was too much.

**Comment by skbolton** [comment]
If it's up for grabs and not stepping on anybody especially toes I would like to work on this.

**Comment by wojtekmach** [comment]
Go for it!

**Comment by skbolton** [comment]
Does it make sense to have the callback be to_string and align with String.Chars, or does message make more sense to align with Exceptions and Changes etc custom error messages on a field.

**Comment by greg-rychlewski** [comment]
The former imo. I believe the goal is to pretty print the parameterized type.

**Comment by josevalim** [comment]
Yeah, now that we mention it, I would even call it `inspect(...)`.

**Comment by skbolton** [comment]
I'll get to work on it and we can always see it in action and the PR and pivot if it feels off. @greg-rychlewski I was really not wanting to step on your toes most of all if this was something you wanted to work on.

**Comment by greg-rychlewski** [comment]
oh yeah no worries go for it :)
