### ISSUE TITLE
Preload behavior with `field: false`

### ISSUE THREAD

**Issue by Sleepful** [elixir-ecto/ecto#4095]
### Elixir version

Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]  Elixir 1.14.2 (compiled with Erlang/OTP 23)

### Database and Version

postgresql

### Ecto Versions

* ecto 3.9.1 (Hex package) (mix)

### Database Adapter and Versions (postgrex, myxql, etc)

* postgrex 0.16.5 (Hex package) (mix)

### Current behavior

Given a schema like
```elixir
defmodule Comment do
      schema "comment" do
        belongs_to :post,
          Post,
          [foreign_key: :post_id,
		  define_field: false]  # <--- this makes Preload fail

        field :related_post, :integer,
          [source: :post_id]
      end

      def changeset(schema, attrs) do
        schema
        |> cast(attrs, [:post_id])
        |> cast_assoc(:post)
      end
end
```
the following fails:
```elixir
Comment
  |> Repo.get!(id)
  |> Repo.preload(:post)
```
with error like:
`(MatchError) no match of right hand side value`

### Expected behavior

I expected `define_field: false` to work fine with Preload.

Perhaps I am misunderstanding its purpose?

removing `define_field: false` works fine, so maybe not-a-bug and I am just holding-it-wrong

**Comment by greg-rychlewski** [comment]
If you provided a full stacktrace it would be easier for us to say for sure. But without knowing more preload will look for the value of the foreign key. So if it's not defined there will be a problem.

**Comment by Sleepful** [comment]
The stacktrace wasn't valuable at all, it was rather confusing, there were no line-numbers referencing any Ecto files, just some native Enum functions.

The `define_field` docs say: `When false, does not automatically define a :foreign_key field, implying the user is defining the field manually elsewhere`

So this is what I did in the schema, with `field :related_post, :integer, source: :post_id` which matches the `:foreign_key` in `belongs_to`.

Removing the `define_field: false` fixed the issue, but now I have two definitions of a foreign key, I thought this was going to cause issues but it works fine. So what is the use case for `define_field`? 

I suppose the meaning of `does not automatically define a :foreign_key field` is a little lost on me, what does it mean to `define an FK field` in this case?

Let me know if my questions are too specific and I should answer them by reading the source myself 😅

**Comment by greg-rychlewski** [comment]
> The stacktrace wasn't valuable at all, it was rather confusing, there were no line-numbers referencing any Ecto files, just some native Enum functions.

Is still better than nothing. Probably the people trying to solve the problem should decide?

>I defined the FK field manually with field :related_post, :integer, source: :post_id which matches the :foreign_key in belongs_to.

Your foreign key is `post_id` but the field you defined is `related_post`. They won't match. It's looking for the field on the schema.  ` [source: :post_id]` is a last minute translation before the query is executed but it's not affecting the preload behaviour.

**Comment by Sleepful** [comment]
alright let me find the stack trace:
```elixir
** (MatchError) no match of right hand side value: %WB.Classifier.Join.Word.Text{__meta__: #Ecto.Schema.Metadata<:loaded, "words_categories_join_text">, id: 85, values: #Ecto.Association.NotLoaded<association :values is not loaded>, word_id: 159, kind: #Ecto.Association.NotLoaded<association :kind is not loaded>, type: #Ecto.Association.NotLoaded<association :type is not loaded>, type_id: 126, inserted_at: ~N[2023-02-06 17:32:17], updated_at: ~N[2023-02-06 17:32:17]}
     code: |> Repo.preload(categories_text: [:type])
     stacktrace:
       (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (stdlib 4.0.1) maps.erl:411: :maps.fold_1/3
       test/w_b/base_test.exs:72: (test)
```

**Comment by Sleepful** [comment]
Thank you @greg-rychlewski,
Feel free to close this

**Comment by greg-rychlewski** [comment]
>it is a little funny/confusing to understand when the docs refer to foreign_key that matches the database and foreign_key that matches an Ecto field

Oh maybe we can improve the docs. Sorry could you point me this part and I'll try to make it better.
