### ISSUE TITLE
Prepare for v3.10

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4102]
### Elixir version

All

### Database and Version

All

### Ecto Versions

v3.10-dev

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

No v3.10.

### Expected behavior

Yes v3.10.

**Comment by josevalim** [comment]
@greg-rychlewski, are we ready to launch v3.10? Anything pending besides with ties PR?

**Comment by greg-rychlewski** [comment]
@josevalim Nothing pending besides that. I'll be able to finish it this weekend. I'm a big fan of https://github.com/lanodan/prometheus.ex/commit/31f7fbe4b71b79ba27efc2a5085746c4011ceb8f and think I can do it at the same time but if not I don't think it needs to block 3.10.

**Comment by josevalim** [comment]
No worries, we don't have to rush into this release either. We can wait a bit!

**Comment by LostKobrakai** [comment]
Is there any idea for when 3.10 will be released? There are some great features in there I'd like to start using.

**Comment by josevalim** [comment]
Soon. I wanted to avoid overlapping with Phoenix release and I also want to use this opportunity to release both Postgrex and MyXQL 1.0.

**Comment by josevalim** [comment]
It is out. Awesome job @greg-rychlewski and @v0idpwn !
