### ISSUE TITLE
has_one and has_many :through do not use the join table

### ISSUE THREAD

**Issue by noahduncan** [elixir-ecto/ecto#4114]
### Elixir version

1.14.2

### Database and Version

PostgreSQL 14.6

### Ecto Versions

ecto 3.9.4 / ecto_sql 3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

When using `:through` with `has_one` or `has_many` the join table is ignored.  The join in the SQL is made directly from the source table to the target table which ignores the presence, or more importantly the absence, of a record in the join table.

The current behavior is identified by the results of the code sample with the labels `ecto_has_one_through (unexpected)` and `ecto_has_many_through (unexpected)` results from the [attached code sample](https://github.com/elixir-ecto/ecto/files/10829695/sample3.exs.gz)

-- edit: updated attached code sample with versions to match issue report --

### Expected behavior

I would expect that if I'm joining through a join table, then no results would be returned for a `:through` relationship if a row in the join table does not exist.

The expected behavior is outlined in the results labeled with `manual_has_one_through (expected)` and `manual_has_many_through (expected)` from the code sample attached under "current behavior".

**Comment by greg-rychlewski** [comment]
Thanks for the Report. For reference, here is your script:

```elixir
Mix.install([
  {:ecto_sql, "~> 3.9.2"},
  {:postgrex, "~> 0.16.5"}
])

Application.put_env(:foo, Repo, database: "bug_sample", username: "postgres")

defmodule Repo do
  use Ecto.Repo,
    adapter: Ecto.Adapters.Postgres,
    otp_app: :foo
end

defmodule Migration0 do
  use Ecto.Migration

  def change do
    create table("transactions") do
      add(:merchant_id, :id)
    end

    create table("merchants") do
    end

    create table("metadata") do
      add(:merchant_id, :id)
      add(:contact_email, :string)
    end


  end
end

defmodule Transaction do
  use Ecto.Schema

  schema "transactions" do
    belongs_to :merchant, Merchant

    field :amount, :integer
    has_one :metadata, through: [:merchant, :metadata]
  end
end

defmodule Merchant do
  use Ecto.Schema
  
  schema "merchants" do
    has_one :metadata, Metadata
    has_many :transactions, Transaction
  end
end

defmodule Metadata do
  use Ecto.Schema

  schema "metadata" do
    field :contact_email, :string
    belongs_to :merchant, Merchant
    has_many :transactions, through: [:merchant, :transactions]
  end
end

defmodule Queries do
  import Ecto.Query

  @doc """
    Returns nil for contact_email. (expected)
  """
  def manual_has_one_through do
    from(t in Transaction,
      left_join: m in assoc(t, :merchant),
      left_join: md in assoc(m, :metadata),
      select: %{
        transaction_id: t.id,
        contact_email: md.contact_email
      }
    )
  end

  @doc """
    Returns nil for transaction.id. (expected)
  """
  def manual_has_many_through do
    from(md in Metadata,
      left_join: m in assoc(md, :merchant),
      left_join: t in assoc(m, :transactions),
      select: %{
        transaction_id: t.id,
        contact_email: md.contact_email
      }
    )
  end

  @doc """
    Returns a value for Metadata.contact_email. (unexpected)
  """
  def ecto_has_one_through do
    from(t in Transaction,
      left_join: md in assoc(t, :metadata),
      select: %{
        transaction_id: t.id,
        contact_email: md.contact_email
      }
    )
  end

  @doc """
    Returns a value for Transaction.id. (unexpected)
  """
  def ecto_has_many_through do
    from(md in Metadata,
      left_join: t in assoc(md, :transactions),
      select: %{
        transaction_id: t.id,
        contact_email: md.contact_email
      }
    )
  end
end

defmodule Main do
  def main do
    children = [
      Repo
    ]

    _ = Repo.__adapter__().storage_down(Repo.config())
    :ok = Repo.__adapter__().storage_up(Repo.config())

    {:ok, _} = Supervisor.start_link(children, strategy: :one_for_one)

    Ecto.Migrator.run(Repo, [{0, Migration0}], :up, all: true, log_sql: :debug)

    # SETUP
    #Repo.insert!(%Merchant{})
    Repo.insert!(%Metadata{merchant_id: 1, contact_email: "test@example.com"})
    Repo.insert!(%Transaction{merchant_id: 1})

    # HAS ONE
    IO.inspect(Repo.all(Queries.manual_has_one_through()), label: "manual_has_one_through (expected)")
    IO.inspect(Repo.all(Queries.ecto_has_one_through()), label: "ecto_has_one_through (unexpected)")

    # HAS MANY
    IO.inspect(Repo.all(Queries.manual_has_many_through()), label: "manual_has_many_through (expected)")
    IO.inspect(Repo.all(Queries.ecto_has_many_through()), label: "ecto_has_many_through (unexpected)")
  end
end

Main.main()
```

So you have a though association `Transaction` -> `Merchant` -> `Metadata`:

  - `Transaction` and `Metadata` are connected by `merchant_id`
  -  Your test data inserted `Transaction` and `Metadata` with the same `merchant_id` but didn't actually insert the `Merchant` record
  - This is allowed because your migrations are not setting the appropriate foreign key constraints.

So now your question is, why is `Metadata` loaded if the `Merchant` record is not existing?

My understanding is that `join_through` is not saying it will perform all the intermediary joins each time you preload the association. It will only associate the records through the proper chain of association fields.

So the result you are seeing is the correct/expected one because the association fields are aligning. The real issue is that your migrations are not enforcing referential integrity and that is the part that should be fixed.

But before you throw tomatoes at me, let's see what @josevalim says. I don't really use this part of Ecto and he might say I have no clue what I am talking about :).

**Comment by josevalim** [comment]
Thanks @noahduncan for the report and @greg-rychlewski for debugging. This is an optimization we do, which is probably welcome in many applications, but it assumes proper data references. I have documented this behaviour.

**Comment by noahduncan** [comment]
I can respect that design decision, and there is a work around by simply not using a `:through`.  

Thanks @greg-rychlewski and @josevalim for the fast responses and @josevalim for the documentation update!  Cheers!
