### ISSUE TITLE
Add Ecto.Changeset.changed?(changeset, field, filters \\ [])

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4117]
### Elixir version

Any

### Database and Version

Any

### Ecto Versions

All

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

No function exists.

### Expected behavior

I would like to add `Ecto.Changeset.changed?(changeset, field)` that returns a boolean if the field has changed. You can pass additional filters that will further restrict the verification. For example:

    Ecto.Changeset.changed?(changeset, :role, from: :admin)

will return true only if the field was previously an admin.

The following returns true only if the field was nilified:

    Ecto.Changeset.changed?(changeset, :role, to: nil)

Or only if the role changed from admin to editor:

    Ecto.Changeset.changed?(changeset, :role, from: :admin, to: :editor)

I feel this will make understanding how a field changed much more accessible. It doesn't cover some cases (the field was something BUT admin), but it should be generally useful.

**Comment by josevalim** [comment]
PRs are welcome! :)

**Comment by cjbottaro** [comment]
Gah, how did I not see there was already a PR for this? Oh well.

**Comment by josevalim** [comment]
Closing to avoid duplicate work :) see PR
