### ISSUE TITLE
Aliased modules names and nested embedded schemas

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4124]
### Elixir version

1.14

### Database and Version

Any

### Ecto Versions

All?

### Database Adapter and Versions (postgrex, myxql, etc)

Any

### Current behavior

From: https://groups.google.com/g/elixir-ecto/c/rxZT_kzPp2o

Today we got an issue that was very hard to understand the root cause, and maybe a compilation warning or failure would help when defining Ecto schema.

Let's say we had a module like this:

```elixir
defmodule Blog do
  use Ecto.Schema
 
  embeds_many :comments, Comment do
    field :text, :string
  end
...
end
```

It will generate two modules Blog, and Blog.Comment.

Later, an unware developer adds an alias:

```
 defmodule Blog do
   use Ecto.Schema
+  alias Utils.Comment
 
   embeds_many :comments, Comment do
     field :text, :string
   end
 ...
  end
```

The Blog.Comment will not exist anymore, and the developer will have a failure telling that Blog.Comment doesn't exist anymore in another file.

### Expected behavior

In Elixir, defining a module always overrides the previous alias. Perhaps Ecto should preserve the same behaviour as Elixir.

**Comment by greg-rychlewski** [comment]
I was trying to look into this. 

From what I can tell the difference between `defmodule` and `Module.create` in this situation is that eventually `defmodule` passes a tuple into `:elixir_module.compile` of the form `{full, old, new}` which is capturing the alias. But `Module.create` is just passing the module name.

Does it seem like I'm on the right track? Right now `Module.create` cannot accept a tuple and not sure if there is a workaround.

**Comment by josevalim** [comment]
Both :elixir_module.compile and Module.create already expect the expanded name, so I think we need to make sure we are properly expanding the name in Ecto. The logic is here: https://github.com/elixir-lang/elixir/blob/50741091baa10170805730ed91943c481b7ab270/lib/elixir/lib/kernel.ex#L4971-L4993 WDYT?

**Comment by josevalim** [comment]
PS: we can use `Module.concat` instead of the private `:elixir_aliases`
