### ISSUE TITLE
`dynamic()` conflicts with newly introduced built-in type in OTP26-rc2

### ISSUE THREAD

**Issue by moogle19** [elixir-ecto/ecto#4132]
### Elixir version

1.14.3

### Database and Version

-

### Ecto Versions

3.9.5

### Database Adapter and Versions (postgrex, myxql, etc)

-

### Current behavior

Ecto fails to compile with following error:
```
== Compilation error in file lib/ecto/query.ex ==
** (CompileError) lib/ecto/query.ex:431: type dynamic/0 is a built-in type and it cannot be redefined
    (elixir 1.14.3) lib/kernel/typespec.ex:936: Kernel.Typespec.compile_error/2
    (stdlib 5.0) lists.erl:1599: :lists.foldl_1/3
    (elixir 1.14.3) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
```
because OTP26-rc2 introduced a [new built-in type `dynamic()`](https://www.erlang.org/news/162#dialyzer).

### Expected behavior

Ecto should compile 🤷‍♂️

**Comment by josevalim** [comment]
Pushed a fix to main and released v3.9.5.
