### ISSUE TITLE
Unexpected wrapping transactions when using Repo modification functions and put_assoc

### ISSUE THREAD

**Issue by eprothro** [elixir-ecto/ecto#4146]
### Elixir version

Elixir 1.13.4 (compiled with Erlang/OTP 23)

### Database and Version

PostgreSQL 11.2.5

### Ecto Versions

ecto 3.9.5

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

When calling `Repo.insert/2` with a changeset using `put_assoc` to set the FK, I am seeing an unexpected transaction wrapping the query.

When I change to using `put_change` to set the FK, I do not see the transaction.

#### Example 
Adapted from my real-world example,  but using the terminology from the [Post/Comments example](https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4-example-adding-a-comment-to-a-post) in the docs:

##### using `put_assoc`
```elixir
params = %{body: "foo", post: post}

%Comment{}
|> Ecto.Changeset.cast(params, [:body])
|> Ecto.Changeset.put_assoc(:post, params[:post])
|> Repo.insert()
```

This generates an unexpected wrapping transaction, seen in ecto telemetry as well as at the postgres instance with logging set to `all`.

```
LOG:  statement: BEGIN
LOG:  duration: 0.121 ms
LOG:  duration: 1.007 ms
LOG:  duration: 0.207 ms
LOG:  execute <unnamed>: INSERT INTO "comments" ("post_id","body","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5)
DETAIL:  parameters: $1 = '01864cd8-63a1-4497-36fc-fdf10d51376a', $2 = 'foo', $3 = '018757f8-9898-3f66-f0e8-8cdaabcf32a5', $4 = '2023-04-06 19:08:42', $5 = '2023-04-06 19:08:42'
LOG:  duration: 5.035 ms
LOG:  statement: COMMIT
LOG:  duration: 0.884 ms
```

##### using `put_change`

```elixir
params = %{body: "foo", post: post}

%Comment{}
|> Ecto.Changeset.cast(params, [:body])
|> Ecto.Changeset.put_change(:post_id, post.id)
|> Repo.insert()
```

This generates no wrapping transaction, as expected.

```
LOG:  execute <unnamed>: INSERT INTO "comments" ("post_id","body","id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5)
DETAIL:  parameters: $1 = '01864cd8-63a1-4497-36fc-fdf10d51376a', $2 = 'foo', $3 = '018757fc-1b03-8a8a-d08c-718e34d92526', $4 = '2023-04-06 19:12:32', $5 = '2023-04-06 19:12:32'
LOG:  duration: 5.814 ms
```

### Expected behavior

I expect to see no transaction with a single modification statement, since this statement only involves one database operation. From ecto docs for the mod functions (`insert`, `update`, `delete`):

> If more than one database operation is required, they're automatically wrapped in a transaction.

---

**note**: This example shows unnamed prepared statements, but I did verify I saw the same behavior with the default configuration of named prepared statements.

**Comment by josevalim** [comment]
This is tricky to avoid because a changeset may write for several reasons:

1. It has changes
2. It has a flag to force a transaction
3. It has callbacks
4. Itself has associations/relations

Therefore, trying to see preemptively that a child has none of these is actually quite tricky. So in those cases, I suggest to rewrite the operation in a way that is less reliant on associations if that's a concern. :)
