### ISSUE TITLE
validate_number/3 yields a valid changeset when the provided value is a string with a single space

### ISSUE THREAD

**Issue by edwardsmit** [elixir-ecto/ecto#4152]
### Elixir version

1.14.3

### Database and Version

N/A

### Ecto Versions

3.10.0

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

In v3.10.0 adding a test with a string with a single space `" "` to the `validate_number/3` test in `test/ecto/changeset_test.exs` will succeed, but when the same test is done in the v3.9 branch, the test fails.

```elixir
 test "validate_number/3" do
    changeset = changeset(%{"upvotes" => " "})
         |> validate_number(:upvotes, greater_than: 0)
    assert changeset.valid?
    assert changeset.errors == []
    assert validations(changeset) == [upvotes: {:number, [greater_than: 0]}]
```

### Expected behavior

I expect the test to fail, just as it does on the v3.9 branch.

**Comment by josevalim** [comment]
That's because `" "` is considered as blank so it is discarded. v1.10 mirrors the concept of blank/presence used by `validate_required`with cast, as noted in the CHANGELOG. :)

**Comment by edwardsmit** [comment]
Ah, I didn't connect those dots. Thanks for your quick response.
