### ISSUE TITLE
Ecto v3.10 started to accept whitespace only characters in given data

### ISSUE THREAD

**Issue by ekatt2** [elixir-ecto/ecto#4166]
### Elixir version

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Database and Version

None

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

None

### Current behavior

With Ecto v3.10.1, validate_required/3 accepts whitespace only characters in given data (for Ecto v.3.9.x, this was invalid):
```
iex(1)> only_whitespace = %{attr: " "}
%{attr: " "}
iex(2)> types = %{attr: :string}
%{attr: :string}
iex(3)> Ecto.Changeset.change({only_whitespace, types}) |> Ecto.Changeset.validate_required(:attr)
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [],
  data: %{attr: " "},
  valid?: true
>
```
However, empty strings are still invalid (like in Ecto 3.9.x):
```
iex(4)> empty_string = %{attr: ""}
%{attr: ""}
iex(5)> Ecto.Changeset.change({empty_string, types}) |> Ecto.Changeset.validate_required(:attr)
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [attr: {"can't be blank", [validation: :required]}],
  data: %{attr: ""},
  valid?: false
>
```

### Expected behavior

In Ecto v3.9.x, **both** whitespace only **and** emtpy strings are marked as invalid by validate_required/3 when provided in given data.

It feels like a bug but if the change in behavior is intentional in v3.10, I am curious about the reasoning behind it

**Comment by josevalim** [comment]
Hi  @ekatt2, this is all mentioned in the CHANGELOG, including the rationale. The issues tracker should also have past discussions on the topic. :)
