### ISSUE TITLE
validate_json_path fix in 1.13 too strict for custom `:parameterized` types

### ISSUE THREAD

**Issue by Miradorn** [elixir-ecto/ecto#4169]
### Elixir version

1.14.3-otp25

### Database and Version

postgres 14.5

### Ecto Versions

1.13.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.1

### Current behavior

1. Use https://github.com/mathieuprog/polymorphic_embed and set up a polymorphic embed
2. query a field of a polymorphic embedded struct via `json` query
3. the query planner errors with 
    ```
    expected field `$FIELDNAME` to be an embed or a map, got: `{:parameterized, PolymorphicEmbed, $EMBED}`
    ```

### Expected behavior

As before the rework/fix in #4101 it should "just work" :D

I've run into this when trying to update to Ecto 0.13.1 and it stops us from updating since we rely on the `PolymorphicEmbed` library.

From my (very basic) understanding the `defp validate_json_path!([path_field | rest], field, {:parameterized, Ecto.Embedded, embed})` function head should not match on `Ecto.Embedded` to allow custom parameterized types, but that might break something else.

Help very much appreciated and as always thanks for your great work! :love

**Comment by greg-rychlewski** [comment]
Hi,

I believe we fixed it here: https://github.com/elixir-ecto/ecto/pull/4163

Could you give it a try and let us know?

**Comment by Miradorn** [comment]
Looks good, thanks for the pointer! ❤️

**Comment by Miradorn** [comment]
Hey there lovely people! Just wanted to ask if you may cut a new release with this fix included since it's stopped us from upgrading in a while. Thanks! ❤️
