### ISSUE TITLE
Ecto.UUID.cast succeeds on non-uuid strings with 16 characters

### ISSUE THREAD

**Issue by omginbd** [elixir-ecto/ecto#4174]
### Elixir version

Elixir 1.14.0; Erlang/OTP 25

### Database and Version

N/A

### Ecto Versions

3.9.4

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

Currently, given a non-uuid string of length 16 like "xxxxxxxxxxxxxxxx":

1. Call `Ecto.UUID.cast("xxxxxxxxxxxxxxxx")`
2. The cast succeeds and returns `{:ok, "78787878-7878-7878-7878-787878787878"}`

### Expected behavior

I would expect that given a non-uuid string of length 16 like "xxxxxxxxxxxxxxxx":

1. Calling `Ecto.UUID.cast("xxxxxxxxxxxxxxxx")`
2. Would fail to cast and instead return `:error`

I would expect this to be caught by some of the tests [here](https://github.com/elixir-ecto/ecto/blob/master/test/ecto/uuid_test.exs#L12), but it seems to specifically require a 16 character string.

**Comment by josevalim** [comment]
Yes, we support both binary (low-level) and string (high-level) UUIDs when casting. If you want to restrict, it can be done with a custom type. :)

**Comment by josevalim** [comment]
To further clarify, a UUID is stored as a 16 byte binary, which can be anything, even 16 x in a row.
