### ISSUE TITLE
Repo.aggregate not using query prefix

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4183]
### Elixir version

1.13.4

### Database and Version

13.3

### Ecto Versions

3.10

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16

### Current behavior

```
defmodule MyApp.Repo do
  def prepare_query(_, q, _) do
    IO.inspect(q.prefix)
  end
end

SomeSchema
|> Ecto.put_query_prefix("whatever")
|> MyApp.Repo.aggregate(:count)
```

inspect returns nil

### Expected behavior

inspect returns "whatever"

**Comment by tfwright** [comment]
I do think the result of the aggregate is correct, I presume because the subquery is using the prefix.

The issue I am running into is with some logic in prepare_query that checks the prefix

**Comment by josevalim** [comment]
Ah, we can copy the prefix to the parent. A PR is welcome!
