### ISSUE TITLE
Using dynamic in dynamic doesn't use schema field types

### ISSUE THREAD

**Issue by mattnenterprise** [elixir-ecto/ecto#4186]
### Elixir version

1.14.0

### Database and Version

PostgreSQL 10.23

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.1

### Current behavior

When using [dynamic/2](https://hexdocs.pm/ecto/Ecto.Query.html#dynamic/2) inside [dynamic/2](https://hexdocs.pm/ecto/Ecto.Query.html#dynamic/2) values in the query aren't being cast to the field type.

There is an example project with this behavior [here](https://github.com/mattnenterprise/ecto_dynamic). Here is an example output of running the query in iex.

```
iex(21)> import Ecto.Query
Ecto.Query
iex(22)> EctoDynamic.Dynamic
EctoDynamic.Dynamic
iex(23)> |> where(^EctoDynamic.ids_greater_than(Ecto.UUID.generate(), :id))
#Ecto.Query<from d0 in EctoDynamic.Dynamic,
 where: d0.id > ^"7cc0903b-a62b-4c09-bb61-a2e0ca783c2d" and true>
iex(24)> |> EctoDynamic.Repo.all()
[debug] QUERY ERROR source="dynamic" db=3.2ms queue=1.8ms idle=1306.2ms
SELECT d0."id", d0."inserted_at", d0."updated_at" FROM "dynamic" AS d0 WHERE ((d0."id" > $1) AND TRUE) ["7cc0903b-a62b-4c09-bb61-a2e0ca783c2d"]
↳ anonymous fn/4 in :elixir.eval_external_handler/1, at: src/elixir.erl:298
** (DBConnection.EncodeError) Postgrex expected a binary of 16 bytes, got "7cc0903b-a62b-4c09-bb61-a2e0ca783c2d". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    (postgrex 0.17.1) lib/postgrex/type_module.ex:947: Postgrex.DefaultTypes.encode_params/3
    (postgrex 0.17.1) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection 2.5.0) lib/db_connection.ex:1323: DBConnection.encode/5
    (db_connection 2.5.0) lib/db_connection.ex:1423: DBConnection.run_prepare_execute/5
    (db_connection 2.5.0) lib/db_connection.ex:1527: DBConnection.run/6
    (db_connection 2.5.0) lib/db_connection.ex:656: DBConnection.parsed_prepare_execute/5
    (db_connection 2.5.0) lib/db_connection.ex:648: DBConnection.prepare_execute/4
    (ecto_sql 3.10.1) lib/ecto/adapters/postgres/connection.ex:70: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:836: Ecto.Adapters.SQL.execute!/5
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    iex:24: (file)
iex(24)> 
```

I originally found this behavior from my work on https://github.com/duffelhq/paginator/pull/166, but made an example project to show a simpler example.

### Expected behavior

Values nested in [dynamic/2](https://hexdocs.pm/ecto/Ecto.Query.html#dynamic/2) calls are casted to the referenced field type. The docs include an example of building a query with nested dynamic calls [here](https://hexdocs.pm/ecto/dynamic-queries.html#building-dynamic-queries) so that seems to be the expectation for how dynamic works.

**Comment by greg-rychlewski** [comment]
Hi,

Thanks for the report. Is there a failing test in that repo or something like that you could point to? I was looking into this but it's not obvious to me which part in that example project is showing the issue.

**Comment by mattnenterprise** [comment]
It is the query [here](https://github.com/mattnenterprise/ecto_dynamic/blob/3611770d204da87464f0d42ec603acd2d2a4f9c8/lib/ecto_dynamic.ex#L11)

**Comment by greg-rychlewski** [comment]
Thanks that test helped a lot. So the issue is not with nested dynamics but it's because of the way the dynamic column is being accessed. If you'd like to do a dynamic column this is the way Ecto expects it:

```elixir
def ids_greater_than(id, column) do
  dynamic([query], field(query, ^column) > ^id and true)
end
```

The way given in the example was

```elixir
def ids_greater_than(id, column) do
  dynamic([query], ^field_query(column) > ^id and true)
end

def field_query(column) do
  dynamic([query], field(query, ^column))
end
```

Please let me know if this solves your issue.

**Comment by greg-rychlewski** [comment]
Actually sorry I see it now. I'm pretty sure you're right this should work. I think I see the issue.

**Comment by greg-rychlewski** [comment]
After looking at this for a while I believe you are allowed to interpolate a dynamic boolean condition inside of another dynamic but you cannot interpolate just the column name. i.e. you can do this

```elixir
def ids_greater_than(id, column) do
  dynamic([query], ^field_query(id, column) and true)
end

def field_query(id, column) do
  dynamic([query], field(query, ^column) > ^id)
end
```

but not this

```elixir
def ids_greater_than(id, column) do
  dynamic([query], ^field_query(column) > ^id and true)
end

def field_query(column) do
  dynamic([query], field(query, ^column))
end
```

It looks by design to me but should get information from @josevalim

**Comment by mattnenterprise** [comment]
If that is the case what is the recommended way to handle a situation where you are building a query where a part needs to be either a field or expression ? There is an example of that [here](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/lib/paginator/ecto/query/helpers.ex#L4) were I initially ran into this issue.

**Comment by greg-rychlewski** [comment]
I believe it is to encapsulate the entire boolean expression and not just the field.

**Comment by josevalim** [comment]
Yeah, each dynamic is analyzed in isolation right now. It is simpler to request the paginator project to build with `field(...) OP ^value` at once instead of in individual dynamic bits.

**Comment by mattnenterprise** [comment]
So are you recommending that we implement two versions of [field_or_expr/2](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/lib/paginator/ecto/query/helpers.ex#L4) for each operator ?

**Comment by josevalim** [comment]
Or that or convert it to macros so you are not wrapping everything in `dynamic`. The main issue here is the `dynamic` bits and a macro would allow you to compose without introducing the dynamic boundaries.

**Comment by mattnenterprise** [comment]
Are you recommending converting [field_or_expr/2](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/lib/paginator/ecto/query/helpers.ex#L4) to a macro ? An example of what you are describing with the macro would be really helpful.

**Comment by mattnenterprise** [comment]
The maintainers for paginator have been MIA for quite a while. The PR for this work is almost a year old at this point. I don't think it is to complicated so I will try to explain here best I can.

Paginator essentially build queries based on cursors field or expressions. The queries differ based on sort direction and the current values in the cursor. Here is a snippet from [asc_null_last.ex](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/lib/paginator/ecto/query/asc_nulls_last.ex#LL19C2-L33C6) of a few of the queries.

```elixir
def build_dynamic_filter(args = %{direction: :after, next_filters: true}) do
    dynamic(
      [{query, args.entity_position}],
      ^field_or_expr(args) > ^args.value or is_nil(^field_or_expr(args))
    )
  end

  def build_dynamic_filter(args = %{direction: :after}) do
    dynamic(
      [{query, args.entity_position}],
      (^field_or_expr(args) == ^args.value and ^args.next_filters) or
        ^field_or_expr(args) > ^args.value or
        is_nil(^field_or_expr(args))
    )
  end
```

[field_or_expr/2](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/lib/paginator/ecto/query/helpers.ex#LL4C1-L10C6) was written so either a field or an expression could be put into the query for a given cursor field depending on how the user configured the cursor field. You can see an example of an expression based cursor [here](https://github.com/mattnenterprise/paginator/blob/expression-cursor-v3/test/paginator_test.exs#L1037). Where the rank value isn't a field on the schema, but is computed using text search functions.

**Comment by josevalim** [comment]
I see, I would do `field_or_expr_equal` and `field_or_expr_greater` then. It seems like the simplest fix. :)

**Comment by mattnenterprise** [comment]
Is there a way we could make using dynamic in an unintended way like this a compilation error or at least put something in the docs about it ? The docs are a bit misleading now since the docs mention dynamic can be used to build the query bit by bit, but it really can't. Also using it the way we were worked depending on the field types. For example it worked fine when a field was a string or a datetime, but caused a runtime error when the field was a UUID.

**Comment by josevalim** [comment]
The dynamic is still valid because you can use it in select. Perhaps the note we need to add is that "type casting does not cross dynamic boundaries".
