### ISSUE TITLE
Clearly error when log config is set to true

### ISSUE THREAD

**Issue by wodow** [elixir-ecto/ecto#4188]
### Elixir version

Elixir 1.14.4 (compiled with Erlang/OTP 23)

### Database and Version

Any

### Ecto Versions

ecto 3.9.5, ecto_sql 3.9.2

### Database Adapter and Versions (postgrex, myxql, etc)

Any

### Current behavior

As per https://hexdocs.pm/ecto/Ecto.Repo.html , `:log` config key can be a log level atom or `false`.

This can cause confusion when reading a config file without the docs to hand, as flipping `false` to `true` seems like an obvious option, but is not prevented and leads to errors such as https://github.com/elixir-ecto/ecto_sql/issues/351 

Such a config should be considered invalid.

### Expected behavior

Throw an error (at compile time?)

**Comment by wodow** [comment]
Added this as a bug with the intention to write a PR, as keeps tripping me up and can't be that difficult... but please close if this should go to the mailing list as an idea instead.

**Comment by josevalim** [comment]
A PR is welcome although I am almost sure it should belong to the ecto_sql repo.

**Comment by greg-rychlewski** [comment]
Yeah IMO it should be here https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L735
