### ISSUE TITLE
Can't use subquery result at `on:` join

### ISSUE THREAD

**Issue by MateusAquino** [elixir-ecto/ecto#4189]
### Elixir version

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Database and Version

PostgreSQL 13-alpine

### Ecto Versions

ecto 3.9.2, ecto_sql 3.9.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

Having a subquery returning a list from an aggregate function, and using its return to write a new join is totally feasible in PostgreSQL. Here's a dummy example (n:n) of a relation Author <-> Pair (book authors) <->  Books

```ex
Author
|> join(:left, [a], pair in subquery(pair_query), as: :pair, on: a.id == pair.author_id)
|> join(:left, [a, pair], cp in Pair, on: cp.book_id == any(pair.books)) # <- fails to parse any(pair.books)
|> ...
```

In this example the subquery `pair_query` is returning a list of ids: `select array_agg(book_id) as books`, this works in postgresql, however, the elixir code above throws the following ArgumentError:

```== Compilation error in file lib/conciliador/inputs/system/system_cashin.ex ==
** (ArgumentError) invalid expression for join `:on`, subqueries aren't supported
    (ecto 3.9.2) lib/ecto/query/builder/join.ex:210: Ecto.Query.Builder.Join.build_on/7
    (ecto 3.9.2) lib/ecto/query/builder/join.ex:187: Ecto.Query.Builder.Join.build/10
    (ecto 3.9.2) expanding macro: Ecto.Query.join/5
```

ref: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder/join.ex#L215

### Expected behavior

As the subquery's join is aliased, it should converge to something like this:

```sql
LEFT JOIN pairs ON pairs.book_id = ANY(pair.books)
```

**Comment by greg-rychlewski** [comment]
Hi,

Thanks for the report. The `any` you are using is actually not the same as Postgres operator. [It means something else in Ecto](https://hexdocs.pm/ecto/Ecto.Query.API.html#any/1):

```
Tests whether one or more values returned from the provided subquery match in a comparison operation.
```

What you want to do should be achievable by something like this:

```elixir
s = from p in Post, select: %{agg: fragment("array_agg(?)", p.title)}
q = from p in Post, join: s in subquery(s), on: p.title in s.agg
```

This will generate the SQL you are expecting here:

```sql
LEFT JOIN pairs ON pairs.book_id = ANY(pair.books)
```

Please give it a try and let me know if you still have an issue.

**Comment by greg-rychlewski** [comment]
I should clarify, the subquery `any` is not a new construct by Ecto. It is something Postgres and other databases have: https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-ANY-SOME

**Comment by MateusAquino** [comment]
Oh, you're right @greg-rychlewski! Thank you so much for the clarification, indeed the query worked like a charm by using the `in` operator instead :D
