### ISSUE TITLE
The order for has_many :through  associations is not working.

### ISSUE THREAD

**Issue by freevova** [elixir-ecto/ecto#4192]
### Elixir version

1.14.3

### Database and Version

11.8

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.1

### Current behavior

Let's say I have following schemas:
```elixir
defmodule Post do
  use Ecto.Schema

  schema "posts" do
    has_many :comments, Comment
    has_many :authors, through: [:comments, :author]
  end
end

defmodule Comment do
  use Ecto.Schema

  schema "comments" do
    belongs_to :author, Author
    belongs_to :post, Post
  end
end
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    field :name, :string
  end
end
```
and I want to get authors for the post, ordered by name with preload, like:
```elixir
query = order_by(Author, [desc: :name])
post_with_authors = Post |> Pt.Repo.all() |> Pt.Repo.preload([authors: query])
```

I tried to insert multiple authors with different names, but they were not loaded according to the query's order.
`post_with_authors` performs 3 queries: 
```sql
SELECT ... FROM "posts"
SELECT ... FROM "comments" AS c0 WHERE (c0."post_id" = ANY(...)) ORDER BY c0."post_id"
SELECT ... FROM "authors" AS a0 WHERE (a0."id" = ANY('...')) ORDER BY a0."name" DESC
```
I suppose this is because of the intermediate schema(Comment), because if I run the last SQL query in the psql everything works as expected.

### Expected behavior

the right order of items after preloading associations with has_many :through.

**Comment by josevalim** [comment]
Correct. We load the authors into the comments and then we load them in the order from comments. I am not sure there is a fix here besides adding a note to preload docs to mention the query apply to the last step of a has through association.
