### ISSUE TITLE
Pool lazy true has not effect and overflow doesn't work

### ISSUE THREAD

**Issue by dmitrydprog** [elixir-ecto/ecto#4197]
### Elixir version

1.14.4

### Database and Version

Postgresql 15

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

Postgrex, 0.15.13

### Current behavior

1.
Set config at: 

config :my_app, MyApp.Repo,
  ...,
  pool_size: 5,
  max_overflow: 50,
  lazy: true

2.
Run app

3.
Fetch count connection from pg_stat_activity:

```sql
SELECT state, wait_event, datname  FROM pg_stat_activity
where datname = 'myapp'
```

Actually:

|state |wait_event|datname |
|------|----------|--------|
|idle  |ClientRead|contract|
|idle  |ClientRead|contract|
|idle  |ClientRead|contract|
|idle  |ClientRead|contract|
|idle  |ClientRead|contract|

4.
Run code from iex:

```elixir
for i <- 1..50, do: (
  spawn fn ->
    MyApp.Repo.raw "SELECT pg_sleep_for('15 seconds');"
  end
)
```

Repeat SQL from step 3:

|state |wait_event|datname |query                               |
|------|----------|--------|------------------------------------|
|active|PgSleep   |contract|SELECT pg_sleep_for('20 seconds');  |
|active|PgSleep   |contract|SELECT pg_sleep_for('20 seconds');  |
|active|PgSleep   |contract|SELECT pg_sleep_for('20 seconds');  |
|active|PgSleep   |contract|SELECT pg_sleep_for('20 seconds');  |
|active|PgSleep   |contract|SELECT pg_sleep_for('20 seconds');  |

Actually only five connection are open

### Expected behavior

Step 3 expected 0 connection, because lazy set in true
Step 4 expected 50 connections be opened

**Comment by dmitrydprog** [comment]
I found it on the page: https://hexdocs.pm/ecto/1.1.0/Ecto.Pools.Poolboy.html

**Comment by josevalim** [comment]
@dmitrydprog that page is for version 1.1.0. The current version is 3.10.1. The lazy option is not supported nor it has been for quite some time. :)

**Comment by dmitrydprog** [comment]
Ok, this issue has two problem, first with lazy, second with overflow, which don't create new connection.
First resolved, my mistake, sry.

**Comment by josevalim** [comment]
None of those options are supported anymore. Please check the latest docs. :)

**Comment by dmitrydprog** [comment]
Mmm, what was the reason for rejecting these settings?
I find them very useful and would like to have some kind of replacement, and not implement my own pool for connections.
