### ISSUE TITLE
load/1 in @behaviour Ecto.Type is not called on insert or update

### ISSUE THREAD

**Issue by aus70** [elixir-ecto/ecto#4198]
### Elixir version

1.14.4

### Database and Version

SQLite 3.39.2

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

ecto_sqlite3 0.10.3

### Current behavior

Create a custom Ecto type:

```
defmodule MyApp.Type.Data do
  @behaviour Ecto.Type
  def type, do: :string
  def cast(value) when is_binary(value), do: {:ok, value}
  def cast(value) when is_map(value), do: {:ok, encode_data(value)}
  def cast(value) when is_list(value), do: {:ok, encode_data(value)}
  def load(value), do: {:ok, decode_data(value)}
  def dump(value) when is_binary(value), do: {:ok, value}
  def dump(value) when is_map(value), do: {:ok, encode_data(value)}
  def dump(value) when is_list(value), do: {:ok, encode_data(value)}
  def dump(_), do: :error
  def embed_as(_format), do: :dump
  def equal?(x, y), do: encode_data(x) == encode_data(y)

  defp encode_data(data) do
    data |> :erlang.term_to_binary() |> Base.encode64()
  end

  defp decode_data(data) do
    data |> Base.decode64!() |> :erlang.binary_to_term()
  end
end
```

Then try inserting, getting, updating a record containing the custom type.

### Expected behavior

`Repo.get` correctly returns the custom type, `Repo.insert` and `Repo.update` do not, and return the native type instead, as if the `load/1` callback would not be called.

Possibly related to https://github.com/elixir-ecto/ecto/issues/345

**Comment by josevalim** [comment]
insert and update is not going to call `load` because they are not loading data from the database. Can you please provide a more complete example of what is in your schema and which repo operations you are calling?

**Comment by greg-rychlewski** [comment]
I think the `returning` option is probably not being specified so it is just showing the casted values.

**Comment by aus70** [comment]
> I think the `returning` option is probably not being specified so it is just showing the casted values.

That solves the problem, thanks!
Should I be happy with this solution or am I misusing Ecto?

**Comment by greg-rychlewski** [comment]
These parts are a bit unintuitive to me:

```elixir
 def cast(value) when is_binary(value), do: {:ok, value}
  def cast(value) when is_map(value), do: {:ok, encode_data(value)}
  def cast(value) when is_list(value), do: {:ok, encode_data(value)}
  def load(value), do: {:ok, decode_data(value)}
```

The loaded value should be the casted value but here they are different.

**Comment by v0idpwn** [comment]
@aus70 you don't need to encode on `cast/1`, you should encode only on `dump/1`. The value returned by `cast` should be the "canonical form" of the data inside your application, being able to convert input to the canonical form. `dump/1` receives  the canonical form and returns how its sent to the database, load converts from how the database sends it to canonical form.

**Comment by greg-rychlewski** [comment]
Yeah exactly. I was going to say Jose summed it up nicely in the referenced ticket:

>cast should receive any type and output the ecto type (list)
dump should receive the ecto type (list) and output the db type (binary)
load should receive the db type (binary) and output the ecto type (list)

**Comment by aus70** [comment]
I'd a tad confused: All I need is to transparently store a Map or a List in the Data field. Hoping to have understood your suggestions right, I revised the type accordingly:

```
  def type, do: :string
  def cast(value), do: {:ok, value}
  def load(value), do: {:ok, decode_data(value)}
  def dump(value), do: {:ok, encode_data(value)}
  def embed_as(_format), do: :dump
  def equal?(x, y), do: encode_data(x) == encode_data(y)
```

Does it make sense?

**Comment by greg-rychlewski** [comment]
It looks correct to me if your goal is to convert any elixir term to/from base64. You could also return an error from `cast` is it is not a list or a map if you want to guard against other types being used.

**Comment by aus70** [comment]
> It looks correct to me if your goal is to convert any elixir term to/from base64. You could also return an error from `cast` if it is not a list or a map if you want to guard against other types being used.

Thanks! I just removed my last question, because it's better suited for the elixir forum. For the records,  and hoping it'll help other people, here is my latest version of the type, about which you commented:

```
@behaviour Ecto.Type
def type, do: :string
def cast(value), do: {:ok, value}
def load(value), do: {:ok, decode_data(value)}
def dump(value), do: {:ok, encode_data(value)}
def embed_as(_format), do: :dump
def equal?(x, y), do: encode_data(x) == encode_data(y)
```
