### ISSUE TITLE
Cheatsheet example (Updating all associated records, using external data) is wrong

### ISSUE THREAD

**Issue by Munksgaard** [elixir-ecto/ecto#4199]
### Elixir version

1.14.3

### Database and Version

Postgres 15.2

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgresx

### Describe the bug

The cheatsheet for ecto has an example of how to update existing records using external data: https://hexdocs.pm/ecto/associations.html#updating-all-associated-records-using-external-data.

As far as I can tell, the example doesn't work, because [`cast_assoc/3`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) is used incorrectly. Specifically, the documentation shows that the third argument is some options, not the params, and that the params should instead be `cast` (and should contain the parent struct as well).

I'm not sure how best to fix the documentation. I've resorted to using `put_change` in my own code, but other suggestions (such as moving `params` to the `cast` call) have been suggested. However, it should be noted that the current `params` also pose difficulties (in having string keys, and in not having the parent struct included).

**Comment by v0idpwn** [comment]
You're right. I think it would be nice to use `put_change/2` since we already have an example using `cast` + `cast_assoc` here: https://hexdocs.pm/ecto/associations.html#inserting-parent-and-child-records-together (even though its an insert)

PRs welcome :) (or just let me know and I send myself)
