### ISSUE TITLE
Error when using json_extract_path on a field using custom type after updating from 3.9 to 3.10

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4200]
### Elixir version

1.13.4

### Database and Version

postgres 13

### Ecto Versions

3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

Assuming a schema with a field defined with a custom type something like this

```
defmodule Thing
  schema "things" do
    field :object, CustomType
  end
end

defmodule CustomType do
  use Ecto.Type

  def type, do: :map
  
  # ...
end

from(t in Thing, where: t["key"] == "val") |> Repo.all()
```

I get an error like this:

```
     ** (RuntimeError) expected field `object` to be an embed or a map, got: `CustomType`
     stacktrace:
       (elixir 1.13.4) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.10.1) lib/ecto/repo/queryable.ex:34: Ecto.Repo.Queryable.stream/3
```

### Expected behavior

I would expect the query succeed, which it does when using Ecto 3.9.2.

If this was an expected change in the API then I think we should make the error more clear about why it does not work.

**Comment by v0idpwn** [comment]
Hi, @tfwright, I believe this was fixed here: https://github.com/elixir-ecto/ecto/pull/4195, but it wasn't released yet.

**Comment by tfwright** [comment]
My bad for not checking first! Thanks!
