### ISSUE TITLE
`Repo.insert!` with `on_conflict: [inc: ...]` does not return the incremented result

### ISSUE THREAD

**Issue by feynmanliang** [elixir-ecto/ecto#4202]
### Elixir version

1.14.4

### Database and Version

PostgreSQL 15.2

### Ecto Versions

3.10.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.17.1

### Current behavior

1. Create a table+schema with an integer field

```elixir
defmodule CreateExample do
  use Ecto.Migration

  def change do
    create table(:example) do
      add :volume_bytes, :integer
    end
  end
end

defmodule Example do
  use Ecto.Schema
  import Ecto.Changeset

  schema "example" do
    field(:volume_bytes, :integer)
  end
end
```

2. Create an `Example` and upsert to it with an increment (`:inc`) for the `on_conflict` option. Below, the first `insert!` succeeds without issue while the second violates the `id` primary key constraint and dispatches to `on_conflict`

```elixir
    {:ok, _} = Repo.insert!(
      %Example{
        id: 1
        volume_bytes: 2
      },
      on_conflict: [inc: [volume_bytes: +2]],
      conflict_target: [:id]
    )
    {:ok, result} = Repo.insert!(
      %Example{
        id: 1
        volume_bytes: 3
      },
      on_conflict: [inc: [volume_bytes: +3]],
      conflict_target: [:id]
    )
```

Actual behavior: `result.volume_bytes == 3`.

It seems like even when `on_conflict` runs, `Ecto.Repo.insert!` returns the struct in the first argument position. I would expect the correct behavior to be to return the state of the actual DB, but perhaps I am missing something?

### Expected behavior

Expected behavior: `result.volume_bytes == 5`, because it is first created with `volume_bytes=2` and then subsequently incremented again by `5` in the second `insert!`

**Comment by feynmanliang** [comment]
I am still receiving the value passed as the struct first argument to `insert!` even with `read_after_writes`; is that expected behavior as well?

**Comment by v0idpwn** [comment]
Ah, sorry, @feynmanliang, to do it in the Repo call, the option is named differently, its `:returning`.
