### ISSUE TITLE
Docs for Ecto.Repo.insert_all and update_all do not describe what happens on error

### ISSUE THREAD

**Issue by wodow** [elixir-ecto/ecto#4223]
### Elixir version

1.14

### Database and Version

N/A

### Ecto Versions

3.10.2

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

https://hexdocs.pm/ecto/Ecto.Repo.html#c:delete_all/2 and https://hexdocs.pm/ecto/Ecto.Repo.html#c:update_all/3 do not mention errors.

https://stackoverflow.com/a/43688851/ suggests errors are raised.

### Expected behavior

Documentation should include at least that errors are raised vs `:error` returned or similar.

**Comment by greg-rychlewski** [comment]
I might be wrong but I believe it's standard that anything not returning  `:error` or `{:error, e}` could potentially raise. Otherwise you'd have to specify on all the functions things like this:

**Comment by greg-rychlewski** [comment]
@josevalim Do you think it's ok to close this one? Personally I am not sure either of the options for documentation are good:

1. Put each possible `raise` in every function
2. Put it in the module doc where I think it will be missed most of the time

**Comment by josevalim** [comment]
I think it is worth adding something to the Repo moduledoc saying that functions may raise adapter specific errors, such as `PostgrexError`. Otherwise exceptions, such as ArgumentError, FunctionClauseError, etc do not need to be commented.
