### ISSUE TITLE
Ecto.UUID.cast casts a string value that is not a valid UUID

### ISSUE THREAD

**Issue by dantuck** [elixir-ecto/ecto#4224]
### Elixir version

1.14.0

### Database and Version

PostgreSQL 15.2

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

`Ecto.UUID.cast!("warehouse worker")`

The output is `"77617265-686f-7573-6520-776f726b6572"`

### Expected behavior

** (Ecto.CastError) cannot cast "warehouse worker" to Ecto.UUID
    (ecto 3.8.4) lib/ecto/uuid.ex:54: Ecto.UUID.cast!/1
    iex:1: (file)

**Comment by josevalim** [comment]
Yes, we match 16 bytes UUIDs (their raw representation) and any 16 bytes are valid. You can consult previous reports for more info. :)

**Comment by lytedev** [comment]
@josevalim Would you accept a contribution to the documentation for this function that provides this context? Looks like you've posted the same response a couple of other times and perhaps clarifying this case in the functions docstring would be beneficial -- even though its typespec sort of provides some clarity.

Previous reports:

- https://github.com/elixir-ecto/ecto/issues/4174
- https://github.com/elixir-ecto/ecto/issues/3125
