### ISSUE TITLE
Prefix missing in association on_delete query

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4225]
### Elixir version

1.13.4

### Database and Version

postgres 13

### Ecto Versions

3.10

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

Similar issue to https://github.com/elixir-ecto/ecto/issues/4183 (affecting `prepare_query`)

Add has_many association with :on_delete option
Delete parent record, loaded from prefix
Observe query.prefix is nil

### Expected behavior

query.prefix should be same as parent

**Comment by josevalim** [comment]
Perfect. so I agree delete_all and nilify_all should use the prefix. PRs welcome too!
