### ISSUE TITLE
Subquery in select generates conflicting cache key

### ISSUE THREAD

**Issue by Coffei** [elixir-ecto/ecto#4241]
### Elixir version

1.14.3

### Database and Version

PostgresSQL 15

### Ecto Versions

tried on 3.10.1 and master

### Database Adapter and Versions (postgrex, myxql, etc)

0.16.2

### Current behavior

I am having issues using subqueries in select clause. First of all, this is not mentioned as supported in the [current documentation](https://hexdocs.pm/ecto/Ecto.Query.html#subquery/2), but it is mentioned in a [recent changelog](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#v390-2022-09-27) so I am not sure what's the status of this feature. Still, feels like a bug that should be fixed.

TLDR: When I use a subquery in select clause the generated cache key only contains `{:subquery, 0}` instead of more details about the subquery. This can easily cause cache conflicts.

In the example/reproducer below you can observe the following. There are two different queries each using a subquery in a select. Both these queries produce the same key for the Ecto cache, but the queries are different - one takes 1 parameter the other takes 0 parameters. So if you use a query with 1 parameter, the cache returns the previously cached query with 0 parameters and it crashes.

The model and queries are purely for demostration purposes.

```elixir
defmodule EctoBugSubqueryInSelect do
  # some model and repo, details are not important for the bug
  alias AssetMap.Ecto.Model.Incident
  alias AssetMap.Ecto.Repo
  import Ecto.Query, only: [from: 2]

  # Functions `run_bug*` demonstrate that subquery used inside select clause causes Ecto to generate
  # conflicting cache key for the query. The key doesn't contain information about the subquery and
  # contains just `{:subquery, 0}`. This can cause a collision of two differnet queries (e.g. two
  # queries with different number of params which causes a crash).

  def run_bug1 do
    clear_cache()
    IO.inspect(bug("a"))
    # this uses the cached query from the previous line and causes an error since it expects to
    # receive 1 parameter
    IO.inspect(bug())
  rescue
    x ->
      IO.puts("ERROR: #{x.message}")
      # 1 query in the cache
      [a] = :ets.tab2list(cache())
      # key is the same as in run_bug2
      elem(a, 0)
  end

  # same as above but in reversed order
  def run_bug2 do
    clear_cache()
    IO.inspect(bug())
    # this uses the cached query from the previous line and causes an error since it expects to
    # receive 0 parameters
    IO.inspect(bug("a"))
  rescue
    x ->
      IO.puts("ERROR: #{x.message}")
      # 1 query in the cache
      [a] = :ets.tab2list(cache())
      # key is the same as in run_bug1
      elem(a, 0)
  end

  # subqueries in select are not mentioned as supported in the docs, but are implemented as per the
  # changelog: https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#v390-2022-09-27
  #
  # queries don't make sense, they only demonstrate how cache keys can conflict
  def bug(a) do
    q = from(i in Incident, where: i.type == ^a, limit: 2, select: count(i.id))
    Repo.all(from(x in Incident, limit: 1, select: %{a: x.subject, b: subquery(q)}))
  end

  def bug do
    q = from(i in Incident, where: i.type == "a", limit: 2, select: count(i.id))
    Repo.all(from(x in Incident, limit: 1, select: %{a: x.subject, b: subquery(q)}))
  end

  def clear_cache do
    :ets.delete_all_objects(cache())
  end

  def cache do
    :ets.all() |> Enum.filter(&(:ets.info(&1, :name) == Repo)) |> hd()
  end
end
```

To reproduce run `EctoBugSubqueryInSelect.run_bug1` and `EctoBugSubqueryInSelect.run_bug2`. The function will crash with incorrect number of params and will output the query cache key, which is as follows on my machine.

```elixir
[
  :all,
  {:limit, {false, 1}},
  {:from, {"incidents", AssetMap.Ecto.Model.Incident, 99480805, nil}, []},
  {:select,
   {:%{}, [],
    [a: {{:., [], [{:&, [], [0]}, :subject]}, [], []}, b: {:subquery, 0}]}}
]
```

### Expected behavior

Subqueries should work in select clause. IMO the cache key should be more specific and should include details about the subquery, so that collisions of different queries cannot happen.

**Comment by Coffei** [comment]
I'd like to credit @bossek who originally found this issue.

**Comment by greg-rychlewski** [comment]
Thanks for the report @Coffei . Could you please try the fix we pushed to master?

**Comment by greg-rychlewski** [comment]
Would you want to send a PR to add it to the docs, btw?

**Comment by Coffei** [comment]
Thanks for a speedy fix! I confirm it works fine now. I'll see if I can improve the docs.

**Comment by Coffei** [comment]
Created #4244 for the doc update.
