### ISSUE TITLE
many_to_many cast_assoc update seems to create even when id is present in params

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4250]
### Elixir version

1.14

### Database and Version

postgres 13

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.1

### Current behavior

Add many_to_many association between parent schema Foo and child schema Bar

```
defmodule Foo do
  schema "foos" do
    many_to_many :bars, Bar
  end
end

defmodule Bar do
  schema "bars" do
  end
end
```

Insert Foo changeset with params for an existing bar:

```
b = Bar.insert!()

f = %Foo{} |> Ecto.Changeset.cast(%{bars: [%{id: b.id}]}) |> Repo.insert()
```

`f.bars` is associated with a new bar record with a different id

### Expected behavior

Based on docs for `cast_assoc` `f` should be associated with existing `b` record

See also https://elixirforum.com/t/cast-assoc-issue-with-many-to-many/23046/6

**Comment by tfwright** [comment]
Will try to recreate this with a test case as well.

**Comment by tfwright** [comment]
Working in many_to_many_tests.exs. In this test case it does not try to insert a new post, but it doesn't show any changes parents at all:

```
  test "with no params" do
    posts = [%Post{title: "first", id: 1}]
    params = [%{"id" => 1}]

    changeset =
      %Author{posts: posts}
      |> Ecto.Changeset.cast(%{"posts" => params}, [])
      |> Ecto.Changeset.cast_assoc(:posts, with: fn post, params ->
        Changeset.cast(post, params, [])
      end)

    assert [first] = changeset.changes.posts
    assert first.data.id == 1
  end
```

```
  1) test with no params (Ecto.Changeset.ManyToManyTest)
     test/ecto/changeset/many_to_many_test.exs:132
     ** (KeyError) key :posts not found in: %{}
     code: assert [first] = changeset.changes.posts
     stacktrace:
       test/ecto/changeset/many_to_many_test.exs:144: (test)
```

**Comment by greg-rychlewski** [comment]
The error you are seeing is because the changeset function for the assoc is not producing any changes. You could change it to this

```elixir
  test "with no params" do
    posts = [%Post{title: "first", id: 1}]
    params = [%{"id" => 1, "title" => "second"}]

    changeset =
      %Author{posts: posts}
      |> Ecto.Changeset.cast(%{"posts" => params}, [])
      |> Ecto.Changeset.cast_assoc(:posts, with: fn post, params ->
        Changeset.cast(post, params, [:title])
      end)

    assert [first] = changeset.changes.posts
    assert first.data.id == 1
  end
```

**Comment by greg-rychlewski** [comment]
In general this is how cast assoc works:

1. If the pk is in the params but not in the data then it's an insert.
2. If the pk is in both the params and the data then it's an update
3. If the pk is in the data but not in the params then it's a delete
4. If there is no pk in either then a new pk is created and inserted

It's probably explained better here: https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3

**Comment by tfwright** [comment]
@greg-rychlewski 🤦 yes of course that's the wrong setup for my case

after changing the test to this

```
  test "with no params" do
    posts = []
    params = [%{"id" => 1}]

    changeset =
      %Author{posts: posts}
      |> cast(%{"posts" => params}, :posts)

    assert [first] = changeset.changes.posts
    assert first.data.id == 1
  end
```

I get the following error 

```
  1) test with no params (Ecto.Changeset.ManyToManyTest)
     test/ecto/changeset/many_to_many_test.exs:132
     Assertion with == failed
     code:  assert first.data.id == 1
     left:  nil
     right: 1
     stacktrace:
       test/ecto/changeset/many_to_many_test.exs:141: (test)
```

**Comment by greg-rychlewski** [comment]
Thanks. That is expected because the data for that change is an empty struct. Since the `posts` data is an empty list there is no pre-existing data and the change is considered relative to a new struct.

**Comment by tfwright** [comment]
I think this is the crux of the issue: `If the pk is in the params but not in the data then it's an insert.`

I see that is also pretty clearly stated in the docs so I might be misunderstanding the rationale here.

Does this mean it is intentionally not permitted to associate existing children with a parent using cast_assoc? Only to insert new children and/or update _already_ associated records?

**Comment by greg-rychlewski** [comment]
I believe so. At least it looks very intentional to me. Jose was the only one around when it was made though so we could also see what he says. 

Thinking about it, Ecto has to know what operation to do before it hits the database. So it has no way of knowing the data exists unless it's told so.

I think the standard thing to do in this case is to update the association struct with the foreign key of the parent, once the parent is created.

**Comment by tfwright** [comment]
If it's not possible to change the behavior, I can open a PR expanding the docs on this case to explicitly say that creating new associations to already existing data is not permitted with `cast_assoc`?

**Comment by greg-rychlewski** [comment]
I was actually playing around with `put_assoc` and it seems like that does what you want. Can you give it a try?

**Comment by tfwright** [comment]
Oh I know I can use put_assoc in this case, in fact I was using it before. I ran into this issue when trying to implement a refactor that abstracted some custom changeset behavior for a whole group of assocs. I need cast_assoc for a few of those, and for most of them cast_assoc works fine, but just not for one many_to_many I need to handle. That's fine, I can easily modify the refactor to handle the one many_to_many individually using put_assoc.

**Comment by greg-rychlewski** [comment]
Ah ok. Sorry I have to think about your comments because tbh I don't touch these things too much. 

I think the crux is that Ecto looks to see if the data struct is `:built` (this happens when you create a struct in your code without loading it from the db, or it's implicitly created by Ecto because it's not supplied) or `:loaded` (this happens when it is returned from the db).

From this it infers whether it's an insert or update (built = insert, loaded = update). 

My first thought is this can't and shouldn't be changed. So most likely something to make the docs clearer would be the best route.

**Comment by tfwright** [comment]
> My first thought is this can't and shouldn't be changed. So most likely something to make the docs clearer would be the best route.

That makes sense to me. Although I do still wonder about the use case for inferring casting id -> insert. Why would an external input (the target use case for cast_assoc) have an id it knows should be used to create the record with? It seems _much_ more likely they would be trying to associate external data. 

So unless I'm still missing something, it seems like it might be preferable to make such a changeset invalid, or at least issue a warning instead of just trying to create?

**Comment by greg-rychlewski** [comment]
> That makes sense to me. Although I do still wonder about the use case for inferring casting id -> insert. Why would an external input (the target use case for cast_assoc) have an id it knows should be used to create the record with? It seems much more likely they would be trying to associate existing data, which isn't actually allowed.

We can ask Jose he will have a lot better insight into the rationale. What I'm thinking of is a form where a list of some association is presented to the user and they can edit fields. They don't have to know whether the IDs exist or not but your app does.

**Comment by tfwright** [comment]
> What I'm thinking of is a form where a list of some association is presented to the user and they can edit fields. 

So I think that's exactly the case I would like to handle but is not allowed currently, because that would be associating existing data (records with ids).

The form that the existing behavior would support is having the _user_ enter an id to use to create a _new_ record to be associated....

If the user wants to create the child at the same time they are associating it with the parent, which works fine currently, they would not be providing the id.

**Comment by greg-rychlewski** [comment]
It might be that the application creates the ID as well. If autogeneration is not being used.

**Comment by tfwright** [comment]
>  If autogeneration is not being used.

Hm, right I didn't consider that case.

**Comment by greg-rychlewski** [comment]
Basically you want to put the existing association and then possibly add a change to it right? What about this

```elixir
test "with no params" do
    p = TestRepo.insert!%Post{title: "first", id: 1}
    cs = Ecto.Changeset.cast(p, %{title: "second"}, [:title])

    r =
      %User{posts: []}
      |> Ecto.Changeset.cast(%{}, [])
      |> Ecto.Changeset.put_assoc(:posts, [cs])
      |> TestRepo.insert!()

    IO.inspect r
  end
```

**Comment by tfwright** [comment]
In my case I do not even need to change the association records, just add them to the parent's association. It's not difficult to handle, I was just confused that/why `cast_assoc` couldn't handle it.

**Comment by josevalim** [comment]
> I believe so. At least it looks very intentional to me. Jose was the only one around when it was made though so we could also see what he says.

Yes, because allowing that would be a security risk. For example, imagine you have manager table which has many projects. If I can assign any random ID, I could get a project that does not long to this org and assign it to my manager. Depending on how the query is structured, then I get visibility in projects from other orgs.

There could be ways to limit this but the best is to close the attack vector altogether and simply not allow this feature via cast_assoc. You can associate them in other, more explicit, ways. :)
