### ISSUE TITLE
on_confict: :replace_all gives ERROR 42601 (syntax_error) when using fields that source existing fields

### ISSUE THREAD

**Issue by benstepp** [elixir-ecto/ecto#4251]
### Elixir version

Elixir 1.15.4, OTP 26.0.2

### Database and Version

Postgres 15.3

### Ecto Versions

ecto 3.10.3, ecto_sql 3.10.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.2

### Current behavior

When using `on_conflict: :replace_all` and using fields that `:source` other existing fields, ecto generates invalid sql. Ecto already provides some mechanisms to get around this issue, such as `{:replace_all_except, fields}`, or `{:replace, fields}` but this can become quite cumbersome with larger schemas.

Here's a test case that reproduces this scenario:

```elixir
# migration
defmodule EctoConflictTarget.Repo.Migrations.CreateUsers do
  use Ecto.Migration

  def change do
    create table(:users) do
      add(:email, :string)
      add(:full_name, :string)
      timestamps()
    end

    create unique_index(:users, [:email])
  end
end

# test case
defmodule EctoConflictTargetTest do
  use EctoConflictTarget.DataCase

  defmodule User do
    @moduledoc false

    use Ecto.Schema

    schema "users" do
      field(:email, :string)
      field(:full_name, :string)
      field(:legacy_full_name_field, :string, source: :full_name)
      timestamps()
    end
  end

  @timestamp NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)

  test "insert with on_conflict: :replace_all" do
    Repo.insert!(%User{email: "user@ecto.test"})

    assert {:ok, %User{}} =
             Repo.insert(%User{email: "user@ecto.test", full_name: "First Last"},
               conflict_target: [:email],
               on_conflict: :replace_all
             )
  end

  test "insert_all with on_conflict: :replace_all" do
    Repo.insert!(%User{email: "user@ecto.test"})

    assert {1, nil} =
             Repo.insert_all(
               User,
               [
                 %{
                   email: "user@ecto.test",
                   full_name: "First Last",
                   inserted_at: @timestamp,
                   updated_at: @timestamp
                 }
               ],
               conflict_target: [:email],
               on_conflict: :replace_all
             )
  end
end
```

```
  1) test insert with on_conflict: :replace_all (EctoConflictTargetTest)
     test/ecto_conflict_target_test.exs:48
     ** (Postgrex.Error) ERROR 42601 (syntax_error) multiple assignments to same column "full_name"

         query: INSERT INTO "users" ("email","full_name","inserted_at","updated_at") VALUES ($1,$2,$3,$4) ON CONFLICT ("email") DO UPDATE SET "id" = EXCLUDED."id","email" = EXCLUDED."email","full_name" = EXCLUDED."full_name","full_name" = EXCLUDED."full_name","inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at" RETURNING "id"
     code: Repo.insert(%User{email: "user@ecto.test", full_name: "First Last"},
     stacktrace:
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto 3.10.3) lib/ecto/repo/schema.ex:764: Ecto.Repo.Schema.apply/4
       (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       test/ecto_conflict_target_test.exs:52: (test)



  2) test insert_all with on_conflict: :replace_all (EctoConflictTargetTest)
     test/ecto_conflict_target_test.exs:58
     ** (Postgrex.Error) ERROR 42601 (syntax_error) multiple assignments to same column "full_name"

         query: INSERT INTO "users" ("inserted_at","email","full_name","updated_at") VALUES ($1,$2,$3,$4) ON CONFLICT ("email") DO UPDATE SET "id" = EXCLUDED."id","email" = EXCLUDED."email","full_name" = EXCLUDED."full_name","full_name" = EXCLUDED."full_name","inserted_at" = EXCLUDED."inserted_at","updated_at" = EXCLUDED."updated_at"
     code: Repo.insert_all(
     stacktrace:
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:803: Ecto.Adapters.SQL.insert_all/9
       (ecto 3.10.3) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7
       test/ecto_conflict_target_test.exs:62: (test)

..
Finished in 0.1 seconds (0.00s async, 0.1s sync)
2 tests, 2 failures
```

### Expected behavior

Expected behaviour is ecto doesn't produce invalid sql. It would be nice to not have to use `{:replace_all_except, [:legacy_full_name_field]}`.

I would be happy to submit a PR. It looks like I can fix this by wrapping the following with `Enum.uniq`, adding a sourced column to MySchema in ecto/test/ecto/repo_test.exs and updating the on_conflict related tests. 

https://github.com/elixir-ecto/ecto/blob/e9520e48f76254b25a7ab62a8bea4632da99b2d6/lib/ecto/repo/schema.ex#L729-L731

**Comment by greg-rychlewski** [comment]
Thank you for opening an issue. TBH I think a different PR should be made, to raise a compile error when a source conflicts with an existing field name. Otherwise you will have other issues like performing updates. Imagine the scenario below:

```elixir
p = TestRepo.insert!%Post{title: "one", title2: "two"}
cs = Ecto.Changeset.cast(p, %{title: "new_one", title2: "new_two"})
TestRepo.update!(cs)
```

Where `:title2` is mapped to `:title`. Which value should be saved in the database?

**Comment by benstepp** [comment]
Yeah that is quite the question... I will say that we really like being able to source existing columns, and I'd hate to lose them to a compile error.

Some context, we have been slowly transitioning from bigints (and some i32s from the rails 3 days) to uuids for primary keys. We have older schemas with an id of bigint and a separate public_id of uuid, and newer schemas with id of uuid, and a public_id that just sources the id column. It's really convenient to just use public_id and get a public facing uuid back regardless of how the data is stored.

**Comment by greg-rychlewski** [comment]
So for sure having them conflicting like this can't be allowed. It just doesn't work. 

It seems to me like you want the old field to hang around but don't want it to interfere with your queries? If that is the case maybe making it `:virtual` would work for you? If it does we could also add a condition to not raise against virtual fields.

**Comment by benstepp** [comment]
Yeah, we want to just call struct.public_id and have it be whatever public facing uuid we are using.

For old schemas this is just a regular `field(:public_id, Ecto.UUID, autogenerate: true)`, for newer schemas
we have been using `field(:public_id, Ecto.UUID, source: :id, read_after_writes: true)` with pretty decent success. 

Virtual fields don't support read_after_writes, so they wouldn't work for us in this case.

**Comment by greg-rychlewski** [comment]
The part I'm not sure I understand is when you have a schema like this:

```elixir
field :id, :uuid
field :public_id, :uuid, source: :id
```

What's the motivation for keeping the first field? And if you need to keep it what's the motivation for reading the same value into both fields?

**Comment by benstepp** [comment]
Having the :id field is primarily for database consistency and convenience. It makes it so all association related constructs are named consistently and work automatically (across multiple backend languages).

We could copy to a virtual field (either :id to :public_id or :public_id to :id), but it isn't supported automatically (virtual fields do not support read_after_writes). So, the motivation is not having to manually copying an id for ~100 schemas at every location they are queried or modified in the codebase.

**Comment by greg-rychlewski** [comment]
>Having the :id field is primarily for database consistency and convenience. It makes it so all association related constructs are named consistently and work automatically (across multiple backend languages).

You could keep the `:id` field in the database though and remove it from the Ecto schema. It's completely ok to have a schema that doesn't include all the fields in the table. Would that solve your issue?

**Comment by benstepp** [comment]
I'd say that could work for us, we'll just have some insane cleanup to do. While we use struct.public_id everywhere that is public, we use struct.id for everything internally (like assigning association_ids and generating cache keys), and that's going to be a mess to change.

Compile time checks to forbid sourcing existing fields is not perfectly ergonomic, but I can live with it.

**Comment by greg-rychlewski** [comment]
Since it's an an usual situation let's see what the other maintainers say too.

**Comment by josevalim** [comment]
> field :id, :uuid
> field :public_id, :uuid, source: :id

We would be able to support it if we introduce the concept of `read_only` fields. The fields can never be set, only read from whatever the database gives. But I can also see people wanting some sort of `read_or_insert_only` and I am not sure if it is worth going down that path.

**Comment by greg-rychlewski** [comment]
Those kind of behaviours are pretty easily controlled by the user as well. i.e. not casting the field in changesets or specifying them in `:replace_all_except`. 

It's hard for me to say the added complexity to the code base is worth it. Because we wouldn't be able to change a single place and have it flow through everywhere. We'd have to be on top of all the places that insert/update/delete data now and in the future. 

I might be a bit biased though because tbh I'm not sure I 100% understand the use case.

**Comment by benstepp** [comment]
We've had an `integer :id` and `uuid :public_id` as a solution to not expose auto incrementing ids for years before we migrated to elixir, and in our perfect world we would just have a singular `:id` column. Sourcing `:id` into `:public_id` was a method of keeping the schemas consistent with older tables because changing the older tables is just not something we can do quickly.

However, I do see the many problems and increased complexity of sourcing existing fields, so I think disallowing sourcing existing fields is probably the best solution for most. However it would be cool if `[virtual: true, source: :id]` worked when loading structs, but that might be unnecessarily complex too.

**Comment by greg-rychlewski** [comment]
Is the `public_id` something you just expose through API/PubSub, etc?

If so you could, for example, implement `Jason.Encoder` to transform the field names on the way out: https://hexdocs.pm/jason/Jason.Encoder.html

**Comment by benstepp** [comment]
Yeah our problem has lots of different solutions, sourcing an existing field just seemed like the easiest. We'll probably just create our own PublicId protocol, and find and replace every '.public_id' in the codebase, or wrap OurApp.Repo with another module and some custom struct loading to copy the field over for every schema that defines a virual public_id field. Both seem easy and I'm leaning toward a protocol to not perform unneeded copying, which is probably better performance wise than sourcing in the first place. I'd say a compile error on duplicate source fields is perfectly fine.

**Comment by greg-rychlewski** [comment]
>[virtual: true, source: :id]

Something like this might not be out of the question. Though it would have to be more generic, I think. Something like giving the ability to return/store an arbitrarily calculated value. I would have to dig deeper to see how possible this is though. Also not sure if this idea was already discussed/rejected in the past.

**Comment by v0idpwn** [comment]
@greg-rychlewski similar ideas have been proposed a few times (even I proposed something similar once!), you can find such proposals in the mailing list.

**Comment by greg-rychlewski** [comment]
@benstepp Sorry for the long silcence. We added read only fields, which should help with you situation here.
