### ISSUE TITLE
Ecto association doesn't reset after the ID has been updated (from Changeset changes)

### ISSUE THREAD

**Issue by francois08** [elixir-ecto/ecto#4256]
### Elixir version

1.14.4

### Database and Version

PostgreSQL 15

### Ecto Versions

3.6

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

Say in the changeset function I allow to change a foreign key:
```elixir
defmodule MyApp.Transactions.Revenue do
  schema "revenues" do
    # ...
    belongs_to :wallet, Wallet
  end

  def changeset(revenue, attrs) do
    required_fields = ~w(date amount wallet_id)a
    revenue
    |> cast(attrs, required_fields)
    |> validate_required(required_fields)
  end
end
```

```elixir
def update_revenue(%Revenue{} = revenue, attrs) do
  revenue
  |> Revenue.changeset(attrs)
  |> Repo.update()
end
```

If `revenue` had a wallet preloaded (which we can't know as all we know is that we receive a `revenue` struct with preloaded assocs or not) and the ID has been changed, after a successful update the association will not match with the ID.

Can't we reset the associations as we know from the Changeset that the IDs have changed (present in `:changes`)?

If not, I wonder how this problem is solved. It must be pretty common because as an example, I imagine a user may select the wallet through a combo box for the revenue, and so we receive a wallet ID in a form or absinthe request. Assuming the wallet will never be preloaded is dangerous and error-prone (and I opened this issue because what happened to me is that the `wallet` was preloaded - and didn't match with the ID which led to bugs - because the code for my real case is more complex than the example code shown, as it uses transactions for example).

We should know the source of truth in this case from `:changes`.

### Expected behavior

Expected the association to reset to not-loaded

**Comment by josevalim** [comment]
This is “expected”. Ecto never loads and reloads data behind the scenes for associations, Because while it works in some cases, it also leads to surprising and often slow behavior in others. You can chose to preload the association again by calling Repo.preload with the force option.

**Comment by francois08** [comment]
What do you think about something like this? (quickly wrote it down, it would be adapted to make it reusable)

```elixir
  def changeset(revenue, attrs) do
    required_fields = ~w(date amount wallet_id)a
    revenue
    |> cast(attrs, required_fields)
    |> validate_required(required_fields)
    |> unload_assocs()
  end

  defp unload_assocs(changeset) do
    if changed?(changeset, :wallet_id) do
      unload_assoc(changeset, :wallet_id) # unfortunately I'm not aware of such a function (to set to `NotLoaded`)
    else
      changeset
    end
  end
```

**Comment by josevalim** [comment]
I see. Now that you proposed that, I actually changed my mind: I think on update we can see if any of the foreign key changed and, if so, unload the association.

**Comment by greg-rychlewski** [comment]
Would it be surprising for users if some associations were updated and not others?  For example would we update the `has_*` associations if the `:references` field was changed? Similarly for `:through` associations I think there would be inconsistencies with the intermediate structs.

**Comment by josevalim** [comment]
I think this applies only to `belongs_to`, no? The other associations cannot be updated by definition but I guess your point is precisely that inconsistency?

**Comment by francois08** [comment]
In my perspective this is only for belongs_to where we have a foreign key and a nested struct.
By the lack of this proposal, all the nested structs which may turn stale due to a change of the foreign key should be forcefully preloaded after each Repo update.
1. the context need to be aware of the fields being casted in order to preload with force true after an update, because the context doesn't know if a nested assoc was loaded or not (which leads to error-prone code as a change in the schema might require to change the context and vice versa because of coupling).
2. we might preload too much and so we may do so conditionally using assoc_loaded?, which requires then a lot of code.

My guess is that most codebases using Ecto do not have this check because in most cases the nested struct is not loaded when passed to the context update_ function, but it is only thus by chance and it is wrong to assume that it is not loaded, so for robust code each Repo update should check if an assoc should be forcefully preloaded or not.

I'll leave space to others:) just wanted to highlight that this would be really nice to have as it avoids a lot of bloat that otherwise would be needed.

**Comment by greg-rychlewski** [comment]
Yeah I was mostly questioning if it would be surprising for users if it worked for `belongs_to` but not for the following situations:

**has_{one,many}**
```elixir
schema "a" do
  field :referenced_field
  has_{one,many} :b, B, references: :referenced_field
end
```

If `:b` is preloaded and `:referenced_field` is updated then the preload is also not valid anymore. 

**many_to_many**

```elixir
schema "a" do
  field :referenced_field
  many_to_many :b, B, join_keys: [a_field: :referenced_field, ...]
end
```

Similar thing here except it's even more complicated than the `has` variant because changing `:referenced_field` might invalidate some of the preloads or all of them or none of them.

**through**

```elixir
schema "a" do
  belongs_to :b_id, B
  has_one, :c, through: [:b, :c]
end

schema "b" do
  field :referenced:field
  has_one, :c, C, references: :referenced_field
end
```

If you are doing an update where `a.c` is already preloaded and `a.b_id` doesn't change but `b.referenced_field` changes then `a.c` is not valid anymore and it is hard to detect because none of the fields changed on `a`. I'm not 100% sure if this kind of nested update is allowed and I'm a bit short on time to look. Apologies if that's the case.

**Comment by greg-rychlewski** [comment]
Maybe I can make my point more clearly:

If we are concerned about discrepancies between preloads and the "regular" fields that define them, I'm not sure I understand what is special about foreign keys in this case. You are allowed to preload on both sides of the relationship, so both sides can equally be out of sync. 

And if we agree with this then we have extra complications when dealing with `through` associations due to nested updates (assuming they are allowed, I think they are but can't remember 100%).

**Comment by francois08** [comment]
- if it leads to an inconsistency between loaded belongs_to and has_{one,many} and other cases, this could be clarified in the docs, that we handle one case and not the others. If it is then documented,  the developers are now informed, and they do not have to handle the most common case themselves (see next point).

- what are truly the alternatives? My guess is that most codebases using Ecto do something like below, even when foreign keys might have changed:
```elixir
def update_foo(foo, attrs) do
  foo
  |> Foo.changeset(attrs)
  |> Repo.update()
end
```
It's wrong to me eyes. Now we need a convention in the application that after the Repo update call, we need to call the function (which could be a new Elixir library) `reload_changed_assocs`. This function will check whether A. a foreign key has changed, B. the nested struct is loaded, and if both conditions are true, call Repo preload with force true. It would need to be always called to avoid the added cognition load: if I add a foreign key in the cast, I have to remember to add that function for every Repo update call on that changeset int he application. As it needs to be always called, it should be in Ecto.

**Comment by josevalim** [comment]
@greg-rychlewski a possible counter argument is that I am almost sure belongs to already has special logic in a couple places. If you do `employee |> put_assoc(:company, company)`, doesn't it automatically set the `company_id` in employee? This doesn't happen on `has_*`, since there is no field to set?

**Comment by greg-rychlewski** [comment]
Ah ok if it’s already setting the foreign key like that then it would be pretty consistent to unset the association when it changes. 

Probably there will still be some confusion for people not acquainted with that behaviour but it seems like it could be explained pretty reasonably.

**Comment by francois08** [comment]
THANK YOU! Any recommended way I can test this before release?

And I just noticed the recent addition of `Ecto.reset_fields/2`, which also avoids me in some places some force reloads, and instead just let me unload the stale associations.

With these 2 new features I feel much more confident using Ecto! This updates makes a huge difference for me as this prevents possible bugs and unnecessary forced preloads, and consequently helps the Elixir codebases to be a little safer for free for all developers; that's always a win!

<3

**Comment by greg-rychlewski** [comment]
We're happy it helps :).

If you wanted to try it out before release you could change your ecto dependency in `mix.exs` to refrence this repo:

```elixir
{:ecto, git: "https://github.com/elixir-ecto/ecto.git"}
```
