### ISSUE TITLE
has_many with through: Impossible to apply filter to first query/model shows warnings

### ISSUE THREAD

**Issue by iStefo** [elixir-ecto/ecto#4258]
### Elixir version

1.15.2

### Database and Version

Postgres 14

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

Postgres 0.17.2

### Current behavior

I have read several of the previous tickets to the situation with `has_many` associations with `through` and I understand that preload queries & functions can only customise the last step of the association.

However, this is very unfortunate for our use case where we want to use the `through` table to filter the association.

If we define the relationship as
```elixir
has_many :comment_authors, through: [:comments, :authors]
```
we can't use the the function preload to filter the `comments` association as described in the docs.

If we define the relationship as
```elixir
has_many :comment_authors, Author
```
(which wouldn't work without custom preload queries, but that's fine for us since there is specific application logic that needs to happen anyways) we receive a compiler warning because the associated Author schema has no `post_id` field.

We're currently rolling with the second option, but having that warning is definitely not ideal.

### Expected behavior

It would be nice if we could

a) access/filter the `posts` -> `comments` association preload or
b) mark the second `has_many` definition as *virtual* or something similar s.t. preloading with custom queries/functions still works but Ecto doesn't validate the association

**Comment by josevalim** [comment]
> I have read several of the previous tickets to the situation with has_many associations with through and I understand that preload queries & functions can only customise the last step of the association.

Yes, this is because we prepopulate and reuse each step of the association. Changing it means rewriting large chunks of how through associations work and it will require us to execute more queries, so I don't see we going down this path.

> has_many :comment_authors, Author

If the issue is the field, then you can always set it to something else that exists, such as `foreign_key: :id`. We would also accept a PR that adds an option to skip the warning.

**Comment by iStefo** [comment]
Thanks for your reply.
It seems like setting the `foreign_key` to any field of the target model is not the solution, though. While it solves the warning, it cannot really be *any* field, since it is used by the preloader for `has_many` relationships to zip the records back together.
For the query to actually work, I needed to define a virtual `post_id` field on the target schema and populate that in the custom preload query – but a virtual field doesn't satisfy the schema compiler and thus the warning persists.

In the end, a (temporary?) solution is to model the relationship as `many_to_many` and still use a custom preload function because now we can return tuples of `{post_id, Author}` and apply as much filtering logic on the intermediate table as desired. I just hope that no-one tries to use the association for updating in the future...

**Comment by greg-rychlewski** [comment]
Are you not able to do a normal nested preload because you want to separately load comments without the filter?

**Comment by iStefo** [comment]
Thanks for following up.

I think that nested preloading is somewhat unergonomic since most parts of the application code are only interested in the association target. The intermediate table really only serves the purpose of creating this specific many-to-many association (so reusing it is not an issue). It also stores additional data required for filtering this association (think composite foreign keys which aren't currently available).

So in theory, it could be possible to `preload(comments: {^adjusted_comments_query(…), [:author]})`, is that what you suggest? I haven't tried it out, though.

**Comment by greg-rychlewski** [comment]
> So in theory, it could be possible to preload(comments: {^adjusted_comments_query(…), [:author]}), is that what you suggest? 

Yeah basically this. I thought it might model the relationship more accurately, if it is 1:n instead of m:n. But wasn't sure if there was a reason why it didn't work for your case.

**Comment by greg-rychlewski** [comment]
Also if the relationship between comments and author is 1:1 you could probably save a query by making the join inside of `adjusted_comments_query`.

**Comment by iStefo** [comment]
Unfortunately, it's not 1:1 but n:m.

To explain the situation in a bit more detail: We're writing a multi-tenancy system where `client_id` is used to restrict access by tenant. If we stay at the example of `post -> comments -> authors`, then a single post can be accessible by multiple tenants with different comments each (hence the need to filter the intermediate association).
Additionally, the equivalent of `comment -> author(s)` uses a compound foreign key (hence the need for another custom filter).

Effectively, our preload setup now looks like this (using a join):

```elixir
# Post schema:
many_to_many :comment_authors, Author, join_through: Comments

# Post context:
def load(post_id, client_id, params) do
  from(p in Post, where:
    # Contrived check whether post is accessible by client
    p.id in ^allowed_posts_for_client(client_id))
  |> maybe_preload(client_id, params)
  |> Repo.one()
end

def maybe_preload(query, client_id, %{with_authors: true}) do
  preload(query, comment_authors: ^&preload_comment_authors(&1, client_id))
end

def preload_comment_authors(post_ids, client_id) do
  from(c in Comment, where: c.post_id in ^post_ids
    # Note the first "special" condition here, as the post can have comments across clients
    and c.client_id = ^client_id
  )
  |> join(:left, [c], a in Author, on: c.author_id = a.id and
    # Second "special" thing, but fully contrived here...
    c.foo = author.foo
  )
  |> select([c, a], {c.post_id, a})
end
```

So while this seems to work as intended, it would be cooler if Ecto supported more advanced association preload in these two ways:
- Dynamic filters based on context (`client_id` in this case). Generally possible, but not for the intermediate association ship with `has_many through`.
- Composite foreign keys s.t. the second step `comments -> authors` could be modelled directly
