### ISSUE TITLE
Preload query does not allow to preload other associations on the same level

### ISSUE THREAD

**Issue by dkuku** [elixir-ecto/ecto#4273]
### Elixir version

 1.14.2 

### Database and Version

postgres 12.3

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.2

### Current behavior

I'm using preloads filtering with a query, this works ok even when I specify nested queries.
https://hexdocs.pm/ecto/Ecto.Query.html#preload/3
```elixir
    preload(
      query,
      pay: [
        location_pay: ^location_pay_preload_query
      ]
    )
```
But when I wan't to preload more items on the same level where I have the function or tuple with nested preloads I'm getting an error
```elixir
    preload(
      query,
      pay: [
        location_pay: [^location_pay_preload_query, :location]
      ]
    )
```
```
     ** (ArgumentError) invalid preload `#Ecto.Query<from l0 in Pay.Schemas.LocationPay, where: l0.location_id == ^0>` in 
     `[pay: [location_pay: [#Ecto.Query<from l0 in Pay.Schemas.LocationPay, where: l0.location_id == ^0>, :location]]]`. 
     preload expects an atom, a (nested) keyword or a (nested) list of atoms
```

### Expected behavior

I would expect that ecto will accept a list here and preload every association the same way as it's done with a list of atoms
this works: 
      `location_pay: [:city, :location]`
     `location_pay: ^location_preload_query`
     `location_pay: ^{location_preload_query, employee_location_pay}`
 but none of thee works
     `location_pay: [^location_preload_query]`
     `location_pay: [^{location_preload_query, employee_location_pay}, :employee]`

**Comment by josevalim** [comment]
Correct, you need to embed that inside the query: `location_preload_query |> preload(:employee)`. We could attempt to merge those but I think having two distinct sources for the data can be confusing.

**Comment by josevalim** [comment]
A PR is definitely welcome!

**Comment by josevalim** [comment]
Ah, the docs cover this:

```
When specifying a preload query, you can still preload the associations of
  those records. For instance, you could preload an author's published posts and
  the comments on those posts:

      posts_query = from p in Post, where: p.state == :published
      Repo.all from a in Author, preload: [posts: ^{posts_query, [:comments]}]
```

which makes sense, because the tuple indicates an addition rather than what would look like two sibling preloads: `[posts: [^posts_query, :comments]` :)

**Comment by josevalim** [comment]
Ah yes, pushed one line to the docs then, feel free to send more PRs.

**Comment by dkuku** [comment]
Yesterday when I was writing the doc queries I spotted where my mistake was:
instead of trying to do preload the employee in a list after the keyword
`location_pay: [^{location_preload_query, :employee_location_pay}, :employee]`
It should be inside the second tuple element:
`location_pay: ^{location_preload_query, [:employee, :employee_location_pay]}`
