### ISSUE TITLE
Ecto.Enum and Jason.encode as dumped values

### ISSUE THREAD

**Issue by maxsalven** [elixir-ecto/ecto#4283]
### Elixir version

1.15.2

### Database and Version

N/A

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

N/A

### Current behavior

```elixir
defmodule MyApp.User do
   use Ecto.Schema

  @derive {Jason.Encoder, except: [:__meta__]}
  schema "users" do
    field :status, Ecto.Enum, values: [a: "FOO"]
  end
end
```

```bash
iex(1)> Jason.encode!(%MyApp.User{status: :a})
"{\"id\":null,\"status\":\"a\"}"
```

### Expected behavior

I would have expected (liked?) status to be encoded as "FOO", rather than "a". Perhaps an option (similar to `embed_as: :dumped`) would be handy.

**Comment by greg-rychlewski** [comment]
Thanks for reaching out.

I believe you would have to make a custom Jason Encoder for this case. When you call `Jason.encode!(%MyApp.User{status: :a})` all Jason sees is a struct and it doesn't check that it's an Ecto Schema with Ecto.Enum fields. But if you had your own encoder you could add that logic.

Some Ecto functionality that might help:

https://hexdocs.pm/ecto/Ecto.Enum.html#mappings/2
https://hexdocs.pm/ecto/Ecto.Schema.html#module-reflection

**Comment by josevalim** [comment]
Correct, you need to write your own encoder and handle it, if that's what you desire. For embeddings there is a configuration option.
