### ISSUE TITLE
update_change/3 removes from changes unexpectedly when force_changes: true

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4292]
### Elixir version

1.14.5

### Database and Version

postgres

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

1. cast attr that does not change value, with force_changes true so that it is added to list of changes

```
changeset = cast(%MyApp.Schema{title: nil}, %{title: nil}, [:title], force_changes: true)
initial_changes = changeset.changes # => %{title: nil}
```

2. update change but return same value

```
changeset = update_change(changeset, :title, fn title -> title end)
changes_after_update = changeset.changes # => %{}
```

### Expected behavior

I expect `initial_changes` and `changes_after_update` to be identical, which is the behavior when the change is not forced:

```
     data = %{title: "test"}
      types = %{title: :string}
      changeset = cast({data, types}, %{title: "world"}, [:title])
      changeset.changes |> IO.inspect # => %{title: "world"} 
      changeset = update_change(changeset, :title, fn title -> title end)
      changeset.changes |> IO.inspect # => %{title: "world"} 
```

**Comment by tfwright** [comment]
Looking at the source, it looks like the root of the problem is with put_change: https://github.com/elixir-ecto/ecto/blob/f2a0def734dcee354acb223116550e9ae659fb0c/lib/ecto/changeset.ex#L1757

I'm not quite following why explicitly deleting the change is necessary there, I would expect a noop that just returns the original changes

**Comment by greg-rychlewski** [comment]
I believe outside of `force`, any change function will check to see if it's equal to the current value and consider it to be no change if they  are the same. 

If it's no-op then you could do this:

```elixir
cs = cs |> put_change(:key, new_value) |> update_change(:key, current_value)

# cs.changes = %{key: new_value}
``

There is a `force_change/3` but it only accepts a value and not a function. For your purpose is the function really important?

**Comment by tfwright** [comment]
Basically any workaround involves reimplementing the `changes` tracking myself, in part, by separate tracking the params and original data, instead of using force_changes for what would appear to be its main intended use: tracking attempted changes regardless of whether they affect the underlying data.

**Comment by greg-rychlewski** [comment]
There might be better ideas. But at the moment the only thing I can think is to have the other functions introduce a `:force` function. Otherwise the intention of calls to `update_change` and others is ambiguous. You might not want to remove the change but someone else might expect it to behave that way. Or someone might want to sometimes and not others.

**Comment by tfwright** [comment]
I note that the current docs for put_change have the following, which is consistent with the comment in the code:

> If the change has the same value as in the changeset data, it is not added to the list of changes.

But the implementation is _deleting_ the value from changes. 

I think this inconsistency is a bug that should be fixed even if it breaks current use taking advantage of the inconsistent behavior. Maybe it could also be done via a new option and deprecating the existing behavior so as to be backwards compatible.

I can't think why this inconsistency would actually be desirable such that we would want to preserve the behavior. But if the implementation can not be made consistent with force_changes and the docs because it is for some reason specifically desirable, then I think docs at least need to be corrected to specifically mention this exception.

**Comment by greg-rychlewski** [comment]
Just to be sure I understand your proposal. What would you expect to be returned from `cs.changes` in the two cases below if the data has `current_value` in it?

Case 1:

```elixir
cs = cs |> put_change(:key, new_value) |> update_change(:key, fn _ -> current_value end)
```

Case 2:

```elixir
cs = data |> cast(%{key: current_value}, [:key], force_changes: true) |> put_change(:key, new_value) |> update_change(:key, fn _ -> current_value end)
```

**Comment by tfwright** [comment]
Based on existing docs, I would expect to see `%{}` in the first and `%{key: new_value in the second}` since in the first case it matches existing value and "is not added" to existing changes of %{}, and the in the second case it still "is not added" to the existing changes of `%{key: new_value in the second}`

**Comment by greg-rychlewski** [comment]
Do you expect it to show up in the second case because it was forced? So do you mean to say that once a value is forced once, no matter how many times it changes to something else, bringing it back to the current value should respect the original force?

**Comment by tfwright** [comment]
I think I misread your example. Looking closer, neither case matches what I am trying to do.

**Comment by greg-rychlewski** [comment]
I am basically trying to understand when you suggest it should stay in changes and when it should stay. Because we would have to come up with consistent behaviour even outside the example your provided.

Do you mean to say that once a particular value is forced then any other function should not remove it as long as the value is staying the same. But if you switch to another value the force is forgotten? 

For example would you expect it to remain in changes here:

```elixir
cs = 
  data 
  |> cast(%{key: current_value}, [:key], force_changes: true)
  |> put_change(:key, current_value)
  |> update_change(:key, fn _ -> current_value end)
```

But not here 

```elixir
cs = 
  data 
  |> cast(%{key: current_value}, [:key], force_changes: true)
  |> put_change(:key, new_value)
  |> update_change(:key, fn _ -> current_value end)
```

**Comment by greg-rychlewski** [comment]
Or if you mean to say it should be silently ignored in both cases then I believe that will lead to other issues. So I don't think that is the optimal behaviour. I see your point about the docs suggesting this though and that should be improved.

**Comment by tfwright** [comment]
If I am right that the root issue is with put_change, I don't think update_change actually changes anything important.

The basic answer is that I don't think changes should _ever_ be _removed_ by `put_change` _or_ `update_change` because 1) they do not express that intention (principle of least surprise) and 2) it contradicts existing documentation (implying that even the authors would be surprised by this behavior!).

Whether they _change_ an existing value is irrelevant to this issue. These functions can add or change values based on whatever intent, without needing to actually _remove_ a preexisting change.

**Comment by tfwright** [comment]
> Or if you mean to say it should be silently ignored in both cases then I believe that will lead to other issues

Yes I may be in the dark on those but I think even if we fix the docs it would be a suboptimal API design due to the violation of the principle of least surprise. But that is up to the maintainers ultimately! I am happy to make the doc change.

**Comment by greg-rychlewski** [comment]
I think since this is a tricky issue let's see what the other maintainers say too. I understand now your POV and to me I can see how both ways would be surprising: silently ignored vs silently deleted.

So now I think it's about what is most consistent with the rest of Ecto and whether we need to add options to allow better control over behaviour.

**Comment by greg-rychlewski** [comment]
It also seems to me like it was not intended for `cast` to be mixed with `put_change/update_change` (`update` eventually calls `put`). This is at least what it looks like to me reading the code. 

`put_/update_` are always comparing to the current data and inserting changes directly because they are considered safe. Whereas `cast` is accumulating potentially unsafe changes and comparing to the latest one. 

So it might be this pattern of usage is not meant to be used and changing the functions not desired.

**Comment by josevalim** [comment]
> The basic answer is that I don't think changes should ever be removed by put_change or update_change

It doesn't matter what we think, doing so is a backwards incompatible and it could break existing code out there. The docs should reflect this.

Also, it is worth saying the principle of least surprise is not necessarily helpful: different people from different backgrounds building different applications will have different expectations. I would particularly be surprised if my changeset is sending to the database a value that it knows to perfectly match the data. If there is an anti-pattern here, I would say it is the use of force_change.

**Comment by tfwright** [comment]
First off, I accept the decision. But I am confused by the response enough to not be confident how to move forward with a docs change.

> It doesn't matter what we think, doing so is a backwards incompatible and it could break existing code out there. 

Should it be automatically understood that backwards incompatible changes are always off limits? Aren't there backwards compatible paths forward here that don't involve accepting this behavior?

> Also, it is worth saying the principle of least surprise is not necessarily helpful: different people from different backgrounds building different applications will have different expectations.

With all due respect, I'm not sure how "everyone has different expectations" is the more helpful way to frame it. I think it's understood that _perfectly_ meeting everyone's expectations is impossible. Thus it's _least_ surprise. Of course it's not definitive, but I'm not aware of what the reasoning for the existing behavior is (why it would be less surprising to anyone), which probably should be reflected in a docs change.

> If there is an anti-pattern here, I would say it is the use of force_change

I'm not sure what this means. Are you confirming what @greg-rychlewski has said: 

> It also seems to me like it was not intended for cast to be mixed with put_change/update_change (update eventually calls put).

If so I was definitely not aware of this and I think it should _also_ be in the docs. It makes some sense to me viz. put_change, but update_change seems like an entirely different matter.

If I can get some clarification on these points, I think I can propose a docs change, otherwise I'll take it the matter is closed.

**Comment by greg-rychlewski** [comment]
Just to be clear, I am not sure what the intended usage was meant to be. I am many years late to the party. I just started reading the code in more depth while we were talking and got some impressions.

**Comment by josevalim** [comment]
What I meant to say is that: you are expecting `force_change` to be the primary behavior, and that's your least surprising choice. I have the opposite perspective: if my changeset is sending changes to the database, that it knows match the current data, I would consider data surprising.

For me, `force_change` is always opt-in. It is the special case. The less common pattern. Filtering out up to date fields is the correct thing to always do, unless explicitly asked otherwise.

**Comment by josevalim** [comment]
> Should it be automatically understood that backwards incompatible changes are always off limits? 

Generally yes. We need to have strong motivations to justify breaking the last 5 years of code written on top of Ecto. I don't think we have a strong motivation here (and, from my point of view, not even an agreement this is a desired change).

**Comment by tfwright** [comment]
I think maybe there's a miscommunication because I don't think this is true of what I've proposed:

> you are expecting force_change to be the primary behavior,

In my case I am using cast with force_changes option, because I need to know if a user has requested a change regardless of whether it is already reflected in the source data or not. Then I need to modify this requested change (strip some non digit chars from a phone number) whether it has changed or not, without losing information about whether the user requested the change or not. I agree this is an edge case, but I also think it is only this case that will be affected by my proposed changed, not any "primary behavior"--although I could certainly be wrong about that!

**Comment by greg-rychlewski** [comment]
It will change the existing behaviour for anyone reaching the same situation as you. Which would be where the major issue is, even if we all agreed what you say is the best behaviour.

Since update_change can be applied to changes given by cast or put_change maybe it just makes sense to add a `force_changes` option that defaults to false. Then changes coming from cast can continue to be forced.

**Comment by josevalim** [comment]
I don't think there is a misunderstanding. You are saying that once a change is forced, it should be always forced (unless somehow said otherwise). That's what I mean by primary behaviour. Once enabled, it wins over other behaviours. While I say that once a change is a no-op, it should always be a no-op.

Another concern with your proposal is that, if that was the default, I wouldn't be surprised if someone later asks us to add an API to unforce changes... growing more the API surface.

**Comment by tfwright** [comment]
> You are saying that once a change is forced, it should be always forced (unless somehow said otherwise).

Communication is hard! I don't take that to be what I'm proposing since I think from the user's POV the "forcing" is one time thing, it takes a change that would not be added to changes, and adds it anyway. From that point forward it is just a change like any other. But I do understand that the current implementation "wants" (it is intentional, not accidental or an oversight) to treat forced changes differently, I'm just still not sure why.

|> It will change the existing behaviour for anyone reaching the same situation as you. Which would be where the major issue is, even if we all agreed what you say is the best behaviour.

Yes of course but the same could be said for any bug fix, even ones that result in outright app errors, because it's possible someone was relying on the unintentional behavior for whatever reason. So I think the major issues is just whether this should be considered a bug or an intended value add. Again, I do not understand _why_ it would be intentional, I guess it saves the hypothetical user taking advantage of current API the explicit use of delete_change? 

Without any further insight, my takeaway from this thread is that forcing changes is not recommended and won't play nicely with put_change and update_change, and the docs should be updated to reflect that.

**Comment by tfwright** [comment]
> Since update_change can be applied to changes given by cast or put_change maybe it just makes sense to add a force_changes option that defaults to false. Then changes coming from cast can continue to be forced.

This would be a great outcome from my POV

**Comment by greg-rychlewski** [comment]
If Jose agrees then it's ok with me. I believe it makes sense for the workflow cast -> update_change.

**Comment by josevalim** [comment]
> Again, I do not understand why it would be intentional

I have tried several times to explain the rationale and, given I failed all times, I will do one last attempt. If it still does not come across, I will drop this and maybe someone who can communicate clearer than me can help.

Perhaps the part that you are missing is that _any_ change can be dropped:

```
iex(1)> import Ecto.Changeset
Ecto.Changeset
iex(2)> data = %{title: "test"}
%{title: "test"}
iex(3)> types = %{title: :string}
%{title: :string}
iex(4)> change({data, types}) |> put_change(:title, "another") |> put_change(:title, "test")
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [],
  data: %{title: "test"},
  valid?: true
>
```

Given the above, let's re-read this:

> "forcing" is one time thing, it takes a change that would not be added to changes, and adds it anyway. From that point forward it is just a change like any other. But I do understand that the current implementation "wants" (it is intentional, not accidental or an oversight) to treat forced changes differently

Forced changes are not treated especially. Any change can be reverted at anytime, including forced changes. To achieve the behaviour you want, there are two possibilities:

* Forced changes, in particular, should not be reverted. This will effectively make them special

* No changes should be reverted, then it is a massive breaking change, which will make changesets more expensive and make it so partial updates to the data become much harder (if someone updates two different fields in a page, now all other fields clobber previous values too)
