### ISSUE TITLE
Some tests are failing with OTP 26

### ISSUE THREAD

**Issue by moogle19** [elixir-ecto/ecto#4296]
### Elixir version

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]  Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Database and Version

-

### Ecto Versions

master

### Database Adapter and Versions (postgrex, myxql, etc)

-

### Current behavior

9 tests are failing, e.g. this one: 
```elixir
  1) test values list source (Ecto.Query.Builder.JoinTest)
     test/ecto/query/builder/join_test.exs:24
     Assertion with == failed
     code:  assert {:values, [], [types_kw, length(values)]} == join.source
     left:  {:values, [], [[{:num, :integer}, {:text, :string}], 2]}
     right: {:values, [], [[{:text, :string}, {:num, :integer}], 2]}
     stacktrace:
       test/ecto/query/builder/join_test.exs:32: (test)
...
```
This is probably because of the updated sorting (or lack thereof) in OTP 26 when converting a `Map`/`MapSet` to a `List`.

### Expected behavior

All test should succeed 🙂
It would also be nice to add the latest OTP & Elixir version to the CI pipeline.

**Comment by josevalim** [comment]
Yup, it is about map field ordering. PRs are welcome. :)
