### ISSUE TITLE
Incompatible behavior of selecting many_to_many relation

### ISSUE THREAD

**Issue by v1d3rm3** [elixir-ecto/ecto#4311]
### Elixir version

1.14.4

### Database and Version

PostgresSQL 15

### Ecto Versions

3.10.3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.3

### Current behavior

When defining many to many relations in Ecto, the relation is using module name of relations in join relation. For example, if i've these definitions:

```elixir
defmodule EctoAssocRepro.UserSchema do
  alias EctoAssocRepro.OrganizationSchema
  alias EctoAssocRepro.UserOrganizationSchema
  use Ecto.Schema

  schema "users" do
    # many_to_many(:organizations, OrganizationSchema, join_through: UserOrganizationSchema, join_keys: [user_id: :id, organization_id: :id]) # IT WORKS
    many_to_many(:organizations, OrganizationSchema, join_through: UserOrganizationSchema)
    belongs_to :team, EctoAssocRepro.TeamSchema
  end
end

defmodule EctoAssocRepro.OrganizationSchema do
  alias EctoAssocRepro.UserSchema
  alias EctoAssocRepro.UserOrganizationSchema
  use Ecto.Schema

  schema "organizations" do
    many_to_many(:users, UserSchema, join_through: UserOrganizationSchema)
  end
end

defmodule EctoAssocRepro.UserOrganizationSchema do
  alias EctoAssocRepro.OrganizationSchema
  alias EctoAssocRepro.UserSchema
  use Ecto.Schema

  @primary_key false
  schema "users_organizations" do
    belongs_to(:user, UserSchema)
    belongs_to(:organization, OrganizationSchema)
    timestamps()
  end
end
```

and try to query relationship:

```bash
import Ecto.Query
EctoAssocRepro.Repo.all(from u in EctoAssocRepro.UserSchema, preload: [:organizations])
```

It gives me this error:

```bash 
** (Ecto.QueryError) deps/ecto/lib/ecto/query/planner.ex:963: field `user_schema_id` in `select` does not exist in schema EctoAssocRepro.UserOrganizationSchema in query:

from o0 in EctoAssocRepro.OrganizationSchema,
  join: u1 in EctoAssocRepro.UserOrganizationSchema,
  on: o0.id == u1.organization_schema_id,
  where: u1.user_schema_id in ^[3, 2, 1],
  order_by: [asc: type(u1.user_schema_id, :id)],
  select: {type(u1.user_schema_id, :id), o0}

    (elixir 1.14.4) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
```

But, it doesn't seem to be the default behavior of using module name. When we have a simple one to many relation, it uses the name of the schema, not the module name.

Repro repo: https://github.com/v1d3rm3/ecto_assoc_repro

### Expected behavior

I would expect that relationships in Ecto works the same way in different relationship kinds, and there's no need to use `join_keys` option.

**Comment by josevalim** [comment]
This is expected and behaves the same as has_many: https://github.com/elixir-ecto/ecto/blob/8fac7068ed28cbb63c9844bb4cfba09fb48b9a09/lib/ecto/schema.ex#L1325

Basically, all many associations infer from the schema name.

**Comment by v1d3rm3** [comment]
> This is expected and behaves the same as has_many:
> 
> https://github.com/elixir-ecto/ecto/blob/8fac7068ed28cbb63c9844bb4cfba09fb48b9a09/lib/ecto/schema.ex#L1325
> 
> Basically, all many associations infer from the schema name.

I may not have understood, or I may be wrong. **But the keys are not being inflected from schema names.**

As showed in my repro, it's using **module name**. For example, in the error shown, it generates 'user_schema_id', which is not the name of the schema ("users"). The same occurs with `organizations`.

**Comment by josevalim** [comment]
The schema name in this case is the *module* (the one who calls `schema "..." do`). If you would like to send a PR to make it clear, it is welcome. :) Your Ecto.Schemas never query your database.

**Comment by v1d3rm3** [comment]
Ok. Soon i'll try something. Thanks @josevalim

**Comment by wakeless** [comment]
@josevalim Dredging up an old issue here, but I was expecting the foreign keys to be inferred, not from the schema name, but from what is defined in the join table foreign_keys. Does not appear that way and this is definitely unexpected for me (I'm renaming a couple of foreign keys)
