### ISSUE TITLE
'has_one' association returns the first result when there are multiple found.

### ISSUE THREAD

**Issue by dkuku** [elixir-ecto/ecto#4324]
### Elixir version

1.15.7

### Database and Version

postgres 15

### Ecto Versions

3.11.0

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

I debugged a parent schema that links a table with `has_one` association. It turned out it setting the first found result not informing about that there are more (this may happen when you use soft deletion and handle the deleted field yourself)
Example:
```
schema "parent" do
  has_many :children, Child
  has_one :child, Child
end
```
When you insert 2 children linked with current parent ecto will return:
`[child_1, child_2] = parent.children`
`child_1 = parent.child`

### Expected behavior

Should the behaviour be that it raises similar as `Repo.one` does when it finds multiple results ??
Or at least log a warning - I imagine this may be a breaking change. But the current behavior is a bit unexpected for me.

**Comment by josevalim** [comment]
This is tricky. The query is done with LIMIT 1. We could remove the LIMIT 1 but, IIRC, that makes the query slower because you will always traverse the whole dataset instead of immediately stopping it. I would add a tiny note to the docs instead.
