### ISSUE TITLE
Using url in config to set database name overrides dynamic_repo config

### ISSUE THREAD

**Issue by benschenker** [elixir-ecto/ecto#4331]
### Elixir version

1.15.4

### Database and Version

PostgreSQL 16.0

### Ecto Versions

3.11.0

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.3

### Current behavior

When following https://underjord.io/ecto-multi-tenancy-dynamic-repos-part-2.html, setting the dynamic repo, swapping the DB name based on a customer id, I was able to get everything working in my dev environment which sets the repo default config params directly via username, password, hostname, database.
Specifically in a phoenix plug I would set RepoManager.set_customer(customer_id)
Then later on in the request handling I would use the Repo normally and it would query the correct database.

In prod, I set the repo default config via the :url option, when doing this it seems to always clobber the dynamic repo such that using Repo will always query the default database specified in the url, rather than the customer specific database.

I even updated the RepoManager code to parse the URL and extract the default values, removing the url from the config before calling start_link, to no avail

The only workaround I found was a line of code in my runtime.exs config like
```
  db_config =
    case System.get_env("DATABASE_URL") do
      url when is_binary(url) ->
        Ecto.Repo.Supervisor.parse_url(url)

      _ ->
        nil
    end

  if(db_config) do
    config :myapp, Myapp.Repo, db_config
  end
```

### Expected behavior

I'd expect that using url, to set the repo default config would end up working the same way as setting the individual values directly.

That being said, my workaround does work, just spent a whole day going a bit crazy :p

**Comment by greg-rychlewski** [comment]
Hi,

If you're able to create a reproducible example we can verify for sure. But based on your link it looks like the issue is here

```elixir
def get_customer_options(customer) do
  customer_database = get_database_name(customer)
  config = Application.get_env(:my_app, MyApp.Repo)

  config
  |> Keyword.put(:name, nil)
  |> Keyword.put(:database, customer_database)
end
```

Your original config will be something like this

```elixir
config :myapp, MyApp.Repo, url: "myurl"
```

What that function does is adds `name: nil` and `database: customer_database` to it. So it ends up like this

```elixir
config :myapp, MyApp.Repo, url: "myurl", name: nil, database: customer_database
```

Now it tries to start the repo. How this works is Ecto pops the url parameter, parses it, and then merges it into the rest:

```elixir
{url, config} =  Application.get_env(:myapp, MyApp.Repo, []) |> Keyword.pop(:url)
parsed_url_options = parse_url(url) # = [database: url_database, .... ]
config = Keyword.merge(config, parsed_url_options) # the url database overwrites the customer database here
```

Then you start the repo and connect to the url database. So the issue is that the code you are using needs to be modified to consider urls. One option is instead of merging in `:database` ,etc.. you can construct a new url from the customer database and merge that.

**Comment by benschenker** [comment]
Yes I noticed that behaviour (the URL superseding the database name) thanks for adding the documentation! When I had modified my code in get_customer_options to have something like
```
    config =
      case Keyword.fetch(config, :url) do
        {:ok, url} ->
          updated_config = Ecto.Repo.Supervisor.parse_url(url)

          config
          |> Keyword.merge(updated_config)
          |> Keyword.delete(:url)

        _ ->
          config
      end
```
it still did not work as expected.  My suspicion is that it is something about the default config having a URL and when I called
```
{:ok, repo_pid} = Repo.start_link(options)
Repo.put_dynamic_repo(repo_pid)
```
it wouldn't 'forget' the default url

Either way, my workaround does work for me, and I suspect your idea of generating a new url with the custom DB name would also work.  thanks for taking a look

**Comment by benschenker** [comment]
@greg-rychlewski 
I setup a minimal reproducible example at https://github.com/benschenker/EctoUrlBug

this is definitely no urgency on this one as my workaround described above has been working fine, but I would expect the code to work (especially with https://github.com/benschenker/EctoUrlBug/blob/main/lib/ecto_url_bug/repo_manager.ex#L48)

I think somehow the initial setup of the repo (using the url from the config) gets persisted somewhere such that when we set up the dynamic repo config (even though we explicitly delete the url keyword) the initial config url keeps clobbering the dynamic repo config (sans url)

You are probably right that updating the url (instead of extracting the params individually and deleting) would work too

**Comment by greg-rychlewski** [comment]
You are correct, the options you pass into start_link are merged into the application configuration. It should do what you want if you put `url: nil` instead of deleting the url key.

**Comment by benschenker** [comment]
yes that works very well! good catch :) thanks for the quick response. I'll update my main branch with the fix for anyone in the future and update the above link to the specific commit where it wasn't passing

**Comment by greg-rychlewski** [comment]
Thanks! Glad it works. I haven't checked the start_link docs but if you feel they could be improved to make this situation clearer a PR would be welcome
