### ISSUE TITLE
`FunctionClauseError` in `Ecto.RepoPreloader`

### ISSUE THREAD

**Issue by whatyouhide** [elixir-ecto/ecto#4344]
### Elixir version

1.16.0

### Database and Version

PostgreSQL 13.3

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

Postgrex `0.17.4`

### Current behavior

I've recently seen this error:

```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Repo.Preloader.maybe_pmap/3
```

This is the stacktrace:

```
lib/enum.ex in anonymous fn/3 in Enum.map/2 at line 1708
lib/enum.ex in anonymous fn/3 in Enum.map/2 at line 4399
lib/task/supervised.ex in Task.Supervised.stream_deliver/7 at line 386
lib/enum.ex in Enum.map/2 at line 4399
```

I’m not sure if this is an Ecto issue or an application issue, but seems like an Ecto issue from my investigation. I’m still trying to debug, but figured I're report this in case I’m missing something obvious 🙃 

### Expected behavior

No `FunctionClauseError` if this is indeed happening in Ecto.

**Comment by josevalim** [comment]
I think Ecto is hiding the actual bug here. I think you are calling it from a process that is trapping exits, hiding the underlying pmap failure. We will improve it.

**Comment by whatyouhide** [comment]
Fantastique, this will definitely help debug it. Thanks @josevalim! 💟
