### ISSUE TITLE
Allow string fields for schemaless changesets?

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/ecto#4345]
### Elixir version

all

### Database and Version

all

### Ecto Versions

all

### Database Adapter and Versions (postgrex, myxql, etc)

all

### Current behavior

Currently when casting fields into a changeset, we expect the list of fields to be atoms. The subsequent validation functions also expect the changes to be cast to atoms.

This makes sense when we are dealing with schemas because all the fields are defined upfront, however there seems to be a legitimate use case for string fields when dealing with user-defined "schemas". For example, see here: https://elixirforum.com/t/casting-into-maps-with-string-keys-in-ecto/60801.

### Expected behavior

How does the team feel about exploring the idea of allowing string keys when dealing with schemaless changesets? This could be useful when your schemaless changeset represents all of your data or when wanting to validate a map field within an actual schema.

I would have to go into the weeds to be sure, but I believe this can be done safely by adding a new field to the changeset like `string_keys?` that is set the first time the changeset is made. Then we can protect against users putting string fields into changesets that will eventually make their way to the repo functions.

**Comment by wojtekmach** [comment]
-1 from me, I believe the atom vs string keys is pretty important implementation and practical usage wise. While schemas, changesets, and validations are all field name based, fwiw users can use casting standalone, via Ecto.Type.cast and friends standalone.

**Comment by josevalim** [comment]
I also think implementing is going to have a lot of implications to the API and its usage. For example, `changeset.errors` will no longer be a keyword list, and we will have to change all usages accordingly. We will also have to change things like filters, to allow string keys, and that will propagate changes to all adapters. And still queries do not really allow binary keys. And even if we say "let's not do that", it is just a matter of time until someone wants to push it forward.

So supporting this will be a very very large change to the codebase and a bit against Ecto's etho of being tied to a particular schema. I think schemaless changesets with atom keys is as far as we can push this. :)
