### ISSUE TITLE
Ecto.put_query_prefix/2 does not allow atoms, inconsistent with prefix option

### ISSUE THREAD

**Issue by tfwright** [elixir-ecto/ecto#4356]
### Elixir version

1.14

### Database and Version

PostgreSQL 13

### Ecto Versions

3

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17

### Current behavior

```
s = Repo.get(Schema, 1, prefix: :prefix)

Schema |> Ecto.put_query_prefix(Ecto.get_meta(s, :prefix)) |> Repo.all()
```

`no function clause matching in Ecto.Query.put_query_prefix/2 `

Function guards on binary: https://github.com/elixir-ecto/ecto/blob/270fab062dd96d11eef2b5f7827e18fffa47a014/lib/ecto/query.ex#L908-L914

### Expected behavior

Behavior matches prefix option

**Comment by josevalim** [comment]
I don't think prefix is allowed as an atom. Repo.get should be the one checking?

**Comment by tfwright** [comment]
Not sure what I'm missing then

```
Accounts.User |> limit(1) |> Repo.one(prefix: :demo) |> Map.fetch!(:id) |> then(fn id -> Repo.get!(Accounts.User, id, prefix: :demo) end) |> is_nil()
```

**Comment by tfwright** [comment]
Although docs consistently use strings in examples, I am not sure where to look that it is actually enforced

**Comment by tfwright** [comment]
Also tested on 3.11.1 and I see the same result. `Repo.get` allows an atom prefix...
