### ISSUE TITLE
union with struct/map will result in setting values in incorrect keys

### ISSUE THREAD

**Issue by kafaichoi** [elixir-ecto/ecto#4365]
### Elixir version

1.16.0

### Database and Version

PostgresSQL 15

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

I created a mix project https://github.com/kafaichoi/ecto_union_bug to replicate the bug.

```
  defmodule Post do
    use Ecto.Schema
    import Ecto.Changeset

    schema "posts" do
      field(:title, :string)
      field(:subtitle, :string)
    end
  end

  test "bug" do
    post1 = %Post{title: "post1", subtitle: "post1_subtitle"}
    post2 = %Post{subtitle: "post2_subtitle", title: "post2"}
    Repo.insert(post1)
    Repo.insert(post2)

    union_query1 =
      from(p in Post,
        where: p.title == "post1",
        select: %{id: p.id, title: p.title, subtitle: p.subtitle}
      )

    union_query2 =
      from(p in Post,
        where: p.title == "post2",
        select: %{id: p.id, subtitle: p.subtitle, title: p.title}
      )

    post1 =
      union_query2
      |> union(^union_query1)
      |> Repo.all()
      |> dbg()
      |> Enum.find(&(&1.title == "post1"))

    refute is_nil(post1)
  end
```

You can run it by 
```
MIX_ENV=test mix ecto.create && mix ecto.migrate && mix test
```

If you run the test case. you will see the post1 is not being found because subtitle value is being used as title value.(the dbg result should explain this).

### Expected behavior

I expect that the post1 will be found with `"post1"` as `:title`

**Comment by kafaichoi** [comment]
and actual sql query generated is 
`SELECT p0."id", p0."subtitle", p0."title" FROM "posts" AS p0 WHERE (p0."title" = 'post2') UNION (SELECT p0."id", p0."title", p0."subtitle" FROM "posts" AS p0 WHERE (p0."title" = 'post1')) []`

So I believe the bug is in here where the ordering of columns in select query is not the same

**Comment by kafaichoi** [comment]
looking at the source code, it looks like it's because the sql query generated by `combination` didn't consider the ordering of the fields in query1. https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/postgres/connection.ex#L787

**Comment by josevalim** [comment]
We could try to change this for maps but the general rule is that you must have the exact same matching field order in combinations, even if using maps. So alternatively we make this very clear in docs. :)

**Comment by greg-rychlewski** [comment]
I think it is hard to fix the order because the map keys don't have to correspond to the values in the first part of the union. And the values can be fragments, expressions, etc. 

For example this can be fixed by swapping the title/subtitle keys in either query but then it seems like we are getting into SQL parsing territory:

```elixir
union_query1 =
      from(p in Post,
        where: p.title == "post1",
        select: %{id: p.id, title: fragment("coalesce(?, 'n/a')", p.subtitle), subtitle: p.title}
      )

union_query2 =
      from(p in Post,
        where: p.title == "post2",
        select: %{id: p.id, title: p.title, subtitle: p.subtitle}
      )
```

**Comment by kafaichoi** [comment]
Thank you for both of your reply. 

Yea it's true that that's the requirement for sql union and it's indeed not easy to fix this.
But I think if ecto provide abstraction to select it into map, it will be so awesome that the library can handle it. I can give it a try(but probably take some time) but just want to make sure that fixing this will also be sth that we want?

**Comment by greg-rychlewski** [comment]
Let's see what Jose says but I don't see how it can be fixed without parsing SQL due to fragments. And parsing SQL isn't something Ecto would be able to do. That's complex business that the database devs spend years perfecting =).

And if we go by map keys alone then we can make correct queries incorrect.

**Comment by josevalim** [comment]
We may be able to look at the parent select and the combination select, but that will be very dependent on the order we process stuff and not even then accurate. So I’d go with docs.
