### ISSUE TITLE
Discrepancies between schema with Repo and embedded schema with Ecto.embedded_load on invalid fields.

### ISSUE THREAD

**Issue by dkuku** [elixir-ecto/ecto#4383]
### Elixir version

1.16.1

### Database and Version

Postgres 12

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

We use EctoPhoneNumber to store fields in the database. This validates the data, but it can get invalidated when obfuscating.
With ecto schema backed by db when I have a field:
`field(:contact_number, EctoPhoneNumber)` it loads the invalid data still fine.
```
Repo.get(Customer, 2929) |> Map.get(:contact_number)
#EctoPhoneNumber<14111111111>
```
Even when it's not valid
```
CustomersCore.LegacyRepo.all("customers" |> where([c], c.id == 2929) |> select([c], c.contact_number)) |> hd()
"14111111111"
"customers" |> where([c], c.id == 2929) |> select([c], c.contact_number) |> CustomersCore.LegacyRepo.all() |> hd() |> EctoPhoneNumber.cast()
:error
```
My problem is that I created an embedded schema for use with elastic search that has the same data and field definition and it fails when loading with Ecto.embedded_load.
```
Ecto.embedded_load(Customer, customer["_source"], :json)
** (ArgumentError) cannot load `"14111111111"` as type EctoPhoneNumber for field `contact_number` in schema CustomersCore.Schemas.Legacy.Customer
    (ecto 3.11.1) lib/ecto/schema/loader.ex:76: anonymous fn/5 in Ecto.Schema.Loader.unsafe_load/4
    (elixir 1.16.1) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:24: (file)
    ```

### Expected behavior

I would expect that schema and embedded schema behave in the same way.

**Comment by dkuku** [comment]
It looks like Repo uses `load` function but embedded_load uses `cast`

**Comment by josevalim** [comment]
Correct. You must file a bug in ExPhoneNumber, since it should be able to handle the value it loads in cast. I will improve the docs here.

**Comment by dkuku** [comment]
Ok, thanks for the explanation.
