### ISSUE TITLE
Cannot use `fragment` next to other stuff in on_conflict update query

### ISSUE THREAD

**Issue by saveman71** [elixir-ecto/ecto#4385]
### Elixir version

1.15.6

### Database and Version

13.4

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

0.17.4

### Current behavior

Currently I have to do the following

```elixir
changeset = Upload.submit_changeset(params)

# Split the query building in two update/2 calls to avoid issue with Ecto
on_conflict_query =
  from(upload in Upload)
  |> update([upload], set: ^Keyword.new(changeset.changes))
  |> update([upload], set: [version: fragment("COALESCE(?, 0) + 1", upload.version)])

Repo.insert(
  changeset,
  on_conflict: on_conflict_query,
  conflict_target: [:uploader_id],
  returning: true
)
```

This perfectly works but I had to figure out a way of escaping compilation errors such as `unexpected expression after keyword list. Keyword lists must always come last in lists and maps.` or `is not a valid query expression.`

### Expected behavior

You should be able to compose at will the fragment around other stuff like this:

*with `|`*
```elixir
on_conflict_query =
  from(tu in Upload,
    update: [set: [version: fragment("COALESCE(?, 0) + 1", tu.version) | ^Keyword.new(changeset.changes)]]
  )
```

(`is not a valid query expression` error)

*or with `++`*
```elixir
on_conflict_query =
  from(tu in Upload,
    update: [set: [version: fragment("COALESCE(?, 0) + 1", tu.version)] ++ ^Keyword.new(changeset.changes)]
  )
```

(`malformed update` error)

In a perfect world, I wouldn't have to mess around with the changeset and there would be an API that would automatically compose existing fields (potentially excepting some) with new fields, `fragment` or not directly without a query

**Comment by josevalim** [comment]
While we could make it work, I am not sure we should. Ecto Queries are a subset of Elixir, it is understandable if Ecto queries do not implement the semantics of `++` or `|` inside them. For example, what about this?

```
update: [set: [version: fragment("COALESCE(?, 0) + 1", tu.version)] |> Kernel.++(^Keyword.new(changeset.changes))]
```

Do you see what I mean? So while you are inside the query, you need to abide to its rules. Relaxing the rules to support certain expressions will be a cat-mouse game until we have to reimplement all Elixir semantics.

**Comment by saveman71** [comment]
I see what you mean! It's easy to get caught because it "feels" like Elixir, gets syntax colored like Elixir, but I didn't find any "gotcha" or "common pitfalls" section in the docs (maybe I overlooked it) about that. Using query composition works for me though, but I feel like it should be officially recommended in these cases then?

The version that ended up working was still the result of 10-15mn of fiddling around and google searches for examples of correct syntax. That's also why I opened the issue, not even sure if there was a problem to begin with. Feel free to close, that answer satisfies me as long as I can justify with a link to that issue in my code ;)

**Comment by josevalim** [comment]
> Using query composition works for me though, but I feel like it should be officially recommended in these cases then?

Would you like to send a PR adding more examples to the `Ecto.Query.update`, showing it can be invoked multiple times to merge results?

**Comment by saveman71** [comment]
https://github.com/elixir-ecto/ecto/pull/4386

lmk if that's enough / do no hestitate to tweak wording / location in the docs
