### ISSUE TITLE
Constraints (like foreign_key_constraint) are removed from changeset when put_assoc/cast_assoc is used

### ISSUE THREAD

**Issue by ChristopheBelpaire** [elixir-ecto/ecto#4387]
### Elixir version

1.16.1

### Database and Version

Bug is in changeset, not related to a specific database

### Ecto Versions

3.11

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

Hello!
With a relation has_many, if there is a constraint defined in the child schema , put_assoc, cast_assoc is will not copy the constraint from the changeset.
Here is an example :
```
Mix.install([:ecto])

defmodule PurchaseOrder do
    import Ecto.Changeset

    use Ecto.Schema
    schema "purchase_orders" do
        has_many :fabrication_orders, FabricationOrder, on_replace: :delete
        field :reference, :string

    end
    
    def changeset(changeset, attrs) do
      changeset
      |> cast(attrs, [:reference])
      |> cast_assoc :fabrication_orders
    end
end

defmodule FabricationOrder do
    import Ecto.Changeset

    use Ecto.Schema
    schema "fabrication_orders" do
        belongs_to :purchase_order, PurchaseOrder, on_replace: :delete
        field :product, :string
        field :quantity, :integer
    end
    
    def changeset(changeset, attrs) do
        changeset
        |> cast(attrs, [:product, :quantity])
        |> foreign_key_constraint( :purchase_order_id)
    end
end

fabrication_order_changeset = FabricationOrder.changeset(%FabricationOrder{}, %{product: "A product", quantity: 10})

IO.inspect(fabrication_order_changeset.constraints, label: "Fabrication order constraints")

purchase_order_changeset = PurchaseOrder.changeset(%PurchaseOrder{}, %{reference: "123"})

purchase_order_changeset = Ecto.Changeset.put_assoc(purchase_order_changeset, :fabrication_orders, [%{product: "A product", quantity: 10}])

hd(purchase_order_changeset.changes.fabrication_orders) 
|> Map.get(:constraints)
|> IO.inspect(label: "Purchase order constraints (removed)")
```

### Expected behavior

In the last IO inspect, the constraints is not there anymore.
It means is it impossible to catch a key constraint if put_assoc/cast_assoc is used.

Please let me know if you need more information of if my scenario is not clear enough.

Kind regards,

**Comment by wojtekmach** [comment]
While `cast_assoc` by default calls the associations's `changeset/2` function, `put_assoc` does _not_. Quote from the docs:

> Opposite to cast_assoc and embed_assoc, the given map (or struct) is not validated in any way and will be inserted as is.

If I change in your snippet:

```diff
- purchase_order_changeset = Ecto.Changeset.put_assoc(purchase_order_changeset, :fabrication_orders, [%{product: "A product", quantity: 10}])
+ purchase_order_changeset = Ecto.Changeset.cast_assoc(purchase_order_changeset, :fabrication_orders, [%{product: "A product", quantity: 10}])
```

then I'm seeing the behaviour you're expecting.

I believe this works as expected so I'm gonna close this but as always please feel free to continue the discussion.
