### ISSUE TITLE
`Repo.config/0` do not support dynamic repos

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#4390]
### Elixir version

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]  Elixir 1.16.1 (compiled with Erlang/OTP 26)

### Database and Version

PostgreSQL 14.11

### Ecto Versions

3.11.0

### Database Adapter and Versions (postgrex, myxql, etc)

0.17.3

### Current behavior

`Repo.config/0` returns configuration set via application environment, it do not support dynamic configuration.

```elixir
{:ok, pid} = Repo.start_link(foo: :bar)

Repo.put_dynamic_repo(pid)

Repo.config()[:foo] == nil
```

### Expected behavior

Configuration options set via `Repo.start_link/1` should be visible in `Repo.config/0`:

```elixir
{:ok, pid} = Repo.start_link(foo: :bar)

Repo.put_dynamic_repo(pid)

Repo.config()[:foo] == :bar
```

**Comment by josevalim** [comment]
I need to check but I believe Repo.config is always the static config. So we would need to update the docs.

**Comment by hauleth** [comment]
Technically that is documented, however I find that counterintuitive, as we often may want to configure some stuff extra with either `init/2` or by passing extra options to `start_link/1`. And these options may be quite important, so just dismissing them is IMHO slightly weird approach.

**Comment by josevalim** [comment]
@hauleth the config is mostly used for external invocation, such as migration, where you don't have a running repo. If you want to runtime config, that's a separate feature request. For the use cases this feature was written for, it makes sense.

**Comment by Schultzer** [comment]
This has hit me as well! It would be a significant improvement;

**Comment by josevalim** [comment]
If someone wants to explore this via a new API, call it `process_config` or similar, we would be happy to review PRs.

**Comment by hauleth** [comment]
I have found yet another problem with this approach. While `Ecto.Migrator.up/4` accepts `:dynamic_repo` when running migrations, it do not allow changing `:migration_source`. That mean that it *greatly* reduce the capabilities of this system. That is quite painful there.

Our case is that user defines PostgreSQL connection URL and sets schema/prefix to be used in queries. However it allows using multiple sources in that schema. That mean, that we can have multiple migrations in parallel (we ensure that the tables and migration tables will have unique names). But with current implementation of `Ecto.Migrator` it is not possible.

**Comment by Schultzer** [comment]
So, even with a new feature. The migrator would still be an issue. If so, it would be good to document what it would take to have a more dynamic repo since  I’ve already proposed giving the adapter more control. To me, it sounds like there is an even better argument for a revised migrator and migration in general.

**Comment by hauleth** [comment]
For better migrations (unfortunately only with Postgres) I was looking into integrating [pgroll](https://github.com/xataio/pgroll) which has quite interesting approach to rolling out migrations.
