### ISSUE TITLE
IO.inspect doesn't log Changeset.Params

### ISSUE THREAD

**Issue by ponychicken** [elixir-ecto/ecto#4395]
### Elixir version

1.16

### Database and Version

any

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

any

### Current behavior

```
def changeset(event, attrs) do
    event
    |> cast(attrs, [:type, :received_at, :body, :title, :from, :metadata])
    |> IO.inspect(label: "Changeset after cast")
```

Returns:

```
Changeset after cast: #Ecto.Changeset<
  action: nil,
  changes: %{title: "zzzzzzzzzz"},
  errors: [],
  data: #Events.Eventlog.Event<>,
  valid?: true
>
```

The params are missing. As a beginner first I thought functions like cast_assoc work like magic, because where do they get the data from?? 
Turns out all the data is in params, but its simply not logged. If I do `IO.inspect(changeset.params)` I get them fine.

### Expected behavior

Log the **complete** changeset struct.

I don't know if this is a bug in Ecto or in Elixir. That is for the more wise to decide.

**Comment by josevalim** [comment]
This is by design. `params` can have any shape and they can have sensitive data, so if we log them by default in changesets, there is a chance we can leak passwords and other fields. If you want to inspect params, you should be the one that plucks it out.

If you think we can improve the docs here, a pull request is definitely welcome. :)

**Comment by ponychicken** [comment]
Can you point me to the place where this happens?
I would suggest to change the output to something like this:

```
$  IO.inspect(changeset)
Changeset after cast: #Ecto.Changeset<
  action: nil,
  changes: %{title: "zzzzzzzzzz"},
  errors: [],
  data: #Events.Eventlog.Event<>,
  valid?: true,
  params: "Params redacted for security reasons"
>
```

**Comment by josevalim** [comment]
I think what we should do is to add a `...` at the end, to make it clear there are other fields. That's because even if we show params: ..., they are other fields omitted.

**Comment by ponychicken** [comment]
I have send you two PRs. 
The first one lists all redacted fields, similar how it is done with the filter() function.
It ends up being a bit verbose, because there are many fields not printed.
The second one just adds a note at the end. I thought it would be good to output more than ..., which can be easily missed. 
Choose whichever fits more the style ;)
