### ISSUE TITLE
`Repo.load/2` doesn't cast virtual fields into a Schema struct

### ISSUE THREAD

**Issue by nicolasdabreo** [elixir-ecto/ecto#4398]
### Elixir version

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Database and Version

PostgreSQL 14

### Ecto Versions

ecto 3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.4

### Current behavior

1. I perform a complex manual query to retrieve some data, this data includes additional fields relevant to my Schema in this data context.

```
query = `BIG SCARY SQL`
%{columns: columns, rows: rows} = Repo.query!(query)
```

2. I iterate over the rows to load the data into my Struct, including the additional fields as virtual fields.

```
    for row <- rows do
      casted_data = Repo.load(MyStruct, {columns, row})
      ## IO.inspect(casted_data)
      ## %MyStruct{persisted_field: "foo", virtual_field: nil}
    end
```

### Expected behavior

As the Schema as just one of the representations of my data in this context and not the actual database table itself I should be able to load not just the fields present in the database to my struct using `Repo.load/2`.

**Comment by josevalim** [comment]
Thanks for the report.

Load is exclusively about loading database data and virtual fields are never sent/read from the database, so it is understandable that load won't set virtual fields, and I am not sure we should make an exception here. Can't you set the field after calling load?

**Comment by nicolasdabreo** [comment]
It requires doing a number of additional enumerations over the database, converting to atom keys, zipping the cols/rows up, getting the new data and loading it back into the struct.

This is basically what we're already doing and just not working with the struct at all. I saw this as a refactoring opp to simplify, bring data safety with the struct and reduce enumerations.

**Comment by josevalim** [comment]
We would be glad to consider a PR if it is a small change. But if it requires semantic or large changes, then it will likely be refused. :) Give it a try if you want to!

**Comment by nicolasdabreo** [comment]
Thanks for confirming! I'll take a look this weekend :grin:
