### ISSUE TITLE
Unexpected behavior of cast_embed

### ISSUE THREAD

**Issue by diegonogueira** [elixir-ecto/ecto#4400]
### Elixir version

1.16.2

### Database and Version

15.0

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

Hello.

The example code below is experiencing unexpected behavior for `cast_embed`.

When calling `cast_embed` for the second time without validation, previous errors are being reset, which does not occur in the main changeset (User), where errors are preserved even without validation.

```elixir
defmodule Address do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field(:street, :string)
    field(:number, :string)
  end

  def changeset_without_validations(changeset, params \\ %{}) do
    cast(changeset, params, [:street, :number])
  end

  def changeset_with_validations(changeset, params \\ %{}) do
    changeset
    |> cast(params, [:street, :number])
    |> validate_required([:street, :number])
  end
end

defmodule User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string

    embeds_one(:address, Address)
  end

  def start do
    params = %{"name" => "", "address" => %{}}

    {:error, changeset} =
      %User{}
      |> cast(params, [:name])
      |> cast_embed(:address, with: &Address.changeset_with_validations/2)
      |> validate_required([:name])
      |> apply_action(:insert)

    IO.inspect "This changeset has all the errors (User errors and Address errors)"
    IO.inspect changeset

    IO.inspect "---------------------------------------"

    params = %{
      "name" => "John Doe",
      "address" => %{"street" => "Street One", "number" => ""}
    }

    changeset =
      changeset
      |> cast(params, [:name])
      |> cast_embed(:address, with: &Address.changeset_without_validations/2)

    IO.inspect "This changeset has only users errors. Where is the previous address errors?"
    IO.inspect changeset

    :ok
  end
end
```

![cast_embed](https://github.com/elixir-ecto/ecto/assets/68256/9ce5e01c-b8ff-4e49-8e69-dcb234794823)

### Expected behavior

In the same way as in the main changeset (User), errors are being preserved, even after going through the changeset without validation.

It seems that the child changeset (Address) is not being passed forward, but rather, always a zero initialization of the struct.

**Comment by josevalim** [comment]
Yes, `cast_embed` will always start from scratch, which you can notice by the fact that `changeset_without_validations` and `changeset_with_validations` are always called with a struct.

Perhaps you could pass the existing changeset in case you want to propagate `cast_embed(:address, with: &Address.changeset_without_validations(&1, &2, changeset))` but `cast_embed` does assume the new params are a new entry.
