### ISSUE TITLE
Repo.insert(changeset, on_conflict: {:replace, []}) fails.

### ISSUE THREAD

**Issue by dkuku** [elixir-ecto/ecto#4402]
### Elixir version

1.16.2

### Database and Version

postgres 12.3

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.2

### Current behavior

I have logic that conditionally adds changes to a changeset. This changeset is then piped Repo.insert(changeset).
So far all is ok but I started refactoring this to have a `on_conflict: {:replace, [fields]}`. 

- Here I had the first problem - if I specify in on conflict a field that is not present in the changeset then it gets reset because the generated query has `ON CONFLICT ("user_id") DO UPDATE SET "languages" = EXCLUDED."languages"` where EXCLUDED.languages is null - this causes to reset the field.
- I wanted to work around this and conditionally add the fields to replace but one of the tests was setting nothing so I ended up with `Repo.insert(changeset, on_conflict: {:replace, []})` 
This generated an invalid query: `ON CONFLICT ("user_id") DO UPDATE SET  RETURNING "id"`

### Expected behavior

I'm not sure if the first one is easy to solve. We may remove the conflict targets that are not included in the changeset.
The second one should generate a correct query.

**Comment by dkuku** [comment]
I don't want to force it. When it's not included in the changeset then it should not update the existing value, but having config_target set to a field that is not provided in the changeset it resets the existing value.
This is imo a different behaviour than if it were compared to just Repo.update - update would not touch the value in this case.

**Comment by greg-rychlewski** [comment]
Is the issue that you are doing an insert where the data struct has `nil` for the value? So something like this:

```elixir
data = %Data{maybe_missing: nil}
changes = %{not_missing: 1})
```

And then the record already in the database has a non nil value for `maybe_missing`?

If so I think this is consistent/expected with how inserts work. The data and the changes are effectively merged together before the SQL is generated. So they are "equal" once we start generating the actual SQL, if that makes sense. Changes are only special during updates.

If we ignored fields in the data when using `:replace` then that would change the behaviour of existing code that is hoping for it to be replaced. And I don't believe it is inline with the docs or other behaviour to only consider things in changes. We also replace autogenerated fields not specified at all by the user.

Maybe we can convert `{:replace, []}` to a no-op so it generates correct SQL.

**Comment by dkuku** [comment]
Ok, the first one may not be a bug when I think about it. 
I was inserting an empty struct that has all values set to nil by default and it reset the values on original. I was assuming it will only replace the ones that are changed by the changeset: 
```elixir
    test "ecto" do
      customer =
        Factory.insert(:customer,
          last_name: "Kukula",
          first_name: "Daniel"
        )

      %Customer{}
      |> Ecto.Changeset.change(Map.take(customer, [:id, :first_name]))
      |> Repo.insert!(
        on_conflict: {:replace, [:last_name, :first_name]},
        conflict_target: :id,
        returning: true
      )

      [updated] = Repo.all(Customer)

      assert updated.last_name == "Kukula"
      # this fails
      # Assertion with == failed
      # code:  assert updated.last_name == "Kukula"
      # left:  nil
      # right: "Kukula"
    end
```
With the second one I think we should just skip the whole on conflict in the generated sql.

**Comment by dkuku** [comment]
I ended up with getting the changes from the changeset and using
```
changes = Keyword.new(changeset.changes)
on_conflict = if changes == [], do: :nothing, else: [set: changes]
```
   and later
 `on_conflict: on_conflict`

**Comment by josevalim** [comment]
Yeah, I think raising on empty replace can be good to catch bugs, so I  think we are ok with no changes for now. Thanks!
