### ISSUE TITLE
put_assoc() Deletes many_to_many Relationships on Update (for already-linked elements)

### ISSUE THREAD

**Issue by WammKD** [elixir-ecto/ecto#4405]
### Elixir version

 1.14.0

### Database and Version

MariaDB 10.10.2

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

myxql 0.6.4

### Current behavior

I've, more or less, got something along the lines of

``` elixir
defmodule ItemA do
  use    Ecto.Schema;
  import Ecto.Changeset;

  schema "item_a" do
    …

    many_to_many(:item_bs, ItemB, join_through: "item_a_to_item_b");

    timestamps();
  end

  def changeset(%ItemA{} = a, attrs) do
    a |> cast(attrs, […])    # in my code, these are actual struct.s from the database
      |> put_assoc(:item_bs, [%ItemB{}, %ItemB{}, %ItemB{}, %ItemB{}])
  end
end
```

I'm receiving data from a third party and, so, the identifying attributes of that data doesn't map to the primary keys and, so, has to be looked up, regardless of anything else; so `put_assoc()` was chosen to handle this since I've already got the struct.s from having to look them up in the database.

I'm finding that running an update on an `ItemA` with the same `item_bs` as is already associated to the struct. (in the database) ends up deletes all relevant entries from the mapping table. So, even though I've provided a series of `ItemB` struct.s to `put_assoc()`, all said struct.s end up getting removed from the mapping table, by the the end of the update. A subsequent, identical update re`INSERT`s the relevant IDs into the mapping table; running the same update removes them, again. If some `ItemB`s are associated to an `ItemA` and I run `put_assoc()` with the struct.s of those `ItemB`s plus a new one to add, all the existing `ItemB`s given to `put_assoc()` are removed from the mapping table while the new one is added to the mapping table. It seems to just swap existing rows/entries with being removed and vice versa.

### Expected behavior

Even if deleting the rows from the mapping table before re`INSERT`ing them, I'd expect that all of the struct.s which I provide to `put_assoc()` to end up in the mapping table, by the end of my call to `update!()`.

**Comment by josevalim** [comment]
Can you provide a small example that reproduces the issue? put_assoc works by matching IDs, so as long as the IDs match, data won’t be deleted.

**Comment by WammKD** [comment]
Ack; good Void…

I finally figured it out; stupid user error.

Due to design constraints outside my control, I had a joint sort of table that linked to two other tables. For ease of reference, I had two schemas to represent each linked table but was using each to update each type; I was focused on trying to update one but, since both schemas represent the same table, calling `put_assoc()` on the second schema – of course – is interpreted as the database items having been removed.

Sorry about this; no bug.
