### ISSUE TITLE
docs specify that maps with atoms keys must be passed to `insert_all` but string keyed maps work too

### ISSUE THREAD

**Issue by simonmcconnell** [elixir-ecto/ecto#4411]
### Elixir version

1.16.2

### Database and Version

n/a

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

n/a

### Current behavior

The docs and typespecs tell you that you must supply atom keyed maps to `Repo.insert_all` but you can also provide string keyed maps.

This is fine: `Repo.insert_all("analog_input", [%{"t" => 0, "value" => 1}])`

### Expected behavior

docs and typespecs are correct.

**Comment by josevalim** [comment]
Please send a PR!
