### ISSUE TITLE
`Repo.insert`'s `on_conflict` with an instruction set or `{:replace, [:field]}` is replacing timestamps (both updated_at and inserted_at)

### ISSUE THREAD

**Issue by kybishop** [elixir-ecto/ecto#4413]
### Elixir version

1.16.2

### Database and Version

PostgreSQL 14.8

### Ecto Versions

3.11

### Database Adapter and Versions (postgrex, myxql, etc)

ecto_sql 3.11

### Current behavior

Run either of these with a few seconds between, note that the returned record has an altered inserted_at and updated_at:

```elixir
Repo.insert(
  SomeSchemaWithTimestamps.changeset(%{email: email, remote_id: remote_id}),
  conflict_target: :remote_id,
  on_conflict: {:replace, [:email]}
)

Repo.insert(
  SomeSchemaWithTimestamps.changeset(%{email: email, remote_id: remote_id}),
  conflict_target: :remote_id,
  on_conflict: [
    set: [email: email]
  ]
)
```

Here is the Schema for the record where we're seeing this happen:

```elixir
  defmodule ExternalUserSchema do
  alias Ecto.Changeset

  use Ecto.Schema

  @type t :: %__MODULE__{}

  @derive {Jason.Encoder, only: [:id, :email]}

  schema "external_users" do
    field(:deleted_at, :utc_datetime)
    field(:email, :string)
    field(:remote_id, :string)

    timestamps()
  end

  def changeset(params) do
    Changeset.cast(%__MODULE__{}, params, [:email, :remote_id])
    |> Changeset.validate_required([:email, :remote_id])
  end
end
```

### Expected behavior

When providing an instruction set, the instruction set is carried out and timestamps remain unchanged.

When providing a `{:replace, [:fields]}`, only the specified fields are replaced (not timestamps).

**Comment by kybishop** [comment]
`updated_at` changing makes sense here, but `inserted_at` changing seems like it can't be intentional.

**Comment by josevalim** [comment]
@kybishop the struct is not updated with the information from the database. You would have to use read_after_writes or explicitly read it back instead, the semantics are database dependent and the docs cover it: https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2-upserts :)
