### ISSUE TITLE
select_merge erroneously validates struct keys if the select_merge contains a subquery

### ISSUE THREAD

**Issue by kieraneglin** [elixir-ecto/ecto#4420]
### Elixir version

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Database and Version

SQLite

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

ecto_sqlite3 0.15.1, exqlite 0.19.0

### Current behavior

The [documentation](https://hexdocs.pm/ecto/Ecto.Query.html#select_merge/3) for `select_merge` states:

> The value being merged on must be a struct or a map. If it is a struct, the fields merged later on must be part of the struct, otherwise an error is raised.

Which works as expected _except_ if the map's value is a subquery:

```elixir
from(p in Post,
  as: :post,
  # Converting to a map
  select: map(p, ^Post.__schema__(:fields)),
  # The below works
  # select_merge: %{foo: "bar"}
  # The below does _not_ work
  select_merge: %{
    foo:
      subquery(
        from l in Likes,
          where: l.post_id == parent_as(:post).id,
          select: count(l.id)
      )
  }
)
```

In the case of the subquery, the following error is returned: `struct MyApp.Post does not have the key :foo`

### Expected behavior

The subquery should be evaluated and its result should be added to the returned map without checking if the `Post` struct contains the given key

There are a few workarounds. First, I can start the parent query off as `from p in "posts"` which avoids the Post struct entirely. Another option is to change the `select` to `merge(map(s, ^Source.__schema__(:fields)), %{})` which works but looks _very_ incorrect

**Comment by kieraneglin** [comment]
an aside: a `to_map(p)` function to replace the `map(p, ^Post.__schema__(:fields))` would be very cool (:

**Comment by greg-rychlewski** [comment]
Thanks for the report @kieraneglin. Could you try against our master branch? When I try to create an integration test that reproduces the issue, I don't get the same error:

```elixir
test "subquery map merge" do
    TestRepo.insert!(%Comment{})

    squery = from c in Comment, select: count(c.lock_version)
    q = from c in Comment, select: map(c, ^Comment.__schema__(:fields)), select_merge: %{foo: subquery(squery)}
    TestRepo.all(q)
  end
```

**Comment by kieraneglin** [comment]
Thanks for the quick response, @greg-rychlewski!

I've pulled down the repo locally and added your test verbatim (along with `alias Ecto.TestRepo`) to `test/ecto/query/subquery_test.exs` and I was able to replicate the issue on the master branch with Elixir 1.16.2 (compiled with Erlang/OTP 26).  For completeness, this non-subquery test produces no error:

```elixir
test "subquery map merge non-subquery" do
  TestRepo.insert!(%Comment{})

  q = from c in Comment, select: map(c, ^Comment.__schema__(:fields)), select_merge: %{foo: "bar"}
  TestRepo.all(q)
end
```

![Screenshot 2024-05-17 at 2 49 39 PM](https://github.com/elixir-ecto/ecto/assets/569917/218e4e46-965b-4342-a472-2113d09a964a)

**Comment by kieraneglin** [comment]
Oh, sorry, I misread. Let me see if I can produce the exact same error I was seeing

**Comment by kieraneglin** [comment]
Updating from `3.11.1` to `3.11.2` seems to have done it!

Thank you for the help 🙌
