### ISSUE TITLE
Support `select: map(x, fields), select_merge: %{...}` in source query for insert_all

### ISSUE THREAD

**Issue by nmk** [elixir-ecto/ecto#4430]
### Elixir version

1.16.3

### Database and Version

PostgreSQL 15.0

### Ecto Versions

master

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

```elixir
Repo.insert_all(Foo, from x in Foo, select: %{foo: x.foo, bar: x.bar}, select_merge: %{baz: some_fun(x.baz)})
```

works as intended.

```elixir
Repo.insert_all(Foo, from x in Foo, select: map(x, [:foo, :bar]), select_merge: %{baz: some_fun(x.baz)})
```

raises an ArgumentError stating that the source query does not select into a map.

### Expected behavior

The above two snippets should both be supported as they should result in the same source query being produced.

I would be happy to take a stab at this if this is indeed the intended behaviour.

**Comment by josevalim** [comment]
Please take a stab at it. It may be that making it work is just too complex, and then we could improve the error message, but we should definitely try it!

**Comment by nmk** [comment]
> Please take a stab at it. It may be that making it work is just too complex, and then we could improve the error message, but we should definitely try it!

I have made a PR which adds a test and the simplest code to make the test pass.

As far as I can see the test (as others in the same vein) only assert that a query would be successfully created, not that it would be correct. Is there a way to assert on the query itself?

**Comment by aglassman** [comment]
Using insert_all also fails with `struct/2`, and `%{c | field: ^val}`.   Just happened to dig into this today.

```elixir
  # This does not work!
  def test_1() do
    # initial query
    query = from(c in Click, select: c, limit: 1)

    Ecto.Multi.new()
    |> Ecto.Multi.insert_all(:click, Click, query)
    |> Repo.transaction()
  end

  # This does not work!
  def test_2() do
    # initial query
    query = from(c in Click, select: struct(c, [:short_code]), limit: 1)

    Ecto.Multi.new()
    |> Ecto.Multi.insert_all(:click, Click, query)
    |> Repo.transaction()
  end

  # This does not work!
  def test_3(short_code_override \\ "default sc") do
    # initial query
    query = from(c in Click, select: %{c | short_code: ^short_code_override}, limit: 1)

    Ecto.Multi.new()
    |> Ecto.Multi.insert_all(:click, Click, query)
    |> Repo.transaction()
  end
```

**Comment by greg-rychlewski** [comment]
Hi @aglassman ,

Something like this will not work because the update syntax is essentially post processing. Whatever is returned from the query will later be updated in Elixir. Thus it can't work for `insert_all` where you need everything to happen in the database.

```elixir
 query = from(c in Click, select: %{c | short_code: ^short_code_override}, limit: 1)

```

But this should work. I tested it:

```elixir
query = from(c in Click, select: struct(c, [:short_code]), limit: 1)
```

Maybe your ecto version is old? If you try on the latest commit does it still happen?

**Comment by greg-rychlewski** [comment]
I thought maybe it would make sense to select the entire struct. But after playing around with it there are quite a few issues. Mostly because you will be selecting primary keys and foreign keys which will cause issues in a lot of cases.

**Comment by aglassman** [comment]
@greg-rychlewski Thanks for the explanation into why the update syntax does not work, that is good to know.  As for `struct/2` usage, I mistakingly assumed the error was related to the insert_all select, when it was actually a constraint violation (inserted_at is required).  My apologies on that one!
