### ISSUE TITLE
Failure when using multiple lateral joins

### ISSUE THREAD

**Issue by mewa** [elixir-ecto/ecto#4436]
### Elixir version

1.16.0

### Database and Version

MySQL 8.3.0

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.7.0

### Current behavior

When composing a query consisting of _multiple_ lateral joins Ecto erroneously tries to use only the results from the first join, resulting in errors about access to non-existent fields.

I prepared a short example which demonstrates the issue.

## Example

```elixir
defmodule TestSchema do
  use Ecto.Schema
  import Ecto.Changeset

  import Ecto.Query, warn: false
  alias Test.Repo

  @primary_key {:id, Ecto.UUID, autogenerate: true}
  @foreign_key_type :binary_id
  schema "test_schemas" do
  end

  def changeset() do
    %__MODULE__{}
    |> cast(%{}, [])
  end

  def test() do
    # create test table
    try do
      Repo.query!("CREATE TABLE test_schemas (id BINARY(16))")
      |> IO.inspect
    rescue
      _ ->
        nil
    end

    # create record to be fetched
    p = changeset()
    |> Repo.insert!()

    # fetch record
    TestSchema
    |> where([p], p.id == ^p.id)
    # fetch_a() and fetch_b() are both using lateral joins
    |> fetch_a()
    |> fetch_b()
    |> Repo.one!()
  end

  defp fetch_a(query) do
    query
    |> join(:left_lateral,
            [p],
            data_a in subquery(
              TestSchema
              |> select([p], %{data_a: 1})
            ), on: true
    )
    |> select_merge([p, data_a], %{p | data_a: data_a.data_a})
  end

  defp fetch_b(query) do
    query
    |> join(:left_lateral,
            [p],
            data_a in subquery(
              TestSchema
              |> select([p], %{data_b: 500})
            ), on: true
    )
    |> select_merge([p, data_b], %{p | data_b: data_b.data_b})
  end

end
```

When fetching the record with just one lateral join (either `fetch_a()` or `fetch_b()`) it works as expected.

However, using both (`TestSchema.test()`) results in the following error:
```elixir
iex(1)> TestSchema.test
[debug] QUERY ERROR db=0.3ms queue=0.5ms idle=1079.7ms
CREATE TABLE test_schemas (id BINARY(16)) []
[debug] QUERY OK db=1.1ms queue=0.7ms idle=1097.1ms
INSERT INTO `test_schemas` (`id`) VALUES (?) ["f8937c19-d535-4c26-af50-b0667b51c055"]
↳ TestSchema.test/0, at: lib/repro.ex:28
** (Ecto.QueryError) lib/repro.ex:46: field `data_b` does not exist in subquery in query:

from t0 in TestSchema,
  left_lateral_join: t1 in subquery(from t0 in TestSchema, # first lateral join is `t1`
  select: %{data_a: 1}),
  on: true,
  left_lateral_join: t2 in subquery(from t0 in TestSchema, # second lateral join is `t2`
  select: %{data_b: 500}),
  on: true,
  where: t0.id == ^"f8937c19-d535-4c26-af50-b0667b51c055",
  select: merge(merge(t0, %{t0 | data_a: t1.data_a}), %{t0 | data_b: t1.data_b})
  # but `data_b` is accessed using `t1`, instead of `t2` as it should be

    (elixir 1.16.0) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.11.2) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
    iex:1: (file)
```

As you can see, the first lateral join is `t1`, the second one is `t2`, but when accessing `data_b` it is being accessed using `t1`, rather than `t2` as it should be.

### Expected behavior

It's possible to perform a query with multiple lateral joins and their results are correctly assigned when selected.

**Comment by greg-rychlewski** [comment]
Hi @mewa ,

When you call `fetch_a` and then `fetch_b` there are actually 3 binds. The first is `TestSchema`, the second is the first lateral join and the third is the second lateral join. 

So `select_merge([p, data_b], %{p | data_b: data_b.data_b})` is selecting the first lateral join. The bindings are based on positions unless you name them ([see here](https://hexdocs.pm/ecto/Ecto.Query.html#module-named-bindings)).

**Comment by mewa** [comment]
Thanks for the quick response! I just came to a similar realization and came back to close the issue but you beat me to it 😄  Sorry for the trouble!

For anyone bumping into a similar issue in the future, it's also possible to do it using `[p, ..., data_a]` and `[p, ..., data_b]` syntax, where `...` is translated to all the bindings in-between the first and the last one (which you're usually defining when writing composable queries) – [link to docs](https://hexdocs.pm/ecto/Ecto.Query.html#module-positional-bindings)
