### ISSUE TITLE
Use of "queryable" in documentation for e.g. `has_one` is misleading

### ISSUE THREAD

**Issue by Munksgaard** [elixir-ecto/ecto#4443]
### Elixir version

1.17.1

### Database and Version

PostgresQL 15.7

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

The documentation for [`has_one/3`](https://hexdocs.pm/ecto/Ecto.Schema.html#has_one/3) and some of the other functions in `Ecto.Schema` list their second argument as `queryable`. The only other use of "queryable" in that document is under [Examples](https://hexdocs.pm/ecto/Ecto.Schema.html#module-example) where it says:

> Source-based schemas are queryable by default, which means we can pass them to [Ecto.Repo](https://hexdocs.pm/ecto/Ecto.Repo.html) modules and also build queries:
>
> ```elixir
> MyRepo.all(User)
> MyRepo.all(from u in User, where: u.id == 13)
> ```

Which leads me to believe that the `queryable` argument to `has_one/3` is the same as requiring a value implementing the [`Ecto.Queryable`](https://hexdocs.pm/ecto/Ecto.Queryable.html) protocol. 

However, this does not seem to be the case. When I tried specifying a schema with the field

```elixir
has_one :foo, from(p in Foo, order_by: [desc: :inserted_at])
```

I get the error:

```
== Compilation error in file lib/foo/foos/foo.ex ==
** (ArgumentError) association :foo queryable must be a schema or a {source, schema}. got: #Ecto.Query<from p0 in Foo.Foos.Foo, order_by: [desc: p0.inserted_at]>
    (ecto 3.11.2) lib/ecto/association.ex:468: Ecto.Association.related_from_query/2
    (ecto 3.11.2) lib/ecto/association.ex:799: Ecto.Association.Has.struct/3
    (ecto 3.11.2) lib/ecto/schema.ex:1969: Ecto.Schema.association/5
    (ecto 3.11.2) lib/ecto/schema.ex:2133: Ecto.Schema.__has_one__/4
    lib/foo/foos/foo.ex:19: (module)
``` 

### Expected behavior

I would either expect a clarifying remark in the documentation as to what specifically a `queryable` is in this context or I would expect `has_one/3` and friends to accept an `Ecto.Queryable` instead.

**Comment by v0idpwn** [comment]
Seems to be indeed an oversight in the parameter name.
