### ISSUE TITLE
Macro expansion in `order_by`

### ISSUE THREAD

**Issue by Gigitsu** [elixir-ecto/ecto#4448]
### Elixir version

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Database and Version

*

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

*

### Current behavior

Using a macro that returns a list of orders in an `order_by` clause, results in an error.

For example, I can define a macro like this:

```
defmacro my_custo_order(t) do
  quote do
    [desc: unquote(t).id, asc: unquote(t).inserted_at]
  end
end
```

But when I try to use it:

```
from p in Post, order_by: my_custo_order(p)
```

I get the following error:

```
** (Ecto.Query.CompileError) Tuples can only be used in comparisons with literal tuples of the same size
    (ecto 3.11.1) expanding macro: Ecto.Query.order_by/3
    iex:2: (file)
```

Defining macro like the latter could be handy if you have a fragment as a part of the order logic (eg. `[asc: fragment("? <<-> ?", ^search_query, t.name), desc: ....]`)

### Expected behavior

The macro should be correctly expanded and the expression generated used without errors

**Comment by Gigitsu** [comment]
I've made a quick PR (#4449) to fix this issue.
It's still a draft, I tried an approach to fix this issue. If this approach is reasonable, I can complete it.

**Comment by josevalim** [comment]
Closing in favor of the PR.
