### ISSUE TITLE
Should we allow disabling of Ecto cache on specific queries?

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/ecto#4470]
### Elixir version

all

### Database and Version

all

### Ecto Versions

all

### Database Adapter and Versions (postgrex, myxql, etc)

all

### Current behavior

I believe all queries are using the Ecto cache with no API no turn it off.

### Expected behavior

This forum post makes me think there is a valid use case to make it configurable per query: https://elixirforum.com/t/ecto-query-cache-seems-to-grow-without-limits/65326

The use case is they are issuing "one and done" kind of queries to do some clean up. These queries are utilizing `values` which is cached based on a count of the number of entries. So each new count creates a new cache entry would could potentially be very big in size (they are saying 200-600 params per query). Since these are big queries that aren't meant to be repeatedly used it might make sense to let them disable the cache?

**Comment by josevalim** [comment]
We should disable the cache for `values` queries unless the values are somehow passed as parameters.

**Comment by josevalim** [comment]
We do something similar for `in` in SQL queries.
