### ISSUE TITLE
Error for insert_all with select_merge query

### ISSUE THREAD

**Issue by liamwhite** [elixir-ecto/ecto#4474]
### Elixir version

Elixir 1.17.0

### Database and Version

PostgreSQL 16.3

### Ecto Versions

master ef93693

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex ee52684

### Current behavior

given
```elixir
defmodule ImageCommentNotification do
  use Ecto.Schema

  @primary_key false
  schema "image_comment_notifications" do
    belongs_to :user, User, primary_key: true
    belongs_to :image, Image, primary_key: true
    belongs_to :comment, Comment
    field :read, :boolean, default: false
    timestamps(type: :utc_datetime)
  end
end
```
the following insert fails:
```elixir
    new_comment_notifications =
      from cn in ImageCommentNotification,
        where: cn.image_id == ^source.id,
        select_merge: %{
          user_id: cn.user_id,
          image_id: ^target.id,
          comment_id: cn.comment_id,
        },
        select_merge: %{
          read: cn.read,
          inserted_at: cn.inserted_at,
          updated_at: cn.updated_at
        }

    {comment_notification_count, nil} =
      Repo.insert_all(ImageCommentNotification, new_comment_notifications, on_conflict: :nothing)
```
with this error:
```
** (ArgumentError) the source query given to `insert_all` has selected both `map/2` and
a literal map:

#Ecto.Query<from i0 in ImageCommentNotification, where: i0.image_id == ^..., select: merge(merge(i0, %{user_id: i0.user_id, image_id: ^..., comment_id: i0.comment_id}), %{
  read: i0.read,
  inserted_at: i0.inserted_at,
  updated_at: i0.updated_at
})>

when using `select_merge` with `insert_all`, you must always use literal
maps or always use `map/2`. The two cannot be combined.
```
I used literal maps.

This error message was introduced by https://github.com/elixir-ecto/ecto/pull/4460 as part of a solution for https://github.com/elixir-ecto/ecto/issues/4430 (which I recognize is substantially similar to this report). Before it would fail with a different error.

### Expected behavior

This should work and not fail, probably.

**Comment by greg-rychlewski** [comment]
@liamwhite Does it happen even if the first merge is converted to a plain select?

**Comment by liamwhite** [comment]
@greg-rychlewski I just tried it and it does, yes

**Comment by greg-rychlewski** [comment]
Can you post your code you use to generate that second query? From my testing it should be ok

```elixir
from s in MySchema,
          where: s.x > ^threshold,
          select: %{
            x: s.x,
            y: "bar",
            z: nil
          },
          select_merge: %{
            w: s.y
          }
          
%Ecto.Query.SelectExpr{
  aliases: %{},
  expr: {:%{}, [],
   [
     x: {{:., [type: :string], [{:&, [], [0]}, :x]}, [], []},
     y: "bar",
     z: nil,
     w: {{:., [type: :binary], [{:&, [], [0]}, :yyy]}, [], []}
   ]}
```

The reason two select merges doesn't work is because adding a merge without a select tries to merge the literal map onto the entire source. So we have a mismatch again

```elixir
from s in MySchema,
          where: s.x > ^threshold,
          select_merge: %{
            x: s.x,
            y: "bar",
            z: nil
          },
          select_merge: %{
            w: s.y
          }   
   
%Ecto.Query.SelectExpr{
  aliases: %{},
  expr: {:merge, [],
   [
     {:merge, [],
      [
        {:&, [], [0]},
        {:%{}, [],
         [
           x: {{:., [type: :string], [{:&, [], [0]}, :x]}, [], []},
           y: "bar",
           z: nil
         ]}
      ]},
     {:%{}, [], [w: {{:., [type: :binary], [{:&, [], [0]}, :yyy]}, [], []}]}
   ]}
```

**Comment by liamwhite** [comment]
It's the same as in the OP but I changed the first select_merge to select. Try adding an interpolation in the first select. I think that's the issue.

**Comment by greg-rychlewski** [comment]
Oh I see, yes you're right that would cause the issue. I think this is a mistake in how we build the select expression. Will try to see what I can do.

**Comment by greg-rychlewski** [comment]
We should probably also improve the error message to account for the two merges case

**Comment by greg-rychlewski** [comment]
@josevalim This one is pretty tricky. Take this query:

```elixir
from cn in ImageCommentNotification,
        where: cn.image_id == ^source.id,
        select: %{
          user_id: cn.user_id,
          image_id: ^target.id,
          comment_id: cn.comment_id,
        },
        select_merge: %{
          read: cn.read,
          inserted_at: cn.inserted_at,
          updated_at: cn.updated_at
        }
```

Under normal circumstances 2 literal maps would merge into each other, but when one of them has a query parameter they don't. Relevant excerpt from select builder:

```elixir
{{:map, meta, old_fields}, {:map, _, new_fields}} when old_params == [] ->
      cond do
        old_fields == [] ->
          new_expr

        new_fields == [] ->
          old_expr

        Keyword.keyword?(old_fields) and Keyword.keyword?(new_fields) ->
          {:%{}, meta, Keyword.merge(old_fields, new_fields)}

        true ->
          {:merge, [], [old_expr, new_expr]}

{_, {:map, _, _}} ->
      {:merge, [], [old_expr, new_expr]}
```

So what happens is we select both the old and the new value then clean it up in post processing. I think I can understand the rationale why. If we didn't do this we would need to clean up the params so the query doesn't fail.

So I see three options:

1. Clean up the params if we can. I don't think this is so bad implementation wise. But then it's a question if we want the code to behave this way. One argument for it behaving this way is it's consistent with how it works for other things. i.e. if we have `select: %{x: s.x}, select_merge: %{x: s.y}` we won't select both `x` and `y`.
2. Say you can't merge literal maps if there is a query parameter in anything but the latest merge. But is limiting and probably a bit confusing for users.
3. Try to make all select expressions work. We considered it before but with all the nesting that can happen it can get a bit unweidy.

My thought right now is 1 seems the best. But please let me know what you think.

**Comment by josevalim** [comment]
Good analysis!

> Even outside of insert_all, we have bugs with subqueries which seems to point towards cleaning up the params:

This is exactly the problem. Removing a parameter from an expression after the fact can be quite complicated. Since they are positional, you would have to rearrange all other subsequent positions. Depending on where that happens in the planner, it can be too late or too tricky or too expensive.

So I am not against improvements but I am also completely fine with raising a better error message on the subquery case and saying you cannot merge over a parameter. After all, the user can always write `except(:select) |> select()` and define the proper select from scratch. We don't have to make all possible combinations work. :)

**Comment by liamwhite** [comment]
Given the consensus in the linked PR is that Ecto can't reasonably support `insert_all` with interpolations and `select_merge`, I ask about another issue I am having related to this: is there any way I can spare myself the duplication in the following insert_all examples?

My original plan for subscription query -> notification table was
```elixir
defp convert_to_notification(subscription, [_ | _] = conditions) do
  now = DateTime.utc_now()
  query =
    from s in subscription,
      select: %{
        user_id: s.user_id,
        inserted_at: ^now,
        updated_at: ^now,
        read: false
      }
      
  Enum.reduce(conditions, query, fn {name, object_id} ->
    select_merge(query, [s], %{^name => type(^object_id, :integer)})
  end)
end
```

But since this isn't possible, I've expanded it out to two functions, since this is currently the maximum amount I need. Is this necessary or could I have written something simpler?

```elixir
defp convert_to_notification(subscription, [{name, object_id}]) do
  now = DateTime.utc_now()

  from s in subscription,
    select: %{
      ^name => type(^object_id, :integer),
      user_id: s.user_id,
      inserted_at: ^now,
      updated_at: ^now,
      read: false
    }
end

defp convert_to_notification(subscription, [{name1, object_id1}, {name2, object_id2}]) do
  now = DateTime.utc_now()

  from s in subscription,
    select: %{
      ^name1 => type(^object_id1, :integer),
      ^name2 => type(^object_id2, :integer),
      user_id: s.user_id,
      inserted_at: ^now,
      updated_at: ^now,
      read: false
    }
end
```

**Comment by greg-rychlewski** [comment]
Does something like this work for you:

```elixir
now = dynamic([_], ^DateTime.utc_now())
user_id = dynamic([s], s.user_id)
base = %{user_id: user_id,  inserted_at: now, updated_at: now , read: false}
extra = [name1: :obj1, name2: :obj2] |> Enum.into(%{})
select = Map.merge(base, extra)
query = from(b in "blogs", select: ^select)

assert Macro.to_string(query.select.expr) == "%{inserted_at: ^0, name1: :obj1, name2: :obj2, read: false, updated_at: ^1, user_id: &0.user_id()}"
```

**Comment by greg-rychlewski** [comment]
For completeness, I got this to work on our integration tests. It looks like what you are trying to do:

```elixir
TestRepo.insert!(%Post{})

now = dynamic([_], type(^DateTime.utc_now(), :utc_datetime))
id = dynamic([p], p.id + 1)

base = %{id: id, inserted_at: now, updated_at: now, public: false}
extra = [visits: 1, counter: 2] |> Enum.map(fn {field, value} -> {field, dynamic([_], type(^value, :integer))} end) |> Enum.into(%{})
select = Map.merge(base, extra)

query = from(p in Post, select: ^select)
IO.inspect TestRepo.insert_all(Post, query, returning: true, log: :error)
```

The query generated is:

```sql
INSERT INTO "posts" ("id","public","counter","visits","inserted_at","updated_at") (SELECT p0."id" + 1, FALSE, $1::bigint, $2::bigint, $3::timestamp, $4::timestamp FROM "posts" AS p0) RETURNING "updated_at","inserted_at","author_id","read_only","posted","intensities","links","meta","uuid","bid","intensity","wrapped_visits","visits","cost","public","blob","title","counter","id" [2, 1, ~U[2024-08-06 08:45:39Z], ~U[2024-08-06 08:45:39Z]]
```

**Comment by greg-rychlewski** [comment]
In general `select_merge` is used when you are re-using an old query and want to add some new stuff onto it. And `dynamic/2` is used when you have one thing but you don't know what that thing will be at compile time.

**Comment by liamwhite** [comment]
Okay, that's a lot messier than what I had hoped for with the select_merge but it works. Thanks.
