### ISSUE TITLE
Improve support for soft deletes

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4481]
### Elixir version

All

### Database and Version

PostgreSQL 14+

### Ecto Versions

All

### Database Adapter and Versions (postgrex, myxql, etc)

Postgrex

### Current behavior

I am trying to enable soft-delete behaviour in an application, following the rules in this article: https://evilmartians.com/chronicles/soft-deletion-with-postgresql-but-with-logic-on-the-database

Assuming a "item" table with the following field:

```elixir
  add :_deleted_at, :utc_datetime
```

I can trivially add soft deletes like this:

```elixir
    execute """
            CREATE OR REPLACE RULE "phx_sync_soft_deletion" AS ON DELETE TO "items"
            DO INSTEAD UPDATE items SET _deleted_at = NOW() WHERE id = OLD.id RETURNING OLD.*;
            """,
            """
            DROP RULE IF EXISTS phx_sync_soft_deletion ON items;
            """
```

As well as a view that hides all deleted rows:

```
    execute "CREATE OR REPLACE VIEW visible_items AS SELECT * FROM items WHERE _deleted_at IS NULL",
            "DROP VIEW IF EXISTS visible_items"
```

And then I change my Ecto schema to the following:

```elixir
  schema "visible_items" do
```

This means I only see the non soft-deleted rows. But if I want to see them all, I can do `Repo.all({"items", Item})`.

However, this has one issue: because the delete never happen, the underlying `Repo.delete(item)` operation returns zero rows. Ecto then assumes this is happening because the record does not exist, and return an `Ecto.StaleEntryError`. We can workaround this by calling `{:error, _changeset} = Repo.delete(item, stale_error_field: :id)` but it still returns an error tuple.

### Expected behavior

Perhaps we should allow a `allow_stale: true` option? Or `allow_no_return: true`?

I thought about enabling this by default, because a `delete` should be idempotent, but perhaps that's not the best idea. Some applications may want to detect when two deletes race each other?

**Comment by greg-rychlewski** [comment]
`:allow_stale` seems better to me because the count of 0 is still technically a return value. and also you can still use `returning`. 

i thought maybe postgres has a way to send the number of affected rows if a rule is changing the delete. but i haven't been able to find anything to do that

**Comment by greg-rychlewski** [comment]
Enabling by default might be confusing. Assuming we will still return `{:ok, struct}`.

My reason for thinking this is because I see the same kind of confusion when insert/update are used without returning. It is relatively common for new people to be confused why the returned struct is not what they expect to be in the database. So this is kind of like another way to be confused.

**Comment by josevalim** [comment]
Since zero rows are returned, returning has no effect, unfortunately.

**Comment by v0idpwn** [comment]
[Implementation is trivial](https://github.com/elixir-ecto/ecto/commit/ca3c50a912d663805e7f45ebb1986946b178e289). I'm against it being default because:
1) It's a breaking change
2) It can be a foot-gun / confusion point. Being opt-in is more straightforward IMO

**Comment by greg-rychlewski** [comment]
Oh if both the rule and the delete operation specify returning I think you can still get data. At least it worked when I tested on my psql

**Comment by josevalim** [comment]
> Oh if both the rule and the delete operation specify returning I think you can still get data. At least it worked when I tested on my psql

So psql is doing something special. If I do this on the sample app I have:

    Sync.Repo.query!("DELETE FROM items WHERE id = $1 RETURNING id", [Ecto.UUID.dump!(id)])
    |> IO.inspect()

It returns this:

```
%Postgrex.Result{
  command: :delete,
  columns: nil,
  rows: nil,
  num_rows: 0,
  connection_id: 1286,
  messages: []
}
```

I would love if it worked :(

**Comment by greg-rychlewski** [comment]
Yeah it seems it works with simple queries but not the binary protocol. I tried testing in Ecto as well and when it didn't work I tried in Postgrex directly to see what was going on. And I could get it to work on a simple connection but not a "normal" postgrex connection.

I'm curious what's going on so I'll probably still keep looking into it. But don't know if I'll find anything useful so probably shouldn't hold up this issue.

**Comment by Schultzer** [comment]
Beside the obvious benefits that comes with creating rules in the the database, then Ecto already points in the directions of implementation in the application layer:  https://hexdocs.pm/ecto/Ecto.Repo.html#c:prepare_query/3 and to me, this is where Ecto/Elixir application becomes powerful.

 So maybe we should be able to modify a repos insert/delete/update even more.

**Comment by josevalim** [comment]
We can close this, no?

**Comment by v0idpwn** [comment]
I reopened because while the suggestion was implemented, there could be further discussion. But yeah, I think it can be closed :)
