### ISSUE TITLE
Release v3.12

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#4483]
### Elixir version

All

### Database and Version

All

### Ecto Versions

All

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

Ecto v3.12 is not released.

### Expected behavior

Ecto v3.12 to be released.

@greg-rychlewski / @v0idpwn are you happy with a new release?

**Comment by greg-rychlewski** [comment]
All good for me

**Comment by v0idpwn** [comment]
I didn't track most of the changes closely. From my side, all seems good

**Comment by josevalim** [comment]
Done, thank you once again @greg-rychlewski for doing the bulk of the work on this new release! :green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
