### ISSUE TITLE
Undocumented or Incorrect dialyzer spec changes

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-ecto/ecto#4484]
### Elixir version

1.17

### Database and Version

---

### Ecto Versions

3.12.0

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

mix dialyzer warning:
```
Ecto.Enum.values(MyApp.MySchema, :status)

will never return since the success typing is:
(map(), atom()) :: [atom()]

and the contract is
(map() | Ecto.Schema.t(), atom()) :: [atom()]
```

### Expected behavior

Since the code above still works, it seems like the typespec is incorrect. If it is incorrect, I missed anything regarding this in the Changelog. This is from live view generated code.

**Comment by josevalim** [comment]
Wait, I checked the code and the spec accepts schema. Perhaps you need a fresh dialyzer build or something?

**Comment by wkirschbaum** [comment]
@josevalim let me refresh the cache and check. We are getting this from CI and multiple machines 🤔.

**Comment by wkirschbaum** [comment]
refreshed dialyzer cache and still getting the issue. Let us investigate further on our side.

**Comment by wkirschbaum** [comment]
Is this not correct? 

```diff
@@ -235,7 +235,7 @@ defmodule Ecto.Enum do
       #=> [:foo, :bar, :baz]
 
   """
-  @spec values(map | Ecto.Schema.t(), atom) :: [atom()]
+  @spec values(map | atom, atom) :: [atom()]
   def values(schema_or_types, field) do
     schema_or_types
     |> mappings(field)
@@ -316,7 +316,7 @@ defmodule Ecto.Enum do
       #=> [foo: 1, bar: 2, baz: 5]
 
   """
-  @spec mappings(map | Ecto.Schema.t(), atom) :: keyword(String.t() | integer())
+  @spec mappings(map | atom, atom) :: keyword(String.t() | integer())
   def mappings(schema_or_types, field)
 
   def mappings(types, field) when is_map(types) do
```

since 

```elixir
  @spec mappings(map | atom, atom) :: keyword(String.t() | integer())
  def mappings(schema_or_types, field)

  def mappings(types, field) when is_map(types) do
   .....
  end

  def mappings(schema, field) when is_atom(schema) do
  ...
  end
  ```
  
  can be an atom or map

**Comment by josevalim** [comment]
Ah, you are right. Schema.t is the struct. Please send a PR! But please use `module` instead of `atom`.

**Comment by wkirschbaum** [comment]
@josevalim just made that change. PR is draft until we finished our testing on our side.

**Comment by thiagogsr** [comment]
I'm not sure if it's the same issue, but I'm having issues with the schema enum field.

e.g.

```elixir
field(:resource_type, Ecto.Enum, values: ~w(resource_type1 resource_type2 resource_type3 resource_type4)a)
```

The error

```elixir
** (FunctionClauseError) no function clause matching in Ecto.Type.cast_fun/1

     The following arguments were given to Ecto.Type.cast_fun/1:

         # 1
         {:parameterized, Ecto.Enum, %{on_load: %{"resource_type1" => :resource_type1, "resource_type2" => :resource_type2, "resource_type3" => :resource_type3, "resource_type4" => :resource_type4}, type: :string, on_cast: %{"resource_type1" => :resource_type1, "resource_type2" => :resource_type2, "resource_type3" => :resource_type3, "resource_type4" => :resource_type4}, embed_as: :self, mappings: [resource_type4: "resource_type4", resource_type1: "resource_type1", resource_type2: "resource_type2", resource_type3: "resource_type3"], on_dump: %{resource_type4: "resource_type4", resource_type1: "resource_type1", resource_type2: "resource_type2", resource_type3: "resource_type3"}}}
```

That function on ecto is:

```elixir
defp cast_fun({:parameterized, {mod, params}}), do: &mod.cast(&1, params)
```

So `{:parameterized, {mod, params}}` is different than `{:parameterized, mod, params}`

**Comment by josevalim** [comment]
This is listed in the CHANGELOG as a potential backwards incompatible change. It may either be a bug in Ecto or, if you are using an Ecto extension, they need to be updated accordingly. A full stacktrace and a potential reproduction mechanism will be welcome.

**Comment by thiagogsr** [comment]
Ah yes, I've just noticed it's happening on [Oban structured jobs](https://getoban.pro/docs/pro/1.4.11/Oban.Pro.Worker.html#module-structured-jobs) and on [PolymorphicEmbed](https://hexdocs.pm/polymorphic_embed/readme.html)

**Comment by josevalim** [comment]
Nice, please report them and point them them to the CHANGELOG. Ideally we should have a public API for defining them that does not rely on its internal representation. Unfortunately we had to change it due to a bug fix.
