### ISSUE TITLE
v3.12: new errors raised in cast_assoc and put_assoc not mentioned in the CHANGELOG

### ISSUE THREAD

**Issue by dushyantss** [elixir-ecto/ecto#4500]
### Elixir version

All

### Database and Version

All

### Ecto Versions

All

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

The changes introduced in https://github.com/elixir-ecto/ecto/pull/4370 to cast_assoc and put_assoc now raise an ArgumentError, when they did not used to earlier.

### Expected behavior

The `Potential incompatibilities`(or `Bug Fixes`) section of the CHANGELOG should probably mention that.

**Comment by greg-rychlewski** [comment]
Thanks for the report. 3.12.2 was released and has the updated changelog

**Comment by jeremyowensboggs** [comment]
The change log 
> [Ecto.Changeset] Associations inside embeds have always been read-only. We now raise if you try to cast them inside a changeset

does not seem to be accurate - it appears that the associations were not read only. In 3.11 we could use
```
    embedded_schema do
      has_many :filters, AdvancedFilter, on_replace: :delete
      field :active_only, :boolean, default: true
    end

    @spec changeset(t(), map()) :: Ecto.Changeset.t()
    def changeset(model = %__MODULE__{}, params) do
      model
      |> cast(params, [:active_only])
      |> cast_assoc(:filters)
    end
```
and it worked, but in 3.12 it fails with an error.

**Comment by greg-rychlewski** [comment]
@jeremyowensboggs It worked to put it into the changeset, but in terms of how it behaved when using repo functions it was read only. So we stopped it from going into the changeset because it was being ignored.

Could you let me know if that make sense or if you have a use case that conflicts with it?

**Comment by jeremyowensboggs** [comment]
Ah - This use case is that we are taking data from the user - using the embedded schema to handle the conversion, validation and some change tracking - but only for driving the UI - it never is persisted to a database.

**Comment by greg-rychlewski** [comment]
@josevalim Is that aligned with the intended usage? I'm not sure if we need to roll this change back or not. I thought associations are always supposed to be persisted but I could be wrong.

**Comment by josevalim** [comment]
Yes, you can use embedded schemas for validation. We should revert the warning and update the docs to say they cannot be persisted. Thank you Greg and Jeremy!
