### ISSUE TITLE
`field/3`'s `:writable` seems to ignore the `:insert` option

### ISSUE THREAD

**Issue by lucavenir** [elixir-ecto/ecto#4524]
### Elixir version

1.16.2

### Database and Version

PostgreSQL 16.1

### Ecto Versions

3.12.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.19.1

### Current behavior

I wanted to apply this `:writable` option mentioned in [field/3' documentation](https://hexdocs.pm/ecto/Ecto.Schema.html#field/3). Unluckily `writable: insert` seems to be ignored.

Given this schema:
```ex
defmodule MyApp.Accounts.Account do
  use Ecto.Schema
  import Ecto.Changeset

  schema "accounts" do
    field :firebase_uid, :string, writable: :insert
    field :deactivated_at, :utc_datetime

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(account, attrs) do
    account
    |> cast(attrs, [:firebase_uid, :deactivated_at])
    |> validate_required([:firebase_uid])
  end
end
```
This tests fails:
```ex
test "update_account/2 doesn't allow firebase_uid to change" do
  account = account_fixture()
  invalid_attrs = %{ firebase_uid: "another different uid" }

  # this wont work
  # assert {:error, %Ecto.Changeset{}} = Accounts.update_account(account, invalid_attrs)
  # instead, these pass (???)
  {:ok, account} = Accounts.update_account(account, invalid_attrs)
  assert account.firebase_uid == "another different uid"  # !!
end
```

### Expected behavior

I'd expect the previous test to have the commented parts to pass, and the uncommented parts to fail, i.e. I'd expect this test to pass:

```ex
test "update_account/2 doesn't allow firebase_uid to change" do
  account = account_fixture()
  invalid_attrs = %{ firebase_uid: "another different uid" }

  assert {:error, %Ecto.Changeset{}} = Accounts.update_account(account, invalid_attrs)
  # or
  # {:ok, account} = Accounts.update_account(account, invalid_attrs)
  # assert account.firebase_uid != "another different uid" 
end
```

(meaning: I'm not sure if the `:insert` option ignores the write or returns an error, but surely it shouldn't allow an edit!)

**Comment by greg-rychlewski** [comment]
Hi @lucavenir ,

Thank you for the report. I believe the update is not silently not happening. We just filter the non-updatable fields out before performing the operation. Are you able to select from the database afterwards to see what the real value is? In the test I just did, this is the case.

Then I guess the question is should do something more than silently ignore.

**Comment by lucavenir** [comment]
Hello @gentoid,

Silently ignoring is coherent with much of `Ecto`'s behaviors AFAIK. So it's fine for me.

But in the test above, I check for the updated struct, and I find it to be updated even though it should silently ignore it.

So you're not able to reproduce this? If that's the case I'll try and reproduce this in a sandbox.

**Comment by greg-rychlewski** [comment]
You might have to pull the data again with `Repo.one`/`Repo.all`, etc... instead of looking at just the return from the update.

If you are not using the `returning` option or you are using that option and nothing is updated, you will just see the changeset you proposed for update. Not necessarily what's in the database.

**Comment by josevalim** [comment]
> Let me preface that I'm a 110% newbie on Ecto, but the APIs I've used up until now always return a struct representing the current state of the db after any operation.

When you have a changeset, we only send the fields you changed to the database. If any of the fields in the database have been changed meanwhile, that will actually not be reflected on the struct, unless you set `read_after_writes` for some particular fields (or via the `:returning` option). In other words, `returning` does not default to true (and it is not even supported by all databases).

There may still be arguments for changing the behaviour here though. Unsure. :)

**Comment by lucavenir** [comment]
Yeah I guess I didn't read the documentation well enough. Thanks for the quick response! 💕 

I understand what the current behavior is, so, it's expected behavior. I fail to understand what value does this behavior bring. But I accept it now.

What my [simple grug mind](https://grugbrain.dev/) would think (or desire?) is this process:
- hey ecto, here's some changes, I validated them via a changeset
- _great, I trust a changeset, but turns out this field is read-only, here's what has **actually** changed_
- nice, this struct you've given me now represents the current state of the system

Instead, what grug receives now is: "here's the fields that effectively changed PLUS whatever you passed me in that might not have changed". Am I understanding this right? I'm not sure what I can make of this (again, consider that I'm a 110% newb).

I'd leave the debate to people _way smarter than me_, I just wanted to share my 2 cents as a person in a learning process.

**In any case**, knowing that `returning: true` isn't a default, I simply used in `Repo.update/3` and I'm good to go! It works and my use case is solved like that.

**Comment by josevalim** [comment]
In your particular case, I'd say the simplest solution would be to not cast `firebase_uid` at all during updates, but I believe you are right that we should not apply that field at all as part of changes. It may be that we are filtering it too late? So it doesn't make its way to the database, but it still makes its way to the record.

**Comment by josevalim** [comment]
For now, the changeset approach is the way to go but we plan to fix what you reported so it just works. :)

**Comment by greg-rychlewski** [comment]
@lucavenir Thank you for the report and discussion. This never even crossed my mind.

**Comment by lucavenir** [comment]
Thank _you_ guys!

You're [breathtaking](https://youtu.be/5F_Kj5xgAcg?si=c-ITAg2FauGwfzTA)!

The fact that you've discussed and addressed this in less than 24h is awesome, beyond any possible imagination. Have a great day! 👍
