### ISSUE TITLE
Unexpected footgun while using `Repo.exists?/2`

### ISSUE THREAD

**Issue by nicolasferraro** [elixir-ecto/ecto#4530]
### Elixir version

1.17.3

### Database and Version

PostgreSQL 14.11

### Ecto Versions

3.11.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.17.5

### Current behavior

I quickly skimmed through `Repo.exists?/2`'s docs the other day and I saw that a keyword list could be provided as a second argument. My mind immediately assumed that an API similar to what `Repo.get_by/2` supports was supported, I.e. that something like this could work:
```elixir
> Repo.exists?(User, id: 1)
true
```
And it does, but it does not behave that way, what actually happens is that the `id: 1` argument I gave the function is just ignored and it checks for the existence of an User instead of an User with id `1`.

Now this is clearly my fault for not paying attention while reading, but I ended up shipping a bug to prod due to this mistake (again, my fault). Could a warning be added if keys other than `:prefix` or one of the `Shared options` are given to the second arg?

(Sorry if this is not the right place to post this)

### Expected behavior

Maybe something like this?

```elixir
Repo.exists?(User, id: 1, name: "John")
> warning: `[:id, :name]` are not supported as options, only: `[:prefix, ...]` are
> true
```

**Comment by josevalim** [comment]
This is tricky for us to handle because the options given to `Repo.exists?` are actually understood and interpreted by the database adapter. And we even have callbacks such as `prepare_options` that allow users to parse and customize options. So I don't think we can do something to effectively address this. We could special case some keys, such as `:id`, but it may not be worth it.

**Comment by greg-rychlewski** [comment]
Would it help at all if we expanded the description? Or do you think that would that have not prevented the issue from happening?

**Comment by nicolasferraro** [comment]
At the risk of sounding silly, a small admonition or callout with a colored background would've grabbed my attention for sure 😂 . But maybe a text disclaimer in the docs would be good enough too

**Comment by nicolasferraro** [comment]
> We could special case some keys, such as :id, but it may not be worth it.

Agreed on probably not being worth it. 

I looked for similar issues and couldn't find any in the repo so maybe updating the docs is good enough? 

Thanks to both for the quick responses!

**Comment by josevalim** [comment]
Would you like to send a PR giving the admonition text a try? Then we can collaborate and suggest improvements too, if you are not 100% comfortable.
