### ISSUE TITLE
json query with no results

### ISSUE THREAD

**Issue by someoneof** [elixir-ecto/ecto#4531]
### Elixir version

1.14.5

### Database and Version

postgresql 13

### Ecto Versions

3.0

### Database Adapter and Versions (postgrex, myxql, etc)

{:ecto_sql, "~> 3.0"},

### Current behavior

i have two rows in the user table with test jsonb fields
1. test: {"a": 1}
2. test: {"b": 3, "c": {"d": 4}}
3. query sql like this
user = :user
query =
      from(user in User, as: ^user)
Repo.all(query)

when filter condition is where([c], fragment("(?->>?)::int4 = ?", field(as(^user), :test), ^"b", ^3)),  no row to return
but when filter condition  is where([c], fragment("(?->>?)::int4 = ?", field(as(^user), :test), ^"a", ^1)),  one row to return

4.print sql like this:
SELECT u0."id", u0."name", u0."phone", u0."password", u0."ip", u0."status", u0."data_id", u0."test" FROM "user" AS u0 WHERE ((u0."test"->>$1)::int4 = $2) ["b", 3]

### Expected behavior

when filter is where([c], fragment("(?->>?)::int4 = ?", field(as(^user), :test), ^"b", ^3)), should return at least one row

**Comment by josevalim** [comment]
Can you please run the SQL query directly in the database and let us know what it returns? Or do you mean we should emit another SQL? If so, which SQL?

**Comment by someoneof** [comment]
SELECT u0."id", u0."name", u0."phone", u0."password", u0."ip", u0."status", u0."data_id", u0."test" FROM "user" AS u0 WHERE ((u0."test"->>'b')::int4 = 3)  
execute directly in postgresql  return one row
Repo.all(where(from(user in User, as: :user), [c], fragment("(?->>?)::int4 = ?", field(as(^user), :test), ^"b", ^3))), nothing to return

**Comment by someoneof** [comment]
![image](https://github.com/user-attachments/assets/b35db247-0932-4742-a912-730cae3241a1)
![image](https://github.com/user-attachments/assets/cb6a4d8a-9b19-481a-bce2-f8d32da81c74)

**Comment by someoneof** [comment]
It's my mistake. When I used preload, the two tables were not in the same schema. So I created the same tables under another schema and opened the SQL executor under the same schema, but I forgot to add @schema_prefix in the module. I'm very sorry.
Then there is a new problem: how to support different schemas when preloading?
