### ISSUE TITLE
Keep (and stringify) atoms in SELECT fields if keeping literals (for combinations)

### ISSUE THREAD

**Issue by ruslandoga** [elixir-ecto/ecto#4546]
### Elixir version

1.17.3

### Database and Version

Ecto.Query.Planner

### Ecto Versions

3.12.4

### Database Adapter and Versions (postgrex, myxql, etc)

Ecto.Query.Planner

### Current behavior

Context: https://elixirforum.com/t/unexpected-union-results-with-certain-ecto-selects/67376

Seems like Ecto.Query.Planner.normalize_select keeps literals if there are combinations already, but atoms are dropped [unconditionally](https://github.com/elixir-ecto/ecto/blob/4a99afd20cced4dbb354bfbc24653723cc70013a/lib/ecto/query/planner.ex#L2061-L2064) although they can be viewed [as strings](https://github.com/elixir-ecto/ecto/blob/4a99afd20cced4dbb354bfbc24653723cc70013a/lib/ecto/query/planner.ex#L2041-L2043) in that scenario.

### Expected behavior

 Ecto.Query.Planner.normalize_select keeps atoms and `Atom.to_string(atom)`'s them?

**Comment by josevalim** [comment]
This is tricky because the end result would require atoms instead, as the user wrote, so we would need to know which side of the union we need to convert back to atom, which can get messy. I think we should improve the error message here, if possible, but we need to be careful with atoms in "safe" positions (such as map keys).

**Comment by greg-rychlewski** [comment]
I remember investigating this before. It's very very tough to make the atoms work. For reference, we went with a warning in the docs last year when it was brought up: https://github.com/elixir-ecto/ecto/pull/4248

**Comment by ruslandoga** [comment]
The link to this warning was marked as the solution so I guess it's good enough :)

**Comment by greg-rychlewski** [comment]
if you wanted you could still look into it. particularly the angle Jose mentioned, as it's probably a bit more doable. but just wanted to give a heads up it's not as simple as it first appears

**Comment by ruslandoga** [comment]
OK! I'll try adding an error on type and column count mismatches in combinations wrt to the parent query.

**Comment by greg-rychlewski** [comment]
I may misunderstand the original issue. But I think even if the counts are the same you can still have problems. For example if both use atoms and they are different.

**Comment by greg-rychlewski** [comment]
Oh nm the issue is about string vs atom. So counts should be good.
