### ISSUE TITLE
wrong(?) `unknown_binding` warnings when upgrading to Ecto 3.12

### ISSUE THREAD

**Issue by Miradorn** [elixir-ecto/ecto#4547]
### Elixir version

Elixir 1.17.2 (compiled with Erlang/OTP 26)

### Database and Version

postgres 14.9

### Ecto Versions

3.12.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.19.2

### Current behavior

I'm trying to update from Ecto 3.11.2 to 3.12.4 and suddenly some of our queries can no longer be compiled with the warning `invalid query has specified more bindings than bindings available in `where` (look for `unknown_binding!` in the printed query below) in query`, but the query itself doesn't have this warning and it does look correct to me (and it did work before the update :D). Here is the query logged by the error (with the names of stuff anonymized):

```
from e0 in MySchema1,
           as: :my_schema_1,
           join: p1 in assoc(e0, :my_schema_2),
           as: : my_schema_2,
           where: my_schema_1.field_1 == ^53091,
           where: exists(
           subquery(
             #Ecto.Query<from e0 in MySchema3, where: e0.field_1 == parent_as(:my_schema_1).id, where: parent_as(:my_schema_2).field_2 not in ^["X"] and e0.field_2 >= ^~D[2024-11-11], or_where: e0.field_3 == parent_as(:my_schema_1).id and
           parent_as(: my_schema_2).field_3 == ^"Y" and e0.end_date >= ^~D[2024-10-11], select: 1>
           )
         ),
           where: p1.field_4 != :xyz,
           select: e0
```

I'm not sure wether this is a bug or a change in 3.12 is just surfacing an error by us when creating the query.

If you need any more information, please let me know.

❤️ Thanks!

### Expected behavior

The query should probably still compile and work as before

**Comment by josevalim** [comment]
Hi @Miradorn, I think there is no `unknown_binding!` in the query you pasted? Can you please try to provide a snippet that reproduces the issue, rather than the printed query? You can probably do it by using "strings" in from, such as `from s in "schema"`, just remember to do `select: s.something`.

**Comment by Miradorn** [comment]
>  I think there is no unknown_binding! in the query you pasted?

Exactly, that's my main problem in understanding what goes wrong. all bindings seem to be good 🙈 
I'll try to create a reproduction.

**Comment by Miradorn** [comment]
ok, here we go:

```
defmodule EctoTest.Stuff do
  import Ecto.Query

  def da_query do
    base_query =
      from ef in "ef",
        where: ef.e_id == parent_as(:e).id,
        where:
          parent_as(:p).e_type not in ^["gp"] and
            ef.end_date >= ^~D[2023-05-02],
        select: 1

    subquery =
      Enum.reduce(%{"gp" => ~D[2023-04-02], "c" => ~D[2023-01-02]}, base_query, fn {type, date},
                                                                                   acc ->
        or_where(
          acc,
          [ef],
          ef.e_id == parent_as(:e).id and
            parent_as(:p).etype == ^type and ef.end_date >= ^date
        )
      end)

    query = from(e in "e",
      as: :e,
      join: p in "p",
      on: e.p_id == p.id,
      as: :p,
      where: e.c_id == ^1,
      where: exists(subquery),
      select: e.id
    )

    EctoTest.Repo.all(query)
  end
end
```

 leads to the error when doing `EctoTest.Stuff.da_query()` and I don't see an obvious problem with the query at least? 😕

**Comment by greg-rychlewski** [comment]
I can reproduce and know where the issue is. But may take some time to find a fix. In case anyone else can do it faster you can do it with this:

```elixir
@tag :issue
  test "issue" do
    base_query =
      from ef in "ef",
        where: ^1 == parent_as(:e).id,
        select: 1

    query = from(e in "e",
      as: :e,
      join: p in "p",
      as: :p,
      on: e.p_id == p.id,
      where: e.c_id == ^1,
      where: exists(base_query),
      select: e.id
    )

    normalize(query)
  end
```

The conditions you need:

1. You have a subquery inside a `:where` (maybe inside other things, but this one works to trigger it)
2. The subquery must cast a query parameter to a type from a field specified as `parent_as`/`as`

It manifests as `query.sources` being `nil` here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/planner.ex#L2280

Which is called from `cast_param` here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/planner.ex#L1135 (it goes cast_param -> field_type -> type -> get_source).

Git bisect shows it happend here: https://github.com/elixir-ecto/ecto/commit/3ebd13840f8b431fc96917ce1be9946a90a287d9

**Comment by Miradorn** [comment]
thanks a lot for the rapid fix ❤️ 
Any plans on cutting a release soon-ish including it?
