### ISSUE TITLE
v3.12.5 tag missing from GitHub

### ISSUE THREAD

**Issue by jswanner** [elixir-ecto/ecto#4556]
### Elixir version

n/a

### Database and Version

n/a

### Ecto Versions

3.12.5

### Database Adapter and Versions (postgrex, myxql, etc)

n/a

### Current behavior

Visiting https://github.com/elixir-ecto/ecto/tree/v3.12.5 displays a 404 page, which means all "View Source" links for https://hexdocs.pm/ecto/3.12.5/Ecto.html lead to 404 page.

### Expected behavior

Should see code when visiting https://github.com/elixir-ecto/ecto/tree/v3.12.5

**Comment by wojtekmach** [comment]
Thanks for the report, done!
