### ISSUE TITLE
Bug on documentation, lack of other mix tasks

### ISSUE THREAD

**Issue by maikelthedev** [elixir-ecto/ecto#4557]
### Elixir version

n/a

### Database and Version

n/a

### Ecto Versions

latest

### Database Adapter and Versions (postgrex, myxql, etc)

n/a

### Current behavior

In the Ecto documentation there's no mention of ecto.setup, nor ecto.rollback nor ecto.reset and others. 

### Expected behavior

Description on the MIX TASKS sections of what each one of these does.

**Comment by josevalim** [comment]
The tasks are in the ecto_sql repo: https://hexdocs.pm/ecto_sql/

Although the Ecto.setup one in particular is defined as part of your mix.exs. We should probably name that after your app itself, to avoid confusion like this. I will submit a PR.

**Comment by josevalim** [comment]
Closing this, it has been addressed. There are plans for cross-package search soon, so that should address the discoverability part too.

**Comment by maikelthedev** [comment]
Thank you
